Repository SumoLogic/sumologic-documentation, pull requests merged in 2022-10, with the labels that each got.

#398 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#400 9/30/22 Traces release
  docs/apm/traces/working-with-tracing-data/search-query-language-support-for-traces.md
  docs/releasenotes/service.md
Labels: cla-signed

#401 link fixes
  docs/alerts/monitors/index.md
  docs/dashboards-new/explore-view.md
  docs/integrations/containers-orchestration/kubernetes.md
  docs/releasenotes/collector.md
  docusaurus.config.js
  sidebars.ts
Labels: cla-signed

#397 Route 404 to homepage
  cid-redirects.json
  docusaurus.config.js
Labels: cla-signed

#402 Route 404 to home
  src/theme/NotFound.js
Labels: cla-signed

#300 production.yml: changed Cloudfront URL to help-opensource.sumologic.com
  .github/workflows/production.yml
Labels: doc:site tech, cla-signed

#404 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#403 Search operator SEO
  docs/search/search-query-language/field-expressions.md
  docs/search/search-query-language/index.md
  docs/search/search-query-language/operators.md
  docs/search/search-query-language/parse-operators/index.md
Labels: cla-signed

#405 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#406 app components solution doc
  docs/observability/app-components.md
  docs/observability/diagnose-issues.md
  sidebars.ts
Labels: cla-signed

#407 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#408 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#409 Link fixes
  docs/dashboards/about.md
  docs/get-started/library.md
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/cloudfront.md
  docs/integrations/amazon-aws/cloudtrail.md
  docs/integrations/amazon-aws/elastic-load-balancer-app.md
  docs/integrations/amazon-aws/elastic-load-balancing-classic.md
  docs/integrations/amazon-aws/s3-audit.md
  docs/integrations/amazon-aws/ses.md
  docs/manage/data-forwarding/manage.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-sources.md
  docs/send-data/hosted-collectors/amazon-aws/configure-your-aws-source-cloudformation.md
  sidebars.ts
Labels: cla-signed

#410 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#411 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#412 ci: deploy to production on pushes to main
  .github/workflows/production.yml
Labels: cla-signed

#414 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#415 Update collector.md
  docs/releasenotes/collector.md
Labels: cla-signed

#416 Update iis-search-examples.md
  docs/search/search-cheat-sheets/iis-search-examples.md
Labels: cla-signed

#417 Update hash-rules.md
  docs/send-data/collection/processing-rules/hash-rules.md
Labels: cla-signed

#418 Update service.md
  docs/releasenotes/service.md
Labels: cla-signed

#420 Update hash-rules.md
  docs/send-data/collection/processing-rules/hash-rules.md
Labels: cla-signed

#421 Update service.md
  docs/releasenotes/service.md
Labels: cla-signed

#419 Update iis-search-examples.md
  docs/search/search-cheat-sheets/iis-search-examples.md
Labels: cla-signed

#422 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#423 Update service.md
  docs/releasenotes/service.md
Labels: cla-signed

#424 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#425 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#426 Update iis-search-examples.md
  docs/search/search-cheat-sheets/iis-search-examples.md
Labels: cla-signed

#427 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#428 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#429 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#430 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#431 search operator cheat
  docs/search/search-cheat-sheets/log-operators.md
Labels: cla-signed

#432 Update docusaurus.config.js
  docusaurus.config.js
Labels: cla-signed

#433 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#435 rules syntax, RUM link
  docs/apm/apm.md
  docs/cse/rules/cse-rules-syntax.md
  docs/integrations/sumo-apps/cse.md
Labels: cla-signed

#434 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#436 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#439 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#440 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#441 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#442 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#443 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#445 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#438 Update cse.md
  docs/integrations/sumo-apps/cse.md
Labels: cla-signed

#449 Rel notes and cse
  docs/cse/integrations/integrate-cse-with-taxii-feed.md
  docs/releasenotes/collector.md
  static/img/cse/add-new-source.png
Labels: cla-signed

#450 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#437 Update logexplain.md
  docs/search/behavior-insights/logexplain.md
Labels: cla-signed

#451 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#453 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#452 eli issues
  docs/cse/administration/manage-custom-insight-resolutions.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/search/search-cheat-sheets/general-search-examples.md
  static/img/cse/action-icon-entity.png
  static/img/cse/create-entity-group-values.png
  static/img/cse/resolutions-link.png
Labels: cla-signed

#454 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#456 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#457 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#458 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#461 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#462 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#464 Announcement bar - wording, formatting, hyperlinking
  docusaurus.config.js
Labels: cla-signed

#463 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#465 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#466 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#467 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#473 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#474 Update .clabot
  .clabot
Labels: cla-signed

#476 replace link: log categories for log schemas
  docs/send-data/collect-from-other-data-sources/azure-monitoring/index.md
Labels: cla-signed

#471 Fixed typo. added i to config in step 6
  docs/send-data/installed-collectors/collector-installation-reference/add-collector-linux-machine-image.md
Labels: cla-signed

#480 Update index.md
  docs/search/index.md
Labels: cla-signed

#484 482-fix-link-in-observabilityawsquickstart
  docs/observability/aws/quickstart.md
Labels: cla-signed

#485 Fix formatting in /search/search-query-language/operators#save
  docs/search/search-query-language/operators.md
  sidebars.ts
Labels: cla-signed

#486 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#490 CID redirects
  cid-redirects.json
Labels: cla-signed

#489 added new contributor
  .clabot
Labels: cla-signed

#488 Get rid of unwanted escaping
  docs/metrics/metric-queries-alerts/operators.md
Labels: cla-signed

#494 New contributor
  .clabot
Labels: cla-signed

#497 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#500 Prod URL change
  .github/workflows/production.yml
Labels: cla-signed

#491 Update amazon-cloudwatch-source-metrics.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-cloudwatch-source-metrics.md
Labels: cla-signed

#501 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-signed

#502 clabot link and seo improvements
  .clabot
  cid-redirects.json
  docs/search/search-cheat-sheets/general-search-examples.md
  docs/search/search-query-language/field-expressions.md
  docs/search/search-query-language/math-expressions.md
  docs/search/search-query-language/transaction-analytics/flow-diagrams.md
  src/css/sumo.scss
Labels: cla-signed

#503 Link fixes
  docs/api/getting-started.md
  docs/contributing/index.md
Labels: cla-signed

#509 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#510 Update .clabot
  .clabot
Labels: cla-signed

#495 Update cloud-siem.md
  docs/releasenotes/cloud-siem.md
Labels: cla-signed

#505 Update cid 5427
  cid-redirects.json
Labels: cla-signed

#511 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#492 Update cloud-siem.md
  docs/releasenotes/cloud-siem.md
Labels: cla-signed

#507 Fix search styling
  docusaurus.config.js
  src/css/sitesearch360.scss
Labels: cla-signed

#515 data forwarding
  docs/manage/data-forwarding/amazon-s3-bucket.md
Labels: cla-signed

#516 Custom inventory source
  docs/cse/administration/custom-inventory-sources.md
  docs/manage/data-forwarding/amazon-s3-bucket.md
  docs/manage/data-forwarding/installed-collectors.md
  sidebars.ts
  static/img/cse/add-source-link.png
  static/img/cse/connections.png
  static/img/cse/create-webhook.png
  static/img/cse/select-source.png
  static/img/data-forwarding/bad-cred.png
  static/img/data-forwarding/create-S3-destination.png
  static/img/data-forwarding/data-forwarding-icon-message.png
  static/img/data-forwarding/data-forwarding-status-icons.png
  static/img/data-forwarding/enable-option.png
  static/img/data-forwarding/specifiy-destination.png
Labels: cla-signed

#517 add contributor
  .clabot
Labels: cla-signed

#508 ci: preserve Webpack cache
  .github/workflows/build_and_deploy.yml
  .github/workflows/pr.yml
Labels: cla-signed

#519 git issues and DF rel note
  docs/cse/ingestion/sumo-logic-ingest-mapping.md
  docs/metrics/logs-to-metrics.md
  docs/releasenotes/service.md
  static/img/metrics/mets-dims.png
Labels: cla-signed

#518 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#520 404 notfound.js redesign
  docusaurus.config.js
  src/css/sumo.scss
  src/theme/NotFound.js
Labels: cla-signed

#521 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#523 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#514 Update zscaler-private-access.md
  docs/integrations/security-threat-detection/zscaler-private-access.md
Labels: cla-signed

#524 new ss360
  docusaurus.config.js
Labels: cla-signed, do-not-merge

#525 Revert "new ss360"
  docusaurus.config.js
Labels: cla-signed

#526 tags test
  docs/search/search-query-language/operators.md
Labels: cla-signed

#527 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#528 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#530 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#531 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#533 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#532 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#534 math expressions, agg operators
  cid-redirects.json
  docs/search/search-query-language/field-expressions.md
  docs/search/search-query-language/group-aggregate-operators.md
  docs/search/search-query-language/group-aggregate-operators/avg.md
  docs/search/search-query-language/group-aggregate-operators/count-count-distinct-and-count-frequent.md
  docs/search/search-query-language/group-aggregate-operators/first-last.md
  docs/search/search-query-language/group-aggregate-operators/index.md
  docs/search/search-query-language/group-aggregate-operators/median.md
  docs/search/search-query-language/group-aggregate-operators/min-max.md
  docs/search/search-query-language/group-aggregate-operators/most-recent-least-recent.md
  docs/search/search-query-language/group-aggregate-operators/pct-percentile.md
  docs/search/search-query-language/group-aggregate-operators/pct-sampling.md
  docs/search/search-query-language/group-aggregate-operators/stddev.md
  docs/search/search-query-language/group-aggregate-operators/sum.md
  docs/search/search-query-language/group-aggregate-operators/values.md
  docs/search/search-query-language/math-expressions.md
  docs/search/search-query-language/math-expressions/abs.md
  docs/search/search-query-language/math-expressions/acos.md
  docs/search/search-query-language/math-expressions/asin.md
  docs/search/search-query-language/math-expressions/atan.md
  docs/search/search-query-language/math-expressions/atan2.md
  docs/search/search-query-language/math-expressions/cbrt.md
  docs/search/search-query-language/math-expressions/ceil.md
  docs/search/search-query-language/math-expressions/cos.md
  docs/search/search-query-language/math-expressions/cosh.md
  docs/search/search-query-language/math-expressions/exp.md
  docs/search/search-query-language/math-expressions/expm1.md
  docs/search/search-query-language/math-expressions/floor.md
  docs/search/search-query-language/math-expressions/hypot.md
  docs/search/search-query-language/math-expressions/index.md
  docs/search/search-query-language/math-expressions/isnan-isinfinity.md
  docs/search/search-query-language/math-expressions/log.md
  docs/search/search-query-language/math-expressions/log10.md
  docs/search/search-query-language/math-expressions/log1p.md
  docs/search/search-query-language/math-expressions/round.md
  docs/search/search-query-language/math-expressions/sin.md
  docs/search/search-query-language/math-expressions/sinh.md
  docs/search/search-query-language/math-expressions/sqrt.md
  docs/search/search-query-language/math-expressions/tan.md
  docs/search/search-query-language/math-expressions/tanh.md
  docs/search/search-query-language/math-expressions/todegrees.md
  docs/search/search-query-language/math-expressions/toradians.md
  docs/search/search-query-language/search-operators/index.md
  sidebars.ts
Labels: cla-signed

#536 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#538 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#541 table formatting
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-inventory-source.md
Labels: cla-signed

#540 Operators, sidebars, formatting
  .clabot
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/metrics/metrics-operators/accum.md
  docs/metrics/metrics-operators/bottomk.md
  docs/search/search-query-language/group-aggregate-operators/avg.md
  docs/search/search-query-language/group-aggregate-operators/first-last.md
  docs/search/search-query-language/group-aggregate-operators/median.md
  docs/search/search-query-language/group-aggregate-operators/min-max.md
  docs/search/search-query-language/group-aggregate-operators/most-recent-least-recent.md
  docs/search/search-query-language/group-aggregate-operators/pct-percentile.md
  docs/search/search-query-language/group-aggregate-operators/pct-sampling.md
  docs/search/search-query-language/group-aggregate-operators/stddev.md
  docs/search/search-query-language/group-aggregate-operators/sum.md
  docs/search/search-query-language/group-aggregate-operators/values.md
  docs/search/search-query-language/math-expressions/sqrt.md
  docs/search/search-query-language/math-expressions/tan.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
  sidebars.ts
Labels: cla-signed

#539 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#542 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#543 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#544 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#546 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#547 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#548 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#549 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#550 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#551 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#552 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#553 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#554 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#555 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#556 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#557 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#558 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#559 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#560 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#561 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#562 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#563 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#564 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#565 Fix broken timestamp expression
  docs/integrations/amazon-aws/guardduty.md
Labels: cla-signed

#567 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#566 SUMO-20385
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/search/search-query-language/parse-operators/parse-variable-patterns-using-regex.md
Labels: cla-signed

#568 migrate sdo updates
  docs/quickstart/index.md
  docs/sdo/quickstart.md
  docs/sdo/set-up-sdo/index.md
  docs/sdo/set-up-sdo/sdo-manual-configuration.md
  docs/sdo/set-up-sdo/sdo-setup-from-atlassian-marketplace.md
  docs/sdo/set-up-sdo/sdo-setup-with-terraform-script.md
  sidebars.ts
Labels: cla-signed

#569 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#571 Update aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
Labels: cla-signed

#572 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#575 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#577 Last CID redirects
  cid-redirects.json
Labels: cla-signed

#579 kafka logo fix
  docs/integrations/containers-orchestration/kafka.md
  static/img/integrations/containers-orchestration/kafka.png
Labels: cla-signed

#506 Update for v2.5.1
  docs/observability/aws/deploy-use-aws-observability/changelog.md
Labels: cla-signed

#588 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#592 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#587 Update index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
Labels: cla-signed

#596 dochub fixes
  cid-redirects.json
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
Labels: cla-signed
