Repository SumoLogic/sumologic-documentation, pull requests merged in 2022-12, with the labels that each got.

#1077 Update proofpoint-on-demand-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-on-demand-source.md
Labels: cla-signed

#1083 Catch up and typos
  blog-cse/2022-11-10-content.md
  blog-cse/2022-11-15-content.md
  blog-cse/2022-11-17-content.md
  blog-cse/2022-11-22-content.md
  blog-cse/2022-12-01-content.md
Labels: cla-signed

#1084 data tier, feature table
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
  docs/manage/partitions-data-tiers/data-tiers-faqs.md
Labels: cla-signed

#1085 met dimension required
  blog-service/2022-12-01-metrics.md
Labels: cla-signed

#1088 data forwarding audit logging
  docs/manage/data-forwarding/manage.md
  docs/manage/security/audit-event-index.md
Labels: cla-signed

#1087 C2C - Miro Update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/miro-source.md
Labels: cla-signed

#1086 Add _view to the metadata table
  docs/search/get-started-with-search/search-basics/built-in-metadata.md
Labels: cla-signed

#1089 lookup and keys
  docs/search/search-query-language/search-operators/lookup.md
Labels: cla-signed

#1091 added gmail-tracelogsapp.md
  docs/integrations/saas-cloud/gmail-tracelogs.md
  sidebars.ts
  static/img/integrations/saas-cloud/crowdstrike-analysis.png
  static/img/integrations/saas-cloud/tracelogsapp-overview.png
Labels: cla-signed

#1092 added cid
  cid-redirects.json
Labels: cla-signed

#1090 Terraform AWS ELB SLO release notes
  blog-service/2022-12-02-slo.md
Labels: cla-signed, do-not-merge

#1093 rel note, MAPPER statement
  blog-service/2022-12-02-manage.md
  docs/cse/schema/parsing-language-reference-guide.md
Labels: cla-signed

#1094 css
  src/components/Feature/index.tsx
  src/css/sidebar.scss
Labels: cla-signed

#1095 Gh isses 12 02
  docs/contributing/style-guide.md
  docs/cse/integrations/insight-enrichment-server.md
  docs/cse/schema/attributes-map-to-records.md
  docs/metrics/metrics-operators/index.md
  static/files/Metric-Cheat-Sheet.pdf
Labels: cla-signed

#1096 Update write-aggregation-rule.md
  docs/cse/rules/write-aggregation-rule.md
Labels: cla-signed

#1098 funnel chart topic and rel note
  blog-service/2022-12-05-metrics.md
  docs/metrics/metrics-queries/funnel-chart.md
  sidebars.ts
  static/img/metrics/funnel-chart.png
Labels: cla-signed

#1099 Google Workspace - rm broken anchors and cleaned up section
  docs/integrations/google/workspace/collect-logs-legacy.md
Labels: cla-signed

#1100 Update pagerduty-v3.md
  docs/integrations/saas-cloud/pagerduty-v3.md
Labels: cla-signed

#1101 Broken DB links
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/postgresql.md
Labels: cla-signed

#968 INVS-607: Update entity types list
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
Labels: cla-signed

#1107 Cloud SOAR clarifications, alt text
  docs/cloud-soar/appendix.md
  docs/cloud-soar/architecture.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/configuration.md
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/index.md
  docs/cloud-soar/main-menu.md
  docs/cloud-soar/product-overview.md
  docs/cloud-soar/working-with-soar.md
  sidebars.ts
  static/img/cloud-soar/automation.png
  static/img/cloud-soar/cog.png
  static/img/cloud-soar/entities.png
  static/img/cloud-soar/image13.png
  static/img/cloud-soar/image15.png
  static/img/cloud-soar/image15b.png
  static/img/cloud-soar/image15c.png
  static/img/cloud-soar/image15d.png
  static/img/cloud-soar/image15e.png
  static/img/cloud-soar/image24.png
  static/img/cloud-soar/image25.png
  static/img/cloud-soar/image8.png
  static/img/cloud-soar/incidents.png
  static/img/cloud-soar/support.png
Labels: cla-signed

#1106 Remove outdated section about CSE API rate limiting
  docs/cse/administration/cse-apis.md
Labels: cla-signed

#1104 new entity types
  docs/cse/records-signals-entities-insights/create-custom-entity-type.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
Labels: cla-signed

#1108 Fixed Sumo admonition light mode
  src/theme/Admonition/index.js
Labels: cla-signed

#1115 Updated gmail icon
  docs/integrations/saas-cloud/gmail-tracelogs.md
  static/img/integrations/saas-cloud/gmail-icon.png
Labels: cla-signed

#1117 CON-1107 C2C Qualys VMDR
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
  sidebars.ts
  static/img/send-data/qualys-config-collection-selection.png
  static/img/send-data/qualys-config-main.png
  static/img/send-data/qualys-icon.png
Labels: cla-signed

#1102 Webhooks/connections refactor
  docs/manage/connections-integrations/heroku.md
  docs/manage/connections-integrations/index.md
  docs/manage/connections-integrations/jfrog-artifactory.md
  docs/manage/connections-integrations/servicenow/launch-investigations.md
  docs/manage/connections-integrations/servicenow/set-up-connections.md
  docs/manage/connections-integrations/webhook-connections/audit-index.md
  docs/manage/connections-integrations/webhook-connections/cloud-soar.md
  docs/manage/connections-integrations/webhook-connections/datadog.md
  docs/manage/connections-integrations/webhook-connections/hipchat.md
  docs/manage/connections-integrations/webhook-connections/index.md
  docs/manage/connections-integrations/webhook-connections/jira-cloud.md
  docs/manage/connections-integrations/webhook-connections/jira-server.md
  docs/manage/connections-integrations/webhook-connections/jira-service-desk.md
  docs/manage/connections-integrations/webhook-connections/microsoft-azure-functions.md
  docs/manage/connections-integrations/webhook-connections/microsoft-teams.md
  docs/manage/connections-integrations/webhook-connections/new-relic.md
  docs/manage/connections-integrations/webhook-connections/opsgenie-legacy.md
  docs/manage/connections-integrations/webhook-connections/opsgenie.md
  docs/manage/connections-integrations/webhook-connections/pagerduty.md
  docs/manage/connections-integrations/webhook-connections/schedule-searches-webhook-connections.md
  docs/manage/connections-integrations/webhook-connections/set-up-webhook-connections.md
  docs/manage/connections-integrations/webhook-connections/slack.md
  docusaurus.config.js
  sidebars.ts
  static/img/connection-and-integration/connections.png
Labels: cla-signed

#1120 style guide and word list edits
  docs/contributing/style-guide.md
  docs/contributing/word-list.md
Labels: cla-signed

#1119 github issue fixes
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/search/search-query-language/search-operators/join.md
  docs/search/search-query-language/search-operators/querytimerange.md
  docs/send-data/collection/processing-rules/mask-rules.md
  sidebars.ts
Labels: cla-signed

#1121 timeslice join slice, broken image link in entity doc
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/search/search-query-language/search-operators/timeslice-join.md
  sidebars.ts
Labels: cla-signed

#1122 Style guide fixes
  docs/contributing/glossary.md
  docs/contributing/style-guide.md
  docs/contributing/word-list.md
  sidebars.ts
  static/files/UX-Sumo-Style.pdf
Labels: cla-signed

#1124 rule pages and insight enrich fixes
  docs/cse/integrations/insight-enrichment-server.md
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-chain-rule.md
  docs/cse/rules/write-match-rule.md
  docs/cse/rules/write-threshold-rule.md
Labels: cla-signed

#1125 Storylane UI tour for hackathon
  docs/hackathon/aws-lambda.md
  docs/hackathon/awso-drilldown.md
  docs/hackathon/cse.md
  docs/hackathon/dashboards.md
  docs/hackathon/get-started.md
  docs/hackathon/index.md
  docs/hackathon/schedule-search.md
  sidebars.ts
  src/css/sumo.scss
  static/storylane.html
  static/styles.css
Labels: cla-signed

#1123 CON-1107 Reduce image sizes
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
Labels: cla-signed

#1128 Descriptions missing
  docs/manage/security/2-step-verification-admins.md
  docs/manage/security/2-step-verification-users.md
  docs/manage/security/about-2-step-verification.md
  docs/manage/security/audit-event-index.md
  docs/manage/security/audit-index.md
  docs/manage/security/create-allowlist-ip-cidr-addresses.md
  docs/manage/security/data-access-level-shared-dashboards.md
  docs/manage/security/enable-support-account.md
  docs/manage/security/index.md
  docs/manage/security/installation-tokens.md
  docs/manage/security/log-search-audit-index.md
  docs/manage/security/saml/index.md
  docs/manage/security/saml/integrate-aws-sso.md
  docs/manage/security/saml/integrate-google-iam-service.md
  docs/manage/security/saml/integrate-onelogin.md
  docs/manage/security/saml/integrate-sumo-logic-with-okta.md
  docs/manage/security/saml/integrate-sumo-with-azure-ad.md
  docs/manage/security/saml/integrate-with-bitium.md
  docs/manage/security/saml/manage-permissions-with-adfs.md
  docs/manage/security/saml/set-up-adfs-authenticate-users.md
  docs/manage/security/saml/set-up-saml.md
  docs/manage/security/saml/view-saml-debug-information.md
  docs/manage/security/search-audit-index.md
  docs/manage/security/set-limit-user-concurrent-sessions.md
  docs/manage/security/set-max-web-session-timeout.md
  docs/manage/security/set-password-policy.md
Labels: cla-signed

#1129 line 80: the value was wrong
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
Labels: cla-signed

#1133 ps1 link tests
  docs/integrations/microsoft-azure/active-directory-legacyx.md
Labels: cla-signed

#1135 Revert "ps1 link tests"
  docs/integrations/microsoft-azure/active-directory-legacyx.md
Labels: cla-signed

#1136 Create 2022-12-08-content.md
  blog-cse/2022-12-08-content.md
Labels: cla-signed

#1132 Hackathon
  community/aws/aws-lambda.md
  community/aws/awso-drilldown.md
  community/get-started/setup.md
  community/kubernetes/schedule-search.md
  community/security/cse.md
  community/tracing/dashboards.md
  docs/apm/real-user-monitoring.md
  docs/hackathon/get-started.md
  docs/hackathon/index.md
  docusaurus.config.js
  sidebars.ts
  sidebarsCommunity.js
  src/css/sumo.scss
Labels: cla-signed

#1137 Active Dir legacy ps1
  docs/integrations/microsoft-azure/active-directory-legacy.md
Labels: cla-signed

#1140 .ps1 windows legacy
  docs/integrations/microsoft-azure/active-directory-legacy.md
Labels: cla-signed

#1138 cid 210642 link update
  cid-redirects.json
Labels: cla-signed

#1134 formatting n images fixes
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-tracelogs.md
  sidebars.ts
  static/img/send-data/ms-exchange-api-perm-step-1.png
  static/img/send-data/ms-exchange-api-perm-step-10-a.png
  static/img/send-data/ms-exchange-api-perm-step-10-b.png
  static/img/send-data/ms-exchange-api-perm-step-11.png
  static/img/send-data/ms-exchange-api-perm-step-2.png
  static/img/send-data/ms-exchange-api-perm-step-3.png
  static/img/send-data/ms-exchange-api-perm-step-4.png
  static/img/send-data/ms-exchange-api-perm-step-5.png
  static/img/send-data/ms-exchange-api-perm-step-6.png
  static/img/send-data/ms-exchange-api-perm-step-7.png
  static/img/send-data/ms-exchange-api-perm-step-8.png
  static/img/send-data/ms-exchange-api-perm-step-9.png
  static/img/send-data/ms-exchange-app-reg-step-2.png
  static/img/send-data/ms-exchange-app-reg-step-3.png
  static/img/send-data/ms-exchange-app-reg-step-4.png
  static/img/send-data/ms-exchange-app-reg-step-5.png
  static/img/send-data/ms-exchange-app-reg-step-6.png
  static/img/send-data/ms-exchange-azure-roles-step-1.png
  static/img/send-data/ms-exchange-azure-roles-step-2.png
  static/img/send-data/ms-exchange-azure-roles-step-3.png
  static/img/send-data/ms-exchange-azure-roles-step-4.png
  static/img/send-data/ms-exchange-azure-roles-step-5.png
  static/img/send-data/ms-exchange-azure-roles-step-6.png
  static/img/send-data/ms-exchange-azure-roles-step-7.png
  static/img/send-data/ms-exchange-azure-roles-step-8.png
  static/img/send-data/ms-exchange-azure-roles-step-9.png
  static/img/send-data/ms-exchange-client-secret-step-1.png
  static/img/send-data/ms-exchange-client-secret-step-2.png
  static/img/send-data/ms-exchange-client-secret-step-3.png
  static/img/send-data/ms-exchange-icon.png
  static/img/send-data/ms-exchange-schema-ui.png
Labels: cla-signed

#1144 CON-1262 Adding CID
  cid-redirects.json
Labels: cla-signed

#1145 ingest doc fixes
  docs/cse/ingestion/cisco-asa.md
  docs/cse/ingestion/cisco-meraki.md
  docs/cse/ingestion/corelight-zeek.md
  docs/cse/ingestion/fortigate-firewall.md
  docs/cse/ingestion/g-suite-alert-center.md
  docs/cse/ingestion/google-g-suite-apps-audit.md
  docs/cse/ingestion/kemp-loadmaster.md
  docs/cse/ingestion/microsoft-audit-office.md
  docs/cse/ingestion/microsoft-azure-activity-log.md
  docs/cse/ingestion/microsoft-windows.md
  docs/cse/ingestion/nginx-access-logs.md
  docs/cse/ingestion/okta.md
  docs/cse/ingestion/onelogin.md
  docs/cse/ingestion/osquery.md
  docs/cse/ingestion/palo-alto-firewall.md
  docs/cse/ingestion/signal-sciences-waf.md
  docs/cse/ingestion/symantec-proxy-secure-gateway-blue-coat-proxy.md
  docs/cse/ingestion/symantec-proxy-secure-gateway.md
  docs/cse/ingestion/zscaler-nss.md
  docs/cse/ingestion/zscaler-private-access.md
Labels: cla-signed

#1146 Fixed some formatting, rm duplicate text
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/index.md
Labels: cla-signed

#1142 Update create-document.md
  docs/contributing/create-document.md
Labels: cla-signed

#1148 Storylane test
  community/platform-capabilities/create-monitor.md
  community/platform-capabilities/dashboards.md
  sidebarsCommunity.js
Labels: cla-signed

#1149 Google translate
  docs/hello.md
  docusaurus.config.js
  src/helper/google-translate.js
  src/theme/NavbarItem/HtmlNavbarItem.tsx
  src/theme/NavbarItem/index.tsx
  static/hello.html
  static/storylane.html
Labels: cla-signed

#1143 Update microsoft-exchange-tracelogs.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-tracelogs.md
Labels: cla-signed

#1150 nav edits to make room for google translate
  docs/hello.md
  docusaurus.config.js
  src/components/NavLink/styles.css
  src/css/sumo.scss
  static/hello.html
Labels: cla-signed

#1141 Update metrics-explorer.md
  docs/metrics/metrics-queries/metrics-explorer.md
Labels: cla-signed, do-not-merge

#967 refresh landing
  src/css/sidebar.scss
  src/css/sumo.scss
  src/pages/index.module.css
  src/pages/index.tsx
  src/theme/Footer/index.tsx
Labels: cla-signed, do-not-merge

#1152 index fix
  src/pages/index.tsx
Labels: cla-signed

#1154 Update .clabot
  .clabot
Labels: cla-signed

#1153 Fixing table layout
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/duo-source.md
Labels: cla-signed

#1155 updated screenshots
  docs/integrations/amazon-aws/cloudtrail.md
  static/img/integrations/amazon-aws/cloudtrail-consolelogins.png
  static/img/integrations/amazon-aws/cloudtrail-network.png
  static/img/integrations/amazon-aws/cloudtrail-operations.png
  static/img/integrations/amazon-aws/cloudtrail-overview.png
  static/img/integrations/amazon-aws/cloudtrail-usermonitoring.png
Labels: cla-signed

#1157 Add note about V1 ingest budgets
  docs/manage/ingestion-volume/ingest-budgets/assign-collector-ingest-budget.md
Labels: cla-signed

#1130 updated-drop-down usage
  docs/contributing/word-list.md
Labels: cla-signed

#1158 AWS privatelink beta page
  docs/beta/aws-private-link.md
  static/img/beta/create-endpoint.png
  static/img/beta/create-record.png
  static/img/beta/dns-checkbox.png
  static/img/beta/endpoints.png
  static/img/beta/hosted-zone.png
  static/img/beta/image1%2B(1).png
  static/img/beta/modify-dns.png
  static/img/beta/peer-connection.png
  static/img/beta/privatelink-targetgroup.png
  static/img/beta/quickcreaterecord.png
Labels: cla-signed

#1160 Update insight-generation-process.md
  docs/cse/records-signals-entities-insights/insight-generation-process.md
Labels: cla-signed

#1163 2022-12-13 application update release notes
  blog-cse/2022-12-13-application-update.md
  docs/cse/records-signals-entities-insights/insight-generation-process.md
  static/img/release-notes/cse/Custom-Window-Size-For-Rules.png
  static/img/release-notes/cse/Entity-Notes.png
  static/img/release-notes/cse/Inventory-Favorite-Fields.png
Labels: cla-signed

#1166 Update haversine.md
  docs/search/search-query-language/search-operators/haversine.md
Labels: cla-signed

#1167 Update haversine.md
  docs/search/search-query-language/search-operators/haversine.md
Labels: cla-signed

#1168 Update 2022-07-20.md
  blog-collector/2022-07-20.md
Labels: cla-signed

#1169 Qualys app
  docs/integrations/saas-cloud/qualys-vmdr.md
  sidebars.ts
  static/img/integrations/saas-cloud/qualys-icon.png
  static/img/integrations/saas-cloud/qualys-vmdr-overview.png
  static/img/send-data/qualys-icon.png
Labels: cla-signed

#1170 updated screenshots
  docs/integrations/amazon-aws/cloudtrail.md
  static/img/integrations/amazon-aws/cloudtrail-consolelogins.png
  static/img/integrations/amazon-aws/cloudtrail-network.png
  static/img/integrations/amazon-aws/cloudtrail-operations.png
  static/img/integrations/amazon-aws/cloudtrail-overview.png
  static/img/integrations/amazon-aws/cloudtrail-usermonitoring.png
Labels: cla-signed

#1171 added-release notes
  blog-collector/2022-12-14.md
Labels: cla-signed

#1172 Create cid
  cid-redirects.json
Labels: cla-signed

#1175 Update inspector.md
  docs/integrations/amazon-aws/inspector.md
Labels: cla-signed

#1178 Update haversine.md
  docs/search/search-query-language/search-operators/haversine.md
Labels: cla-signed

#1182 updated saved and scheduled search UI
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/edit-cancel.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/scheduled-searches/generate-cse-signals.md
  docs/alerts/scheduled-searches/save-to-index.md
  docs/alerts/scheduled-searches/save-to-lookup.md
  docs/alerts/scheduled-searches/schedule-search.md
  docs/search/get-started-with-search/search-basics/save-search.md
  static/img/alerts/DataUsageBreached.png
  static/img/alerts/SaveToIndex.png
  static/img/alerts/add-more-mappings.png
  static/img/alerts/alert-type-selected.png
  static/img/alerts/edit-search.png
  static/img/alerts/options.png
  static/img/alerts/run-freq-signal-gen.png
  static/img/alerts/run-frequency-1.png
  static/img/alerts/save-as.png
  static/img/alerts/save-item-1.png
  static/img/alerts/save-item-after-run-frequency.png
  static/img/alerts/save-item.png
  static/img/alerts/save-real-time.png
  static/img/alerts/save-search.png
  static/img/alerts/schedule-this-search.png
  static/img/search/get-started-search/search-basics/save-search.png
Labels: cla-signed

#1183 Create 2022-12-14-content.md
  blog-cse/2022-12-14-content.md
Labels: cla-signed

#1185 Update windows-json-pci-compliance.md
  docs/integrations/microsoft-azure/windows-json-pci-compliance.md
Labels: cla-signed

#1174 Tracing releases trace duration
  blog-service/2022-12-14-trace-duration-chart.md
Labels: cla-signed

#1189 removed refs to cloud sensor
  cid-redirects.json
  docs/cse/ingestion/corelight-zeek.md
Labels: cla-signed

#1184 sessionize update and cloud sensor removed
  docs/cse/sensors/cloud-sensor-guide.md
  docs/search/search-query-language/search-operators/sessionize.md
  sidebars.ts
Labels: cla-signed

#1191 source name change
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
  static/img/send-data/aws-security-lake.png
Labels: cla-signed

#1192 added knowbe4c2c
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
  static/img/send-data/2022-12-15_17-33-32.png
  static/img/send-data/2022-12-15_17-33-52.png
  static/img/send-data/knowbe4-config-main.png
  static/img/send-data/knowbe4-icon.png
Labels: cla-signed

#1193 Update .clabot
  .clabot
Labels: cla-signed

#1179 Update index.md
  docs/dashboards-new/panels/index.md
Labels: cla-signed

#1177 Update view-and-investigate-traces.md
  docs/apm/traces/working-with-tracing-data/view-and-investigate-traces.md
Labels: cla-signed

#1194 K8s trace collection
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-kubernetes-environments.md
Labels: cla-signed

#1199 Review knowbe4
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
  static/img/send-data/knowbe4-icon.png
Labels: cla-signed

#1197 orb link update
  docs/sdo/set-up-sdo/sdo-manual-configuration.md
Labels: cla-signed

#1198 SUMO-0: Add an example of how to send a test trace to sumo to the HTTP traces docs
  docs/apm/traces/get-started-transaction-tracing/http-traces-source.md
Labels: cla-signed

#1196 MET-17446 MQ error/warning message doc update
  docs/metrics/metrics-queries/metric-query-error-messages.md
Labels: cla-signed

#1176 APP-2054: Update view-manage-entities.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
Labels: cla-signed

#1201 Contributing edits
  README.md
  docs/contributing/create-doc.md
  docs/contributing/create-document.md
  docs/contributing/edit-doc.md
  docs/contributing/index.md
  docs/reuse/doc-prerequisites.md
  sidebars.ts
  static/img/contributing/clabot.png
Labels: doc:update, cla-signed

#1204 removing-beta
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
  sidebars.ts
  static/img/dashboards/green tick.png
Labels: cla-signed

#1202 created community content catalog page
  docs/integrations/community-ecosystem-apps.md
  docs/integrations/partner-ecosystem-apps.md
  docs/integrations/partner-integrations.md
Labels: cla-signed

#1207 Updating log monitor query length limit
  docs/alerts/monitors/index.md
Labels: cla-signed

#1209 Aws link
  cid-redirects.json
Labels: cla-signed

#1205 MET-17986 Update to fix a few display issues
  docs/metrics/metrics-queries/metric-query-error-messages.md
Labels: cla-signed

#1210 added armis-api
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
  sidebars.ts
  static/img/send-data/armis-config-main.png
  static/img/send-data/armis-icon.png
  static/img/send-data/armis-settings.png
  static/img/send-data/create-api.png
  static/img/send-data/show-key.png
  static/img/send-data/show-secretkey.png
  static/img/send-data/view-key.png
Labels: cla-signed

#1203 Dash timerange
  docs/dashboards-new/set-custom-time-ranges.md
  static/img/dashboards-new/set-custom-time-ranges/custom-tab.png
  static/img/dashboards-new/set-custom-time-ranges/dashboard-setting-default.png
  static/img/dashboards-new/set-custom-time-ranges/dashboard-setting-modified.png
  static/img/dashboards-new/set-custom-time-ranges/recent-time-ranges.png
  static/img/dashboards-new/set-custom-time-ranges/relative-ranges.png
Labels: cla-signed

#1214 added a .pem cert
  docs/integrations/saas-cloud/acquia.md
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
Labels: cla-signed

#1212 added airtable c2c
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  sidebars.ts
  static/img/send-data/airtable-config-main.png
  static/img/send-data/airtable-icon.png
Labels: cla-signed

#1217 Documenting monitors behavior on user deactivation
  docs/manage/users-roles/users/deactivate-activate-user.md
Labels: cla-signed

#1218 added cids
  cid-redirects.json
Labels: cla-signed

#1220 additions to armis
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
Labels: cla-signed

#1223 Update armis-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
Labels: cla-signed

#1224 2022-12-21 CSE Content Release
  blog-cse/2022-12-14-content.md
  blog-cse/2022-12-21-content.md
Labels: cla-signed

#1226 links to csma apps
  docs/integrations/hosts-operating-systems/linux.md
  docs/integrations/microsoft-azure/windows-json.md
Labels: cla-signed

#1225 timerange editor
  docs/dashboards-new/set-custom-time-ranges.md
  static/img/dashboards-new/set-custom-time-ranges/set-as-dashboard-default.png
Labels: cla-signed

#1222 Update aws-guardduty.md
  docs/cse/ingestion/aws-guardduty.md
Labels: cla-signed

#1219 Removed whitespace breaking code closure
  docs/manage/security/audit-index.md
Labels: cla-signed

#1216 Release note for Circle CI
  blog-service/2022-12-22-Circle-CI.md
Labels: cla-signed

#1228 Update enterprise-search-audit.md
  docs/integrations/sumo-apps/enterprise-search-audit.md
Labels: cla-signed

#1229 Update cassandra.md
  docs/integrations/databases/cassandra.md
Labels: cla-signed

#1213 added cids
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
Labels: cla-signed

#1232 added-cid
  cid-redirects.json
Labels: cla-signed

#1231 Airtable source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  static/img/send-data/airtable-icon copy.png
  static/img/send-data/airtable-icon.png
Labels: cla-signed

#1233 Update windows.md
  docs/send-data/installed-collectors/windows.md
Labels: cla-signed

#1227 cloud-soar
  docs/cloud-soar/architecture.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/main-menu.md
  static/img/cloud-soar/cyberArk1.png
  static/img/cloud-soar/image10.png
  static/img/cloud-soar/image11.png
  static/img/cloud-soar/image120b.png
  static/img/cloud-soar/image125.png
  static/img/cloud-soar/image126.png
  static/img/cloud-soar/image127.png
  static/img/cloud-soar/image128.png
  static/img/cloud-soar/image130.png
  static/img/cloud-soar/image140.png
  static/img/cloud-soar/image141.png
  static/img/cloud-soar/image149.png
  static/img/cloud-soar/image151.png
  static/img/cloud-soar/image152.png
  static/img/cloud-soar/image153.png
  static/img/cloud-soar/image158.png
  static/img/cloud-soar/image159.png
  static/img/cloud-soar/image161.png
  static/img/cloud-soar/image162.png
  static/img/cloud-soar/image163.png
  static/img/cloud-soar/image166.png
  static/img/cloud-soar/image16b.png
  static/img/cloud-soar/image16d.png
  static/img/cloud-soar/image16e.png
  static/img/cloud-soar/image16f.png
  static/img/cloud-soar/image170.png
  static/img/cloud-soar/image188.png
  static/img/cloud-soar/image199.png
  static/img/cloud-soar/image20b.png
  static/img/cloud-soar/image22.png
  static/img/cloud-soar/image26.png
  static/img/cloud-soar/image28.png
  static/img/cloud-soar/image29.png
  static/img/cloud-soar/image33.png
  static/img/cloud-soar/image36.png
  static/img/cloud-soar/image42.png
  static/img/cloud-soar/image50.png
  static/img/cloud-soar/image51.png
  static/img/cloud-soar/image57c.png
  static/img/cloud-soar/image58.png
  static/img/cloud-soar/image62.png
  static/img/cloud-soar/image9.png
  static/img/cloud-soar/war_room.png
Labels: cla-signed, do-not-merge

#1234 Update reference-field-special-characters.md
  docs/search/get-started-with-search/search-basics/reference-field-special-characters.md
Labels: cla-signed

#1230 Update real-user-monitoring.md
  docs/apm/real-user-monitoring.md
Labels: cla-signed

#1237 SLO updates
  docs/observability/reliability-management-slo.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/observability/reliability-management-slo/dashboards.md
  docs/observability/reliability-management-slo/index.md
  docs/observability/reliability-management-slo/use-cases.md
  sidebars.ts
  static/img/observability/log-search.png
  static/img/observability/slo-create.png
  static/img/observability/slo-more-actions-kebab.png
Labels: cla-signed

#1239 added automigration
  docs/dashboards-new/migrate-new-dashboards.md
  sidebars.ts
  static/img/dashboards-new/migrate-dashboard1.png
  static/img/dashboards-new/migrate-dashboard2.png
  static/img/dashboards-new/migrate-dashboard3.png
  static/img/dashboards-new/migrate-dashboard4.png
  static/img/dashboards-new/migrate-dashboard5.png
Labels: cla-signed

#1240 Update migrate-new-dashboards.md
  docs/dashboards-new/migrate-new-dashboards.md
Labels: cla-signed

#1242 save is end of query
  docs/search/search-query-language/search-operators/save.md
Labels: cla-signed

#1243 Updated robots.txt and docusaurus.config.js for new Algolia instance
  docusaurus.config.js
  static/robots.txt
Labels: cla-signed

#1241 Update real-user-monitoring.md
  docs/apm/real-user-monitoring.md
Labels: cla-signed

#1236 RUM release note 12-29 - getOverriddenServiceName
  blog-service/2022-12-29-rum.md
  docs/apm/real-user-monitoring.md
Labels: cla-signed, hot🔥

#1251 Update sidebars.ts
  sidebars.ts
Labels: cla-signed

#1252 Update gmail-tracelogs.md
  docs/integrations/saas-cloud/gmail-tracelogs.md
Labels: cla-signed

#1238 Creating SLOs from Logs, Metrics, Monitors
  docs/observability/reliability-management-slo/create-slo.md
Labels: cla-signed

#1253 Fix rendering of algolia search in navbar
  src/css/sumo.scss
Labels: cla-signed

#1256 Minor fixes on Installing Apache Monitors section
  docs/integrations/web-servers/apache.md
Labels: cla-signed

#1257 Installing the Apache App section
  docs/integrations/web-servers/apache.md
Labels: cla-signed
