Repository SumoLogic/sumologic-documentation, pull requests merged in 2022-11, with the labels that each got.

#818 Sqs doc
  docs/integrations/amazon-aws/sqs.md
Labels: cla-signed

#821 Update .clabot
  .clabot
Labels: cla-signed

#820 Update gitlab.md
  docs/integrations/app-development/gitlab.md
Labels: cla-signed

#822 Docusaurus upgrade to 2.2
  .github/workflows/build_and_deploy.yml
  .github/workflows/pr.yml
  package.json
  yarn.lock
Labels: cla-signed

#825 Update index.tsx
  src/pages/index.tsx
Labels: cla-signed

#827 Update 2022-10-27-metric-explorer.md
  blog-service/2022-10-27-metric-explorer.md
Labels: cla-signed

#828 Update 2022-10-19-sailpoint.md
  blog-service/2022-10-19-sailpoint.md
Labels: cla-signed

#829 Fixed hyperlink - SUMO-205450
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
Labels: cla-signed

#830 Updated aws-S3-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
Labels: cla-signed

#831 Observability update
  docs/observability/aws/integrations/aws-ec2-metrics.md
Labels: cla-signed

#834 Update index.md
  docs/send-data/hosted-collectors/index.md
Labels: cla-signed

#766 google workspace app
  docs/integrations/google/workspace/collect-logs-legacy.md
  docs/integrations/google/workspace/collect-logs.md
  sidebars.ts
Labels: cla-signed

#835 Update json-parameters-installed-sources.md
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
Labels: cla-signed

#838 Fixed link to 'data-payload-considerations'
  docs/send-data/hosted-collectors/http-source/upload-logs.md
Labels: cla-signed

#843 Update insight-enrichment-server.md
  docs/cse/integrations/insight-enrichment-server.md
Labels: cla-signed

#851 Update write-aggregation-rule.md
  docs/cse/rules/write-aggregation-rule.md
Labels: cla-signed

#849 Update insight-enrichment-server.md
  docs/cse/integrations/insight-enrichment-server.md
Labels: cla-signed

#850 Update cse-ingestion-best-practices.md
  docs/cse/ingestion/cse-ingestion-best-practices.md
Labels: cla-signed

#853 Update .clabot
  .clabot
Labels: cla-signed

#858 Fixed Dashboards > Markdown redirect
  cid-redirects.json
Labels: cla-signed

#852 Release notes for 19.415-6
  blog-collector/2022-11-04.md
Labels: cla-signed

#855 Fixed broken formatting on SQL code snippet
  docs/search/search-query-language/group-aggregate-operators/sum.md
Labels: cla-signed

#859 Hosted Collectors landing pages refactor
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
  docs/send-data/hosted-collectors/configure-hosted-collector.md
  docs/send-data/hosted-collectors/index.md
  docs/send-data/installed-collectors/index.md
Labels: cla-signed

#860 Fixed anchor IDs
  docs/send-data/collection/edit-collector.md
  docs/send-data/collection/edit-source.md
  docs/send-data/collection/index.md
  docs/send-data/collection/restart-collectors.md
  docs/send-data/collection/search-collector-or-source.md
  docs/send-data/collection/set-collector-cpu-usage-target.md
  docs/send-data/collection/upgrade-collectors.md
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
  sidebars.ts
Labels: cla-signed

#861 Added redirect for API endpoints
  cid-redirects.json
Labels: cla-signed

#862 Default colorMode = light
  docusaurus.config.js
Labels: cla-signed

#863 Light mode default
  docusaurus.config.js
Labels: cla-signed

#864 Timestamp table missing data
  docs/send-data/reference-information/time-reference.md
Labels: cla-signed

#865 Fixed OpenAPI Spec 404s
  cid-redirects.json
Labels: cla-signed

#867 Added more missing links to redirects file
  blog-service/2016/12-31.md
  cid-redirects.json
  docs/send-data/collection/pause-resume-source.md
  sidebars.ts
Labels: cla-signed

#868 Added permalink RSS subscribe button to top of blog posts
  blog-collector/2022-11-04.md
  blog-cse/2022-10-06-app-content.md
  blog-cse/2022-10-27-content.md
  blog-developer/2020/12-31.md
  blog-developer/2022-10-12-welcome.md
  blog-service/2022-10-27-metric-explorer.md
  docusaurus.config.js
  static/img/release-notes/developer/Installation-Tokens.png
  static/img/release-notes/rss-blue.png
  static/img/release-notes/rss-orange.png
Labels: cla-signed

#876 Update .clabot
  .clabot
Labels: cla-signed

#873 Update the sensor locations
  docs/cse/sensors/sensor-download-locations.md
Labels: cla-signed

#880 Update .clabot
  .clabot
Labels: cla-signed

#877 Update predict.md
  docs/search/search-query-language/search-operators/predict.md
Labels: cla-signed

#878 Update infrequent-tier-search.md
  docs/manage/partitions-data-tiers/infrequent-tier-search.md
Labels: cla-signed

#875 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#871 Update use-receipt-time.md
  docs/search/get-started-with-search/build-search/use-receipt-time.md
Labels: cla-signed

#881 Update .clabot
  .clabot
Labels: cla-signed

#870 Update metrics metadata limits audit logging
  docs/metrics/manage-metric-volume/data-limits-for-metrics.md
Labels: cla-signed

#882 Update create-an-entity-group.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
Labels: cla-signed

#888 Update .clabot
  .clabot
Labels: cla-signed

#886 Add note about negative indexes in split mapping format
  docs/cse/schema/create-structured-log-mapping.md
Labels: cla-signed

#889 Formatting only
  docs/apm/traces/working-with-tracing-data/tracing-dashboards.md
  docs/observability/application-components.md
Labels: cla-signed

#890 update to match, addition of first seen
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-match-rule.md
  static/img/cse/add-more-mappings.png
  static/img/cse/between.png
  static/img/cse/dyamic-severity-field.png
  static/img/cse/equal-to.png
  static/img/cse/first-seen-rule.png
  static/img/cse/greater-than.png
  static/img/cse/if-the-value-is.png
  static/img/cse/less-than.png
  static/img/cse/not-in.png
  static/img/cse/select-rule-type.png
Labels: cla-signed

#893 legacy links
  docs/integrations/amazon-aws/ec2-host-metrics.md
  docs/integrations/containers-orchestration/kafka.md
  docs/observability/application-components.md
  docs/observability/aws/integrations/aws-ec2-metrics.md
Labels: type:bug, cla-signed

#892 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#895 Added ec2 hostmetrics.md
  docs/observability/aws/integrations/aws-ec2-host-metrics.md
  sidebars.ts
Labels: cla-signed

#897 feat: change links to sumologic-otel-collector docs to lowercase
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/databases/cassandra.md
  docs/send-data/choose-collector-source.md
Labels: cla-signed

#899 use case update
  docs/cse/rules/write-first-seen-rule.md
Labels: cla-signed

#900 Update .clabot
  .clabot
Labels: cla-signed

#902 restored earlier version
  docs/integrations/google/workspace/collect-logs.md
Labels: cla-signed

#898 List of reserved fields fixed
  docs/alerts/alert-variables.md
Labels: cla-signed

#906 new screenshot
  static/img/cse/first-seen-rule.png
Labels: cla-signed

#911 Update python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python.md
Labels: cla-signed

#912 Update .clabot
  .clabot
Labels: cla-signed

#904 Fix AWS Lamba Observability regex query
  docs/observability/aws/integrations/aws-lambda.md
Labels: cla-signed

#903 Monitors link change
  docs/alerts/monitors/index.md
Labels: cla-signed

#914 README.md logo
  README.md
  src/theme/Footer/index.tsx
  static/img/sumo-docs-readme.png
  static/img/sumo-wrestler.png
  static/img/twitter-logo.png
  static/img/youtube-logo.png
Labels: cla-signed

#916 Update README.md
  README.md
Labels: cla-signed

#917 Manage redirect in Learning course
  cid-redirects.json
Labels: cla-signed

#918 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#919 Send Data redirects
  cid-redirects.json
Labels: cla-signed

#921 Update README.md
  README.md
Labels: cla-signed

#896 Mandatory `metric` dimension
  docs/metrics/introduction/metric-formats.md
  docs/metrics/metrics-transformation-rules.md
Labels: cla-signed

#924 Formatting/style - Monitors
  docs/alerts/monitors/add-monitor.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/edit-settings.md
  sidebars.ts
Labels: cla-signed

#894 Release notes for 19.415-6
  blog-collector/2022-11-04.md
Labels: cla-signed

#922 Update collect-aws-lambda-logs-extension.md
  docs/send-data/collect-from-other-data-sources/collect-aws-lambda-logs-extension.md
Labels: cla-signed

#913 Create 2022-11-10-content.md
  blog-cse/2022-11-10-content.md
Labels: cla-signed

#929 c2c source migration links
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloud-to-cloud-source-migration.md
  sidebars.ts
  static/img/send-data/consumer-groups.png
  static/img/send-data/delete-resource-groups.png
  static/img/send-data/delete-resource-groups2.png
  static/img/send-data/diagnostic-settings.png
  static/img/send-data/resource-groups.png
  static/img/send-data/shared-access-policy.png
  static/img/send-data/stopping-dataflow.png
  static/img/send-data/stopping-dataflow2.png
Labels: cla-signed

#931 Updated Data Volume.md
  static/img/integrations/sumo-apps/Data-Volume-Metrics.png
Labels: cla-signed

#933 Azure C2C Source Doc migration fixes
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloud-to-cloud-source-migration.md
Labels: cla-signed

#934 C2C Azure Migration fixes
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-cloud-to-cloud-source-migration.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  sidebars.ts
Labels: cla-signed

#935 Adding missing canonical redirects
  cid-redirects.json
  docs/cse/administration/inventory-sources-and-data.md
  docs/dashboards-new/share-dashboard-new.md
  docs/send-data/installed-collectors/sources/windows-active-directory-inventory-source.md
  docs/send-data/use-json-configure-sources/index.md
  docs/send-data/use-json-configure-sources/json-parameters-hosted-sources.md
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
  sidebars.ts
Labels: cla-signed

#938 Contribution guide
  docs/contributing/code-of-conduct.md
  docs/contributing/create-document.md
  docs/contributing/glossary.md
  docs/contributing/index.md
  docs/contributing/markdown-cheat-sheet.md
  docs/contributing/release-notes.md
  docs/contributing/style-guide.md
  docs/contributing/templates/template-doc.md
  docs/contributing/translations.md
  sidebars.ts
Labels: cla-signed

#943 Update .clabot
  .clabot
Labels: cla-signed

#941 jmw-update-diff-syntax
  docs/search/search-query-language/search-operators/diff.md
Labels: cla-signed

#937 Canonical URL redirects from legacy docs
  cid-redirects.json
  docs/search/get-started-with-search/build-search/use-url-to-run-search.md
  docs/search/get-started-with-search/search-page/field-browser/index.md
  docs/search/get-started-with-search/search-page/field-browser/search-from-field-browser.md
  docs/search/get-started-with-search/search-page/field-browser/show-hide-fields-in-field-browser.md
  docs/search/get-started-with-search/search-page/wildcards-in-full-text-searches.md
Labels: cla-signed

#944 Search operator (backshift) link fixes
  docs/search/search-query-language/search-operators/backshift.md
Labels: cla-signed

#947 Update .clabot
  .clabot
Labels: cla-signed

#942 Update Password Policy Help
  docs/manage/security/set-password-policy.md
Labels: cla-signed

#950 Create 2022-11-15-content.md
  blog-cse/2022-11-15-content.md
Labels: cla-signed

#949 jmw-isreservedip-syntax
  docs/search/search-query-language/search-operators/isreservedip.md
Labels: cla-signed

#948 API Permissions Table Update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-azure-ad-inventory-source.md
Labels: cla-signed

#953 k8s-operator-ga
  blog-service/2022-11-15-traces.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/kubernetes.md
Labels: cla-signed

#928 add google workspace alertcent source to nav
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
  sidebars.ts
Labels: cla-signed

#954 docs(rum): cors urls fix examples
  docs/apm/real-user-monitoring.md
Labels: cla-signed

#959 updated c2c migration
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-cloud-to-cloud-source-migration.md
  static/img/send-data/consumer-groups.png
  static/img/send-data/delete-resource-groups.png
  static/img/send-data/delete-resource-groups1.png
  static/img/send-data/delete-resource-groups2.png
  static/img/send-data/diagnostic-settings.png
  static/img/send-data/diagnostic-settings1.png
  static/img/send-data/resource-groups.png
  static/img/send-data/shared-access-policy.png
  static/img/send-data/stopping-dataflow.png
  static/img/send-data/stopping-dataflow1.png
  static/img/send-data/stopping-dataflow2.png
Labels: cla-signed

#823 Homepage redesign
  docusaurus.config.js
  get-pip.py
  package.json
  src/components/Card/index.tsx
  src/components/Card/styles.module.css
  src/components/CardWithImage/index.tsx
  src/components/Feature/index.tsx
  src/components/HomeLayout/index.tsx
  src/components/HomepageFeatures.js
  src/components/HomepageFeatures.module.css
  src/components/Slider/index.tsx
  src/components/Social/index.tsx
  src/components/Social/styles.css
  src/css/sumo.scss
  src/helper/features.js
  src/pages/index.tsx
  src/pages/markdown-page.md
  src/theme/Footer/index.tsx
  src/theme/NotFound.js
  static/img/hero-secondary-background.png
  static/img/hero-secondary-graphic.png
  types.d.ts
  yarn.lock
Labels: cla-signed, do-not-merge

#961 More canonical redirects from legacy docs
  cid-redirects.json
Labels: cla-signed

#962 Site tools/packages
  .nvmrc
  package.json
  yarn.lock
Labels: cla-signed

#964 Update .clabot
  .clabot
Labels: cla-signed

#956 EC2 fixes
  docs/integrations/amazon-aws/ec2-cloudwatch-metrics.md
  docs/integrations/amazon-aws/ec2-host-metrics.md
  static/img/integrations/amazon-aws/AWS-EC2-Events-CloudTrail.png
  static/img/integrations/amazon-aws/Fields_schema.png
  static/img/integrations/amazon-aws/configure-metadata.png
Labels: cla-signed

#925 New feature: Alerts List subscriptions/preference settings
  docs/alerts/monitors/alert-response.md
  static/img/alerts/alert-list-page-bell-border.png
  static/img/alerts/alert-preferences.png
  static/img/alerts/bell-top-nav.png
  static/img/alerts/filter-active.png
  static/img/alerts/filter-subscribe.png
Labels: type:feature, cla-signed, do-not-merge

#965 Update system-requirements.md
  docs/get-started/system-requirements.md
Labels: cla-signed

#963 syslog-ng template format for Sumo is incorrect
  docs/send-data/hosted-collectors/cloud-syslog-source/syslog-ng.md
Labels: cla-signed

#970 docs(istio): update k8s endpoint
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/istio.md
Labels: cla-signed

#975 added GmailBigQuery
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-bigquery.md
  sidebars.ts
Labels: cla-signed

#976 Typo in line 15
  docs/search/search-query-language/group-aggregate-operators/first-last.md
Labels: cla-signed

#869 Env Support for APM Dashboards
  blog-service/2022-11-17-traces.md
  docs/apm/traces/working-with-tracing-data/tracing-dashboards.md
  static/img/traces/Service-Dashboards-from-traces.png
  static/img/traces/install-tracing-app.png
Labels: type:feature, cla-signed, do-not-merge

#973 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#969 Aws moose source
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
  static/img/send-data/aws-security-lake.png
  static/img/send-data/cloudtrail.png
  static/img/send-data/green-circle.png
  static/img/send-data/orange-triangle.png
  static/img/send-data/setup-subscriber.png
Labels: cla-signed

#977 Minor style fixes
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
Labels: cla-signed

#979 Revert "Minor style fixes"
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
Labels: cla-signed

#980 Minor fixes
  blog-service/2022-11-18-traces.md
Labels: cla-signed

#981 Update aws-security-data-lake-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
Labels: cla-signed

#982 Broken link and alignment
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
Labels: cla-signed

#983 Update aws-security-data-lake-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
Labels: cla-signed

#986 Canonical redirects
  cid-redirects.json
  docs/manage/security/saml/integrate-sumo-logic-with-okta.md
  docs/manage/security/saml/integrate-sumo-with-azure-ad.md
  sidebars.ts
Labels: cla-signed

#987 RUM Microlesson link updated
  docs/apm/real-user-monitoring.md
Labels: cla-signed

#978 updated-gmailbigquery
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-bigquery.md
Labels: cla-signed

#907 Beta docs
  docs/api/dashboard-data.md
  docs/integrations/amazon-aws/aws-privatelink.md
Labels: cla-signed

#991 chore: change ownership for @SumoLogic/open-source-collection-team from * to /.github/workflows/
  .github/CODEOWNERS
Labels: cla-signed

#992 updated-schematype
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs.md
  sidebars.ts
Labels: cla-signed

#996 Homepage redesign
  package.json
  src/components/Feature/index.tsx
  src/pages/index.tsx
  static/img/docs-lockup-blue.svg
  static/img/docs-lockup-white.svg
  static/img/sumo-logic-docs-blue.svg
  static/img/sumo-logic-docs.svg
  yarn.lock
Labels: cla-signed

#997 Fixing the search example under wildcards
  docs/search/search-query-language/parse-operators/parse-json-formatted-logs.md
Labels: cla-signed

#988 Alert response release notes
  blog-service/2022-11-21-alerts.md
  docs/alerts/monitors/alert-response.md
  static/img/alerts/alert-monitor-subscriptions.png
Labels: cla-signed

#1002 Dependabot loader-utils updates
  yarn.lock
Labels: cla-signed

#1003 Create aws-region-by-deployment.md
  docs/api/aws-region-by-deployment.md
  docs/api/getting-started.md
  docs/reuse/aws-region-by-sumo-deployment.md
Labels: cla-signed

#1006 md-fix
  docs/api/aws-region-by-deployment.md
  docs/api/getting-started.md
Labels: cla-signed

#1007 Update vpc-flow-logs.md
  docs/integrations/amazon-aws/vpc-flow-logs.md
Labels: cla-signed

#1008 release note for aws lambda
  blog-service/2022-11-21-apps
Labels: cla-signed

#1009 updated netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: cla-signed

#1016 netskope doc titles
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
  sidebars.ts
Labels: cla-signed

#1015 Update .clabot
  .clabot
Labels: cla-signed

#1014 Update fed ramp c2 cs docs
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-amp-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/okta-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
Labels: cla-signed

#1017 legacy redirects
  cid-redirects.json
Labels: cla-signed

#1018 legacy redirects - varnish
  cid-redirects.json
Labels: cla-signed

#1019 Legacy redirects
  cid-redirects.json
Labels: cla-signed

#993 updated fedramp sources
  blog-service/2022-08-25-collection.md
Labels: cla-signed

#1023 updated link to new orb
  docs/sdo/set-up-sdo/sdo-manual-configuration.md
Labels: cla-signed

#1021 feat(sumologic-kubernetes-collection): update external links
  blog-service/2020/12-31.md
  docs/apm/traces/working-with-tracing-data/view-and-investigate-traces.md
  docs/integrations/app-development/jmx.md
  docs/integrations/containers-orchestration/docker-enterprise-edition.md
  docs/integrations/containers-orchestration/kubernetes-control-plane.md
  docs/integrations/containers-orchestration/kubernetes.md
  docs/integrations/saas-cloud/istio.md
  docs/metrics/kubernetes-metrics.md
  docs/observability/kubernetes/index.md
  docs/observability/kubernetes/quickstart.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
Labels: cla-signed

#1033 Update collect-metrics-azure-monitor.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/collect-metrics-azure-monitor.md
Labels: cla-signed

#1036 newC2C-miro
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/miro-source.md
  sidebars.ts
  static/img/send-data/create-app.png
  static/img/send-data/create-team.png
  static/img/send-data/enable-scope.png
  static/img/send-data/get-access-token.png
  static/img/send-data/get-credentials.png
  static/img/send-data/get-token-pair.png
  static/img/send-data/install-app.png
  static/img/send-data/orange-exclamation-point.png
  static/img/send-data/your-apps1.png
Labels: cla-signed

#1037 Minor fix
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  sidebars.ts
Labels: cla-signed

#1038 Miro c2c
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/miro-source.md
Labels: cla-signed

#839 AWSEC2 Metrics - removed links
  docs/observability/aws/integrations/aws-ec2-metrics.md
Labels: cla-signed

#1035 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#1034 docs(k8sinstr): update img and propagators info
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/kubernetes.md
Labels: cla-signed, do-not-merge

#1031 AWS Cost Explorer source/app
  cid-redirects.json
  docs/integrations/amazon-aws/cost-explorer.md
  docs/reuse/aws-cost-explorer.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cost-explorer-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cost-explorer.md
  sidebars.ts
Labels: cla-signed

#1001 Update Monitor log ingestion and alerts page
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/edit-settings.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/observability/application-components.md
  docusaurus.config.js
  sidebars.ts
  static/img/monitors/monitor-actions.png
  static/img/monitors/outlier-detection-method.png
  static/img/monitors/trigger-conditions-monitor.png
Labels: cla-signed

#1044 sidebars fix
  docs/alerts/monitors/create-monitor.md
Labels: cla-signed

#1046 Revert "ci: always create review environments for PRs"
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/review.yml
Labels: cla-signed

#1040 Update index.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/index.md
Labels: cla-signed

#1041 Update autosubscribe-arn-destination.md
  docs/send-data/collect-from-other-data-sources/autosubscribe-arn-destination.md
Labels: cla-signed

#1049 Collectors hub page link fix
  docs/send-data/hosted-collectors/configure-hosted-collector.md
Labels: cla-signed

#1042 Update audit-event-index.md
  docs/manage/security/audit-event-index.md
Labels: cla-signed

#1048 removed page
  docs/send-data/hosted-collectors/amazon-aws/aws-security-data-lake-source.md
Labels: cla-signed

#804 Update metric-query-error-messages.md
  docs/metrics/metrics-queries/metric-query-error-messages.md
Labels: cla-signed, do-not-merge

#1052 C2C Source States formatting
  docs/send-data/hosted-collectors/amazon-aws/aws-cost-explorer-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/akamai-siem-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-amp-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cybereason-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dropbox-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/duo-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-azure-ad-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-azure-ad-reporting-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-identity-protection-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/okta-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/palo-alto-cortex-xdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-on-demand-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sailpoint-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sentinelone-mgmt-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sophos-central-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/symantec-web-security-service-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
Labels: cla-signed
