Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-09, with the labels that each got.

#3026 Replacing continuously for by at all times within in metrics monitor documentation
  docs/alerts/monitors/create-monitor.md
Labels: cla-signed

#3025 C2C template updated
  docs/contributing/templates/c2c-source.md
Labels: cla-signed

#3029 Clarify the save to lookup functionality
  docs/alerts/scheduled-searches/save-to-lookup.md
  docs/search/lookup-tables/manage-update-lookup-tables.md
Labels: doc:minor edit, cla-signed

#3030 Revert the "Create an Entity Group" article
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  static/img/cse/create-entity-group-inventory.png
Labels: doc:update, cla-signed

#3032 Revert "Revert the "Create an Entity Group" article"
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  static/img/cse/create-entity-group-inventory.png
Labels: cla-signed

#3033 Revert "Clarify the save to lookup functionality"
  docs/alerts/scheduled-searches/save-to-lookup.md
  docs/search/lookup-tables/manage-update-lookup-tables.md
Labels: cla-signed

#3036 Broken link fixes
  blog-service/2022/12-31.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/index.md
  docs/alerts/monitors/overview.md
  docs/apm/traces/index.md
  docs/cloud-security-analytics/introduction-to-cloud-security-analytics.md
  docs/cloud-security-analytics/threat-detection-and-investigation.md
  docs/contributing/templates/c2c-source.md
  docs/cse/administration/custom-inventory-sources.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/get-started/faq.md
  docs/get-started/help.md
  docs/integrations/account-plans.md
  docs/integrations/amazon-aws/elastic-load-balancing-classic.md
  docs/integrations/amazon-aws/sns.md
  docs/integrations/databases/mysql.md
  docs/integrations/global-intelligence/apache-tomcat.md
  docs/integrations/microsoft-azure/windows-legacy.md
  docs/integrations/pci-compliance/index.md
  docs/integrations/security-threat-detection/evident-security-platform.md
  docs/integrations/security-threat-detection/observable-networks.md
  docs/integrations/security-threat-detection/threat-intel-quick-analysis.md
  docs/integrations/security-threat-detection/vmware-carbon-black.md
  docs/manage/content-sharing/content-sharing-faq.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/metrics/index.md
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
  docs/observability/sdo/install-sdo-app-view-dashboards.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
  docs/observability/sdo/set-up-sdo/sdo-setup-with-terraform-script.md
  docs/search/get-started-with-search/build-search/keyword-search-expressions.md
  docs/search/index.md
  docs/search/search-query-language/math-expressions/index.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/troubleshoot-azure-blob-storage-log-collection.md
  docs/send-data/collect-from-other-data-sources/sumo-logic-open-source-projects.md
  docs/send-data/collection/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
  docs/send-data/hosted-collectors/google-source/index.md
Labels: cla-signed

#3037 Rerun changes for reverting the "Create an Entity Group" article
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  static/img/cse/create-entity-group-inventory.png
Labels: doc:update, cla-signed

#3038 Rerun "Clarify the save to lookup functionality"
  docs/alerts/scheduled-searches/save-to-lookup.md
  docs/search/lookup-tables/manage-update-lookup-tables.md
Labels: doc:update, cla-signed

#3041 Datadog doc cid redirect added
  cid-redirects.json
Labels: cla-signed

#2777 Abnormal Security release note
  blog-service/2023-08-06-collections.md
Labels: cla-signed, do-not-merge

#3044 Update release notes date for Abnormal C2C
  blog-service/2023-09-06-collections.md
Labels: cla-signed

#3043 LogExplain doc formatting
  docs/search/behavior-insights/logexplain.md
Labels: cla-signed

#3042 Add Azure Blob videos
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/index.md
Labels: doc:update, cla-signed

#3048 vmware script were changed. Need to change the download link for s3 p…
  docs/integrations/containers-orchestration/vmware.md
Labels: cla-signed

#3046 Update archive.md
  docs/manage/data-archiving/archive.md
Labels: cla-signed

#3050 Remove note
  docs/alerts/scheduled-searches/generate-cse-signals.md
Labels: doc:minor edit, cla-signed

#3052 Create 2023-09-07-content.md
  blog-cse/2023-09-07-content.md
Labels: cla-signed

#3051 CONN-2503 C2C Cisco Meraki - Known Timeout Issue
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
Labels: cla-signed

#3045 Metrics DPM - beta
  docs/metrics/metrics-dpm.md
  sidebars.ts
  static/img/metrics/metrics-dpm.png
Labels: doc:new, cla-signed, do-not-merge

#3055 fix: fix Otelcol install command for Linux
  docs/send-data/opentelemetry-collector/install-collector-linux.md
Labels: cla-signed

#3040 Query timer bug release note
  blog-service/2023-09-08-search.md
Labels: cla-signed, hot🔥

#3053 Fix Metrics DPM screenshot
  static/img/metrics/metrics-dpm.png
Labels: doc:minor edit, cla-signed

#3054 initial checkin for for nine new AWS specific doc-only app documentat…
  cid-redirects.json
  docs/integrations/amazon-aws/amazon-data-lifecycle-manager.md
  docs/integrations/amazon-aws/amazon-emr.md
  docs/integrations/amazon-aws/amazon-eventbridge.md
  docs/integrations/amazon-aws/amazon-gamelift.md
  docs/integrations/amazon-aws/amazon-opensearch-service.md
  docs/integrations/amazon-aws/aws-elastic-beanstalk.md
  docs/integrations/amazon-aws/aws-global-accelerator.md
  docs/integrations/amazon-aws/aws-ground-station.md
  docs/integrations/amazon-aws/aws-healthlake.md
  sidebars.ts
  static/img/integrations/amazon-aws/amazon-data-lifecycle-manager-logo.png
  static/img/integrations/amazon-aws/amazon-emr-logo.png
  static/img/integrations/amazon-aws/amazon-eventbridge-logo.png
  static/img/integrations/amazon-aws/amazon-gamelift-logo.png
  static/img/integrations/amazon-aws/amazon-opensearch-service-logo.png
  static/img/integrations/amazon-aws/aws-elastic-beanstalk-logo.png
  static/img/integrations/amazon-aws/aws-global-accelerator-logo.png
  static/img/integrations/amazon-aws/aws-ground-station-logo.png
  static/img/integrations/amazon-aws/aws-healthlake-logo.png
Labels: cla-signed

#2844 Move Automation Service from limited availability (LA) to general availability (GA)
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/automation-service/automation-service-bridge.md
  docs/cse/automation-service/automation-service-examples.md
  docs/cse/automation-service/automation-service-integration-framework.md
  docs/cse/automation-service/automation-service-integrations.md
  docs/cse/automation-service/automation-service-playbooks.md
  docs/reuse/automation-service-la-note.md
  static/img/cse/automation-service-app-central.png
Labels: doc:update, cla-signed

#2991 TRIDENT-18118 - Migrate legacy actions and enrichments
  docs/cse/administration/create-cse-actions.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/integrations/insight-enrichment-server.md
Labels: doc:new, cla-signed

#3061 Revert "Move Automation Service from limited availability (LA) to general availability (GA)"
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/automation-service/automation-service-bridge.md
  docs/cse/automation-service/automation-service-examples.md
  docs/cse/automation-service/automation-service-integration-framework.md
  docs/cse/automation-service/automation-service-integrations.md
  docs/cse/automation-service/automation-service-playbooks.md
  docs/reuse/automation-service-la-note.md
  static/img/cse/automation-service-app-central.png
Labels: cla-signed

#3062 Revert "TRIDENT-18118 - Migrate legacy actions and enrichments"
  docs/cse/administration/create-cse-actions.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/integrations/insight-enrichment-server.md
Labels: cla-signed

#3063 Re-run "Automation service GA"
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/automation-service/automation-service-bridge.md
  docs/cse/automation-service/automation-service-examples.md
  docs/cse/automation-service/automation-service-integration-framework.md
  docs/cse/automation-service/automation-service-integrations.md
  docs/cse/automation-service/automation-service-playbooks.md
  docs/reuse/automation-service-la-note.md
  static/img/cse/automation-service-app-central.png
Labels: doc:update, cla-signed

#3065 Re-run "Trident 18118 migrate to automation service"
  docs/cse/administration/create-cse-actions.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/integrations/insight-enrichment-server.md
Labels: doc:update, cla-signed

#3064 CSE Release notes 2023-09-11
  blog-cse/2023-09-11-application-update.md
  static/img/release-notes/cse/automation-service.png
Labels: cla-signed

#3049 Creating heroku app doc
  cid-redirects.json
  docs/integrations/web-servers/heroku.md
  docs/integrations/web-servers/index.md
  sidebars.ts
  static/img/integrations/web-servers/Heroku.png
  static/img/integrations/web-servers/heroku-application-errors.png
  static/img/integrations/web-servers/heroku-application.png
  static/img/integrations/web-servers/heroku-cpu-load-metrics.png
  static/img/integrations/web-servers/heroku-dyno.png
  static/img/integrations/web-servers/heroku-infrastructure-errors.png
  static/img/integrations/web-servers/heroku-memory-metrics.png
  static/img/integrations/web-servers/heroku-overview.png
Labels: cla-signed

#3056 hash-algoritham-doc-update
  docs/send-data/collection/processing-rules/hash-rules.md
  docs/send-data/use-json-configure-sources/index.md
Labels: cla-signed

#3069 proper code block used
  docs/integrations/web-servers/heroku.md
Labels: cla-signed

#3066 Update construct-search-filter-for-role.md
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
Labels: cla-signed, do-not-merge

#3072 vmware metric collection does not have the content type and protocol …
  docs/integrations/containers-orchestration/vmware.md
Labels: cla-signed

#3068 Tenable app doc
  cid-redirects.json
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/tenable.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#3071 Adding _blockid to disallow list for grouping key in monitors
  docs/alerts/monitors/alert-grouping.md
Labels: cla-signed

#3074 Update tenable.md
  docs/integrations/saas-cloud/tenable.md
Labels: cla-signed

#3059 Update Advanced Expression field description
  docs/cse/rules/write-outlier-rule.md
Labels: doc:minor edit, cla-signed

#3060 Add audit apps to the Audit and Compliance article
  docs/cloud-security-analytics/audit-and-compliance.md
Labels: doc:update, cla-signed

#3070 Add action limit explanation
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-app-central.md
  static/img/cse/automation-service-app-central.png
Labels: doc:update, cla-signed

#3078 Update knowbe4-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#3077 Tenable app release note
  blog-service/2023-09-14-tenable-apps.md
Labels: cla-signed

#3079 CONN-2491: Update salesforce documentation
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
Labels: cla-signed

#3081 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#3083 Add more videos
  docs/cse/automation-service/automation-service-app-central.md
  docs/integrations/index.md
  docs/search/get-started-with-search/index.md
Labels: doc:update, cla-signed

#3075 MET-16093 - Add note to sharing documentation
  docs/manage/content-sharing/index.md
Labels: doc:update, cla-signed

#3082 Add "Actions limit" section
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-app-central.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/automation-service/automation-service-examples.md
  docs/cse/automation-service/automation-service-integrations.md
  docs/cse/automation-service/automation-service-playbooks.md
  docs/reuse/action-limits.md
Labels: doc:new, cla-signed

#3076 fix(otelcol): fix setting `_sourceName` in logs collection examples
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#3031 TRIDENT-18400 - Update entity group for inventory
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  static/img/cse/create-entity-group-inventory.png
  static/img/cse/entity-groups-dynamic-schema-tags.png
Labels: doc:update, cla-signed

#3073 Log Message Inspector doc added
  docs/search/get-started-with-search/search-page/index.md
  docs/search/get-started-with-search/search-page/log-message-inspector.md
  sidebars.ts
  static/img/search/get-started-search/search-page/filter-selected-value.png
  static/img/search/get-started-search/search-page/log-message-inspector-approach-1.png
  static/img/search/get-started-search/search-page/log-message-inspector-approach-2.png
  static/img/search/get-started-search/search-page/log-message-inspector.png
Labels: cla-signed

#3085 Add link to Integration Framework
  docs/cloud-soar/automation.md
Labels: doc:minor edit, cla-signed

#3086 Update "Manage Organizational Settings" article
  docs/manage/manage-subscription/manage-org-settings.md
Labels: doc:minor edit, cla-signed

#3087 Update unlock-user-account.md
  docs/manage/users-roles/users/unlock-user-account.md
Labels: cla-signed

#2988 Conn 2456 normalize 1password c2c
  cid-redirects.json
  docs/contributing/style-guide.md
  docs/integrations/1password.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  package.json
  static/img/c2c/1password/example.json
  static/img/c2c/1password/example.tf
  yarn.lock
Labels: doc:update, cla-signed

#2845 zoom source doc updated
  docs/send-data/hosted-collectors/webhook-sources/zoom.md
Labels: doc:update, cla-signed

#2624 CON-1922 - Security Foundations app documentation
  blog-service/2023-09-20-apps.md
  cid-redirects.json
  docs/cloud-security-analytics/threat-detection-and-investigation.md
  docs/integrations/sumo-apps/index.md
  docs/integrations/sumo-apps/security-analytics.md
  docs/integrations/sumo-apps/security-foundations.md
  sidebars.ts
  static/img/integrations/sumo-apps/security-foundations-app-alerts-overview-dashboard.png
  static/img/integrations/sumo-apps/security-foundations-app-coverage-overview.png
  static/img/integrations/sumo-apps/security-foundations-app-entity-risk-score-dashboard.png
Labels: doc:update, cla-signed

#3089 Revert "Conn 2456 normalize 1password c2c"
  cid-redirects.json
  docs/contributing/style-guide.md
  docs/integrations/1password.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  package.json
  static/img/c2c/1password/example.json
  static/img/c2c/1password/example.tf
  yarn.lock
Labels: cla-signed, do-not-merge

#3088 Fix "Manage Organization Settings" article
  docs/manage/manage-subscription/manage-org-settings.md
Labels: doc:minor edit, cla-signed

#3090 Docusaurus update 2.4.3
  package.json
  yarn.lock
Labels: cla-signed

#3094 CSE Release Note for 9/21/23
  blog-cse/2023-09-21-application-update.md
  static/img/release-notes/cse/enitty-group-inventory-enhancements.png
Labels: cla-signed

#3093 SQL Server OT doc cid added
  cid-redirects.json
Labels: doc:update, cla-signed

#3092 modified the heroku log collection sections
  docs/integrations/web-servers/heroku.md
Labels: cla-signed

#3098 query for getting logs from cloud logging had incorrect case for logi…
  docs/integrations/google/cloud-armor.md
  docs/integrations/google/cloud-backup-for-gke.md
  docs/integrations/google/cloud-bigtable.md
  docs/integrations/google/cloud-certificate-manager.md
  docs/integrations/google/cloud-dataflow.md
  docs/integrations/google/cloud-dataproc-metastore.md
  docs/integrations/google/cloud-dataproc.md
  docs/integrations/google/cloud-datastore.md
  docs/integrations/google/cloud-datastream.md
  docs/integrations/google/cloud-deploy.md
  docs/integrations/google/cloud-firestore.md
  docs/integrations/google/cloud-logging.md
  docs/integrations/google/cloud-memorystore-for-redis.md
  docs/integrations/google/cloud-pub-sub.md
  docs/integrations/google/cloud-run.md
  docs/integrations/google/cloud-traffic-director.md
  docs/integrations/google/cloud-vertex-ai.md
Labels: cla-signed

#3101 Update mysql.md
  docs/integrations/databases/mysql.md
Labels: cla-signed

#3100 Heroku app release note
  blog-service/2023-09-22-apps.md
Labels: cla-signed

#3099 best practices section added
  docs/dashboards/advanced.md
Labels: doc:update, cla-signed

#3103 CSE content release note 9/22/2023
  blog-cse/2023-09-22-content.md
Labels: cla-signed

#3106 Update automation-service-bridge.md
  docs/cse/automation-service/automation-service-bridge.md
Labels: cla-signed

#3104 Legacy URL/404 fixes
  cid-redirects.json
  docs/observability/kubernetes/apps.md
Labels: cla-signed

#3107 Revert "CON-1922 - Security Foundations app documentation"
  blog-service/2023-09-20-apps.md
  cid-redirects.json
  docs/cloud-security-analytics/threat-detection-and-investigation.md
  docs/integrations/sumo-apps/index.md
  docs/integrations/sumo-apps/security-analytics.md
  docs/integrations/sumo-apps/security-foundations.md
  sidebars.ts
  static/img/integrations/sumo-apps/security-foundations-app-alerts-overview-dashboard.png
  static/img/integrations/sumo-apps/security-foundations-app-coverage-overview.png
  static/img/integrations/sumo-apps/security-foundations-app-entity-risk-score-dashboard.png
Labels: doc:update, cla-signed

#3105 Update cloud-soar-bridge.md
  docs/cloud-soar/cloud-soar-bridge.md
Labels: cla-signed

#3091 Remove the duplicate Amazon cloudfront doc
  cid-redirects.json
  docs/integrations/amazon-aws/amazon-cloudfront.md
  docs/integrations/amazon-aws/cloudfront.md
  docs/integrations/amazon-aws/index.md
  sidebars.ts
  static/img/integrations/amazon-aws/AWS-CloudFront-Latency-Monitoring.png
  static/img/integrations/amazon-aws/AWS-Cloudfront-Overview.png
  static/img/integrations/amazon-aws/Amazon-CloudFront-VisitorStatistics.png
  static/img/integrations/amazon-aws/Amazon-CloudFront-WebOperations.png
Labels: doc:update, cla-signed, hot🔥

#3110 Update advanced.md
  docs/dashboards/advanced.md
Labels: cla-signed

#3116 Update Cisco Vulnerability Management Icon
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-vulnerability-management-source.md
Labels: cla-signed

#3112 Add log level video
  docs/search/get-started-with-search/search-page/log-level.md
Labels: doc:minor edit, cla-signed

#3102 1password doc updated
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  static/img/c2c/1password/example.json
  static/img/c2c/1password/example.tf
Labels: doc:update, cla-signed, hot🔥

#3114 Update log-operators.md
  docs/search/search-cheat-sheets/log-operators.md
Labels: cla-signed

#3109 Export Detailed Child Usages release notes
  blog-service/2023-09-26-manage-account.md
  static/img/account/download-detailed-child-usages.png
Labels: cla-signed

#3118 Remove Gigamon ThreatInsight
  docs/cse/ingestion/products-with-log-mappings.md
  docs/integrations/partner-ecosystem-apps.md
Labels: doc:minor edit, cla-signed

#3119 Update the Network Sensor Deployment Guide to clarify firewall rules and remove references to legacy CSE servers
  docs/cse/sensors/network-sensor-deployment-guide.md
Labels: cla-signed

#3097 Cisco Vulnerability Management release note
  blog-service/2023-09-27-collections.md
Labels: doc:new, cla-signed

#3067 Service list view doc update
  docs/apm/traces/services-list-map.md
  static/img/traces/enable-alerts.png
  static/img/traces/services-list-filters.png
Labels: cla-signed, do-not-merge

#3115 Azure docs only apps changes
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-batch.md
  docs/integrations/microsoft-azure/azure-data-explorer.md
  docs/integrations/microsoft-azure/azure-data-factory.md
  docs/integrations/microsoft-azure/azure-event-grid.md
  docs/integrations/microsoft-azure/azure-event-hubs.md
  docs/integrations/microsoft-azure/azure-front-door.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-iot-hub.md
  docs/integrations/microsoft-azure/azure-key-vault.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-logic-app.md
  docs/integrations/microsoft-azure/azure-network-interface.md
  docs/integrations/microsoft-azure/azure-public-ipAddress.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/azure-synapse-analytics.md
  docs/integrations/microsoft-azure/azure-virtual-network.md
  docs/integrations/microsoft-azure/index.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-application-gateway.png
  static/img/integrations/microsoft-azure/azure-data-explorer.png
  static/img/integrations/microsoft-azure/azure-data-factory.png
  static/img/integrations/microsoft-azure/azure-event-grid.png
  static/img/integrations/microsoft-azure/azure-event-hubs.png
  static/img/integrations/microsoft-azure/azure-front-door.png
  static/img/integrations/microsoft-azure/azure-functions.png
  static/img/integrations/microsoft-azure/azure-iot-hub.png
  static/img/integrations/microsoft-azure/azure-key-vault.png
  static/img/integrations/microsoft-azure/azure-load-balancer.png
  static/img/integrations/microsoft-azure/azure-logic-app.png
  static/img/integrations/microsoft-azure/azure-network-interface.png
  static/img/integrations/microsoft-azure/azure-public-ipAddress.png
  static/img/integrations/microsoft-azure/azure-storage.png
  static/img/integrations/microsoft-azure/azure-synapse-analytics.png
  static/img/integrations/microsoft-azure/azure-virtual-network.png
Labels: doc:new, cla-signed

#3120 Update Best Practices page
  docs/dashboards/advanced.md
Labels: cla-signed

#3121 feat: http traces source to otlp http endpoint
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/istio.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/kubernetes.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby-on-rails.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-aws-environments.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-kubernetes-environments.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-other-environments.md
Labels: cla-signed

#3124 Update gcp-metrics-source.md
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
Labels: cla-signed

#3125 Update automation.md
  docs/cloud-soar/automation.md
Labels: doc:update, cla-signed

#3096 Log Message Inspector release notes
  blog-service/2023-09-28-search.md
Labels: doc:new, cla-signed

#3123 Add sukhhanda1 to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#3129 Add Cloud SIEM glossary entries
  docs/contributing/glossary.md
  docs/cse/introduction-to-cloud-siem.md
Labels: doc:update, cla-signed

#3138 Add ffelici-sumo to clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#3131 Style Guide - code blocks/inline
  docs/contributing/style-guide.md
  docs/integrations/microsoft-azure/active-directory-azure1.md
  yarn.lock
Labels: cla-signed

#3132 Mobile usability (reported by Google console)
  blog-collector/2016/12-31.md
  cid-redirects.json
  docs/integrations/security-threat-detection/keeper-security.md
  docs/integrations/security-threat-detection/netskope-legacy-collection.md
  docs/integrations/security-threat-detection/trend-micro-deep-security.md
  docs/integrations/security-threat-detection/vmware-carbon-black.md
  docs/manage/security/index.md
  docs/search/get-started-with-search/search-basics/share-link-to-search.md
Labels: cla-signed

#3128 Various /alerts updates
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/monitors/overview.md
Labels: cla-signed, do-not-merge

#3135 add the replicated ECR on cloud soar bridge network requirements
  docs/cloud-soar/cloud-soar-bridge.md
  docs/cse/automation-service/automation-service-bridge.md
Labels: cla-signed

#3127 Add playbook inputs section
  docs/cse/automation-service/automation-service-examples.md
  static/img/cse/Playbook_inputs.png
Labels: doc:new, cla-signed

#3130 Improving docs for at any time trigger condition for metrics monitors
  docs/alerts/monitors/create-monitor.md
Labels: cla-signed
