Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-08, with the labels that each got.

#2865 Align Service Release Notes titles, add usage guidance to Contributing
  blog-service/2023-01-05-search-query.md
  blog-service/2023-01-09-metrics.md
  blog-service/2023-01-17-alerts.md
  blog-service/2023-01-17-metrics.md
  blog-service/2023-01-19-traces.md
  blog-service/2023-01-24-security.md
  blog-service/2023-01-27-search-query.md
  blog-service/2023-01-30-monitor-based-slos.md
  blog-service/2023-02-06-metrics-monitors.md
  blog-service/2023-02-13-metrics-query.md
  blog-service/2023-02-13-rum.md
  blog-service/2023-02-15-slo-log-search.md
  blog-service/2023-02-17-reliability-management-slo.md
  blog-service/2023-02-24-improved-query-editor.md
  blog-service/2023-03-02-dashboard-migration.md
  blog-service/2023-03-28-otel-collector-apps.md
  blog-service/2023-04-05-scheduled-dashboard.md
  blog-service/2023-04-07-search.md
  blog-service/2023-04-07-traces.md
  blog-service/2023-04-13-apps.md
  blog-service/2023-04-13-sources.md
  blog-service/2023-04-18-apps.md
  blog-service/2023-04-19-collection.md
  blog-service/2023-04-21-apps.md
  blog-service/2023-04-25-awso.md
  blog-service/2023-04-28-apps-c2c.md
  blog-service/2023-04-28-apps.md
  blog-service/2023-04-28-dashboard.md
  blog-service/2023-04-28-slo.md
  blog-service/2023-05-04-manage-account.md
  blog-service/2023-05-12-apps-bigquery.md
  blog-service/2023-05-12-apps-http.md
  blog-service/2023-05-12-apps.md
  blog-service/2023-05-22-apps.md
  blog-service/2023-06-05-slo.md
  blog-service/2023-06-08-apps-mimecast.md
  blog-service/2023-06-08-apps-proofpoint-tap.md
  blog-service/2023-06-12-alerts.md
  blog-service/2023-06-26-metrics.md
  blog-service/2023-06-28-metrics.md
  blog-service/2023-07-05-apps.md
  blog-service/2023-07-10-log-search.md
  blog-service/2023-07-25-apps.md
  docs/contributing/style-guide.md
Labels: cla-signed

#2863 Create 2022 archive for developer release notes
  blog-developer/2022-01-18-tracing.md
  blog-developer/2022-04-25-data-forwarding.md
  blog-developer/2022-10-12-welcome.md
  blog-developer/2022/12-31.md
Labels: doc:update, cla-signed

#2869 Add manashar4 to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#2870 Add datfinesould to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#2871 Log level rn img replacement
  static/img/search/get-started-search/search-page/log-level-rn.png
Labels: cla-signed

#2873 Document when baseline is reset
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-outlier-rule.md
Labels: doc:update, cla-signed

#2872 Update palo-alto-firewall.md - Update GlobalProtect Log Output Format
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/palo-alto-firewall.md
Labels: cla-signed

#2823 Fix/google translate disappearing fix v4
  docusaurus.config.js
  src/theme/NavbarItem/HtmlNavbarItem.tsx
Labels: cla-signed

#2875 Update palo-alto-firewall.md - Update All LogTypes + Supported Versio…
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/palo-alto-firewall.md
Labels: cla-signed

#2867 Update cron-examples-reference.md
  docs/send-data/installed-collectors/sources/script-source/cron-examples-reference.md
Labels: cla-signed

#2879 Suggesting 5 min offset for scheduled searches
  docs/alerts/scheduled-searches/schedule-search.md
Labels: cla-signed

#2881 Update .clabot
  .clabot
Labels: cla-signed

#2878 Update email address description
  docs/dashboards/scheduled-report.md
Labels: cla-signed

#2880 Increase size search query editor
  docs/search/get-started-with-search/search-page/index.md
Labels: cla-signed

#2860 Enterprise audit doc update
  docs/integrations/sumo-apps/cse.md
  static/img/integrations/sumo-apps/cloud-SIEM-SOC-insights.png
  static/img/integrations/sumo-apps/cloud-SIEM-SOC-standup-overview.png
  static/img/integrations/sumo-apps/cloud-SIEM-parsing-and-mapping-troubleshooting.png
  static/img/integrations/sumo-apps/cloud-SIEM-user-telemetry.png
Labels: cla-signed, do-not-merge

#2884 Update azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
Labels: doc:update, cla-signed

#2886 Add note to the HUD article
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
Labels: doc:minor edit, cla-signed

#2877 Terraform fix
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#2889 Hyperlink updated
  docs/integrations/sumo-apps/index.md
Labels: cla-signed

#2891 updated azure blob FAQs and screenshots
  docs/integrations/microsoft-azure/arm-integration-faq.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage.md
  static/img/integrations/microsoft-azure/Azure-FAQ_BlobTaskConsumer.png
  static/img/integrations/microsoft-azure/Azure-FAQ_Event-Subscription.png
  static/img/integrations/microsoft-azure/Azure-FAQ_Increase_BatchSize.png
  static/img/integrations/microsoft-azure/Azure_New_Host_Key.png
Labels: cla-signed

#2866 Update Search URL to include parameterized search
  docs/search/get-started-with-search/build-search/use-url-to-run-search.md
Labels: doc:update, cla-signed

#2888 Add link to rule types
  docs/cse/rules/before-writing-custom-rule.md
Labels: doc:minor edit, cla-signed

#2896 Add redirect for /docs/dashboards/edit-dashboards/manage-axis
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#2897 Make update to the security landing page
  docs/security/index.md
Labels: doc:minor edit, cla-signed

#2898 CSE Content Release Note 8/3/23
  blog-cse/2023-08-03-content.md
Labels: cla-signed

#2892 Added note about host network
  docs/integrations/containers-orchestration/docker-ulm.md
Labels: cla-signed

#2831 Windows otel
  cid-redirects.json
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/linux-opentelemetry.md
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/windows-opentelemetry.md
  sidebars.ts
Labels: cla-signed

#2895 update for google cloud platform source for additional step for creat…
  docs/send-data/hosted-collectors/google-source/google-cloud-platform-source.md
Labels: cla-signed, do-not-merge

#2899 Make correction
  docs/integrations/sumo-apps/data-volume.md
Labels: doc:minor edit, cla-signed

#2543 Muting Schedules
  blog-service/2023-08-03-alerts.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/muting-schedules.md
  docs/alerts/monitors/overview.md
  docs/manage/users-roles/roles/role-capabilities.md
  sidebars.ts
  static/img/alerts/mute-sched1.png
  static/img/alerts/mute-sched2.png
Labels: cla-signed, do-not-merge

#2900 2023-08-04 content release note
  blog-cse/2023-08-04-content.md
Labels: cla-signed

#2904 Update cloud-flex-credits-accounts.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
Labels: cla-signed

#2885 Create 2023-08-07-dashboards.md
  blog-service/2023-08-07-dashboards.md
Labels: doc:new, cla-signed, do-not-merge

#2906 Fix broken image in "Insight Enrichment Server"
  docs/cse/integrations/insight-enrichment-server.md
Labels: doc:minor edit, cla-signed

#2907 Update ADFS SAML config help
  docs/manage/security/saml/set-up-adfs-authenticate-users.md
Labels: cla-signed

#2903 Clean up image coding for Cloud SIEM match list articles
  docs/cse/match-lists-suppressed-lists/create-match-list.md
  docs/cse/match-lists-suppressed-lists/custom-match-list-columns.md
  docs/cse/match-lists-suppressed-lists/match-fields-reference.md
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
  docs/cse/match-lists-suppressed-lists/suppressed-lists.md
Labels: doc:update, cla-signed

#2893 Beta Host list page added
  docs/observability/host-list-beta.md
  static/img/observability/alerts_host_list.png
  static/img/observability/column_selector.png
  static/img/observability/host_list.png
  static/img/observability/host_list2.png
  static/img/observability/navigation_OS_type.png
  static/img/observability/navigation_alert_status.png
  static/img/observability/navigation_cloud_provider.png
  static/img/observability/navigation_environment.png
  static/img/observability/navigation_group.png
  static/img/observability/navigation_host_name.png
  static/img/observability/navigation_time_range.png
Labels: cla-signed

#2909 Azure functions are not supported in monitors yet
  docs/alerts/webhook-connections/microsoft-azure-functions.md
Labels: cla-signed

#2857 SUMO-223544 Ingest Budget beta
  docs/manage/ingestion-volume/ingest-budgets/index.md
  docs/manage/ingestion-volume/ingest-budgets/minute-volume.md
  docs/reuse/budget-assignment.md
  static/img/ingestion-volume/create-ingest-budget.png
Labels: cla-signed, do-not-merge

#2911 Add "DONE GATHERING HISTOGRAM" to table
  docs/api/search-job.md
Labels: doc:minor edit, cla-signed

#2841 Contact Support button
  docusaurus.config.js
  src/css/sumo.scss
Labels: cla-signed

#2908 Add Cloud SIEM and Cloud SOAR role capabilities
  docs/cse/administration/cse-user-accounts-and-roles.md
  docs/manage/users-roles/roles/role-capabilities.md
Labels: doc:update, cla-signed

#2913 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#2914 Trident 17917 - Update standard match lists
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: doc:update, cla-signed

#2912 Clean up syntax examples
  docs/search/behavior-insights/logexplain.md
  docs/search/behavior-insights/logreduce-keys.md
  docs/search/behavior-insights/logreduce-values.md
Labels: doc:minor edit, cla-signed

#2916 Update sql-logs.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#2915 add mange-org-links-cfc2.png screenshot
  static/img/subscriptions/manage-org-links-cfc.png
Labels: cla-signed

#2918 image updated
  docs/observability/host-list-beta.md
  static/img/observability/host_list.png
Labels: cla-signed

#2921 TRIDENT-17406 - Add reference to account ID
  docs/cse/administration/create-cse-actions.md
  static/img/cse/create-action-empty.png
  static/img/cse/gear-menu-actions.png
Labels: doc:update, cla-signed

#2922 Legacy link/404 corrections
  blog-developer/2019/12-31.md
  blog-developer/2020/12-31.md
  cid-redirects.json
  docs/api/ingest-budget-v1.md
Labels: cla-signed

#2926 Fix reference to Security Foundations app
  docs/cloud-security-analytics/threat-detection-and-investigation.md
Labels: doc:minor edit, cla-signed

#2928 Add michaljmatusiak92 to clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#2929 TRIDENT-15645 - Okta source update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/okta-source.md
Labels: doc:minor edit, cla-signed

#2925 MET-0: Update metrics documentation for topk/bottomk latest
  docs/metrics/metrics-operators/bottomk.md
  docs/metrics/metrics-operators/topk.md
Labels: doc:minor edit, cla-signed

#2923 alert logic app doc
  cid-redirects.json
  docs/integrations/security-threat-detection/alert-logic.md
  docs/integrations/security-threat-detection/index.md
  sidebars.ts
  static/img/integrations/security-threat-detection/alert-logic-logo.jpg
Labels: cla-signed

#2930 TRIDENT-15182-sentinalone-update
  docs/send-data/collect-from-other-data-sources/collect-logs-sentinelone.md
Labels: doc:minor edit, cla-signed

#2935 Change Fed C2C 1B address
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
Labels: doc:minor edit, cla-signed, hot🔥

#2934 Update zscaler-private-access.md
  docs/integrations/security-threat-detection/zscaler-private-access.md
Labels: cla-signed

#2937 Update Cloud SOAR role capabilities
  docs/manage/users-roles/roles/role-capabilities.md
Labels: doc:minor edit, cla-signed

#2941 Add CID for Playbooks article
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#2940 Update aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
Labels: doc:new, cla-signed

#2920 AWS amplify apps doc added
  cid-redirects.json
  docs/integrations/amazon-aws/aws-amplify.md
  docs/integrations/amazon-aws/index.md
  sidebars.ts
  static/img/integrations/amazon-aws/aws-amplify-logo.png
Labels: cla-signed, hot🔥

#2932 druva-cyber-resilience apps doc
  cid-redirects.json
  docs/integrations/saas-cloud/druva-cyber-resilience.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#2725 Metrics-based SLOs (GA 8/18)
  blog-service/2023-08-17-metrics-slos.md
  docs/observability/reliability-management-slo/create-slo.md
  static/img/observability/metrics-slo.png
Labels: cla-signed, do-not-merge

#2931 Query updated
  docs/dashboards/panels/single-value-charts.md
Labels: cla-signed

#2946 Fixing the title for metrics slos release notes
  blog-service/2023-08-17-metrics-slos.md
Labels: cla-signed

#2910 Update entity group for inventory
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  static/img/cse/create-entity-group-inventory.png
  static/img/cse/entity-groups-dynamic-schema-tags.png
  static/img/cse/gear-menu-2.png
Labels: doc:update, cla-signed, do-not-merge

#2939 Monitor limit increase
  docs/alerts/monitors/monitor-faq.md
Labels: cla-signed

#2950 Update docker-collection-methods.md
  docs/send-data/collect-from-other-data-sources/docker-collection-methods.md
Labels: cla-signed

#2933 Mimecast doc update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source.md
  static/img/send-data/mimecast-add-apis-input.png
Labels: cla-signed

#2917 c2c template added
  docs/contributing/templates/c2c-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/source-info.md
  sidebars.ts
Labels: cla-signed

#2953 Mimecast C2C page update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source.md
  static/img/send-data/mimecast-add-apis-input.png
Labels: cla-signed, hot🔥

#2954 Updated Otel - Collect Logs page regarding Syslog collection
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#2956 Update .clabot
  .clabot
Labels: cla-signed

#2952 Update buddy.md
  docs/integrations/webhooks/buddy.md
Labels: cla-signed

#2726 OTEL HTTP receiver checks enhancement
  docs/send-data/opentelemetry-collector/faq.md
  static/img/send-data/opentelemetry-collector/otel-ping.png
Labels: cla-signed, do-not-merge

#2962 App Catalog --> Apps and Integrations
  docs/integrations/index.md
  docusaurus.config.js
Labels: cla-signed

#2963 Update .clabot
  .clabot
Labels: cla-signed

#2964 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#2965 Update Muting Schedule screenshots
  static/img/alerts/mute-sched1.png
  static/img/alerts/mute-sched2.png
Labels: cla-signed

#2949 CID redirect link instructions
  docs/contributing/create-doc.md
Labels: cla-signed, do-not-merge

#2955 Monitor tags
  blog-service/2023-08-22-alerts.md
  cid-redirects.json
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/settings.md
  i18n/ja/alerts/alerts/monitors/index.md
  sidebars.ts
  static/img/monitors/Montor-playbook-input.png
  static/img/monitors/monitor-details-during-creation.png
Labels: cla-signed, do-not-merge

#2958 SLO docs overhaul
  cid-redirects.json
  docs/observability/reliability-management-slo/alerts.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/observability/reliability-management-slo/dashboards.md
  docs/observability/reliability-management-slo/index.md
  docs/observability/reliability-management-slo/use-cases.md
  sidebars.ts
Labels: cla-signed

#2959 SUMO-227597: documentation for 12 webhook doc only apps
  cid-redirects.json
  docs/get-started/help.md
  docs/integrations/amazon-aws/aws-amplify.md
  docs/integrations/amazon-aws/rds.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/active-directory-json-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-linux-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/nginx-opentelemetry.md
  docs/integrations/webhooks/buddy.md
  docs/integrations/webhooks/postman.md
  docs/integrations/webhooks/pusher.md
  docs/integrations/webhooks/rollbar.md
  docs/integrations/webhooks/sendgrid.md
  docs/integrations/webhooks/sentry.md
  docs/integrations/webhooks/split.md
  docs/integrations/webhooks/squadcast.md
  docs/integrations/webhooks/stripe.md
  docs/integrations/webhooks/superwise.md
  docs/integrations/webhooks/uptime.md
  docs/integrations/webhooks/zebrium-rcaas.md
  docs/integrations/webhooks/zenduty.md
  docs/metrics/introduction/metric-histograms.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/send-data/choose-collector-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
  docs/send-data/opentelemetry-collector/install-collector-linux.md
  sidebars.ts
  static/img/integrations/webhooks/postman-logo.png
  static/img/integrations/webhooks/pusher-logo.png
  static/img/integrations/webhooks/rollbar-logo.png
  static/img/integrations/webhooks/sendGrid-logo.png
  static/img/integrations/webhooks/sentry-logo.png
  static/img/integrations/webhooks/split-logo.png
  static/img/integrations/webhooks/squadcast-logo.png
  static/img/integrations/webhooks/stripe-logo.png
  static/img/integrations/webhooks/superwise-logo.png
  static/img/integrations/webhooks/uptime-logo.png
  static/img/integrations/webhooks/zebrium-rcaas-logo.png
  static/img/integrations/webhooks/zenduty-logo.png
Labels: cla-signed

#2942 Collector Version 19.456-3 release note
  blog-collector/2023-08-22.md
  docs/send-data/installed-collectors/collector-installation-reference/collector-properties.md
Labels: cla-signed, do-not-merge

#2967 Certified by Sumo definition
  docs/get-started/apps-integrations.md
  static/img/get-started/cert-app.png
Labels: cla-signed

#2966 2957 notes on collection properties
  docs/api/collector-management/collector-api-methods-examples.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-windows.md
  docs/integrations/amazon-aws/ses.md
  docs/integrations/databases/mariadb.md
  docs/integrations/security-threat-detection/carbon-black-cloud.md
  docs/reuse/apps/create-aws-s3-source.md
  docs/reuse/collection-should-begin-note.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
  docs/send-data/installed-collectors/sources/collect-forwarded-events-windows-event-collector.md
  docs/send-data/installed-collectors/sources/local-file-source.md
  docs/send-data/installed-collectors/sources/local-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/remote-file-source/index.md
  docs/send-data/installed-collectors/sources/remote-windows-event-log-source.md
  docs/send-data/use-json-configure-sources/index.md
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
Labels: doc:update, cla-signed

#2969 Missing CIDs
  cid-redirects.json
Labels: cla-signed

#2938 TRIDENT-18367 Signal index migration FAQ
  docs/cse/records-signals-entities-insights/signal-index-migration-faq.md
Labels: doc:new, cla-signed, do-not-merge

#2970 Update automation-service-bridge.md - adjustments based on field expe…
  docs/cse/automation-service/automation-service-bridge.md
Labels: cla-signed

#2971 Update cloud-soar-bridge.md - adjustments based on field experience
  docs/cloud-soar/cloud-soar-bridge.md
Labels: cla-signed

#2968 Update time-reference.md
  docs/send-data/reference-information/time-reference.md
Labels: cla-signed

#2972 Add Grok deprecation release note
  blog-cse/2023-08-22-application-update.md
  docs/cse/ingestion/sumo-logic-ingest-mapping.md
  docs/cse/schema/parsing-language-reference-guide.md
Labels: doc:new, cla-signed

#2973 Add Cloud SIEM content release notes for August 22, 2023
  blog-cse/2023-08-22-content.md
Labels: cla-signed

#2948 Initial checkin for 10 AWS specific doc only app pages.
  cid-redirects.json
  docs/integrations/amazon-aws/amazon-appflow.md
  docs/integrations/amazon-aws/amazon-appstream2.md
  docs/integrations/amazon-aws/amazon-athena.md
  docs/integrations/amazon-aws/amazon-cloudfront.md
  docs/integrations/amazon-aws/aws-amplify.md
  docs/integrations/amazon-aws/aws-apprunner.md
  docs/integrations/amazon-aws/aws-appsync.md
  docs/integrations/amazon-aws/aws-backup.md
  docs/integrations/amazon-aws/aws-certificate-manager.md
  docs/integrations/amazon-aws/aws-chatbot.md
  docs/integrations/amazon-aws/aws-private-certificate-authority.md
  docs/integrations/amazon-aws/index.md
  sidebars.ts
  static/img/integrations/amazon-aws/amazon-appflow-logo.png
  static/img/integrations/amazon-aws/amazon-appstream2-logo.png
  static/img/integrations/amazon-aws/amazon-athena-logo.png
  static/img/integrations/amazon-aws/amazon-cloudfront-logo.png
  static/img/integrations/amazon-aws/aws-apprunner-logo.png
  static/img/integrations/amazon-aws/aws-appsync-logo.png
  static/img/integrations/amazon-aws/aws-backup-logo.png
  static/img/integrations/amazon-aws/aws-certificate-manager-logo.png
  static/img/integrations/amazon-aws/aws-chatbot-logo.png
  static/img/integrations/amazon-aws/aws-private-certificate-authority-logo.png
Labels: cla-signed

#2979 Grafana Plugin Release Note.md
  blog-service/2023-08-23-metrics.md
Labels: cla-signed

#2976 SUMO-227719: added documentation for first set of webhook apps
  cid-redirects.json
  docs/integrations/webhooks/bugsnag.md
  docs/integrations/webhooks/configcat.md
  docs/integrations/webhooks/emnify.md
  docs/integrations/webhooks/firefly.md
  docs/integrations/webhooks/flagsmith.md
  docs/integrations/webhooks/grafana-oncall.md
  docs/integrations/webhooks/gremlin.md
  docs/integrations/webhooks/honeybadger.md
  docs/integrations/webhooks/ilert.md
  docs/integrations/webhooks/mailgun.md
  docs/integrations/webhooks/mparticle.md
  docs/integrations/webhooks/neoload.md
  docs/integrations/webhooks/netlify.md
  docs/integrations/webhooks/newrelic-alerts.md
  docs/integrations/webhooks/nobl9.md
  docs/integrations/webhooks/papertrail.md
  sidebars.ts
  static/img/integrations/webhooks/buddy-logo.png
  static/img/integrations/webhooks/bugsnag-logo.png
  static/img/integrations/webhooks/configcat-logo.png
  static/img/integrations/webhooks/emnify-logo.png
  static/img/integrations/webhooks/firefly-logo.png
  static/img/integrations/webhooks/flagsmith-logo.png
  static/img/integrations/webhooks/grafana-oncall-logo.png
  static/img/integrations/webhooks/gremlin-logo.png
  static/img/integrations/webhooks/honeybadger-logo.png
  static/img/integrations/webhooks/ilert-logo.png
  static/img/integrations/webhooks/mailgun-logo.png
  static/img/integrations/webhooks/mparticle-logo.png
  static/img/integrations/webhooks/neoload-logo.png
  static/img/integrations/webhooks/netlify-logo.png
  static/img/integrations/webhooks/newrelic-alerts-logo.png
  static/img/integrations/webhooks/nobl9-logo.png
  static/img/integrations/webhooks/papertrail-logo.png
Labels: doc:new, cla-signed

#2983 Broken link https://sumologic.slack.com/archives/C0S86TM6K/p1692933015632559
  docs/search/live-tail/live-tail-cli.md
Labels: cla-signed

#2986 CONN-2416 Update microsoft-graph-security-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
Labels: doc:minor edit, cla-signed

#2987 Add damiangarbacz to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#2981 Update cloud-soar-bridge.md - Add caveat indicating the ALIAS must be less than 20 characters
  docs/cloud-soar/cloud-soar-bridge.md
Labels: doc:minor edit, cla-signed

#2982 Update automation-service-bridge.md Add caveat indicating the ALIAS must be less than 20 characters
  docs/cse/automation-service/automation-service-bridge.md
Labels: doc:minor edit, cla-signed

#2992 404 fixes
  cid-redirects.json
Labels: cla-signed

#2984 Azure Batch doc only apps
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-batch.md
  docs/integrations/microsoft-azure/index.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-batch.png
Labels: doc:new, cla-signed, do-not-merge

#2995 Wrong /integrations index pg links
  docs/integrations/index.md
Labels: cla-signed

#2996 Update palo-alto-firewall.md - change output field from src_user to s…
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/palo-alto-firewall.md
Labels: doc:minor edit, cla-signed

#2998 Update collect-logs.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#2994 export dashboards doc update
  docs/dashboards/export-dashboard-new.md
  docs/dashboards/scheduled-report.md
Labels: cla-signed, do-not-merge

#2978 gcp doc only app - Batch 1
  cid-redirects.json
  docs/integrations/google/cloud-alloydb-for-postgresql.md
  docs/integrations/google/cloud-api-gateway.md
  docs/integrations/google/cloud-apis.md
  docs/integrations/google/cloud-armor.md
  docs/integrations/google/cloud-auto-scaler.md
  docs/integrations/google/cloud-backup-for-gke.md
  docs/integrations/google/cloud-bigquery-bi-engine.md
  docs/integrations/google/cloud-bigtable.md
  docs/integrations/google/cloud-certificate-authority-service.md
  docs/integrations/google/cloud-certificate-manager.md
  docs/integrations/google/cloud-composer.md
  docs/integrations/google/cloud-dataflow.md
  docs/integrations/google/cloud-dataproc-metastore.md
  docs/integrations/google/cloud-dataproc.md
  docs/integrations/google/cloud-datastore.md
  docs/integrations/google/cloud-datastream.md
  docs/integrations/google/cloud-deploy.md
  docs/integrations/google/cloud-filestore.md
  docs/integrations/google/cloud-firebase.md
  docs/integrations/google/cloud-firestore.md
  docs/integrations/google/index.md
  sidebars.ts
  static/img/integrations/google/GoogleAutoScaler.png
  static/img/integrations/google/GoogleCloudAPIGateway.png
  static/img/integrations/google/GoogleCloudAPIs.png
  static/img/integrations/google/GoogleCloudAlloyDBforPostgreSQL.png
  static/img/integrations/google/GoogleCloudArmor.png
  static/img/integrations/google/GoogleCloudBackupforGKE.png
  static/img/integrations/google/GoogleCloudBigQueryBIEngine.png
  static/img/integrations/google/GoogleCloudBigtable.png
  static/img/integrations/google/GoogleCloudCertificateAuthorityService.png
  static/img/integrations/google/GoogleCloudCertificateManager.png
  static/img/integrations/google/GoogleCloudComposer.png
  static/img/integrations/google/GoogleCloudDataflow.png
  static/img/integrations/google/GoogleCloudDataproc.png
  static/img/integrations/google/GoogleCloudDataprocMetastore.png
  static/img/integrations/google/GoogleCloudDatastore.png
  static/img/integrations/google/GoogleCloudDatastream.png
  static/img/integrations/google/GoogleCloudDeploy.png
  static/img/integrations/google/GoogleCloudFilestore.png
  static/img/integrations/google/GoogleCloudFireStore.png
  static/img/integrations/google/GoogleCloudFirebase.png
Labels: doc:new, cla-signed

#2997 Combine Search Audit Index articles
  cid-redirects.json
  docs/manage/security/index.md
  docs/manage/security/log-search-audit-index.md
  docs/manage/security/search-audit-index.md
  sidebars.ts
Labels: doc:update, cla-signed

#3003 TRIDENT-15425 - Add "Degraded rules" section
  docs/cse/rules/before-writing-custom-rule.md
Labels: doc:new, cla-signed

#3004 Amazon/AWS apps ABC sort order
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
  docs/integrations/amazon-aws/aurora-postgresql-ulm.md
  docs/integrations/amazon-aws/global-intelligence-guardduty.md
  docs/integrations/amazon-aws/vpc-flow-logs-pci-compliance.md
  sidebars.ts
Labels: cla-signed

#3008 minor formatting
  docs/integrations/google/cloud-alloydb-for-postgresql.md
  docs/integrations/google/cloud-api-gateway.md
  docs/integrations/google/cloud-apis.md
  docs/integrations/google/cloud-armor.md
  docs/integrations/google/cloud-auto-scaler.md
  docs/integrations/google/cloud-backup-for-gke.md
  docs/integrations/google/cloud-bigquery-bi-engine.md
  docs/integrations/google/cloud-certificate-authority-service.md
  docs/integrations/google/cloud-certificate-manager.md
  docs/integrations/google/cloud-composer.md
  docs/integrations/google/cloud-dataflow.md
  docs/integrations/google/cloud-dataproc-metastore.md
  docs/integrations/google/cloud-dataproc.md
  docs/integrations/google/cloud-datastore.md
  docs/integrations/google/cloud-datastream.md
  docs/integrations/google/cloud-deploy.md
  docs/integrations/google/cloud-filestore.md
  docs/integrations/google/cloud-firebase.md
  docs/integrations/google/cloud-firestore.md
Labels: cla-signed

#2999 Update advantages in Migrate to new dashboard
  docs/dashboards/dashboards-migration/index.md
Labels: cla-signed

#3009 Gcpdoconlydocsbatch2
  cid-redirects.json
  docs/integrations/google/cloud-fleet-engine.md
  docs/integrations/google/cloud-interconnect.md
  docs/integrations/google/cloud-logging.md
  docs/integrations/google/cloud-memorystore-for-redis.md
  docs/integrations/google/cloud-net-app-cloud-volumes-service.md
  docs/integrations/google/cloud-network-topology.md
  docs/integrations/google/cloud-pub-sub.md
  docs/integrations/google/cloud-router.md
  docs/integrations/google/cloud-run.md
  docs/integrations/google/cloud-spanner.md
  docs/integrations/google/cloud-tasks.md
  docs/integrations/google/cloud-tpu.md
  docs/integrations/google/cloud-trace.md
  docs/integrations/google/cloud-traffic-director.md
  docs/integrations/google/cloud-vertex-ai.md
  docs/integrations/google/cloud-vpn.md
  sidebars.ts
  static/img/integrations/google/GoogleCloudFleetEngine.png
  static/img/integrations/google/GoogleCloudInterconnect.png
  static/img/integrations/google/GoogleCloudLogging.png
  static/img/integrations/google/GoogleCloudMemorystoreforRedis.png
  static/img/integrations/google/GoogleCloudNetworkTopology.png
  static/img/integrations/google/GoogleCloudRouter.png
  static/img/integrations/google/GoogleCloudRun.png
  static/img/integrations/google/GoogleCloudSpanner.png
  static/img/integrations/google/GoogleCloudTPU.png
  static/img/integrations/google/GoogleCloudTasks.png
  static/img/integrations/google/GoogleCloudTrace.png
  static/img/integrations/google/GoogleCloudTrafficDirector.png
  static/img/integrations/google/GoogleCloudVPN.png
  static/img/integrations/google/GoogleCloudVertexAI.png
  static/img/integrations/google/GooglePubSub.png
  static/img/integrations/google/gcp_netapp.png
Labels: cla-signed

#3010 added cards for new apps
  docs/integrations/google/index.md
  static/img/integrations/google/k8s.png
Labels: cla-signed

#3014 Update local-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/local-windows-event-log-source.md
Labels: cla-signed

#3012 Fix image coding in Cloud SIEM administration articles
  docs/cse/administration/create-a-custom-tag-schema.md
  docs/cse/administration/create-cse-context-actions.md
  docs/cse/administration/create-custom-threat-intel-source.md
  docs/cse/administration/create-use-network-blocks.md
  docs/cse/administration/cse-apis.md
  docs/cse/administration/cse-audit-logging.md
  docs/cse/administration/cse-data-retention.md
  docs/cse/administration/cse-user-accounts-and-roles.md
  docs/cse/administration/custom-inventory-sources.md
  docs/cse/administration/filter-search.md
  docs/cse/administration/manage-custom-insight-resolutions.md
  docs/cse/administration/manage-custom-insight-statuses.md
  docs/cse/administration/save-inventory-data-lookup-table.md
  docs/cse/administration/using-sensor-zones.md
Labels: doc:update, cla-signed

#3013 Fix 404s
  cid-redirects.json
  docs/cse/introduction-to-cloud-siem.md
  docs/dashboards-classic/get-started/move-panel-dashboard.md
  docs/integrations/containers-orchestration/strimzi-kafka.md
  docs/integrations/saas-cloud/druva-cyber-resilience.md
  docs/integrations/saas-cloud/symantec-web-security-service.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/metrics/introduction/metric-formats.md
Labels: cla-signed

#3018 Fix image coding in cloud soar
  docs/cloud-soar/architecture.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/main-menu.md
  docs/cloud-soar/mssp.md
Labels: doc:update, cla-signed

#3017 Update .clabot
  .clabot
Labels: cla-signed

#3016 Update binary-package-install-a-collector.md
  docs/send-data/installed-collectors/collector-installation-reference/binary-package-install-a-collector.md
Labels: cla-signed

#3020 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#3000 Create doc for hasura app
  cid-redirects.json
  docs/integrations/webhooks/hasura.md
  sidebars.ts
  static/img/integrations/webhooks/buddy-logo.png
  static/img/integrations/webhooks/bugsnag-logo.png
  static/img/integrations/webhooks/configcat-logo.png
  static/img/integrations/webhooks/emnify-logo.png
  static/img/integrations/webhooks/firefly-logo.png
  static/img/integrations/webhooks/flagsmith-logo.png
  static/img/integrations/webhooks/grafana-oncall-logo.png
  static/img/integrations/webhooks/gremlin-logo.png
  static/img/integrations/webhooks/hasura-logo.png
  static/img/integrations/webhooks/honeybadger-logo.png
  static/img/integrations/webhooks/ilert-logo.png
  static/img/integrations/webhooks/mailgun-logo.png
  static/img/integrations/webhooks/mparticle-logo.png
  static/img/integrations/webhooks/neoload-logo.png
  static/img/integrations/webhooks/netlify-logo.png
  static/img/integrations/webhooks/newrelic-alerts-logo.png
  static/img/integrations/webhooks/nobl9-logo.png
  static/img/integrations/webhooks/papertrail-logo.png
  static/img/integrations/webhooks/postman-logo.png
  static/img/integrations/webhooks/pusher-logo.png
  static/img/integrations/webhooks/rollbar-logo.png
  static/img/integrations/webhooks/sendGrid-logo.png
  static/img/integrations/webhooks/sentry-logo.png
  static/img/integrations/webhooks/split-logo.png
  static/img/integrations/webhooks/squadcast-logo.png
  static/img/integrations/webhooks/stripe-logo.png
  static/img/integrations/webhooks/superwise-logo.png
  static/img/integrations/webhooks/uptime-logo.png
  static/img/integrations/webhooks/zebrium-rcaas-logo.png
  static/img/integrations/webhooks/zenduty-logo.png
Labels: doc:new, cla-signed

#3021 Update cisco-meraki-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
Labels: cla-signed

#3022 created cid for devops app
  cid-redirects.json
Labels: cla-signed

#3019 Contributing to Docs edits
  docs/cloud-soar/index.md
  docs/contributing/create-doc.md
  docs/contributing/edit-doc.md
  docs/contributing/index.md
  docs/contributing/remove-doc.md
  docs/reuse/doc-prerequisites.md
  sidebars.ts
Labels: cla-signed

#3023 Added doc for signl4 doc only app
  cid-redirects.json
  docs/integrations/webhooks/signl4.md
  sidebars.ts
  static/img/integrations/webhooks/signl4-logo.png
Labels: cla-signed

#3015 Formatting/wordsmithing GCP Docs
  docs/integrations/google/cloud-alloydb-for-postgresql.md
  docs/integrations/google/cloud-api-gateway.md
  docs/integrations/google/cloud-apis.md
  docs/integrations/google/cloud-armor.md
  docs/integrations/google/cloud-auto-scaler.md
  docs/integrations/google/cloud-backup-for-gke.md
  docs/integrations/google/cloud-bigtable.md
  docs/integrations/google/cloud-certificate-authority-service.md
  docs/integrations/google/cloud-certificate-manager.md
  docs/integrations/google/cloud-composer.md
  docs/integrations/google/cloud-dataflow.md
  docs/integrations/google/cloud-dataproc-metastore.md
  docs/integrations/google/cloud-dataproc.md
  docs/integrations/google/cloud-datastore.md
  docs/integrations/google/cloud-datastream.md
  docs/integrations/google/cloud-deploy.md
  docs/integrations/google/cloud-filestore.md
  docs/integrations/google/cloud-firebase.md
  docs/integrations/google/cloud-firestore.md
  docs/integrations/google/cloud-interconnect.md
  docs/integrations/google/cloud-logging.md
  docs/integrations/google/cloud-memorystore-for-redis.md
  docs/integrations/google/cloud-net-app-cloud-volumes-service.md
  docs/integrations/google/cloud-network-topology.md
  docs/integrations/google/cloud-pub-sub.md
  docs/integrations/google/cloud-router.md
  docs/integrations/google/cloud-run.md
  docs/integrations/google/cloud-spanner.md
  docs/integrations/google/cloud-tasks.md
  docs/integrations/google/cloud-tpu.md
  docs/integrations/google/cloud-trace.md
  docs/integrations/google/cloud-traffic-director.md
  docs/integrations/google/cloud-vertex-ai.md
  docs/integrations/google/cloud-vpn.md
Labels: cla-signed

#3007 Remove PCI app article
  cid-redirects.json
  docs/cloud-security-analytics/audit-and-compliance.md
  docs/integrations/pci-compliance/index.md
  docs/integrations/pci-compliance/setup.md
  docs/integrations/sumo-apps/index.md
  sidebars.ts
Labels: doc:update, cla-signed

#3002 Classic Metrics to Metrics Explorer notice
  docs/metrics/index.md
  docs/metrics/metrics-queries/metrics-explorer.md
Labels: cla-signed

#3005 Apply fixes to the "Network Sensor Deployment Guide"
  docs/cse/sensors/network-sensor-deployment-guide.md
Labels: doc:update, cla-signed
