Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-11, with the labels that each got.

#3272 On-premises SOAR end-of-life release note
  blog-csoar/2023-11-01-23-application-update.md
Labels: doc:new, cla-signed

#3270 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: doc:site tech, cla-signed

#3276 Update .clabot
  .clabot
Labels: cla-signed

#3278 Create 2023-11-01-application-update.md
  blog-cse/2023-11-01-application-update.md
Labels: cla-signed

#3228 Reduce CEP state size
  docs/cse/records-signals-entities-insights/view-records-signal.md
  static/img/cse/attached-records.png
Labels: doc:update, cla-signed

#3280 Style Guide link text guidance
  docs/contributing/style-guide.md
Labels: cla-signed

#3281 Update SOAR on-premises release note
  blog-csoar/2023-11-01-23-application-update.md
Labels: doc:update, cla-signed

#3254 AWSO 2.7 release notes
  blog-service/2023-11-02-apps.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
Labels: cla-signed, do-not-merge

#3275 opentelemetry collector documentation on monitoring jobs
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#3283 Revert "opentelemetry collector documentation on monitoring jobs"
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#3274 partner app template updated
  docs/contributing/templates/partner-app.md
Labels: cla-signed

#3277 Add FedRAMP article
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/manage/manage-subscription/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#3284 ckruse edits from #3275
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#3289 Create 2023-11-02-content.md
  blog-cse/2023-11-02-content.md
Labels: cla-signed

#3279 Azure Event Hubs Source Beta
  cid-redirects.json
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-audit-office.md
  docs/integrations/microsoft-azure/office-365.md
  docs/integrations/product-list.md
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/send-data/hosted-collectors/configure-hosted-collector.md
  docs/send-data/hosted-collectors/index.md
  docs/send-data/hosted-collectors/microsoft-source/ms-azure-event-hubs-source.md
  docs/send-data/hosted-collectors/microsoft-source/ms-office-audit-source.md
  sidebars.ts
  static/img/send-data/azure-event-hub-configs.png
  static/img/send-data/azure-event-hub-name.png
  static/img/send-data/azure-event-hub-step1.png
  static/img/send-data/azure-event-hub-step2.png
  static/img/send-data/azure-event-hub-step3.png
  static/img/send-data/azure-event-hub-step4.png
  static/img/send-data/azure-event-hub-step5.png
  static/img/send-data/azure-event-hub-step6.png
  static/img/send-data/azure-event-hub-step7.png
  static/img/send-data/azure-event-hub-step8.png
  static/img/send-data/azure-event-hub-step9.png
Labels: cla-signed, do-not-merge

#3290 Parser templates
  docs/cse/schema/parser-editor.md
  static/img/cse/parser-templates.png
Labels: doc:new, cla-signed

#3287 chore(instr): update lambda layers and switch from http traces to otlp http
  docs/apm/real-user-monitoring/browser-traces.md
  docs/apm/traces/get-started-transaction-tracing/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby-on-rails.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-aws-environments.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-other-environments.md
Labels: cla-signed

#3288 Update FedRAMP article per SMEs
  docs/manage/manage-subscription/fedramp-capabilities.md
Labels: doc:update, cla-signed

#3286 Update aws-privatelink.md
  docs/integrations/amazon-aws/aws-privatelink.md
Labels: cla-signed

#3292 Update Signal Deprecation FAQ
  docs/cse/records-signals-entities-insights/signal-index-migration-faq.md
Labels: cla-signed

#3285 Update about.md
  docs/dashboards/about.md
Labels: cla-signed

#3291 Timezone setting for alerts/monitors
  blog-service/2023-11-07-monitors.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/settings.md
  static/img/monitors/monitor-notifications-input.png
Labels: cla-signed, do-not-merge

#3282 K8s Helm chart v4 replacement
  docs/observability/kubernetes/collection-setup.md
  static/img/kubernetes/K8s-architecture.png
Labels: cla-signed, do-not-merge

#3297 Alerts auto-resolve change
  docs/alerts/monitors/overview.md
Labels: cla-signed

#3298 Differentiate Azure Event Hubs Source alpha vs. beta
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/microsoft-source/ms-azure-event-hubs-source.md
  static/img/send-data/azure-event-hub-configs.png
  static/img/send-data/azure-event-hub-step1.png
  static/img/send-data/azure-event-hub-step2.png
  static/img/send-data/azure-event-hub-step3.png
  static/img/send-data/azure-event-hub-step4.png
  static/img/send-data/azure-event-hub-step5.png
  static/img/send-data/azure-event-hub-step6.png
  static/img/send-data/azure-event-hub-step7.png
  static/img/send-data/azure-event-hub-step8.png
  static/img/send-data/azure-event-hub-step9.png
Labels: cla-signed

#3296 Update obsolete App Catalog install UI elements
  docs/reuse/apps/app-install.md
Labels: cla-signed

#3302 Update .clabot
  .clabot
Labels: cla-signed

#3305 Add rotating-credentials-playbooks.md
  docs/manage/security/rotating-credentials-playbooks.md
Labels: doc:new, cla-signed, hot🔥

#3306 Update rotating-credentials-playbooks.md
  docs/manage/security/rotating-credentials-playbooks.md
Labels: cla-signed

#3309 Update event hubs beta with Scaling information.
  docs/send-data/hosted-collectors/microsoft-source/ms-azure-event-hubs-source.md
Labels: cla-signed

#3257 Publish product list for GA
  docs/integrations/index.md
  docs/integrations/product-list.md
  sidebars.ts
  static/img/integrations/misc/sensu-logo.png
Labels: doc:update, cla-signed

#3308 Update Collector Management API
  docs/api/collector-management/index.md
Labels: cla-signed

#3304 Enable process metric collection added
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  static/img/integrations/hosts-operating-systems/Linux-YAML.png
  static/img/integrations/hosts-operating-systems/Mac-YAML.png
  static/img/integrations/hosts-operating-systems/Windows-YAML.png
  static/img/integrations/hosts-operating-systems/process-metric-collection.png
Labels: cla-signed, hot🔥

#3311 Update set-up-webhook-connections.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#3303 Collector 19.467-2 Release Notes
  blog-collector/2023-11-13.md
Labels: cla-signed

#3313 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#3314 Create 2023-11-13-content.md
  blog-cse/2023-11-13-content.md
Labels: doc:new, cla-signed

#3312 Image path updated
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
Labels: cla-signed

#3295 Update K8s app installation instructions
  docs/integrations/containers-orchestration/kubernetes.md
Labels: cla-signed

#3301 Update substring.md
  docs/search/search-query-language/search-operators/substring.md
Labels: cla-signed

#3317 Update style-guide.md
  docs/contributing/style-guide.md
Labels: cla-signed

#3320 Cloud SIEM Release Notes for 11/17/23
  blog-cse/2023-11-17-application-update.md
  static/img/release-notes/cse/markdown-rule-description.jpg
Labels: cla-signed

#3319 Fzampori csoar changelog
  blog-csoar/2023-10-20-application-update.md
  blog-csoar/2023-11-01-application-update.md
  blog-csoar/2023-11-16-application-update.md
Labels: cla-signed

#3325 Update .clabot
  .clabot
Labels: cla-signed

#3323 Update index.md
  docs/manage/ingestion-volume/ingest-budgets/index.md
Labels: cla-signed

#3326 Temp banner for AWS re:Invent
  docusaurus.config.js
Labels: cla-signed

#3273 Restricted Operators in Dashboards doc added
  docs/dashboards/about.md
  docs/dashboards/index.md
  docs/dashboards/restricted-operators-dashboards.md
  sidebars.ts
Labels: cla-signed

#3322 New Partner Apps Release notes
  blog-service/2023-11-21-partner-apps.md
  docs/integrations/partner-ecosystem-apps.md
Labels: cla-signed

#3328 Update schedule-searches-webhook-connections.md
  docs/alerts/webhook-connections/schedule-searches-webhook-connections.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#3324 Update about.md
  docs/dashboards/about.md
Labels: cla-signed

#3315 Use playbooks with monitors - beta
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  static/img/monitors/monitor-anomaly-logs.png
  static/img/monitors/monitor-detection-methods.png
  static/img/monitors/monitor-playbooks-ui.png
  static/img/monitors/new-monitor-advanced-settings.png
  static/img/monitors/new-monitor-anomaly-detection-method.png
  static/img/monitors/new-monitor-details.png
  static/img/monitors/new-monitor-dialog.png
  static/img/monitors/new-monitor-notifications.png
  static/img/monitors/new-monitor-set-trigger-conditions.png
  static/img/monitors/playbook-alert-type.png
  static/img/monitors/playbook-complete-task.png
  static/img/monitors/playbook-completed-icon.png
  static/img/monitors/playbook-duplicate-button.png
  static/img/monitors/playbook-in-automation-service.png
  static/img/monitors/playbook-running-icon.png
  static/img/monitors/playbook-user-interaction-icon.png
  static/img/monitors/playbook-waiting-owner.png
  static/img/monitors/view-playbooks-on-alert.png
Labels: doc:new, cla-signed, do-not-merge

#3333 Update index.md
  docs/search/get-started-with-search/search-page/index.md
Labels: cla-signed

#3330 Added a note about Start date limit
  docs/manage/scheduled-views/add-scheduled-view.md
Labels: cla-signed

#3327 Update markdown-syntax.md
  docs/dashboards-classic/get-started/markdown-syntax.md
  docs/dashboards/panels/markdown-syntax.md
Labels: cla-signed, do-not-merge

#3334 Fix table
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
Labels: doc:minor edit, cla-signed

#3336 Add role capabilities for the Automation Service
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/platform-services/automation-service/about-automation-service.md
Labels: doc:update, cla-signed

#3339 Create 2023-11-27-AWSO-logs-for-m&t
  blog-service/2023-11-28-AWSO-logs-for-mt.md
Labels: cla-signed

#3337 Update CSE type
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/platform-services/automation-service/automation-service-playbooks.md
Labels: doc:update, cla-signed

#3335 Updates for inventory type entity groups
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
Labels: doc:update, cla-signed

#3341 Revert "Create 2023-11-27-AWSO-logs-for-m&t (#3339)"
  blog-service/2023-11-28-AWSO-logs-for-mt.md
Labels: doc:minor edit, cla-signed

#3332 Changes to the example which describes hashing in a log body
  docs/send-data/opentelemetry-collector/data-transformations.md
Labels: cla-signed

#3342 Re-add AWS logs release note
  blog-service/2023-11-28-observability.md
Labels: doc:new, cla-signed

#3345 Update optimize-search-partitions.md
  docs/search/optimize-search-partitions.md
Labels: cla-signed

#3310 Export SAML metadata XML
  blog-service/2023-11-29-manage.md
  docs/manage/security/saml/set-up-saml.md
  static/img/security/config-list.png
  static/img/security/download-metadata-xml-button.png
  static/img/security/saml-add-configuration.png
Labels: doc:new, cla-signed

#3344 Add list of Insight attributes
  docs/cloud-soar/incidents-triage.md
Labels: doc:new, cla-signed

#3347 Update Metrics DPM doc
  docs/metrics/metrics-dpm.md
Labels: cla-signed

#3350 Add sumo-drew to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#3349 Update zscaler-private-access.md
  docs/integrations/security-threat-detection/zscaler-private-access.md
Labels: cla-signed
