Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-07, with the labels that each got.

#2625 Updated aws-ec2-inventory docs
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
  static/img/send-data/AWS-EC2-input-pane.png
  static/img/send-data/key-based.png
  static/img/send-data/role-based.png
Labels: cla-signed

#2711 Trident 16723 - Replace "dwell time" with "detection time"
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
  static/img/cse/board.png
  static/img/cse/hud.png
  static/img/cse/insight-details.png
  static/img/cse/insight-summary.png
  static/img/cse/insights-page.png
Labels: doc:update, cla-signed

#2712 TRIDENT-18174 - New global suppression screenshots
  docs/cse/records-signals-entities-insights/about-signal-suppression.md
  docs/cse/records-signals-entities-insights/set-insight-generation-window-threshold.md
  static/img/cse/detection-threshold-global-signal-suppression.png
  static/img/cse/detection-threshold-popup.png
Labels: doc:update, cla-signed

#2707 Linux-CSMA-Opentelemetry docs
  cid-redirects.json
  docs/integrations/cloud-security-monitoring-analytics/index.md
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/linux-opentelemetry.md
  sidebars.ts
Labels: cla-signed

#2716 Update Metrics cardinality limit to 50K
  docs/metrics/metrics-queries/metric-query-error-messages.md
Labels: cla-signed

#2715 Adding more examples for special chars in JSON operator
  docs/search/search-query-language/parse-operators/parse-json-formatted-logs.md
Labels: cla-signed

#2717 Increased Cardinality Limit release notes
  blog-service/2023-07-04-metrics.md
Labels: cla-signed, hot🔥

#2714 Code42 Incydr C2C doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/code42-incydr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/img/send-data/code42-incydr-config.png
  static/img/send-data/code42-incydr-icon.png
  static/img/send-data/code42-incydr-logo.png
Labels: cla-signed

#2713 infrequent tier monitors and ARP
  docs/manage/partitions-data-tiers/infrequent-tier-monitors.md
Labels: cla-signed, do-not-merge

#2587 Next-Gen apps docs & release notes (GA: week ending 6/23)
  blog-service/2023-07-05-apps.md
  docs/get-started/apps-integrations.md
  docs/integrations/index.md
Labels: cla-signed

#2567 Log level
  docs/search/get-started-with-search/search-page/index.md
  docs/search/get-started-with-search/search-page/log-level.md
  static/img/search/get-started-search/search-page/log-level-error-filter.png
  static/img/search/get-started-search/search-page/log-level-legend.png
Labels: cla-signed, do-not-merge

#2722 SUMO-216336 - Update RBAC for indexes beta article
  docs/manage/users-roles/roles/rbac-for-indexes.md
Labels: doc:new, cla-signed

#2694 Update collect-aws-lambda-logs-extension.md
  docs/send-data/collect-from-other-data-sources/collect-aws-lambda-logs-extension.md
Labels: cla-signed

#2727 API Docs
  docs/api/getting-started.md
Labels: cla-signed

#2724 Fix legacy and broken links
  cid-redirects.json
Labels: cla-signed

#2719 end of life caution added for Classic dashboard docs
  docs/dashboards/get-started/create-dashboard.md
  docs/dashboards/index.md
Labels: cla-signed

#2720 cross reference link added
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/pci-compliance/opentelemetry/linux-opentelemetry.md
Labels: cla-signed

#2730 Code42 Incydr release note
  blog-service/2023-07-06-collections.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/code42-incydr-source.md
  static/img/send-data/code42-incydr-config.png
Labels: cla-signed

#2731 Update new manage org settings for the Cloudflex Credits accounts
  docs/manage/manage-subscription/manage-org-settings.md
  static/img/subscriptions/Manage_Organization_options.png
  static/img/subscriptions/manage-org-links-cfc.png
Labels: cla-signed

#2589 TRIDENT-18109 - Add note on extracted fields
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-chain-rule.md
  docs/cse/rules/write-match-rule.md
  docs/cse/rules/write-threshold-rule.md
Labels: doc:minor edit, cla-signed

#2738 Admin file changes - Codeowners, clabot
  .clabot
  .github/CODEOWNERS
Labels: cla-signed

#2721 JumpCloud Directory Insights C2C doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
  sidebars.ts
  static/img/send-data/jumpcloud-directory-insights-config.png
  static/img/send-data/jumpcloud-directory-insights-icon.png
  static/img/send-data/jumpcloud-directory-insights-logo.png
Labels: cla-signed, do-not-merge

#2661 opentelemetry docs update
  docs/send-data/opentelemetry-collector/install-collector-linux.md
  docs/send-data/opentelemetry-collector/install-collector-macos.md
  docs/send-data/opentelemetry-collector/install-collector-windows.md
  docs/send-data/opentelemetry-collector/quickstart.md
  sidebars.ts
  static/img/send-data/opentelemetry-collector/linux-terminal.png
  static/img/send-data/opentelemetry-collector/macOs.png
  static/img/send-data/opentelemetry-collector/windows.png
Labels: cla-signed

#2710 CrowdStrike Spotlight c2c doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-spotlight-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/img/send-data/crowdstrike-spotlight-config-main.png
  static/img/send-data/crowdstrike-spotlight-icon.png
Labels: cla-signed, do-not-merge

#2734 JMX - OpenTelemetry Docs
  cid-redirects.json
  docs/integrations/app-development/opentelemetry/jmx-opentelemetry.md
  sidebars.ts
Labels: cla-signed

#2736 ActiveMQ OpenTelemetry App Docs
  cid-redirects.json
  docs/integrations/containers-orchestration/opentelemetry/activemq-opentelemetry.md
  sidebars.ts
Labels: cla-signed

#2740 updated artifactory screenshots
  static/img/integrations/app-development/Art-Cached.png
  static/img/integrations/app-development/Art-Download.png
  static/img/integrations/app-development/Art-Non-Cached.png
  static/img/integrations/app-development/Art-Overview.png
  static/img/integrations/app-development/Art-Traffic.png
  static/img/integrations/app-development/artifactory_app_request_access.png
Labels: cla-signed

#2704 Log Level GA (7/10)
  blog-service/2023-07-10-log-search.md
  docs/search/get-started-with-search/search-page/index.md
  docs/search/get-started-with-search/search-page/log-level.md
  sidebars.ts
  static/img/search/get-started-search/search-page/log-level-error-filter.png
  static/img/search/get-started-search/search-page/log-level-legend.png
Labels: do-not-merge

#2741 FAQ for alert deletion on monitor deletion
  docs/alerts/monitors/alert-response-faq.md
Labels: cla-signed

#2743 Change date for JumpCloud release note
  blog-service/2023-07-10-collections.md
Labels: doc:minor edit, cla-signed

#2733 docker ulm mewboard upgrade doc level changes and screenshot update
  docs/integrations/containers-orchestration/docker-ulm.md
  static/img/integrations/containers-orchestration/docker-cpu-usage.png
  static/img/integrations/containers-orchestration/docker-memory-usage.png
  static/img/integrations/containers-orchestration/docker-network-usage.png
  static/img/integrations/containers-orchestration/docker-overview.png
Labels: cla-signed, hot🔥

#2742 Update .clabot
  .clabot
Labels: cla-signed

#2621 Manual C2C source template
  docs/contributing/templates/c2c-source.md
Labels: cla-signed

#2732 Collector 19.451-1 release docs added
  blog-collector/2023-07-11.md
  docs/send-data/installed-collectors/collector-installation-reference/collector-properties.md
Labels: cla-signed

#2746 Removing Create a Monitor-based SLO from Alert response page
  docs/alerts/monitors/alert-response.md
Labels: cla-signed

#2748 SUMO-224299 - Change release version number
  blog-collector/2023-07-11.md
Labels: doc:minor edit, cla-signed

#2750 Fix link to Cloud SOAR on help home page
  src/helper/features.js
Labels: doc:minor edit, cla-signed

#2632 Public dashboards
  docs/dashboards-new/index.md
  docs/dashboards-new/share-dashboards-outside-org.md
  sidebars.ts
  static/img/dashboards-new/share-option.png
  static/img/dashboards-new/share-option_2.png
  static/img/dashboards-new/share-outside.png
Labels: cla-signed

#2753 CSE Content RelNote 20230711
  blog-cse/2023-07-11-content.md
Labels: cla-signed

#2614 public dashboards release note
  blog-service/2023-07-12-dashboards.md
Labels: cla-signed

#2758 Add cpawar29 to .clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#2759 Update set-up-webhook-connections.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#2760 Update quickstart.md
  docs/manage/ingestion-volume/ingest-budgets/quickstart.md
Labels: cla-signed

#2737 Add resue text
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/custom-tags-configuration.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/kubernetes.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby-on-rails.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-aws-environments.md
Labels: doc:update, cla-signed

#2761 CONN-2333: updated notes to include limitation
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
Labels: cla-signed

#2764 Remove public dashboards from limitations
  docs/dashboards-new/dashboards-migration/index.md
Labels: doc:minor edit, cla-signed

#2765 CSE Release Notes for 7/13/2023
  blog-cse/2023-07-13-application-update.md
Labels: cla-signed

#2763 Fix C2C alpha order
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-azure-ad-reporting-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-identity-protection-source.md
  sidebars.ts
Labels: cla-signed

#2756 added pci windows json otel docs
  docs/integrations/pci-compliance/index.md
  docs/integrations/pci-compliance/opentelemetry/windows-json-opentelemetry.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#2768 Fix broken links in AWS Lamba article
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: doc:minor edit, cla-signed

#2762 Update qualys-vmdr-source.md - Provide guidance on forwarding Qualys …
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
Labels: cla-signed

#2770 Add more micro lessons
  docs/cse/automation-service/about-automation-service.md
  docs/cse/records-signals-entities-insights/global-intelligence-security-insights.md
  docs/manage/ingestion-volume/log-ingestion.md
Labels: doc:update, cla-signed

#2771 CSE Release Notes 2023-07-14
  blog-cse/2023-07-14-content.md
Labels: cla-signed

#2772 Update create-match-list.md
  docs/cse/match-lists-suppressed-lists/create-match-list.md
Labels: cla-signed

#2773 Update standard-match-lists.md
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: cla-signed

#2778 Fixed AWS Lambda app docs for Concurrency metrics related content.
  docs/integrations/amazon-aws/lambda.md
  static/img/integrations/amazon-aws/AWS-Lambda-Configure-Provisioned-Concurrency.png
  static/img/integrations/amazon-aws/AWS-Lambda-Search-Provisioned-Concurrency-Metrics.png
Labels: cla-signed, hot🔥

#2784 Update .clabot
  .clabot
Labels: cla-signed

#2782 Added a section on how to troubleshoot webhook payloads
  docs/alerts/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#2781 Fix the broken link.md
  docs/metrics/metrics-operators/index.md
Labels: cla-signed

#2660 Update Default collector name and Clobber property.
  docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
Labels: cla-signed

#2779 okta C2C doc updated
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/okta-source.md
  static/img/send-data/Okta-version.png
Labels: cla-signed

#2786 Move internal GDrive files to /files/
  docs/integrations/partner-ecosystem-apps.md
  docs/search/search-cheat-sheets/log-operators.md
  static/files/search-operators-cheat-sheet.pdf
  static/files/zerofox-integrations.pdf
Labels: cla-signed

#2789 Update information for collector compression
  docs/send-data/opentelemetry-collector/data-source-configurations/index.md
Labels: cla-signed

#2791 strimzi kafka app documentation complete
  docs/integrations/containers-orchestration/index.md
  docs/integrations/containers-orchestration/strimzi-kafka.md
  sidebars.ts
  static/img/integrations/containers-orchestration/appobservability-messaging-fer.png
  static/img/integrations/containers-orchestration/prometheus-targets.png
  static/img/integrations/containers-orchestration/strimzi.png
Labels: cla-signed

#2796 Update .clabot
  .clabot
Labels: cla-signed

#2794 Strimzi Kafka Cid link added
  cid-redirects.json
Labels: cla-signed, hot🔥

#2797 Late Arriving Metrics Data Documentation
  docs/metrics/introduction/get-started-metrics.md
  docs/metrics/introduction/index.md
Labels: cla-signed

#2801 Correction to the "Configure a Custom Insight" article
  docs/cse/records-signals-entities-insights/configure-custom-insight.md
  static/img/cse/custom-insight.png
Labels: doc:minor edit, cla-signed

#2787 Microsoft Graph Security API v1 --> v2
  blog-service/2022/12-31.md
  blog-service/2023-05-25-apps-microsoft-graph-security.md
  blog-service/2023-05-25-apps-ms-graph-azure-ad-reporting.md
  cid-redirects.json
  docs/contributing/templates/c2c-source.md
  docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/microsoft-graph-azure-ad-reporting.md
  docs/integrations/saas-cloud/microsoft-graph-security-v1.md
  docs/integrations/saas-cloud/microsoft-graph-security-v2.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-azure-ad-reporting-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-identity-protection-source.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#2799 Fix numbering in "Install a Collector on Windows"
  docs/send-data/installed-collectors/linux.md
  docs/send-data/installed-collectors/macos.md
  docs/send-data/installed-collectors/windows.md
Labels: doc:minor edit, cla-signed

#2804 [DO NOT MERGE] Update metrics data ingestion limit
  blog-service/2023-07-20-metrics.md
  docs/metrics/manage-metric-volume/metric-ingestion-and-storage.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/index.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/upload-metrics.md
  docs/send-data/hosted-collectors/http-source/otlp.md
  docs/send-data/installed-collectors/sources/streaming-metrics-source.md
Labels: cla-signed, do-not-merge

#2802 Update cloudflare.md
  docs/integrations/saas-cloud/cloudflare.md
Labels: cla-signed

#2806 Legacy link 301s
  cid-redirects.json
Labels: cla-signed

#2808 Fix/google translate disappearing fix v2
  src/theme/NavbarItem/HtmlNavbarItem.tsx
Labels: cla-signed

#2809 Fix/google translate disappearing fix v3
  src/theme/NavbarItem/HtmlNavbarItem.tsx
Labels: cla-signed

#2803 updated links
  docs/send-data/collect-from-other-data-sources/integrate-halo-event-logs.md
Labels: cla-signed

#2709 Save SLO filters
  blog-service/2023-07-21-saved-slo.md
  docs/observability/reliability-management-slo/create-slo.md
  static/img/observability/DefaultView.png
  static/img/observability/FilterByTagKey.png
  static/img/observability/FilterByTagValue.png
  static/img/observability/ListOfSavedFilters.png
  static/img/observability/MenuOptionsForAnExistingFilter.png
  static/img/observability/SaveANewFilter.png
  static/img/observability/SaveANewFilterDialogue.png
Labels: cla-signed

#2810 Revert Google Translate widget
  src/theme/NavbarItem/HtmlNavbarItem.tsx
Labels: cla-signed

#2811 Fixing note for saved filter views for SLOs
  docs/observability/reliability-management-slo/create-slo.md
Labels: cla-signed

#2813 info about order of forwarded fields added
  docs/manage/data-forwarding/amazon-s3-bucket.md
Labels: cla-signed

#2817 CSE Release Notes July 21, 2023
  blog-cse/2023-07-21-application-update.md
  blog-cse/2023-07-21-content.md
Labels: cla-signed

#2812 Update syslog-logs.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#2792 S3M OTEL doc update
  docs/integrations/app-development/opentelemetry/jfrog-artifactory-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jira-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jmx-opentelemetry.md
  docs/integrations/app-development/opentelemetry/puppet-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/activemq-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/docker-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/kafka-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mariadb-opentelemetry.md
  docs/integrations/databases/opentelemetry/memcached-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/active-directory-json-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-linux-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
  docs/integrations/pci-compliance/opentelemetry/windows-json-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/nginx-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/squid-proxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/varnish-opentelemetry.md
Labels: cla-signed, do-not-merge

#2816 Update palo-alto-firewall-10.md - Updated Reference Link for Log Forw…
  docs/integrations/cloud-security-monitoring-analytics/palo-alto-firewall-10.md
Labels: cla-signed

#2815 Update application-components.md
  docs/observability/application-components.md
Labels: cla-signed

#2818 Fix image coding in Cloud SIEM schema and sensors sections
  docs/cse/schema/attributes-map-to-records.md
  docs/cse/schema/create-structured-log-mapping.md
  docs/cse/schema/cse-normalized-classification.md
  docs/cse/schema/cse-record-types.md
  docs/cse/schema/field-mapping-security-event-sources.md
  docs/cse/schema/parser-editor.md
  docs/cse/schema/parser-troubleshooting-tips.md
  docs/cse/schema/parsing-language-reference-guide.md
  docs/cse/schema/record-processing-pipeline.md
  docs/cse/schema/username-and-hostname-normalization.md
  docs/cse/sensors/ingest-zeek-logs.md
  docs/cse/sensors/network-sensor-deployment-guide.md
  docs/cse/sensors/network-sensor-troubleshooting.md
Labels: doc:minor edit, cla-signed

#2805 Update share-dashboards-outside-org.md
  docs/dashboards-new/share-dashboards-outside-org.md
Labels: cla-signed

#2819 Fix image coding in the Cloud SIEM Integrations articles
  docs/cse/integrations/configuring-threatq-source-in-cse.md
  docs/cse/integrations/enable-virustotal-enrichment.md
  docs/cse/integrations/enrichments-and-indicators.md
  docs/cse/integrations/insight-enrichment-server.md
  docs/cse/integrations/integrate-cse-with-taxii-feed.md
  docs/cse/integrations/security-incident-response-integration.md
Labels: doc:minor edit, cla-signed

#2826 Fix typo in "Public Dashboards" release note
  blog-service/2023-07-12-dashboards.md
Labels: doc:minor edit, cla-signed

#2828 Add jtrakitan
  .clabot
Labels: cla-signed

#2820 Updated Gmail Trace Logs Source doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  static/img/send-data/gmail-trace-logs-icon.png
  static/img/send-data/gmail-trace-logs_config_main.png
Labels: cla-signed

#2827 Updated Q1 2023 security apps and C2Cs.
  blog-service/2023-07-25-apps.md
Labels: doc:new, cla-signed

#2824 Update collect-windows-custom-channel-logs.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#2832 cid redirects added
  cid-redirects.json
Labels: cla-signed, hot🔥

#2834 Add webhook example to Cloud SOAR documentation
  docs/cloud-soar/cloud-soar-integration-framework.md
Labels: doc:new, cla-signed

#2836 Update kubernetes-metrics.md
  docs/metrics/kubernetes-metrics.md
Labels: cla-signed

#2837 doc updated
  docs/integrations/pci-compliance/opentelemetry/windows-json-opentelemetry.md
Labels: cla-signed

#2840 404 fixes
  cid-redirects.json
Labels: cla-signed

#2838 Remove duplicate redirect entries
  cid-redirects.json
Labels: cla-signed

#2847 Template edits
  docs/contributing/templates/generic-doc.md
  docs/contributing/templates/partner-app.md
  sidebars.ts
Labels: cla-signed

#2849 Add / to end of API URLs
  docs/api/getting-started.md
Labels: doc:minor edit, cla-signed

#2850 Doc changes for addition of dashboard in windows app. Correction in l…
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
Labels: cla-signed

#2851 Update knowbe4-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#2658 Cloud security analytics guide
  docs/cloud-security-analytics/application-security.md
  docs/cloud-security-analytics/audit-and-compliance.md
  docs/cloud-security-analytics/data-lake.md
  docs/cloud-security-analytics/index.md
  docs/cloud-security-analytics/introduction-to-cloud-security-analytics.md
  docs/cloud-security-analytics/threat-detection-and-investigation.md
  docs/cloud-soar/index.md
  docs/cse/get-started-with-cloud-siem/index.md
  docs/cse/index.md
  docs/cse/introduction-to-cloud-siem.md
  docs/security/index.md
  sidebars.ts
  static/img/csa/24-hours.png
  static/img/csa/add-map-panel.png
  static/img/csa/add-time-series-panel.png
  static/img/csa/bar-chart-setting.png
  static/img/csa/brute-force-attack-panel.png
  static/img/csa/create-new-dashboard.png
  static/img/csa/create-template-variable-dialog.png
  static/img/csa/create-template-variable.png
  static/img/csa/create-variable-1.png
  static/img/csa/create-variable-2.png
  static/img/csa/dashboard-with-failed-login-attempts-dashboard.png
  static/img/csa/data-collection.png
  static/img/csa/data-pipeline.png
  static/img/csa/example-dashboard.png
  static/img/csa/export-dashboard-dialog.png
  static/img/csa/export-dashboard.png
  static/img/csa/filter-icon.png
  static/img/csa/geo-location-panel.png
  static/img/csa/new-query.png
  static/img/csa/rename-to-cloud-security-dashboard.png
  static/img/csa/time-series-panel.png
  static/img/csa/top-10-user-activity-panel.png
  static/img/csa/windows-security-analytics.png
  static/img/security/practitioner_messaging_feature_matrix_chart_v01.png
  static/img/security/practitioner_messaging_feature_overlaps_venn diagram_opt_01A.png
Labels: doc:new, cla-signed

#2854 Add info on "JSON Array Notation" to Zscaler article
  docs/integrations/security-threat-detection/zscaler-internet-access.md
Labels: cla-signed

#2856 Add note about storage credits
  docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
Labels: doc:minor edit, cla-signed

#2852 google workspace docs updated
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-source.md
  static/img/send-data/google-workspace.png
Labels: cla-signed

#2859 note in jenkins app doc, after jenkins upgrade
  docs/integrations/app-development/jenkins.md
Labels: cla-signed

#2858 Fix cards
  docs/cloud-security-analytics/index.md
Labels: doc:minor edit, cla-signed

#2862 Create collector 2022 release notes archive
  blog-collector/2022-03-03.md
  blog-collector/2022-04-18.md
  blog-collector/2022-05-11.md
  blog-collector/2022-07-07.md
  blog-collector/2022-07-20.md
  blog-collector/2022-09-26.md
  blog-collector/2022-10-12-welcome.md
  blog-collector/2022-10-26.md
  blog-collector/2022-11-04.md
  blog-collector/2022-12-14.md
  blog-collector/2022/12-31.md
Labels: doc:update, cla-signed

#2864 Create 2022 Cloud SIEM release notes archive
  blog-cse/2022-04-30-archive.md
  blog-cse/2022-05-31-archive.md
  blog-cse/2022-06-30-archive.md
  blog-cse/2022-07-31-archive.md
  blog-cse/2022-08-18.md
  blog-cse/2022-08-25.md
  blog-cse/2022-09-01.md
  blog-cse/2022-09-08.md
  blog-cse/2022-09-09.md
  blog-cse/2022-09-12.md
  blog-cse/2022-09-19.md
  blog-cse/2022-09-29.md
  blog-cse/2022-10-06-app-content.md
  blog-cse/2022-10-12-welcome.md
  blog-cse/2022-10-13-application-update.md
  blog-cse/2022-10-20-application-update.md
  blog-cse/2022-10-20-content.md
  blog-cse/2022-10-27-content.md
  blog-cse/2022-11-10-content.md
  blog-cse/2022-11-15-content.md
  blog-cse/2022-11-17-content.md
  blog-cse/2022-11-22-content.md
  blog-cse/2022-12-01-content.md
  blog-cse/2022-12-08-content.md
  blog-cse/2022-12-13-application-update.md
  blog-cse/2022-12-14-content.md
  blog-cse/2022-12-21-content.md
  blog-cse/2022/12-31.md
Labels: doc:update, cla-signed

#2769 Split Dashboards and Alerts in nav/dropdown
  docusaurus.config.js
  sidebars.ts
Labels: doc:minor edit, cla-signed
