Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-10, with the labels that each got.

#3141 Azure doc only apps (set 3)
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-analysis-services.md
  docs/integrations/microsoft-azure/azure-api-management.md
  docs/integrations/microsoft-azure/azure-app-configuration.md
  docs/integrations/microsoft-azure/azure-app-service-environment.md
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  docs/integrations/microsoft-azure/azure-automation.md
  docs/integrations/microsoft-azure/azure-hdinsight.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/microsoft-dynamics365-customer-insights.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-analysis-services.png
  static/img/integrations/microsoft-azure/azure-api-management.png
  static/img/integrations/microsoft-azure/azure-app-configuration.png
  static/img/integrations/microsoft-azure/azure-app-service-environment.png
  static/img/integrations/microsoft-azure/azure-app-service-plan.png
  static/img/integrations/microsoft-azure/azure-automation.png
  static/img/integrations/microsoft-azure/azure-hdinsight.png
  static/img/integrations/microsoft-azure/azure-storage.png
  static/img/integrations/microsoft-azure/microsoft-dynamics365-customer-insights.png
Labels: doc:new, cla-signed

#2718 TRIDENT-18006 - MITRE coverage
  docs/cse/administration/index.md
  docs/cse/administration/mitre-coverage.md
  sidebars.ts
  static/img/cse/mitre-coverage-page.png
  static/img/cse/mitre-details.png
  static/img/cse/mitre-ttp-filter.png
  static/img/cse/mitre-vendor-product-filter.png
Labels: doc:new, cla-signed

#3151 spellcheck fixes
  .github/workflows/pr.yml
  docs/cloud-soar/mssp.md
  docs/cse/rules/cse-built-in-rules.md
  docs/integrations/amazon-aws/lambda.md
  docs/integrations/amazon-aws/rds.md
  docs/integrations/saas-cloud/microsoft-graph-azure-ad-reporting.md
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/observability/kubernetes/alerts.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/search/get-started-with-search/search-basics/about-search-basics.md
  docs/search/get-started-with-search/suggested-searches/cisco-asa-parser.md
  docs/search/optimize-search-performance.md
  docs/send-data/collection/processing-rules/include-and-exclude-rules.md
Labels: cla-signed

#3150 Revert "Azure doc only apps (set 3)"
  .github/workflows/pr.yml
  cid-redirects.json
  docs/cloud-soar/mssp.md
  docs/cse/rules/cse-built-in-rules.md
  docs/integrations/amazon-aws/lambda.md
  docs/integrations/amazon-aws/rds.md
  docs/integrations/microsoft-azure/azure-analysis-services.md
  docs/integrations/microsoft-azure/azure-api-management.md
  docs/integrations/microsoft-azure/azure-app-configuration.md
  docs/integrations/microsoft-azure/azure-app-service-environment.md
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  docs/integrations/microsoft-azure/azure-automation.md
  docs/integrations/microsoft-azure/azure-hdinsight.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/microsoft-dynamics365-customer-insights.md
  docs/integrations/saas-cloud/microsoft-graph-azure-ad-reporting.md
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/observability/kubernetes/alerts.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/search/get-started-with-search/search-basics/about-search-basics.md
  docs/search/get-started-with-search/suggested-searches/cisco-asa-parser.md
  docs/search/optimize-search-performance.md
  docs/send-data/collection/processing-rules/include-and-exclude-rules.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-analysis-services.png
  static/img/integrations/microsoft-azure/azure-api-management.png
  static/img/integrations/microsoft-azure/azure-app-configuration.png
  static/img/integrations/microsoft-azure/azure-app-service-environment.png
  static/img/integrations/microsoft-azure/azure-app-service-plan.png
  static/img/integrations/microsoft-azure/azure-automation.png
  static/img/integrations/microsoft-azure/azure-hdinsight.png
  static/img/integrations/microsoft-azure/azure-storage.png
  static/img/integrations/microsoft-azure/microsoft-dynamics365-customer-insights.png
Labels: cla-signed

#3149 Update pr.yml
  .github/workflows/pr.yml
Labels: cla-signed

#3146 2023-10-02 CSE Release Note
  .github/workflows/pr.yml
  blog-cse/2023-10-02-application-update.md
  static/img/release-notes/cse/Mitre-Explorer.png
Labels: cla-signed

#3144 Create 2023-10-02-dashboards
  blog-service/2023-10-02-dashboards.md
Labels: cla-signed

#3148 Remove multiple signals from Insight
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  static/img/cse/signal-list-area.png
Labels: doc:update, cla-signed

#3152 Update .clabot
  .clabot
Labels: cla-signed

#3143 Proposed yarn.lock edits
  yarn.lock
Labels: cla-signed

#3154 Update 2023-10-02-application-update.md
  blog-cse/2023-10-02-application-update.md
Labels: cla-signed

#3155 Update crowdstrike spotlight docs with troubleshooting section
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-spotlight-source.md
Labels: cla-signed

#3145 New SIGNL4 alerting article
  docs/alerts/webhook-connections/signl4.md
  sidebars.ts
Labels: doc:new, cla-signed

#3157 Update .clabot
  .clabot
Labels: cla-signed

#3153 Fixing PR builder errors for PR 3141
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-analysis-services.md
  docs/integrations/microsoft-azure/azure-api-management.md
  docs/integrations/microsoft-azure/azure-app-configuration.md
  docs/integrations/microsoft-azure/azure-app-service-environment.md
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  docs/integrations/microsoft-azure/azure-automation.md
  docs/integrations/microsoft-azure/azure-cosmos-db-for-postgresql.md
  docs/integrations/microsoft-azure/azure-cosmos-db.md
  docs/integrations/microsoft-azure/azure-database-for-mariadb.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/microsoft-azure/azure-front-door.md
  docs/integrations/microsoft-azure/azure-hdinsight.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-network-interface.md
  docs/integrations/microsoft-azure/azure-service-bus.md
  docs/integrations/microsoft-azure/azure-sql-elastic-pool.md
  docs/integrations/microsoft-azure/azure-stream-analytics.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/microsoft-dynamics365-customer-insights.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-analysis-services.png
  static/img/integrations/microsoft-azure/azure-api-management.png
  static/img/integrations/microsoft-azure/azure-app-configuration.png
  static/img/integrations/microsoft-azure/azure-app-service-environment.png
  static/img/integrations/microsoft-azure/azure-app-service-plan.png
  static/img/integrations/microsoft-azure/azure-automation.png
  static/img/integrations/microsoft-azure/azure-hdinsight.png
  static/img/integrations/microsoft-azure/azure-storage.png
  static/img/integrations/microsoft-azure/microsoft-dynamics365-customer-insights.png
Labels: cla-signed

#3156 Update collector-api-methods-examples.md
  docs/api/collector-management/collector-api-methods-examples.md
Labels: cla-signed

#3158 Update Slack C2C to document details around rate limits
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/slack-source.md
Labels: cla-signed

#3161 Repo/Actions test
  docs/metrics/metrics-queries/map-charts.md
Labels: cla-signed

#3162 Google Console video indexing fixes
  docs/dashboards/explore-view.md
  docs/get-started/help.md
  docs/reuse/apps/create-aws-s3-source.md
  docs/send-data/hosted-collectors/amazon-aws/grant-access-aws-product.md
  static/img/get-started/Help-Support-product.png
  static/img/get-started/Help-Support.png
Labels: cla-signed

#3134 Google Cloud Platform services release note
  blog-service/2023-10-04-gcp-apps.md
Labels: cla-signed

#3139 Webhook setup guides release notes
  blog-service/2023-10-04-webhooks-doc.md
Labels: cla-signed

#3159 Add note about View Rules role capability
  docs/cse/administration/mitre-coverage.md
Labels: doc:minor edit, cla-signed

#3169 Fix match list broken link
  docs/cse/match-lists-suppressed-lists/create-match-list.md
Labels: doc:minor edit, cla-signed

#3035 OTEL Install Collector for Ansible, Chef, Puppet
  cid-redirects.json
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/databases/cassandra.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-trace-logs.md
  docs/send-data/opentelemetry-collector/faq.md
  docs/send-data/opentelemetry-collector/index.md
  docs/send-data/opentelemetry-collector/install-collector/ansible.md
  docs/send-data/opentelemetry-collector/install-collector/chef.md
  docs/send-data/opentelemetry-collector/install-collector/index.md
  docs/send-data/opentelemetry-collector/install-collector/linux.md
  docs/send-data/opentelemetry-collector/install-collector/macos.md
  docs/send-data/opentelemetry-collector/install-collector/puppet.md
  docs/send-data/opentelemetry-collector/install-collector/windows.md
  docs/send-data/opentelemetry-collector/troubleshooting.md
  sidebars.ts
  static/img/integrations/microsoft-azure/windows.png
  static/img/send-data/ansible-logo.png
  static/img/send-data/chef-logo.png
  static/img/send-data/mac-logo.png
  static/img/send-data/opentelemetry-collector/ansible.png
  static/img/send-data/opentelemetry-collector/chef.png
  static/img/send-data/opentelemetry-collector/puppet.png
Labels: cla-signed, do-not-merge

#3137 Setup Guides for Amazon Web Service (AWS) integrations
  blog-service/2023-10-05-aws-docs.md
Labels: cla-signed

#3163 Setup Guides for Azure Services
  blog-service/2023-10-05-azure.md
Labels: cla-signed

#3164 New Setup Guides
  blog-service/2023-10-05-new-guides.md
Labels: cla-signed, do-not-merge

#3174 Trident 18486 - Add parsing patterns
  .github/workflows/pr.yml
  docs/cse/schema/parsing-language-reference-guide.md
  docs/cse/schema/parsing-patterns.md
  sidebars.ts
Labels: doc:new, cla-signed

#3167 Add features in subscription table
  docs/manage/manage-subscription/cloud-flex-accounts.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
Labels: doc:update, cla-signed

#3170 node and actions upgrades in pr.yml
  .github/workflows/pr.yml
Labels: doc:site tech, cla-signed, do-not-merge

#3177 Test PR for pr.yml edits
  docs/metrics/index.md
Labels: cla-signed

#3172 timezone instructions updated
  docs/integrations/amazon-aws/api-gateway.md
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
  docs/integrations/amazon-aws/aurora-postgresql-ulm.md
  docs/integrations/amazon-aws/dynamodb.md
  docs/integrations/amazon-aws/ec2-cloudwatch-metrics.md
  docs/integrations/amazon-aws/elastic-container-service-container-insights-cloudwatch.md
  docs/integrations/amazon-aws/elastic-container-service.md
  docs/integrations/amazon-aws/elasticache.md
  docs/integrations/amazon-aws/kinesis-streams.md
  docs/integrations/amazon-aws/rds.md
  docs/integrations/amazon-aws/redshift-ulm.md
  docs/integrations/amazon-aws/sns.md
  docs/integrations/amazon-aws/sqs.md
  docs/integrations/amazon-aws/waf.md
Labels: cla-signed

#3173 Update sophos-central-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sophos-central-source.md
Labels: cla-signed

#3180 Add information about OpenTelmetry Collector Endpoints
  docs/api/getting-started.md
Labels: cla-signed

#3181 Update download-collector-from-static-url.md
  docs/send-data/installed-collectors/collector-installation-reference/download-collector-from-static-url.md
Labels: cla-signed

#3187 Add janek-sumo to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#3182 Remove asterisk from screenshot
  static/img/cse/create-entity-group-inventory.png
Labels: doc:minor edit, cla-signed

#3184 Add pbaroni to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#3188 Update set-up-traces-collection-for-kubernetes-environments.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-kubernetes-environments.md
Labels: cla-signed

#3186 Fix AWS Lambda link in the alerts webhook connections page
  docs/alerts/webhook-connections/index.md
Labels: cla-signed

#3192 Included State "GATHERING RESULTS FROM SUBQUERIES"
  docs/api/search-job.md
Labels: cla-signed

#3196 Add SIEM release note 1023-10-11-content
  blog-cse/2023-10-11-content.md
Labels: doc:new, cla-signed

#3198 Update quickstart.md
  docs/manage/ingestion-volume/ingest-budgets/quickstart.md
Labels: cla-signed

#3193 Add rmamilla-sumo to clabot
  .clabot
Labels: cla-signed

#3200 Update Signal Index Migration FAQ
  docs/cse/records-signals-entities-insights/signal-index-migration-faq.md
Labels: doc:minor edit, cla-signed

#3197 Add audit index section
  blog-developer/2023-06-15-api.md
  blog-service/2016/12-31.md
  blog-service/2018/12-31.md
  blog-service/2019/12-31.md
  blog-service/2020/12-31.md
  blog-service/2023-05-04-manage-account.md
  cid-redirects.json
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/webhook-connections/audit-index.md
  docs/cse/get-started-with-cloud-siem/onboarding-checklist-cse.md
  docs/dashboards-classic/share-dashboard-outside-org.md
  docs/dashboards/share-dashboards-outside-org.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/overview.md
  docs/get-started/sumo-logic-ui.md
  docs/integrations/sumo-apps/audit.md
  docs/integrations/sumo-apps/enterprise-audit.md
  docs/integrations/sumo-apps/infrequent-data-tier.md
  docs/manage/data-archiving/archive.md
  docs/manage/data-forwarding/manage.md
  docs/manage/health-events.md
  docs/manage/ingestion-volume/ingest-budgets/index.md
  docs/manage/ingestion-volume/log-ingestion.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/manage/security/audit-indexes/audit-event-index.md
  docs/manage/security/audit-indexes/audit-index-access.md
  docs/manage/security/audit-indexes/audit-index.md
  docs/manage/security/audit-indexes/index.md
  docs/manage/security/audit-indexes/search-audit-index.md
  docs/manage/security/index.md
  docs/manage/users-roles/roles/rbac-for-indexes.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/search/index.md
  docs/send-data/collection/restart-collectors.md
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
  i18n/ja/alerts/alerts/monitors/monitor-faq.md
  i18n/ja/alerts/alerts/scheduled-searches/faqs/failed-scheduled-search.md
  i18n/ja/alerts/alerts/scheduled-searches/faqs/suspended-scheduled-search.md
  sidebars.ts
Labels: doc:new, cla-signed

#3201 Replace ADFS screenshot
  static/img/security/adfs06.png
Labels: doc:minor edit, cla-signed

#3203 Update metric-ingestion-and-storage.md
  docs/metrics/manage-metric-volume/metric-ingestion-and-storage.md
Labels: cla-signed

#3207 Update log ingestion articles
  docs/get-started/sign-up.md
  docs/manage/ingestion-volume/log-ingestion.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/manage/manage-subscription/cloud-flex-accounts.md
  docs/manage/users-roles/roles/role-capabilities.md
Labels: doc:update, cla-signed

#3205 Remove Ideas Portal link
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
Labels: doc:minor edit, cla-signed

#3209 Revert "Update metric-ingestion-and-storage.md (#3203)"
  docs/metrics/manage-metric-volume/metric-ingestion-and-storage.md
Labels: doc:minor edit, cla-signed

#3210 Update metric-ingestion-and-storage
  docs/metrics/manage-metric-volume/metric-ingestion-and-storage.md
Labels: doc:minor edit, cla-signed

#3208 Replace image for SP initiated login
  docs/manage/security/saml/integrate-sumo-with-azure-ad.md
  static/img/security/sp-init-settings.png
Labels: doc:minor edit, cla-signed

#3213 Update create-an-entity-group.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
Labels: cla-signed

#3214 Update sentinelone-mgmt-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sentinelone-mgmt-api-source.md
Labels: cla-signed

#3218 Add rnishtala-sumo to the clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#3216 MET-0: Remove false information about default quantization rollup selection
  docs/metrics/introduction/metric-quantization.md
Labels: cla-signed

#3220 Re-do metrics quant change (#3216)
  docs/metrics/introduction/metric-quantization.md
Labels: cla-signed

#3223 Update last instance of "Cloud SIEM Enterprise"
  docs/send-data/installed-collectors/sources/windows-active-directory-inventory-source.md
Labels: doc:minor edit, cla-signed

#3211 add automation bridge with podman version
  docs/cloud-soar/cloud-soar-bridge.md
  docs/cse/automation-service/automation-service-bridge.md
Labels: cla-signed

#3215 New Setup Guides for Security release note
  blog-service/2023-10-18-security-apps.md
Labels: cla-signed

#3227 Update sdo-manual-configuration.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
Labels: cla-signed

#3226 MET-0: Clean up metrics quantization section
  docs/metrics/introduction/metric-quantization.md
Labels: cla-signed

#3221 Draft proposal - yarn install action
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#3232 Release note for signal forwarding deprecation
  blog-cse/2023-10-18-application-update.md
Labels: doc:new, cla-signed

#3160 Change CSA to Cloud Infracture Security
  cid-redirects.json
  docs/cloud-infrastructure-security/application-security.md
  docs/cloud-infrastructure-security/audit-and-compliance.md
  docs/cloud-infrastructure-security/data-lake.md
  docs/cloud-infrastructure-security/index.md
  docs/cloud-infrastructure-security/introduction-to-cloud-infrastructure-security.md
  docs/cloud-infrastructure-security/threat-detection-and-investigation.md
  docs/cloud-security-analytics/index.md
  docs/get-started/training-certification-faq.md
  docs/security/index.md
  sidebars.ts
  static/img/security/practitioner_messaging_feature_matrix_chart_v02.png
  static/img/security/practitioner_messaging_feature_overlaps_venn_diagram_opt_01A.png
  static/img/security/practitioner_messaging_feature_overlaps_venn_diagram_opt_02A.png
Labels: doc:update, cla-signed

#3183 Add Cloud SOAR Audit Index documentation
  docs/cloud-soar/audit-event-index.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/index.md
  sidebars.ts
Labels: cla-signed

#3237 feat: switch from aws distro to sumo distro
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-aws-environments.md
Labels: cla-signed

#3229 Add Automation menu
  docs/cse/automation-service/about-automation-service.md
  static/img/cse/automation-menu-in-nav-bar.png
  static/img/cse/automations-integrations-list.png
  static/img/cse/automations-playbook-list.png
Labels: doc:update, cla-signed

#3233 Connection, dashboard, dashboard-new, and integrations image updated
  static/img/connection-and-integration/connections.png
  static/img/dashboards-new/create-dashboard-new/DB_Metrics_Query_Chart-results.png
  static/img/dashboards-new/create-dashboard-new/DB_Metrics_Query_Metric.png
  static/img/dashboards-new/create-dashboard-new/DB_Name_NewDashboard.png
  static/img/dashboards-new/create-dashboard-new/DB_New_Panel.png
  static/img/dashboards-new/create-dashboard-new/DB_Query_Save_panel.png
  static/img/dashboards-new/create-dashboard-new/Dashboard-name.png
  static/img/dashboards-new/create-dashboard-new/custom-dashboard.png
  static/img/dashboards-new/db-drilldown.png
  static/img/dashboards-new/drill-root-causes/Explore_Navigate_View_Dashboard.png
  static/img/dashboards-new/drill-root-causes/k8s-nodes-example.png
  static/img/dashboards-new/explore/aws-view.png
  static/img/dashboards-new/explore/stack-linking.png
  static/img/dashboards-new/link-dashboard-explore/CDB_Dashboard_Link_New-menu-option.png
  static/img/dashboards-new/link-dashboard-explore/CDB_Dashboard_Link_Success.png
  static/img/dashboards-new/link-dashboard-explore/CDB_Save_dashboard.png
  static/img/dashboards-new/link-dashboard-explore/CDB_Stack_Linking_option.png
  static/img/dashboards-new/link-dashboard-explore/CDB_Verify_Dashboard_Link1.png
  static/img/dashboards-new/link-dashboard-explore/K8s_Stack-Linking_option.png
  static/img/dashboards-new/link-dashboard-explore/explore-with-location-tooltip.png
  static/img/dashboards-new/panels/modify-chart/Logs-and-Metrics.png
  static/img/dashboards-new/set-custom-time-ranges/dashboard-setting-default.png
  static/img/dashboards-new/set-custom-time-ranges/dashboard-setting-modified.png
  static/img/dashboards-new/share-dashboard-new/K8_Save_Custom_Dashboard.png
  static/img/dashboards-new/share-dashboard-new/Share_Dashboard_option.png
  static/img/dashboards-new/share-dashboard-new/share-icon.png
  static/img/dashboards/SwitchtoAllShared.png
  static/img/integrations/containers-orchestration/activemq-images.png
  static/img/integrations/containers-orchestration/appobservability-messaging-fer.png
  static/img/integrations/databases/PostgreSQL-Relational.png
  static/img/integrations/saas-cloud/Acquia_Drupal_Requests_Overview.png
  static/img/integrations/saas-cloud/Acquia_FPM_Overview.png
  static/img/integrations/saas-cloud/Akamai-Overview.png
  static/img/integrations/saas-cloud/Akamai-QOS.png
  static/img/integrations/saas-cloud/Akamai-Visitors.png
  static/img/integrations/saas-cloud/Akamai-Web-Application.png
  static/img/integrations/saas-cloud/Cloudflare-Performance_Hostname.png
  static/img/integrations/saas-cloud/Cloudflare-Performance_Static.png
  static/img/integrations/saas-cloud/Cloudflare-Security-Overview.png
  static/img/integrations/saas-cloud/Cloudflare-Security_WAF.png
  static/img/integrations/saas-cloud/Cloudflare-Snapshot.png
  static/img/integrations/saas-cloud/Cloudflare_-_Reliability.png
  static/img/integrations/saas-cloud/Cloudflare_Security-RateLimiting.png
  static/img/integrations/saas-cloud/Cloudflare_Security_Bot_Management.png
  static/img/integrations/saas-cloud/PagerDuty-V3-Incidents-Overview.png
  static/img/integrations/saas-cloud/PagerDutyV2-IncidentsOverview.png
  static/img/integrations/saas-cloud/Palo-Alto-Cortex-XDR-Incidents-Overview.png
  static/img/integrations/saas-cloud/SentinelOne-Agent-Overview.png
  static/img/integrations/saas-cloud/SentinelOne-Threat-Analysis.png
  static/img/integrations/saas-cloud/SentinelOne-Threat-Overview.png
  static/img/integrations/saas-cloud/akamai_app_origin.png
  static/img/integrations/saas-cloud/akamai_app_security.png
  static/img/integrations/sumo-apps/Request_App.png
  static/img/integrations/sumo-apps/audit-app-catalog.png
Labels: cla-signed

#3242 Add fzampori to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#3241 Cloud SOAR and Automation Service first release notes
  blog-csoar/2023-10-20-application-update.md
Labels: cla-signed

#3243 Add alesscorona to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#3238 TRIDENT-15830 Scheduled Actions: Enhance Exit Condition Configuration
  docs/cloud-soar/cloud-soar-integration-framework.md
Labels: cla-signed

#3236 Fix step in SIR integration article
  docs/cse/integrations/security-incident-response-integration.md
Labels: doc:minor edit, cla-signed

#3231 Helm chart v4 update
  static/img/kubernetes/K8s-architecture.png
Labels: cla-signed, do-not-merge

#3250 2023 10 23 content
  blog-csoar/2023-10-23-content.md
Labels: doc:new

#3251 Update API endpoint explanation for SIR integration
  docs/cse/integrations/security-incident-response-integration.md
Labels: doc:minor edit, cla-signed

#3248 Add salvatoremosca to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#3252 Remove references to legacy subscription plans
  docs/alerts/monitors/overview.md
  docs/get-started/sign-up.md
Labels: doc:update, cla-signed

#3202 Scheduled view doc update
  blog-service/2023-10-25-scheduled-view-id.md
  docs/manage/scheduled-views/view-list-scheduled-views.md
  static/img/scheduled-views/sched-view-details.png
Labels: cla-signed

#3225 AWSO v2.7.0
  cid-redirects.json
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/integrations/amazon-rds.md
  docs/observability/aws/integrations/aws-rds-metrics.md
  docs/observability/aws/integrations/index.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
  sidebars.ts
Labels: cla-signed

#3246 Release notes - Helm chart v4
  blog-service/2023-10-25-collection.md
Labels: cla-signed

#3217 Adding documention for hashing and masking using the transform processor
  docs/send-data/opentelemetry-collector/data-transformations.md
  docs/send-data/opentelemetry-collector/index.md
  docs/send-data/opentelemetry-collector/install-collector/index.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#3255 Fix broken image links in the product list article
  docs/integrations/product-list.md
Labels: doc:minor edit, cla-signed

#3133 Collector release notes
  blog-collector/2023-10-26.md
  docs/send-data/installed-collectors/collector-installation-reference/advanced-ui-installer-settings.md
  static/img/send-data/permissions.png
  static/img/send-data/registry-editor.png
Labels: cla-signed

#3256 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#3258 Minor update to the "Configure a Custom Insight" article
  docs/cse/records-signals-entities-insights/configure-custom-insight.md
Labels: doc:minor edit, cla-signed

#3259 Create 2023-10-26-content.md
  blog-cse/2023-10-26-content.md
Labels: cla-signed

#3260 CSE Application Release Note 2023-10-26
  blog-cse/2023-10-26-application-update.md
  static/img/release-notes/cse/custom-insight-status-colors.png
  static/img/release-notes/cse/custom-insight-status-widget.png
Labels: cla-signed

#2843 Make "Index Based Search Filter" available for open beta
  blog-service/2023-10-27-manage.md
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
  docs/manage/users-roles/roles/create-manage-roles.md
  docs/manage/users-roles/roles/rbac-for-indexes.md
  sidebars.ts
Labels: doc:new, cla-signed

#3261 Update Links in the Salesforce C2C Doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
Labels: cla-signed

#3263 Revert "Update Links in the Salesforce C2C Doc"
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
Labels: cla-signed

#3264 Redo updates for PR #3261
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
Labels: doc:minor edit, cla-signed

#3265 Custom Insight status updates
  docs/cse/administration/manage-custom-insight-statuses.md
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
  static/img/cse/hud.png
  static/img/cse/new-status.png
  static/img/cse/reorder-icons.png
  static/img/cse/status-dropdown.png
  static/img/cse/workflow-page.png
Labels: doc:update, cla-signed

#3269 Update .clabot
  .clabot
Labels: cla-signed

#3262 Automation Service as a platform service
  blog-cse/2023-04-21-application-update.md
  blog-cse/2023-09-11-application-update.md
  cid-redirects.json
  docs/cse/administration/create-cse-actions.md
  docs/cse/administration/cse-user-accounts-and-roles.md
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/index.md
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/cse/automation/index.md
  docs/cse/get-started-with-cloud-siem/onboarding-checklist-cse.md
  docs/cse/index.md
  docs/cse/integrations/insight-enrichment-server.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/platform-services/automation-service/automation-service-app-central.md
  docs/platform-services/automation-service/automation-service-bridge.md
  docs/platform-services/automation-service/automation-service-integration-framework.md
  docs/platform-services/automation-service/automation-service-integrations.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/platform-services/automation-service/index.md
  docs/platform-services/index.md
  docs/reuse/action-limits.md
  docusaurus.config.js
  sidebars.ts
  static/img/cse/automation-service-app-central.png
  static/img/platform-services/app-central-main-screen.png
  static/img/platform-services/bridge-main-screen.png
  static/img/platform-services/integrations-main-screen.png
  static/img/platform-services/playbook-main-screen.png
Labels: doc:new, cla-signed, do-not-merge

#3268 docs: fix minor typo powerhell -> powershell
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
Labels: cla-signed

#3267 Update github.md
  docs/integrations/app-development/github.md
Labels: doc:update, cla-signed

#3191 CONN-2590: Update CyberArk EPM Doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
  static/img/send-data/cyberark-source.png
Labels: cla-signed, do-not-merge

#3271 Add Role Based Search Index article to beta section
  sidebars.ts
Labels: doc:minor edit, cla-signed
