Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-06, with the labels that each got.

#2533 revert GA update
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  sidebars.ts
Labels: cla-signed

#2532 Update fields.md
  docs/manage/fields.md
Labels: cla-signed

#2531 Update standard-match-lists.md
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: cla-signed

#2537 Update .clabot
  .clabot
Labels: cla-signed

#2538 docs(lambda): update python documentation
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: cla-signed

#2526 Update styleguide.md
  docs/contributing/style-guide.md
Labels: cla-signed

#2527 Fix legacy/404 links
  cid-redirects.json
Labels: cla-signed

#2521 Updated AWS Lambda Cloudwatch logs collection section.
  docs/integrations/amazon-aws/lambda.md
Labels: cla-signed, hot🔥

#2534 data access level release note
  blog-service/2023-06-01-dashboards.md
Labels: cla-signed, do-not-merge

#2530 Update iis-10.md
  docs/integrations/web-servers/iis-10.md
Labels: cla-signed

#2519 Update feature difference table
  docs/dashboards-new/about.md
Labels: cla-signed

#2548 Update cla
  .clabot
Labels: cla-signed

#2545 updated migrated screenshots
  static/img/integrations/amazon-aws/Kinesis-Events.png
  static/img/integrations/amazon-aws/Kinesis-Metrics.png
  static/img/integrations/google/GoogleAppEngineActivity.png
  static/img/integrations/google/GoogleAppEngineOverview.png
  static/img/integrations/google/GoogleAppEngineRequestActivity.png
  static/img/integrations/saas-cloud/FastlyCDNOriginPerformancepng.png
  static/img/integrations/saas-cloud/FastlyCDNVisitors.png
  static/img/integrations/saas-cloud/WAF-OWASP.png
  static/img/integrations/saas-cloud/WAF-Overview.png
  static/img/integrations/saas-cloud/fastly-cdn-overview.png
  static/img/integrations/saas-cloud/fastly-cdn-quality-of-service.png
  static/img/integrations/saas-cloud/fastly-waf-offenders.png
Labels: cla-signed

#2511 Update CyberARK EPM docs
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
Labels: cla-signed

#2541 Add hub page for Automation Service
  docs/cse/automation-service/index.md
Labels: doc:update, cla-signed

#2546 Migrated old dashboards to new dashboards
  static/img/integrations/google/Google-Cloud-Audit-Operations.png
  static/img/integrations/google/Google-Cloud-Audit-Users.png
  static/img/integrations/google/GoogleCloudAuditNetworkAndSecurity.png
  static/img/integrations/google/GoogleCloudAuditOverview.png
Labels: cla-signed

#2550 Replace screenshot in "Azure Event Hubs Source"
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  static/img/send-data/azure-event-configs.png
Labels: doc:minor edit, cla-signed

#2542 Update view-list-scheduled-views.md
  docs/manage/scheduled-views/view-list-scheduled-views.md
Labels: cla-signed

#2547 doc(lambda): update nodejs, fix python doc
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: cla-signed

#2544 Mew migration doc
  docs/integrations/pci-compliance/linux.md
  docs/integrations/security-threat-detection/barracuda-waf.md
  static/img/integrations/hosts-operating-systems/Host-Metrics-CPU.png
  static/img/integrations/hosts-operating-systems/HostMetricsDisk.png
  static/img/integrations/hosts-operating-systems/HostMetricsNetwork.png
  static/img/integrations/hosts-operating-systems/Host_Metrics_Overview.png
  static/img/integrations/hosts-operating-systems/host_metrics_app_memory.png
  static/img/integrations/hosts-operating-systems/host_metrics_app_tcp.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Admin_Activities.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Client_Traffic.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Network_Activities.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Security_Overview.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Server_Traffic.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Service_Traffic.png
  static/img/integrations/security-threat-detection/BarracudaWAF_System_Activities.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Threat_Analysis.png
  static/img/integrations/security-threat-detection/BarracudaWAF_Traffic_Overview.png
  static/img/integrations/security-threat-detection/Evident.ioESP_DetailedRisks_Dashboard.png
  static/img/integrations/security-threat-detection/Evident.ioESP_Overview_Dashboard.png
Labels: cla-signed

#2551 Create 2023-06-02-content.md
  blog-cse/2023-06-02-content.md
Labels: cla-signed

#2552 Flex docs test
  docs/manage/partitions-data-tiers/flex.md
  docs/reuse/apps/app-install.md
Labels: cla-signed

#2553 TRIDENT-17381 - Update Cloud SIEM role article
  docs/cse/administration/cse-user-accounts-and-roles.md
  docs/manage/users-roles/roles/role-capabilities.md
  static/img/cse/cloud-siem-role-capabilities.png
Labels: doc:update, cla-signed

#2340 S3m app doc
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
Labels: cla-signed

#2366 Amazon RDS doc update
  docs/integrations/amazon-aws/rds.md
  static/img/integrations/amazon-aws/Amazon-RDS-Aurora-Generic.png
  static/img/integrations/amazon-aws/Amazon-RDS-Aurora-MySQL-Global-Database-and-Backtrack-Activity.png
  static/img/integrations/amazon-aws/Amazon-RDS-Aurora-MySQL.png
  static/img/integrations/amazon-aws/Amazon-RDS-CloudTrail-Audit-Events.png
  static/img/integrations/amazon-aws/Amazon-RDS-MySQL-Logs-Audit-Log-Analysis.png
  static/img/integrations/amazon-aws/Amazon-RDS-MySQL-Logs-Audit-Log-SQL-Statements.png
  static/img/integrations/amazon-aws/Amazon-RDS-MySQL-Logs-Error-Logs-Analysis.png
  static/img/integrations/amazon-aws/Amazon-RDS-MySQL-Logs-General-Log-Analysis.png
  static/img/integrations/amazon-aws/Amazon-RDS-MySQL-Logs-Overview.png
  static/img/integrations/amazon-aws/Amazon-RDS-MySQL-Logs-Slow-Query-Analysis.png
  static/img/integrations/amazon-aws/Amazon-RDS-Non-Describe-CloudTrail-Audit-Events.png
  static/img/integrations/amazon-aws/Amazon-RDS-Overview-By-Database-Instance.png
  static/img/integrations/amazon-aws/Amazon-RDS-Overview.png
  static/img/integrations/amazon-aws/Amazon-RDS-Performance-Insights.png
Labels: cla-signed, do-not-merge

#2557 CSOAR-362 - Cloud SOAR APIs
  docs/api/cloud-soar.md
  docs/api/index.md
  docs/cloud-soar/cloud-soar-apis.md
  docs/cloud-soar/cloud-soar-bridge.md
  docs/cloud-soar/cloud-soar-integration-framework.md
  docs/cloud-soar/index.md
  docs/cloud-soar/mssp.md
  docs/cse/automation-service/about-automation-service.md
  docs/reuse/csoar-api-table.md
  sidebars.ts
Labels: doc:new, cla-signed

#2561 Fix reuse for Cloud SOAR API article
  docs/api/cloud-soar.md
  docs/cloud-soar/cloud-soar-apis.md
Labels: doc:minor edit, cla-signed

#2554 proofpoint-TAP apps doc
  cid-redirects.json
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/proofpoint-tap.md
  sidebars.ts
  static/img/integrations/saas-cloud/Proofpoint-TAP-Clicks-Overview.png
  static/img/integrations/saas-cloud/Proofpoint-TAP-Messages-Overview.png
Labels: cla-signed, do-not-merge

#2556 cisco merakai c2c app doc
  cid-redirects.json
  docs/integrations/saas-cloud/cisco-meraki-c2c.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
  static/img/integrations/saas-cloud/Cisco-Meraki-Appliance-Security-Events.png
  static/img/integrations/saas-cloud/Cisco-Meraki-Network-Events-and-Air-Marshal.png
  static/img/integrations/saas-cloud/Cisco-Meraki-Organization-Overview.png
Labels: cla-signed, do-not-merge

#2570 Update cloud-soar-bridge.md
  docs/cloud-soar/cloud-soar-bridge.md
Labels: cla-signed

#2569 Update qualys-vmdr-source.md - Asset inventory pull (additional permi…
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
Labels: cla-signed

#2555 Updated screenshots for the migrated apps.
  docs/integrations/google/cloud-iam.md
  static/img/integrations/google/Google-Cloud-AM-Overview.png
  static/img/integrations/google/Google-Cloud-IAM-Overview.png
  static/img/integrations/google/Google-Cloud-IAM-Role-Activity.png
  static/img/integrations/google/Google-Workspace-Admin.png
  static/img/integrations/google/Google-Workspace-Alert-Center-Gmail-Phishing.png
  static/img/integrations/google/Google-Workspace-Alert-Center-Google-Identity.png
  static/img/integrations/google/Google-Workspace-Alert-Center-Investigations.png
  static/img/integrations/google/Google-Workspace-Alert-Center-Other-Alerts.png
  static/img/integrations/google/Google-Workspace-Alert-Center-Overview.png
  static/img/integrations/google/Google-Workspace-Drive-User-Activity.png
  static/img/integrations/google/Google-Workspace-Drive.png
  static/img/integrations/google/Google-Workspace-Login.png
  static/img/integrations/google/Google-Workspace-Overview.png
  static/img/integrations/google/GoogleCloudVPCOverview.png
  static/img/integrations/google/cloud-vpc-Traffic.png
  static/img/integrations/google/cloud-vpc-activity.png
  static/img/integrations/google/google-cloud-firewall-egress.png
  static/img/integrations/google/google-cloud-firewall-ingress.png
  static/img/integrations/google/google-cloud-firewall-overview.png
  static/img/integrations/security-threat-detection/ZscalerBehavior.png
  static/img/integrations/security-threat-detection/ZscalerBlockedTraffic.png
  static/img/integrations/security-threat-detection/ZscalerFileClassification.png
  static/img/integrations/security-threat-detection/ZscalerOverview.png
Labels: cla-signed

#2566 Maximum limit for time range added
  docs/dashboards-new/set-custom-time-ranges.md
Labels: cla-signed

#2568 Info about new charts and threshold added
  docs/dashboards-new/panels/index.md
Labels: cla-signed

#2575 CSOAR-272 - Add "API Quickstart" content
  docs/api/cloud-soar.md
  docs/cloud-soar/cloud-soar-apis.md
Labels: doc:new, cla-signed

#2577 Add links to cid-redirect.json file
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#2579 Update Entity Timeline
  docs/cse/records-signals-entities-insights/view-manage-entities.md
Labels: doc:minor edit, cla-signed

#2574 Legacy/404 fixes
  cid-redirects.json
Labels: cla-signed

#2578 Encrypted Docs
  package.json
  static/files/flex-tier-test.html
  yarn.lock
Labels: cla-signed, hot🔥

#2581 fixed-link
  docs/send-data/installed-collectors/sources/collect-forwarded-events-windows-event-collector.md
Labels: cla-signed

#2455 Mimecast release note
  blog-service/2023-06-08-apps-mimecast.md
Labels: cla-signed, do-not-merge

#2583 Cisco Meraki - C2C - Release note
  blog-service/2023-06-08-apps-cisco-meraki-c2c.md
Labels: cla-signed, hot🔥

#2588 Patch - Uncaught Exception in yaml security vulnerability
  package.json
  yarn.lock
Labels: cla-signed

#2596 updated clabot
  .clabot
Labels: cla-signed

#2598 Added cid for cisco meraki doc
  cid-redirects.json
Labels: cla-signed

#2586 Tweaks to "About the Automation Service"
  docs/cse/administration/cse-data-retention.md
  docs/cse/automation-service/about-automation-service.md
Labels: doc:minor edit, cla-signed

#2594 CSOAR-426 || New CSOAR Release Notes section
  blog-csoar/2023-06-08-first-release-note.md
  docs/release-notes/index.md
  docusaurus.config.js
Labels: cla-signed

#2593 updated docs and migrated screenshots
  docs/integrations/amazon-aws/ses.md
  docs/integrations/google/compute-engine.md
  docs/integrations/microsoft-azure/performance.md
  static/img/integrations/amazon-aws/AWS_SecurityHub_Compliance.png
  static/img/integrations/amazon-aws/AWS_SecurityHub_Overview.png
  static/img/integrations/amazon-aws/AWS_SecurityHub_ResourcesAffected.png
  static/img/integrations/amazon-aws/AWS_SecurityHub_Types.png
  static/img/integrations/amazon-aws/AmazonSESBouncedNotifications.png
  static/img/integrations/amazon-aws/AmazonSESCloudTrailEventsOverview.png
  static/img/integrations/amazon-aws/AmazonSESCloudTrailEventsbyEventName.png
  static/img/integrations/amazon-aws/AmazonSESComplaintNotifications.png
  static/img/integrations/amazon-aws/SES-Delivered.png
  static/img/integrations/amazon-aws/SES-Notification.png
  static/img/integrations/google/google-cloud-storage-buckets.png
  static/img/integrations/google/google-cloud-storage-overview.png
  static/img/integrations/google/google-cloud-storage-users.png
  static/img/integrations/google/google-compute-engine-activity.png
  static/img/integrations/google/google-compute-engine-overview.png
  static/img/integrations/google/google-compute-engine-severity.png
  static/img/integrations/google/google-compute-engine-users.png
  static/img/integrations/hosts-operating-systems/EventSources.png
  static/img/integrations/hosts-operating-systems/LoginStatus.png
  static/img/integrations/hosts-operating-systems/Overview.png
  static/img/integrations/hosts-operating-systems/SecurityStatus.png
  static/img/integrations/microsoft-azure/ad_app_information_new.png
  static/img/integrations/microsoft-azure/ad_app_service_activity_new.png
  static/img/integrations/microsoft-azure/ad_app_service_failures.png
Labels: cla-signed

#2599 CON-2184 Remove reference to support team
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#2595 state screenshot updated
  docs/reuse/aws-cost-explorer.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/aws-cost-explorer-source.md
  static/img/send-data/azure-cost-status.png
Labels: cla-signed

#2565 Share a Dashboard Outside Your Organization doc
  docs/dashboards-new/index.md
  docs/dashboards-new/share-dashboards-outside-org.md
  sidebars.ts
  static/img/dashboards-new/share-option.png
  static/img/dashboards-new/share-option_2.png
  static/img/dashboards-new/share-outside.png
Labels: cla-signed, do-not-merge

#2590 Update set-custom-time-ranges.md
  docs/dashboards-new/set-custom-time-ranges.md
Labels: cla-signed

#2591 Hsharma c2m docs 4
  docs/integrations/amazon-aws/aurora-postgresql-ulm.md
  docs/integrations/amazon-aws/redshift-ulm.md
  static/img/integrations/amazon-aws/Amazon-Redshift-Audit-Connection-Log-Analysis.png
  static/img/integrations/amazon-aws/Amazon-Redshift-Audit-User-Activity-Log-Analysis.png
  static/img/integrations/amazon-aws/Amazon-Redshift-Audit-User-Log-Analysis.png
  static/img/integrations/amazon-aws/Amazon-Redshift-CloudTrail-Events-Overview.png
  static/img/integrations/amazon-aws/Amazon-Redshift-Overview.png
  static/img/integrations/amazon-aws/Amazon-Redshift-Resource-Utilization-by-ClusterIdentifier.png
  static/img/integrations/amazon-aws/Amazon-Redshift-Resource-Utilization-by-NodeID.png
  static/img/integrations/amazon-aws/Aurora-PostgreSQL-ULM-CloudTrail-Event-Details.png
  static/img/integrations/amazon-aws/Aurora-PostgreSQL-ULM-CloudTrail-Event-Overview.png
  static/img/integrations/amazon-aws/Aurora-PostgreSQL-ULM-Metric-Generic.png
  static/img/integrations/amazon-aws/Aurora-PostgreSQL-ULM-Metric-Latency,-Throughput-and-IOPS-Monitoring.png
  static/img/integrations/amazon-aws/Aurora-PostgreSQL-ULM-Metric-Overview.png
  static/img/integrations/amazon-aws/AuroraPostgreSQLULM_CloudTrailEvent_Details.png
  static/img/integrations/amazon-aws/AuroraPostgreSQLULM_CloudTrailEvent_Overview.png
  static/img/integrations/amazon-aws/AuroraPostgreSQLULM_Metric_Generic.png
  static/img/integrations/amazon-aws/AuroraPostgreSQLULM_Metric_LTIOPSMonitoring.png
  static/img/integrations/amazon-aws/AuroraPostgreSQLULM_Metric_Overview.png
  static/img/integrations/amazon-aws/amazon-redshift-cloudtrail-events-overview.png
  static/img/integrations/amazon-aws/amazon-redshift-connection-log-analysis.png
  static/img/integrations/amazon-aws/amazon-redshift-overview.png
  static/img/integrations/amazon-aws/amazon-redshift-resource-utilization-clusteridentifier.png
  static/img/integrations/amazon-aws/amazon-redshift-resource-utilization-nodeid.png
  static/img/integrations/amazon-aws/amazon-redshift-user-activity-log-analysis.png
  static/img/integrations/amazon-aws/amazon-redshift-user-log-analysis.png
Labels: cla-signed

#2597 images updates for iis7 app, Cisco Meraki app and Twistlock classic app
  docs/integrations/microsoft-azure/iis-7.md
  docs/integrations/security-threat-detection/cisco-meraki.md
  docs/integrations/security-threat-detection/twistlock.md
  static/img/integrations/security-threat-detection/Cisco-Meraki-Events.png
  static/img/integrations/security-threat-detection/Cisco-Meraki-Flows-Allowed-and-Rejected.png
  static/img/integrations/security-threat-detection/Cisco-Meraki-Flows-Overview.png
  static/img/integrations/security-threat-detection/Cisco-Meraki-Overview.png
  static/img/integrations/security-threat-detection/Cisco-Meraki-Security-Threats.png
  static/img/integrations/security-threat-detection/Cisco-Meraki-URLs-Content-and-Client-Platform.png
  static/img/integrations/security-threat-detection/Cisco-Meraki-URLs-Overview.png
  static/img/integrations/security-threat-detection/Cisco-Meraki-URLs-Threat-Intel.png
  static/img/integrations/security-threat-detection/TwistlockClassic-CVE-Status.png
  static/img/integrations/security-threat-detection/TwistlockClassic-Compliance-Violations.png
  static/img/integrations/security-threat-detection/TwistlockClassic-Defender-Incidents.png
  static/img/integrations/security-threat-detection/TwistlockClassic-Detected-Vulnerabilities.png
  static/img/integrations/security-threat-detection/TwistlockClassic-Overview.png
  static/img/integrations/security-threat-detection/TwistlockClassic-Runtime.png
  static/img/integrations/security-threat-detection/TwistlockClassic-Scans.png
  static/img/integrations/web-servers/IIS-7-Overview.png
  static/img/integrations/web-servers/IIS-7-Server-Operation-Errors.png
  static/img/integrations/web-servers/IIS-7-Server-Operation-Requests-and-Response-Time.png
  static/img/integrations/web-servers/IIS-7-Traffic-Insights-Apps-and-Requests.png
  static/img/integrations/web-servers/IIS-7-Traffic-Insights-Content-and-Client-Platform.png
  static/img/integrations/web-servers/IIS-7-Visitor-Insights.png
Labels: cla-signed

#2559 Deprecate apps docs
  blog-service/2016/12-31.md
  cid-redirects.json
  docs/integrations/amazon-aws/elastic-load-balancing-metrics.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/containers-orchestration/docker-community-edition.md
  docs/integrations/containers-orchestration/docker-enterprise-edition.md
  docs/integrations/containers-orchestration/index.md
  docs/integrations/partner-ecosystem-apps.md
  docs/send-data/collect-from-other-data-sources/docker-collection-methods.md
  sidebars.ts
Labels: cla-signed

#2600 rm unused app images
  static/img/integrations/security-threat-detection/CiscoMeraki_Events.png
  static/img/integrations/security-threat-detection/CiscoMeraki_Flows_Allowed_and_Rejected.png
  static/img/integrations/security-threat-detection/CiscoMeraki_Flows_Overview.png
  static/img/integrations/security-threat-detection/CiscoMeraki_Overview.png
  static/img/integrations/security-threat-detection/CiscoMeraki_Security_Threats.png
  static/img/integrations/security-threat-detection/CiscoMeraki_URLs_Content_and_Client_Platform.png
  static/img/integrations/security-threat-detection/CiscoMeraki_URLs_Overview.png
  static/img/integrations/security-threat-detection/CiscoMeraki_URLs_Threat_Intel.png
  static/img/integrations/security-threat-detection/TwistlockClassic_CVE_Status.png
  static/img/integrations/security-threat-detection/TwistlockClassic_Compliance_Violations.png
  static/img/integrations/security-threat-detection/TwistlockClassic_Detected_Vulnerabilities.png
  static/img/integrations/security-threat-detection/TwistlockClassic_Overview.png
  static/img/integrations/security-threat-detection/TwistlockClassic_Runtime.png
  static/img/integrations/security-threat-detection/TwistlockClassic_Scans.png
Labels: cla-signed

#2602 Global intelligence for apache redirect
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#2571 Add App Central to the Automation Service
  docs/cse/automation-service/automation-service-app-central.md
  docs/cse/automation-service/index.md
  sidebars.ts
  static/img/cse/automation-service-app-central-export-button.png
  static/img/cse/automation-service-app-central-update-integration.png
  static/img/cse/automation-service-app-central.png
Labels: doc:new, cla-signed

#2601 Timeslice/monitor correlation
  docs/alerts/monitors/alert-response.md
  docs/reuse/alerts-timeslice.md
  docs/search/search-query-language/search-operators/timeslice.md
Labels: cla-signed

#2592 screenshot update for PCI compliance for windows legacy
  docs/integrations/microsoft-azure/windows-legacy-pci-compliance.md
Labels: cla-signed, do-not-merge

#2520 Updated Azure Blockbobreader docs
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/index.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/troubleshoot-azure-blob-storage-log-collection.md
  static/img/send-data/Azure_Blob_Storage_Custom_Deployment.png
  static/img/send-data/Azure_Blob_all-resources.png
  static/img/send-data/Azure_Blob_create-table.png
  static/img/send-data/autoscalling.png
  static/img/send-data/edit-template.png
  static/img/send-data/review+create.png
  static/img/send-data/review-configuration.png
  static/img/send-data/storage-accounts.png
  static/img/send-data/storage-blob-data-reader.png
Labels: cla-signed, hot🔥

#2606 doc(java): update java documentation
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/custom-tags-configuration.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/traceid-spanid-injection-into-logs-configuration.md
Labels: cla-signed

#2604 Monitor / timeslice
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/reuse/alerts-timeslice.md
Labels: cla-signed

#2311 Automation examples for the Automation Service
  docs/cse/automation-service/automation-service-examples.md
  sidebars.ts
  static/files/IP-Quality-Score-Test.yaml
  static/files/IP-Reputation.yaml
  static/img/cse/automation-example-playbook-4-send-email.png
  static/img/cse/automation-example-playbook-4.png
  static/img/cse/automation-examples-add-condition.png
  static/img/cse/automation-examples-add-insight-enrichmeent-node.png
  static/img/cse/automation-examples-add-insight-enrichment-node.png
  static/img/cse/automation-examples-add-integration-button.png
  static/img/cse/automation-examples-add-ip-reputation-node.png
  static/img/cse/automation-examples-add-playbook-button.png
  static/img/cse/automation-examples-add-resource-button.png
  static/img/cse/automation-examples-add-resource-ip-quality-score.png
  static/img/cse/automation-examples-complex-condition-1.png
  static/img/cse/automation-examples-edit-sumo-logic-resource.png
  static/img/cse/automation-examples-ip-reputation-v3-add-node.png
  static/img/cse/automation-examples-search-sumo-logic-node-2.png
  static/img/cse/automation-examples-search-sumo-logic-node.png
  static/img/cse/automation-examples-send-email-node.png
  static/img/cse/automation-examples-sumo-logic-cip-resource-edit-button.png
  static/img/cse/automation-examples-upload-button.png
  static/img/cse/automation-examples-virus-total-edit-resource.png
  static/img/cse/automation-examples-virus-total-resource-edit-button.png
  static/img/cse/configure-a-notification-playbook.png
  static/img/cse/configure-an-enrichment-playbook.png
  static/img/cse/custom-integration-entity-enrichment.png
  static/img/cse/custom-integration-insight-enrichment.png
Labels: doc:new, cla-signed

#2607 Update mongodb-atlas.md
  docs/integrations/databases/mongodb-atlas.md
Labels: cla-signed

#2610 2023-06-12-application-update.md
  blog-cse/2023-06-12-application-update.md
Labels: cla-signed

#2609 Add links to the new "Automation Examples" and "App Central" articles
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/automation-service/automation-service-integration-framework.md
  docs/cse/automation-service/automation-service-integrations.md
  docs/cse/automation-service/automation-service-playbooks.md
Labels: doc:update, cla-signed

#2611 Fix image coding in "Get Started with Cloud SIEM"
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
  docs/cse/get-started-with-cloud-siem/introduction-to-cloud-siem.md
Labels: doc:minor edit, cla-signed

#2510 feat(send-data/opentelemetry-collector): add SQL Query receiver docs
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed, do-not-merge

#2612 Revert "Share a Dashboard Outside Your Organization doc"
  docs/dashboards-new/index.md
  docs/dashboards-new/share-dashboards-outside-org.md
  sidebars.ts
  static/img/dashboards-new/share-option.png
  static/img/dashboards-new/share-option_2.png
  static/img/dashboards-new/share-outside.png
Labels: cla-signed, do-not-merge

#2501 feat(send-data): improve OpenTelemetry logs collection configurations
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#2615 Updated Workday public doc.
  docs/integrations/saas-cloud/workday.md
  static/img/integrations/saas-cloud/Workday-SignOn-Report-Prompts-Tab.png
Labels: cla-signed

#2618 Update Azure Network Watcher app doc
  docs/integrations/microsoft-azure/network-watcher.md
Labels: cla-signed

#2622 Legacy 301s
  cid-redirects.json
Labels: cla-signed

#2605 Deleted Zscalar web security ad IIS-10 app docs
  blog-service/2016/12-31.md
  blog-service/2017/12-31.md
  blog-service/2019/12-31.md
  cid-redirects.json
  docs/integrations/databases/mariadb.md
  docs/integrations/microsoft-azure/iis-10-legacy.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/security-threat-detection/index.md
  docs/integrations/security-threat-detection/zscaler-internet-access.md
  docs/integrations/security-threat-detection/zscaler-web-security.md
  docs/integrations/web-servers/iis-10.md
  docs/observability/index.md
  docs/observability/work-from-home-vpn.md
  sidebars.ts
Labels: cla-signed

#2294 Data archiving structure
  blog-collector/2018/12-31.md
  blog-service/2019/12-31.md
  blog-service/2020/12-31.md
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/api/archive-ingestion.md
  docs/manage/data-archiving/archive.md
  docs/manage/data-archiving/index.md
  docs/manage/data-archiving/installed-collectors.md
  docs/manage/data-forwarding/amazon-s3-bucket.md
  docs/manage/data-forwarding/index.md
  docs/search/index.md
  docs/send-data/collection/processing-rules/create-processing-rule.md
  docs/send-data/use-json-configure-sources/index.md
  sidebars.ts
Labels: doc:update, cla-signed, do-not-merge

#2627 dataforwarding-infrequent
  docs/manage/partitions-data-tiers/infrequent-tier-data-forwarding.md
  static/img/partitions-data-tiers/enable-infrequent.png
Labels: cla-signed

#2535 S3m apps linux doc content updated
  cid-redirects.json
  docs/integrations/microsoft-azure/opentelemetry/sql-server-linux-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
  docs/integrations/saas-cloud/citrix-cloud.md
  docs/search/search-query-language/parse-operators/parse-predictable-patterns-using-an-anchor.md
  docs/search/search-query-language/search-operators/isnumeric.md
  docs/send-data/hosted-collectors/webhook-sources/zoom.md
  sidebars.ts
Labels: cla-signed, hot🔥

#2617 Added more prerequisites and updated the installation code
  docs/observability/aws/quickstart.md
Labels: cla-signed

#2626 Azure Blob Storage Collector - release note
  blog-service/2023-06-15-apps.md
Labels: cla-signed

#2633 updated migrated carbon black dashboards
  docs/integrations/security-threat-detection/vmware-carbon-black.md
  static/img/integrations/security-threat-detection/CB_Defense-Alerts.png
  static/img/integrations/security-threat-detection/CB_Defense-Device.png
  static/img/integrations/security-threat-detection/CB_Defense-Indicators-of-Compromise.png
  static/img/integrations/security-threat-detection/CB_Defense-Overview.png
  static/img/integrations/security-threat-detection/CB_Defense-Threat-Intelligence.png
  static/img/integrations/security-threat-detection/CB_Defense-endpoint.png
  static/img/integrations/security-threat-detection/CB_Response-Alerts.png
  static/img/integrations/security-threat-detection/CB_Response-Feeds.png
  static/img/integrations/security-threat-detection/CB_Response-Indicators-of-Compromise.png
  static/img/integrations/security-threat-detection/CB_Response-Network.png
  static/img/integrations/security-threat-detection/CB_Response-Processes.png
  static/img/integrations/security-threat-detection/CB_Response-Sensors.png
  static/img/integrations/security-threat-detection/CB_Response-Threat-Intelligence.png
  static/img/integrations/security-threat-detection/CB_Response-User-and-Host-Alerts.png
  static/img/integrations/security-threat-detection/CB_Response-Watchlists.png
Labels: cla-signed

#2637 API accessID - Audit event index
  blog-developer/2023-06-15-api.md
  docs/manage/security/audit-event-index.md
Labels: cla-signed

#2638 Change "Cloud SIEM/SOAR" to "Security" in guides list
  docusaurus.config.js
Labels: doc:minor edit, cla-signed

#2628 Cisco webex c2c
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/webex-source.md
  sidebars.ts
  static/img/send-data/accept-page.png
  static/img/send-data/add-integration.png
  static/img/send-data/code-url.png
  static/img/send-data/create-a-new-app.png
  static/img/send-data/create-integration.png
  static/img/send-data/my-webex-apps.png
  static/img/send-data/oauth-authorization.png
  static/img/send-data/organization-id.png
  static/img/send-data/webex-cofig-page.png
  static/img/send-data/webex-icon.png
  static/img/send-data/webex-logo.png
Labels: cla-signed, hot🔥

#2636 MET-19588: Update rate/delta operators docs to reflect new features
  docs/metrics/metrics-operators/delta.md
  docs/metrics/metrics-operators/rate.md
Labels: cla-signed

#2639 Update CODEOWNERS for OTEL docs
  .github/CODEOWNERS
Labels: cla-signed

#2641 Update rate.md
  docs/metrics/metrics-operators/rate.md
Labels: cla-signed

#2631 Updated screenshot files and readme files for set 3 mewboards migration activity for Cylance and imperva WAF apps
  docs/integrations/security-threat-detection/cylance.md
  docs/integrations/security-threat-detection/imperva-incapsula.md
  static/img/integrations/security-threat-detection/Cylance-AuditLog.png
  static/img/integrations/security-threat-detection/Cylance-Device-Control.png
  static/img/integrations/security-threat-detection/Cylance-Device.png
  static/img/integrations/security-threat-detection/Cylance-Memory-Exploit-Attempts.png
  static/img/integrations/security-threat-detection/Cylance-Overview.png
  static/img/integrations/security-threat-detection/Cylance-Script-Control.png
  static/img/integrations/security-threat-detection/Cylance-Threat-Classification.png
  static/img/integrations/security-threat-detection/Cylance-Threat.png
  static/img/integrations/security-threat-detection/Imperva-Incapsula-WAF-BOT-Access-Control.png
  static/img/integrations/security-threat-detection/Imperva-Incapsula-WAF-Blocked-Countries.png
  static/img/integrations/security-threat-detection/Imperva-Incapsula-WAF-Overview.png
Labels: cla-signed, hot🔥

#2645 screenshots updated
  static/img/integrations/security-threat-detection/TIQA_Domain_Dashboard.png
  static/img/integrations/security-threat-detection/TIQA_Email_Dashboard.png
  static/img/integrations/security-threat-detection/TIQA_Hash256_Dashboard.png
  static/img/integrations/security-threat-detection/TIQA_IP_Dashboard.png
  static/img/integrations/security-threat-detection/TIQA_Overview_Dashboard.png
  static/img/integrations/security-threat-detection/TIQA_URL_Dashboard.png
  static/img/integrations/sumo-apps/EA_Access_Key_Activities.png
  static/img/integrations/sumo-apps/EA_Collector_Activities.png
  static/img/integrations/sumo-apps/EA_Collector_Management_Overview.png
  static/img/integrations/sumo-apps/EA_Collector_Sources_Activities.png
  static/img/integrations/sumo-apps/EA_Content_Management_Overview.png
  static/img/integrations/sumo-apps/EA_Created_Deleted_Exported_Imported_Content.png
  static/img/integrations/sumo-apps/EA_Data_Forwarding_Destination_Activities.png
  static/img/integrations/sumo-apps/EA_Data_Forwarding_Index_Activities.png
  static/img/integrations/sumo-apps/EA_Data_Forwarding_Management_Overview.png
  static/img/integrations/sumo-apps/EA_Field_Extraction_Rule_Activities.png
  static/img/integrations/sumo-apps/EA_Password_Policy_MFA_Service_AllowList.png
  static/img/integrations/sumo-apps/EA_Permission_Updated_Synchronized.png
  static/img/integrations/sumo-apps/EA_Publicly_Accessed_Application_Installed.png
  static/img/integrations/sumo-apps/EA_Role_Activities.png
  static/img/integrations/sumo-apps/EA_SAML_Activities.png
  static/img/integrations/sumo-apps/EA_Security_Management_Overview.png
  static/img/integrations/sumo-apps/EA_Updated_Moved_Copied_Content.png
  static/img/integrations/sumo-apps/EA_User_Activities.png
  static/img/integrations/sumo-apps/EA_User_Email_Password_Activities.png
  static/img/integrations/sumo-apps/EA_User_Role_Management_Overview.png
  static/img/integrations/sumo-apps/EA_User_Role_Relationship_Activities.png
  static/img/integrations/sumo-apps/EA_User_Session_Activities.png
Labels: cla-signed

#2643 Revert documentation changes for new rate/delta
  docs/metrics/metrics-operators/delta.md
  docs/metrics/metrics-operators/rate.md
Labels: cla-signed

#2648 cid redirect link added
  cid-redirects.json
Labels: hot🔥

#2635 Trellix c2c
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/trellix-mvisio-epo-source.md
  sidebars.ts
  static/img/send-data/api-key.png
  static/img/send-data/credential-configuration.png
  static/img/send-data/generate.png
  static/img/send-data/self-service.png
  static/img/send-data/trellix-config.png
  static/img/send-data/trellix-icon.png
  static/img/send-data/trellix-logo.png
Labels: cla-signed, hot🔥

#2146 Outlier rules GA
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/index.md
  docs/cse/rules/write-outlier-rule.md
  sidebars.ts
Labels: doc:update, cla-signed

#1985 SUMO-216189 - Doc for deactivation of unused access keys
  docs/manage/security/access-keys.md
  static/img/security/access-keys-deactivation.png
Labels: doc:new, cla-signed

#1981 SUMO-210897 - Release note for deactivation of unused access keys
  blog-service/2023-06-20-manage-account.md
Labels: doc:new, cla-signed

#2651 Fix image wrapping in access-keys.md
  docs/manage/security/access-keys.md
Labels: doc:minor edit, cla-signed

#2653 Update index.md
  docs/manage/data-forwarding/index.md
Labels: cla-signed

#2275 SLO Tags [GA = w/e June 9]
  blog-service/2023-06-05-slo.md
  docs/observability/index.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/observability/reliability-management-slo/index.md
  static/img/observability/slo-details.png
  static/img/observability/slo-tags-query-log.png
  static/img/observability/slo-tags-query.png
  static/img/observability/slo-tags.gif
  static/img/observability/slo-tags.png
Labels: doc:new, cla-signed, do-not-merge

#2644 Update construct-search-filter-for-role.md
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
Labels: cla-signed

#2630 Observable Networks Screenshot Update for dashboard migration
  static/img/integrations/security-threat-detection/ObservableNetworks_Overview_Dashboard.png
Labels: cla-signed, hot🔥

#2655 Fix for issue 2654 - Provide certificate information in Trend Micro article
  docs/integrations/security-threat-detection/trend-micro-deep-security.md
Labels: doc:minor edit, cla-signed

#2657 App Install instructions fixes
  blog-service/2022/12-31.md
  docs/integrations/amazon-aws/vpc-flow-logs.md
  docs/integrations/app-development/puppet.md
  docs/integrations/cloud-security-monitoring-analytics/amazon-guardduty.md
  docs/integrations/cloud-security-monitoring-analytics/amazon-vpc-flow.md
  docs/integrations/cloud-security-monitoring-analytics/aws-cloudtrail.md
  docs/integrations/cloud-security-monitoring-analytics/aws-security-hub.md
  docs/integrations/cloud-security-monitoring-analytics/aws-waf.md
  docs/integrations/cloud-security-monitoring-analytics/linux.md
  docs/integrations/cloud-security-monitoring-analytics/palo-alto-firewall-10.md
  docs/integrations/cloud-security-monitoring-analytics/palo-alto-firewall-9.md
  docs/integrations/cloud-security-monitoring-analytics/windows.md
  docs/integrations/containers-orchestration/activemq.md
  docs/integrations/containers-orchestration/vmware.md
  docs/integrations/databases/postgresql.md
  docs/integrations/global-intelligence/apache-tomcat.md
  docs/integrations/global-intelligence/apache.md
  docs/integrations/global-intelligence/kubernetes-devops.md
  docs/integrations/global-intelligence/nginx.md
  docs/integrations/hosts-operating-systems/host-process-metrics.md
  docs/integrations/microsoft-azure/sql.md
  docs/integrations/saas-cloud/acquia.md
  docs/integrations/saas-cloud/airtable.md
  docs/integrations/saas-cloud/asana.md
  docs/integrations/saas-cloud/cato-networks.md
  docs/integrations/saas-cloud/cisco-umbrella.md
  docs/integrations/saas-cloud/citrix-cloud.md
  docs/integrations/saas-cloud/cloudflare.md
  docs/integrations/saas-cloud/docusign.md
  docs/integrations/saas-cloud/dropbox.md
  docs/integrations/saas-cloud/druva.md
  docs/integrations/saas-cloud/fastly.md
  docs/integrations/saas-cloud/knowbe4.md
  docs/integrations/saas-cloud/microsoft-exchange-trace-logs.md
  docs/integrations/saas-cloud/microsoft-graph-security.md
  docs/integrations/saas-cloud/mimecast.md
  docs/integrations/saas-cloud/miro.md
  docs/integrations/saas-cloud/ms-graph-azure-ad-reporting.md
  docs/integrations/saas-cloud/pagerduty-v2.md
  docs/integrations/saas-cloud/pagerduty-v3.md
  docs/integrations/saas-cloud/palo-alto-cortex-xdr.md
  docs/integrations/saas-cloud/proofpoint-on-demand.md
  docs/integrations/saas-cloud/qualys-vmdr.md
  docs/integrations/saas-cloud/rapid7.md
  docs/integrations/saas-cloud/sentinelone.md
  docs/integrations/saas-cloud/symantec-web-security-service.md
  docs/integrations/saas-cloud/zoom.md
  docs/integrations/saml/onelogin.md
  docs/integrations/security-threat-detection/akamai-security-events.md
  docs/integrations/security-threat-detection/cisco-meraki.md
  docs/integrations/security-threat-detection/observable-networks.md
  docs/integrations/web-servers/iis-10.md
  docs/reuse/apps/app-install.md
  static/img/get-started/library/App-Catalog.png
  static/img/get-started/library/add-integration.png
  static/img/get-started/library/add-version.png
  static/img/get-started/library/app-success.png
  static/img/get-started/library/configure-next.png
Labels: cla-signed

#2646 Azure docs update
  docs/integrations/microsoft-azure/active-directory-azure.md
  docs/integrations/microsoft-azure/audit.md
  docs/integrations/microsoft-azure/kubernetes.md
  docs/integrations/microsoft-azure/sql.md
  docs/integrations/microsoft-azure/web-apps.md
  static/img/integrations/microsoft-azure/diagnostic-setting-audit.png
  static/img/integrations/microsoft-azure/diagnostic-setting-kuberetes.png
  static/img/integrations/microsoft-azure/diagnostic-setting-web-apps.png
  static/img/integrations/microsoft-azure/diagnostic-setting.png
  static/img/integrations/microsoft-azure/export-activity-log.png
Labels: cla-signed

#2647 Trellix release notes
  blog-service/2023-06-22-apps-trellix.md
Labels: cla-signed, do-not-merge

#2616 connection map content added
  docs/dashboards-new/panels/map-charts.md
  static/img/dashboards-new/panels/map-charts/map-panel-option.png
  static/img/dashboards-new/panels/map-charts/missile-map.png
Labels: cla-signed, do-not-merge

#2667 CONN-2239 Add additional SIEM event ID details
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/palo-alto-cortex-xdr-source.md
Labels: cla-signed

#2659 404 fixes
  blog-cse/2023-06-20-application-update.md
  cid-redirects.json
  docs/cse/rules/index.md
  docs/search/get-started-with-search/search-basics/index.md
  docs/search/get-started-with-search/search-page/index.md
  docs/search/lookup-tables/index.md
  docs/search/search-query-language/group-aggregate-operators/index.md
  docs/search/search-query-language/math-expressions/index.md
  docs/search/search-query-language/transaction-analytics/index.md
Labels: cla-signed

#2670 Content release note 2023-06-22
  blog-cse/2023-06-22-content.md
Labels: cla-signed

#2669 Explain Insight Trainer weekly learning period
  docs/cse/rules/insight-trainer.md
Labels: doc:update, cla-signed

#2668 Add information to the "About Signal Suppression" article
  docs/cse/records-signals-entities-insights/about-signal-suppression.md
Labels: doc:update, cla-signed

#2671 Fix image coding in "Records, Signals, Entities, and Insights"
  docs/cse/records-signals-entities-insights/configure-custom-insight.md
  docs/cse/records-signals-entities-insights/configure-entity-lookup-table.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/cse/records-signals-entities-insights/create-custom-entity-type.md
  docs/cse/records-signals-entities-insights/entity-criticality.md
  docs/cse/records-signals-entities-insights/global-intelligence-security-insights.md
  docs/cse/records-signals-entities-insights/search-cse-records-in-sumo.md
  docs/cse/records-signals-entities-insights/tags-insights-signals-entities-rules.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
  docs/cse/records-signals-entities-insights/view-records-signal.md
Labels: doc:minor edit, cla-signed

#2620 Sumo 216336 - Beta doc for RBAC for indexes
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
  docs/manage/users-roles/roles/create-manage-roles.md
  docs/manage/users-roles/roles/rbac-for-indexes.md
  static/img/users-roles/advanced-filter.png
  static/img/users-roles/create-new-role-index-based-boxed.png
  static/img/users-roles/create-new-role-index-based.png
  static/img/users-roles/emulate-log-search-index-based.png
  static/img/users-roles/emulate-log-search-window.png
  static/img/users-roles/index-based-filter.png
Labels: doc:new, cla-signed

#2640 Cloud SOAR delivery 2 beta
  docs/cloud-soar/cloud-soar-delivery-2.md
  docs/cloud-soar/global-functions-menu.md
  static/img/cloud-soar/delivery-2-access-dashboards.png
  static/img/cloud-soar/delivery-2-access-reports.png
  static/img/cloud-soar/delivery-2-add-integration-button.png
  static/img/cloud-soar/delivery-2-add-resource.png
  static/img/cloud-soar/delivery-2-automation-menu.png
  static/img/cloud-soar/delivery-2-completed-integration-2.png
  static/img/cloud-soar/delivery-2-completed-integration.png
  static/img/cloud-soar/delivery-2-create-action-file.png
  static/img/cloud-soar/delivery-2-create-widget.png
  static/img/cloud-soar/delivery-2-dashboard-1.png
  static/img/cloud-soar/delivery-2-edit-dashboard-button.png
  static/img/cloud-soar/delivery-2-edit-resource-button.png
  static/img/cloud-soar/delivery-2-edit-resource-cloud-execution.png
  static/img/cloud-soar/delivery-2-empty-dashboard.png
  static/img/cloud-soar/delivery-2-new-dashboard-example.png
  static/img/cloud-soar/delivery-2-new-dashboard.png
  static/img/cloud-soar/delivery-2-new-integration-dialog.png
  static/img/cloud-soar/delivery-2-report-ui.png
  static/img/cloud-soar/delivery-2-save-report.png
  static/img/cloud-soar/delivery-2-test-action.png
  static/img/cloud-soar/delivery-2-upload-files.png
  static/img/cloud-soar/delivery-2-upload-icon.png
  static/img/cloud-soar/delivery-2-widgets-in-report.png
  static/img/cloud-soar/delivery-2-widgets.png
Labels: doc:new, cla-signed

#2672 SUMO-218223 Add the details about AWS regions info
  docs/integrations/amazon-aws/aws-privatelink.md
Labels: cla-signed

#2673 Clean up image coding in the CSE ingestion articles
  docs/cse/ingestion/cse-ingestion-best-practices.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/auth0.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-application-load-balancer.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-cloudtrail.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-guardduty.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-network-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-vpc-flow.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/check-point-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/cisco-asa.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/cisco-meraki.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/corelight-zeek.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/fortigate-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/g-suite-alert-center.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/google-workspace-apps-audit.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/kemp-loadmaster.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/linux-os-syslog.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-audit-office.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-azure-activity-log.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-windows.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/nginx-access-logs.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/okta.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/onelogin.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/osquery.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/palo-alto-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/sentinelone.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/signal-sciences-waf.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/symantec-proxy-secure-gateway-blue-coat-proxy.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/symantec-proxy-secure-gateway.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/zscaler-nss.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/zscaler-private-access.md
  docs/cse/ingestion/sumo-logic-ingest-mapping.md
  docs/cse/ingestion/view-mappers-for-product.md
Labels: doc:minor edit, cla-signed

#2663 Update save-classic.md
  docs/search/search-query-language/search-operators/save-classic.md
Labels: cla-signed

#2675 fix: fix Otelcol installation instructions
  docs/send-data/opentelemetry-collector/install-collector-linux.md
  docs/send-data/opentelemetry-collector/install-collector-macos.md
Labels: cla-signed

#2679 Update .clabot
  .clabot
Labels: cla-signed

#2674 Druva cyber resilience - C2C
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-cyber-resilience-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/img/send-data/druva-cloud-settings.png
  static/img/send-data/druva-console.png
  static/img/send-data/druva-cyber-config.png
Labels: cla-signed

#2678 istio.md: correct a typo
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/istio.md
Labels: cla-signed

#2681 Update druva-cyber-resilience-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-cyber-resilience-source.md
Labels: cla-signed

#2682 fixed image
  static/img/get-started/github/sumo-logic-access-token.png
Labels: cla-signed

#2684 update sophos doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sophos-central-source.md
Labels: cla-signed

#2683 viewing dashboard filters
  docs/reuse/filter-dashboards.md
  static/img/dashboards-new/filter-dashboards.png
Labels: cla-signed

#2687 Partner app template
  docs/contributing/templates/partner-app.md
Labels: cla-signed

#2680 Druva Cyber Resilience-release notes
  blog-service/2023-06-22-apps-trellix.md
  blog-service/2023-06-28-apps.md
Labels: cla-signed, do-not-merge

#2662 updated doc for v2 alerts
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
  static/img/send-data/6_ms_graph_app_add_permissions.png
  static/img/send-data/7_ms_graph_app_add_role.png
  static/img/send-data/Microsoft-Graph-Security-API-Source-input.png
Labels: cla-signed, do-not-merge

#2686 Sophos Central release note
  blog-service/2023-06-28-collections.md
Labels: cla-signed

#2689 Download image/csv
  blog-service/2023-06-28-metrics.md
Labels: cla-signed

#2613 Manage account first updates
  docs/manage/manage-subscription/close-cancel-sumo-account.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
  docs/manage/manage-subscription/manage-org-settings.md
  static/img/account/account-details-of-credit-usage.png
  static/img/account/account-usage-fields.png
  static/img/account/account-usage-fields_old.png
Labels: cla-signed

#2688 Update index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
Labels: cla-signed

#2690 Release notes account page
  blog-service/2023-06-28-manage-account-page.md
Labels: cla-signed

#2685 Kinesis docs update
  cid-redirects.json
  docs/integrations/amazon-aws/eks-control-plane.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-amazon-kinesis.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template-with-secured-sumoendpoint.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-collector-script.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-lambda-function.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/index.md
  docs/send-data/collect-from-other-data-sources/collect-logs-aws-fargate.md
  sidebars.ts
  static/img/send-data/add-trigger.png
  static/img/send-data/basic-information.png
  static/img/send-data/cloudWatch-logs-trigger.png
  static/img/send-data/create-destination.png
  static/img/send-data/create-lambda-subscription-filter.png
  static/img/send-data/environment-variables.png
  static/img/send-data/select-a-source.png
  static/img/send-data/success.png
  static/img/send-data/test-pattern.png
Labels: cla-signed

#2696 Revert "Release notes account page"
  blog-service/2023-06-28-manage-account-page.md
Labels: cla-signed

#2695 Revert "Kinesis docs update"
  cid-redirects.json
  docs/integrations/amazon-aws/eks-control-plane.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-amazon-kinesis.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template-with-secured-sumoendpoint.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-collector-script.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-lambda-function.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/index.md
  docs/send-data/collect-from-other-data-sources/collect-logs-aws-fargate.md
  sidebars.ts
  static/img/send-data/add-trigger.png
  static/img/send-data/basic-information.png
  static/img/send-data/cloudWatch-logs-trigger.png
  static/img/send-data/create-destination.png
  static/img/send-data/create-lambda-subscription-filter.png
  static/img/send-data/environment-variables.png
  static/img/send-data/select-a-source.png
  static/img/send-data/success.png
  static/img/send-data/test-pattern.png
Labels: cla-signed

#2698 Update index.md
  docs/send-data/hosted-collectors/index.md
Labels: type:bug, cla-signed

#2699 Manage Acct release notes
  blog-service/2023-06-29-manage-account.md
Labels: cla-signed

#2700 Kinesis doc update (redo)
  cid-redirects.json
  docs/integrations/amazon-aws/eks-control-plane.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-amazon-kinesis.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template-with-secured-sumo-endpoint.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-collector-script.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-lambda-function.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/index.md
  docs/send-data/collect-from-other-data-sources/collect-logs-aws-fargate.md
  sidebars.ts
  static/img/send-data/add-trigger.png
  static/img/send-data/basic-information.png
  static/img/send-data/cloudWatch-logs-trigger.png
  static/img/send-data/create-destination.png
  static/img/send-data/create-lambda-subscription-filter.png
  static/img/send-data/environment-variables.png
  static/img/send-data/select-a-source.png
  static/img/send-data/success.png
  static/img/send-data/test-pattern.png
Labels: cla-signed

#2702 Azure typos
  docs/integrations/microsoft-azure/arm-integration-faq.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/index.md
Labels: cla-signed

#2703 June 29 2023 Application Update
  blog-cse/2023-06-29-application-update.md
  blog-cse/2023-06-29-content.md
Labels: cla-signed

#2693 pci-compliance-linux-opentelemetry docs
  cid-redirects.json
  docs/integrations/pci-compliance/index.md
  docs/integrations/pci-compliance/opentelemetry/linux-opentelemetry.md
  sidebars.ts
Labels: cla-signed

#2705 Changes from PR https://github.com/SumoLogic/sumologic-documentation/…
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
Labels: cla-signed

#2708 Remove TRACE log level
  docs/search/get-started-with-search/search-page/log-level.md
Labels: cla-signed

#2706 Docker ce upgarde to mew board - note addition to the doc and screens…
  docs/integrations/containers-orchestration/docker-community-edition.md
  static/img/integrations/containers-orchestration/docker_app_cpu_performance.png
  static/img/integrations/containers-orchestration/docker_app_memory_performance.png
  static/img/integrations/containers-orchestration/docker_app_network_performance.png
  static/img/integrations/containers-orchestration/docker_app_overview.png
Labels: cla-signed
