Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-01, with the labels that each got.

#1259 Removed whitespaces to fix formatting
  docs/metrics/metrics-operators/along.md
Labels: cla-signed

#1263 Update system-requirements.md
  docs/get-started/system-requirements.md
Labels: cla-signed

#1264 Update manage-indexes-variable-retention.md
  docs/manage/partitions-data-tiers/manage-indexes-variable-retention.md
Labels: cla-signed

#1262 Update Streaming Metrics Source page
  docs/send-data/installed-collectors/sources/streaming-metrics-source.md
Labels: cla-signed

#1247 where operator updates
  docs/metrics/metrics-operators/filter.md
  docs/metrics/metrics-operators/where.md
Labels: cla-signed, do-not-merge

#1258 missing alt text
  docs/cloud-soar/automation.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/main-menu.md
Labels: cla-signed

#1269 Update .clabot
  .clabot
Labels: cla-signed

#1270 Update vpc-flow-logs.md
  docs/integrations/amazon-aws/vpc-flow-logs.md
Labels: cla-signed

#1271 Update vpc-flow-logs.md
  docs/integrations/amazon-aws/vpc-flow-logs.md
Labels: cla-signed

#1272 Release search query editor
  blog-service/2023-01-05-search-query.md
Labels: cla-signed, hot🔥

#1187 Discourage using meta tags in metrics formats section
  docs/metrics/introduction/metric-formats.md
Labels: cla-signed

#1261 threshold tab support
  docs/metrics/metrics-queries/metrics-explorer.md
Labels: cla-signed, do-not-merge

#1275 CON-1379 C2C Azure AD Report Add Permission
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-azure-ad-reporting-source.md
Labels: cla-signed

#1274 ewma, where, heat map, delete engine updates
  .clabot
  docs/metrics/metrics-operators/ewma.md
  docs/metrics/metrics-operators/where.md
  docs/metrics/metrics-queries/engine-updates.md
  docs/metrics/metrics-queries/heat-map.md
  sidebars.ts
  static/img/metrics/heat-map-metric.png
  static/img/metrics/heat-map-option.png
Labels: cla-signed

#1273 Simplify Tuning Expression descriptions
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/rule-tuning-expressions.md
Labels: cla-signed

#1277 clabot update
  .clabot
Labels: cla-signed

#1276 Update upload-metrics.md
  docs/send-data/hosted-collectors/http-source/upload-metrics.md
Labels: cla-signed

#1278 Update .clabot
  .clabot
Labels: cla-signed

#1268 CON-1050: Update doc for Netskope REST APIv2
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: cla-signed

#1279 Update .clabot
  .clabot
Labels: cla-signed

#1250 Update aurora-mysql-ulm.md
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
Labels: cla-signed

#1266 added a clear section for supported variables
  docs/cse/integrations/insight-enrichment-server.md
Labels: cla-signed

#1284 cid-redirects.json audit
  cid-redirects.json
Labels: cla-signed

#1287 updated google workspace alertcenter
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
  static/img/send-data/alertcenter-config-main.png
  static/img/send-data/alertcenter-icon.png
Labels: cla-signed

#1288 Update google-workspace-alertcenter.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
Labels: cla-signed

#1290 entity types defn
  docs/cse/integrations/insight-enrichment-server.md
  docs/cse/records-signals-entities-insights/about-cse-insight-ui.md
  docs/cse/records-signals-entities-insights/create-custom-entity-type.md
  docs/cse/records-signals-entities-insights/insight-generation-process.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
Labels: cla-signed

#1291 Update .clabot
  .clabot
Labels: cla-signed

#1293 Update metadata doc to include _metricId change
  docs/metrics/introduction/built-in-metadata.md
Labels: cla-signed

#1294 quantize is first operator
  docs/metrics/introduction/metric-quantization.md
Labels: cla-signed

#1292 where and thresholds
  blog-service/2023-01-09-metrics.md
  yarn.lock
Labels: cla-signed

#1295 Update index.md
  docs/search/search-cheat-sheets/index.md
Labels: cla-signed

#1299 Update index.md
  docs/metrics/metrics-operators/index.md
Labels: cla-signed

#1296 baseline type guidance
  docs/cse/rules/write-first-seen-rule.md
Labels: cla-signed

#1301 CON-1335: Qualys VMDR C2C - Adding FAQ
  .github/workflows/pr.yml
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
Labels: cla-signed

#1285 Update index.md
  docs/alerts/monitors/index.md
Labels: cla-signed

#1306 cheat sheet link and bulk library move
  docs/get-started/library.md
  docs/search/search-cheat-sheets/index.md
  static/img/get-started/library/checkbox.png
  static/img/get-started/library/move-option.png
  static/img/get-started/library/select-folder.png
Labels: cla-signed

#1307 Fix links and formatting - Parser editor
  docs/cse/schema/parser-editor.md
Labels: cla-signed

#1309 Create 2023-01-05-content.md
  blog-cse/2023-01-05-content.md
Labels: cla-signed

#1310 Update aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
Labels: cla-signed

#1312 service list/map
  docs/apm/traces/working-with-tracing-data/service-map.md
  static/img/traces/service-list.png
Labels: cla-signed

#1316 Update account-setup.md
  docs/get-started/account-setup.md
Labels: cla-signed

#1315 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#1311 Angadrandhawa1 alertresponse recovery update
  docs/alerts/monitors/alert-response.md
Labels: cla-signed

#1319 remove internal-only content
  docs/manage/manage-subscription/close-cancel-sumo-account.md
  docs/manage/security/enable-support-account.md
Labels: cla-signed

#1323 Update ServiceNow Connection
  docs/manage/connections-integrations/servicenow/set-up-connections.md
Labels: cla-signed

#1321 rule severity
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-match-rule.md
Labels: cla-signed

#1322 Update aws-lambda.md
  docs/manage/connections-integrations/webhook-connections/aws-lambda.md
Labels: cla-signed

#1283 Customizable recovery payload
  docs/manage/connections-integrations/servicenow/set-up-connections.md
  docs/manage/connections-integrations/webhook-connections/aws-lambda.md
  docs/manage/connections-integrations/webhook-connections/set-up-webhook-connections.md
  docs/manage/connections-integrations/webhook-connections/slack.md
  static/img/connection-and-integration/alert-payload.png
  static/img/connection-and-integration/recovery-payload-example.png
  static/img/connection-and-integration/recovery-payload.png
Labels: doc:update, cla-signed

#1325 Angadrandhawa1 PagerDuty Update
  docs/manage/connections-integrations/webhook-connections/pagerduty.md
  docs/manage/connections-integrations/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#1324 Update pagerduty.md
  docs/manage/connections-integrations/webhook-connections/pagerduty.md
  docs/manage/connections-integrations/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#1304 updated-knowbe4
  docs/search/search-cheat-sheets/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#1327 Update knowbe4-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#1339 Update performance.md
  docs/integrations/microsoft-azure/performance.md
Labels: cla-signed

#1338 Update windows-legacy.md
  docs/integrations/microsoft-azure/windows-legacy.md
Labels: cla-signed

#1340 Create 2023-01-13-content.md
  blog-cse/2023-01-13-content.md
Labels: cla-signed

#1337 Update windows-legacy-pci-compliance.md
  docs/integrations/microsoft-azure/windows-legacy-pci-compliance.md
Labels: cla-signed

#1333 Update web-apps.md
  docs/integrations/microsoft-azure/web-apps.md
Labels: cla-signed

#1341 Update sql-server.md
  docs/integrations/microsoft-azure/sql-server.md
Labels: cla-signed

#1336 Update office-365.md
  docs/integrations/microsoft-azure/office-365.md
Labels: cla-signed

#1331 Update network-watcher.md
  docs/integrations/microsoft-azure/network-watcher.md
Labels: cla-signed

#1332 Update sql.md
  docs/integrations/microsoft-azure/sql.md
Labels: cla-signed

#1328 Update teams.md
  docs/integrations/microsoft-azure/teams.md
Labels: cla-signed

#1343 Update .clabot
  .clabot
Labels: cla-signed

#1345 Filter search
  docs/cse/administration/filter-search.md
  sidebars.ts
  static/img/cse/filter-options.png
  static/img/cse/list-page-search.png
Labels: cla-signed

#1347 MS SQL server K8s/non-K8s fix
  docs/integrations/microsoft-azure/sql-server.md
Labels: cla-signed

#1335 Update iis-10-legacy.md
  docs/integrations/microsoft-azure/iis-10-legacy.md
Labels: cla-signed

#1334 Update iis-7.md
  docs/integrations/microsoft-azure/iis-7.md
Labels: cla-signed

#1330 Update kubernetes.md
  docs/integrations/microsoft-azure/kubernetes.md
Labels: cla-signed

#1329 Update audit.md
  docs/integrations/microsoft-azure/audit.md
Labels: cla-signed

#1350 Custom recovery/alert payload
  docs/alerts/webhook-connections/datadog.md
  docs/alerts/webhook-connections/jira-cloud.md
  docs/alerts/webhook-connections/jira-server.md
  docs/alerts/webhook-connections/jira-service-desk.md
  docs/alerts/webhook-connections/microsoft-azure-functions.md
  docs/alerts/webhook-connections/microsoft-teams.md
  docs/alerts/webhook-connections/opsgenie-legacy.md
  docs/alerts/webhook-connections/opsgenie.md
Labels: cla-signed

#1348 typo in old release note
  blog-cse/2022-10-13-application-update.md
Labels: cla-signed

#1349 Missing link - user.properties
  docs/manage/security/installation-tokens.md
  docs/send-data/installed-collectors/collector-installation-reference/user-properties.md
Labels: cla-signed

#1351 Webhooks hub
  cid-redirects.json
  docs/alerts/scheduled-searches/index.md
  docs/alerts/webhook-connections/audit-index.md
  docs/alerts/webhook-connections/aws-lambda.md
  docs/alerts/webhook-connections/cloud-soar.md
  docs/alerts/webhook-connections/datadog.md
  docs/alerts/webhook-connections/hipchat.md
  docs/alerts/webhook-connections/index.md
  docs/alerts/webhook-connections/jira-cloud.md
  docs/alerts/webhook-connections/jira-server.md
  docs/alerts/webhook-connections/microsoft-azure-functions.md
  docs/alerts/webhook-connections/microsoft-teams.md
  docs/alerts/webhook-connections/new-relic.md
  docs/alerts/webhook-connections/opsgenie-legacy.md
  docs/alerts/webhook-connections/opsgenie.md
  docs/alerts/webhook-connections/pagerduty.md
  docs/alerts/webhook-connections/schedule-searches-webhook-connections.md
  docs/alerts/webhook-connections/servicenow/index.md
  docs/alerts/webhook-connections/servicenow/launch-investigations.md
  docs/alerts/webhook-connections/servicenow/set-up-connections.md
  docs/alerts/webhook-connections/servicenow/set-up-searches.md
  docs/alerts/webhook-connections/servicenow/set-up-security-incident-webhook.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/alerts/webhook-connections/slack.md
  docs/get-started/faq.md
  docs/manage/connections-integrations/index.md
  docs/manage/connections-integrations/jfrog-artifactory.md
  i18n/ja/alerts/alerts/scheduled-searches/index.md
  sidebars.ts
  src/css/sumo.scss
  static/img/connection-and-integration/aws-lambda.svg
  static/img/connection-and-integration/azure-functions.png
  static/img/connection-and-integration/hipchat-logo-vector.svg
  static/img/connection-and-integration/new-relic-seeklogo.com.svg
Labels: cla-signed

#1356 Fixed cid redirect for CIS AWS app
  cid-redirects.json
Labels: cla-signed

#1353 monitor resolution note
  docs/alerts/monitors/alert-response.md
Labels: cla-signed

#1354 {{AlertStatus}) not available for Sched search
  docs/alerts/alert-variables.md
Labels: cla-signed

#1355 Recovery settings clarification
  docs/alerts/monitors/create-monitor.md
Labels: cla-signed

#1359 Added more SLO Beta URLs
  cid-redirects.json
Labels: cla-signed

#1362 Add FAQ for not allowed fields for Alert Grouping
  docs/alerts/monitors/alert-grouping.md
Labels: cla-signed

#1370 Fixing broken link
  docs/cse/schema/parser-troubleshooting-tips.md
Labels: cla-signed

#1367 Recovery payload fixes
  docs/alerts/webhook-connections/cloud-soar.md
  docs/alerts/webhook-connections/datadog.md
  docs/alerts/webhook-connections/hipchat.md
  docs/alerts/webhook-connections/index.md
  docs/alerts/webhook-connections/jira-cloud.md
  docs/alerts/webhook-connections/jira-server.md
  docs/alerts/webhook-connections/jira-service-desk.md
  docs/alerts/webhook-connections/microsoft-azure-functions.md
  docs/alerts/webhook-connections/opsgenie-legacy.md
  src/css/sumo.scss
  static/img/connection-and-integration/azure-functions.png
Labels: cla-signed

#1369 Fixed broken links to local docs (sort, topk)
  docs/search/search-query-language/search-operators/top.md
Labels: cla-signed

#1358 RUM hosted collector clarification
  docs/apm/real-user-monitoring.md
  docs/apm/traces/quickstart.md
  static/img/reuse/add-source.png
  static/img/traces/traces-menu-option.png
Labels: cla-signed

#1368 Fixing broken URL
  docs/search/get-started-with-search/build-search/use-url-to-run-search.md
Labels: cla-signed

#1375 Update okta.md
  docs/integrations/saml/okta.md
Labels: cla-signed

#1244 predict operator topic
  docs/metrics/metrics-operators/predict.md
  static/img/metrics/predict-1.png
  static/img/metrics/predict-2.png
Labels: cla-signed

#1378 Entity Group properties apply retroactively
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
Labels: cla-signed

#1379 predict release note
  blog-service/2023-01-17-metrics.md
  sidebars.ts
Labels: cla-signed

#1372 Gmail Trace Logs
  docs/integrations/saas-cloud/gmail-tracelogs.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
Labels: cla-signed

#1373 CID redirect - Workday
  cid-redirects.json
Labels: cla-signed

#1382 dwell definition
  docs/cse/records-signals-entities-insights/about-cse-insight-ui.md
  docs/cse/records-signals-entities-insights/cse-heads-up-display.md
Labels: cla-signed

#1364 Cross-reference formatDate and parseDate
  blog-service/2017/12-31.md
  cid-redirects.json
  docs/search/search-query-language/parse-operators/parsedate.md
  docs/search/search-query-language/parse-operators/parsehex.md
  docs/search/search-query-language/search-operators/formatdate.md
  sidebars.ts
Labels: cla-signed

#1363 Casting data search operator - broken links
  docs/search/search-query-language/search-operators/contains.md
  docs/search/search-query-language/search-operators/formatdate.md
  docs/search/search-query-language/search-operators/lookup-classic.md
  docs/search/search-query-language/search-operators/lookup.md
  docs/search/search-query-language/search-operators/sort.md
  docs/search/search-query-language/search-operators/where.md
Labels: cla-signed

#1380 raw vs. rolled up
  docs/metrics/manage-metric-volume/metric-ingestion-and-storage.md
Labels: cla-signed

#1352 Custom resolution payload relnote
  blog-service/2023-01-17-alerts.md
Labels: cla-signed

#1388 Update okta.md
  docs/integrations/saml/okta.md
Labels: cla-signed

#1391 Update create-structured-log-mapping.md
  docs/cse/schema/create-structured-log-mapping.md
Labels: cla-signed

#1389 Update aws-s3-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
Labels: cla-signed

#1392 Update amazon-path-expressions.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-path-expressions.md
Labels: cla-signed

#1394 airtable beta update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  sidebars.ts
Labels: cla-signed, hot🔥

#1395 Update netskope.md
  docs/integrations/security-threat-detection/netskope.md
Labels: cla-signed

#1365 Helm v3 updates
  docs/integrations/containers-orchestration/activemq.md
  docs/integrations/containers-orchestration/kubernetes-control-plane.md
  docs/integrations/containers-orchestration/kubernetes.md
  docs/integrations/containers-orchestration/rabbitmq.md
  docs/integrations/databases/cassandra.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/elasticsearch.md
  docs/integrations/databases/mariadb.md
  docs/integrations/databases/memcached.md
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/oracle/collect-logs-metrics.md
  docs/integrations/microsoft-azure/sql-server.md
  docs/integrations/saas-cloud/istio.md
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx.md
  docs/integrations/web-servers/squid-proxy.md
  docs/integrations/web-servers/varnish.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/install-telegraf.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
Labels: cla-signed, hot🔥

#1384 JSON5 security fix
  package.json
  yarn.lock
Labels: cla-signed

#1398 updated rule and attribute docs
  docs/cse/rules/cse-built-in-rules.md
  docs/cse/schema/schema-attributes.md
Labels: cla-signed

#1387 inv data, geolocation attributes
  docs/cse/schema/schema-attributes.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
Labels: cla-signed

#1399 Update actions to run on Node 16 instead of Node 12
  .github/workflows/build_and_deploy.yml
  .github/workflows/pr.yml
Labels: doc:site tech, cla-signed

#1385 Upgrade utils for webpack loaders
  package.json
  yarn.lock
Labels: cla-signed

#1403 use NOT in keyword search
  docs/cse/administration/filter-search.md
Labels: cla-signed

#1410 Add 'seldomly' to spellcheck allowlist
  .github/workflows/pr.yml
Labels: cla-signed

#1390 Update amazon-path-expressions.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-path-expressions.md
Labels: cla-signed

#1397 Update aws-s3-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
Labels: cla-signed

#1412 Streamline Telegraf Metrics doc
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
  sidebars.ts
Labels: cla-signed

#1406 Python OTEL log correlation
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python.md
Labels: cla-signed

#1415 cid for predict
  cid-redirects.json
Labels: cla-signed

#1416 Create 2023-01-19-application-update.md
  blog-cse/2023-01-19-application-update.md
Labels: cla-signed

#1396 Update aws-sources.md
  docs/send-data/hosted-collectors/amazon-aws/aws-sources.md
Labels: cla-signed

#1401 frequent and infrequent tier data
  docs/metrics/logs-to-metrics.md
Labels: cla-signed

#1417 Update okta.md
  docs/integrations/saml/okta.md
Labels: cla-signed

#1428 Making Airtable Docs GA
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  sidebars.ts
Labels: cla-signed

#1427 Update s3-audit.md
  docs/integrations/amazon-aws/s3-audit.md
Labels: cla-signed

#1422 Update save.md
  docs/search/search-query-language/search-operators/save.md
Labels: cla-signed

#1429 Update .clabot
  .clabot
Labels: cla-signed

#1423 Update python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python.md
Labels: cla-signed

#1430 Update FAQ / Adding Comments Process
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#1431 More legacy redirects
  cid-redirects.json
  docs/integrations/amazon-aws/threat-intel.md
Labels: cla-signed

#1418 Create 2023-01-19-content.md
  blog-cse/2023-01-20-content.md
Labels: cla-signed

#1419 Update asn-lookup.md
  docs/search/search-query-language/search-operators/asn-lookup.md
Labels: cla-signed

#1432 Fix permission error for NetskopeV2 source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: cla-signed

#1433 aws sources fix
  docs/send-data/hosted-collectors/amazon-aws/aws-sources.md
Labels: cla-signed

#1420 Update top.md
  docs/search/search-query-language/search-operators/top.md
Labels: cla-signed

#1421 Update lookup-classic.md
  docs/search/search-query-language/search-operators/lookup-classic.md
Labels: cla-signed

#1436 More formatting fixes
  docs/beta/aws-private-link.md
  docs/beta/index.md
  docs/contributing/create-doc.md
  docs/contributing/edit-doc.md
  docs/contributing/glossary.md
  docs/contributing/style-guide.md
  docs/contributing/templates/generic-doc.md
  docs/contributing/templates/partner-app.md
  sidebars.ts
Labels: cla-signed

#1437 Style guide edits
  docs/contributing/style-guide.md
  static/img/contributing/style-steps-headings.png
Labels: cla-signed

#1435 Update README.md with node requirements
  README.md
Labels: cla-signed

#1439 Update .clabot
  .clabot
Labels: cla-signed

#1438 Add missing verb to metrics operators parse tip
  docs/metrics/metrics-operators/parse.md
Labels: cla-signed

#1408 Python log injection traceID/spanID
  cid-redirects.json
  docs/apm/traces/get-started-transaction-tracing/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/istio.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/traceid-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/traceid-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby-on-rails.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby.md
  sidebars.ts
Labels: cla-signed

#1441 haversine redirect
  cid-redirects.json
Labels: cla-signed

#1442 Quickstart IA
  community/app-observability/services-list-map.md
  docs/apm/traces/quickstart.md
  docs/get-started/quickstart.md
  docs/manage/ingestion-volume/ingest-budgets/quickstart.md
  docs/observability/kubernetes/quickstart.md
  docs/search/search-query-language/index.md
  sidebars.ts
  sidebarsCommunity.js
Labels: cla-signed

#1440 num operator double floating point clarification
  docs/search/search-query-language/search-operators/num.md
Labels: cla-signed

#1445 Fixing broken link and typos
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
Labels: cla-signed

#1444 Update concat.md
  docs/search/search-query-language/search-operators/concat.md
Labels: cla-signed

#1361 Clarify Google Workspace AlertCenter
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
Labels: cla-signed, do-not-merge

#1446 Adding sourceCategory for audit logs for Alerts
  docs/manage/security/audit-event-index.md
Labels: cla-signed

#1449 Update k8s tracing
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-kubernetes-environments.md
Labels: cla-signed

#1452 CIDs for metric operators
  cid-redirects.json
Labels: cla-signed

#1450 improved along topic
  docs/metrics/metrics-operators/along.md
  static/img/metrics/join-results-with-along.png
  static/img/metrics/join-results-without-along.png
  static/img/metrics/joined-quantized.png
  static/img/metrics/multiple-queries.png
  static/img/metrics/odd-join-results.png
  static/img/metrics/simple-join.png
Labels: cla-signed

#1453 Update .clabot
  .clabot
Labels: cla-signed

#1451 update zscaler-web-security: Zscaler pricing info
  docs/integrations/security-threat-detection/zscaler-web-security.md
Labels: cla-signed

#1447 Alerts cleanup
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/alerts/difference-from-scheduled-searches.md
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/alert-response-faq.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/alert-variables.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/edit-settings.md
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/scheduled-searches/create-email-alert.md
  i18n/ja/alerts/alerts/alert-variables.md
  i18n/ja/alerts/alerts/monitors/alert-response-faq.md
  i18n/ja/alerts/alerts/monitors/alert-response.md
  i18n/ja/alerts/alerts/monitors/index.md
  i18n/ja/alerts/alerts/monitors/monitor-faq.md
  i18n/ja/alerts/alerts/scheduled-searches/create-email-alert.md
  sidebars.ts
Labels: cla-signed
