Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-05, with the labels that each got.

#2246 Fix for issue 2106
  docs/cse/administration/create-custom-threat-intel-source.md
Labels: doc:update, cla-signed

#2242 CON-1956: Added step for DocuSign authentication, updated App Consent…
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/docusign-source.md
  static/img/send-data/docusign-authetication.png
Labels: cla-signed

#2251 Add built-in keys image for issue 2144
  docs/cse/administration/create-a-custom-tag-schema.md
  static/img/cse/built-in-tags.png
Labels: doc:update, cla-signed

#2250 Update aws-cost-explorer.md
  docs/reuse/aws-cost-explorer.md
  static/img/integrations/amazon-aws/cost-explorer-v2-1-1.png
Labels: cla-signed

#2241 Update akamai-siem-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/akamai-siem-api-source.md
Labels: cla-signed

#2225 MET-19342: Metrics Heatmap Changes
  docs/metrics/metrics-queries/heat-map.md
  static/img/metrics/heat-map.png
Labels: cla-signed

#2254 Add new screenshots for issue 2168
  docs/alerts/scheduled-searches/generate-cse-signals.md
  static/img/alerts/save-as.png
  static/img/alerts/save-item.png
Labels: doc:update, cla-signed

#2223 Update prerequisites-windows-remote-file-collection.md
  docs/send-data/installed-collectors/sources/remote-file-source/prerequisites-windows-remote-file-collection.md
Labels: cla-signed

#2255 Update collect-logs.md
  docs/integrations/google/workspace/collect-logs.md
Labels: cla-signed

#2252 Add new screen image for issue 2182
  docs/cse/administration/create-a-custom-tag-schema.md
  static/img/cse/gear-tag-schema.png
Labels: doc:update, cla-signed

#2257 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#2216 screenshots updated
  docs/integrations/amazon-aws/sns.md
  static/img/integrations/amazon-aws/Amazon-SNS-Audit-Events-Details.png
  static/img/integrations/amazon-aws/Amazon-SNS-Audit-Events.png
  static/img/integrations/amazon-aws/Amazon-SNS-Messages-Notifications.png
  static/img/integrations/amazon-aws/Amazon-SNS-Overview.png
  static/img/integrations/amazon-aws/Amazon-SNS-Threat-Intel.png
Labels: cla-signed

#2258 Update .clabot
  .clabot
Labels: cla-signed

#2179 More style guide additions
  docs/contributing/style-guide.md
  docusaurus.config.js
  sidebars.ts
  src/css/sumo.scss
Labels: cla-signed

#2256 Log level beta note
  docs/search/get-started-with-search/search-page/log-level.md
Labels: cla-signed

#2261 content update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#2259 Update release notes
  blog-service/2023-04-28-dashboard.md
Labels: cla-signed

#2260 Added Keyboard shortcuts
  docs/get-started/keyboard-shortcuts.md
Labels: cla-signed

#2217 formatting
  docs/integrations/amazon-aws/application-load-balancer.md
  static/img/integrations/amazon-aws/AWS-Application-Load_Balancer-Response_Analysis.png
  static/img/integrations/amazon-aws/Bucket-Name.png
Labels: cla-signed

#2264 Clarify match lists documentation for issue 2116
  docs/cse/match-lists-suppressed-lists/create-match-list.md
  docs/cse/match-lists-suppressed-lists/suppressed-lists.md
Labels: doc:update, cla-signed

#2266 Update index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
Labels: cla-signed

#2263 updated screens and content
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/akamai-siem-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dropbox-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sophos-central-source.md
  static/img/send-data/Akamai-SIEM-API-Source.png
  static/img/send-data/airtable-config-main.png
  static/img/send-data/azure-event-hubs-input.png
  static/img/send-data/box-source1.png
  static/img/send-data/citrix-cloud-config-main.png
  static/img/send-data/dropbox-input.png
  static/img/send-data/sophos-central-source.png
Labels: cla-signed

#2271 Update json-parameters-hosted-sources.md
  docs/send-data/use-json-configure-sources/json-parameters-hosted-sources.md
Labels: cla-signed

#2129 TRIDENT-17567 - Doc for Insight Trainer
  docs/cse/rules/index.md
  docs/cse/rules/insight-trainer.md
  docs/integrations/sumo-apps/cse.md
  sidebars.ts
  static/img/cse/cloud-siem-insight-trainer-dashboard.png
  static/img/cse/cloud-siem-insight-trainer-filters.png
  static/img/cse/cloud-siem-insight-trainer-filters.snagx
  static/img/cse/cloud-siem-insight-trainer-recommendations-summary.png
  static/img/cse/cloud-siem-trainer-recommended-rule-severities.png
  static/img/integrations/sumo-apps/cloud-siem-insight-trainer-dashboard.png
Labels: doc:new, cla-signed

#2268 updated data sources
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
Labels: cla-signed

#2213 Doc - Support for Infrequent Tier SLOs.
  docs/manage/partitions-data-tiers/infrequent-tier-dashboard-support.md
  docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
  static/img/partitions-data-tiers/infrequent-support-slo.png
Labels: cla-signed

#2273 CSE release notes for 5/3/23
  blog-cse/2023-05-03-application-update.md
  static/img/release-notes/cse/insight-trainer.png
Labels: cla-signed

#2267 Reusable snippets for AWS Sources and Rate limit
  docs/api/collector-management/collector-api-methods-examples.md
  docs/api/collector-management/source-api.md
  docs/api/metrics.md
  docs/api/search-job.md
  docs/api/tracing.md
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/cloudfront.md
  docs/integrations/amazon-aws/elastic-load-balancer-app.md
  docs/integrations/amazon-aws/elastic-load-balancing-classic.md
  docs/integrations/amazon-aws/s3-audit.md
  docs/integrations/amazon-aws/ses.md
  docs/integrations/google/app-engine.md
  docs/integrations/google/bigquery.md
  docs/integrations/google/cloud-audit.md
  docs/integrations/google/cloud-firewall.md
  docs/integrations/google/cloud-functions.md
  docs/integrations/google/cloud-iam.md
  docs/integrations/google/cloud-load-balancing.md
  docs/integrations/google/cloud-sql.md
  docs/integrations/google/cloud-storage.md
  docs/integrations/google/cloud-vpc.md
  docs/integrations/google/compute-engine.md
  docs/integrations/saas-cloud/acquia.md
  docs/manage/data-forwarding/installed-collectors.md
  docs/reuse/api-rate-limit.md
  docs/reuse/apps/create-aws-s3-source.md
  docs/send-data/collection/processing-rules/include-and-exclude-rules.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-sources.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dropbox-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sailpoint-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
  docs/send-data/hosted-collectors/http-source/otlp.md
  docs/send-data/hosted-collectors/ms-office-audit-source.md
  docs/send-data/installed-collectors/sources/script-source/index.md
  docs/send-data/installed-collectors/sources/script-source/use-cron-expression.md
Labels: cla-signed

#2226 Data Volume Index.
  docs/manage/ingestion-volume/data-volume-index/index.md
Labels: cla-signed

#2269 updated box-plot docs
  docs/dashboards-new/panels/box-plot-charts.md
  static/img/dashboards-new/panels/box-plot-charts/Box-plot.png
  static/img/dashboards-new/panels/box-plot-charts/charts_box_plot.png
  static/img/dashboards-new/panels/box-plot-charts/time-series-or-categorical.png
Labels: cla-signed

#2230 Ingestion and Volume Index
  docs/manage/ingestion-volume/index.md
Labels: cla-signed

#2209 Connections and Integrations Index
  docs/manage/connections-integrations/index.md
Labels: cla-signed

#2211 Content Sharing Index
  docs/manage/content-sharing/index.md
Labels: cla-signed

#2214 Data Forwarding Index
  docs/manage/data-forwarding/index.md
Labels: cla-signed

#2274 Fix typo, change ectd to etcd
  docs/observability/kubernetes/about.md
Labels: cla-signed

#2009 Trident 16024 onboarding checklist for cse
  docs/cse/administration/onboarding-checklist-cse.md
  sidebars.ts
  static/img/cse/cse-option-in-left-nav.png
Labels: doc:new, cla-signed, do-not-merge

#2276 updated screenshots
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/docusign-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-source.md
  static/img/send-data/docusign-config-main.png
  static/img/send-data/druva-config.png
Labels: cla-signed

#2208 Introducing dotnet full autoinstrumentation
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
Labels: cla-signed

#2278 Ingest Budgets Index
  docs/manage/ingestion-volume/ingest-budgets/index.md
Labels: cla-signed

#2283 2280 write release note for connections management audit logs
  blog-service/2023-05-04-manage-account.md
  docs/manage/security/audit-event-index.md
Labels: doc:new, cla-signed

#2284 TRIDENT-17883 - Update Automation Service bridge doc
  docs/cse/automation-service/automation-service-bridge.md
Labels: doc:update, cla-signed

#2281 Update migrate-new-dashboards.md
  docs/dashboards-new/migrate-to-new-dashboards.md
Labels: cla-signed

#2171 Admonitions CSS
  src/css/sumo.scss
Labels: cla-signed

#2277 Added-ReleaseNotes
  blog-collector/2023-05-05.md
Labels: cla-signed, do-not-merge

#2084 Sumo OTel Collector Quickstart
  docs/get-started/index.md
  docs/send-data/opentelemetry-collector/index.md
  docs/send-data/opentelemetry-collector/performance-benchmarks.md
  docs/send-data/opentelemetry-collector/quickstart.md
  docs/send-data/opentelemetry-collector/sumo-logic-opentelemetry-vs-opentelemetry-upstream-relationship.md
  docs/send-data/opentelemetry-collector/troubleshooting-faq.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#2286 Re-enabled staging env
  .github/workflows/pr.yml
Labels: cla-signed

#2290 updated migrated dashboard screenshots
  docs/integrations/amazon-aws/cloudfront.md
  static/img/integrations/amazon-aws/AWS-CloudFront-Latency-Monitoring.png
  static/img/integrations/amazon-aws/AWS-Cloudfront-Overview.png
  static/img/integrations/amazon-aws/Amazon-CloudFront-VisitorStatistics.png
  static/img/integrations/amazon-aws/Amazon-CloudFront-WebOperations.png
  static/img/integrations/google/Google-Bigquery-Overview.png
  static/img/integrations/google/Google-Bigquery-Queries.png
  static/img/integrations/google/Google-Bigquery-Users.png
  static/img/integrations/google/Google-Bigquery-mgmt.png
  static/img/integrations/google/google-cloud-functions-advanced-metrics.png
  static/img/integrations/google/google-cloud-functions-overview.png
  static/img/integrations/google/google-cloud-functions-statistics.png
  static/img/integrations/google/google-cloud-load-balancing-overview.png
  static/img/integrations/google/google-cloud-load-balancing-request-analysis.png
  static/img/integrations/google/google-cloud-load-balancing-status-analysis.png
  static/img/integrations/google/google-cloud-sql-activity.png
  static/img/integrations/google/google-cloud-sql-failures.png
  static/img/integrations/google/google-cloud-sql-overview.png
  static/img/integrations/google/google-cloud-sql-users.png
Labels: cla-signed

#2265 TRIDENT-17659 - Add inventory sources
  docs/cse/administration/inventory-sources-and-data.md
Labels: doc:new, cla-signed

#2293 2023 05 05 cse content
  blog-cse/2023-05-05-content.md
Labels: cla-signed

#2285 CSE Docs | Updated standard-match-lists.md
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: cla-signed

#2288 added missing conjunction
  docs/integrations/amazon-aws/ec2-cloudwatch-metrics.md
Labels: cla-signed

#2287 renamed Missile map to Connection map
  blog-service/2023-04-28-dashboard.md
Labels: cla-signed

#2297 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#2298 Add Rapid7 mappings
  docs/cse/administration/inventory-sources-and-data.md
Labels: doc:new, cla-signed

#2296 style/admonitions
  docs/contributing/style-guide.md
  src/css/sumo.scss
Labels: cla-signed

#2299 Revert "Re-enabled staging env"
  .github/workflows/pr.yml
Labels: cla-signed

#2302 Update parse-json-formatted-logs.md
  docs/search/search-query-language/parse-operators/parse-json-formatted-logs.md
Labels: cla-signed

#2303 style fixes
  docs/contributing/style-guide.md
Labels: cla-signed

#2307 Update where.md
  docs/search/search-query-language/search-operators/where.md
Labels: cla-signed

#2314 Update about-automation-service.md
  docs/cse/automation-service/about-automation-service.md
Labels: cla-signed

#2292 Sankey cahrt
  docs/dashboards-new/panels/sankey-charts.md
  sidebars.ts
  static/img/dashboards-new/panels/sankey-chart/chart_type.png
  static/img/dashboards-new/panels/sankey-chart/panel_type.png
  static/img/dashboards-new/panels/sankey-chart/sankey_chart.png
Labels: cla-signed

#2304 Azure screens update
  docs/integrations/microsoft-azure/active-directory-azure.md
  static/img/integrations/microsoft-azure/Azure-AD-Role-Management.png
  static/img/integrations/microsoft-azure/Azure-AD-User-Management.png
  static/img/integrations/microsoft-azure/Azure-Active-Directory-Authorization_Authentication_Other.png
  static/img/integrations/microsoft-azure/Azure-ActiveDirectory-Application-Management.png
  static/img/integrations/microsoft-azure/Azure-ActiveDirectory-Group-Management.png
  static/img/integrations/microsoft-azure/Azure_Active_Directory-Directory_Management.png
  static/img/integrations/microsoft-azure/azure-ad-failure-sign-in-event.png
  static/img/integrations/microsoft-azure/azure-ad-overview.png
  static/img/integrations/microsoft-azure/azure-ad-successful-sign-in-events.png
Labels: cla-signed

#2317 Add JWT token section
  docs/cloud-soar/cloud-soar-bridge.md
Labels: doc:update, cla-signed

#2316 Scheduled Views Index
  docs/manage/scheduled-views/index.md
Labels: cla-signed

#2310 Partitions and Data Tiers Index
  docs/manage/partitions-data-tiers/index.md
Labels: cla-signed

#2313 Integration framework article for the Automation Service
  docs/cse/automation-service/automation-service-integration-framework.md
  docs/cse/automation-service/automation-service-integrations.md
  sidebars.ts
  static/img/cse/integration-framework-action-editor.png
  static/img/cse/integration-framework-action-result-2.png
  static/img/cse/integration-framework-action-result.png
  static/img/cse/integration-framework-add-automation-rule.png
  static/img/cse/integration-framework-add-integration.png
  static/img/cse/integration-framework-app-3-image-1.png
  static/img/cse/integration-framework-app-d-image-1.png
  static/img/cse/integration-framework-app-d-image-2.png
  static/img/cse/integration-framework-app-e-image-2.png
  static/img/cse/integration-framework-app-e-image-3.png
  static/img/cse/integration-framework-app-e-image-4.png
  static/img/cse/integration-framework-browser-market-share.png
  static/img/cse/integration-framework-container.png
  static/img/cse/integration-framework-custom-docker-image.png
  static/img/cse/integration-framework-daemon-action.png
  static/img/cse/integration-framework-definition.png
  static/img/cse/integration-framework-docker-editor-2.png
  static/img/cse/integration-framework-docker-editor-3.png
  static/img/cse/integration-framework-docker-editor.png
  static/img/cse/integration-framework-file-portability.png
  static/img/cse/integration-framework-new-integration.png
  static/img/cse/integration-framework-show-details-2.png
  static/img/cse/integration-framework-show-details.png
  static/img/cse/integration-framework-test-action.png
  static/img/cse/integration-framework-test-docker-image-2.png
  static/img/cse/integration-framework-test-docker-image-3.png
  static/img/cse/integration-framework-test-docker-image-4.png
  static/img/cse/integration-framework-test-docker-image.png
  static/img/cse/integration-framework-upload.png
Labels: doc:new, cla-signed

#2326 Add data range text
  docs/cse/rules/insight-trainer.md
Labels: doc:update, cla-signed

#2323 Update 2023-05-05.md
  blog-collector/2023-05-05.md
Labels: cla-signed

#2321 Security Index
  docs/manage/security/index.md
Labels: cla-signed

#2262 zoom doc update
  docs/integrations/saas-cloud/zoom.md
  docs/send-data/hosted-collectors/index.md
  docs/send-data/hosted-collectors/webhook-sources/zoom.md
  sidebars.ts
  static/img/send-data/advanced-options.png
  static/img/send-data/app-activated-message.png
  static/img/send-data/events-subscriptions.png
  static/img/send-data/processing-rules.png
  static/img/send-data/secret-token.png
  static/img/send-data/show-url-zoom.png
  static/img/send-data/zoom-app-info.png
  static/img/send-data/zoom-configuration-settings.png
  static/img/send-data/zoom-sign-in.png
Labels: cla-signed, do-not-merge

#2319 zero networks segment doc added
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zero-networks-segment-source.md
  sidebars.ts
  src/css/sumo.scss
  static/img/send-data/filters.png
  static/img/send-data/zero-network-config.png
  static/img/send-data/zero-networks-icon.png
Labels: cla-signed, do-not-merge

#2332 Update transactionize-operator.md
  docs/search/search-query-language/transaction-analytics/transactionize-operator.md
Labels: cla-signed

#2330 More Legacy/404s
  cid-redirects.json
Labels: cla-signed

#2324 Add Cloud SOAR Integration Framework Manual as new article
  docs/cloud-soar/cloud-soar-integration-framework.md
  sidebars.ts
  static/img/cloud-soar/integration-framework-action-editor.png
  static/img/cloud-soar/integration-framework-action-result-2.png
  static/img/cloud-soar/integration-framework-action-result.png
  static/img/cloud-soar/integration-framework-add-automation-rule.png
  static/img/cloud-soar/integration-framework-add-integration.png
  static/img/cloud-soar/integration-framework-app-3-image-1.png
  static/img/cloud-soar/integration-framework-app-d-image-1.png
  static/img/cloud-soar/integration-framework-app-d-image-2.png
  static/img/cloud-soar/integration-framework-app-e-image-2.png
  static/img/cloud-soar/integration-framework-app-e-image-3.png
  static/img/cloud-soar/integration-framework-app-e-image-4.png
  static/img/cloud-soar/integration-framework-browser-market-share.png
  static/img/cloud-soar/integration-framework-container.png
  static/img/cloud-soar/integration-framework-custom-docker-image.png
  static/img/cloud-soar/integration-framework-daemon-action.png
  static/img/cloud-soar/integration-framework-definition.png
  static/img/cloud-soar/integration-framework-docker-editor-2.png
  static/img/cloud-soar/integration-framework-docker-editor-3.png
  static/img/cloud-soar/integration-framework-docker-editor.png
  static/img/cloud-soar/integration-framework-file-portability.png
  static/img/cloud-soar/integration-framework-new-integration.png
  static/img/cloud-soar/integration-framework-show-details-2.png
  static/img/cloud-soar/integration-framework-show-details.png
  static/img/cloud-soar/integration-framework-test-action.png
  static/img/cloud-soar/integration-framework-test-docker-image-2.png
  static/img/cloud-soar/integration-framework-test-docker-image-3.png
  static/img/cloud-soar/integration-framework-test-docker-image-4.png
  static/img/cloud-soar/integration-framework-test-docker-image.png
  static/img/cloud-soar/integration-framework-upload.png
Labels: doc:new, cla-signed

#2334 SAML Index
  docs/manage/security/saml/index.md
Labels: cla-signed

#2335 Manage Roles Index
  docs/manage/users-roles/roles/index.md
Labels: cla-signed

#2329 Release zero network
  blog-service/2023-05-12-apps.md
Labels: cla-signed, hot🔥

#2331 release note added
  blog-service/2023-05-12-apps-http.md
Labels: cla-signed, hot🔥

#2309 bigquery c2c docs added
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-bigquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/img/send-data/Google_Create_Service_Account.png
  static/img/send-data/Google_IAM_and_Admin.png
  static/img/send-data/Google_Project_Name.png
  static/img/send-data/Google_Service_Account_Keys.png
  static/img/send-data/Google_add_key.png
  static/img/send-data/Google_type_json.png
  static/img/send-data/google-bigquery-icon.png
  static/img/send-data/google-bigquery_config_main.png
Labels: cla-signed, do-not-merge

#2320 Added Release Notes
  blog-service/2023-05-11-traces.md
Labels: cla-signed, hot🔥

#2343 upadted cropped screenshots
  static/img/get-started/library/log-analysis-qs-visits.png
  static/img/integrations/saas-cloud/Zoom_Administrator_Activity.png
  static/img/integrations/saas-cloud/Zoom_Authentication.png
  static/img/integrations/saas-cloud/Zoom_Availability.png
  static/img/integrations/saas-cloud/Zoom_Guest_Activity.png
  static/img/integrations/saas-cloud/Zoom_Meeting_Security.png
  static/img/integrations/saas-cloud/Zoom_Meeting_Usage.png
  static/img/integrations/saas-cloud/Zoom_Overview.png
  static/img/integrations/saas-cloud/Zoom_User_Activity.png
  static/img/integrations/saas-cloud/Zoom_Webinars.png
Labels: cla-signed

#2318 Tracing update
  docs/apm/traces/view-and-investigate-traces.md
  static/img/traces/2023-05-10_13-36-59.png
  static/img/traces/breakdown2.png
  static/img/traces/charttype.png
  static/img/traces/error-count-histogram.png
  static/img/traces/error-count-timeseries.png
  static/img/traces/span-count-histogram.png
  static/img/traces/span-count-timeseries.png
  static/img/traces/trace-duration-histogram.png
  static/img/traces/trace-duration-timeseries.png
  static/img/traces/trace-query-view.png
Labels: cla-signed, do-not-merge

#2347 Added Release Notes
  blog-service/2023-05-12-traces.md
Labels: cla-signed, hot🔥

#2349 Updated-Securitylake
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  static/img/send-data/notifications.png
Labels: cla-signed

#2350 Update bridge download instructions
  docs/cloud-soar/cloud-soar-bridge.md
  docs/cse/automation-service/automation-service-bridge.md
Labels: doc:update, cla-signed

#2333 BigQuery release notes
  blog-service/2023-05-12-apps-bigquery.md
Labels: cla-signed

#2346 Add new integrations for the Automation Service
  docs/cse/automation-service/automation-service-integrations.md
Labels: doc:minor edit, cla-signed

#2341 Manage Users Index
  docs/manage/users-roles/users/index.md
Labels: cla-signed

#2344 Update integration framework articles
  docs/cloud-soar/cloud-soar-integration-framework.md
  docs/cse/automation-service/automation-service-integration-framework.md
Labels: doc:update, cla-signed

#2336 Help page fixes and updates
  docs/get-started/help.md
  static/img/get-started/Help-Feature-Request.png
  static/img/get-started/help-menu.png
Labels: cla-signed

#2354 19.441-1 Release update
  blog-collector/2023-05-05.md
Labels: cla-signed

#2355 CID for Kubernetes DevOps App page added
  cid-redirects.json
Labels: cla-signed

#2356 Managing Metrics Volume
  docs/metrics/manage-metric-volume/index.md
Labels: cla-signed

#2351 Update docs based on experience with a customer
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-bigquery-source.md
Labels: cla-signed

#2361 Update .clabot
  .clabot
Labels: cla-signed

#2360 Cloud Soar Bridge Docs Recommended Changes
  docs/cloud-soar/cloud-soar-bridge.md
Labels: cla-signed

#2359 Docusaurus v2.4.1
  package.json
  yarn.lock
Labels: cla-signed

#2362 Webhook alerts index
  docs/alerts/webhook-connections/index.md
  static/img/alerts/webhooks.png
Labels: cla-signed

#2363 Merge duplicate AWS PrivateLink docs
  docs/beta/aws-private-link.md
  docs/integrations/amazon-aws/aws-privatelink.md
  sidebars.ts
Labels: cla-signed

#2364 Legacy and 404 fixes
  cid-redirects.json
Labels: cla-signed

#2086 Outstanding OTEL questions
  docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
Labels: cla-signed

#2305 doc structure updated
  blog-service/2023-03-02-dashboard-migration.md
  cid-redirects.json
  docs/dashboards-new/dashboards-migration/changes-after-migration.md
  docs/dashboards-new/dashboards-migration/index.md
  docs/dashboards-new/dashboards-migration/steps-to-migrate.md
  docs/dashboards-new/index.md
  docs/dashboards-new/migrate-to-new-dashboards.md
  sidebars.ts
  static/img/dashboards-new/color-mapping.png
Labels: cla-signed

#2371 Update view-and-investigate-traces.md
  docs/apm/traces/view-and-investigate-traces.md
Labels: cla-signed

#2368 Explore doc update
  docs/dashboards-new/explore-view.md
  static/img/dashboards-new/explore/apm-service-view.png
  static/img/dashboards-new/explore/aws-view.png
  static/img/dashboards-new/explore/brand_theme_apply_filters.png
  static/img/dashboards-new/explore/brand_theme_save_filters.png
  static/img/dashboards-new/explore/db-drilldown.png
  static/img/dashboards-new/explore/k8s-view.png
  static/img/dashboards-new/explore/remove-default-filter.png
  static/img/dashboards-new/explore/select-filter.png
  static/img/dashboards-new/explore/set-default.png
  static/img/dashboards-new/explore/stack-linking.png
Labels: cla-signed

#2358 Linking Dashboards docs-220644
  docs/dashboards-new/link-dashboards.md
  static/img/dashboards-new/link-dashboard-explore/dashboard-stack-linking-august-2021.png
  static/img/dashboards-new/link-dashboard-explore/dashboard-stack-linking.png
Labels: cla-signed

#2365 Update DocuSign to enable DocuSign Monitor
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/docusign-source.md
Labels: cla-signed

#2374 Update .clabot
  .clabot
Labels: cla-signed

#2373 Update mysql.md - Parsing error from sample telegraf.conf
  docs/integrations/databases/mysql.md
Labels: cla-signed

#2375 Add Insight Trainer video
  docs/cse/rules/insight-trainer.md
Labels: doc:update, cla-signed

#2376 Tracing fix
  docs/apm/traces/tracing-dashboards.md
  static/img/apm/traces/01.-Application-Service-Overview.png
  static/img/apm/traces/01.-Environment-Overview.png
  static/img/apm/traces/02.-Service-Health-Across-Applications-within-Environment.png
  static/img/apm/traces/02.-Service-Health-Across-Applications.png
  static/img/apm/traces/04.-Application-Health-Across-Services.png
  static/img/apm/traces/06.-Service-Health-Across-Environments.png
Labels: cla-signed

#2381 updated-environmentview
  docs/apm/traces/tracing-dashboards.md
Labels: cla-signed

#2382 Screenshots update
  docs/apm/traces/tracing-dashboards.md
  static/img/apm/traces/03.-Application-Service-Health-Across-Operations-within-Environment.png
  static/img/apm/traces/03.-Application-Service-Health-Across-Operations.png
  static/img/apm/traces/04.-Service-Health-Across-Applications-and-Operations-within-Environment.png
  static/img/apm/traces/04.-Service-Health-Across-Applications-and-Operations.png
  static/img/apm/traces/05.-Application-Service-Health-Across-Environments.png
Labels: cla-signed

#2377 Clarification - embedding videos
  docs/contributing/style-guide.md
Labels: cla-signed

#2380 SLO tags
  docs/observability/reliability-management-slo/create-slo.md
  static/img/observability/slo-details.png
Labels: cla-signed, do-not-merge

#2387 Updated dashboards screenshots files based on mewboard migration. Kee…
  docs/integrations/pci-compliance/palo-alto-networks-9.md
  docs/integrations/security-threat-detection/cisco-asa.md
  docs/integrations/security-threat-detection/palo-alto-networks-6.md
  docs/integrations/security-threat-detection/palo-alto-networks-8.md
  docs/integrations/security-threat-detection/palo-alto-networks-9.md
  static/img/integrations/pci-compliance/PCI-Compliance-For-Palo-Alto-Networks-9-PCI-Req-01-02-Data-Access-Monitoring.png
  static/img/integrations/pci-compliance/PCI-Compliance-For-Palo-Alto-Networks-9-PCI-Req-01-Accepted-and-Rejected-Traffic.png
  static/img/integrations/pci-compliance/PCI-Compliance-For-Palo-Alto-Networks-9-PCI-Req-01-Traffic-Direction-Monitoring.png
  static/img/integrations/pci-compliance/PCI-Compliance-For-Palo-Alto-Networks-9-PCI-Req-02-04-Insecure-Data-In-Transit.png
  static/img/integrations/security-threat-detection/Cisco-ASA-Firewall-Detail.png
  static/img/integrations/security-threat-detection/Cisco-ASA-Logs-Analytics.png
  static/img/integrations/security-threat-detection/Cisco-ASA-Overview.png
  static/img/integrations/security-threat-detection/PAN-Generic.png
  static/img/integrations/security-threat-detection/PAN-Overview.png
  static/img/integrations/security-threat-detection/PAN-Threat-Analysis.png
  static/img/integrations/security-threat-detection/PAN-Traffic-Monitoring.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Configuration-Analysis.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Correlation-Analysis.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-High-Severity-Threats.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Overview.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-System-Monitoring.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Threat-Analysis.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Threat-Overview.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Traffic-Insight-File-Activity.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Traffic-Insight-Web-Activity.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Traffic-Monitoring.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-8-Traps-V4-Monitoring.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-Configuration-Analysis.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-HIPMatch-Monitoring.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-High-Severity-Threats.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-Overview.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-System-Monitoring.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-Threat-Analysis.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-Threat-Overview.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-Traffic-Insight-File-Activity.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-Traffic-Insight-Web-Activity.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-Traffic-Monitoring.png
  static/img/integrations/security-threat-detection/Palo-Alto-Networks-9-USERID-Monitoring.png
Labels: cla-signed, do-not-merge

#2384 chore(tracing): update ruby versions for tracing
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby-on-rails.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby.md
Labels: cla-signed

#2378 Update changes-after-migration.md
  docs/dashboards-new/dashboards-migration/changes-after-migration.md
Labels: cla-signed

#2392 Update diagnose-issues.md
  docs/observability/diagnose-issues.md
Labels: cla-signed

#2394 Fixed AWS CloudTrail DevOps image
  static/img/integrations/amazon-aws/GI-CloudTrail-DevOpsDB_2.png
Labels: cla-signed

#2393 Update set-up-saml.md
  docs/manage/security/saml/set-up-saml.md
Labels: cla-signed

#2395 Azure AD images
  docs/integrations/microsoft-azure/active-directory-azure.md
Labels: cla-signed

#2391 Legacy/404 fixes
  cid-redirects.json
  docs/alerts/webhook-connections/cloud-soar.md
  docs/alerts/webhook-connections/datadog.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#2339 Symantec web security service app
  cid-redirects.json
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/symantec-web-security-service.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-bigquery-source.md
  sidebars.ts
  static/img/integrations/saas-cloud/Symantec-Web-Security-Service-Security-Overview.png
  static/img/integrations/saas-cloud/Symantec-Web-Security-Service-Web-Activity-Overview.png
Labels: cla-signed, do-not-merge

#2399 added-himanshu
  .clabot
Labels: cla-signed

#2405 Added-Shivani
  .clabot
Labels: cla-signed

#2383 Metrics Operators Index
  docs/metrics/metrics-operators/index.md
Labels: cla-signed

#2401 Updating screenshots of AWS WAF & PCI compliance for AWS CloudTrail
  docs/integrations/amazon-aws/cloudtrail-pci-compliance.md
  docs/integrations/amazon-aws/waf.md
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-01-Access-Monitoring.png
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-08-10-Privileged-Activity.png
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-08-Account-System-Monitoring.png
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-10-Login-Activity.png
  static/img/integrations/amazon-aws/AWS-Cloudtrail-PCIReq08-AccountSystemMonitoring.png
  static/img/integrations/amazon-aws/AWS-Cloudtrail-PCIReq0810-PrivilegedActivity.png
  static/img/integrations/amazon-aws/AWS-Cloudtrail-PCIReq10-LoginActivity.png
  static/img/integrations/amazon-aws/aws-waf-overview.png
  static/img/integrations/amazon-aws/aws-waf-threat-intelligence.png
  static/img/integrations/amazon-aws/aws-waf-traffic.png
Labels: cla-signed

#2322 troubleshooting content added
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#2406 rm unused AWS image
  .clabot
  cid-redirects.json
  docs/alerts/webhook-connections/cloud-soar.md
  docs/alerts/webhook-connections/datadog.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby-on-rails.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby.md
  docs/dashboards-new/dashboards-migration/changes-after-migration.md
  docs/integrations/amazon-aws/cloudtrail-pci-compliance.md
  docs/integrations/amazon-aws/waf.md
  docs/integrations/microsoft-azure/active-directory-azure.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/symantec-web-security-service.md
  docs/manage/security/saml/set-up-saml.md
  docs/observability/diagnose-issues.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-bigquery-source.md
  sidebars.ts
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-01-Access-Monitoring.png
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-08-10-Privileged-Activity.png
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-08-Account-System-Monitoring.png
  static/img/integrations/amazon-aws/AWS-CloudTrail-PCI-Req-10-Login-Activity.png
  static/img/integrations/amazon-aws/AWS-Cloudtrail-AccessMonitoring.png
  static/img/integrations/amazon-aws/AWS-Cloudtrail-PCIReq08-AccountSystemMonitoring.png
  static/img/integrations/amazon-aws/AWS-Cloudtrail-PCIReq0810-PrivilegedActivity.png
  static/img/integrations/amazon-aws/AWS-Cloudtrail-PCIReq10-LoginActivity.png
  static/img/integrations/amazon-aws/GI-CloudTrail-DevOpsDB_2.png
  static/img/integrations/amazon-aws/aws-waf-overview.png
  static/img/integrations/amazon-aws/aws-waf-threat-intelligence.png
  static/img/integrations/amazon-aws/aws-waf-traffic.png
  static/img/integrations/saas-cloud/Symantec-Web-Security-Service-Security-Overview.png
  static/img/integrations/saas-cloud/Symantec-Web-Security-Service-Web-Activity-Overview.png
Labels: cla-signed

#2403 CON-1987: added base URL and updated UI
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
  static/img/send-data/Microsoft-Graph-Security-API-Source-input.png
Labels: cla-signed

#2407 Add First Seen rule to list of rules
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/index.md
Labels: doc:update, cla-signed

#2414 Update .clabot with mvirga-sumo
  .clabot
Labels: cla-signed

#2412 Update cloud-soar-bridge.md - High Availability Section
  docs/cloud-soar/cloud-soar-bridge.md
Labels: doc:update, cla-signed

#2418 Update .clabot
  .clabot
Labels: cla-signed

#2417 cid-redirect for AWS PL
  cid-redirects.json
Labels: cla-signed

#2411 AWS Observability Solution Index.
  docs/observability/aws/index.md
Labels: cla-signed

#2408 Metrics Queries Index
  docs/metrics/metrics-queries/index.md
Labels: cla-signed

#2402 Mention alternative quantize syntax (and clean-up metrics operators docs)
  docs/metrics/introduction/metric-quantization.md
  docs/metrics/metrics-operators/accum.md
  docs/metrics/metrics-operators/along.md
  docs/metrics/metrics-operators/avg.md
  docs/metrics/metrics-operators/bottomk.md
  docs/metrics/metrics-operators/count.md
  docs/metrics/metrics-operators/delta.md
  docs/metrics/metrics-operators/eval.md
  docs/metrics/metrics-operators/ewma.md
  docs/metrics/metrics-operators/fillmissing.md
  docs/metrics/metrics-operators/filter.md
  docs/metrics/metrics-operators/histogram-quantile.md
  docs/metrics/metrics-operators/in.md
  docs/metrics/metrics-operators/max.md
  docs/metrics/metrics-operators/min.md
  docs/metrics/metrics-operators/outlier.md
  docs/metrics/metrics-operators/parse.md
  docs/metrics/metrics-operators/pct.md
  docs/metrics/metrics-operators/predict.md
  docs/metrics/metrics-operators/quantize.md
  docs/metrics/metrics-operators/rate.md
  docs/metrics/metrics-operators/stddev.md
  docs/metrics/metrics-operators/sum.md
  docs/metrics/metrics-operators/timeshift.md
  docs/metrics/metrics-operators/topk.md
  docs/metrics/metrics-operators/where.md
Labels: cla-signed

#2419 Add videos to SIEM articles
  docs/cse/administration/create-cse-actions.md
  docs/cse/administration/create-cse-context-actions.md
  docs/cse/administration/create-custom-threat-intel-source.md
  docs/cse/ingestion/sumo-logic-ingest-mapping.md
  docs/cse/records-signals-entities-insights/about-cse-insight-ui.md
  docs/cse/records-signals-entities-insights/cse-heads-up-display.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/insight-trainer.md
  docs/cse/rules/rule-tuning-expressions.md
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-chain-rule.md
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-match-rule.md
  docs/cse/rules/write-threshold-rule.md
  docs/integrations/sumo-apps/cse.md
  sidebars.ts
  static/img/cse/chain.png
  static/img/cse/match.png
  static/img/cse/threshold.png
Labels: doc:update, cla-signed

#2413 Update automation-service-bridge.md - Automation Service
  docs/cse/automation-service/automation-service-bridge.md
Labels: doc:update, cla-signed

#2420 Removes extraneous API Gateway docs
  docs/integrations/amazon-aws/api-gateway/api-gateway-classic.md
  docs/integrations/amazon-aws/api-gateway/api-gateway-s3m.md
Labels: cla-signed

#2409 Renaming image names of waf readme
  docs/integrations/amazon-aws/waf.md
Labels: cla-signed

#2421 rm outdated VMWare zip files
  docs/integrations/containers-orchestration/vmware-legacy.md
  docs/integrations/containers-orchestration/vmware.md
Labels: cla-signed

#2422 Add videos to SOAR articles
  docs/cloud-soar/automation.md
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/incidents-triage.md
  docs/cse/records-signals-entities-insights/configure-custom-insight.md
  docs/cse/records-signals-entities-insights/insight-generation-process.md
Labels: doc:update, cla-signed

#2423 Dashboard migration colors
  docs/dashboards-new/dashboards-migration/changes-after-migration.md
Labels: cla-signed

#2424 Tracing OTEL docs org
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/custom-tags-configuration.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/traceid-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/traceid-spanid-injection-into-logs.md
  sidebars.ts
Labels: cla-signed

#2426 Updated minor changes to awso deploy with terraform page.
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#2369 MS Graph Azure AD Reporting app docs
  cid-redirects.json
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/ms-graph-azure-ad-reporting.md
  sidebars.ts
  static/img/integrations/saas-cloud/Microsoft-Graph-Azure-AD-Reporting-Audits.png
  static/img/integrations/saas-cloud/Microsoft-Graph-Azure-AD-Reporting-Provisioning-Activities.png
  static/img/integrations/saas-cloud/Microsoft-Graph-Azure-AD-Reporting-Sign-Ins.png
Labels: cla-signed, do-not-merge, hot🔥

#2429 adding-saumya
  .clabot
Labels: cla-signed

#2428 added new dashboard screenshots
  static/img/integrations/app-development/jfrog-xray-container-analysis.png
  static/img/integrations/app-development/jfrog-xray-detected-vulnerabilities.png
  static/img/integrations/app-development/jfrog-xray-overview.png
  static/img/integrations/app-development/jfrog-xray-threat-analysis.png
  static/img/integrations/app-development/jfrog-xray-vulnerable-artifacts.png
  static/img/integrations/saas-cloud/Slack_Access.png
  static/img/integrations/saas-cloud/Slack_Audit_Overview.png
  static/img/integrations/saas-cloud/Slack_Bots.png
  static/img/integrations/saas-cloud/Slack_Channel_Audit.png
  static/img/integrations/saas-cloud/Slack_File_And_App_Audit.png
  static/img/integrations/saas-cloud/Slack_Members.png
  static/img/integrations/saas-cloud/Slack_Overview.png
  static/img/integrations/saas-cloud/Slack_Public_Channels.png
  static/img/integrations/saas-cloud/Slack_Public_Messages_Investigation.png
  static/img/integrations/saas-cloud/Slack_User_Audit.png
  static/img/integrations/saas-cloud/Slack_Workspace_Audit.png
Labels: cla-signed
