Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-02, with the labels that each got.

#1531 Formatting corrections - keyword search expressions
  docs/search/get-started-with-search/build-search/keyword-search-expressions.md
Labels: cla-signed

#1534 Update keyword-search-expressions.md
  docs/search/get-started-with-search/build-search/keyword-search-expressions.md
Labels: cla-signed

#1529 updated-operators
  docs/cse/rules/cse-rules-syntax.md
Labels: cla-signed

#1537 added-newc2c
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
  sidebars.ts
  static/img/send-data/access-management.png
  static/img/send-data/api-access.png
  static/img/send-data/citrix-cloud-base-url.png
  static/img/send-data/citrix-cloud-config-main.png
  static/img/send-data/citrix-cloud-icon.png
  static/img/send-data/create-client.png
  static/img/send-data/customer-id.png
  static/img/send-data/navigation-button.png
  static/img/send-data/navigation-menu.png
  static/img/send-data/successful-credentials.png
Labels: cla-signed

#1542 Nav fix
  cid-redirects.json
  docs/integrations/global-intelligence/kubernetes-devops.md
  docs/observability/kubernetes/apps.md
  docs/observability/kubernetes/quickstart.md
  sidebars.ts
Labels: cla-signed

#1543 Update keyword-search-expressions.md
  docs/search/get-started-with-search/build-search/keyword-search-expressions.md
Labels: cla-signed

#1544 updated screenshots
  docs/manage/fields.md
  static/img/fields/fields-capacity.png
  static/img/fields/manage-fields-page.png
  static/img/send-data/fields-capacity.png
  static/img/send-data/manage-fields-page.png
Labels: cla-signed

#1546 add yuting
  .clabot
Labels: cla-signed

#1548 Add the restart sources to all c2c source doc page
  docs/reuse/restart-c2c-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/akamai-siem-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-amp-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloud-to-cloud-source-versions.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cybereason-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dropbox-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/duo-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-azure-ad-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-tracelogs.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/miro-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-azure-ad-reporting-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-identity-protection-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/okta-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/palo-alto-cortex-xdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-on-demand-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sailpoint-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sentinelone-mgmt-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sophos-central-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/symantec-web-security-service-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
Labels: cla-signed

#1549 Update json-parameters-installed-sources.md
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
Labels: cla-signed

#1550 Update g-suite-apps-audit-source.md
  docs/send-data/hosted-collectors/google-source/g-suite-apps-audit-source.md
Labels: cla-signed

#1535 Update lambda.md
  docs/integrations/amazon-aws/lambda.md
Labels: cla-signed

#1552 Draft
  docs/cloud-soar/mssp.md
  static/img/cloud-soar/dashboard-customize-widget-list.png
  static/img/cloud-soar/dashboard-customize.png
  static/img/cloud-soar/edit-widget-details.png
  static/img/cloud-soar/edit-widget-tenants.png
  static/img/cloud-soar/mssp-soar-options.png
  static/img/cloud-soar/playbook-list.png
  static/img/cloud-soar/playbook.png
  static/img/cloud-soar/push-field.png
  static/img/cloud-soar/save-to-tenants.png
  static/img/cloud-soar/synchronized.png
Labels: cla-signed, do-not-merge

#1551 Adjusting example for along
  docs/metrics/metrics-operators/along.md
Labels: cla-signed

#1554 formatting
  docs/cloud-soar/mssp.md
  sidebars.ts
  static/img/cloud-soar/architecture.png
  static/img/cloud-soar/nodes-mgmt-option.png
Labels: cla-signed

#1538 added-cid
  cid-redirects.json
Labels: cla-signed

#1557 new changes
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
Labels: cla-signed, hot🔥

#1558 Temp staging for Algolia
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/review.yml
Labels: cla-signed

#1562 Revert "Temp staging for Algolia"
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/review.yml
Labels: cla-signed

#1564 Update .clabot to automate security fixes
  .clabot
Labels: cla-signed

#1556 Monitor-based SLOs
  docs/observability/reliability-management-slo/create-slo.md
Labels: cla-signed

#1565 swapped otel demo with petclinic in test
  docs/apm/traces/get-started-transaction-tracing/http-traces-source.md
Labels: cla-signed

#1566 github issues
  docs/cse/integrations/insight-enrichment-server.md
  docs/cse/rules/import-yara-rules.md
  docs/manage/manage-subscription/manage-org-settings.md
  docs/metrics/introduction/joins.md
  static/img/alerts/save-as.png
  static/img/subscriptions/manage-org-links.png
Labels: cla-signed

#1560 rm baseURL from c2c reuse file
  docs/reuse/restart-c2c-source.md
Labels: cla-signed

#1563 Nav and footer
  docs/contributing/index.md
  docs/release-notes/index.md
  docusaurus.config.js
Labels: cla-signed

#1568 Codeowners, CLA
  .clabot
  .github/CODEOWNERS
Labels: cla-signed

#1540 updated suggested searches
  docs/search/get-started-with-search/suggested-searches/index.md
Labels: cla-signed

#1571 updated monitors page
  docs/alerts/monitors/create-monitor.md
  static/img/monitors/edit-recover-settings.png
  static/img/monitors/metrics-trigger-types.png
  static/img/monitors/minimum-datapoints.png
Labels: cla-signed, hot🔥

#1572 release notes for metrics monitors
  blog-service/2023-02-06-metrics-monitors.md
Labels: cla-signed, hot🔥

#1573 minor-addition
  blog-service/2023-02-06-metrics-monitors.md
Labels: cla-signed, hot🔥

#1575 Update log-search-audit-index.md
  docs/manage/security/log-search-audit-index.md
Labels: cla-signed

#1574 updated-docs
  blog-service/2023-02-06-metrics-monitors.md
  docs/api/search-job.md
Labels: cla-signed

#1570 More 404 fixes
  cid-redirects.json
  docs/contributing/glossary.md
  docs/get-started/index.md
  docs/get-started/support-terms.md
  docs/integrations/1password.md
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
  docs/integrations/amazon-aws/eks-control-plane.md
  docs/integrations/amazon-aws/lambda.md
  docs/integrations/amazon-aws/vpc-flow-logs.md
  docs/integrations/cloud-security-monitoring-analytics/amazon-vpc-flow.md
  docs/integrations/databases/cassandra.md
  docs/integrations/saas-cloud/box.md
  docs/integrations/saas-cloud/salesforce.md
  docs/integrations/security-threat-detection/trend-micro-deep-security.md
  docs/integrations/security-threat-detection/zscaler-internet-access.md
  docs/integrations/security-threat-detection/zscaler-private-access.md
  docs/observability/aws/integrations/aws-api-gateway.md
  docs/observability/work-from-home-vpn.md
  docs/search/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
  docusaurus.config.js
Labels: cla-signed

#1579 Update migrate-new-dashboards.md
  docs/dashboards-new/migrate-new-dashboards.md
Labels: cla-signed

#1533 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#1581 More 404 fixes
  blog-developer/2020/12-31.md
  cid-redirects.json
  docs/api/lookup-tables.md
  docs/contributing/glossary.md
  docs/integrations/amazon-aws/api-gateway.md
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
  docs/integrations/amazon-aws/aurora-postgresql-ulm.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/cloudfront.md
  docs/integrations/amazon-aws/dynamodb.md
  docs/integrations/amazon-aws/elastic-container-service.md
  docs/integrations/amazon-aws/elastic-load-balancer-app.md
  docs/integrations/amazon-aws/elastic-load-balancing-classic.md
  docs/integrations/amazon-aws/elasticache.md
  docs/integrations/amazon-aws/kinesis-streams.md
  docs/integrations/amazon-aws/rds.md
  docs/integrations/amazon-aws/redshift-ulm.md
  docs/integrations/amazon-aws/s3-audit.md
  docs/integrations/amazon-aws/ses.md
  docs/integrations/amazon-aws/sns.md
  docs/integrations/amazon-aws/sqs.md
  docs/integrations/amazon-aws/waf.md
  docs/integrations/app-development/puppet.md
  docs/integrations/cloud-security-monitoring-analytics/windows.md
  docs/integrations/containers-orchestration/vmware-legacy.md
  docs/integrations/containers-orchestration/vmware.md
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/oracle/performance-metrics.md
  docs/integrations/databases/redis.md
  docs/integrations/microsoft-azure/active-directory-json.md
  docs/integrations/microsoft-azure/active-directory-legacy.md
  docs/integrations/microsoft-azure/windows-json-pci-compliance.md
  docs/integrations/microsoft-azure/windows-json.md
  docs/integrations/microsoft-azure/windows-legacy-pci-compliance.md
  docs/integrations/microsoft-azure/windows-legacy.md
  docs/integrations/pci-compliance/linux.md
  docs/integrations/saas-cloud/salesforce.md
  docs/integrations/security-threat-detection/cisco-asa.md
  docs/integrations/security-threat-detection/cisco-meraki.md
  docs/integrations/security-threat-detection/trend-micro-deep-security.md
  docs/integrations/security-threat-detection/twistlock.md
  docs/integrations/security-threat-detection/zscaler-web-security.md
  docs/integrations/web-servers/haproxy.md
  docs/manage/security/2-step-verification-admins.md
  docs/manage/security/2-step-verification-users.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/observability/aws/about.md
  docs/observability/aws/integrations/aws-api-gateway.md
  sidebars.ts
Labels: cla-signed

#1580 Docusaurus upgrade to version 2.3.1
  package.json
  yarn.lock
Labels: cla-signed

#1586 Update explore-view.md
  docs/dashboards-new/explore-view.md
Labels: cla-signed

#1585 added newapp
  docs/integrations/saas-cloud/microsoft-exchange-tracelogs.md
  static/img/integrations/saas-cloud/microsoft-exchange-trace-logs-message-monitoring.png
  static/img/integrations/saas-cloud/microsoft-exchange-trace-logs-overview.png
Labels: cla-signed

#1588 2023-02-08 Content Release
  blog-cse/2023-01-20-content.md
  blog-cse/2023-02-08-content.md
Labels: cla-signed

#1587 More 404 fixes
  cid-redirects.json
  docs/contributing/glossary.md
  docs/get-started/index.md
  docs/manage/security/audit-index-access.md
  docs/manage/users-roles/roles/role-capabilities.md
Labels: cla-signed

#1590 addedtosidebars.ts
  sidebars.ts
  static/img/integrations/saas-cloud/google_workspace_admin_sdk.png
  static/img/integrations/saas-cloud/google_workspace_credentials.png
  static/img/integrations/saas-cloud/google_workspace_service_account.png
Labels: cla-signed, hot🔥

#1559 added cid
  cid-redirects.json
Labels: cla-signed

#1592 added-app
  docs/integrations/saas-cloud/armis.md
  docs/integrations/saas-cloud/microsoft-exchange-tracelogs.md
  sidebars.ts
  static/img/integrations/saas-cloud/Armis-Alerts-Overview.png
  static/img/integrations/saas-cloud/Armis-Device-Overview.png
  static/img/integrations/saas-cloud/armis-icon.png
Labels: cla-signed, hot🔥

#1414 deployment.environment RUM value
  docs/apm/real-user-monitoring/configure-data-collection.md
  docs/apm/real-user-monitoring/dashboards.md
  static/img/rum/RUM-Overview-Application-Service.png
  static/img/rum/RUM-Overview.png
  static/img/rum/RUM-Performance-Analytics-Application.png
  static/img/rum/RUM-TopN-Application.png
  static/img/rum/RUM_Overview.png
  static/img/rum/explore-view-rum.png
Labels: cla-signed, do-not-merge

#1576 armiscid
  cid-redirects.json
Labels: cla-signed, hot🔥

#1584 updates to SUMO-208827
  docs/api/search-job.md
Labels: cla-signed

#1594 fixed
  cid-redirects.json
  docs/integrations/saas-cloud/microsoft-exchange-tracelogs.md
  sidebars.ts
Labels: cla-signed, hot🔥

#1577 Misc fixes
  docs/get-started/onboarding.md
  docs/send-data/installed-collectors/macos.md
Labels: cla-signed

#1595 algolia test
  docs/alerts/index.md
  docs/alerts/monitors/index.md
  docs/api/access-keys.md
  docs/api/account-management.md
  docs/api/archive-ingestion.md
  docs/api/aws-region-by-deployment.md
  docs/api/collectors.md
  docs/api/content-management.md
  docs/api/content-permissions.md
  docs/api/cse.md
  docs/api/dashboard-new.md
  docs/api/data-forwarding.md
  docs/api/dynamic-parsing.md
  docs/api/field-extraction-rules.md
  docs/api/fields.md
  docs/api/folders.md
  docs/api/health-events.md
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/api/lookup-tables.md
  docs/api/metrics-query.md
  docs/api/metrics.md
  docs/api/monitors.md
  docs/api/partitions.md
  docs/api/password-policy.md
  docs/api/policies.md
  docs/api/roles.md
  docs/api/saml-configuration.md
  docs/api/scheduled-views.md
  docs/api/search-job.md
  docs/api/service-allowlist.md
  docs/api/tokens.md
  docs/api/tracing.md
  docs/api/users.md
  docs/integrations/index.md
  docs/metrics/index.md
  docs/metrics/metrics-queries/query-comments.md
Labels: cla-signed

#1596 Metrics query release notes
  blog-service/2023-02-13-metrics-query.md
Labels: cla-signed

#1593 release notes: deployment env RUM
  blog-service/2023-02-13-rum.md
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/real-user-monitoring/metrics.md
Labels: cla-signed, hot🔥

#1600 Update generate-cse-signals.md
  docs/alerts/scheduled-searches/generate-cse-signals.md
Labels: cla-signed

#1599 update wildcard behavior for where operator
  docs/search/search-query-language/search-operators/where.md
Labels: cla-signed

#1601 Broken note and other DB fixes
  docs/integrations/databases/index.md
  docs/integrations/databases/redis.md
  docs/integrations/google/workspace/collect-logs.md
Labels: cla-signed

#1603 Dark mode
  docs/contributing/glossary.md
  docs/dashboards-new/about.md
Labels: cla-signed

#1602 More 404 fixes
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/api/tokens.md
  docs/contributing/glossary.md
  docs/cse/ingestion/carbon-black.md
  docs/get-started/index.md
  docs/integrations/amazon-aws/elastic-container-service-container-insights-cloudwatch.md
  docs/integrations/amazon-aws/inspector.md
  docs/integrations/amazon-aws/network-firewall.md
  docs/integrations/amazon-aws/redshift-ulm.md
  docs/integrations/amazon-aws/security-hub.md
  docs/integrations/amazon-aws/vpc-flow-logs.md
  docs/integrations/amazon-aws/waf.md
  docs/integrations/cloud-security-monitoring-analytics/amazon-vpc-flow.md
  docs/integrations/containers-orchestration/vmware.md
  docs/integrations/databases/oracle/collect-logs-metrics.md
  docs/integrations/microsoft-azure/active-directory-legacy.md
  docs/integrations/saas-cloud/cloudflare.md
  docs/integrations/saas-cloud/microsoft-exchange-trace-logs.md
  docs/integrations/security-threat-detection/carbon-black-cloud.md
  docs/integrations/security-threat-detection/imperva-incapsula.md
  docs/integrations/security-threat-detection/vmware-carbon-black.md
  docs/manage/security/audit-index-access.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/metrics/introduction/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-trace-logs.md
  sidebars.ts
  sumologic-api.yaml
Labels: cla-signed

#1604 CSE application release notes for 2023-02-13
  blog-cse/2023-02-13-application-update.md
  static/img/release-notes/cse/Active-Entities-Panel-CSE-HUD.png
Labels: cla-signed

#1605 Couchbase logo fix
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/index.md
  static/img/integrations/databases/Couchbase.png
  static/img/integrations/databases/couchbase-logo.png
Labels: cla-signed

#1606 Security patch - cacheable-request
  package.json
  yarn.lock
Labels: cla-signed

#1598 Update configure-data-collection.md
  docs/apm/real-user-monitoring/configure-data-collection.md
Labels: cla-signed

#1608 Misc broken items found during Algolia setup
  docs/integrations/containers-orchestration/kafka.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/search/get-started-with-search/search-page/index.md
  docs/search/get-started-with-search/search-page/modify-search-from-messages-tab.md
Labels: cla-signed

#1609 More 404 fixes
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/api/collectors.md
  docs/api/data-forwarding.md
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/api/metrics-query.md
  docs/api/metrics.md
  docs/api/scheduled-views.md
  docs/api/search-job.md
  docs/contributing/glossary.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/get-started/faq.md
  docs/integrations/account-plans.md
  docs/integrations/amazon-aws/cost-explorer.md
  docs/integrations/amazon-aws/elastic-container-service-container-insights-cloudwatch.md
  docs/integrations/amazon-aws/sqs.md
  docs/integrations/app-development/puppet.md
  docs/integrations/cloud-security-monitoring-analytics/windows.md
  docs/integrations/containers-orchestration/docker-community-edition.md
  docs/integrations/containers-orchestration/docker-ulm.md
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/containers-orchestration/vmware-legacy.md
  docs/integrations/containers-orchestration/vmware.md
  docs/integrations/databases/mariadb.md
  docs/integrations/global-intelligence/nginx.md
  docs/integrations/microsoft-azure/active-directory-json.md
  docs/integrations/microsoft-azure/active-directory-legacy.md
  docs/integrations/microsoft-azure/iis-10-legacy.md
  docs/integrations/microsoft-azure/iis-7.md
  docs/integrations/microsoft-azure/windows-json-pci-compliance.md
  docs/integrations/microsoft-azure/windows-json.md
  docs/integrations/microsoft-azure/windows-legacy-pci-compliance.md
  docs/integrations/microsoft-azure/windows-legacy.md
  docs/integrations/pci-compliance/linux.md
  docs/integrations/saas-cloud/salesforce.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/manage/security/audit-event-index.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/metrics/metrics-queries/query-comments.md
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
  docs/observability/aws/integrations/aws-api-gateway.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-collector-script.md
  docs/send-data/collect-from-other-data-sources/sumo-logic-open-source-projects.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
  docs/send-data/installed-collectors/collector-installation-reference/add-collector-linux-machine-image.md
Labels: cla-signed

#1612 Adding FAQ for scheduled search limit
  docs/alerts/scheduled-searches/faq.md
Labels: cla-signed

#1618 Update normalized-threat-rules.md
  docs/cse/rules/normalized-threat-rules.md
Labels: cla-signed

#1607 Update certification-faq.md
  docs/get-started/certification-faq.md
Labels: cla-signed

#1610 More 404 fixes
  blog-collector/2018/12-31.md
  cid-redirects.json
  docs/integrations/microsoft-azure/iis-10-legacy.md
Labels: cla-signed

#1619 Fix on Training doc
  docs/get-started/certification-faq.md
Labels: cla-signed

#1525 Update application-load-balancer.md
  docs/integrations/amazon-aws/application-load-balancer.md
Labels: cla-signed

#1620 Update .clabot
  .clabot
Labels: cla-signed

#1622 More 404 fixes
  cid-redirects.json
  docs/integrations/amazon-aws/elastic-load-balancing.md
Labels: cla-signed

#1625 Remove Feature Requests
  docs/manage/users-roles/users/secure-third-party-service-access.md
Labels: cla-signed

#1627 Update cloud-flex-credits-accounts.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
Labels: cla-signed, hot🔥

#1630 Getting started hub page
  docs/get-started/account-setup.md
  docs/get-started/apps-integrations.md
  docs/get-started/certification-faq.md
  docs/get-started/help.md
  docs/get-started/index.md
  docs/get-started/keyboard-shortcuts.md
  docs/get-started/library.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/overview.md
  docs/get-started/sign-up.md
  docs/get-started/system-requirements.md
  sidebars.ts
Labels: cla-signed

#1631 tags for algolia
  docs/alerts/index.md
  docs/alerts/monitors/index.md
  docs/apm/real-user-monitoring/index.md
  docs/apm/traces/index.md
  docs/cse/index.md
  docs/dashboards-new/index.md
  docs/get-started/index.md
  docs/get-started/onboarding.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/index.md
  docs/manage/security/index.md
  docs/observability/index.md
  docs/observability/reliability-management-slo/index.md
  docs/search/index.md
  docs/send-data/hosted-collectors/index.md
  docs/send-data/index.md
  docs/send-data/installed-collectors/linux.md
Labels: cla-signed

#1632 Create 2023-02-17-content.md
  blog-cse/2023-02-17-content.md
Labels: cla-signed

#1634 Fix API link - Citrix
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
Labels: cla-signed

#1614 Update data-enrichment.md
  docs/send-data/data-enrichment.md
Labels: cla-signed

#1636 More 404 fixes
  cid-redirects.json
  docs/send-data/data-enrichment.md
  docs/send-data/installed-collectors/macos.md
Labels: cla-signed

#1637 aws fixes
  docs/integrations/amazon-aws/sqs.md
  docs/observability/aws/about.md
Labels: cla-signed

#1567 Lookup tables - SLO
  docs/observability/reliability-management-slo/create-slo.md
  static/img/observability/add-to-dashboard.png
  static/img/observability/percent-error-remain.png
Labels: cla-signed, do-not-merge

#1638 Lookup SLO table rn
  blog-service/2023-02-17-reliability-management-slo.md
Labels: cla-signed

#1639 Get started
  docs/get-started/account-setup.md
  docs/get-started/apps-integrations.md
  docs/get-started/index.md
  docs/get-started/keyboard-shortcuts.md
  docs/get-started/onboarding.md
  docs/get-started/overview.md
  docs/get-started/sign-up.md
  src/css/sumo.scss
Labels: cla-signed

#1640 CSS and hub page cards
  docs/alerts/index.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/index.md
  docs/cloud-soar/main-menu.md
  docs/cloud-soar/overview.md
  docs/metrics/index.md
  sidebars.ts
  src/css/sumo.scss
Labels: cla-signed

#1583 changes-monitorsdoc
  blog-service/2023-02-06-metrics-monitors.md
  docs/alerts/monitors/create-monitor.md
Labels: doc:update, cla-signed, do-not-merge

#1641 More Hub Pages
  docs/cse/index.md
  docs/search/get-started-with-search/index.md
  docs/search/index.md
  docs/search/subqueries.md
Labels: cla-signed

#1642 Get started and hub page CSS
  docs/get-started/account-setup.md
  docs/get-started/apps-integrations.md
  docs/get-started/faq.md
  docs/get-started/help.md
  docs/get-started/index.md
  docs/get-started/library.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/onboarding.md
  docs/get-started/training-certification-faq.md
  docs/manage/content-sharing/changing-alerts.md
  docs/search/lookup-tables/create-lookup-table.md
  docusaurus.config.js
  package.json
  src/pages/index.tsx
  static/img/get-started/WTS_Home-Search-icons.png
  static/img/get-started/library/App-Catalog.png
  static/img/reuse/library-icon.png
  static/img/search/lookup-tables/library-icon.png
  yarn.lock
Labels: cla-signed

#1644 Brought back navbar Material Icons
  docusaurus.config.js
Labels: cla-signed

#1643 Hub page edits and CSS
  docs/apm/apm.md
  docs/get-started/quickstart.md
  docs/integrations/databases/index.md
  docs/integrations/index.md
  docs/integrations/saml/index.md
  docs/observability/index.md
  docs/observability/kubernetes/index.md
  docs/search/behavior-insights/index.md
  docs/search/get-started-with-search/index.md
  docs/search/get-started-with-search/suggested-searches/index.md
  docs/search/search-cheat-sheets/index.md
  docs/search/search-query-language/index.md
  docs/send-data/hosted-collectors/configure-hosted-collector.md
  docs/send-data/index.md
  sidebars.ts
  static/img/integrations/saml/okta.png
Labels: cla-signed

#1524 Update ec2-cloudwatch-metrics.md
  docs/integrations/amazon-aws/ec2-cloudwatch-metrics.md
Labels: cla-signed

#1647 Resize navbar logo and free trial button
  src/css/sumo.scss
Labels: cla-signed

#1646 Added and updated Micro Lessons
  docs/alerts/monitors/alert-response.md
  docs/apm/real-user-monitoring/configure-data-collection.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-aws-environments.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-kubernetes-environments.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-other-environments.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/incidents-triage.md
  docs/contributing/templates/partner-app.md
  docs/dashboards-new/share-dashboard-new.md
  docs/integrations/web-servers/nginx.md
  docs/manage/partitions-data-tiers/searching-data-tiers.md
  docs/manage/security/access-keys.md
  docs/observability/about.md
  docs/observability/aws/deploy-use-aws-observability/index.md
  docs/observability/kubernetes/index.md
  docs/observability/reliability-management-slo/index.md
  docs/search/get-started-with-search/search-basics/about-search-basics.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source.md
Labels: cla-signed

#1645 Nav guides
  docs/get-started/account-setup.md
  docs/get-started/apps-integrations.md
  docs/get-started/keyboard-shortcuts.md
  docs/get-started/library.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/onboarding.md
  docs/get-started/overview.md
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  docs/get-started/sumo-logic-ui.md
  docs/search/search-cheat-sheets/general-search-examples.md
  docs/search/search-cheat-sheets/log-operators.md
  docusaurus.config.js
  sidebars.ts
  src/css/sumo.scss
Labels: cla-signed

#1648 Navbar dropdown edits for Algolia
  docusaurus.config.js
  sidebars.ts
Labels: cla-signed

#1649 More icons
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/edit-settings.md
  docs/cloud-soar/architecture.md
  docs/cloud-soar/index.md
  docs/cse/index.md
  docs/cse/schema/index.md
  docs/dashboards-new/index.md
  docs/dashboards/index.md
  docs/get-started/support-terms.md
  docs/observability/index.md
  docs/observability/kubernetes/about.md
  docs/search/index.md
  docs/search/optimize-search-performance.md
  docs/search/search-query-language/index.md
  sidebars.ts
Labels: cla-signed

#1650 Nav guides
  docs/metrics/index.md
  docs/metrics/metrics-queries/funnel-chart.md
  docs/metrics/metrics-queries/heat-map.md
  docusaurus.config.js
  sidebars.ts
Labels: cla-signed

#1651 More Get Started improvements
  blog-service/2016/12-31.md
  cid-redirects.json
  docs/dashboards/about.md
  docs/get-started/account-settings-preferences.md
  docs/get-started/account-setup.md
  docs/get-started/apps-integrations.md
  docs/get-started/index.md
  docs/get-started/keyboard-shortcuts.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/onboarding.md
  docs/get-started/sign-up.md
  docs/get-started/sumo-logic-ui.md
  docs/manage/security/access-keys.md
  docs/manage/users-roles/users/change-users-email-address.md
  docs/manage/users-roles/users/reset-user-password.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/search/get-started-with-search/build-search/set-time-range.md
  docs/search/get-started-with-search/search-basics/search-autocomplete.md
  docs/search/get-started-with-search/search-basics/time-range-expressions.md
  docs/search/search-query-language/parse-operators/parsedate.md
  sidebars.ts
  static/img/get-started/change-email.png
  static/img/get-started/change-password.png
  static/img/get-started/change-password2.png
  static/img/get-started/check-role.png
Labels: cla-signed

#1652 Onboarding fixes and improvements
  docs/api/access-keys.md
  docs/api/account-management.md
  docs/api/password-policy.md
  docs/api/policies.md
  docs/api/saml-configuration.md
  docs/api/service-allowlist.md
  docs/cloud-soar/index.md
  docs/cse/index.md
  docs/dashboards-new/about.md
  docs/dashboards-new/drill-down-to-discover-root-causes.md
  docs/dashboards-new/explore-view.md
  docs/dashboards-new/export-dashboard-new.md
  docs/dashboards-new/link-dashboards.md
  docs/dashboards-new/migrate-new-dashboards.md
  docs/get-started/index.md
  docs/get-started/system-requirements.md
  docs/get-started/training-certification-faq.md
  docs/manage/manage-subscription/manage-org-settings.md
  docs/observability/root-cause-explorer.md
  docs/observability/work-from-home-vpn.md
  docs/search/live-tail/index.md
  docusaurus.config.js
  sidebars.ts
  static/img/dashboards-new/about-dashboard-new/dashboards-new.png
  static/img/dashboards-new/explore/explore.png
  static/img/observability/rootcause.png
  static/img/search/livetail/livetail.png
Labels: cla-signed

#1656 New branch (knowbe4)
  cid-redirects.json
  docs/cse/rules/write-first-seen-rule.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
  static/img/send-data/knowbe4-config-main.png
  static/img/send-data/knowbe4-icon.png
Labels: cla-signed

#1657 renamed title
  cid-redirects.json
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/manage/field-extractions/field-extraction-rule-templates/akamai-cloud-monitor.md
  docs/manage/field-extractions/field-extraction-rule-templates/apache-access-logs.md
  docs/manage/field-extractions/field-extraction-rule-templates/apache-tomcat-access-log-fer.md
  docs/manage/field-extractions/field-extraction-rule-templates/apache-tomcat-access-logs.md
  docs/manage/field-extractions/field-extraction-rule-templates/aws-cloudtrail-logs.md
  docs/manage/field-extractions/field-extraction-rule-templates/aws-elastic-load-balancing-logs.md
  docs/manage/field-extractions/field-extraction-rule-templates/aws-s3-usage-logs.md
  docs/manage/field-extractions/field-extraction-rule-templates/cisco-app.md
  docs/manage/field-extractions/field-extraction-rule-templates/cisco-fwsm-fer.md
  docs/manage/field-extractions/field-extraction-rule-templates/index.md
  docs/manage/field-extractions/field-extraction-rule-templates/microsoft-iis-logs.md
  docs/manage/field-extractions/field-extraction-rule-templates/nginx-logs.md
  docs/manage/field-extractions/field-extraction-rule-templates/palo-alto-networks.md
  docs/manage/field-extractions/field-extraction-rule-templates/varnish-logs.md
  sidebars.ts
Labels: cla-signed

#1661 Revert "renamed title"
  cid-redirects.json
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/manage/field-extractions/fer-templates/akamai-cloud-monitor.md
  docs/manage/field-extractions/fer-templates/apache-access-logs.md
  docs/manage/field-extractions/fer-templates/apache-tomcat-access-log-fer.md
  docs/manage/field-extractions/fer-templates/apache-tomcat-access-logs.md
  docs/manage/field-extractions/fer-templates/aws-cloudtrail-logs.md
  docs/manage/field-extractions/fer-templates/aws-elastic-load-balancing-logs.md
  docs/manage/field-extractions/fer-templates/aws-s3-usage-logs.md
  docs/manage/field-extractions/fer-templates/cisco-app.md
  docs/manage/field-extractions/fer-templates/cisco-fwsm-fer.md
  docs/manage/field-extractions/fer-templates/index.md
  docs/manage/field-extractions/fer-templates/microsoft-iis-logs.md
  docs/manage/field-extractions/fer-templates/nginx-logs.md
  docs/manage/field-extractions/fer-templates/palo-alto-networks.md
  docs/manage/field-extractions/fer-templates/varnish-logs.md
  sidebars.ts
Labels: cla-signed

#1662 Update .clabot
  .clabot
Labels: cla-signed

#1653 More nav edits for search opt
  docs/integrations/amazon-aws/index.md
  docs/observability/reliability-management-slo/create-slo.md
Labels: cla-signed

#1663 Update local-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/local-windows-event-log-source.md
Labels: cla-signed

#1660 Update index.md
  docs/search/logreduce/index.md
Labels: cla-signed

#1664 Restore First Seen Rule beta
  cid-redirects.json
  docs/cse/rules/write-first-seen-rule.md
Labels: cla-signed

#1666 Remove 'Preview Apps' - deprecated
  docs/get-started/apps-integrations.md
Labels: cla-signed

#1613 Knowbe4api update
  docs/reuse/restart-c2c-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed, do-not-merge

#1667 Clarify behavior for custom columns with multiple attributes
  docs/cse/match-lists-suppressed-lists/custom-match-list-columns.md
Labels: cla-signed

#1669 Minor update for First Seen Rule
  docs/cse/rules/write-first-seen-rule.md
  static/img/cse/first-seen-rule.jpg
  static/img/cse/first-seen-rule.png
Labels: cla-signed

#1668 Remove redocusaurus and comments
  docusaurus.config.js
  package.json
  yarn.lock
Labels: cla-signed

#1670 More 404s
  cid-redirects.json
  docs/integrations/saas-cloud/box.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
Labels: cla-signed

#1673 Update .clabot
  .clabot
Labels: cla-signed

#1675 More 404s!
  blog-collector/2019/12-31.md
  cid-redirects.json
  docs/apm/traces/index.md
  docs/cse/administration/inventory-sources-and-data.md
  docs/dashboards/get-started/set-data-access-level-dashboard.md
  docs/get-started/account-settings-preferences.md
  docs/integrations/microsoft-azure/office-365.md
  docs/search/get-started-with-search/search-basics/search-surrounding-messages.md
  docs/search/get-started-with-search/search-basics/time-range-expressions.md
  docs/search/get-started-with-search/search-basics/view-traces-search-results.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
Labels: cla-signed

#1676 Fixes for algolia nav/ index
  docs/integrations/amazon-aws/network-load-balancer.md
  docs/integrations/amazon-aws/rds.md
  docs/metrics/index.md
  docs/metrics/introduction/index.md
  docs/metrics/metric-charts/create-metrics-visualization.md
  docs/metrics/metric-charts/line-area-metric-charts.md
  docs/metrics/metric-charts/metrics-outliers.md
  docs/metrics/metric-rules-editor.md
  docs/metrics/metrics-transformation-rules.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/send-data/data-enrichment.md
  sidebars.ts
Labels: cla-signed

#1678 renamingtitle
  docs/manage/field-extractions/fer-templates/index.md
Labels: cla-signed

#1679 Revert "renamingtitle"
  docs/manage/field-extractions/fer-templates/index.md
Labels: cla-signed

#1680 Traces improvements
  docs/apm/apm.md
  docs/apm/index.md
  docs/apm/real-user-monitoring/configure-data-collection.md
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/traces/advanced-configuration/filter-shape-tracing-data.md
  docs/apm/traces/advanced-configuration/index.md
  docs/apm/traces/get-started-transaction-tracing/index.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-kubernetes-environments.md
  docs/apm/traces/index.md
  docs/apm/traces/quickstart.md
  docs/apm/traces/search-query-language-support-for-traces.md
  docs/apm/traces/spans.md
  docs/apm/traces/tracing-dashboards.md
  docs/apm/traces/view-and-investigate-traces.md
  docs/integrations/saas-cloud/istio.md
  docs/manage/connections-integrations/index.md
  docs/manage/index.md
  docs/manage/manage.md
  sidebars.ts
  static/img/integrations/saas-cloud/istio.png
Labels: cla-signed

#1686 Fix for broken table
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
Labels: cla-signed

#1690 Add note about circuit breakers for First Seen Rules
  docs/cse/rules/write-first-seen-rule.md
Labels: cla-signed

#1694 Hubs and formatting - Search, Send Data, CSE. Fixed incorrect regex in parse operators.
  docs/cse/administration/create-cse-actions.md
  docs/cse/administration/create-use-network-blocks.md
  docs/cse/administration/cse-apis.md
  docs/cse/ingestion/zscaler-private-access.md
  docs/manage/field-extractions/fer-templates/index.md
  docs/metrics/metrics-transformation-rules.md
  docs/search/search-query-language/field-expressions.md
  docs/search/search-query-language/parse-operators/index.md
  docs/search/search-query-language/parse-operators/parse-delimited-logs-using-split.md
  docs/search/search-query-language/parse-operators/parse-field-option.md
  docs/search/search-query-language/parse-operators/parse-json-formatted-logs.md
  docs/search/search-query-language/parse-operators/parse-keyvalue-formatted-logs.md
  docs/search/search-query-language/parse-operators/parse-predictable-patterns-using-an-anchor.md
  docs/search/search-query-language/parse-operators/parse-variable-patterns-using-regex.md
  docs/search/search-query-language/parse-operators/parse-xml-formatted-logs.md
  docs/search/search-query-language/parse-operators/parsedate.md
  docs/search/search-query-language/search-operators/where.md
  docs/send-data/choose-collector-source.md
  docs/send-data/installed-collectors/index.md
  docs/send-data/reference-information/use-wildcards-paths.md
  sidebars.ts
Labels: cla-signed

#1695 algolia rank test
  docs/apm/traces/index.md
  docs/metrics/index.md
  docs/observability/index.md
  docs/search/index.md
  sidebars.ts
Labels: cla-signed

#1698 Clarify that AWS GovCloud ARNs are also supported
  docs/cse/schema/username-and-hostname-normalization.md
Labels: cla-signed

#1697 Update create-slo.md
  docs/observability/reliability-management-slo/create-slo.md
Labels: cla-signed

#1699 Update cse-built-in-rules.md
  docs/cse/rules/cse-built-in-rules.md
Labels: cla-signed

#1684 View/Investigate Traces
  docs/apm/index.md
  docs/apm/traces/index.md
  docs/apm/traces/spans.md
  docs/apm/traces/tracing-dashboards.md
  docs/apm/traces/view-and-investigate-traces.md
  docs/search/search-query-language/index.md
  sidebars.ts
  static/img/dashboards-new/drill-root-causes/entities-tab.png
  static/img/dashboards-new/drill-root-causes/entities-time-selector.png
  static/img/dashboards-new/drill-root-causes/infrastructure-tab-with-RCE-link.png
  static/img/traces/Logs-links.png
  static/img/traces/critical-path-on-trace-view.png
  static/img/traces/service-color-traces-span.png
  static/img/traces/span-event-more2.png
  static/img/traces/toggle-and-button-hide.png
  static/img/traces/trace-details-metadata.png
  static/img/traces/trace-hover.png
  static/img/traces/trace-page.png
  static/img/traces/trace-view-details.png
  static/img/traces/trace-view-details2.png
  static/img/traces/trace-view.png
  static/img/traces/trace-zooms.png
  static/img/traces/traces-table-row.png
Labels: cla-signed, do-not-merge

#1685 Update information about kubernetes metrics
  docs/metrics/kubernetes-metrics.md
Labels: cla-signed

#1703 updated-c2c
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
  static/img/send-data/cyberark-icon.png
  static/img/send-data/cyberark-source.png
  static/img/send-data/login-cyberark.png
Labels: cla-signed, hot🔥

#1705 release notes
  blog-service/2023-02-24-improved-query-editor.md
Labels: cla-signed

#1693 Update this page to include links and FAQ
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#1711 Fix bullet - cloud flex
  docs/manage/manage-subscription/upgrade-cloud-flex-account.md
Labels: cla-signed

#1707 Add Community Ecosystem apps to sidebar
  sidebars.ts
Labels: cla-signed

#1712 fix regex
  docs/search/search-query-language/parse-operators/parse-variable-patterns-using-regex.md
Labels: cla-signed

#1700 More 404s
  cid-redirects.json
Labels: cla-signed

#1708 Update migrate-new-dashboards.md
  docs/dashboards-new/migrate-new-dashboards.md
Labels: cla-signed

#1704 Update configure-alerts.md
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
Labels: cla-signed

#1714 Hubs, Material icons
  docs/alerts/index.md
  docs/apm/traces/index.md
  docs/apm/traces/services-list-map.md
  docs/manage/fields.md
  docs/metrics/index.md
  docs/sdo/index.md
  docs/search/index.md
  docs/send-data/index.md
  docusaurus.config.js
  static/img/metrics/metrics.png
  static/img/search/get-started-search/search-basics/logsearch.png
  static/img/search/livetail/livetail.png
  static/img/traces/servicemap.png
  static/img/traces/traces.png
Labels: cla-signed

#1716 CSE Insight server
  docs/cse/integrations/insight-enrichment-server.md
Labels: cla-signed

#1683 Update google-g-suite-apps-audit.md
  docs/cse/ingestion/google-g-suite-apps-audit.md
Labels: cla-signed

#1682 Update g-suite-apps-audit-source.md
  docs/send-data/hosted-collectors/google-source/g-suite-apps-audit-source.md
Labels: cla-signed

#1713 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#1526 Update sns.md
  docs/integrations/amazon-aws/sns.md
Labels: cla-signed

#1717 404s
  blog-collector/2022-10-12-welcome.md
  blog-cse/2022-04-30-archive.md
  blog-service/2019/12-31.md
  blog-service/2020/12-31.md
  blog-service/2021/12-31.md
  cid-redirects.json
Labels: cla-signed

#1719 Fixing more legacy links and 404s
  docs/contributing/glossary.md
Labels: cla-signed

#1721 help / get started
  docs/get-started/help.md
  docs/get-started/onboarding.md
Labels: cla-signed

#1722 Formatting - API Docs and Send Data > Other Sources
  blog-service/2019/12-31.md
  blog-service/2020/12-31.md
  cid-redirects.json
  docs/api/collector-management/collector-api-methods-examples.md
  docs/api/collector-management/source-api.md
  docs/api/dashboard-data.md
  docs/api/getting-started.md
  docs/api/ingest-budget-v2.md
  docs/api/metrics.md
  docs/api/search-job.md
  docs/api/troubleshooting.md
  docs/reuse/api-endpoints.md
  docs/reuse/api-errors.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-amazon-kinesis.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-collector-script.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-lambda-function.md
  docs/send-data/collect-from-other-data-sources/amazon-msk-prometheus-metrics-collection.md
  docs/send-data/collect-from-other-data-sources/autosubscribe-arn-destination.md
  docs/send-data/collect-from-other-data-sources/aws-fargate-log-collection.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/index.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/troubleshoot-azure-blob-storage-log-collection.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/collect-logs-azure-monitor.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/collect-metrics-azure-monitor.md
  docs/send-data/collect-from-other-data-sources/collect-aws-lambda-logs-extension.md
  docs/send-data/collect-from-other-data-sources/collect-logs-aws-fargate.md
  docs/send-data/collect-from-other-data-sources/collect-logs-heroku.md
  docs/send-data/collect-from-other-data-sources/collect-logs-oracle-cloud-infrastructure.md
  docs/send-data/collect-from-other-data-sources/collect-logs-palo-alto-networks-cortex.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/collect-custom-jmx-metrics-jolokia.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/configure-telegraf-output-plugin.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/index.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/install-telegraf.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-vrealize-operations-manager.md
  docs/send-data/collect-from-other-data-sources/collect-prometheus-metrics.md
  docs/send-data/collect-from-other-data-sources/collect-ruby-on-rails-logs.md
  docs/send-data/collect-from-other-data-sources/collect-statsd-metrics.md
  docs/send-data/collect-from-other-data-sources/collect-vmware-vrealize/index.md
  docs/send-data/collect-from-other-data-sources/create-amazon-lambda-function.md
  docs/send-data/collect-from-other-data-sources/deploy-collectors-aws-opsworks.md
  docs/send-data/collect-from-other-data-sources/docker-collection-methods.md
  docs/send-data/collect-from-other-data-sources/import-raw-data-splunk.md
  docs/send-data/collect-from-other-data-sources/kubernetes-fluentd-plugin.md
  docs/send-data/collect-from-other-data-sources/kubernetes.md
  docs/send-data/collect-from-other-data-sources/performance-impact-failover-handling.md
  docs/send-data/collect-from-other-data-sources/vmware-airwatch-integration.md
  docs/send-data/collect-from-other-data-sources/vmware-vrealize-log-insight.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
  docs/send-data/use-json-configure-sources/index.md
  docs/send-data/use-json-configure-sources/json-parameters-hosted-sources.md
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/existing-collectors-and-sources.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/new-collectors-and-sources.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/view-download-source-json-configuration.md
  sidebars.ts
Labels: cla-signed

#1723 Fix legacy links causing 404s
  blog-service/2018/12-31.md
  blog-service/2020/12-31.md
  blog-service/2021/12-31.md
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/integrations/amazon-aws/eks-control-plane.md
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/containers-orchestration/activemq.md
  docs/integrations/containers-orchestration/kubernetes-control-plane.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/elasticsearch.md
  docs/integrations/databases/mariadb.md
  docs/integrations/databases/memcached.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/oracle/collect-logs-metrics.md
  docs/integrations/databases/postgresql.md
  docs/integrations/databases/redis.md
  docs/integrations/google/kubernetes-engine.md
  docs/integrations/hosts-operating-systems/host-process-metrics.md
  docs/integrations/microsoft-azure/kubernetes.md
  docs/integrations/microsoft-azure/sql-server.md
  docs/integrations/security-threat-detection/netskope-legacy-collection.md
  docs/integrations/security-threat-detection/netskope.md
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx.md
  docs/integrations/web-servers/squid-proxy.md
Labels: cla-signed

#1724 Amazon ECS EW links and formatting
  docs/integrations/amazon-aws/elastic-container-service-container-insights-cloudwatch.md
  docs/integrations/amazon-aws/sqs.md
  docs/search/live-tail/live-tail-cli.md
  static/img/integrations/amazon-aws/ecs1.png
  static/img/integrations/amazon-aws/ecs2.png
  static/img/integrations/amazon-aws/ecs3.png
  static/img/integrations/amazon-aws/ecs4.png
  static/img/integrations/amazon-aws/ecs5.png
Labels: cla-signed

#1726 Formatting, cleanup
  docs/search/get-started-with-search/build-search/index.md
  docs/search/get-started-with-search/build-search/set-time-range.md
  docs/search/get-started-with-search/index.md
  docs/search/live-tail/live-tail-cli.md
  docs/search/live-tail/troubleshooting-live-tail.md
  docs/search/logcompare.md
  docs/search/logreduce/logreduce-operator.md
  docs/search/subqueries.md
  docs/send-data/reference-information/collect-multiline-logs.md
  docs/send-data/reference-information/metadata-naming-conventions.md
  docs/send-data/reference-information/time-reference.md
Labels: cla-signed

#1727 App dev hub
  docs/integrations/app-development/index.md
  static/img/integrations/app-development/appdev.png
Labels: cla-signed
