Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-04, with the labels that each got.

#1937 Group or Aggregate Operators index page
  docs/search/search-query-language/group-aggregate-operators/index.md
Labels: cla-signed

#1970 S3M Doc updates
  docs/send-data/choose-collector-source.md
  docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-metrics.md
  docs/send-data/opentelemetry-collector/data-source-configurations/index.md
  docs/send-data/opentelemetry-collector/install-collector-linux.md
  docs/send-data/opentelemetry-collector/install-collector-macos.md
  docs/send-data/opentelemetry-collector/install-collector-windows.md
  docs/send-data/opentelemetry-collector/sumo-logic-opentelemetry-vs-opentelemetry-upstream-relationship.md
  docs/send-data/opentelemetry-collector/troubleshooting-faq.md
  docs/send-data/setup-wizard.md
Labels: cla-signed

#2004 Remove parse mode limitation from monitors docs
  docs/alerts/monitors/index.md
Labels: cla-signed

#1976 CON-1761: Microsoft graph identity protection app
  cid-redirects.json
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
  sidebars.ts
  static/img/integrations/microsoft-azure/microsoft-graph-identity-protection-risk-detections.png
  static/img/integrations/microsoft-azure/microsoft-graph-identity-protection-risky-users.png
Labels: cla-signed

#1974 CON-1803: Deprecate non-C2C methods in Workday app
  docs/integrations/saas-cloud/workday.md
Labels: cla-signed

#2006 docs(lambda): add note about supported images
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: cla-signed

#2005 updated sidelabel for redis doc and title for mongodb atlas
  docs/integrations/databases/mongodb-atlas.md
  docs/integrations/databases/redis.md
Labels: cla-signed

#1994 Update configure-data-collection.md
  docs/apm/real-user-monitoring/configure-data-collection.md
  static/img/rum/RUM-HTTP-Traces-Source-Advanced.png
  static/img/rum/RUM-HTTP-Traces-Source.png
Labels: cla-signed

#2010 MS Graph ID images
  docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
  static/img/integrations/microsoft-azure/microsoft-graph-identity-protection-risk-detections.png
  static/img/integrations/microsoft-azure/microsoft-graph-identity-protection-risky-users.png
Labels: cla-signed

#1948 Search Operators index page
  docs/search/search-query-language/search-operators/index.md
Labels: cla-signed

#2008 More 404 fixes
  cid-redirects.json
  docs/manage/security/search-audit-index.md
Labels: cla-signed

#1996 Monitors index page
  docs/alerts/monitors/index.md
  docs/search/get-started-with-search/search-page/index.md
Labels: cla-signed

#2013 Typo fix
  docs/search/get-started-with-search/build-search/use-receipt-time.md
Labels: cla-signed

#1825 Update query re-writing page, optimize-search-partitions.md (ETA late March)
  docs/search/optimize-search-partitions.md
Labels: cla-signed, do-not-merge

#2011 Sched search 404 fix
  cid-redirects.json
Labels: cla-signed

#2018 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#2012 Changes for sqlserver doc for upgrade to tier 2 app
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
Labels: cla-signed

#2020 TRIDENT-17655 - Minor update for redundant signal suppression section
  docs/cse/records-signals-entities-insights/insight-generation-process.md
Labels: doc:minor edit, cla-signed

#2019 TRIDENT-17658 - Fix issues in entity group article
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
Labels: doc:minor edit, cla-signed

#2023 created_release_notes_for_scheduled_reports
  blog-service/2023-04-05-scheduled-dashboard.md
Labels: cla-signed

#2014 updated URL to latest v2.6.0
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
Labels: cla-signed

#2026 Add list of integrations to CSE Automation Service Beta doc
  docs/cse/integrations/automation-service.md
Labels: cla-signed

#2027 Updated entity group doc
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
Labels: cla-signed

#2028 Update automation-service.md
  docs/cse/integrations/automation-service.md
Labels: cla-signed

#2025 CON-1832 Cisco Meraki Source - New Option
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
  static/img/send-data/cisco-meraki-sumo-source-form.png
Labels: cla-signed

#2034 Fix CSE product name in Automation Service Beta doc
  docs/cse/integrations/automation-service.md
Labels: cla-signed

#2024 created_miro_apps_docs
  cid-redirects.json
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/miro.md
  sidebars.ts
Labels: cla-signed

#966 Amazon SQS / AWSO 2.6.0 (early Apr 2023)
  docs/integrations/amazon-aws/api-gateway/api-gateway-classic.md
  docs/integrations/amazon-aws/api-gateway/api-gateway-s3m.md
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/faq.md
  docs/observability/aws/integrations/amazon-sqs.md
Labels: cla-signed, do-not-merge

#2030 created_scheduled_dashboards_doc
  docs/dashboards-new/scheduled-report.md
  sidebars.ts
  static/img/dashboards-new/scheduled_reports/create_scheduled_report.png
  static/img/dashboards-new/scheduled_reports/delete_scheduled_report.png
  static/img/dashboards-new/scheduled_reports/scheduled_report.png
  static/img/dashboards-new/scheduled_reports/update_scheduled_report.png
Labels: cla-signed, hot🔥

#1997 Adding Lambda Function URL configuration
  docs/alerts/webhook-connections/aws-lambda.md
Labels: cla-signed

#2031 CSE Rules Index
  docs/cse/rules/before-writing-custom-rule.md
  docs/cse/rules/index.md
  sidebars.ts
Labels: cla-signed

#2036 Revert "Amazon SQS / AWSO 2.6.0 (early Apr 2023)"
  docs/integrations/amazon-aws/api-gateway/api-gateway-classic.md
  docs/integrations/amazon-aws/api-gateway/api-gateway-s3m.md
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/faq.md
  docs/observability/aws/integrations/amazon-sqs.md
Labels: cla-signed

#2038 Update .clabot - kburtt
  .clabot
Labels: cla-signed

#2037 Update training-certification-faq.md
  docs/get-started/training-certification-faq.md
Labels: cla-signed

#2022 Scheduled Searches index page.
  docs/alerts/scheduled-searches/index.md
Labels: cla-signed

#2039 Data Lake CID
  cid-redirects.json
Labels: cla-signed

#2047 Add joined mapping
  docs/cse/schema/create-structured-log-mapping.md
  static/img/cse/joined-mapping.png
Labels: doc:update, cla-signed

#2048 Create 2023-04-07-content.md
  blog-cse/2023-04-07-content.md
Labels: cla-signed

#2035 Update search-cse-records-in-sumo.md
  docs/cse/records-signals-entities-insights/search-cse-records-in-sumo.md
Labels: cla-signed

#2021 Log Search: Histogram + Log Levels 📊
  blog-service/2023-04-07-search.md
  docs/beta/aws-private-link.md
  docs/beta/search-log-level.md
  docs/manage/security/audit-index-access.md
  docs/search/get-started-with-search/search-page/change-time-range-in-histogram.md
  sidebars.ts
  static/img/search/get-started-search/search-page/hide-histogram.png
  static/img/search/get-started-search/search-page/log-level-error-filter.png
  static/img/search/get-started-search/search-page/log-level-legend.png
  static/img/search/get-started-search/search-page/log-level-rn.png
Labels: doc:new, cla-signed

#2041 dashboard_images_added
  docs/integrations/saas-cloud/miro.md
Labels: cla-signed, hot🔥

#2043 Build Searches index page.
  docs/search/get-started-with-search/build-search/index.md
Labels: cla-signed

#2044 Collection index page
  docs/send-data/collection/index.md
Labels: cla-signed

#2049 Update elastic-container-service.md
  docs/integrations/amazon-aws/elastic-container-service.md
Labels: cla-signed

#2050 Comment out staging
  .github/workflows/build_and_deploy.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/review.yml
Labels: cla-signed

#2040 Asana c2c docs
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/asana-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  sidebars.ts
  static/img/send-data/add_service_account.png
  static/img/send-data/asana-icon.png
  static/img/send-data/asana_config_main.png
  static/img/send-data/asana_login.png
  static/img/send-data/pat.png
  static/img/send-data/workspace_id.png
Labels: cla-signed, hot🔥

#1902 Consolidate PR checks
  .github/workflows/pr.yml
Labels: doc:site tech, cla-signed

#2051 Traces - Improved Remote Services Detection
  blog-service/2023-04-07-traces.md
Labels: cla-signed

#2016 Tracing ingest audit events
  docs/apm/traces/index.md
  docs/apm/traces/tracing-ingest.md
  docs/manage/security/audit-event-index.md
  sidebars.ts
Labels: doc:new, cla-signed

#2042 Final polish on Lambda Function URL
  docs/alerts/webhook-connections/aws-lambda.md
Labels: cla-signed

#2056 App Catalog hub page
  docs/integrations/app-development/index.md
  docs/integrations/cloud-security-monitoring-analytics/index.md
  docs/integrations/containers-orchestration/index.md
  docs/integrations/databases/index.md
  docs/integrations/global-intelligence/index.md
  docs/integrations/google/index.md
  docs/integrations/hosts-operating-systems/index.md
  docs/integrations/index.md
  docs/integrations/partner-integrations.md
  docs/integrations/pci-compliance/index.md
  docs/integrations/saml/index.md
  docs/integrations/sumo-apps/index.md
  docs/integrations/web-servers/index.md
  static/img/global-intelligence/gis.svg
Labels: cla-signed

#2055 Update collect-multiline-logs.md
  docs/send-data/reference-information/collect-multiline-logs.md
Labels: cla-signed

#2057 Oracle app alignment
  cid-redirects.json
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/oracle.md
  docs/integrations/databases/oracle/alerts.md
  docs/integrations/databases/oracle/collect-logs-metrics.md
  docs/integrations/databases/oracle/index.md
  docs/integrations/databases/oracle/monitors-app-dashboards.md
  docs/integrations/databases/oracle/performance-metrics.md
  sidebars.ts
Labels: cla-signed

#2058 Legacy site 301s
  cid-redirects.json
Labels: cla-signed

#2045 1Password token generation manual updated
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
Labels: cla-signed

#2059 Update transactionize-operator.md
  docs/search/search-query-language/transaction-analytics/transactionize-operator.md
Labels: cla-signed

#2064 Open --> Closed Beta docs
  docs/beta/aws-private-link.md
  docs/beta/infrequent-tier-search.md
  docs/beta/search-log-level.md
  sidebars.ts
Labels: cla-signed

#2061 cato-networks-c2c-docs
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/img/send-data/cato-config-main.png
  static/img/send-data/cato-logo.png
  static/img/send-data/cato-networks-account-id.png
  static/img/send-data/cato-networks-administration.png
  static/img/send-data/cato-networks-enable-events-feed.png
  static/img/send-data/cato-networks-new-api-key.png
Labels: cla-signed

#2069 Added beta
  docs/send-data/collection/restart-collectors.md
  sidebars.ts
Labels: cla-signed

#2071 Dashboard support on Infrequent tier
  docs/beta/infrequent-dashboard-support.md
  static/img/beta/infrequent-dashboard.png
Labels: cla-signed

#2074 Fixed-indexing
  docs/beta/infrequent-dashboard-support.md
Labels: cla-signed

#2075 Infrequent dashboard support
  docs/manage/partitions-data-tiers/infrequent-dashboard-support.md
Labels: cla-signed

#2078 minor formatting
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/docusign-source.md
Labels: cla-signed

#2076 Update workday.md
  docs/integrations/saas-cloud/workday.md
Labels: cla-signed

#2065 Update create-slo.md
  docs/observability/reliability-management-slo/create-slo.md
Labels: cla-signed

#2082 Create 2023-04-13-application-update.md
  blog-cse/2023-04-13-application-update.md
Labels: cla-signed

#2081 TRIDENT-17128 - Remove UEBA app
  docs/integrations/cloud-security-monitoring-analytics/index.md
  sidebars.ts
Labels: doc:update, cla-signed

#2080 TRIDENT-17474 - Add missing CSE attributes
  docs/cse/schema/attributes-map-to-records.md
  docs/cse/schema/schema-attributes.md
Labels: doc:update, cla-signed

#2062 Sources for Installed Collectors index page
  docs/send-data/installed-collectors/sources/index.md
Labels: cla-signed

#2072 Release note: New C2C Sources recap
  blog-service/2023-04-13-sources.md
Labels: cla-signed

#2073 Release note: New SaaS apps recap
  blog-service/2023-04-13-apps.md
Labels: cla-signed

#2083 OTEL = Preferred collector note
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  static/img/get-started/WTS_Collector_page.png
Labels: cla-signed

#1971 OTEL Collector docs edits
  docs/get-started/overview.md
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  docs/send-data/index.md
  docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#2085 OTEL/GS Fixes
  docs/get-started/quickstart.md
Labels: cla-signed

#2053 Update search-log-level.md
  docs/beta/search-log-level.md
Labels: cla-signed

#2092 Small update to tracing ingest
  docs/apm/traces/tracing-ingest.md
Labels: doc:minor edit, cla-signed

#2088 Adding requirement of credits account for tracing data
  docs/send-data/hosted-collectors/http-source/otlp.md
Labels: cla-signed

#2070 CON-1871 Add common error note
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-trace-logs.md
Labels: cla-signed

#2093 Closed Beta docs
  docs/manage/partitions-data-tiers/infrequent-dashboard-support.md
  docs/manage/partitions-data-tiers/infrequent-tier-search.md
  docs/manage/security/audit-index-access.md
  sidebars.ts
Labels: cla-signed

#2094 Instructions for removing docs
  docs/contributing/create-doc.md
  docs/contributing/edit-doc.md
  docs/contributing/index.md
  docs/contributing/remove-doc.md
  docs/contributing/style-guide.md
  sidebars.ts
  static/img/contributing/old-url.png
Labels: cla-signed

#2098 Update .clabot
  .clabot
Labels: cla-signed

#2097 Update db_cluster
  docs/integrations/microsoft-azure/sql-server.md
Labels: cla-signed

#2095 TRIDENT-16849 - Add a note about scripts
  docs/cse/integrations/insight-enrichment-server.md
Labels: doc:minor edit, cla-signed, do-not-merge

#2101 GH workflow staging
  .github/workflows/main.yml
  .github/workflows/review.yml
Labels: cla-signed

#2100 Misc. Style edits
  blog-cse/2023-03-10-content.md
  blog-service/2020/12-31.md
  docs/contributing/glossary.md
  docs/contributing/remove-doc.md
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
  docs/integrations/amazon-aws/aurora-postgresql-ulm.md
  docs/integrations/amazon-aws/ec2-cloudwatch-metrics.md
  docs/integrations/amazon-aws/redshift-ulm.md
  docs/integrations/amazon-aws/ses.md
  docs/integrations/amazon-aws/sns.md
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/databases/cassandra.md
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/faq.md
  docs/observability/aws/integrations/amazon-sns.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/observability/root-cause-explorer.md
  docs/observability/set-up-collection.md
  docs/search/get-started-with-search/build-search/dynamic-parsing.md
Labels: cla-signed

#2102 Update .clabot
  .clabot
Labels: cla-signed

#2099 TRIDENT-17128 - Add redirect
  cid-redirects.json
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-outlier-rule.md
  docs/integrations/cloud-security-monitoring-analytics/ueba.md
Labels: doc:minor edit, cla-signed

#2104 Update install-collector-linux.md
  docs/send-data/opentelemetry-collector/install-collector-linux.md
Labels: cla-signed

#2103 Update collect-metrics.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-metrics.md
Labels: cla-signed

#2105 Update attributes-map-to-records.md
  docs/cse/schema/attributes-map-to-records.md
Labels: cla-signed

#2107 Update create-custom-threat-intel-source.md
  docs/cse/administration/create-custom-threat-intel-source.md
Labels: cla-signed

#2108 Update inventory-sources-and-data.md
  docs/cse/administration/inventory-sources-and-data.md
Labels: cla-signed

#2111 Update deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#2110 Update deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#2066 minor formatting
  docs/integrations/containers-orchestration/kubernetes.md
  static/img/integrations/containers-orchestration/k8s-health.png
Labels: cla-signed, hot🔥

#2113 Updated-Securitylake
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  static/img/send-data/servicerole.png
Labels: cla-signed

#2120 updated table
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
Labels: cla-signed, do-not-merge, hot🔥

#2121 added new cid
  cid-redirects.json
Labels: cla-signed, hot🔥

#2052 Soar integration updates
  docs/cloud-soar/automation.md
  static/img/cloud-soar/integration-add-comment-to-issue.png
  static/img/cloud-soar/integration-automation-menu.png
  static/img/cloud-soar/integration-certified-2.png
  static/img/cloud-soar/integration-certified-action.png
  static/img/cloud-soar/integration-certified.png
  static/img/cloud-soar/integration-deleted-2.png
  static/img/cloud-soar/integration-deleted.png
  static/img/cloud-soar/integration-duplicate.png
  static/img/cloud-soar/integration-duplicated-resources-actions.png
  static/img/cloud-soar/integration-duplicated.png
  static/img/cloud-soar/integration-event-subscriptions.png
  static/img/cloud-soar/integration-profile-button.png
  static/img/cloud-soar/integration-settings-menu.png
  static/img/cloud-soar/integration-slack-add-app.png
  static/img/cloud-soar/integration-slack-bot-user-2.png
  static/img/cloud-soar/integration-slack-bot-user.png
  static/img/cloud-soar/integration-slack-chat-enable.png
  static/img/cloud-soar/integration-slack-chat-incident-id.png
  static/img/cloud-soar/integration-slack-chat-new-channel.png
  static/img/cloud-soar/integration-slack-edit-resource.png
  static/img/cloud-soar/integration-slack-from-scratch.png
  static/img/cloud-soar/integration-slack-in-list.png
  static/img/cloud-soar/integration-slack-install-to-workspace.png
  static/img/cloud-soar/integration-slack-instant-messaging.png
  static/img/cloud-soar/integration-slack-permissions.png
  static/img/cloud-soar/integration-slack-playbook.png
  static/img/cloud-soar/integration-slack-resource-2.png
  static/img/cloud-soar/integration-slack-resources.png
  static/img/cloud-soar/integration-slack-scopes-bot-token.png
  static/img/cloud-soar/integration-slack-scopes-user-token.png
  static/img/cloud-soar/integration-slack-scopes.png
  static/img/cloud-soar/integration-slack-user-choice-2.png
  static/img/cloud-soar/integration-slack-user-choice.png
  static/img/cloud-soar/integration-slack-user-oauth-token.png
  static/img/cloud-soar/integration-slack-workspace.png
  static/img/cloud-soar/integration-update-after.png
  static/img/cloud-soar/integration-update-before.png
  static/img/cloud-soar/integration-update.png
  static/img/cloud-soar/integrations-interactivity.png
Labels: doc:new, cla-signed, do-not-merge

#2124 updated screenshot and one step
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-azure-ad-inventory-source.md
  static/img/send-data/azure-ad-step-8.png
Labels: cla-signed

#2087 removed data volume legacy app docs
  blog-service/2017/12-31.md
  cid-redirects.json
  docs/get-started/apps-integrations.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/overview.md
  docs/integrations/sumo-apps/data-volume-legacy.md
  docs/integrations/sumo-apps/index.md
  sidebars.ts
Labels: cla-signed

#2119 Weekly legacy/404 fixes
  cid-redirects.json
Labels: cla-signed

#2125 Akamai DataStream app release note, release notes reformatting
  blog-service/2022/12-31.md
  blog-service/2023-01-05-search-query.md
  blog-service/2023-01-09-metrics.md
  blog-service/2023-01-17-alerts.md
  blog-service/2023-01-17-metrics.md
  blog-service/2023-01-19-traces.md
  blog-service/2023-01-24-security.md
  blog-service/2023-01-27-search-query.md
  blog-service/2023-01-30-monitor-based-slos.md
  blog-service/2023-02-06-metrics-monitors.md
  blog-service/2023-02-13-metrics-query.md
  blog-service/2023-02-13-rum.md
  blog-service/2023-02-15-slo-log-search.md
  blog-service/2023-02-17-reliability-management-slo.md
  blog-service/2023-02-24-improved-query-editor.md
  blog-service/2023-03-02-dashboard-migration.md
  blog-service/2023-03-28-otel-collector-apps.md
  blog-service/2023-04-05-scheduled-dashboard.md
  blog-service/2023-04-07-search.md
  blog-service/2023-04-07-traces.md
  blog-service/2023-04-13-apps.md
  blog-service/2023-04-13-sources.md
  blog-service/2023-04-18-apps.md
Labels: cla-signed

#2128 Move log_level beta page to search
  cid-redirects.json
  docs/search/get-started-with-search/search-page/log-level.md
  sidebars.ts
Labels: cla-signed

#2077 added metadata section
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
Labels: cla-signed

#2079 Collect from Other Data Sources index page.
  docs/send-data/collect-from-other-data-sources/index.md
Labels: cla-signed

#2089 FER Templates
  docs/integrations/microsoft-azure/iis-10-legacy.md
  docs/integrations/microsoft-azure/iis-7.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/index.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/varnish-opentelemetry.md
  docs/integrations/web-servers/varnish.md
  docs/manage/field-extractions/fer-templates/index.md
  static/img/integrations/cloud-security-monitoring-analytics/paloalto.png
  static/img/integrations/microsoft-azure/microsoft_iis_10.jpg
  static/img/integrations/microsoft-azure/microsoft_iis_10.png
  static/img/integrations/web-servers/Varnish_Small.png
  static/img/integrations/web-servers/varnish-cache.png
  static/img/integrations/web-servers/varnish.png
Labels: cla-signed

#2067 Collect Metrics Telegraf index page
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/index.md
  static/img/send-data/telegraf_icon.png
Labels: cla-signed

#2114 Rapid7-c2c
  blog-service/2023-04-19-collection.md
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
  sidebars.ts
  static/img/send-data/rapid7-logo.png
  static/img/send-data/rapid7_config_main.png
Labels: cla-signed, do-not-merge, hot🔥

#2130 updated sidebar title
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
Labels: cla-signed

#2131 SLO data retention
  docs/observability/reliability-management-slo/index.md
Labels: cla-signed

#2123 Shareable message
  docs/search/get-started-with-search/search-basics/share-message-link.md
  sidebars.ts
  static/img/search/get-started-search/search-basics/copy-message.png
  static/img/search/get-started-search/search-basics/highlighted-message.png
  static/img/search/get-started-search/search-basics/message-notification.png
  static/img/search/get-started-search/search-basics/select-message.png
Labels: cla-signed

#2137 Update crowdstrike-fdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-source.md
Labels: cla-signed

#2142 Collector release
  blog-collector/2023-04-19.md
Labels: cla-signed, do-not-merge

#2143 Update windows-active-directory-inventory-source.md
  docs/send-data/installed-collectors/sources/windows-active-directory-inventory-source.md
Labels: cla-signed

#2145 Update create-custom-threat-intel-source.md
  docs/cse/administration/create-custom-threat-intel-source.md
Labels: cla-signed

#2148 Added-Druva app
  docs/integrations/saas-cloud/druva.md
  sidebars.ts
  static/img/integrations/saas-cloud/druva-alerts-overview.png
  static/img/integrations/saas-cloud/druva-backup-and-restore.png
  static/img/integrations/saas-cloud/druva-overview.png
Labels: cla-signed

#2151 added-cid
  cid-redirects.json
Labels: cla-signed

#2141 Update crowdstrike-fdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-source.md
Labels: cla-signed

#2136 Update Send Data page - add links to Kubernetes Solution
  docs/send-data/collect-from-other-data-sources/kubernetes.md
  docs/send-data/index.md
  sidebars.ts
Labels: cla-signed

#2149 updated migrated screenshots
  static/img/integrations/app-development/Art-Cached.png
  static/img/integrations/app-development/Art-Download.png
  static/img/integrations/app-development/Art-Non-Cached.png
  static/img/integrations/app-development/Art-Overview.png
  static/img/integrations/app-development/Art-Traffic.png
  static/img/integrations/app-development/artifactory_app_request_access.png
  static/img/integrations/saas-cloud/Acquia_Drupal_Requests_Overview.png
  static/img/integrations/saas-cloud/Acquia_Errors_Overview.png
  static/img/integrations/saas-cloud/Acquia_FPM_Overview.png
  static/img/integrations/saas-cloud/Acquia_Overview.png
  static/img/integrations/saas-cloud/Akamai-Overview.png
  static/img/integrations/saas-cloud/Akamai-QOS.png
  static/img/integrations/saas-cloud/Akamai-Visitors.png
  static/img/integrations/saas-cloud/Akamai-Web-Application.png
  static/img/integrations/saas-cloud/Cloudflare-Performance_Hostname.png
  static/img/integrations/saas-cloud/Cloudflare-Performance_Requests.png
  static/img/integrations/saas-cloud/Cloudflare-Performance_Static.png
  static/img/integrations/saas-cloud/Cloudflare-Security-Overview.png
  static/img/integrations/saas-cloud/Cloudflare-Security_WAF.png
  static/img/integrations/saas-cloud/Cloudflare-Snapshot.png
  static/img/integrations/saas-cloud/Cloudflare_-_Reliability.png
  static/img/integrations/saas-cloud/Cloudflare_-_Security_(Overview).png
  static/img/integrations/saas-cloud/Cloudflare_Security-RateLimiting.png
  static/img/integrations/saas-cloud/Cloudflare_Security_Bot_Management.png
  static/img/integrations/saas-cloud/akamai_app_origin.png
  static/img/integrations/saas-cloud/akamai_app_security.png
Labels: cla-signed

#2135 minor update
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#2154 Revert "Collector release"
  blog-collector/2023-04-19.md
Labels: cla-signed

#2155 Collector Release
  blog-collector/2023-04-20.md
Labels: cla-signed

#2150 Sumo Logic Enterprise Apps index
  docs/integrations/sumo-apps/index.md
Labels: cla-signed

#2156 More legacy/404 fixes
  cid-redirects.json
Labels: cla-signed

#2153 Infrequent tier dashboard support correction
  cid-redirects.json
  docs/manage/partitions-data-tiers/infrequent-tier-dashboard-support.md
  docs/manage/partitions-data-tiers/infrequent-tier-search.md
Labels: cla-signed

#2158 Create 2023-04-13-content.md
  blog-cse/2023-04-13-content.md
Labels: cla-signed

#2159 Create 2023-04-20-content.md
  blog-cse/2023-04-20-content.md
Labels: cla-signed

#2160 Clarify Send Data > JSON Config section
  docs/alerts/monitors/index.md
  docs/send-data/collect-from-other-data-sources/kubernetes.md
  docs/send-data/index.md
  docs/send-data/use-json-configure-sources/index.md
  sidebars.ts
Labels: cla-signed

#2161 Cross-link IsValidIP on CIDR doc
  docs/search/search-query-language/search-operators/cidr.md
Labels: cla-signed

#2157 Google Analytics 4 (GA4) property tag
  docusaurus.config.js
  src/helper/google-analytics.js
Labels: cla-signed

#2091 TRIDENT-17611 - Automation Service for LA
  cid-redirects.json
  docs/cloud-soar/automation.md
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/automation-service/automation-service-bridge.md
  docs/cse/automation-service/automation-service-integrations.md
  docs/cse/automation-service/automation-service-playbooks.md
  docs/cse/automation-service/index.md
  docs/cse/index.md
  docs/cse/integrations/automation-service-enrichments.md
  docs/cse/integrations/automation-service.md
  sidebars.ts
  static/img/cse/automations-action-example.png
  static/img/cse/automations-add-a-condition-3.png
  static/img/cse/automations-add-action-node-1.png
  static/img/cse/automations-add-action-node.png
  static/img/cse/automations-add-condition-node-2.png
  static/img/cse/automations-add-condition-node.png
  static/img/cse/automations-add-node.png
  static/img/cse/automations-add-resource.png
  static/img/cse/automations-automations-list.png
  static/img/cse/automations-bridge-alias-create.png
  static/img/cse/automations-bridge-alias-default.png
  static/img/cse/automations-bridge-example-output.png
  static/img/cse/automations-bridge-installation-token.png
  static/img/cse/automations-bridge-monitoring-panel.png
  static/img/cse/automations-config-menu.png
  static/img/cse/automations-edit-button.png
  static/img/cse/automations-edit-condition-node.png
  static/img/cse/automations-edit-dialog.png
  static/img/cse/automations-edit-resource-2.png
  static/img/cse/automations-edit-resource.png
  static/img/cse/automations-entity-automations-menu.png
  static/img/cse/automations-insight-actions-menu.png
  static/img/cse/automations-integration-add-comment-to-issue.png
  static/img/cse/automations-integration-certified-2.png
  static/img/cse/automations-integration-certified-action.png
  static/img/cse/automations-integration-certified.png
  static/img/cse/automations-integration-duplicate.png
  static/img/cse/automations-integration-duplicated-resources-actions.png
  static/img/cse/automations-integration-duplicated.png
  static/img/cse/automations-integrations-actions-list.png
  static/img/cse/automations-integrations-file-hierarchy.png
  static/img/cse/automations-integrations-framework.png
  static/img/cse/automations-integrations-list.png
  static/img/cse/automations-malicious-threat-indicator.png
  static/img/cse/automations-manage-playbooks.png
  static/img/cse/automations-new-empty-playbook.png
  static/img/cse/automations-new-playbook-button.png
  static/img/cse/automations-new-playbook-dialog.png
  static/img/cse/automations-new.png
  static/img/cse/automations-on-insight.png
  static/img/cse/automations-open-playbook.png
  static/img/cse/automations-playbook-list.png
  static/img/cse/automations-playbook-status-graph.png
  static/img/cse/automations-playbook-status.png
  static/img/cse/automations-publish-playbook.png
  static/img/cse/automations-resource-example.png
  static/img/cse/automations-save-playbook-button.png
  static/img/cse/automations-start-node.png
Labels: doc:update, cla-signed

#2167 Letter fix in code snippet
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: cla-signed

#2152 Added-Release Notes
  blog-service/2023-04-21-apps.md
Labels: cla-signed, do-not-merge

#2169 Style guide edits
  docs/contributing/style-guide.md
  docs/integrations/microsoft-azure/iis-10-legacy.md
  docs/integrations/microsoft-azure/iis-7.md
  static/img/contributing/logo-no.png
  static/img/contributing/logo-yes.png
  static/img/contributing/screenshot-no.png
  static/img/contributing/screenshot-yes.png
  static/img/contributing/static-file.png
Labels: cla-signed

#2170 GA4 tag
  docusaurus.config.js
Labels: cla-signed

#2173 Release note for April 21, 2023
  blog-cse/2023-04-21-application-update.md
  cid-redirects.json
  docs/cse/automation-service/about-automation-service.md
  docs/cse/automation-service/automation-service-automations.md
  docs/cse/integrations/enrichments-and-indicators.md
  sidebars.ts
  static/img/release-notes/cse/automation-service-integrations.png
  static/img/release-notes/cse/automation-service-menu.png
  static/img/release-notes/cse/automation-service-playbook1.png
Labels: cla-signed

#2166 Source Reference Information
  docs/send-data/reference-information/index.md
Labels: cla-signed

#2174 TRIDENT-17806 - Add FedRAMP note
  docs/cse/automation-service/about-automation-service.md
Labels: doc:minor edit, cla-signed

#2172 Removal of FIPS 140-2 note
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
Labels: cla-signed, hot🔥

#2176 Update create-use-network-blocks.md
  docs/cse/administration/create-use-network-blocks.md
Labels: cla-signed

#2185 Update json-parameters-hosted-sources.md
  docs/send-data/use-json-configure-sources/json-parameters-hosted-sources.md
Labels: cla-signed

#2188 reverted to old screenshots of artifactory app
  static/img/integrations/app-development/Art-Cached.png
  static/img/integrations/app-development/Art-Download.png
  static/img/integrations/app-development/Art-Non-Cached.png
  static/img/integrations/app-development/Art-Overview.png
  static/img/integrations/app-development/Art-Traffic.png
  static/img/integrations/app-development/artifactory_app_request_access.png
Labels: cla-signed

#1926 Update before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
Labels: cla-signed, do-not-merge

#1933 Update update-aws-observability-stack.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
Labels: cla-signed, do-not-merge

#2133 update resources.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
Labels: cla-signed, do-not-merge

#2184 Log Level fixes
  blog-service/2023-04-07-search.md
  docs/search/get-started-with-search/search-page/log-level.md
Labels: cla-signed

#2127 #966 AWSO 2.6.0 release
  docs/integrations/amazon-aws/api-gateway/api-gateway-classic.md
  docs/integrations/amazon-aws/api-gateway/api-gateway-s3m.md
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/faq.md
  docs/observability/aws/integrations/amazon-sqs.md
Labels: cla-signed

#2134 Added missing alerts
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
Labels: cla-signed
