Repository SumoLogic/sumologic-documentation, pull requests merged in 2023-03, with the labels that each got.

#1763 Corrections to CSE administration articles
  docs/cse/administration/create-cse-actions.md
  docs/cse/administration/create-cse-context-actions.md
  docs/cse/administration/create-custom-threat-intel-source.md
  docs/cse/administration/create-use-network-blocks.md
  docs/cse/administration/cse-apis.md
  docs/cse/administration/cse-audit-logging.md
  docs/cse/administration/cse-user-accounts-and-roles.md
  docs/cse/administration/custom-inventory-sources.md
  docs/cse/administration/inventory-sources-and-data.md
  docs/cse/administration/save-inventory-data-lookup-table.md
Labels: cla-signed

#1762 Add AWS Kinesis Metrics JSON source
  docs/send-data/use-json-configure-sources/index.md
Labels: cla-signed

#1758 updated-screenshots
  docs/send-data/sumo-distribution-opentelemetry.md
  static/img/send-data/add-collector-link.png
  static/img/send-data/otdistro-osversion.png
Labels: cla-signed, do-not-merge, hot🔥

#1768 otel assets
  static/img/send-data/otel-color.svg
Labels: cla-signed

#1770 Fix support link
  docs/manage/manage-subscription/close-cancel-sumo-account.md
Labels: cla-signed

#1681 Update g-suite-apps-audit-source.md
  docs/send-data/hosted-collectors/google-source/g-suite-apps-audit-source.md
  static/img/send-data/g-suite-change-access.png
Labels: cla-signed

#1772 Revert "OT-Redis"
  docs/integrations/databases/opentelemetry/redis.md
Labels: cla-signed

#1672 Update aws-cloudtrail-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source.md
Labels: cla-signed

#1671 Update aws-cloudtrail.md
  docs/cse/ingestion/aws-cloudtrail.md
Labels: cla-signed

#1775 Send Data hub - OTEL
  docs/send-data/index.md
Labels: cla-signed

#1776 Get started signup
  docs/get-started/sign-up.md
Labels: cla-signed

#1777 send data home
  docs/send-data/index.md
Labels: cla-signed

#1778 Algolia launch announcement bar
  docusaurus.config.js
Labels: cla-signed

#1635 Accessibility audit fixes
  src/pages/index.tsx
  src/theme/Footer/index.tsx
Labels: cla-signed

#1779 Updates for Feb 24 and Mar 02
  blog-cse/2023-02-24-content.md
  blog-cse/2023-03-02-content.md
Labels: cla-signed

#1780 Get started/signup
  docs/get-started/sign-up.md
Labels: cla-signed

#1781 Dashboards migration update
  blog-service/2023-03-02-dashboard-migration.md
  static/img/release-notes/service/DashboardMigration.png
Labels: cla-signed

#1784 Consolidate Get Started
  cid-redirects.json
  docs/get-started/index.md
  docs/get-started/onboarding.md
  docs/get-started/overview.md
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  docs/get-started/sumo-logic-ui.md
  docs/manage/partitions-data-tiers/index.md
  docs/send-data/choose-collector-source.md
  sidebars.ts
  src/pages/index.tsx
  static/img/get-started/CollectorsM.png
Labels: cla-signed

#1782 Hosted Collector intro
  docs/send-data/hosted-collectors/index.md
  docs/send-data/index.md
  docs/send-data/installed-collectors/index.md
Labels: cla-signed

#1786 Get started
  docs/get-started/overview.md
  docs/get-started/quickstart.md
  docs/manage/field-extractions/create-field-extraction-rule.md
Labels: cla-signed

#1788 updated-doc
  docs/manage/security/log-search-audit-index.md
Labels: cla-signed

#1790 Update documentation Microsoft SQL Server App according to changes in Helm Chart v3
  docs/integrations/microsoft-azure/sql-server.md
  static/img/integrations/microsoft-azure/sqlk8s.drawio.xml
  static/img/integrations/microsoft-azure/sqlk8s.png
Labels: cla-signed

#1792 Couchabase OTel Collector
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/opentelemetry/couchbase.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#1799 More Legacy link/404s
  blog-collector/2022-10-12-welcome.md
  blog-service/2023-01-09-metrics.md
  blog-service/2023-01-17-metrics.md
  blog-service/2023-01-24-security.md
  blog-service/2023-01-30-monitor-based-slos.md
  blog-service/2023-02-06-metrics-monitors.md
  blog-service/2023-02-13-metrics-query.md
  blog-service/2023-02-13-rum.md
  blog-service/2023-02-15-slo-log-search.md
  cid-redirects.json
  docs/cse/administration/create-cse-context-actions.md
  docs/cse/records-signals-entities-insights/search-cse-records-in-sumo.md
  docs/cse/rules/before-writing-custom-rule.md
  docs/cse/rules/normalized-threat-rules.md
  docs/metrics/index.md
  docs/metrics/manage-metric-volume/index.md
  docs/release-notes/index.md
  docs/send-data/collection/upgrade-collectors.md
Labels: cla-signed

#1805 Fixing link for create SLO monitor
  docs/observability/reliability-management-slo/create-slo.md
Labels: cla-signed

#1789 Update web servers integration documentation
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx-plus-ingress.md
  docs/integrations/web-servers/nginx-plus.md
  docs/integrations/web-servers/nginx.md
  docs/integrations/web-servers/squid-proxy.md
  docs/integrations/web-servers/varnish.md
  static/img/integrations/web-servers/Apache-flow.drawio.xml
  static/img/integrations/web-servers/Apache-flow.png
  static/img/integrations/web-servers/apachetomcat-k8s.drawio.xml
  static/img/integrations/web-servers/apachetomcat-k8s.png
  static/img/integrations/web-servers/haproxy-k8s.drawio.xml
  static/img/integrations/web-servers/haproxy-k8s.png
  static/img/integrations/web-servers/nginxk8s.drawio.xml
  static/img/integrations/web-servers/nginxk8s.png
  static/img/integrations/web-servers/squid-proxy-k8s-flow.drawio.xml
  static/img/integrations/web-servers/squid-proxy-k8s-flow.png
  static/img/integrations/web-servers/varnish-k8s.drawio.xml
  static/img/integrations/web-servers/varnish-k8s.png
Labels: cla-signed

#1808 Update log-search-audit-index.md
  docs/manage/security/log-search-audit-index.md
Labels: cla-signed

#1809 case-sensitive note
  docs/send-data/installed-collectors/sources/local-file-source.md
Labels: cla-signed

#1802 Updated-Googleworkspace
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-source.md
  static/img/send-data/add-key.png
  static/img/send-data/create-cred-button.png
  static/img/send-data/create-credentials-service.png
  static/img/send-data/create-credentials.png
  static/img/send-data/domain-delegation.png
  static/img/send-data/generate-key.png
  static/img/send-data/google-workspace-icon.png
  static/img/send-data/google-workspace.png
  static/img/send-data/google_workspace_adding_scope1.png
  static/img/send-data/google_workspace_adding_scope2.png
  static/img/send-data/manage-domainwide-delegation.png
  static/img/send-data/private-key.png
  static/img/send-data/select-credentials.png
  static/img/send-data/service-account-details.png
  static/img/send-data/service-account-key.png
  static/img/send-data/workspace-setup1.png
  static/img/send-data/workspace-setup2.png
Labels: cla-signed, do-not-merge

#1810 Cse entity rel graph
  docs/cse/records-signals-entities-insights/about-cse-insight-ui.md
  static/img/cse/related-entities.jpg
  static/img/cse/related-entities.png
  static/img/cse/related-entity-graph.jpg
Labels: cla-signed

#1793 Updated-Knowbe4C2C
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed, do-not-merge

#1811 Mar 7, 2023 CSE Release Notes
  blog-cse/2023-03-07-application-update.md
  static/img/release-notes/cse/entity-rel-graph.jpg
Labels: cla-signed

#1812 removed broken image link
  blog-service/2023-03-02-dashboard-migration.md
Labels: cla-signed

#1824 Update knowbe4-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#1807 added-airtableapp
  docs/integrations/saas-cloud/airtable.md
  sidebars.ts
  static/img/integrations/saas-cloud/airtable-overview.png
Labels: cla-signed, do-not-merge

#1773 CID Placeholder - Airtable
  cid-redirects.json
Labels: cla-signed, do-not-merge

#1823 Added Citrix app
  docs/integrations/saas-cloud/citrix.md
  sidebars.ts
  static/img/integrations/saas-cloud/citrix-admin-overview.png
  static/img/integrations/saas-cloud/client-group-admin-overview.png
Labels: cla-signed

#1822 Update sumo-logic-open-source-projects.md - add the tracing integration libraries section and put autotel there
  docs/send-data/collect-from-other-data-sources/sumo-logic-open-source-projects.md
Labels: cla-signed

#1829 Update about.md
  docs/dashboards-new/about.md
Labels: cla-signed

#1827 Update ms-office-audit-source.md
  docs/send-data/hosted-collectors/ms-office-audit-source.md
Labels: cla-signed

#1774 CID Placeholder - Citrix Cloud
  cid-redirects.json
Labels: cla-signed, do-not-merge

#1831 updated-title
  docs/integrations/saas-cloud/citrix.md
  sidebars.ts
Labels: cla-signed

#1834 Added Jake
  .clabot
Labels: cla-signed

#1817 Fix field names for PagerDuty Events API V2
  docs/alerts/webhook-connections/pagerduty.md
Labels: cla-signed

#1801 Change GitHub source configuration procedure
  docs/integrations/app-development/github.md
Labels: cla-signed

#1835 Create 2023-03-10-content.md
  blog-cse/2023-03-10-content.md
Labels: cla-signed

#1839 Histogram Update
  docs/metrics/introduction/metric-histograms.md
  sidebars.ts
  static/img/metrics/metric-failure.png
  static/img/metrics/metric-histogram.png
Labels: cla-signed

#1840 Fix errors reported by spellcheck, extend ignore_words_list
  .github/workflows/pr.yml
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/databases/postgresql.md
Labels: cla-signed

#1815 Update Docker Enterprise Edition documentation
  docs/integrations/containers-orchestration/docker-enterprise-edition.md
Labels: cla-signed

#1843 Update http-traces-source.md
  docs/apm/traces/get-started-transaction-tracing/http-traces-source.md
Labels: cla-signed

#1851 Create stag.yml
  .github/workflows/stag.yml
Labels: cla-signed

#1845 added-structure
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/collect-logs.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/collect-metrics.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/collect-tracing.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/index.md
  docs/send-data/opentelemetry-distro-collector/index.md
  docs/send-data/opentelemetry-distro-collector/install-collector-on-linux.md
  docs/send-data/opentelemetry-distro-collector/install-collector-on-macos.md
  docs/send-data/opentelemetry-distro-collector/install-collector-on-windows.md
  docs/send-data/opentelemetry-distro-collector/sumo-logic-opentelemetry-vs-opentelemetry-upstream-relationship.md
  docs/send-data/opentelemetry-distro-collector/troubleshooting-and-faqs.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#1852 Revert "added-structure"
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/collect-logs.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/collect-metrics.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/collect-tracing.md
  docs/send-data/opentelemetry-distro-collector/data-source-and-configurations/index.md
  docs/send-data/opentelemetry-distro-collector/index.md
  docs/send-data/opentelemetry-distro-collector/install-collector-on-linux.md
  docs/send-data/opentelemetry-distro-collector/install-collector-on-macos.md
  docs/send-data/opentelemetry-distro-collector/install-collector-on-windows.md
  docs/send-data/opentelemetry-distro-collector/sumo-logic-opentelemetry-vs-opentelemetry-upstream-relationship.md
  docs/send-data/opentelemetry-distro-collector/troubleshooting-and-faqs.md
  sidebars.ts
Labels: cla-signed

#1850 added-harrish
  .clabot
Labels: cla-signed

#1863 Update metric-histograms.md
  docs/metrics/introduction/metric-histograms.md
Labels: cla-signed

#1868 Update sdo-manual-configuration.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
Labels: cla-signed

#1866 Update index.md
  docs/observability/sdo/set-up-sdo/index.md
Labels: cla-signed

#1848 Remove reference to Authentication Request URL
  docs/manage/security/saml/set-up-saml.md
Labels: cla-signed

#1864 Missing letter
  docs/search/search-query-language/search-operators/where.md
Labels: cla-signed

#1847 Looks like an issue with formatting here, inexplicable asterisks
  docs/dashboards-new/filter-template-variables.md
Labels: cla-signed

#1869 hitarth-sumo
  .clabot
Labels: cla-signed

#1841 Update workday documentation
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
  static/img/send-data/workday-source.jpg
  static/img/send-data/workday-source.png
Labels: cla-signed

#1836 trying extra space
  docs/send-data/hosted-collectors/http-source/logs-metrics.md
Labels: cla-signed

#1816 otlp.md: Add instructions for configuring OTLP endpoint using environment variables
  docs/send-data/hosted-collectors/http-source/otlp.md
Labels: cla-signed

#1820 Update sumo-logic-open-source-projects.md - add collectors section with Sumo Distro for OTC and Kubernetes Collection Helm Chart
  docs/send-data/collect-from-other-data-sources/sumo-logic-open-source-projects.md
Labels: cla-signed

#1846 Add misp links
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#1865 Update supported-tools-schema.md
  docs/observability/sdo/supported-tools-schema.md
Labels: cla-signed

#1828 Update microsoft-audit-office.md
  docs/cse/ingestion/microsoft-audit-office.md
Labels: cla-signed

#1871 Added-aboguszewski-sumo
  .clabot
Labels: cla-signed

#1838 fix position of docker stats source in send-data/use-json-configure-s…
  docs/send-data/use-json-configure-sources/index.md
Labels: cla-signed

#1728 release notes 19.432
  blog-collector/2023-02-27.md
  yarn.lock
Labels: cla-signed, do-not-merge, hot🔥

#1248 Algolia search bar config - merge March 15
  docusaurus.config.js
  src/css/sumo.scss
  src/theme/SearchBar.js
  src/theme/SearchBar/index.js
Labels: cla-signed, do-not-merge

#1806 Update docker ULM documentation according to Helm Chart v3
  docs/integrations/containers-orchestration/docker-ulm.md
Labels: cla-signed

#1874 Adding jpipkin1 to CLA
  .clabot
Labels: cla-signed

#1875 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#1870 CON-1594: Added troubleshooting section for 1password
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  static/img/send-data/1password-troubleshooting.jpg
Labels: cla-signed

#1857 crowdstrike fdr host inventory doc generation
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-host-inventory.md
  sidebars.ts
  static/img/send-data/crowdstrike-fdr-host-inventory-add-client.png
  static/img/send-data/crowdstrike-fdr-host-inventory-api-key-client.png
  static/img/send-data/crowdstrike-fdr-host-inventory-config-main.png
  static/img/send-data/crowdstrike-fdr-host-inventory-copy-creds.png
  static/img/send-data/crowdstrike-fdr-host-inventory-login-screen.png
  static/img/send-data/crowdstrike-fdr-host-inventory-new-client.png
  static/img/send-data/crowdstrike-fdr-host-inventory-open-menu.png
  static/img/send-data/crowdstrike-fdr-host-inventory-support-and-resources.png
Labels: cla-signed

#1833 Update supported platforms for Kubernetes App and EKS control plane App
  docs/integrations/amazon-aws/eks-control-plane.md
  docs/integrations/containers-orchestration/kubernetes.md
Labels: cla-signed

#1879 Expand/Collapse section - Search
  blog-service/2016/12-31.md
  blog-service/2021/12-31.md
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/search/get-started-with-search/search-page/navigate-messages-in-search-results.md
  sidebars.ts
  static/img/search/get-started-search/search-page/copy-message-option.png
  static/img/search/get-started-search/search-page/expand-message-option.png
Labels: cla-signed

#1881 Create 2023-03-15-content.md
  blog-cse/2023-03-15-content.md
Labels: cla-signed

#1873 add basic otelcol installation info for macOS
  docs/send-data/opentelemetry-collector/install-collector-on-macos.md
Labels: cla-signed, do-not-merge

#1883 Legacy links/404 fixes
  cid-redirects.json
  docs/integrations/microsoft-azure/active-directory-legacy.md
  docs/send-data/use-json-configure-sources/json-parameters-hosted-sources.md
Labels: cla-signed

#1877 docs(opentelemetry-collector): update documentation
  docs/send-data/opentelemetry-collector/data-source-and-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-and-configurations/collect-logs.md
  docs/send-data/opentelemetry-collector/install-collector-on-linux.md
  docs/send-data/opentelemetry-collector/install-collector-on-macos.md
  static/img/send-data/opentelemetry-collector/app-catalog-linux-collector.png
  static/img/send-data/opentelemetry-collector/app-catalog-linux-configure.png
  static/img/send-data/opentelemetry-collector/app-catalog-linux-prerequisite.png
  static/img/send-data/opentelemetry-collector/app-catalog-linux-register-collector.png
  static/img/send-data/opentelemetry-collector/app-catalog-linux-registration-success.png
  static/img/send-data/opentelemetry-collector/app-catalog-linux-success.png
  static/img/send-data/opentelemetry-collector/app-catalog-linux.png
  static/img/send-data/opentelemetry-collector/app-catalog-mac-os.png
  static/img/send-data/opentelemetry-collector/app-catalog-macos-add-new-collector.png
  static/img/send-data/opentelemetry-collector/app-catalog-macos-set-up-collector.png
  static/img/send-data/opentelemetry-collector/app-catalog-macos-source-creation.png
  static/img/send-data/opentelemetry-collector/app-catalog-macos-success-installation.png
  static/img/send-data/opentelemetry-collector/app-catalog-macos-success-registration.png
  static/img/send-data/opentelemetry-collector/linux-terminal-installation.png
  static/img/send-data/opentelemetry-collector/macos-terminal.png
Labels: cla-signed, do-not-merge

#1888 Update 2023-03-10-content.md
  blog-cse/2023-03-10-content.md
Labels: cla-signed

#1889 Algolia searchbar move to center
  docusaurus.config.js
Labels: cla-signed

#1890 CSE release notes for March 16
  blog-cse/2023-03-16-application-update.md
  static/img/release-notes/cse/timeline-filter.jpg
Labels: cla-signed

#1892 docs(opentelemetrry): update
  docs/send-data/opentelemetry-collector/data-source-and-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-and-configurations/collect-logs.md
  docs/send-data/opentelemetry-collector/data-source-and-configurations/collect-metrics.md
  docs/send-data/opentelemetry-collector/data-source-and-configurations/collect-tracing.md
  docs/send-data/opentelemetry-collector/install-collector-on-linux.md
  docs/send-data/opentelemetry-collector/install-collector-on-macos.md
  docs/send-data/opentelemetry-collector/install-collector-on-windows.md
  docs/send-data/opentelemetry-collector/sumo-logic-opentelemetry-vs-opentelemetry-upstream-relationship.md
  docs/send-data/opentelemetry-collector/troubleshooting-and-faqs.md
Labels: cla-signed

#1893 docs(opentelemetry): update
  docs/send-data/opentelemetry-collector/data-source-and-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-and-configurations/collect-logs.md
Labels: cla-signed

#1891 Top nav edits - Algolia searchbar width and feedback
  docusaurus.config.js
  src/css/sumo.scss
Labels: cla-signed

#1895 Update .clabot
  .clabot
Labels: cla-signed

#1887 Hub page - Dashboards (New)
  .github/workflows/stag.yml
  docs/dashboards-new/export-dashboard-new.md
  docs/dashboards-new/index.md
  docs/dashboards-new/link-dashboards.md
  docs/dashboards-new/migrate-new-dashboards.md
  docs/dashboards-new/panels/index.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-host-inventory.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
Labels: cla-signed

#1896 Re-implement stag
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/review.yml
Labels: cla-signed

#1897 Search link
  blog-service/2016/12-31.md
  blog-service/2021/12-31.md
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/search/get-started-with-search/search-page/index.md
  docs/search/get-started-with-search/search-page/navigate-through-search-results.md
  sidebars.ts
Labels: cla-signed

#1898 Revert "Re-implement stag"
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/review.yml
Labels: cla-signed

#1899 Re-implement stag
  .github/workflows/review.yml
Labels: cla-signed

#1900 404s
  cid-redirects.json
Labels: cla-signed

#1901 Missing Period - Threat Intel Quick Analysis
  docs/integrations/security-threat-detection/threat-intel-quick-analysis.md
Labels: cla-signed

#1903 Update choose-collector-source.md
  docs/send-data/choose-collector-source.md
Labels: cla-signed

#1906 Google Sources hub page
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
  docs/send-data/hosted-collectors/google-source/google-cloud-platform-source.md
  docs/send-data/hosted-collectors/google-source/index.md
  static/img/send-data/gcp-icon.png
Labels: cla-signed

#1800 HTTP Source hub page
  cid-redirects.json
  docs/manage/archive.md
  docs/metrics/introduction/metric-formats.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/configure-telegraf-output-plugin.md
  docs/send-data/collect-from-other-data-sources/collect-prometheus-metrics.md
  docs/send-data/collector-faq.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-metadata-tag-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-sources.md
  docs/send-data/hosted-collectors/http-source/generate-new-url.md
  docs/send-data/hosted-collectors/http-source/index.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/index.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/upload-logs.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/upload-metrics.md
  docs/send-data/hosted-collectors/http-source/otlp.md
  docs/send-data/hosted-collectors/http-source/traces.md
  docs/send-data/hosted-collectors/http-source/troubleshooting.md
  docs/send-data/installed-collectors/sources/streaming-metrics-source.md
  sidebars.ts
  static/img/send-data/OTLP-HTTP.png
  static/img/send-data/http-logs-metrics.png
  static/img/send-data/http-rum.png
  static/img/send-data/http-traces.png
Labels: cla-signed

#1754 Web Servers, Global Intelligence, Sumo Apps hub pages
  docs/integrations/global-intelligence/index.md
  docs/integrations/global-intelligence/kubernetes-devops.md
  docs/integrations/sumo-apps/index.md
  docs/integrations/web-servers/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/miro-source.md
  static/img/send-data/Miro-logo.png
  static/img/send-data/gmail-trace-logs-icon.svg
Labels: cla-signed

#1908 AWS Hosted Collector hub, dependency upgrades
  docs/integrations/amazon-aws/cost-explorer.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-cloudfront-source.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-cloudwatch-source-metrics.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-path-expressions.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-s3-audit-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cost-explorer-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-elastic-load-balancing-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-metadata-tag-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-scan-interval-sources.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-sources.md
  docs/send-data/hosted-collectors/amazon-aws/collection-aws-govcloud.md
  docs/send-data/hosted-collectors/amazon-aws/configure-your-aws-source-cloudformation.md
  docs/send-data/hosted-collectors/amazon-aws/index.md
  package.json
  sidebars.ts
  static/img/integrations/amazon-aws/costexplorer.png
  static/img/send-data/AWSGovCloudUS-Logo.jpeg
  static/img/send-data/aws-cloudformation.svg
  static/img/send-data/aws-kinesis-firehose-logs.png
  static/img/send-data/aws-kinesis-firehose-metrics.png
  static/img/send-data/aws-metadata-tag.png
  static/img/send-data/cloudtrail-source.png
  static/img/send-data/cloudwatch-icon.png
  yarn.lock
Labels: cla-signed

#1910 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#1909 Hub page: Hosted Collectors, et al.
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/configure-hosted-collector.md
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
  docs/send-data/hosted-collectors/google-source/google-cloud-platform-source.md
  docs/send-data/hosted-collectors/google-source/index.md
  docs/send-data/hosted-collectors/http-source/index.md
  docs/send-data/hosted-collectors/index.md
  docs/send-data/hosted-collectors/ms-office-audit-source.md
  static/img/send-data/cloud-syslog.png
  static/img/send-data/office_365_48.png
Labels: cla-signed

#1911 Hub page: Installed Collector ref
  docs/send-data/installed-collectors/collector-installation-reference/index.md
Labels: cla-signed

#1855 [CON-1636] Create DocuSign Monitor source doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/docusign-source.md
  sidebars.ts
  static/img/send-data/docusign-add-app-integration-key.png
  static/img/send-data/docusign-config-main.png
  static/img/send-data/docusign-create-app.png
  static/img/send-data/docusign-generate-rsa.png
  static/img/send-data/docusign-home.png
  static/img/send-data/docusign-icon.svg
  static/img/send-data/docusign-integration-key.png
  static/img/send-data/docusign-private-key.png
  static/img/send-data/docusign-redirect-uri.png
  static/img/send-data/docusign-user-id.png
Labels: cla-signed

#1842 [CON-1698] Create Integrations > DocuSign Monitor doc
  cid-redirects.json
  docs/integrations/saas-cloud/docusign.md
  sidebars.ts
  static/img/integrations/saas-cloud/docusign-alerts.png
  static/img/integrations/saas-cloud/docusign-icon.svg
  static/img/integrations/saas-cloud/docusign-overview.png
  static/img/integrations/saas-cloud/docusign-users.png
Labels: cla-signed, do-not-merge

#1884 Create Send Data > Druva C2C Source doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-source.md
  sidebars.ts
  static/img/send-data/druva-base-url.png
  static/img/send-data/druva-config.png
  static/img/send-data/druva-events-api-settings.png
  static/img/send-data/druva-icon.png
  static/img/send-data/druva-wheel-icon.png
Labels: cla-signed

#1913 docs(opentelemetry): fix todos
  docs/send-data/opentelemetry-collector/data-source-and-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-and-configurations/index.md
  docs/send-data/opentelemetry-collector/index.md
  docs/send-data/opentelemetry-collector/install-collector-on-linux.md
  docs/send-data/opentelemetry-collector/install-collector-on-macos.md
  docs/send-data/opentelemetry-collector/install-collector-on-windows.md
  static/img/send-data/opentelemetry-collector/app-catalog-linux-overview.png
  static/img/send-data/opentelemetry-collector/app-catalog-macos-overview.png
  static/img/send-data/opentelemetry-collector/resource-and-record-level-attributes.png
  static/img/send-data/opentelemetry-collector/resource-attributes-only.png
Labels: cla-signed

#1916 S3M OTEL Collector Troubleshooting/FAQ
  docs/send-data/opentelemetry-collector/troubleshooting-and-faqs.md
  docs/send-data/opentelemetry-collector/troubleshooting-faq.md
Labels: cla-signed

#1912 Edits to Hub pages and added missing C2C doc descriptions
  docs/integrations/amazon-aws/index.md
  docs/integrations/saas-cloud/armis.md
  docs/integrations/saas-cloud/dropbox.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/salesforce.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-cloud-to-cloud-source-migration.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-amp-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloud-to-cloud-source-versions.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/docusign-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dropbox-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/duo-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-azure-ad-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-trace-logs.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/miro-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-on-demand-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sophos-central-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/symantec-web-security-service-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
  docs/send-data/hosted-collectors/http-source/index.md
  src/css/sumo.scss
  static/img/integrations/saas-cloud/armis-icon.png
  static/img/integrations/saas-cloud/salesforce-logo.svg
  static/img/send-data/druva-logo.svg
Labels: cla-signed

#1920 G Suite --> Google Workspace rename
  cid-redirects.json
  docs/cse/ingestion/google-g-suite-apps-audit.md
  docs/cse/ingestion/google-workspace-apps-audit.md
  docs/get-started/faq.md
  docs/integrations/google/workspace/collect-logs.md
  docs/search/search-query-language/transaction-analytics/transaction-operator.md
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
  docs/send-data/hosted-collectors/google-source/google-cloud-platform-source.md
  docs/send-data/hosted-collectors/google-source/google-workspace-apps-audit-source.md
  docs/send-data/hosted-collectors/google-source/index.md
  docs/send-data/use-json-configure-sources/json-parameters-hosted-sources.md
  sidebars.ts
  static/img/send-data/google-workspace-audit.png
Labels: cla-signed

#1918 Update index.md
  docs/observability/reliability-management-slo/index.md
Labels: cla-signed

#1921 OTel structure formatting edits
  cid-redirects.json
  docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-metrics.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-traces.md
  docs/send-data/opentelemetry-collector/data-source-configurations/index.md
  docs/send-data/opentelemetry-collector/index.md
  docs/send-data/opentelemetry-collector/install-collector-linux.md
  docs/send-data/opentelemetry-collector/install-collector-macos.md
  docs/send-data/opentelemetry-collector/install-collector-windows.md
  docs/send-data/opentelemetry-collector/sumo-logic-opentelemetry-vs-opentelemetry-upstream-relationship.md
  sidebars.ts
Labels: cla-signed

#1894 [CON-1576] Create Integrations > SentinelOne doc
  cid-redirects.json
  docs/integrations/saas-cloud/sentinelone.md
  sidebars.ts
  static/img/integrations/saas-cloud/SentinelOne-Agent-Overview.png
  static/img/integrations/saas-cloud/SentinelOne-Threat-Analysis.png
  static/img/integrations/saas-cloud/SentinelOne-Threat-Overview.png
  static/img/send-data/sentinelone-icon.png
Labels: cla-signed

#1922 CON-1765: updated data source and images
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-host-inventory.md
  static/img/send-data/crowdstrike-fdr-host-inventory-config-main.png
  static/img/send-data/crowdstrike-fdr-host-inventory-icon.png
Labels: cla-signed

#1923 docs(opentelemetry): migrate troubleshooting.md from github
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/databases/cassandra.md
  docs/send-data/choose-collector-source.md
  docs/send-data/installed-collectors/collector-installation-reference/download-collector-from-static-url.md
  docs/send-data/opentelemetry-collector/install-collector-linux.md
  docs/send-data/opentelemetry-collector/install-collector-macos.md
  docs/send-data/opentelemetry-collector/install-collector-windows.md
  docs/send-data/opentelemetry-collector/troubleshooting-faq.md
  docs/send-data/sumo-distribution-opentelemetry.md
Labels: cla-signed

#1927 Update cid-redirects.json
  cid-redirects.json
Labels: cla-signed

#1924 SentinelOne - add to hub page
  docs/integrations/saas-cloud/airtable.md
  docs/integrations/saas-cloud/cisco-umbrella.md
  docs/integrations/saas-cloud/citrix-cloud.md
  docs/integrations/saas-cloud/cloudflare.md
  docs/integrations/saas-cloud/fastly.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/istio.md
  docs/integrations/saas-cloud/sentinelone.md
  docs/integrations/saas-cloud/slack.md
  docs/integrations/saas-cloud/zoom.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sentinelone-mgmt-api-source.md
  static/img/integrations/saas-cloud/cloudflare.png
  static/img/send-data/sentinelone-logo.svg
Labels: cla-signed

#1929 Added Open Source CSPM
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#1931 Formatting fixes/links, checkbox CSS
  docs/get-started/onboarding-checklists.md
  src/css/sumo.scss
Labels: cla-signed

#1932 updated siem forward option
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-host-inventory.md
  static/img/send-data/crowdstrike-fdr-host-inventory-config-main.png
Labels: cla-signed

#1938 Not formatted properly, the ":::" is displaying as plaintext.
  docs/manage/users-roles/users/delete-user.md
Labels: cla-signed

#1936 Updated the retry table of CyberArk EPM doc.
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
Labels: cla-signed

#1942 Updated links
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#1814 Update Istio documentation according to changes in Helm Chart v3
  docs/integrations/saas-cloud/istio.md
Labels: cla-signed

#1943 404/legacy fixes
  cid-redirects.json
Labels: cla-signed

#1944 Hub pg fixes
  docs/integrations/web-servers/index.md
  docs/search/search-cheat-sheets/index.md
Labels: cla-signed

#1945 otel-reuse
  docs/reuse/opentelemetry/config-app-install.md
  docs/reuse/opentelemetry/send-logs-intro.md
  docs/reuse/opentelemetry/send-logs-outro.md
  docs/reuse/opentelemetry/set-up-collector.md
Labels: cla-signed

#1946 Otel reuse
  docs/reuse/opentelemetry/config-app-install.md
  docs/reuse/opentelemetry/send-logs-outro.md
Labels: cla-signed

#1949 Create 2023-03-24-content.md
  blog-cse/2023-03-24-content.md
Labels: cla-signed

#1935 Added Ciscomeraki
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
  static/img/send-data/cisco-meraki-generate-key.png
  static/img/send-data/cisco-meraki-my-profile.png
  static/img/send-data/cisco-meraki-org-enable-api.png
  static/img/send-data/cisco-meraki-org-save.png
  static/img/send-data/cisco-meraki-org-settings.png
  static/img/send-data/cisco-meraki-save-key.png
  static/img/send-data/cisco-meraki-sumo-source-form.png
  static/img/send-data/cisco-meraki-sumo-source-select.png
Labels: cla-signed

#1947 upgrade Docusaurus packages
  package.json
  yarn.lock
Labels: cla-signed

#1617 OpenTelemetry (S3M) Docs migration - merge March 28
  cid-redirects.json
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/index.md
  docs/get-started/overview.md
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  docs/integrations/microsoft-azure/sql-server.md
  docs/send-data/index.md
  docs/send-data/sumo-distribution-opentelemetry.md
  sidebars.ts
  static/img/get-started/data-collection.png
  static/img/get-started/install-otel.png
  static/img/send-data/live_tail.png
Labels: cla-signed, do-not-merge

#1951 Re-order alphabetically and add Microsoft defender
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#1952 API Hub page and doc images
  docs/api/access-keys.md
  docs/api/collector-management/collector-api-methods-examples.md
  docs/api/collector-management/index.md
  docs/api/collector-management/source-api.md
  docs/api/collector-management/upgrade-downgrade-collectors.md
  docs/api/content-management.md
  docs/api/content-permissions.md
  docs/api/field-extraction-rules.md
  docs/api/field-management.md
  docs/api/folder-management.md
  docs/api/health-events.md
  docs/api/index.md
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/api/lookup-tables.md
  docs/api/metrics-query.md
  docs/api/metrics.md
  docs/api/partition-management.md
  docs/api/password-policy.md
  docs/api/policies-management.md
  docs/api/saml-configuration.md
  docs/api/scheduled-views.md
  docs/api/search-job.md
  docs/api/service-map.md
  docs/api/span-analytics.md
  docs/api/token-management.md
  docs/api/tracing.md
  docs/api/troubleshooting.md
  static/img/icons/magnifying-glass-header.png
  static/img/icons/search-small.png
Labels: cla-signed

#1954 CON-1781 Added base URL and updated source schema screenshot
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
  static/img/send-data/tenable_source.png
Labels: cla-signed

#1956 Added- Jagdish
  .clabot
Labels: cla-signed

#1940 TRIDENT-17529 Add note to First Seen Rule doc
  docs/cse/rules/write-first-seen-rule.md
Labels: doc:minor edit, cla-signed

#1961 CSE APIs with content reuse
  docs/api/cloud-siem-enterprise.md
  docs/cse/administration/cse-apis.md
  docs/reuse/cse-api-table.md
Labels: cla-signed

#1960 Updated CSE API articles
  docs/api/cloud-siem-enterprise.md
  docs/cse/administration/cse-apis.md
  docs/reuse/cse-api-table.md
Labels: doc:update, cla-signed

#1794 OpenTelemetry (S3M) Databases apps
  docs/integrations/databases/cassandra.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/elasticsearch.md
  docs/integrations/databases/mariadb.md
  docs/integrations/databases/memcached.md
  docs/integrations/databases/mongodb-atlas.md
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mariadb-opentelemetry.md
  docs/integrations/databases/opentelemetry/memcached-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
  docs/integrations/databases/postgresql.md
  docs/integrations/databases/redis.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#1795 OpenTelemetry (S3M) Web Servers apps
  .github/workflows/pr.yml
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/nginx.md
  docs/integrations/web-servers/opentelemetry/apache-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/nginx-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/squid-proxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/varnish-opentelemetry.md
  docs/integrations/web-servers/squid-proxy.md
  docs/integrations/web-servers/varnish.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#1962 OTEL databases fix
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
Labels: cla-signed

#1796 OpenTelemetry (S3M) Containers-Orchestration apps
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/containers-orchestration/opentelemetry/kafka-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/containers-orchestration/rabbitmq.md
  sidebars.ts
Labels: cla-signed

#1797 OpenTelemetry (S3M) MS/Azure apps
  docs/integrations/microsoft-azure/active-directory-json.md
  docs/integrations/microsoft-azure/opentelemetry/active-directory-json-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
  docs/integrations/microsoft-azure/sql-server.md
  sidebars.ts
Labels: cla-signed

#1798 OpenTelemetry (S3M) App Development apps
  docs/integrations/app-development/jfrog-artifactory.md
  docs/integrations/app-development/opentelemetry/jfrog-artifactory-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jira-opentelemetry.md
  docs/integrations/app-development/opentelemetry/puppet-opentelemetry.md
  docs/integrations/app-development/puppet.md
  docs/reuse/jfrog-artifactory-cached.md
  docs/reuse/jfrog-artifactory-download.md
  docs/reuse/jfrog-artifactory-noncached.md
  docs/reuse/jfrog-artifactory-overview.md
  docs/reuse/jfrog-artifactory-request-access.md
  docs/reuse/jfrog-artifactory-traffic.md
  sidebars.ts
Labels: cla-signed

#1878 OpenTelemetry (S3M) Host and OS apps
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/reuse/opentelemetry/send-logs-outro.md
  sidebars.ts
  static/img/integrations/hosts-operating-systems/mac-apple-icon.png
Labels: cla-signed, do-not-merge

#1964 OTEL Collector/App Edits
  docs/integrations/containers-orchestration/opentelemetry/kafka-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mariadb-opentelemetry.md
  docs/integrations/databases/opentelemetry/memcached-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/active-directory-json-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/nginx-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/squid-proxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/varnish-opentelemetry.md
  docs/send-data/opentelemetry-collector/data-source-configurations/index.md
  docs/send-data/opentelemetry-collector/install-collector-linux.md
  docs/send-data/opentelemetry-collector/install-collector-macos.md
  docs/send-data/opentelemetry-collector/install-collector-windows.md
  static/img/send-data/opentelemetry-collector/windows-installation.png
  static/img/send-data/opentelemetry-collector/windows-uninstall-3.png
Labels: cla-signed

#1953 Style guide additions
  docs/contributing/create-doc.md
  docs/contributing/style-guide.md
  docs/integrations/saml/auth0.md
  static/img/contributing/hub-card-style.png
Labels: cla-signed
