Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-08, with the labels that each got.

#4383 DOCS-368 - Update schema tag info in the match lists article
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: doc:update, cla-signed

#4320 Webex Bronze - App docs
  blog-service/2024-08-01-webex-app.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/webex-bronze.md
  docs/reuse/apps/view-dashboards.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4380 Update Copilot icon
  docs/get-started/apps-integrations.md
  docs/get-started/library.md
  docs/search/copilot.md
  static/img/search/copilot/copilot-cloud-siem-1.png
  static/img/search/copilot/copilot-cloud-siem-2.png
  static/img/search/copilot/copilot-cloud-siem-3.png
  static/img/search/copilot/copilot-cloud-siem-4.png
  static/img/search/copilot/copilot-json.png
  static/img/search/copilot/copilot-logo.png
  static/img/search/copilot/copilot-tab.png
  static/img/search/copilot/explore.png
  static/img/search/copilot/source-category.png
Labels: cla-signed

#4385 Grammar/formatting in data-enrichment.md
  docs/send-data/data-enrichment.md
Labels: cla-signed

#4387 Change Webex Bronze to Webex
  blog-service/2024-08-01-webex-app.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/webex.md
  sidebars.ts
  static/img/send-data/webex-logo.png
Labels: cla-signed

#4377 Update netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: cla-signed

#4257 AWSO 2.9.0 Docs update
  blog-service/2024-08-02-awso.md
  docs/integrations/amazon-aws/rds.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
  docs/observability/aws/integrations/amazon-rds.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
Labels: cla-signed, do-not-merge

#4388 CONN-3453 Fix redirect typo
  cid-redirects.json
Labels: cla-signed

#4391 Cloud SIEM content release notes for August 5, 2024
  blog-cse/2024-08-05-content.md
Labels: doc:new, cla-signed

#4340 Update Azure storage document
  docs/integrations/microsoft-azure/azure-storage.md
  static/img/integrations/microsoft-azure/Azure-Storage-Access.png
  static/img/integrations/microsoft-azure/Azure-Storage-Audit-control-plane-operations.png
  static/img/integrations/microsoft-azure/Azure-Storage-Availability.png
  static/img/integrations/microsoft-azure/Azure-Storage-Blob-Service.png
  static/img/integrations/microsoft-azure/Azure-Storage-Failures.png
  static/img/integrations/microsoft-azure/Azure-Storage-File-Service.png
  static/img/integrations/microsoft-azure/Azure-Storage-Health.png
  static/img/integrations/microsoft-azure/Azure-Storage-Operations.png
  static/img/integrations/microsoft-azure/Azure-Storage-Overview.png
  static/img/integrations/microsoft-azure/Azure-Storage-Performance.png
  static/img/integrations/microsoft-azure/Azure-Storage-Queue-Service.png
  static/img/integrations/microsoft-azure/Azure-Storage-Security-and-policy.png
  static/img/integrations/microsoft-azure/Azure-Storage-Storage-health.png
  static/img/integrations/microsoft-azure/Azure-Storage-Table-Service.png
  static/img/integrations/microsoft-azure/Azure-Storage-Tag-Location.png
  static/img/integrations/microsoft-azure/Azure-Storage-Tag-Tenant-Name.png
Labels: doc:update, cla-signed

#4395 Update first sentence link to v2 api docs
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: doc:minor edit, cla-signed

#4351 Usage management doc
  cid-redirects.json
  docs/manage/ingestion-volume/data-volume-index/granular-data-tracking.md
  docs/manage/manage-subscription/usage-management.md
  static/img/account/disable-granular-data-tracking.png
  static/img/account/gear-icon-accounts-page.png
  static/img/account/usage-management-click-here.png
  static/img/account/usage-management-warning.png
  static/img/account/usage-management.png
Labels: cla-signed

#4394 Release jamf doc for all
  blog-service/2024-08-07-collection.md
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4396 Update manage-indexes-variable-retention.md
  docs/manage/partitions/manage-indexes-variable-retention.md
Labels: cla-signed

#4393 CLI reference fixes
  docs/send-data/installed-collectors/collector-installation-reference/add-collector-linux-machine-image.md
  docs/send-data/installed-collectors/collector-installation-reference/download-collector-from-static-url.md
  docs/send-data/installed-collectors/collector-installation-reference/enable-sni-collector-transparent-proxy.md
  docs/send-data/installed-collectors/collector-installation-reference/enhanced-file-system-security-installed-collectors.md
  docs/send-data/installed-collectors/collector-installation-reference/force-collectors-name-clobber.md
  docs/send-data/installed-collectors/collector-installation-reference/parameters-command-line-installer.md
  docs/send-data/installed-collectors/collector-installation-reference/set-collector-as-ephemeral.md
  docs/send-data/installed-collectors/collector-installation-reference/set-run-as-user-for-collector.md
  docs/send-data/installed-collectors/collector-installation-reference/sumoconf-for-legacy-collectors.md
  docs/send-data/installed-collectors/collector-installation-reference/user-properties.md
Labels: cla-signed

#4398 Update usage-management.md
  docs/manage/manage-subscription/usage-management.md
Labels: cla-signed

#4401 Minor fix for threat detection article
  docs/security/additional-security-features/threat-detection-and-investigation.md
Labels: doc:minor edit, cla-signed

#4076 DOCS-149 - Data Deletion Requests (Beta)
  cid-redirects.json
  docs/manage/deletion-requests.md
  docs/manage/index.md
  static/img/search/get-started-search/deletion-request-cancel.png
  static/img/search/get-started-search/deletion-request-status.png
  static/img/search/get-started-search/deletion-request.png
Labels: cla-signed

#4404 Docusaurus 3.5.1 update
  docusaurus.config.js
  package.json
  src/css/sumo.scss
  yarn.lock
Labels: cla-signed

#4402 Update microsoft-ews-daemon.md - Add Important Note Section.
  docs/platform-services/automation-service/app-central/integrations/microsoft-ews-daemon.md
Labels: cla-signed

#2379 Release notes redesign POC
  blog-service/2023-05-30-apps.md
  src/css/sumo.scss
  static/img/release-notes/rss-white.png
Labels: cla-signed, do-not-merge

#4403 DOCS-370 - Cloud SOAR automation cleanup
  blog-cse/2023/12-31.md
  blog-csoar/2023/12-31.md
  cid-redirects.json
  docs/cloud-soar/audit-event-index.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/cloud-soar-bridge.md
  docs/cloud-soar/cloud-soar-integration-framework.md
  docs/cloud-soar/compared-to-automation-service.md
  docs/cloud-soar/index.md
  docs/cloud-soar/legacy/legacy-cloud-soar-automation.md
  docs/cloud-soar/overview.md
  docs/manage/security/audit-indexes/audit-event-index.md
  docs/manage/security/audit-indexes/documentation-audit-log-definitions.md
  docs/manage/security/audit-indexes/system-event-index.md
  docs/platform-services/automation-service/app-central/index.md
  docs/platform-services/automation-service/automation-service-app-central.md
  docs/platform-services/automation-service/automation-service-audit-logging.md
  docs/platform-services/automation-service/automation-service-bridge.md
  docs/platform-services/automation-service/automation-service-integration-framework.md
  docs/platform-services/automation-service/automation-service-integrations.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/platform-services/automation-service/index.md
  sidebars.ts
  static/img/cloud-soar/add-automation-rule.png
  static/img/cloud-soar/automation-rule-action-types.png
  static/img/cloud-soar/cloud-soar-secops.png
  static/img/cloud-soar/create-incident-template-2.png
  static/img/cloud-soar/create-incident-template.png
  static/img/cloud-soar/delivery-2-add-integration-button.png
  static/img/cloud-soar/delivery-2-add-resource.png
  static/img/cloud-soar/delivery-2-completed-integration-2.png
  static/img/cloud-soar/delivery-2-completed-integration.png
  static/img/cloud-soar/delivery-2-create-action-file.png
  static/img/cloud-soar/delivery-2-edit-resource-button.png
  static/img/cloud-soar/delivery-2-edit-resource-cloud-execution.png
  static/img/cloud-soar/delivery-2-new-integration-dialog.png
  static/img/cloud-soar/delivery-2-test-action.png
  static/img/cloud-soar/delivery-2-upload-files.png
  static/img/cloud-soar/delivery-2-upload-icon.png
  static/img/cloud-soar/export-playbook.png
  static/img/cloud-soar/import-playbook-modal.png
  static/img/cloud-soar/import-playbook.png
  static/img/cloud-soar/incident-creation-screen.png
  static/img/cloud-soar/incident-templates.png
  static/img/cloud-soar/integration-slack-bot-user-2.png
  static/img/cloud-soar/integration-slack-in-list.png
  static/img/cloud-soar/integration-slack-instant-messaging-delivery2.png
  static/img/cloud-soar/integration-slack-playbook.png
  static/img/cloud-soar/integration-slack-resources.png
  static/img/cloud-soar/new-incident-template.png
  static/img/cloud-soar/sample-automation-rule.png
  static/img/cse/automations-integration-add-comment-to-issue.png
  static/img/cse/automations-integration-duplicate.png
  static/img/cse/automations-integration-duplicated-resources-actions.png
  static/img/cse/automations-integration-duplicated.png
  static/img/cse/automations-new-empty-playbook.png
  static/img/cse/automations-start-node.png
Labels: doc:update, cla-signed

#4406 Azure SQL collection and dashboard update
  blog-service/2024-08-13-apps.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/sql.md
  static/img/integrations/microsoft-azure/Azure-SQL-Automated-Tuning.png
  static/img/integrations/microsoft-azure/Azure-SQL-Configure-Auditing.png
  static/img/integrations/microsoft-azure/Azure-SQL-Configure-Diagnostic-Logs.png
  static/img/integrations/microsoft-azure/Azure-Storage-Security-and-policy.png
  static/img/integrations/microsoft-azure/Azure-Storage-Storage-health.png
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Edit-Settings.png
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Plans.png
Labels: cla-signed, hot🔥

#4409 Update Release notes (2024-08-13-apps.md)
  blog-service/2024-08-13-apps.md
Labels: cla-signed

#4407 Clean up Cloud SOAR links
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/overview.md
  docs/platform-services/automation-service/automation-service-audit-logging.md
  docs/platform-services/automation-service/automation-service-integration-framework.md
Labels: doc:minor edit, cla-signed

#4410 fixed the sumo-logic-notifications-by-gmail
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail.md
Labels: cla-signed

#4411 Update installation-tokens.md
  docs/manage/security/installation-tokens.md
Labels: cla-signed

#4412 Update to Docusaurus 3.5.2
  package.json
  yarn.lock
Labels: cla-signed

#4414 JavaScript config fixes - GA4, GTM, Google Translate
  docusaurus.config.js
  src/helper/google-analytics.js
  src/helper/google-tag-manager.js
  src/helper/google-translate.js
Labels: cla-signed

#4416 Improve alt text style guidance
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/incidents-triage.md
  docs/contributing/style-guide.md
  docs/dashboards/scheduled-report.md
Labels: cla-signed

#4418 Add JP to list of OTEL Code Owners
  .github/CODEOWNERS
Labels: doc:site tech, cla-signed

#4420 Update aws-kinesis-firehose-metrics-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source.md
Labels: cla-signed

#4421 Update faq.md
  docs/observability/aws/faq.md
Labels: cla-signed

#4422 Weekly 404 fixes
  cid-redirects.json
Labels: cla-signed

#4415 Fix JS Uncaught TypeErrors
  src/components/ErrorBoundary.tsx
  src/pages/index.tsx
Labels: doc:site tech, cla-signed

#4423 DOCS-381 - Add view field
  docs/manage/data-forwarding/amazon-s3-bucket.md
Labels: doc:update, cla-signed

#4424 Resolve defaultProps deprecation warning
  package.json
  yarn.lock
Labels: doc:site tech, cla-signed

#4425 Update index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
Labels: doc:update, cla-signed

#4428 Add Andrew-L-Johnson to cla
  .clabot
Labels: doc:minor edit, cla-signed

#4419 Update faq.md
  docs/send-data/opentelemetry-collector/faq.md
Labels: cla-signed

#4426 Fix broken Health dashboard image
  docs/integrations/microsoft-azure/azure-storage.md
Labels: doc:minor edit, cla-signed

#4427 Update Microsoft Teams connections page with Workflows info
  docs/alerts/webhook-connections/microsoft-teams.md
Labels: doc:update, cla-signed

#4432 DOCS-392 - Subfolders note
  docs/get-started/library.md
Labels: doc:update, cla-signed

#4434 Cloud SIEM content release notes for August 16, 2024
  blog-cse/2024-08-16-content.md
Labels: doc:new, cla-signed

#4329 DOCS-342 - Update tour new UI article for Kanso Beta 2.1
  docs/get-started/library.md
  docs/get-started/sumo-logic-ui-new.md
  static/img/get-started/library.png
  static/img/get-started/recent.png
Labels: doc:update, cla-signed

#4436 Fix broken rendering - Google Translate widget
  docusaurus.config.js
  src/theme/NavbarItem/GoogleTranslateNavbarItem.tsx
  src/theme/NavbarItem/HtmlNavbarItem.tsx
Labels: cla-signed

#4430 Updating compressed data support for http sources
  docs/send-data/hosted-collectors/http-source/logs-metrics/upload-logs.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/upload-metrics.md
Labels: cla-signed

#4313 Atlassian c2c Source
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/atlassian-source.md
  sidebars.ts
  static/files/c2c/atlassian/example.json
  static/files/c2c/atlassian/example.tf
  static/img/send-data/atlassian-icon.png
Labels: cla-signed

#4440 Remove beta tag and add to sidebar nav
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/snowflake-sql-api.md
  sidebars.ts
Labels: cla-signed

#4441 Microsoft Graph Security API - Remove write permissions
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
Labels: cla-signed

#4442 CONN-3482 Add OAuth feature to docs
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed

#4433 DOCS-390 - Add jsonArraySize to search operators
  docs/search/search-query-language/search-operators/index.md
  docs/search/search-query-language/search-operators/isvalidip.md
  docs/search/search-query-language/search-operators/jsonarraysize.md
  sidebars.ts
Labels: doc:new, cla-signed

#4447 DOCS-51 - Cloud SOAR incident labels
  docs/cloud-soar/overview.md
  static/img/cloud-soar/new-label.png
Labels: doc:update, cla-signed

#4449 CONN-3478 Update source note
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
Labels: cla-signed

#4448 DOCS-399 - Fix collapsible text box
  docs/apm/real-user-monitoring/configure-data-collection.md
Labels: doc:update, cla-signed

#4450 Add playbooks version section
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/platform-services/automation-service/playbook-versions.png
Labels: doc:new, cla-signed

#4454 DOCS-404 - New domain_controller_hostnames match list
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: doc:new, cla-signed

#4458 Update audit.md
  docs/integrations/microsoft-azure/audit.md
Labels: cla-signed

#4451 CrowdStrike FDR Host Inventory app doc
  blog-service/2024-08-23-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/crowdstrike-fdr-host-inventory.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: cla-signed

#4382 CONN-3450: Added base entry init lookback param for Kaltura Integration
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/kaltura-source.md
  static/files/c2c/kaltura/example.json
  static/files/c2c/kaltura/example.tf
Labels: cla-signed

#4460 Collector Version 19.506-1
  blog-collector/2024-08-23.md
Labels: cla-signed, hot🔥

#4456 Added cluster options in mongo yaml
  docs/integrations/databases/mongodb-atlas.md
Labels: cla-signed

#4461 Cloud SIEM content release notes for August 23, 2024
  blog-cse/2024-08-23-content.md
Labels: cla-signed

#4459 Update index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
Labels: cla-signed

#4453 Changes for full changelog in ST
  cid-redirects.json
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/apache.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/docker.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/kafka.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/linux.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/localfile.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/mac.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/nginx.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/rabbitmq.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/redis.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/syslog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/windows.md
Labels: cla-signed

#4462 DOCS-50 - Add start node parameter types
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/platform-services/automation-service/edit-start-node.png
  static/img/platform-services/automation-service/start-node-parameters.png
  static/img/platform-services/automation-service/start-node.png
Labels: doc:update, cla-signed

#4463 Weekly 404 fixes
  cid-redirects.json
Labels: cla-signed

#4465 App central google chat
  docs/integrations/product-list/product-list-a-l.md
  docs/platform-services/automation-service/app-central/integrations/google-chat.md
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#4464 Symantec Endpoint Security C2C Source
  blog-service/2024-08-27-collection.md
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/symantec-endpoint-security-source.md
  sidebars.ts
Labels: cla-signed

#4472 Create 2024-08-27-content.md
  blog-cse/2024-08-27-content.md
Labels: doc:new, cla-signed

#4466 Add link to Action Limits section
  docs/reuse/actions-limit-query.md
Labels: doc:update, cla-signed

#4471 Add links to the automated playbooks article
  docs/alerts/monitors/use-playbooks-with-monitors.md
Labels: doc:update, cla-signed

#4470 Update Cloud SIEM article with new signals features
  docs/cse/records-signals-entities-insights/view-records-signal.md
  static/img/cse/attached-records.png
Labels: doc:update, cla-signed

#4473 Revert "Update Cloud SIEM article with new signals features"
  docs/cse/records-signals-entities-insights/view-records-signal.md
  static/img/cse/attached-records.png
Labels: cla-signed

#4475 Revert "Revert "Update Cloud SIEM article with new signals features""
  docs/cse/records-signals-entities-insights/view-records-signal.md
  static/img/cse/attached-records.png
Labels: doc:update, cla-signed

#4474 RSS release notes thumbnail test
  blog-collector/2024-07-03.md
  blog-collector/2024-08-23.md
  static/img/sumologic-rss-preview.jpg
Labels: doc:site tech, cla-signed

#4476 Revert "RSS release notes thumbnail test"
  blog-collector/2024-07-03.md
  blog-collector/2024-08-23.md
  static/img/sumologic-rss-preview.jpg
Labels: cla-signed

#4468 Update crowdstrike-fdr-host-inventory.md
  docs/integrations/saas-cloud/crowdstrike-fdr-host-inventory.md
Labels: cla-signed

#4438 Behaviour Change for `_count` Operator - RN
  blog-service/2024-08-28-search.md
  docs/manage/scheduled-views/scheduled-views-best-practices.md
  docs/search/lookup-tables/manage-update-lookup-tables.md
Labels: cla-signed

#4481 Fixed Typo - Missing 2 in Year
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: doc:minor edit, cla-signed

#4446 Added monitors information to 1Password app doc
  docs/integrations/1password.md
  static/img/integrations/1password/1Password-Audit-Security.png
  static/img/integrations/1password/1Password-Overview.png
Labels: cla-signed, do-not-merge

#4479 DOCS-417 - Update Code42 Incydr article
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/code42-incydr-source.md
  static/files/c2c/code42-incydr/example.json
  static/files/c2c/code42-incydr/example.tf
Labels: doc:minor edit, cla-signed

#4444 Azure application gateway doc
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/sql.md
  static/img/integrations/microsoft-azure/Azure-Storage-Access.png
  static/img/integrations/microsoft-azure/Azure-Storage-Audit-control-plane-operations.png
  static/img/integrations/microsoft-azure/Azure-Storage-Availability.png
  static/img/integrations/microsoft-azure/Azure-Storage-Blob-Service.png
  static/img/integrations/microsoft-azure/Azure-Storage-Failures.png
  static/img/integrations/microsoft-azure/Azure-Storage-File-Service.png
  static/img/integrations/microsoft-azure/Azure-Storage-Health.png
  static/img/integrations/microsoft-azure/Azure-Storage-Operations.png
  static/img/integrations/microsoft-azure/Azure-Storage-Overview.png
  static/img/integrations/microsoft-azure/Azure-Storage-Performance.png
  static/img/integrations/microsoft-azure/Azure-Storage-Queue-Service.png
  static/img/integrations/microsoft-azure/Azure-Storage-Security-and-policy.png
  static/img/integrations/microsoft-azure/Azure-Storage-Storage-health.png
  static/img/integrations/microsoft-azure/Azure-Storage-Table-Service.png
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Edit-Settings.png
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Plans-AppService.png
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Plans-Storage.png
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Plans.png
  static/img/integrations/microsoft-azure/appgatway-tier-setting.png
  static/img/send-data/azureapplicationgateway-logs.png
  static/img/send-data/azureapplicationgateway-metrics.png
Labels: cla-signed, do-not-merge

#4452 Azure functions documentation changes
  blog-service/2024-08-29-apps.md
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/sql.md
  static/img/integrations/microsoft-azure/Azure-Functions-Configure-Diagnostic-Metrics.png
  static/img/integrations/microsoft-azure/Azure-Storage-Tag-Location.png
  static/img/integrations/microsoft-azure/Enable-Health-Check-Metric.png
Labels: cla-signed, hot🔥

#4483 DOCS-416 - Update Manage Organizational Settings article
  docs/manage/manage-subscription/manage-org-settings.md
  static/img/subscriptions/manage-org-links-cfc.png
Labels: doc:minor edit, cla-signed

#4488 Updated docs for Jira V2
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-v2.md
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-2.png
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-3.png
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-4.png
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-5.png
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-6.png
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-7.png
Labels: cla-signed

#4489 Updated docs for smtp V3
  docs/platform-services/automation-service/app-central/integrations/smtp-v3.md
Labels: cla-signed

#4493 RUM metrics overhaul for readability
  docs/apm/real-user-monitoring/metrics.md
Labels: cla-signed
