Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-01, with the labels that each got.

#3439 Index Filter (Search) Release note
  blog-service/2024-01-02-index-filter.md
  docs/search/get-started-with-search/search-basics/built-in-metadata.md
  static/img/search/get-started-search/search-basics/msg-with-metadata.png
  static/img/search/get-started-search/search-page/index-filter.png
Labels: cla-signed, do-not-merge

#3455 Add Gourav2906 to CLA
  .clabot
Labels: doc:minor edit, cla-signed

#3457 OpenTelemetry troubleshooting update
  docs/send-data/opentelemetry-collector/troubleshooting.md
Labels: doc:update, cla-signed

#3458 Update to search API article
  docs/api/search-job.md
Labels: doc:minor edit, cla-signed

#3449 Maintenance announcement bar - Jan '24
  docusaurus.config.js
Labels: cla-signed

#3456 Fix path for G Suite Audit parser
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/google-workspace-apps-audit.md
Labels: doc:minor edit, cla-signed

#3459 Added new release notes for Cloud SOAR and Automation Service
  blog-csoar/2024-01-03-application-update.md
Labels: cla-signed

#3450 Move helm chart v4 migration guide
  docs/send-data/kubernetes/v4/upgrade-guide/full-list-of-changes.md
  docs/send-data/kubernetes/v4/upgrade-guide/how-to-upgrade.md
  docs/send-data/kubernetes/v4/upgrade-guide/important-changes.md
  sidebars.ts
Labels: cla-signed

#3454 Move helm chart v3 migration guide
  docs/send-data/kubernetes/helm-chart-overview.md
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/v3/full-list-of-changes.md
  docs/send-data/kubernetes/v3/how-to-upgrade.md
  docs/send-data/kubernetes/v3/important-changes.md
  docs/send-data/kubernetes/v4/full-list-of-changes.md
  docs/send-data/kubernetes/v4/how-to-upgrade.md
  docs/send-data/kubernetes/v4/important-changes.md
  sidebars.ts
Labels: cla-signed

#3464 Description field for rule tuning expressions
  docs/cse/rules/rule-tuning-expressions.md
  static/img/cse/annotated-expression.png
  static/img/cse/enable-on-details.png
  static/img/cse/enable-on-list.png
  static/img/cse/example-expression.png
  static/img/cse/new-expression.png
  static/img/cse/rule-tuning-option.png
  static/img/cse/tuning.png
Labels: doc:minor edit, cla-signed

#3462 Add missing GI Cloudtrail Sched Searches table
  docs/integrations/amazon-aws/global-intelligence-cloudtrail-secops.md
Labels: cla-signed

#3460 Workday app fixes
  docs/integrations/saas-cloud/workday.md
Labels: cla-signed, do-not-merge

#3470 Reduce banner character count
  docusaurus.config.js
Labels: cla-signed

#3468 Enable Process metric collection info added
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/reuse/apps/opentelemetry/process-metric-collection.md
  package.json
  yarn.lock
Labels: cla-signed, do-not-merge

#3419 AWS Observability centralized/hub page info added
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/faq.md
  docs/observability/aws/index.md
Labels: cla-signed

#3474 2024-01-08-content
  blog-csoar/2024-01-08-content.md
Labels: cla-signed

#3472 Update link to v3 migration guide
  docs/send-data/kubernetes/v4/how-to-upgrade.md
Labels: cla-signed

#3475 Update mitre-coverage.md
  docs/cse/administration/mitre-coverage.md
Labels: doc:minor edit, cla-signed

#3471 Fix broken log search syntax
  docs/search/search-cheat-sheets/iis-search-examples.md
  docs/search/search-cheat-sheets/log-operators.md
Labels: cla-signed

#3476 Update search-audit-index.md
  docs/manage/security/audit-indexes/search-audit-index.md
Labels: cla-signed

#3473 Update view-dashboards.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
Labels: cla-signed

#3484 Update link to v3 migration guide in important changes part
  docs/send-data/kubernetes/v4/important-changes.md
Labels: cla-signed

#3487 Adding note for itemized alerts + equal to zero alert condition
  docs/alerts/webhook-connections/schedule-searches-webhook-connections.md
Labels: cla-signed

#3461 Unstructured v. Structured OTEL Logs
  docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-configurations/mapping-records-resources.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#3492 GTM tags
  docusaurus.config.js
  src/helper/google-tag-manager.js
Labels: cla-signed

#3491 Fix broken link in Box article
  docs/integrations/saas-cloud/box.md
Labels: doc:minor edit, cla-signed

#3368 Unified Threat Intelligence - beta
  cid-redirects.json
  docs/platform-services/threat-intelligence-indicators.md
  static/img/platform-services/threat-intelligence-add-indicators.png
  static/img/platform-services/threat-intelligence-delete-indicators.png
  static/img/platform-services/threat-intelligence-tab.png
Labels: doc:new, cla-signed, do-not-merge

#3496 Remove announcementBar, remove legacy Google UA tag, add GTM tag
  docusaurus.config.js
Labels: cla-signed

#3493 Add threat intel role capabilities
  docs/manage/users-roles/roles/role-capabilities.md
Labels: doc:new, cla-signed

#3489 docs: add information about missing opampbridge crd
  docs/send-data/kubernetes/v4/how-to-upgrade.md
Labels: cla-signed

#3488 Release note for New view for child org usages
  blog-service/2024-01-11-manage.md
Labels: cla-signed, do-not-merge, hot🔥

#3431 Child org tab information added to Accounts page
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
  static/img/subscriptions/account-overview-new.png
  static/img/subscriptions/baselines_1.png
  static/img/subscriptions/baselines_2.png
  static/img/subscriptions/child-credit-usage.png
  static/img/subscriptions/child-org.png
Labels: cla-signed

#3499 Update cse-rules-syntax.md
  docs/cse/rules/cse-rules-syntax.md
Labels: cla-signed

#3497 CONN-2809 New C2C for STIX TAXII 2 (Beta)
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
  static/files/c2c/taxii-2/example.json
  static/files/c2c/taxii-2/example.tf
Labels: cla-signed

#3501 Add information about using FIPS compliant OpenTelemetry Collector in the Sumo Logic Helm Chart
  docs/send-data/kubernetes/install-helm-chart.md
Labels: cla-signed

#3503 Fix link in install-helm-chart.md
  docs/send-data/kubernetes/install-helm-chart.md
Labels: cla-signed

#3495 Updates to the threat intelligence indicators beta article
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed, do-not-merge

#3505 Content Release Note
  blog-cse/2024-01-12-content.md
Labels: doc:new, cla-signed

#3440 Release note for Active directory app update
  blog-service/2024-01-15-active-directory-app-update.md
Labels: cla-signed, do-not-merge

#3502 Monitor child org doc update
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
Labels: cla-signed

#3466 adding/modifying notes in all apps which are based on single windows …
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/windows-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/active-directory-json-opentelemetry.md
  docs/integrations/pci-compliance/opentelemetry/windows-json-opentelemetry.md
Labels: cla-signed

#3500 Update workday-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
Labels: cla-signed

#3506 Fix audit index link in metrics dpm documentation
  docs/metrics/metrics-dpm.md
Labels: cla-signed

#3509 Updated 20240103 changelog with Improvements
  blog-csoar/2024-01-03-application-update.md
Labels: cla-signed

#3512 CSOAR-1239 [OIF] Add possibility to rename integrations
  docs/cloud-soar/cloud-soar-integration-framework.md
Labels: cla-signed

#3517 Fix table per issue #3478
  docs/search/get-started-with-search/search-page/log-level.md
Labels: doc:minor edit, cla-signed

#3516 Update Delegated User Email description
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
Labels: doc:minor edit, cla-signed

#3515 Fix bullet lists in integration framework article
  docs/platform-services/automation-service/automation-service-integration-framework.md
Labels: doc:minor edit, cla-signed

#3511 Removed the highlighting for Subqueries in SQL code
  docs/search/subqueries.md
Labels: cla-signed

#3518 Update .clabot
  .clabot
Labels: cla-signed

#3510 Move helm chart best practices document
  docs/send-data/kubernetes/best-practices.md
  docs/send-data/kubernetes/install-helm-chart.md
  sidebars.ts
Labels: cla-signed

#3519 Update tourl.md
  docs/search/search-query-language/search-operators/tourl.md
Labels: cla-signed

#3507 Move helm chart security best practices
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/security-best-practices.md
  sidebars.ts
Labels: cla-signed

#3522 Revert "Removed the highlighting for Subqueries in SQL code"
  docs/search/subqueries.md
  src/css/sumo.scss
Labels: cla-signed

#3526 fix links to security-best-practices and troubleshooting-guide
  docs/send-data/kubernetes/security-best-practices.md
  docs/send-data/kubernetes/troubleshoot-collection.md
Labels: cla-signed

#3520 Fix 365 logo, formatting
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/office-365.md
  static/img/integrations/microsoft-azure/365.png
Labels: cla-signed

#3531 Fix log search sheet links
  docs/search/search-cheat-sheets/log-operators.md
Labels: cla-signed

#3490 Log search New Visualizations - RN
  blog-service/2024-01-18-search.md
  docs/search/get-started-with-search/search-basics/chart-search-results.md
  static/img/search/get-started-search/search-basics/log-query-charts-properties.png
  static/img/search/get-started-search/search-basics/switch-to-classic-visualizations.png
  static/img/search/get-started-search/search-page/new-visualizations.png
Labels: cla-signed

#3535 Spot check for broken asterisks and indentation - Security articles
  docs/cloud-infrastructure-security/threat-detection-and-investigation.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/cloud-soar-integration-framework.md
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/corelight-zeek.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-windows.md
  docs/cse/match-lists-suppressed-lists/create-match-list.md
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
  docs/cse/match-lists-suppressed-lists/suppressed-lists.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/cse/rules/before-writing-custom-rule.md
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-chain-rule.md
  docs/cse/rules/write-match-rule.md
  docs/cse/rules/write-threshold-rule.md
  docs/cse/schema/parser-editor.md
  docs/platform-services/automation-service/about-automation-service.md
Labels: doc:minor edit, cla-signed

#3536 Spot check for broken asterisks and indentation - Manage articles
  docs/manage/data-archiving/archive.md
  docs/manage/data-forwarding/view-list-data-forwarding.md
  docs/manage/manage-subscription/cloud-flex-accounts.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/scheduled-views/scheduled-views-best-practices.md
  docs/manage/security/2-step-verification-users.md
  docs/manage/security/access-keys.md
  docs/manage/security/audit-indexes/audit-event-index.md
  docs/manage/security/create-allowlist-ip-cidr-addresses.md
  docs/manage/security/saml/integrate-google-iam-service.md
  docs/manage/security/saml/integrate-onelogin.md
  docs/manage/security/saml/integrate-sumo-logic-with-okta.md
  docs/manage/security/saml/integrate-with-bitium.md
  docs/manage/users-roles/users/change-users-email-address.md
  docs/manage/users-roles/users/delete-user.md
  docs/manage/users-roles/users/unlock-user-account.md
  static/img/data-forwarding/data-archiving.png
Labels: doc:minor edit, cla-signed

#3508 AWSO docs update
  docs/integrations/amazon-aws/api-gateway.md
  docs/integrations/amazon-aws/network-load-balancer.md
  docs/observability/aws/integrations/amazon-ecs.md
  docs/observability/aws/integrations/amazon-elasticache.md
  docs/observability/aws/integrations/amazon-rds.md
  docs/observability/aws/integrations/amazon-sns.md
  docs/observability/aws/integrations/amazon-sqs.md
  docs/observability/aws/integrations/aws-api-gateway.md
  docs/observability/aws/integrations/aws-application-load-balancer.md
  docs/observability/aws/integrations/aws-classic-load-balancer.md
  docs/observability/aws/integrations/aws-dynamodb.md
  docs/observability/aws/integrations/aws-ec2-host-metrics.md
  docs/observability/aws/integrations/aws-ec2-metrics.md
  docs/observability/aws/integrations/aws-lambda.md
  docs/observability/aws/integrations/aws-network-load-balancer.md
  docs/reuse/apps/app-install.md
  package.json
  yarn.lock
Labels: cla-signed

#3504 Event Analytics
  docs/search/get-started-with-search/search-page/event-analytics.md
  docs/search/get-started-with-search/search-page/log-level.md
  static/img/search/get-started-search/search-page/errors-spike.png
  static/img/search/get-started-search/search-page/event-analytics.png
  static/img/search/get-started-search/search-page/events_charts.png
  static/img/search/get-started-search/search-page/hide_events.png
Labels: cla-signed, do-not-merge

#3532 Resolution for common problems updated
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
Labels: cla-signed

#3537 Spot check for broken asterisks and indentation - Misc articles (Start Here, Alerts, Metrics, APM, and Observability)
  docs/alerts/scheduled-searches/create-email-alert.md
  docs/alerts/scheduled-searches/generate-cse-signals.md
  docs/alerts/webhook-connections/jira-service-desk.md
  docs/alerts/webhook-connections/new-relic.md
  docs/alerts/webhook-connections/pagerduty.md
  docs/alerts/webhook-connections/schedule-searches-webhook-connections.md
  docs/alerts/webhook-connections/signl4.md
  docs/apm/real-user-monitoring/configure-data-collection.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
  docs/contributing/create-doc.md
  docs/contributing/edit-doc.md
  docs/contributing/style-guide.md
  docs/get-started/apps-integrations.md
  docs/get-started/library.md
  docs/get-started/sumo-logic-ui.md
  docs/get-started/system-requirements.md
  docs/get-started/training-certification-faq.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/metrics/metrics-queries/map-charts.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/integrations/amazon-sns.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/observability/kubernetes/troubleshoot-with-explore.md
  docs/observability/root-cause-explorer.md
Labels: doc:minor edit, cla-signed

#3533 Move the metrics collection documents
  docs/integrations/app-development/jmx.md
  docs/metrics/kubernetes-metrics.md
  docs/send-data/kubernetes/collecting-metrics.md
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/v3/how-to-upgrade.md
  docs/send-data/kubernetes/v4/how-to-upgrade.md
  sidebars.ts
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-query.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-targets-error.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-targets-ok.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-ui.png
Labels: cla-signed

#3539 Update common problems section
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
Labels: cla-signed, hot🔥

#3540 Revert "Move the metrics collection documents"
  docs/integrations/app-development/jmx.md
  docs/metrics/kubernetes-metrics.md
  docs/send-data/kubernetes/collecting-metrics.md
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/v3/how-to-upgrade.md
  docs/send-data/kubernetes/v4/how-to-upgrade.md
  sidebars.ts
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-query.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-targets-error.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-targets-ok.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-ui.png
Labels: cla-signed

#3530 Data Management - Cloud Flex acct clarification
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
Labels: cla-signed, do-not-merge

#3542 Revert "Revert "Move the metrics collection documents""
  docs/integrations/app-development/jmx.md
  docs/metrics/kubernetes-metrics.md
  docs/send-data/kubernetes/collecting-metrics.md
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/v3/how-to-upgrade.md
  docs/send-data/kubernetes/v4/how-to-upgrade.md
  sidebars.ts
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-query.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-targets-error.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-targets-ok.png
  static/img/send-data/kubernetes-helm-chart/metrics/prometheus-ui.png
Labels: cla-signed

#3544 Spot check for broken asterisks and indentation - Send Data articles
  docs/api/search-job.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template-with-secured-sumo-endpoint.md
  docs/send-data/collect-from-other-data-sources/autosubscribe-arn-destination.md
  docs/send-data/collect-from-other-data-sources/aws-fargate-log-collection.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/collect-metrics-azure-monitor.md
  docs/send-data/collect-from-other-data-sources/collect-aws-lambda-logs-extension.md
  docs/send-data/collect-from-other-data-sources/collect-logs-sentinelone.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-vrealize-operations-manager.md
  docs/send-data/collect-from-other-data-sources/create-amazon-lambda-function.md
  docs/send-data/collect-from-other-data-sources/kubernetes-fluentd-plugin.md
  docs/send-data/collect-from-other-data-sources/vmware-airwatch-integration.md
  docs/send-data/collection/processing-rules/create-processing-rule.md
  docs/send-data/collector-faq.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/aws-cost-explorer-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dropbox-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/duo-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-webtx-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/palo-alto-cortex-xdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  docs/send-data/hosted-collectors/google-source/gcp-metrics-source.md
  docs/send-data/hosted-collectors/microsoft-source/ms-office-audit-source.md
  docs/send-data/hosted-collectors/webhook-sources/zoom.md
  docs/send-data/installed-collectors/collector-installation-reference/add-collector-linux-machine-image.md
  docs/send-data/installed-collectors/linux.md
  docs/send-data/installed-collectors/sources/collect-forwarded-events-windows-event-collector.md
  docs/send-data/installed-collectors/sources/docker-sources.md
  docs/send-data/installed-collectors/sources/local-file-source.md
  docs/send-data/installed-collectors/sources/local-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/local-windows-performance-monitor-log-source.md
  docs/send-data/installed-collectors/sources/preconfigure-machine-collect-remote-windows-performance-monitoring-logs.md
  docs/send-data/installed-collectors/sources/remote-file-source/index.md
  docs/send-data/installed-collectors/sources/remote-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/windows-active-directory-inventory-source.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: doc:minor edit, cla-signed

#3543 Update obsolete/broken SailPoint docs links
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sailpoint-source.md
Labels: cla-signed

#3546 Update "Windows Active Directory Inventory Source" article
  docs/send-data/installed-collectors/sources/windows-active-directory-inventory-source.md
  static/img/send-data/windows-ad-source-input.png
Labels: doc:update, cla-signed

#3548 Update Metrics DPM documentation
  docs/metrics/metrics-dpm.md
Labels: cla-signed

#3550 Update playbook actions limit
  docs/cloud-soar/automation.md
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/platform-services/automation-service/automation-service-app-central.md
  docs/platform-services/automation-service/automation-service-integrations.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/reuse/action-limits.md
  static/img/cloud-soar/appcentral.png
  static/img/cse/automation-service-app-central.png
Labels: doc:minor edit, cla-signed

#3549 Spot check for broken asterisks and image tag - Dashboards
  docs/dashboards/about.md
  docs/dashboards/create-dashboard-new.md
  docs/dashboards/dashboards-migration/changes-after-migration.md
  docs/dashboards/drill-down-to-discover-root-causes.md
  docs/dashboards/export-dashboard-new.md
  docs/dashboards/faq.md
  docs/dashboards/filter-template-variables.md
  docs/dashboards/link-dashboards.md
  docs/dashboards/locate-deviations-time-series.md
  docs/dashboards/panels/area-charts.md
  docs/dashboards/panels/bar-charts.md
  docs/dashboards/panels/bubble-charts.md
  docs/dashboards/panels/column-charts.md
  docs/dashboards/panels/combo-charts.md
  docs/dashboards/panels/index.md
  docs/dashboards/panels/line-charts.md
  docs/dashboards/panels/map-charts.md
  docs/dashboards/panels/markdown-syntax.md
  docs/dashboards/panels/modify-chart.md
  docs/dashboards/panels/pie-charts.md
  docs/dashboards/panels/scatter-charts.md
  docs/dashboards/panels/single-value-charts.md
  docs/dashboards/panels/table-charts.md
  docs/dashboards/scheduled-report.md
  docs/dashboards/set-custom-time-ranges.md
  docs/dashboards/share-dashboard-new.md
Labels: cla-signed

#3551 CONN-1286 - Update output field description
  docs/cloud-soar/cloud-soar-integration-framework.md
Labels: doc:update, cla-signed

#3552 INVS-1978 - Threat indicators format
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:new, cla-signed

#3557 Fix formatting - asterisks only
  docs/integrations/global-intelligence/nginx.md
  docs/integrations/microsoft-azure/iis-7.md
  docs/integrations/pci-compliance/linux.md
  docs/integrations/saas-cloud/pagerduty-v2.md
  docs/integrations/saas-cloud/pagerduty-v3.md
  docs/integrations/saas-cloud/workday.md
  docs/integrations/security-threat-detection/barracuda-waf.md
  docs/integrations/security-threat-detection/cylance.md
  docs/integrations/security-threat-detection/f5-big-ip-ltm.md
  docs/integrations/security-threat-detection/keeper-security.md
  docs/integrations/security-threat-detection/trend-micro-deep-security.md
  docs/integrations/security-threat-detection/twistlock.md
  docs/integrations/security-threat-detection/vmware-carbon-black.md
  docs/integrations/security-threat-detection/zscaler-private-access.md
  docs/integrations/sumo-apps/cse.md
  docs/integrations/sumo-apps/security-analytics.md
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx-plus.md
  docs/integrations/web-servers/nginx.md
  docs/integrations/web-servers/varnish.md
Labels: cla-signed

#3559 Training portal update
  docs/get-started/quickstart.md
  docs/get-started/sumo-logic-ui.md
  docs/get-started/training-certification-faq.md
  static/img/get-started/WTS_Home-Search-icons.png
  static/img/get-started/Welcome_learn.png
  static/img/get-started/certifications.gif
  static/img/get-started/certifications.png
  static/img/get-started/ui/TUI_Left_Nav.png
  static/img/get-started/ui/TUI_NavBar_Hide.png
  static/img/get-started/ui/TUI_NavBar_Show.png
  static/img/get-started/ui/TUI_Search_Details.png
  static/img/get-started/ui/WTS_UI_Home_landing-page.png
  static/img/get-started/ui/WTS_UI_Search-Metrics-LiveTail.png
Labels: doc:update, cla-signed

#3562 Move collecting kubernetes events document
  docs/send-data/kubernetes/collecting-kubernetes-events.md
  docs/send-data/kubernetes/install-helm-chart.md
  sidebars.ts
Labels: cla-signed

#3555 Collector Version 19.478-2 - Release notes
  blog-collector/2024-01-25.md
Labels: cla-signed

#3564 January 25, 2024 - Content Release
  blog-csoar/2024-01-25-content.md
Labels: doc:new, cla-signed

#3556 AWS RDS - adding postgresql dashboard and collection instruction
  docs/integrations/amazon-aws/rds.md
  static/img/integrations/amazon-aws/Amazon-RDS-PostgreSQL-Logs-Errors.png
  static/img/integrations/amazon-aws/Amazon-RDS-PostgreSQL-Logs-Overview.png
  static/img/integrations/amazon-aws/Amazon-RDS-PostgreSQL-Logs-Query-Execution-Time.png
  static/img/integrations/amazon-aws/Amazon-RDS-PostgreSQL-Logs-Security.png
  static/img/integrations/amazon-aws/Amazon-RDS-PostgreSQL-Logs-Slow-Query-Details.png
  static/img/integrations/amazon-aws/Amazon-RDS-PostgreSQL-Logs-Slow-Query-Overview.png
Labels: cla-signed

#3563 Azure Metrics Doc collections
  docs/integrations/microsoft-azure/sql.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/collect-metrics-azure-monitor.md
  static/img/send-data/azure-metrics/adddiagnosticsetting.png
  static/img/send-data/azure-metrics/azure-template-deploy.png
  static/img/send-data/azure-metrics/azure-template-deploy2.png
  static/img/send-data/azure-metrics/azure-triggers.png
  static/img/send-data/azure-metrics/containers.png
  static/img/send-data/azure-metrics/custom-deployemnt.png
  static/img/send-data/azure-metrics/deployment_successed.png
  static/img/send-data/azure-metrics/diagnosticsetting.png
  static/img/send-data/azure-metrics/event-hub-messages.png
  static/img/send-data/azure-metrics/microsofttemplate_resource.png
  static/img/send-data/azure-metrics/notification.png
  static/img/send-data/azure-metrics/pipeline-custom-deployment.png
  static/img/send-data/azure-metrics/resource.png
  static/img/send-data/azure-metrics/smappinsightfailures.png
  static/img/send-data/azure-metrics/storageaccount.png
  static/img/send-data/azure-metrics/sumolabsmetricendpoint.png
  static/img/send-data/azuresqldatabasediagnosticsetting.png
Labels: doc:update, cla-signed

#3568 integration doc update
  docs/platform-services/automation-service/app-central/integrations/onelogin.md
Labels: cla-signed

#3567 integration doc update
  docs/platform-services/automation-service/app-central/integrations/lacework.md
Labels: doc:minor edit, cla-signed

#3572 Update alert-variables.md - Add {{AlertGroup}}
  docs/alerts/monitors/alert-variables.md
Labels: cla-signed

#3570 Add links to 'Integrations in App Central'
  docs/cloud-soar/automation.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/platform-services/automation-service/app-central/index.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/automation-service-integrations.md
  sidebars.ts
Labels: doc:update, cla-signed

#3573 Add links to the Cloud SIEM Content Catalog
  docs/cse/cloud-siem-content-catalog.md
  docs/cse/ingestion/products-with-log-mappings.md
  docs/cse/ingestion/view-mappers-for-product.md
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/cse-built-in-rules.md
  docs/cse/rules/normalized-threat-rules.md
  docs/cse/schema/attributes-map-to-records.md
  docs/cse/schema/create-structured-log-mapping.md
  docs/cse/schema/cse-record-types.md
  docs/cse/schema/parser-editor.md
  docs/cse/schema/schema-attributes.md
  sidebars.ts
Labels: doc:update, cla-signed

#3566 Increase Algolia search bar width
  src/css/sumo.scss
Labels: cla-signed

#3534 Add log collection document for the Helm Chart
  docs/send-data/kubernetes/collecting-events.md
  docs/send-data/kubernetes/collecting-logs.md
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/troubleshoot-collection.md
  sidebars.ts
Labels: cla-signed

#3575 Fix formatting indentation (Docusaurus v3)
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/config.md
  docs/integrations/amazon-aws/lambda.md
  docs/integrations/app-development/github.md
  docs/integrations/app-development/jfrog-artifactory.md
  docs/integrations/app-development/opentelemetry/jira-opentelemetry.md
  docs/integrations/app-development/opentelemetry/puppet-opentelemetry.md
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/containers-orchestration/opentelemetry/kafka-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/containers-orchestration/strimzi-kafka.md
  docs/integrations/containers-orchestration/vmware-legacy.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mariadb-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/integrations/databases/oracle.md
  docs/integrations/databases/redis.md
  docs/integrations/hosts-operating-systems/host-process-metrics.md
  docs/integrations/hosts-operating-systems/linux.md
  docs/integrations/microsoft-azure/iis-7.md
  docs/integrations/microsoft-azure/kubernetes.md
  docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
  docs/integrations/microsoft-azure/office-365.md
  docs/integrations/microsoft-azure/performance.md
  docs/integrations/microsoft-azure/sql-server.md
  docs/integrations/pci-compliance/opentelemetry/windows-json-opentelemetry.md
  docs/integrations/saas-cloud/cisco-meraki-c2c.md
  docs/integrations/saas-cloud/docusign.md
  docs/integrations/saas-cloud/dropbox.md
  docs/integrations/saas-cloud/fastly.md
  docs/integrations/saas-cloud/gmail-tracelogs.md
  docs/integrations/saas-cloud/knowbe4.md
  docs/integrations/saas-cloud/microsoft-exchange-trace-logs.md
  docs/integrations/saas-cloud/proofpoint-tap.md
  docs/integrations/saas-cloud/qualys-vmdr.md
  docs/integrations/saas-cloud/sentinelone.md
  docs/integrations/saml/auth0.md
  docs/integrations/saml/okta.md
  docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection.md
  docs/integrations/security-threat-detection/imperva-incapsula.md
  docs/integrations/security-threat-detection/observable-networks.md
  docs/integrations/security-threat-detection/palo-alto-networks-6.md
  docs/integrations/security-threat-detection/palo-alto-networks-8.md
  docs/integrations/security-threat-detection/sailpoint.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/opentelemetry/apache-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/manage/partitions-data-tiers/infrequent-tier-dashboard-support.md
  docs/manage/partitions-data-tiers/infrequent-tier-search.md
  docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
Labels: cla-signed

#3577 Docusaurus v3 numbering
  blog-service/2016/12-31.md
  blog-service/2017/12-31.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/scheduled-searches/schedule-search.md
  docs/alerts/webhook-connections/aws-lambda.md
  docs/alerts/webhook-connections/hipchat.md
  docs/alerts/webhook-connections/jira-cloud.md
  docs/alerts/webhook-connections/microsoft-teams.md
  docs/alerts/webhook-connections/opsgenie.md
  docs/beta/index.md
  docs/get-started/sumo-logic-ui.md
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
  docs/integrations/amazon-aws/aurora-postgresql-ulm.md
  docs/integrations/amazon-aws/elastic-load-balancing.md
  docs/integrations/amazon-aws/global-intelligence-cloudtrail-devops.md
  docs/integrations/amazon-aws/global-intelligence-guardduty.md
  docs/integrations/containers-orchestration/activemq.md
  docs/integrations/containers-orchestration/rabbitmq.md
  docs/integrations/databases/cassandra.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/elasticsearch.md
  docs/integrations/databases/mariadb.md
  docs/integrations/databases/memcached.md
  docs/integrations/databases/mongodb-atlas.md
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/oracle.md
  docs/integrations/databases/postgresql.md
  docs/integrations/databases/redis.md
  docs/integrations/global-intelligence/nginx.md
  docs/integrations/hosts-operating-systems/host-metrics.md
  docs/integrations/hosts-operating-systems/linux.md
  docs/integrations/microsoft-azure/iis-7.md
  docs/integrations/pci-compliance/palo-alto-networks-9.md
  docs/integrations/saas-cloud/akamai-cloud-monitor.md
  docs/integrations/saml/okta.md
  docs/integrations/security-threat-detection/cylance.md
  docs/integrations/security-threat-detection/netskope-legacy-collection.md
  docs/integrations/security-threat-detection/netskope.md
  docs/integrations/security-threat-detection/palo-alto-networks-6.md
  docs/integrations/security-threat-detection/palo-alto-networks-8.md
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/nginx-legacy.md
  docs/integrations/web-servers/nginx-plus.md
  docs/integrations/web-servers/nginx.md
  docs/integrations/web-servers/squid-proxy.md
  docs/integrations/web-servers/varnish.md
  docs/search/search-cheat-sheets/general-search-examples.md
  docs/send-data/kubernetes/install-helm-chart.md
Labels: cla-signed

#3582 Classic Dashboards loose ends
  docs/dashboards/faq.md
  docs/metrics/index.md
  docs/metrics/metrics-queries/metrics-explorer.md
  sidebars.ts
Labels: cla-signed

#3578 Docusaurus 3.1.1
  blog-service/2020/12-31.md
  blog-service/2022/12-31.md
  docs/integrations/sumo-apps/security-analytics.md
  docs/manage/content-sharing/admin-mode.md
  docs/observability/sdo/set-up-sdo/sdo-setup-with-terraform-script.md
  package.json
  yarn.lock
Labels: cla-signed

#3583 GCP docs minor update
  docs/integrations/google/cloud-functions.md
  docs/integrations/google/cloud-sql.md
  docs/integrations/google/compute-engine.md
Labels: cla-signed

#3587 Fix ncat link in syslog doc
  docs/send-data/installed-collectors/sources/syslog-source.md
Labels: cla-signed

#3579 Cross-reference transactionize/merge op use case
  docs/search/search-query-language/transaction-analytics/transactionize-operator.md
Labels: cla-signed

#3565 More updates to the threat intelligence indicators beta article
  docs/platform-services/threat-intelligence-indicators.md
  static/img/platform-services/threat-indicators-in-cloud-siem-ui.png
Labels: doc:update, cla-signed

#3589 Troubleshooting added for AWS Observability hierarchy
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  static/img/observability/hierarchy.png
  static/img/observability/metric-query.png
Labels: cla-signed

#3584 Event analytics doc update
  docs/search/get-started-with-search/search-page/event-analytics.md
  static/img/search/get-started-search/search-page/gathering_events.png
  static/img/search/get-started-search/search-page/hide_events_grey.png
Labels: cla-signed

#3590 Added 20240130 changelog
  blog-csoar/2024-01-30-application-update.md
Labels: cla-signed

#3592 New screenshot for Metrics DPM beta article
  docs/metrics/metrics-dpm.md
  static/img/metrics/metrics-dpm.png
Labels: doc:update, cla-signed

#3591 Update examples in Unified Threat Intel beta article
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#3593 Added section for explain how deal with playbook import / export in Cloud Soar -- automation section
  docs/cloud-soar/automation.md
  static/img/cloud-soar/export-playbook.png
  static/img/cloud-soar/import-playbook-modal.png
  static/img/cloud-soar/import-playbook.png
Labels: cla-signed

#3594 App Central integration - Darktrace
  docs/platform-services/automation-service/app-central/integrations/darktrace.md
Labels: cla-signed

#3595 App Central integration - Chronicle
  docs/platform-services/automation-service/app-central/integrations/chronicle.md
  docs/platform-services/automation-service/app-central/integrations/gmail-multiple-mailbox.md
  docs/platform-services/automation-service/app-central/integrations/gmail.md
  docs/platform-services/automation-service/app-central/integrations/google-admin.md
  docs/platform-services/automation-service/app-central/integrations/google-alert-center.md
  docs/platform-services/automation-service/app-central/integrations/google-drive.md
  docs/platform-services/automation-service/app-central/integrations/google-safe-browsing.md
  static/img/platform-services/automation-service/app-central/logos/gmail.png
  static/img/platform-services/automation-service/app-central/logos/google-admin.png
  static/img/platform-services/automation-service/app-central/logos/google-alert-center.png
  static/img/platform-services/automation-service/app-central/logos/google-drive.png
  static/img/platform-services/automation-service/app-central/logos/google-safe-browsing.png
  static/img/platform-services/automation-service/app-central/logos/google.png
Labels: cla-signed

#3596 Update threat indicators section in "Threat Intelligence Indicators" article
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#3599 Redirect for "Cloud Infrastructure Security for AWS - Preview" release note
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#3600 Fix for Issue #3553
  docs/manage/security/saml/integrate-google-iam-service.md
Labels: doc:minor edit, cla-signed
