Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-12, with the labels that each got.

#4824 Azure Cosmos DB for PostgreSQL
  blog-service/2024-11-28-apps.md
  docs/integrations/microsoft-azure/azure-cosmos-db-for-postgresql.md
  docs/integrations/microsoft-azure/azure-database-for-postgresql.md
  static/img/send-data/export-logs-diagnostic-settings-cosmosdbforpostgresql.png
  static/img/send-data/export-metrics-diagnostic-settings-cosmosdbforpostgresql.png
Labels: cla-signed

#4788 DOCS-551 Copilot GA (Dec 2)
  blog-service/2024-12-02-copilot.md
  docs/search/copilot.md
  static/img/search/copilot/ga-releasenote.png
  static/img/search/copilot/resume-convo-history2.png
Labels: cla-signed

#4769 Added new actions in crowdstrike falcon
  docs/platform-services/automation-service/app-central/integrations/crowdstrike-falcon.md
Labels: cla-signed, do-not-merge

#4800 CONN-3897 Enable universal connector source with CID 25633
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/universal-connector-source.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4821 Created new doc for Digital Guardian ARC - Apps
  blog-service/2024-12-02-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/digital-guardian-arc.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4789 Microsoft defender for cloud
  blog-service/2024-12-02-apps2.md
  cid-redirects.json
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/microsoft-defender-for-cloud.md
  docs/integrations/product-list/product-list-m-z.md
  sidebars.ts
  static/img/integrations/microsoft-azure/data-explorer.png
  static/img/integrations/microsoft-azure/event-hub-instance-blade.png
  static/img/integrations/microsoft-azure/live-tailing.png
  static/img/integrations/microsoft-azure/microsoft-defender-for-cloud.png
  static/img/integrations/microsoft-azure/validate-microsoft-defender-alerts.png
Labels: doc:new, cla-signed

#4828 Update instructions to delete indicators
  docs/platform-services/threat-intelligence-indicators.md
  static/img/platform-services/threat-intelligence-delete-indicators.png
Labels: doc:update, cla-signed

#4829 DOCS-575 - Update 'where' rule syntax element
  docs/cse/rules/cse-rules-syntax.md
Labels: doc:update, cla-signed

#4830 Fix error in Cloud SIEM intro article
  docs/cse/introduction-to-cloud-siem.md
Labels: cla-signed

#4831 Remove Source Template enhancements
  blog-service/2024-11-28-apps.md
Labels: cla-signed

#4825 Note added to AWS Observability docs
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#4826 Update Scheduled Views index page
  docs/manage/scheduled-views/index.md
Labels: cla-signed

#4818 DOCS-578 - Log Query Assist edits per Search team
  docs/search/query-assist.md
  static/img/search/get-started-search/query-assist-preview1.gif
Labels: cla-signed, do-not-merge

#4834 Update microsoft-defender-for-cloud.md
  docs/integrations/microsoft-azure/microsoft-defender-for-cloud.md
Labels: cla-signed

#4837 New Integration Sumo Logic Notification By Microsoft
  docs/integrations/product-list/product-list-m-z.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-microsoft.md
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-microsoft/sumo-logic-notifications-by-microsoft-1.png
Labels: cla-signed

#4832 Manage Subscription updates
  blog-service/2023/12-31.md
  blog-service/2024-03-04-manage.md
  docs/get-started/sign-up.md
  docs/integrations/sumo-apps/data-volume.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/manage/manage-subscription/close-cancel-sumo-account.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/manage/manage-subscription/index.md
  docs/manage/manage-subscription/manage-billing-information.md
  docs/manage/manage-subscription/manage-org-settings.md
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
  docs/manage/manage-subscription/sumo-logic-flex-accounts.md
  docs/manage/manage-subscription/upgrade-cloud-flex-legacy-account.md
  docs/manage/manage-subscription/upgrade-sumo-logic-credits-account.md
  docs/reuse/account-credit.md
  sidebars.ts
  static/img/manage/account/account-details-credit-usage-flex.png
  static/img/manage/subscriptions/Manage_Organization_options.png
  static/img/manage/subscriptions/confirm-payment-method.png
  static/img/manage/subscriptions/confirm-upgrade.png
  static/img/manage/subscriptions/current-levels.png
  static/img/manage/subscriptions/current-plan.png
  static/img/manage/subscriptions/customize-plan-new-levels.png
  static/img/manage/subscriptions/enter-payment-method.png
  static/img/manage/subscriptions/manage-plan-upgrade-to-essentials.png
  static/img/manage/subscriptions/new-levels.png
  static/img/manage/subscriptions/upgrade-success.png
Labels: cla-signed

#4838 re:Invent banner and misc get-started fixes
  docs/get-started/ai-machine-learning.md
  docs/get-started/sumo-logic-ui-classic.md
  docs/get-started/sumo-logic-ui.md
  docs/manage/manage-subscription/cloud-flex-legacy-accounts.md
  docs/manage/manage-subscription/index.md
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
  docs/manage/manage-subscription/sumo-logic-flex-accounts.md
  docs/manage/manage-subscription/upgrade-cloud-flex-legacy-account.md
  docusaurus.config.js
  sidebars.ts
Labels: cla-signed, hot🔥

#4745 Metrics anomaly detection fix
  blog-service/2023/12-31.md
  docs/alerts/monitors/create-monitor.md
  static/img/alerts/monitors/anomaly-detection-input.png
  static/img/alerts/monitors/config-resolution-window-2.png
  static/img/alerts/monitors/edit-recover-settings.png
  static/img/alerts/monitors/edit-recovery-settings1.png
  static/img/alerts/monitors/logs-static-missing.png
  static/img/alerts/monitors/logs-trigger-type.png
  static/img/alerts/monitors/metrics-anomaly-critical.png
  static/img/alerts/monitors/metrics-anomaly-missing.png
  static/img/alerts/monitors/metrics-outlier-missing.png
  static/img/alerts/monitors/metrics-query.png
  static/img/alerts/monitors/metrics-static-missing.png
  static/img/alerts/monitors/metricsmonitor.png
  static/img/alerts/monitors/monitor-anomaly-logs.png
  static/img/alerts/monitors/outlier-detection-input.png
Labels: cla-signed, do-not-merge

#4839 Added documentation for azure api management
  docs/integrations/microsoft-azure/azure-api-management.md
  static/img/integrations/microsoft-azure/azure-api-management-services.png
  static/img/send-data/azure-apimanagement-logs.png
  static/img/send-data/azure-apimanagement-metrics.png
Labels: cla-signed

#4843 Added the new content in Google Chat
  docs/platform-services/automation-service/app-central/integrations/google-chat.md
  static/img/platform-services/automation-service/app-central/integrations/google-chat/google-chat-1.png
  static/img/platform-services/automation-service/app-central/integrations/google-chat/google-chat-2.png
  static/img/platform-services/automation-service/app-central/integrations/google-chat/google-chat-3.png
Labels: cla-signed

#4850 Cloud SIEM content release notes for December 6, 2024
  blog-cse/2024-12-06-content.md
Labels: cla-signed

#4833 compareCIDRPrefix and getCIDRPrefix Operators Behavior Change
  blog-service/2024-12-09-search.md
  docs/search/search-query-language/search-operators/cidr.md
Labels: cla-signed, do-not-merge

#4848 Update data-volume.md
  docs/integrations/sumo-apps/data-volume.md
Labels: cla-signed

#4842 Update search-audit-index.md
  docs/manage/security/audit-indexes/search-audit-index.md
Labels: cla-signed

#4847 Remove credits used information from DPM page as we do not display it…
  docs/metrics/metrics-dpm.md
Labels: cla-signed

#4849 New doc- CrowdStrike Falcon FileVantage (Apps)
  blog-service/2024-12-09-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/crowdstrike-falcon-filevantage.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#4806 Remove beta from transformation Rules API
  docs/api/metrics-transformation-rules.md
Labels: doc:update, cla-signed, do-not-merge

#4844 Update mandiant-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mandiant-threat-intel-source.md
Labels: cla-signed

#4852 SUMO-251499: Adding monitor's information to OTEL Apps Set1
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/memcached-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
Labels: cla-signed

#4854 Update macos.md
  docs/send-data/opentelemetry-collector/install-collector/macos.md
Labels: cla-signed

#4846 DOCS-589 - Clarify Terraform support for sched searches
  docs/alerts/difference-from-scheduled-searches.md
Labels: cla-signed

#4857 Swap out re:Invent banner with Copilot
  docusaurus.config.js
Labels: cla-signed

#4859 CONN-3703 Add TAXII Recommended Configurations
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
  static/files/c2c/taxii-1/alien-vault-config.json
  static/files/c2c/taxii-1/recorded-future-config.json
  static/files/c2c/taxii-2/cisa-dhs-config.json
  static/files/c2c/taxii-2/cybersixgill-config.json
  static/files/c2c/taxii-2/dragos-config.json
  static/files/c2c/taxii-2/eclecticiq-config.json
  static/files/c2c/taxii-2/palo-alto-unit42-config.json
  static/files/c2c/taxii-2/recorded-future-config.json
Labels: cla-signed

#4856 README edits
  README.md
Labels: cla-signed

#4773 DOCS-42 - Multi-Insight list page section
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
Labels: doc:new, cla-signed

#4862 DOCS-588 - Add Flex app to product list
  docs/integrations/product-list/product-list-m-z.md
Labels: cla-signed

#4864 New DOCS-569
  cid-redirects.json
  docs/cse/get-started-with-cloud-siem/cloud-siem-content-catalog.md
  docs/cse/get-started-with-cloud-siem/cloud-siem-ui.md
  docs/cse/get-started-with-cloud-siem/index.md
  docs/cse/get-started-with-cloud-siem/intro-for-administrators.md
  docs/cse/get-started-with-cloud-siem/intro-for-analysts.md
  docs/cse/index.md
  docs/cse/introduction-to-cloud-siem.md
  docs/integrations/product-list/index.md
  sidebars.ts
  static/img/cse/cloud-siem-hud.png
  static/img/cse/intro-admin-playbook-example (1).png
  static/img/cse/intro-admin-playbook-example.png
  static/img/cse/intro-blank-rule-template.png
  static/img/cse/intro-cloud-siem-data-pipeline.png
  static/img/cse/intro-cloud-siem-signals.png
  static/img/cse/intro-context-action-icon.png
  static/img/cse/intro-data-flow.png
  static/img/cse/intro-day-in-the-life-cloud-siem.png
  static/img/cse/intro-filter-entities.png
  static/img/cse/intro-filter-rules.png
  static/img/cse/intro-forward-data.gif
  static/img/cse/intro-hud.gif
  static/img/cse/intro-ingest-the-right-data.png
  static/img/cse/intro-insight-example-investigation.png
  static/img/cse/intro-insight-example.png
  static/img/cse/intro-log-search-context-action.png
  static/img/cse/intro-logs-into-records.png
  static/img/cse/intro-records-to-signals.png
  static/img/cse/intro-select-timeframe.png
  static/img/cse/intro-signal-example.png
Labels: doc:new, cla-signed

#4778 DOCS-559 Self-service checkout
  blog-service/2024-12-11-manage.md
  docs/get-started/sign-up.md
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
  docs/manage/manage-subscription/upgrade-sumo-logic-credits-account.md
  static/img/manage/subscriptions/confirm-upgrade-2.png
  static/img/manage/subscriptions/essentials-landing-page.png
Labels: cla-signed, do-not-merge

#4865 Update deletion-requests.md
  docs/manage/deletion-requests.md
Labels: cla-signed

#4560 Update crowdstrike-falcon-endpoint-protection.md
  docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection.md
Labels: cla-signed, do-not-merge

#4860 Release note for New UI enhancements
  blog-service/2024-12-11-new-ui.md
Labels: cla-signed, do-not-merge

#4872 Added the new content Sumo Logic Log Analytics
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-log-analytics.md
Labels: cla-signed

#4868 DOCS-594 - New integration in the Automation Service
  docs/platform-services/automation-service/automation-service-integrations.md
  static/img/platform-services/automation-service/new-integration-dialog.png
Labels: doc:new, cla-signed

#4871 Universal Collector - Release note
  blog-service/2024-12-12-collection.md
Labels: cla-signed, do-not-merge

#4873 Dragos C2C (Source)
  blog-service/2024-12-16-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/dragos/example.json
  static/files/c2c/dragos/example.tf
  static/img/send-data/dragos-logo.png
Labels: doc:new, cla-signed, do-not-merge

#4883 CONN-3980 Recorded Future - Vendor Requested Changes
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
  static/files/c2c/taxii-1/recorded-future-config.json
  static/files/c2c/taxii-2/recorded-future-config.json
Labels: cla-signed

#4876 SUMO-251500: Adding monitor's information to OTEL Apps Set2
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/opentelemetry/mariadb-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-linux-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/squid-proxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/varnish-opentelemetry.md
Labels: cla-signed

#4885 VMware Workspace One - C2C
  blog-service/2024-12-17-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/vmware-workspace-one-source.md
  sidebars.ts
  static/files/c2c/vmware-workspace-one/example.json
  static/files/c2c/vmware-workspace-one/example.tf
  static/img/send-data/vmware_workspace_one.png
Labels: doc:new, cla-signed, do-not-merge

#4888 Update aws-kinesis-firehose-metrics-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source.md
Labels: cla-signed

#4887 DOCS-587 - Make terms lowercase in Cloud SIEM - Getting started, records, ingestion, and rules sections
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/cse/get-started-with-cloud-siem/cloud-siem-content-catalog.md
  docs/cse/get-started-with-cloud-siem/cloud-siem-ui.md
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
  docs/cse/get-started-with-cloud-siem/index.md
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
  docs/cse/get-started-with-cloud-siem/onboarding-checklist-cse.md
  docs/cse/ingestion/cse-ingestion-best-practices.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/carbon-black.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/check-point-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/cisco-asa.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/cisco-meraki.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/corelight-zeek.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/fortigate-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/kemp-loadmaster.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/linux-os-syslog.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/nginx-access-logs.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/osquery.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/symantec-proxy-secure-gateway-blue-coat-proxy.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/symantec-proxy-secure-gateway.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/zscaler-nss.md
  docs/cse/ingestion/sumo-logic-ingest-mapping.md
  docs/cse/ingestion/view-mappers-for-product.md
  docs/cse/records-signals-entities-insights/about-signal-suppression.md
  docs/cse/records-signals-entities-insights/configure-custom-insight.md
  docs/cse/records-signals-entities-insights/configure-entity-lookup-table.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/cse/records-signals-entities-insights/create-custom-entity-type.md
  docs/cse/records-signals-entities-insights/entity-criticality.md
  docs/cse/records-signals-entities-insights/global-intelligence-security-insights.md
  docs/cse/records-signals-entities-insights/index.md
  docs/cse/records-signals-entities-insights/search-cse-records-in-sumo.md
  docs/cse/records-signals-entities-insights/set-insight-generation-window-threshold.md
  docs/cse/records-signals-entities-insights/tags-insights-signals-entities-rules.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
  docs/cse/records-signals-entities-insights/view-records-signal.md
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/before-writing-custom-rule.md
  docs/cse/rules/cse-built-in-rules.md
  docs/cse/rules/cse-rules-syntax.md
  docs/cse/rules/import-yara-rules.md
  docs/cse/rules/index.md
  docs/cse/rules/insight-trainer.md
  docs/cse/rules/normalized-authentication-rules.md
  docs/cse/rules/normalized-threat-rules.md
  docs/cse/rules/rule-tuning-expressions.md
  docs/cse/rules/tailor-global-rule.md
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-chain-rule.md
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-match-rule.md
  docs/cse/rules/write-outlier-rule.md
  docs/cse/rules/write-threshold-rule.md
Labels: doc:update, cla-signed, do-not-merge

#4890 Update dedup.md - Add supported content
  docs/search/search-query-language/search-operators/dedup.md
Labels: cla-signed

#4845 Intel471 threat intel c2 c
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/intel-471-threat-intel-source.md
  sidebars.ts
  static/files/c2c/intel471-threat-intel/example.json
  static/files/c2c/intel471-threat-intel/example.tf
  static/img/integrations/security-threat-detection/intel471-threat-intel.png
Labels: doc:new, cla-signed, do-not-merge

#4889 DOCS-587 - Make terms lowercase in Cloud SIEM - Schema, sensors, integrations, match lists, automation, and administration sections
  docs/cse/administration/create-a-custom-tag-schema.md
  docs/cse/administration/create-cse-actions.md
  docs/cse/administration/create-cse-context-actions.md
  docs/cse/administration/create-custom-threat-intel-source.md
  docs/cse/administration/create-use-network-blocks.md
  docs/cse/administration/cse-apis.md
  docs/cse/administration/cse-audit-logging.md
  docs/cse/administration/cse-data-retention.md
  docs/cse/administration/cse-user-accounts-and-roles.md
  docs/cse/administration/custom-inventory-sources.md
  docs/cse/administration/index.md
  docs/cse/administration/inventory-sources-and-data.md
  docs/cse/administration/manage-custom-insight-resolutions.md
  docs/cse/administration/manage-custom-insight-statuses.md
  docs/cse/administration/mitre-coverage.md
  docs/cse/administration/save-inventory-data-lookup-table.md
  docs/cse/administration/using-sensor-zones.md
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/cse/automation/index.md
  docs/cse/integrations/configuring-threatq-source-in-cse.md
  docs/cse/integrations/enable-virustotal-enrichment.md
  docs/cse/integrations/enrichments-and-indicators.md
  docs/cse/integrations/index.md
  docs/cse/integrations/insight-enrichment-server.md
  docs/cse/integrations/integrate-cse-with-taxii-feed.md
  docs/cse/integrations/security-incident-response-integration.md
  docs/cse/match-lists-suppressed-lists/create-match-list.md
  docs/cse/match-lists-suppressed-lists/custom-match-list-columns.md
  docs/cse/match-lists-suppressed-lists/index.md
  docs/cse/match-lists-suppressed-lists/match-fields-reference.md
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
  docs/cse/match-lists-suppressed-lists/suppressed-lists.md
  docs/cse/schema/attributes-map-to-records.md
  docs/cse/schema/create-structured-log-mapping.md
  docs/cse/schema/cse-normalized-classification.md
  docs/cse/schema/cse-record-types.md
  docs/cse/schema/field-mapping-security-event-sources.md
  docs/cse/schema/index.md
  docs/cse/schema/parser-editor.md
  docs/cse/schema/parser-troubleshooting-tips.md
  docs/cse/schema/parsing-language-reference-guide.md
  docs/cse/schema/record-processing-pipeline.md
  docs/cse/schema/username-and-hostname-normalization.md
  docs/cse/sensors/index.md
  docs/cse/sensors/ingest-zeek-logs.md
  docs/cse/sensors/network-sensor-deployment-guide.md
  docs/cse/sensors/network-sensor-troubleshooting.md
  docs/cse/sensors/sensor-download-locations.md
  docs/reuse/cloud-siem-network-sensor-eol.md
Labels: doc:update, cla-signed

#4878 Fastly formatting fixes
  .clabot
  docs/integrations/saas-cloud/fastly.md
Labels: cla-signed

#4869 DOCS-362 - Log Search Behavior Insights refactor
  blog-service/2021/12-31.md
  cid-redirects.json
  docs/alerts/monitors/alert-response-faq.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/overview.md
  docs/contributing/glossary.md
  docs/dashboards/restricted-operators-dashboards.md
  docs/get-started/ai-machine-learning.md
  docs/integrations/microsoft-azure/windows-legacy.md
  docs/manage/manage-subscription/cloud-flex-legacy-accounts.md
  docs/observability/root-cause-explorer.md
  docs/search/behavior-insights/index.md
  docs/search/behavior-insights/logcompare.md
  docs/search/behavior-insights/logexplain.md
  docs/search/behavior-insights/logreduce/detect-patterns-with-logreduce.md
  docs/search/behavior-insights/logreduce/index.md
  docs/search/behavior-insights/logreduce/influence-the-logreduce-outcome.md
  docs/search/behavior-insights/logreduce/logreduce-keys.md
  docs/search/behavior-insights/logreduce/logreduce-operator.md
  docs/search/behavior-insights/logreduce/logreduce-values.md
  docs/search/behavior-insights/logreduce/understand-the-logreduce-relevance-column.md
  docs/search/get-started-with-search/search-page/navigate-through-search-results.md
  docs/search/index.md
  docs/search/search-cheat-sheets/general-search-examples.md
  docs/search/search-cheat-sheets/log-operators.md
  docs/search/search-query-language/group-aggregate-operators/overview.md
  docs/search/time-compare.md
  i18n/ja/alerts/alerts/monitors/alert-response-faq.md
  i18n/ja/alerts/alerts/monitors/alert-response.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4881 Add Wistia example to style guide
  docs/contributing/style-guide.md
Labels: doc:update, cla-signed

#4891 Change date on release note for RBAC for Indexes
  blog-service/2024-10-14-manage.md
Labels: doc:minor edit, cla-signed

#4896 Add sumologic_volume to list of audit data filters
  blog-service/2023/12-31.md
  docs/manage/security/audit-indexes/index.md
  docs/manage/users-roles/roles/create-manage-roles.md
Labels: doc:minor edit, cla-signed

#4895 Add beta threat intel sources to beta threat intel article
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#4874 DOCS-604 - Test Wistia video embedding
  docs/cse/administration/mitre-coverage.md
Labels: doc:minor edit, cla-signed

#4892 Azure Service Bus Documentation
  docs/integrations/microsoft-azure/azure-api-management.md
  docs/integrations/microsoft-azure/azure-service-bus.md
  static/img/integrations/microsoft-azure/Azure-Service-Bus-Tag-Metric-Fields.png
  static/img/send-data/azure-service-bus-metrics.png
  static/img/send-data/azure-servicebus-logs.png
Labels: cla-signed

#4880 Appflow updated for V2 apps
  docs/integrations/saas-cloud/1password.md
  docs/integrations/saas-cloud/abnormal-security.md
  docs/integrations/saas-cloud/airtable.md
  docs/integrations/saas-cloud/atlassian.md
  docs/integrations/saas-cloud/box.md
  docs/integrations/saas-cloud/cato-networks.md
  docs/integrations/saas-cloud/cisco-meraki-c2c.md
  docs/integrations/saas-cloud/crowdstrike-fdr-host-inventory.md
  docs/integrations/saas-cloud/crowdstrike-spotlight.md
  docs/integrations/saas-cloud/knowbe4.md
  docs/integrations/saas-cloud/lastpass.md
  docs/integrations/saas-cloud/microsoft-azure-ad-inventory.md
  docs/integrations/saas-cloud/microsoft-graph-azure-ad-reporting.md
  docs/integrations/saas-cloud/microsoft-graph-security-v1.md
  docs/integrations/saas-cloud/microsoft-graph-security-v2.md
  docs/integrations/saas-cloud/proofpoint-on-demand.md
  docs/integrations/saas-cloud/proofpoint-tap.md
  docs/integrations/saas-cloud/qualys-vmdr.md
  docs/integrations/saas-cloud/rapid7.md
  docs/integrations/saas-cloud/salesforce.md
  docs/integrations/saas-cloud/sentinelone.md
  docs/integrations/saas-cloud/slack.md
  docs/integrations/saas-cloud/sophos.md
  docs/integrations/saas-cloud/tenable.md
  docs/integrations/saas-cloud/workday.md
  docs/integrations/saml/okta.md
  docs/integrations/security-threat-detection/akamai-security-events.md
  docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection.md
  docs/integrations/security-threat-detection/duo-security.md
  docs/integrations/security-threat-detection/netskope.md
  docs/reuse/apps/app-collection-option-1.md
  docs/reuse/apps/app-collection-option-2.md
  docs/reuse/apps/app-collection-option-3.md
  docs/reuse/apps/collection-configuration.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
Labels: cla-signed

#4894 Cisco AMP - Apps
  blog-service/2024-12-20-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/cisco-amp.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#4897 Add new UI instructions in places previously missed
  blog-cse/2022/12-31.md
  blog-cse/2023/12-31.md
  blog-csoar/2024-01-03-application-update.md
  blog-csoar/2024-01-30-application-update.md
  blog-csoar/2024-02-19-application-update.md
  blog-service/2022/12-31.md
  blog-service/2023/12-31.md
  blog-service/2024-06-24-manage.md
  blog-service/2024-06-28-metrics.md
  docs/cloud-soar/introduction.md
  docs/contributing/index.md
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/auth0.md
  docs/cse/schema/parser-editor.md
  docs/dashboards/share-dashboard-outside-org.md
  docs/integrations/amazon-aws/amazon-opensearch.md
  docs/integrations/containers-orchestration/vmware.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/saas-cloud/acquia.md
  docs/integrations/security-threat-detection/zscaler-internet-access.md
  docs/integrations/security-threat-detection/zscaler-private-access.md
  docs/manage/deletion-requests.md
  docs/manage/ingestion-volume/collection-status-page.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/manage/manage-subscription/upgrade-sumo-logic-credits-account.md
  docs/manage/security/index.md
  docs/manage/security/saml/integrate-sumo-logic-with-okta.md
  docs/manage/security/saml/set-up-adfs-authenticate-users.md
  docs/platform-services/threat-intelligence-indicators.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  docs/send-data/hosted-collectors/amazon-aws/grant-access-aws-product.md
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
  docs/send-data/installed-collectors/linux.md
  docs/send-data/installed-collectors/macos.md
  docs/send-data/installed-collectors/sources/script-action.md
  docs/send-data/installed-collectors/windows.md
  docs/send-data/opentelemetry-collector/quickstart.md
  docs/send-data/opentelemetry-collector/troubleshooting.md
  docs/send-data/setup-wizard.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/index.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/new-collectors-and-sources.md
  i18n/ja/alerts/alerts/monitors/index.md
Labels: doc:update, cla-signed

#4583 DOCS-434 - Ingest Budgets V1 deprecation
  blog-service/2024-06-24-manage.md
  cid-redirects.json
  docs/api/index.md
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/get-started/quickstart.md
  docs/manage/ingestion-volume/ingest-budgets/daily-volume.md
  docs/manage/ingestion-volume/ingest-budgets/daily-volume/assign-collector-ingest-budget.md
  docs/manage/ingestion-volume/ingest-budgets/daily-volume/quickstart.md
  docs/manage/ingestion-volume/ingest-budgets/index.md
  docs/manage/ingestion-volume/ingest-budgets/minute-volume.md
  docs/send-data/collection/edit-collector.md
  docs/send-data/hosted-collectors/configure-hosted-collector.md
  docs/send-data/hosted-collectors/http-source/troubleshooting.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4870 DOCS-601 - Copilot FAQ
  docs/search/copilot.md
  docusaurus.config.js
Labels: cla-signed, do-not-merge

#4500 Update deletion-requests.md
  docs/manage/deletion-requests.md
Labels: cla-signed

#4901 Cloud SIEM content release notes for December 20, 2024
  blog-cse/2024-12-20-content.md
Labels: cla-signed

#4900 Update log-level.md
  docs/search/get-started-with-search/search-page/log-level.md
Labels: cla-signed

#4840 Update logs-to-metrics.md
  docs/metrics/logs-to-metrics.md
Labels: cla-signed

#4819 Update optimize-search-partitions.md
  docs/search/optimize-search-partitions.md
Labels: cla-signed

#4902 Update standard match lists
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: doc:update, cla-signed, do-not-merge

#4903 Legacy 301 fixes
  cid-redirects.json
Labels: cla-signed

#4906 VMware source doc example update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/vmware-workspace-one-source.md
  static/files/c2c/vmware-workspace-one/example.json
  static/files/c2c/vmware-workspace-one/example.tf
Labels: cla-signed

#4909 Azure event grid documentation
  docs/integrations/microsoft-azure/azure-event-grid.md
  static/img/send-data/azure-event-grid-metrics.png
  static/img/send-data/azure-eventgrid-logs.png
Labels: cla-signed

#4907 Release Note Dec 2024 (Apps)
  blog-service/2024-12-31-apps.md
Labels: doc:new, cla-signed
