Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-07, with the labels that each got.

#4260 Disallow cid-redirects.json in robots.txt
  static/robots.txt
Labels: cla-signed

#4262 updated the action
  docs/platform-services/automation-service/app-central/integrations/apivoid.md
Labels: cla-signed

#4256 VMware docs update changes
  blog-service/2024-07-02-apps.md
  docs/integrations/containers-orchestration/vmware.md
Labels: do-not-merge

#4264 updated the actions
  docs/platform-services/automation-service/app-central/integrations/microsoft-onedrive.md
Labels: cla-signed

#4263 Update salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
Labels: cla-signed, hot🔥

#4268 New integration Virus Total V3
  docs/platform-services/automation-service/app-central/integrations/virustotal-v3.md
Labels: cla-signed

#4226 Sumo Orgs: Credit Management docs update
  blog-service/2024-07-03-manage.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
  static/img/subscriptions/access-org.png
  static/img/subscriptions/allocate-credits-set-baseline.png
  static/img/subscriptions/baseline-credits-to-add.png
  static/img/subscriptions/baseline-view-details.png
  static/img/subscriptions/baselines-pov.png
  static/img/subscriptions/baselines_1.png
  static/img/subscriptions/baselines_2.png
  static/img/subscriptions/baselines_3.png
  static/img/subscriptions/basic-details.png
  static/img/subscriptions/calculator.png
  static/img/subscriptions/child-credits-usage.png
  static/img/subscriptions/create-new-org.png
  static/img/subscriptions/credits-calculator.png
  static/img/subscriptions/edit-baseline-example.png
  static/img/subscriptions/edit-baseline.png
  static/img/subscriptions/edit-option.png
  static/img/subscriptions/edit-org-3.png
  static/img/subscriptions/free-org-set-baseline.png
  static/img/subscriptions/modify-allocation-button.png
  static/img/subscriptions/modify-allocation-recommendatio-example-2.png
  static/img/subscriptions/modify-allocation-recommendation.png
  static/img/subscriptions/modify-allocation-usage-forecast.png
  static/img/subscriptions/plan-selected.png
  static/img/subscriptions/pov-baselines.png
  static/img/subscriptions/sp-create-new-org.png
  static/img/subscriptions/upgrade-plan.png
  static/img/subscriptions/upgrade.png
Labels: cla-signed

#4267 updated the actions
  docs/platform-services/automation-service/app-central/integrations/virustotal.md
  static/img/platform-services/automation-service/app-central/integrations/virus-total/virus-total-1.png
  static/img/platform-services/automation-service/app-central/integrations/virus-total/virus-total-2.png
Labels: cla-signed

#4269 Cloud SIEM content release notes - July 3, 2024
  blog-cse/2024-07-03-content.md
Labels: doc:new, cla-signed

#4219 Add metrics collection and metrics-based dashboards info to Memcached OTel app doc
  docs/integrations/databases/opentelemetry/memcached-opentelemetry.md
Labels: cla-signed

#4271 Updated the URL to correct page
  blog-service/2024-06-24-manage.md
Labels: cla-signed

#4272 Salesforce 3.x.x release notes
  blog-service/2024-07-05-collection.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  static/img/release-notes/service/upgrade-source.png
Labels: cla-signed

#4261 Masking st
  cid-redirects.json
  docs/reuse/apps/opentelemetry/log-collection-prerequisite-windows.md
  docs/reuse/apps/opentelemetry/logs-advance-option-otel.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows.md
Labels: cla-signed, do-not-merge

#4275 AWS EC2 fix the issue
  docs/platform-services/automation-service/app-central/integrations/aws-ec2.md
Labels: cla-signed

#4276 Virus Total V3
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#4273 DOC-39 - Cloud SIEM integrations for product list article
  docs/integrations/community-ecosystem-apps.md
  docs/integrations/product-list.md
  static/img/integrations/misc/adaxes-logo.png
  static/img/integrations/misc/alibaba-cloud-logo.png
  static/img/integrations/misc/alphasoc-logo.png
  static/img/integrations/misc/blackberry-logo.png
  static/img/integrations/misc/bluecat-logo.png
  static/img/integrations/misc/circl-logo.png
  static/img/integrations/misc/cloud-logo.svg
  static/img/integrations/misc/dell-logo.png
  static/img/integrations/misc/eset-logo.png
  static/img/integrations/misc/exabeam-logo.svg
  static/img/integrations/misc/extrahop-logo.png
  static/img/integrations/misc/falco-logo.svg
  static/img/integrations/misc/genea-logo.svg
  static/img/integrations/misc/hewlett-packard-logo.svg
  static/img/integrations/misc/illumio-logo.svg
  static/img/integrations/misc/infoblox-logo.svg
  static/img/integrations/misc/isc-logo.png
  static/img/integrations/misc/juniper-networks-logo.png
  static/img/integrations/misc/kandji.png
  static/img/integrations/misc/lastpass-logo.png
  static/img/integrations/misc/laurel.svg
  static/img/integrations/misc/microsoft-logo.png
  static/img/integrations/misc/misp-logo.png
  static/img/integrations/misc/oisf-logo.png
  static/img/integrations/misc/openssh-logo.png
  static/img/integrations/misc/openvpn-logo.png
  static/img/integrations/misc/orca-security-logo.png
  static/img/integrations/misc/ossec-logo.png
  static/img/integrations/misc/ping-logo.svg
  static/img/integrations/misc/pritunl-logo.png
  static/img/integrations/misc/radiant-logo.svg
  static/img/integrations/misc/secureauth-logo.png
  static/img/integrations/misc/snare-logo.png
  static/img/integrations/misc/snowflake-logo.png
  static/img/integrations/misc/sucuri-logo.png
  static/img/integrations/misc/sysdig-logo.png
  static/img/integrations/misc/thinkst-canary-logo.png
  static/img/integrations/misc/threater-logo.png
  static/img/integrations/misc/varonis-logo.png
  static/img/integrations/misc/wiz-logo.png
Labels: doc:update, cla-signed

#4278 DOCS-307 - Clean up Product List article
  docs/integrations/product-list.md
  static/img/integrations/misc/azure-logo.png
Labels: doc:update, cla-signed

#4274 Update iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
Labels: cla-signed

#4280 404 fixes
  cid-redirects.json
  static/robots.txt
Labels: cla-signed

#4281 DOCS-308 - CID for Views (forthcoming feature)
  cid-redirects.json
  docs/manage/views/index.md
Labels: cla-signed

#4282 Yarn 1.22.22 + dependencies upgrade
  yarn.lock
Labels: cla-signed

#4285 Add ruturajsumo to clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#4283 Added two actions
  docs/platform-services/automation-service/app-central/integrations/crowdstrike-falcon.md
Labels: cla-signed

#4288 Introducing a New Index Source Category - Release notes
  blog-service/2024-07-09-search.md
  docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
  static/img/search/get-started-search/search-page/extracted-And-Collected-Fields-Size.png
Labels: cla-signed

#4292 Weekly 404 fixes
  cid-redirects.json
  docusaurus.config.js
Labels: cla-signed

#4294 Update docusaurus.config.js
  docusaurus.config.js
Labels: cla-signed

#4296 updated
  docs/platform-services/automation-service/app-central/integrations/atlassian-opsgenie.md
Labels: cla-signed

#4298 Update .clabot
  .clabot
Labels: cla-signed

#4293 Update salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
Labels: cla-signed

#4265 Add metrics collection and metrics-based dashboards info to HAProxy Otel app
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
Labels: cla-signed

#4295 Added link to micro lesson video 'Creating a new child org'
  docs/manage/manage-subscription/create-manage-orgs.md
Labels: cla-signed

#4300 Update the spelling error
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
Labels: cla-signed

#4301 Update collect-logs to include Microsoft SQL example
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed

#4302 DOCS-326 - Update Scheduled Report article
  docs/dashboards/scheduled-report.md
Labels: doc:update, cla-signed

#4310 DOCS-332 - Fix extracted field format
  docs/cse/rules/write-match-rule.md
Labels: doc:minor edit, cla-signed

#4311 DOCS-314 - Split by field on the filter node
  docs/cloud-soar/automation.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/cloud-soar/configure-filter-node.png
  static/img/platform-services/automation-service/automations-add-filter-node-conditions.png
Labels: doc:update, cla-signed

#4307 Manage a credit org microlesson added
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
Labels: cla-signed

#4286 Add metrics collection and metrics-based dashboards info to Redis Otel
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
Labels: cla-signed

#4314 App central silent push
  docs/platform-services/automation-service/app-central/integrations/silent-push.md
Labels: cla-signed

#4315 Updated Amazon Elastic Kubernetes Service (AWS EKS)
  docs/platform-services/automation-service/app-central/integrations/aws-eks.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem.md
Labels: cla-signed

#4318 Cloud SIEM content release notes for July 16, 2024
  blog-cse/2024-07-16-content.md
Labels: doc:new, cla-signed

#4317 DOCS-311 - System Event Index
  docs/alerts/monitors/monitor-faq.md
  docs/cloud-soar/audit-event-index.md
  docs/cse/administration/cse-audit-logging.md
  docs/cse/administration/mitre-coverage.md
  docs/cse/get-started-with-cloud-siem/onboarding-checklist-cse.md
  docs/manage/health-events.md
  docs/manage/security/audit-indexes/audit-event-index.md
  docs/manage/security/audit-indexes/audit-index.md
  docs/manage/security/audit-indexes/documentation-audit-log-definitions.md
  docs/manage/security/audit-indexes/index.md
  docs/manage/security/audit-indexes/system-event-index.md
  docs/platform-services/automation-service/automation-service-audit-logging.md
  i18n/ja/alerts/alerts/monitors/monitor-faq.md
  sidebars.ts
Labels: doc:new, cla-signed

#4316 DOCS-336 app-install /reuse/ wording
  docs/reuse/apps/app-install-v2.md
  docs/reuse/apps/app-install.md
  docs/reuse/apps/app-uninstall.md
  docs/reuse/apps/app-update.md
Labels: cla-signed

#4308 new release note for cloud soar
  blog-csoar/2024-07-17-application-update.md
Labels: cla-signed

#4321 Update transactionize-operator.md
  docs/search/search-query-language/transaction-analytics/transactionize-operator.md
Labels: cla-signed

#4322 Update timeslice.md
  docs/search/search-query-language/search-operators/timeslice.md
Labels: cla-signed

#4324 DOCS-340 - Update file path
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: doc:minor edit, cla-signed

#4326 Adjust date on Cloud SOAR on-premises release note
  blog-csoar/2023/12-31.md
Labels: doc:minor edit, cla-signed

#4304 Alerts/Monitors - grammar, formatting cleanup
  docs/alerts/difference-from-scheduled-searches.md
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/alert-response-faq.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/alert-variables.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/index.md
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/monitors/muting-schedules.md
  docs/alerts/monitors/overview.md
  docs/alerts/monitors/settings.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/alerts/scheduled-searches/create-email-alert.md
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/scheduled-searches/generate-cse-signals.md
  docs/alerts/scheduled-searches/index.md
Labels: cla-signed

#4327 Revert "Alerts/Monitors - grammar, formatting cleanup"
  docs/alerts/difference-from-scheduled-searches.md
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/alert-response-faq.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/alert-variables.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/index.md
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/monitors/muting-schedules.md
  docs/alerts/monitors/overview.md
  docs/alerts/monitors/settings.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/alerts/scheduled-searches/create-email-alert.md
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/scheduled-searches/generate-cse-signals.md
  docs/alerts/scheduled-searches/index.md
Labels: cla-signed, hot🔥

#4328 Revert the "Revert for 'Alerts/Monitors - grammar, formatting cleanup' "
  docs/alerts/difference-from-scheduled-searches.md
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/alert-response-faq.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/alert-variables.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/index.md
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/monitors/muting-schedules.md
  docs/alerts/monitors/overview.md
  docs/alerts/monitors/settings.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/alerts/scheduled-searches/create-email-alert.md
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/scheduled-searches/generate-cse-signals.md
  docs/alerts/scheduled-searches/index.md
Labels: doc:update, cla-signed

#4330 Update schedule-search.md
  docs/alerts/scheduled-searches/schedule-search.md
Labels: cla-signed

#4331 Weekly 404 fixes
  cid-redirects.json
  docs/search/get-started-with-search/search-page/index.md
  docusaurus.config.js
Labels: cla-signed

#4333 Temp announcementBar re: outages
  docusaurus.config.js
Labels: cla-signed

#4023 OpenTelemetry Remote Management index page (beta)
  docs/send-data/opentelemetry-collector/remote-management/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/index.md
Labels: cla-signed

#4341 Update collect-logs.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
Labels: cla-signed, hot🔥

#4335 Update datadog.md
  docs/integrations/saas-cloud/datadog.md
Labels: cla-signed

#4337 Update netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: cla-signed

#4342 Update sumo-logic-flex-accounts.md
  docs/manage/manage-subscription/sumo-logic-flex-accounts.md
Labels: cla-signed

#4338 Update close-cancel-sumo-account.md
  docs/manage/manage-subscription/close-cancel-sumo-account.md
Labels: cla-signed

#4323 DOCS-338 - Fix Windows keyboard shortcuts
  docs/get-started/keyboard-shortcuts.md
Labels: doc:update, cla-signed

#4344 Update collect-logs-oracle-cloud-infrastructure.md
  docs/send-data/collect-from-other-data-sources/collect-logs-oracle-cloud-infrastructure.md
Labels: doc:update, cla-signed

#4345 Add sachin-sumologic to clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#4334 Real-time alerts/Sched Search edits
  docs/alerts/difference-from-scheduled-searches.md
  docs/alerts/scheduled-searches/create-email-alert.md
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/faq.md
  docs/send-data/reference-information/time-reference.md
  i18n/ja/alerts/alerts/scheduled-searches/create-real-time-alert.md
Labels: doc:update, cla-signed

#4346 Amazon Inspector doc update
  docs/integrations/amazon-aws/inspector.md
Labels: cla-signed

#4348 chore: update nodejs lambda layers supported version
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
Labels: cla-signed

#4349 New integration Sum-Logic-Notifaiction-By-Gmail
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail.md
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-1.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-10.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-2.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-3.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-4.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-6.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-7.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-8.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail/sumo-logic-notifications-by-gmail-9.png
  static/img/platform-services/automation-service/app-central/integrations/sumo-logic-notifications/sumo-logic-notifications-4.png
Labels: cla-signed

#4353 Update github.md
  docs/integrations/app-development/github.md
Labels: cla-signed

#4355 Weekly 404 fixes
  cid-redirects.json
Labels: cla-signed

#4309 Changes for cassandra opentelemetry doc after with metric collection …
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
Labels: cla-signed

#4332 Add metrics collection and metrics-based dashboards info to RabbitMQ
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
Labels: doc:update, cla-signed

#4305 DOCS-320 - Log monitor trigger evaluation freq
  docs/alerts/monitors/create-monitor.md
Labels: cla-signed, do-not-merge

#4357 chore: update js instr deps
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
Labels: cla-signed

#4352 DOCS-253 - Kanso cleanup
  docs/alerts/webhook-connections/pagerduty.md
  docs/contributing/style-guide.md
  docs/cse/ingestion/cse-ingestion-best-practices.md
  docs/integrations/containers-orchestration/kubernetes.md
  docs/integrations/containers-orchestration/rabbitmq.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/mariadb.md
  docs/integrations/databases/memcached.md
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/redis.md
  docs/integrations/hosts-operating-systems/host-process-metrics.md
  docs/integrations/microsoft-azure/sql-server.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx-plus-ingress.md
  docs/integrations/web-servers/nginx-plus.md
  docs/integrations/web-servers/nginx.md
  docs/send-data/collect-from-other-data-sources/collect-ruby-on-rails-logs.md
Labels: doc:update, cla-signed

#4354 DOCS-350 - Ensure that the Product List article is indexed
  docs/integrations/product-list/index.md
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/product-list/product-list-m-z.md
  sidebars.ts
Labels: doc:update, cla-signed

#4359 Update cloud-soar-bridge.md - Amend SIEM_URL setting
  docs/cloud-soar/cloud-soar-bridge.md
Labels: cla-signed

#4358 Update automation-service-bridge.md - Amend SIEM_URL setting
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: cla-signed

#4361 Changing the dashboard screenshot file name from jpg to png
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
Labels: cla-signed

#4336 VMWare Otel App Documentation
  cid-redirects.json
  docs/integrations/containers-orchestration/opentelemetry/vmware-opentelemetry.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/reuse/apps/opentelemetry/send-logs-intro.md
  sidebars.ts
Labels: doc:new, cla-signed

#4362 CONN-3431, CONN-3432: Added FAQ sections for Akamai SIEM API
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/akamai-siem-api-source.md
Labels: cla-signed

#4364 chore: update python instr deps
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
Labels: cla-signed

#4365 chore: update .net instr logs location
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
Labels: cla-signed

#4367 Add more integrations to the product list articles
  docs/integrations/product-list/product-list-m-z.md
Labels: doc:minor edit, cla-signed

#4085 DOCS-76 - Integrate UX style guidance
  docs/contributing/code-of-conduct.md
  docs/contributing/remove-doc.md
  docs/contributing/style-guide.md
  docs/contributing/word-list.md
  docs/reuse/doc-prerequisites.md
  src/css/sumo.scss
  static/img/contributing/collapsible-text.png
  static/img/contributing/highlight-codeblock.png
  static/img/contributing/json-codeblock.png
  static/img/contributing/title-codeblock.png
Labels: cla-signed, do-not-merge

#4343 Update faq.md
  docs/manage/partitions/flex/faq.md
Labels: doc:update, cla-signed

#4373 Weekly 404 Fixes
  cid-redirects.json
  docs/search/search-cheat-sheets/log-operators.md
Labels: cla-signed

#4368 Formatting fixes - OTEL Traces Instrumentation
  blog-cse/2023/12-31.md
  blog-service/2017/12-31.md
  blog-service/2024-01-15-active-directory-app-update.md
  docs/alerts/webhook-connections/microsoft-azure-functions.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/traceid-and-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/custom-tags-configuration.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/traceid-spanid-injection-into-logs-configuration.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/traceid-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/traceid-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/traceid-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-aws-environments.md
  docs/apm/traces/spans.md
  docs/apm/traces/view-and-investigate-traces.md
  docs/cse/integrations/insight-enrichment-server.md
  docs/dashboards/panels/map-charts.md
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/hosts-operating-systems/host-process-metrics.md
  docs/manage/security/installation-tokens.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/automatic-installation-script.md
  docs/platform-services/automation-service/app-central/integrations/vmware-carbon-black-cloud-platform.md
  docs/search/time-compare.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/install-telegraf.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/carbon-black-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
  docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
  docs/send-data/opentelemetry-collector/install-collector/windows.md
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
  static/img/traces/Refresh.png
Labels: cla-signed

#4356 Update lookup.md
  docs/search/search-query-language/search-operators/lookup.md
Labels: cla-signed

#4375 DOCS-357 - Remove sentence from match lists article
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: doc:minor edit, cla-signed

#4376 Installed Collected CLI doc formatting fixes
  docs/send-data/installed-collectors/collector-installation-reference/parameters-command-line-installer.md
Labels: cla-signed

#4374 Update base64decode.md
  docs/search/search-query-language/search-operators/base64decode.md
Labels: cla-signed

#4381 Update Sumo social media icons
  docusaurus.config.js
  package.json
  src/theme/Footer/index.tsx
  yarn.lock
Labels: cla-signed
