Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-02, with the labels that each got.

#3581 Added info about Alerts for POV Trial
  blog-service/2024-01-31-manage.md
  docs/get-started/sign-up.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
Labels: cla-signed, do-not-merge

#3601 Bring back the original Sumo UI Tour
  docs/get-started/sumo-logic-ui.md
Labels: cla-signed

#3604 Revert "Added info about Alerts for POV Trial"
  blog-service/2024-01-31-manage.md
  docs/get-started/sign-up.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
Labels: cla-signed

#3597 Add C2C Source - CrowdStrike FileVantage
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-filevantage.md
  static/files/c2c/crowdstrike-filevantage/example.json
  static/files/c2c/crowdstrike-filevantage/example.tf
Labels: cla-signed

#3607 Add CrowdStrike FileVantage article to left nav
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-filevantage.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
Labels: doc:minor edit, cla-signed

#3463 Fix Helm Chart sidebar categories
  sidebars.ts
Labels: cla-signed, do-not-merge

#3609 Update set-custom-time-ranges.md
  docs/dashboards/set-custom-time-ranges.md
Labels: cla-signed

#3610 App Central integration - AWS Network Firewall
  docs/platform-services/automation-service/app-central/integrations/aws-athena.md
  docs/platform-services/automation-service/app-central/integrations/aws-cloudfront.md
  docs/platform-services/automation-service/app-central/integrations/aws-cloudtrail.md
  docs/platform-services/automation-service/app-central/integrations/aws-cloudwatchlogs.md
  docs/platform-services/automation-service/app-central/integrations/aws-ec2.md
  docs/platform-services/automation-service/app-central/integrations/aws-guardduty.md
  docs/platform-services/automation-service/app-central/integrations/aws-iam.md
  docs/platform-services/automation-service/app-central/integrations/aws-inspector.md
  docs/platform-services/automation-service/app-central/integrations/aws-network-firewall.md
  docs/platform-services/automation-service/app-central/integrations/aws-route53.md
  docs/platform-services/automation-service/app-central/integrations/aws-s3.md
  docs/platform-services/automation-service/app-central/integrations/aws-security-hub.md
  docs/platform-services/automation-service/app-central/integrations/aws-simple-notification-service.md
  docs/platform-services/automation-service/app-central/integrations/aws-sqs.md
  static/img/platform-services/automation-service/app-central/logos/aws-cloudfront.png
  static/img/platform-services/automation-service/app-central/logos/aws-cloudtrail.png
  static/img/platform-services/automation-service/app-central/logos/aws-cloudwatchlogs.png
  static/img/platform-services/automation-service/app-central/logos/aws-ec2.png
  static/img/platform-services/automation-service/app-central/logos/aws-guardduty.png
  static/img/platform-services/automation-service/app-central/logos/aws-iam.png
  static/img/platform-services/automation-service/app-central/logos/aws-inspector.png
  static/img/platform-services/automation-service/app-central/logos/aws-route53.png
  static/img/platform-services/automation-service/app-central/logos/aws-s3.png
  static/img/platform-services/automation-service/app-central/logos/aws-security-hub.png
  static/img/platform-services/automation-service/app-central/logos/aws-simple-notification-service.png
  static/img/platform-services/automation-service/app-central/logos/aws-sqs.png
  static/img/platform-services/automation-service/app-central/logos/aws.png
Labels: cla-signed

#3608 Update cloud-flex-credits-accounts.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
Labels: cla-signed

#3614 Remove comments from examples in rules syntax article
  docs/cse/rules/cse-rules-syntax.md
Labels: doc:update, cla-signed

#3611 fix: fix path for Kubernetes Helm Chart
  sidebars.ts
Labels: cla-signed

#3616 Add items to the product list
  docs/integrations/product-list.md
  static/img/integrations/misc/dataminr-logo.svg
  static/img/integrations/misc/jamf-logo.png
Labels: doc:update, cla-signed

#3620 Remove duplicate AD Azure doc
  docs/integrations/microsoft-azure/active-directory-azure1.md
Labels: cla-signed

#3569 Add a configuration reference document for helm chart
  docs/send-data/kubernetes/configuration.md
  sidebars.ts
Labels: cla-signed

#3605 Updated Dashboard depreciation release note
  blog-service/2023/12-31.md
Labels: cla-signed

#3613 Release 2 v2 apps (30)
  docs/contributing/templates/app-template-v2.md
  docs/integrations/amazon-aws/route-53-resolver-security.md
  docs/integrations/amazon-aws/s3-audit.md
  docs/integrations/app-development/jenkins.md
  docs/integrations/app-development/jfrog-artifactory.md
  docs/integrations/cloud-security-monitoring-analytics/linux.md
  docs/integrations/cloud-security-monitoring-analytics/windows.md
  docs/integrations/databases/mongodb-atlas.md
  docs/integrations/hosts-operating-systems/linux.md
  docs/integrations/microsoft-azure/performance.md
  docs/integrations/microsoft-azure/windows-json.md
  docs/integrations/saas-cloud/asana.md
  docs/integrations/saas-cloud/docusign.md
  docs/integrations/saas-cloud/dropbox.md
  docs/integrations/saas-cloud/miro.md
  docs/integrations/saas-cloud/palo-alto-cortex-xdr.md
  docs/integrations/saas-cloud/sentinelone.md
  docs/integrations/saas-cloud/symantec-web-security-service.md
  docs/integrations/saas-cloud/workday.md
  docs/integrations/saml/okta.md
  docs/integrations/saml/onelogin.md
  docs/integrations/security-threat-detection/evident-security-platform.md
  docs/integrations/security-threat-detection/f5-big-ip-ltm.md
  docs/integrations/security-threat-detection/imperva-incapsula.md
  docs/integrations/security-threat-detection/netskope.md
  docs/integrations/security-threat-detection/observable-networks.md
  docs/integrations/security-threat-detection/twistlock.md
Labels: cla-signed, hot🔥

#3625 App Central integration - OneTrust
  docs/platform-services/automation-service/app-central/integrations/onetrust.md
Labels: cla-signed

#3446 Kaltura Source doc
  docs/integrations/product-list.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/kaltura-source.md
  sidebars.ts
  static/files/c2c/kaltura/example.json
  static/files/c2c/kaltura/example.tf
  static/img/send-data/kaltura-logo.png
Labels: cla-signed

#3598 Update incidents-triage.md
  docs/cloud-soar/incidents-triage.md
Labels: cla-signed

#3588 Send Data cleanup
  docs/apm/traces/index.md
  docs/metrics/index.md
  docs/platform-services/threat-intelligence-indicators.md
  docs/search/index.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template-with-secured-sumo-endpoint.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/index.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/troubleshoot-azure-blob-storage-log-collection.md
  docs/send-data/collect-from-other-data-sources/collect-logs-oracle-cloud-infrastructure.md
  docs/send-data/collect-from-other-data-sources/import-raw-data-splunk.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
  docs/send-data/installed-collectors/configuration.md
  docs/send-data/installed-collectors/index.md
  docs/send-data/installed-collectors/linux.md
  docs/send-data/installed-collectors/macos.md
  docs/send-data/installed-collectors/windows.md
  docs/send-data/opentelemetry-collector/data-source-configurations/index.md
  docs/send-data/opentelemetry-collector/data-source-configurations/overview.md
  docs/send-data/opentelemetry-collector/faq.md
  docs/send-data/opentelemetry-collector/index.md
  docs/send-data/opentelemetry-collector/install-collector/index.md
  docs/send-data/opentelemetry-collector/sumo-logic-opentelemetry-vs-opentelemetry-upstream-relationship.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/existing-collectors-and-sources.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/index.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/new-collectors-and-sources.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/view-download-source-json-configuration.md
  sidebars.ts
  static/img/metrics/metrics.png
  static/img/search/get-started-search/search-basics/logsearch.png
  static/img/traces/traces.png
Labels: cla-signed

#3626 App central integration aws iam
  docs/platform-services/automation-service/app-central/integrations/aws-iam.md
  static/img/platform-services/automation-service/app-central/logos/aws.png
Labels: cla-signed

#3628 SUMO-235493 Fix the CloudFormation template for Kinesis log sources
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
  static/files/KinesisFirehoseCWLogs.template.yaml
Labels: cla-signed

#3624 Removed troubleshooting and monitoring with classic dashboards section
  docs/dashboards/about.md
Labels: cla-signed

#3606 Indicators for POV Trial Period Expiry
  blog-service/2024-02-06-manage.md
  docs/get-started/sign-up.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
Labels: cla-signed, hot🔥

#2839 Cloud SOAR Delivery 2 - GA
  blog-csoar/2024-02-06-application-update.md
  cid-redirects.json
  docs/api/cloud-soar.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/cloud-soar-apis.md
  docs/cloud-soar/cloud-soar-delivery-2.md
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/main-menu.md
  docs/cloud-soar/overview.md
  docs/reuse/cse-launch-csoar-automation.md
Labels: doc:new, cla-signed

#3631 App Central integration - Powershell Tools
  docs/platform-services/automation-service/app-central/integrations/powershell-tools.md
Labels: cla-signed

#3635 App Central integration - AWS IAM
  docs/platform-services/automation-service/app-central/integrations/aws-iam.md
Labels: cla-signed

#3636 Update Cloud SOAR release note for Delivery 2 documentation
  blog-csoar/2024-02-06-application-update.md
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/main-menu.md
Labels: doc:update, cla-signed, hot🔥

#3638 Move App Central section
  docs/platform-services/automation-service/app-central/index.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  sidebars.ts
Labels: doc:minor edit, cla-signed

#3630 Fix PAN 9 app snippet syntax
  docs/integrations/security-threat-detection/palo-alto-networks-6.md
  docs/integrations/security-threat-detection/palo-alto-networks-8.md
  docs/integrations/security-threat-detection/palo-alto-networks-9.md
Labels: cla-signed

#3622 Host List (beta) edits
  docs/observability/host-list-beta.md
Labels: cla-signed

#3639 App Central integration - Sumo Logic CSE
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cse.md
Labels: cla-signed

#3640 App Central integration - Dynatrace
  docs/platform-services/automation-service/app-central/integrations/dynatrace.md
Labels: cla-signed

#3633 Update observability kubernetes section
  docs/metrics/kubernetes-metrics.md
  docs/observability/kubernetes/collection-setup.md
  docs/observability/kubernetes/index.md
Labels: cla-signed

#3643 Revert to platform default 404 page
  src/theme/NotFound.js
Labels: cla-signed

#3617 Compare Cloud SOAR to the Automation Service
  docs/cloud-soar/compared-to-automation-service.md
  docs/cloud-soar/index.md
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  sidebars.ts
Labels: doc:new, cla-signed

#3645 Update index.md
  docs/manage/partitions-data-tiers/index.md
Labels: cla-signed

#3646 network-watcher
  docs/integrations/microsoft-azure/network-watcher.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage.md
  static/img/send-data/Azure_Blob_all-resources.png
Labels: cla-signed

#3648 Added counter to show the total number of integrations in App Central
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#3647 Removed CSS rule for DocCardList that hid the top border on hover in dark theme.
  src/css/sumo.scss
Labels: cla-signed

#3650 App Central Integration AWS IAM
  docs/platform-services/automation-service/app-central/integrations/aws-iam.md
Labels: cla-signed

#3644 Move article back to Data Forwarding section
  blog-collector/2018/12-31.md
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/manage/data-archiving/index.md
  docs/manage/data-forwarding/index.md
  docs/manage/data-forwarding/installed-collectors.md
  docs/send-data/collection/processing-rules/create-processing-rule.md
  docs/send-data/use-json-configure-sources/index.md
  sidebars.ts
Labels: doc:update, cla-signed

#3652 Update "TLS Syslog Data" section
  docs/send-data/installed-collectors/sources/syslog-source.md
Labels: doc:minor edit, cla-signed

#3651 Update regex in Zscaler Private Acess
  docs/integrations/security-threat-detection/zscaler-private-access.md
Labels: doc:update, cla-signed

#3612 Updated the Prerequisites for OTEL docs
  docs/integrations/app-development/opentelemetry/jfrog-artifactory-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jira-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jmx-opentelemetry.md
  docs/integrations/app-development/opentelemetry/puppet-opentelemetry.md
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/linux-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/activemq-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/docker-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/kafka-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mariadb-opentelemetry.md
  docs/integrations/databases/opentelemetry/memcached-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/active-directory-json-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-linux-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
  docs/integrations/pci-compliance/opentelemetry/linux-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/nginx-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/squid-proxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/varnish-opentelemetry.md
  docs/reuse/apps/logs-collection-prereqisites.md
Labels: cla-signed, do-not-merge

#3654 Border color - black to gray
  docs/cloud-soar/automation.md
  docs/dashboards/filter-template-variables.md
  docs/integrations/app-development/opentelemetry/jfrog-artifactory-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jira-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jmx-opentelemetry.md
  docs/integrations/app-development/opentelemetry/puppet-opentelemetry.md
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/linux-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/activemq-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/docker-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/kafka-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mariadb-opentelemetry.md
  docs/integrations/databases/opentelemetry/memcached-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/active-directory-json-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-linux-opentelemetry.md
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
  docs/integrations/pci-compliance/opentelemetry/windows-json-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/nginx-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/squid-proxy-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/varnish-opentelemetry.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
  docs/reuse/apps/opentelemetry/process-metric-collection.md
  docs/search/get-started-with-search/search-basics/built-in-metadata.md
  docs/search/get-started-with-search/search-basics/chart-search-results.md
  docs/search/get-started-with-search/search-page/event-analytics.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/asana-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-host-inventory.md
  docs/send-data/opentelemetry-collector/auto-discovery.md
Labels: cla-signed

#3658 updating cwlogs collection docs
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-lambda-function.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
Labels: cla-signed

#3660 Update intsights-tip.md
  docs/platform-services/automation-service/app-central/integrations/intsights-tip.md
Labels: cla-signed

#3656 OTLP/HTTP Source doc update
  docs/send-data/hosted-collectors/http-source/otlp.md
  docs/send-data/use-json-configure-sources/index.md
Labels: cla-signed

#3662 App central integration incident tools
  docs/platform-services/automation-service/app-central/integrations/incident-tools.md
Labels: cla-signed

#3664 Manage Account ref
  docs/manage/index.md
  sidebars.ts
Labels: cla-signed

#3666 CSIEM content release 2024-02-13
  blog-cse/2024-02-13-content.md
Labels: cla-signed

#3655 Install apps doc update
  docs/get-started/apps-integrations.md
  docs/reuse/apps/app-install.md
Labels: cla-signed

#3669 Add the Automation menu
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/get-started/sumo-logic-ui.md
  docs/platform-services/automation-service/about-automation-service.md
  static/img/get-started/ui/TUI_App-Admin-Help.png
  static/img/platform-services/automation-menu-in-nav-bar-main.png
Labels: doc:update, cla-signed, hot🔥

#3634 Added parser metadata field
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zero-networks-segment-source.md
Labels: cla-signed, do-not-merge

#3649 Added metadata field - Trellix
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/trellix-mvisio-epo-source.md
Labels: cla-signed, do-not-merge

#3671 App Central Integration Sumo Logic CSE
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cse.md
Labels: cla-signed

#3670 CSOAR-714 | Added section for explain how deal with test playbook in Cloud Soar -- automation section
  docs/cloud-soar/automation.md
  static/img/cloud-soar/playbook-executed-run-test.png
  static/img/cloud-soar/playbook-run-test-modal.png
  static/img/cloud-soar/playbook-run-test-option.png
Labels: cla-signed

#3678 Add note about AWS Inventory Source
  docs/cse/administration/inventory-sources-and-data.md
Labels: doc:minor edit, cla-signed

#3677 Add RSS feed tagging for Cloud SOAR release notes
  blog-csoar/2023-06-08-first-release-note.md
  blog-csoar/2023-10-20-application-update.md
  blog-csoar/2023-10-23-content.md
  blog-csoar/2023-11-01-application-update.md
  blog-csoar/2023-11-16-application-update.md
  blog-csoar/2023-11-20-content.md
  blog-csoar/2023-12-04-application-update.md
  blog-csoar/2024-01-03-application-update.md
  blog-csoar/2024-01-08-content.md
  blog-csoar/2024-01-25-content.md
  blog-csoar/2024-01-30-application-update.md
  blog-csoar/2024-02-06-application-update.md
  docs/release-notes/index.md
Labels: doc:update, cla-signed

#3675 Update threatlookup operator for Threat Intel beta
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:update, cla-signed

#3676 CONN-2907 update for Threat Intel beta
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
Labels: doc:update, cla-signed

#3673 CID number added for VMware Carbon Black doc
  cid-redirects.json
Labels: cla-signed

#3672 Added metadata field - Druva Cyber Resilience
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-cyber-resilience-source.md
Labels: cla-signed

#3683 Updates to the Hashing/Masking documentation
  docs/send-data/opentelemetry-collector/data-transformations.md
Labels: cla-signed

#3682 Update Threat Intel beta with the latest changes
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:update, cla-signed

#3685 CONN-2833 - Update auth for STIX/TAXII 2 client source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
Labels: doc:update, cla-signed

#3437 Release 5 v2 apps
  docs/integrations/microsoft-azure/active-directory-json.md
  docs/integrations/saas-cloud/acquia.md
  docs/integrations/saas-cloud/airtable.md
  docs/integrations/saas-cloud/akamai-cloud-monitor.md
  docs/integrations/saas-cloud/akamai-datastream.md
  docs/integrations/saas-cloud/armis.md
  docs/integrations/saas-cloud/box.md
  docs/integrations/saas-cloud/cato-networks.md
  docs/integrations/saas-cloud/cisco-umbrella.md
  docs/integrations/saas-cloud/citrix-cloud.md
  docs/integrations/saas-cloud/cloudflare.md
  docs/integrations/security-threat-detection/akamai-security-events.md
  docs/integrations/security-threat-detection/barracuda-waf.md
  docs/integrations/security-threat-detection/carbon-black-cloud.md
  docs/integrations/security-threat-detection/cisco-asa.md
  docs/integrations/security-threat-detection/cylance.md
  docs/integrations/security-threat-detection/duo-security.md
  docs/integrations/webhooks/hasura.md
  docs/integrations/webhooks/ilert.md
  docs/integrations/webhooks/mailgun.md
  docs/integrations/webhooks/neoload.md
  docs/integrations/webhooks/netlify.md
  docs/integrations/webhooks/postman.md
  docs/integrations/webhooks/sentry.md
  docs/integrations/webhooks/split.md
  docs/integrations/webhooks/squadcast.md
  docs/integrations/webhooks/stripe.md
  static/img/integrations/webhooks/Netlify_BuildAndDeployDetails.png
  static/img/integrations/webhooks/Netlify_CommitDetails.png
  static/img/integrations/webhooks/Netlify_Overview.png
  static/img/integrations/webhooks/Postman-Collections,_Requests_&_Team_Activity.png
  static/img/integrations/webhooks/Postman-Monitors.png
  static/img/integrations/webhooks/Postman-Overview.png
  static/img/integrations/webhooks/Sentry-Overview.png
  static/img/integrations/webhooks/Sentry-Tags.png
  static/img/integrations/webhooks/Split-Overview.png
  static/img/integrations/webhooks/Split-Users_and_Groups.png
  static/img/integrations/webhooks/Squadcast-Incidents.png
  static/img/integrations/webhooks/Squadcast-Overview.png
  static/img/integrations/webhooks/Stripe-Customers_and_Billing.png
  static/img/integrations/webhooks/Stripe-Overview.png
  static/img/integrations/webhooks/Stripe-Products.png
  static/img/integrations/webhooks/hasura_overview.png
  static/img/integrations/webhooks/iLert_overview.png
  static/img/integrations/webhooks/mailgun_failedComplainedEvents.png
  static/img/integrations/webhooks/mailgun_overview.png
  static/img/integrations/webhooks/neoload_overview.png
  static/img/integrations/webhooks/neoload_testRunDetails.png
Labels: cla-signed, do-not-merge

#3428 Release4 v2 apps
  docs/integrations/amazon-aws/kinesis-streams.md
  docs/integrations/amazon-aws/redshift-ulm.md
  docs/integrations/amazon-aws/ses.md
  docs/integrations/app-development/jira.md
  docs/integrations/app-development/jmx.md
  docs/integrations/app-development/puppet.md
  docs/integrations/cloud-security-monitoring-analytics/palo-alto-firewall-9.md
  docs/integrations/containers-orchestration/docker-community-edition.md
  docs/integrations/containers-orchestration/docker-ulm.md
  docs/integrations/containers-orchestration/vmware.md
  docs/integrations/global-intelligence/apache-tomcat.md
  docs/integrations/global-intelligence/apache.md
  docs/integrations/global-intelligence/nginx.md
  docs/integrations/google/workspace/install-app-dashboards.md
  docs/integrations/hosts-operating-systems/host-metrics.md
  docs/integrations/hosts-operating-systems/host-process-metrics.md
  docs/integrations/microsoft-azure/windows-legacy.md
  docs/integrations/pci-compliance/linux.md
  docs/integrations/pci-compliance/palo-alto-networks-9.md
  docs/integrations/saas-cloud/cisco-meraki-c2c.md
  docs/integrations/saas-cloud/druva.md
  docs/integrations/security-threat-detection/carbon-black-cloud.md
  docs/integrations/security-threat-detection/cisco-meraki.md
  docs/integrations/security-threat-detection/cloudpassage-halo.md
  docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection.md
  docs/integrations/security-threat-detection/palo-alto-networks-9.md
  docs/integrations/security-threat-detection/trend-micro-deep-security.md
  docs/integrations/security-threat-detection/zscaler-internet-access.md
Labels: cla-signed, do-not-merge

#3688 Update the change log in App Central for the integration
  docs/platform-services/automation-service/app-central/integrations/chronicle.md
  docs/platform-services/automation-service/app-central/integrations/recorded-future.md
  docs/platform-services/automation-service/app-central/integrations/screenshot-machine.md
Labels: cla-signed

#3689 CSIEM Release Notes for 2/19/24
  blog-cse/2024-01-12-content.md
  blog-cse/2024-01-30-content.md
  blog-cse/2024-02-02-content.md
  blog-cse/2024-02-13-content.md
  blog-cse/2024-02-19-application-update.md
  blog-cse/2024-02-19-content.md
Labels: cla-signed

#3686 Update download-collector-from-static-url.md
  docs/send-data/installed-collectors/collector-installation-reference/download-collector-from-static-url.md
Labels: cla-signed

#3690 App Central - Chronicle integration, change log updated
  docs/platform-services/automation-service/app-central/integrations/chronicle.md
Labels: cla-signed

#3692 Consolidate 2023 CSE Release Notes
  blog-cse/2023-01-05-content.md
  blog-cse/2023-01-13-content.md
  blog-cse/2023-01-19-application-update.md
  blog-cse/2023-01-20-content.md
  blog-cse/2023-02-08-content.md
  blog-cse/2023-02-13-application-update.md
  blog-cse/2023-02-17-content.md
  blog-cse/2023-02-22-application-update.md
  blog-cse/2023-02-22-content.md
  blog-cse/2023-02-24-content.md
  blog-cse/2023-03-02-content.md
  blog-cse/2023-03-07-application-update.md
  blog-cse/2023-03-10-content.md
  blog-cse/2023-03-15-content.md
  blog-cse/2023-03-16-application-update.md
  blog-cse/2023-03-24-content.md
  blog-cse/2023-03-31-content.md
  blog-cse/2023-04-07-content.md
  blog-cse/2023-04-13-application-update.md
  blog-cse/2023-04-13-content.md
  blog-cse/2023-04-20-content.md
  blog-cse/2023-04-21-application-update.md
  blog-cse/2023-04-28-content.md
  blog-cse/2023-05-03-application-update.md
  blog-cse/2023-05-05-content.md
  blog-cse/2023-05-12-content.md
  blog-cse/2023-05-26-content.md
  blog-cse/2023-06-02-content.md
  blog-cse/2023-06-12-application-update.md
  blog-cse/2023-06-20-application-update.md
  blog-cse/2023-06-22-content.md
  blog-cse/2023-06-29-application-update.md
  blog-cse/2023-06-29-content.md
  blog-cse/2023-07-11-content.md
  blog-cse/2023-07-13-application-update.md
  blog-cse/2023-07-14-content.md
  blog-cse/2023-07-21-application-update.md
  blog-cse/2023-07-21-content.md
  blog-cse/2023-08-03-content.md
  blog-cse/2023-08-04-content.md
  blog-cse/2023-08-22-application-update.md
  blog-cse/2023-08-22-content.md
  blog-cse/2023-09-07-content.md
  blog-cse/2023-09-11-application-update.md
  blog-cse/2023-09-21-application-update.md
  blog-cse/2023-09-22-content.md
  blog-cse/2023-10-02-application-update.md
  blog-cse/2023-10-11-content.md
  blog-cse/2023-10-18-application-update.md
  blog-cse/2023-10-26-application-update.md
  blog-cse/2023-10-26-content.md
  blog-cse/2023-11-01-application-update.md
  blog-cse/2023-11-02-content.md
  blog-cse/2023-11-13-content.md
  blog-cse/2023-11-17-application-update.md
  blog-cse/2023-12-06-application-update.md
  blog-cse/2023-12-14-application-update.md
  blog-cse/2023/12-31.md
Labels: cla-signed

#3691 Update sql-server-opentelemetry docs
  docs/integrations/microsoft-azure/opentelemetry/sql-server-opentelemetry.md
Labels: cla-signed, hot🔥

#3696 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#3697 App Central Integration Zscaler
  docs/platform-services/automation-service/app-central/integrations/zscaler.md
Labels: cla-signed

#3700 Mandiant logo replacement
  static/img/platform-services/automation-service/app-central/logos/mandiant-advantage-threat-intelligence.png
Labels: cla-signed

#3699 CSOAR-1555 - Add 'Publish an integration' section
  docs/cloud-soar/automation.md
  static/img/cloud-soar/export-button.png
Labels: doc:new, cla-signed, do-not-merge

#3698 Fix App Central index
  docs/platform-services/automation-service/app-central/index.md
  docs/platform-services/automation-service/automation-service-app-central.md
  docs/platform-services/automation-service/index.md
  sidebars.ts
Labels: cla-signed

#3674 Add app central integrations to product list
  docs/integrations/product-list.md
  static/img/integrations/misc/aws-iam-logo.png
  static/img/integrations/misc/aws-simple-notification-service-logo.png
  static/img/integrations/misc/ec2-logo.png
  static/img/integrations/misc/ibm-logo.png
  static/img/integrations/misc/microsoft-azure-logo.png
  static/img/integrations/misc/microsoft-defender-for endpoints-logo.png
Labels: doc:update, cla-signed

#3705 fix: use latest version of Otelcol in installattion docs
  docs/send-data/opentelemetry-collector/install-collector/linux.md
  docs/send-data/opentelemetry-collector/install-collector/macos.md
Labels: cla-signed

#3707 fix: update error when Otel collector deleted from UI
  docs/send-data/opentelemetry-collector/troubleshooting.md
Labels: cla-signed

#3709 feat: add `-Fips` option to Windows Otelcol installer
  docs/send-data/opentelemetry-collector/install-collector/windows.md
Labels: cla-signed

#3711 feat: add `-Version` option to Windows installation script
  docs/send-data/opentelemetry-collector/install-collector/windows.md
Labels: cla-signed

#3710 fix: fix TOC for Windows Otelcol installation
  docs/send-data/opentelemetry-collector/install-collector/windows.md
Labels: cla-signed

#3713 Update kubernetes / quickstart.md
  docs/observability/kubernetes/quickstart.md
Labels: cla-signed

#3704 Not allowing year in cron expression in scheduled searches
  docs/send-data/installed-collectors/sources/script-source/cron-examples-reference.md
Labels: cla-signed

#3714 Replace Metrics operators cheat sheet
  docs/metrics/metrics-operators/index.md
  static/files/metrics-operators-cheat-sheet.pdf
Labels: doc:minor edit, cla-signed

#3694 OT Remote Mgmt Beta
  docs/send-data/opentelemetry-collector/remote-management.md
  static/img/send-data/link-collectors.png
  static/img/send-data/linux-install.png
  static/img/send-data/linux-terminal-installation.png
  static/img/send-data/local-file-apache.png
Labels: cla-signed

#3716 Fix the Metrics operators cheat sheet... again
  docs/metrics/metrics-operators/index.md
Labels: doc:minor edit, cla-signed

#3717 Fix typo in Network Sensor Deployment Guide
  docs/cse/sensors/network-sensor-deployment-guide.md
Labels: doc:minor edit, cla-signed

#3715 Enable hideOnScroll feature
  docusaurus.config.js
Labels: cla-signed

#3719 Update kubernetes / install-helm-chart.md
  docs/send-data/kubernetes/install-helm-chart.md
Labels: cla-signed

#3720 Update asn-lookup.md
  docs/search/search-query-language/search-operators/asn-lookup.md
Labels: cla-signed

#3721 Fix threatlookup example
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed, hot🔥

#3722 Change link to Content Catalog
  docs/cse/cloud-siem-content-catalog.md
  docs/cse/ingestion/products-with-log-mappings.md
  docs/cse/ingestion/view-mappers-for-product.md
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/cse-built-in-rules.md
  docs/cse/rules/normalized-threat-rules.md
  docs/cse/schema/attributes-map-to-records.md
  docs/cse/schema/create-structured-log-mapping.md
  docs/cse/schema/cse-record-types.md
  docs/cse/schema/parser-editor.md
  docs/cse/schema/schema-attributes.md
Labels: cla-signed

#3602 Kanso - Closed Beta - docs and release notes (publish 2/26)
  blog-service/2024-02-23-ui.md
  docs/get-started/sumo-logic-ui-new.md
  docs/get-started/sumo-logic-ui.md
  sidebars.ts
  static/img/get-started/Close.png
  static/img/get-started/Dash3.png
  static/img/get-started/TUI_Search_Details.png
  static/img/get-started/WTS_UI_Add-dashboard-to-Favorites.png
  static/img/get-started/WTS_UI_Metrics-tab-options.png
  static/img/get-started/WTS_UI_Search-Save-and-Favorite.png
  static/img/get-started/acct-pref.png
  static/img/get-started/admin-config.png
  static/img/get-started/admin-expanded.png
  static/img/get-started/admin.png
  static/img/get-started/config.png
  static/img/get-started/dashboard-searches.png
  static/img/get-started/favorite-saved-search.png
  static/img/get-started/favs.png
  static/img/get-started/github/activate-sumo-trial-account.png
  static/img/get-started/github/activate-trial.gif
  static/img/get-started/github/close-icon.png
  static/img/get-started/github/create-access-key.gif
  static/img/get-started/github/github-access-token.png
  static/img/get-started/github/github-pull-requests-dashboard.gif
  static/img/get-started/github/start-free-trial.png
  static/img/get-started/github/sumo-logic-access-token.png
  static/img/get-started/hamburger.gif
  static/img/get-started/library-content-admin.gif
  static/img/get-started/library-search.png
  static/img/get-started/library.png
  static/img/get-started/pin-search.png
  static/img/get-started/pin2.png
  static/img/get-started/pinmessage.png
  static/img/get-started/recent.png
  static/img/get-started/switch-new-ui.png
  static/img/get-started/tabs.png
  static/img/get-started/ui/Account.png
  static/img/get-started/ui/Appcatalog.png
  static/img/get-started/ui/Dash3.png
  static/img/get-started/ui/Home.png
  static/img/get-started/ui/Learn.png
  static/img/get-started/ui/ManageData.png
  static/img/get-started/ui/ManageNewUI.png
  static/img/get-started/ui/NewUItabs.png
  static/img/get-started/ui/WTS_UI_Certification.png
  static/img/get-started/ui/WTS_UI_Learn-Page.png
  static/img/get-started/ui/WTS_UI_Manage-Data_menu-options.png
  static/img/get-started/ui/WTS_UI_Search-Metrics-LiveTail.png
  static/img/get-started/ui/favorite.png
  static/img/get-started/ui/home-icons.png
  static/img/get-started/ui/icon-left-nav-favorites.png
  static/img/get-started/ui/icon-left-nav-library.png
  static/img/get-started/ui/icon-left-nav-org.png
  static/img/get-started/ui/icon-left-nav-recent.png
  static/img/get-started/ui/icon-left-nav-search.png
  static/img/get-started/ui/left-nav.png
  static/img/get-started/ui/new-icons.png
  static/img/get-started/ui/pin-search.png
  static/img/get-started/ui/ui-tab-arrows.png
  static/img/release-notes/service/demo-new-ui-beta.gif
Labels: cla-signed, do-not-merge

#3728 20240219 soar release notes
  blog-csoar/2024-02-23-application-update.md
Labels: cla-signed

#3723 Update Cloud SIEM automation benefits section
  docs/cse/automation/about-automation-service-and-cloud-siem.md
Labels: doc:update, cla-signed

#3724 CONN-2906 - Add API root URLs setting to "STIX/TAXII 2 Client Source" article
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
Labels: doc:update, cla-signed

#3725 Update links in palo-alto-networks-9 doc
  docs/integrations/security-threat-detection/palo-alto-networks-9.md
Labels: cla-signed

#3726 App Central Integration Snowflake
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/app-central/integrations/snowflake.md
  static/img/platform-services/automation-service/app-central/integrations/snowflake/snowflake-1.png
  static/img/platform-services/automation-service/app-central/integrations/snowflake/snowflake-2.png
  static/img/platform-services/automation-service/app-central/integrations/snowflake/snowflake-3.png
  static/img/platform-services/automation-service/app-central/integrations/snowflake/snowflake-4.png
  static/img/platform-services/automation-service/app-central/integrations/snowflake/snowflake-5.png
  static/img/platform-services/automation-service/app-central/integrations/snowflake/snowflake-6.png
  static/img/platform-services/automation-service/app-central/integrations/snowflake/snowflake-7.png
  static/img/platform-services/automation-service/app-central/logos/snowflake.png
Labels: cla-signed

#3702 Update search-templates.md
  docs/search/get-started-with-search/build-search/search-templates.md
Labels: cla-signed

#3729 CSOAR-1149: Add csoar-automation-bridge on Docker documentation
  docs/cloud-soar/cloud-soar-bridge.md
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: cla-signed

#3733 20240219 soar release notes fix date
  blog-csoar/2024-02-19-application-update.md
Labels: cla-signed

#3679 Add RBAC for Cloud SOAR Delivery 2
  docs/manage/users-roles/roles/role-capabilities.md
Labels: doc:new, cla-signed, do-not-merge

#3735 App Central Integration GreyNoise
  docs/platform-services/automation-service/app-central/integrations/greynoise.md
Labels: cla-signed

#3730 CONN-2914 Add New JFrog Cloud-To-Cloud Source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jfrog-xray.md
  sidebars.ts
  static/files/c2c/jfrog-xray/example.json
  static/files/c2c/jfrog-xray/example.tf
  static/img/integrations/security-threat-detection/jfrog.png
Labels: cla-signed

#3727 chore(k8s-instr): update documentation about possible customization
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-kubernetes-environments.md
Labels: cla-signed

#3736 App Central Integration changelog updated
  docs/platform-services/automation-service/app-central/integrations/chronicle.md
  docs/platform-services/automation-service/app-central/integrations/mail-tools.md
  docs/platform-services/automation-service/app-central/integrations/recorded-future.md
  docs/platform-services/automation-service/app-central/integrations/screenshot-machine.md
Labels: cla-signed

#3687 Update citrix-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
Labels: cla-signed, do-not-merge

#3708 Update jumpcloud-directory-insights-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
Labels: cla-signed, do-not-merge

#3732 Added metadata section for code42-incydr-source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/code42-incydr-source.md
Labels: cla-signed, do-not-merge

#3738 Small JFrog Xray fixes
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/product-list.md
Labels: doc:minor edit, cla-signed

#3739 February 27, 2024 - Content Release
  blog-csoar/2024-02-27-content.md
Labels: cla-signed

#3741 CSOAR-1149: Remove last piece of docs, because no needed
  docs/cloud-soar/cloud-soar-bridge.md
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: cla-signed

#3742 Installing the apps doc update
  docs/get-started/apps-integrations.md
Labels: cla-signed

#3747 chore: update opentelemetry java instrumentation documentation
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/custom-tags-configuration.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/traceid-spanid-injection-into-logs-configuration.md
Labels: cla-signed

#3743 INVS-2087 - killChain attribute
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:update, cla-signed

#3744 Test playbooks in the Automation Service
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/platform-services/automation-service/automations-playbook-run-test.png
  static/img/platform-services/automation-service/automations-playbook-test-playbook.png
  static/img/platform-services/automation-service/automations-playbook-test-results-filtered.png
  static/img/platform-services/automation-service/automations-playbook-test-results.png
Labels: doc:new, cla-signed

#3748 App central integration aws security hub
  docs/platform-services/automation-service/app-central/integrations/aws-security-hub.md
Labels: cla-signed

#3751 App Central Integration Mimecast
  docs/platform-services/automation-service/app-central/integrations/mimecast.md
Labels: cla-signed

#3752 App Central Integration Darktrace
  docs/platform-services/automation-service/app-central/integrations/darktrace.md
Labels: cla-signed

#3753 SUMO-126818 - Add note about localhost error
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
Labels: doc:minor edit, cla-signed

#3750 JSON formatting issue fixed
  docs/send-data/installed-collectors/collector-installation-reference/add-collector-linux-machine-image.md
Labels: cla-signed

#3754 Release notes fixes and archiving 2023 posts
  blog-collector/2015/12-31.md
  blog-collector/2016/12-31.md
  blog-collector/2017/12-31.md
  blog-collector/2018/12-31.md
  blog-collector/2019/12-31.md
  blog-collector/2020/12-31.md
  blog-collector/2021/12-31.md
  blog-collector/2022/12-31.md
  blog-collector/2023-03-15.md
  blog-collector/2023-04-20.md
  blog-collector/2023-05-05.md
  blog-collector/2023-05-23.md
  blog-collector/2023-07-11.md
  blog-collector/2023-08-22.md
  blog-collector/2023-10-26.md
  blog-collector/2023-11-13.md
  blog-collector/2023/12-31.md
  blog-collector/2024-01-25.md
  blog-cse/2022/12-31.md
  blog-cse/2023/12-31.md
  blog-cse/2024-02-19-application-update.md
  blog-csoar/2023-06-08-first-release-note.md
  blog-csoar/2023-10-20-application-update.md
  blog-csoar/2023-10-23-content.md
  blog-csoar/2023-11-01-application-update.md
  blog-csoar/2023-11-16-application-update.md
  blog-csoar/2023-11-20-content.md
  blog-csoar/2023-12-04-application-update.md
  blog-csoar/2023/12-31.md
  blog-csoar/2024-01-03-application-update.md
  blog-csoar/2024-01-30-application-update.md
  blog-csoar/2024-02-19-application-update.md
  blog-developer/2018/12-31.md
  blog-developer/2019/12-31.md
  blog-developer/2020/12-31.md
  blog-developer/2021/12-31.md
  blog-developer/2022/12-31.md
  blog-developer/2023/12-31.md
  blog-service/2016/12-31.md
  blog-service/2017/12-31.md
  blog-service/2018/12-31.md
  blog-service/2019/12-31.md
  blog-service/2020/12-31.md
  blog-service/2021/12-31.md
  blog-service/2022/12-31.md
  blog-service/2023/12-31.md
  community/get-started/setup.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-filevantage.md
Labels: cla-signed

#3745 Actions limit /reuse text
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/platform-services/automation-service/automation-service-app-central.md
  docs/platform-services/automation-service/automation-service-integrations.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/reuse/action-limits.md
  docs/reuse/actions-limit.md
Labels: cla-signed

#3757 Kanso FAQs
  docs/get-started/sumo-logic-ui-new.md
  static/img/get-started/return-to-classic.png
Labels: cla-signed

#3758 Minor addt'l fixes - release notes
  blog-service/2024-01-02-index-field.md
  blog-service/2024-01-11-manage.md
  blog-service/2024-01-15-active-directory-app-update.md
  blog-service/2024-01-18-search.md
  blog-service/2024-01-19-aws-for-cis.md
  blog-service/2024-01-30-metrics.md
  blog-service/2024-02-06-manage.md
  blog-service/2024-02-07-collection.md
  blog-service/2024-02-23-ui.md
Labels: cla-signed

#3746 HipChat webhook connection - obsolete
  blog-cse/2022/12-31.md
  blog-service/2018/12-31.md
  blog-service/2022/12-31.md
  blog-service/2024-02-29-apps.md
  cid-redirects.json
  docs/alerts/webhook-connections/hipchat.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/contributing/glossary.md
  docs/cse/administration/create-cse-actions.md
  docs/cse/administration/custom-inventory-sources.md
  docs/integrations/product-list.md
  docs/metrics/introduction/index.md
  docs/observability/sdo/set-up-sdo/sdo-setup-with-terraform-script.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/index.md
  sidebars.ts
Labels: cla-signed
