Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-05, with the labels that each got.

#4039 Update deprecation.md
  docs/alerts/scheduled-searches/deprecation.md
Labels: cla-signed

#4040 Snowflake redirect
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#3896 Copilot - Customer Preview
  docs/search/copilot.md
  static/img/search/copilot/chart-types.png
  static/img/search/copilot/code-editor.png
  static/img/search/copilot/copilot-json.png
  static/img/search/copilot/copilot-logo.png
  static/img/search/copilot/copilot-tab.png
  static/img/search/copilot/explore.png
  static/img/search/copilot/feedback-thumbs.png
  static/img/search/copilot/new-conversation.png
  static/img/search/copilot/open-in-log-search.png
  static/img/search/copilot/play.png
  static/img/search/copilot/refine.png
  static/img/search/copilot/search-button.png
  static/img/search/copilot/show-hide-query.gif
  static/img/search/copilot/source-category.png
  static/img/search/copilot/time-period.png
Labels: doc:new, cla-signed, do-not-merge

#4044 Fix suggested NetworkPolicies for otel metrics
  docs/send-data/kubernetes/security-best-practices.md
Labels: cla-signed

#4042 added the new action
  docs/platform-services/automation-service/app-central/integrations/lacework.md
Labels: cla-signed

#4043 Adding sumo fields which are required by the s3m otel apps to work
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
Labels: cla-signed

#4045 Create 2024-05-02-content.md
  blog-cse/2024-05-02-content.md
Labels: cla-signed

#4046 Update collect-logs-palo-alto-networks-cortex.md
  docs/send-data/collect-from-other-data-sources/collect-logs-palo-alto-networks-cortex.md
Labels: cla-signed

#4047 Add C2C page for Snowflake source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/snowflake-sql-api.md
  static/files/c2c/snowflake-sql-api/example.json
  static/files/c2c/snowflake-sql-api/example.tf
  static/files/c2c/snowflake-sql-api/metrics_example.json
  static/files/c2c/snowflake-sql-api/metrics_schema.json
  static/img/integrations/security-threat-detection/snowflake.png
Labels: cla-signed

#4048 Update flex app doc
  docs/integrations/sumo-apps/flex.md
Labels: cla-signed

#4050 Bg automation service monitor payload
  cid-redirects.json
  docs/alerts/monitors/automation-payload-variables.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  sidebars.ts
  static/img/alerts/parse_from_alert.png
  static/img/alerts/parse_from_json.png
  static/img/alerts/parse_from_json_parameters.png
  static/img/alerts/parse_from_json_payload.png
  static/img/alerts/playbook_payload.png
Labels: doc:new, cla-signed

#4051 Add cards to the Monitors section
  docs/alerts/monitors/index.md
  sidebars.ts
Labels: doc:update, cla-signed

#4053 Small update to Cloud SOAR integration framework
  docs/cloud-soar/cloud-soar-integration-framework.md
Labels: doc:minor edit, cla-signed

#4032 Azure hubs doc reference updated (Rich App)
  docs/integrations/microsoft-azure/active-directory-azure.md
  docs/integrations/microsoft-azure/audit.md
  docs/integrations/microsoft-azure/kubernetes.md
  docs/integrations/microsoft-azure/sql.md
  docs/integrations/microsoft-azure/web-apps.md
Labels: cla-signed

#4011 Azure doc-only apps doc update
  docs/integrations/microsoft-azure/azure-analysis-services.md
  docs/integrations/microsoft-azure/azure-api-management.md
  docs/integrations/microsoft-azure/azure-app-configuration.md
  docs/integrations/microsoft-azure/azure-app-service-environment.md
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-automation.md
  docs/integrations/microsoft-azure/azure-backup.md
  docs/integrations/microsoft-azure/azure-batch.md
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
  docs/integrations/microsoft-azure/azure-cognitive-search.md
  docs/integrations/microsoft-azure/azure-cosmos-db-for-postgresql.md
  docs/integrations/microsoft-azure/azure-cosmos-db.md
  docs/integrations/microsoft-azure/azure-data-explorer.md
  docs/integrations/microsoft-azure/azure-data-factory.md
  docs/integrations/microsoft-azure/azure-database-for-mariadb.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/microsoft-azure/azure-database-for-postgresql.md
  docs/integrations/microsoft-azure/azure-event-grid.md
  docs/integrations/microsoft-azure/azure-event-hubs.md
  docs/integrations/microsoft-azure/azure-front-door.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-iot-hub.md
  docs/integrations/microsoft-azure/azure-key-vault.md
  docs/integrations/microsoft-azure/azure-logic-app.md
  docs/integrations/microsoft-azure/azure-machine-learning.md
  docs/integrations/microsoft-azure/azure-notification-hubs.md
  docs/integrations/microsoft-azure/azure-public-ipAddress.md
  docs/integrations/microsoft-azure/azure-relay.md
  docs/integrations/microsoft-azure/azure-service-bus.md
  docs/integrations/microsoft-azure/azure-sql-managed-instance.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/azure-stream-analytics.md
  docs/integrations/microsoft-azure/azure-synapse-analytics.md
  docs/integrations/microsoft-azure/microsoft-dynamics365-customer-insights.md
Labels: cla-signed

#4061 Updated allowed character length to 15k
  docs/alerts/monitors/create-monitor.md
Labels: cla-signed

#4060 DOCS-158 - Add new UI hidden instructions for Observability (Kanso)
  docs/observability/application-components.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/centralized-aws-cloudtrail-log-collection.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/observability/kubernetes/monitoring.md
  docs/observability/kubernetes/troubleshoot-with-explore.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/observability/reliability-management-slo/dashboards.md
  docs/observability/reliability-management-slo/index.md
  docs/observability/sdo/jenkins-plugin-build-deploy-events.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
  docs/observability/sdo/set-up-sdo/sdo-setup-with-terraform-script.md
  static/img/kubernetes/TSS_Cluster_Pods-Running_panel.png
Labels: doc:update, cla-signed

#4059 Minor fix for Copilot
  docs/search/copilot.md
Labels: cla-signed

#4055 Fixes for Apps and Integrations docs and logos
  docs/integrations/amazon-aws/index.md
  docs/integrations/app-development/github.md
  docs/integrations/app-development/index.md
  docs/integrations/cloud-security-monitoring-analytics/index.md
  docs/integrations/containers-orchestration/index.md
  docs/integrations/databases/index.md
  docs/integrations/global-intelligence/index.md
  docs/integrations/google/index.md
  docs/integrations/hosts-operating-systems/index.md
  docs/integrations/index.md
  docs/integrations/microsoft-azure/arm-integration-faq.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/pci-compliance/index.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saml/index.md
  docs/integrations/security-threat-detection/index.md
  docs/integrations/web-servers/index.md
  docs/send-data/hosted-collectors/configure-hosted-collector.md
  static/img/integrations/app-development/GitHub.png
  static/img/integrations/containers-orchestration/containers.png
  static/img/integrations/containers-orchestration/k8s.png
  static/img/integrations/databases/databases-icon.png
  static/img/integrations/google/google-logo.png
  static/img/integrations/google/google.png
  static/img/integrations/hosts-operating-systems/hosts.png
  static/img/integrations/microsoft-azure/azure-faq.png
  static/img/integrations/microsoft-azure/azure-logo.png
  static/img/integrations/microsoft-azure/microsoft-logo.png
  static/img/integrations/saml/saml.png
  static/img/integrations/web-servers/web-servers.png
  static/img/send-data/cloudquery-logo.png
Labels: cla-signed

#4063 DOCS-160 - Add new UI hidden menus for APM (Kanso)
  docs/apm/real-user-monitoring/configure-data-collection.md
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/real-user-monitoring/index.md
  docs/apm/traces/get-started-transaction-tracing/http-traces-source.md
  docs/apm/traces/quickstart.md
  docs/apm/traces/search-query-language-support-for-traces.md
  docs/apm/traces/services-list-map.md
  docs/apm/traces/spans.md
  docs/apm/traces/tracing-dashboards.md
  docs/apm/traces/view-and-investigate-traces.md
Labels: doc:update, cla-signed

#4057 DOCS-157 - Add new UI hidden instructions for Dashboards (Kanso)
  docs/dashboards/create-dashboard-new.md
  docs/dashboards/dashboards-migration/steps-to-migrate.md
  docs/dashboards/explore-view.md
  docs/dashboards/locate-deviations-time-series.md
  docs/dashboards/share-dashboard-outside-org.md
  static/img/dashboards-new/share-option.png
  static/img/dashboards-new/share-option_2.png
Labels: doc:update, cla-signed

#4041 DOCS-147 - Add hidden instructions for Cloud SOAR (Kanso)
  docs/cloud-soar/audit-event-index.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/cloud-soar-bridge.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/legacy/legacy-global-functions-menu.md
  docs/cloud-soar/overview.md
  docs/platform-services/automation-service/automation-service-audit-logging.md
  docs/search/get-started-with-search/search-basics/about-search-basics.md
  static/img/cloud-soar/cog.png
  static/img/cloud-soar/image62.png
  static/img/search/get-started-search/search-basics/new-log-search-UI-buttons.png
Labels: doc:update, cla-signed

#4067 Updates to query examples
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
Labels: doc:update, cla-signed, hot🔥

#4056 [CONN-3153] CloudQuery Azure plugin C2C source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-azure-plugin-source.md
  static/files/c2c/cloudquery-azure-plugin/example.json
Labels: cla-signed

#4003 feat(k8s collection): document how to use only docker hub registry
  docs/send-data/kubernetes/best-practices.md
Labels: cla-signed

#4070 Remove release note
  blog-service/2024-05-08-manage.md
Labels: doc:update, cla-signed, hot🔥

#4072 DOCS-171 - Fix duplicate 'Logs Data Forwarding' entry in left nav
  sidebars.ts
Labels: doc:minor edit, cla-signed

#4073 Update aws-privatelink.md
  docs/integrations/amazon-aws/aws-privatelink.md
Labels: cla-signed

#4071 DOCS-170 - Fix dashboard screenshots for Data Volume App
  docs/integrations/sumo-apps/data-volume.md
  static/img/integrations/sumo-apps/Data-Volume-Logs.png
Labels: doc:minor edit, cla-signed

#4074 CloudQuery Azure CID
  cid-redirects.json
Labels: cla-signed

#4049 Docusaurus v3.3 upgrade
  docusaurus.config.js
  package.json
  yarn.lock
Labels: doc:site tech, cla-signed, dependencies

#4080 Add license variable to package.json
  package.json
Labels: cla-signed

#4013 DOCS-70 - CloudQuery preview for CIS for AWS
  blog-service/2024-05-13-apps.md
  docs/integrations/amazon-aws/cloud-infrastructure-security-for-aws.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#4077 Removed RSA banner from header
  docusaurus.config.js
Labels: cla-signed

#4083 Remove tags from beta docs
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-azure-plugin-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/snowflake-sql-api.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
Labels: doc:site tech, cla-signed

#4078 Slack webhook - add note about using blocks
  docs/alerts/webhook-connections/slack.md
Labels: cla-signed

#4081 Misc. fixes found during Kanso updates
  blog-service/2024-02-23-ui.md
  docs/apm/traces/get-started-transaction-tracing/http-traces-source.md
  docs/dashboards/locate-deviations-time-series.md
  docs/get-started/sumo-logic-ui-new.md
  docs/observability/application-components.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
Labels: cla-signed

#4082 Add documentation for namespace annotations
  docs/send-data/kubernetes/best-practices.md
Labels: cla-signed

#4084 Redirect for Metrics DPM
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#4065 DOCS-162 - Add new UI hidden instructions to Metrics (Kanso)
  docs/metrics/introduction/index.md
  docs/metrics/logs-to-metrics.md
  docs/metrics/manage-metric-volume/data-limits-for-metrics.md
  docs/metrics/manage-metric-volume/disabled-metrics-sources.md
  docs/metrics/manage-metric-volume/metric-throttling.md
  docs/metrics/metric-rules-editor.md
  docs/metrics/metrics-queries/metrics-explorer.md
  docs/metrics/metrics-transformation-rules.md
  static/img/metrics/disabled-ltm.png
  static/img/metrics/log-to-metrics-add.png
Labels: doc:update, cla-signed

#4066 DOCS-164 - Add new UI hidden instructions for Alerts (Kanso)
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/muting-schedules.md
  docs/alerts/monitors/settings.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/alerts/webhook-connections/aws-lambda.md
  docs/alerts/webhook-connections/cloud-soar.md
  docs/alerts/webhook-connections/datadog.md
  docs/alerts/webhook-connections/index.md
  docs/alerts/webhook-connections/jira-cloud.md
  docs/alerts/webhook-connections/jira-server.md
  docs/alerts/webhook-connections/jira-service-desk.md
  docs/alerts/webhook-connections/microsoft-azure-functions.md
  docs/alerts/webhook-connections/microsoft-teams.md
  docs/alerts/webhook-connections/new-relic.md
  docs/alerts/webhook-connections/opsgenie-legacy.md
  docs/alerts/webhook-connections/opsgenie.md
  docs/alerts/webhook-connections/pagerduty.md
  docs/alerts/webhook-connections/servicenow/set-up-connections.md
  docs/alerts/webhook-connections/servicenow/set-up-security-incident-webhook.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/alerts/webhook-connections/signl4.md
  docs/alerts/webhook-connections/slack.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  static/img/alerts/alert-preferences.png
Labels: doc:update, cla-signed

#4037 DOCS-44 - Override global signal suppression for Cloud SIEM
  docs/cse/records-signals-entities-insights/about-signal-suppression.md
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-chain-rule.md
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-match-rule.md
  docs/cse/rules/write-outlier-rule.md
  docs/cse/rules/write-threshold-rule.md
  static/img/cse/override-global-signal-suppression-grouped-by.png
  static/img/cse/override-global-signal-suppression.png
Labels: doc:new, cla-signed, do-not-merge

#4087 CID number added for CloudQuery source
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
  sidebars.ts
Labels: cla-signed

#4090 Fix preview links in CIS for AWS
  docs/integrations/amazon-aws/cloud-infrastructure-security-for-aws.md
Labels: doc:minor edit, cla-signed

#4086 Deleted the deprecated apps docs
  blog-service/2017/12-31.md
  blog-service/2021/12-31.md
  cid-redirects.json
  docs/get-started/faq.md
  docs/integrations/app-development/jfrog-artifactory.md
  docs/integrations/global-intelligence/nginx.md
  docs/integrations/microsoft-azure/active-directory-legacy.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/windows-legacy-pci-compliance.md
  docs/integrations/pci-compliance/index.md
  docs/integrations/product-list.md
  docs/integrations/security-threat-detection/index.md
  docs/integrations/security-threat-detection/palo-alto-networks-6.md
  docs/integrations/security-threat-detection/palo-alto-networks-8.md
  docs/integrations/web-servers/index.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx-legacy.md
  docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
  sidebars.ts
Labels: cla-signed

#4091 Remove references to pre-Bento UI
  docs/contributing/word-list.md
  docs/metrics/metrics-operators/outlier.md
  docs/search/get-started-with-search/search-basics/comments-search-queries.md
  docs/send-data/collection/processing-rules/create-processing-rule.md
Labels: cla-signed

#4092 Fixes to Sched Searches and Alerts to prep for AI/ML hub
  blog-service/2016/12-31.md
  blog-service/2020/12-31.md
  cid-redirects.json
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/overview.md
  docs/alerts/scheduled-searches/create-email-alert.md
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/edit-cancel.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/scheduled-searches/generate-cse-signals.md
  docs/alerts/scheduled-searches/index.md
  docs/alerts/scheduled-searches/receive-email-alerts.md
  docs/alerts/scheduled-searches/run-search-from-alert-email.md
  docs/alerts/scheduled-searches/save-to-index.md
  docs/alerts/scheduled-searches/save-to-lookup.md
  docs/alerts/scheduled-searches/schedule-search.md
  docs/alerts/webhook-connections/servicenow/index.md
  docs/alerts/webhook-connections/servicenow/launch-investigations.md
  docs/api/field-extraction-rules.md
  docs/apm/real-user-monitoring/metrics.md
  docs/contributing/glossary.md
  docs/get-started/onboarding-checklists.md
  docs/integrations/amazon-aws/amazon-athena.md
  docs/integrations/pci-compliance/index.md
  docs/manage/field-extractions/index.md
  docs/manage/security/audit-indexes/audit-index.md
  docs/observability/aws/about.md
  docs/observability/diagnose-issues.md
  docs/search/behavior-insights/logreduce-values.md
  docs/search/get-started-with-search/suggested-searches/apache-errors-parser.md
  docs/search/search-query-language/parse-operators/index.md
  docs/send-data/installed-collectors/sources/script-action.md
  i18n/ja/alerts/alerts/scheduled-searches/index.md
  sidebars.ts
  static/img/connection-and-integration/connections.png
Labels: cla-signed

#4069 CloudQuery-GCP C2C doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-gcp-source.md
  static/files/c2c/cloudquery-gcp/example.json
  static/files/c2c/cloudquery-gcp/example.tf
Labels: cla-signed

#4095 new integration Cyberint
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/cyberint.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  static/img/platform-services/automation-service/app-central/logos/cyberint.png
Labels: cla-signed

#4100 Create 2024-05-15-content.md
  blog-cse/2024-05-15-content.md
Labels: cla-signed

#4101 CSIEM Release Note 2024-05-15
  blog-cse/2024-05-15-application-update.md
  static/img/release-notes/cse/csiem-rule-signal-suppression.jpg
Labels: cla-signed

#4102 CONN-3223: added limitation in crowdstrike-filevantage.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-filevantage.md
Labels: cla-signed

#4099 DOCS-183 - Add new UI hidden instructions for Log Search
  docs/search/get-started-with-search/build-search/dynamic-parsing.md
  docs/search/get-started-with-search/search-basics/about-search-basics.md
  docs/search/get-started-with-search/search-basics/comments-search-queries.md
  docs/search/get-started-with-search/search-basics/quick-search-collectors-sources.md
  docs/search/get-started-with-search/search-page/search-modes.md
  docs/search/live-tail/about-live-tail.md
  docs/search/lookup-tables/create-lookup-table.md
  docs/search/optimize-search-partitions.md
Labels: doc:update, cla-signed

#4098 DOCS-181 - Add new UI hidden instructions for Get Started and Contributing (Kanso)
  docs/get-started/account-settings-preferences.md
  docs/get-started/help.md
  docs/get-started/library.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/overview.md
  docs/get-started/quickstart.md
  docs/get-started/training-certification-faq.md
  docs/reuse/apps/app-install-index-apps-v2.md
  docs/reuse/apps/app-install-sumo-apps.md
  docs/reuse/apps/app-install-v2.md
  docs/reuse/apps/app-install.md
  static/img/get-started/WTS_Apps-Catalog.png
  static/img/get-started/WTS_Collection_Page.png
  static/img/get-started/WTS_Collector_page.png
  static/img/get-started/Welcome_learn.png
  static/img/get-started/certifications.png
  static/img/get-started/check-role.png
  static/img/get-started/library/SearchSuggestions.png
  static/img/get-started/library/StarredFolders.png
  static/img/get-started/library/personal-folder.png
  static/img/get-started/view-as.png
Labels: doc:update, cla-signed

#3933 AWSO 2.8.0 changes
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/integrations/amazon-rds.md
  docs/observability/aws/integrations/aws-api-gateway.md
  docs/observability/aws/integrations/global-intelligence-cloudtrail-devops.md
  docs/observability/aws/integrations/index.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
  sidebars.ts
  static/img/observability/Multiaccount_5.png
Labels: cla-signed

#3991 AWS Observability 2.8.0 - Release notes
  blog-service/2024-05-17-awso.md
Labels: cla-signed

#4105 DOCS-189 - Fix broken link in Google Cloud Logging article
  docs/integrations/google/cloud-logging.md
Labels: doc:minor edit, cla-signed

#4093 Monitor Enhancements release notes
  blog-service/2024-04-16-apps.md
Labels: cla-signed, do-not-merge

#4096 Classic Apps to Next-Gen Apps Migration release notes
  blog-service/2024-04-26-apps.md
Labels: cla-signed

#4089 API Gateway release notes
  blog-service/2024-03-13-apps.md
Labels: cla-signed

#4106 chore(lambda): nodejs add information about ctx propagation
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
Labels: cla-signed

#4094 Azure Blob Storage Collection Update release note
  blog-service/2024-02-09-apps.md
Labels: cla-signed

#4097 VMware Tanzu Application Service release notes
  blog-service/2024-04-18-apps.md
Labels: cla-signed

#4109 DOCS-187 - Update hard-coded links
  blog-collector/2022/12-31.md
  docs/api/content-permissions.md
  docs/api/dynamic-parsing.md
  docs/api/field-management.md
  docs/api/monitors-management.md
  docs/api/partition-management.md
  docs/api/policies-management.md
  docs/api/role-management.md
  docs/api/user-management.md
  docs/cloud-soar/automation.md
  docs/contributing/create-edit-doc.md
  docs/contributing/templates/c2c-source.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/integrations/google/cloud-functions.md
  docs/integrations/google/cloud-sql.md
  docs/integrations/partner-ecosystem-apps.md
  docs/manage/security/saml/set-up-saml.md
  docs/metrics/metrics-operators/index.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-log-analytics.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications.md
  docs/platform-services/automation-service/automation-service-bridge.md
  docs/reuse/actions-limit.md
  docs/search/search-cheat-sheets/log-operators.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/ms-azure-event-hubs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/source-info.md
  docs/send-data/kubernetes/collecting-events.md
  docs/send-data/kubernetes/v4/important-changes.md
  docs/send-data/opentelemetry-collector/auto-discovery.md
Labels: doc:update, cla-signed

#4112 Update cloud-sql.md
  docs/integrations/google/cloud-sql.md
Labels: cla-signed

#4110 Remove "save operator not supported" as it is supported and there are…
  docs/alerts/scheduled-searches/save-to-lookup.md
Labels: cla-signed

#4113 App Central Integration - Chronicle
  docs/platform-services/automation-service/app-central/integrations/chronicle.md
Labels: cla-signed

#4103 Create monitors using the App Catalog info added
  docs/alerts/monitors/create-monitor.md
  docs/integrations/sumo-apps/audit.md
  docs/reuse/apps/create-monitors.md
Labels: cla-signed

#4115 DOCS-159 - Rework Explore article (Kanso)
  blog-service/2023/12-31.md
  docs/apm/real-user-monitoring/dashboards.md
  docs/contributing/glossary.md
  docs/dashboards/about.md
  docs/dashboards/explore-view.md
  docs/dashboards/index.md
  docs/dashboards/link-dashboards.md
  docs/get-started/sumo-logic-ui-new.md
  docs/integrations/amazon-aws/api-gateway.md
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/dynamodb.md
  docs/integrations/amazon-aws/ec2-cloudwatch-metrics.md
  docs/integrations/amazon-aws/eks-control-plane.md
  docs/integrations/amazon-aws/elastic-container-service-container-insights-cloudwatch.md
  docs/integrations/amazon-aws/elasticache.md
  docs/integrations/amazon-aws/lambda.md
  docs/integrations/amazon-aws/network-load-balancer.md
  docs/integrations/amazon-aws/rds.md
  docs/integrations/amazon-aws/sns.md
  docs/integrations/amazon-aws/sqs.md
  docs/integrations/containers-orchestration/kubernetes-control-plane.md
  docs/integrations/containers-orchestration/kubernetes.md
  docs/integrations/global-intelligence/kubernetes-devops.md
  docs/integrations/google/kubernetes-engine.md
  docs/integrations/microsoft-azure/kubernetes.md
  docs/observability/application-components.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/faq.md
  docs/observability/aws/integrations/amazon-rds.md
  docs/observability/aws/integrations/aws-api-gateway.md
  docs/observability/aws/integrations/aws-application-load-balancer.md
  docs/observability/aws/integrations/aws-classic-load-balancer.md
  docs/observability/aws/integrations/aws-dynamodb.md
  docs/observability/aws/integrations/aws-ec2-host-metrics.md
  docs/observability/aws/integrations/aws-lambda.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/observability/aws/other-configurations-tools/index.md
  docs/observability/host-list-beta.md
  docs/observability/kubernetes/index.md
  docs/observability/kubernetes/monitoring.md
  docs/observability/kubernetes/quickstart.md
  docs/observability/kubernetes/troubleshoot-with-explore.md
  docs/observability/root-cause-explorer.md
  docs/reuse/apps/create-aws-s3-source.md
  docs/send-data/kubernetes/install-helm-chart.md
  static/img/dashboards-new/explore/apm-service-view.png
  static/img/dashboards-new/explore/aws-view.png
  static/img/dashboards-new/explore/k8s-view.png
  static/img/dashboards-new/explore/real-user-monitoring.png
Labels: doc:update, cla-signed

#4117 ListObjectVersions --> ListBucketVersions
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
Labels: cla-signed

#4119 Update deprecation.md
  docs/alerts/scheduled-searches/deprecation.md
Labels: cla-signed

#4120 Disable /reuse/ directory from search engine results
  static/robots.txt
Labels: cla-signed

#4036 Include partition in default scope feature info added in the Flex doc
  docs/manage/partitions/flex/create-edit-partitions-flex.md
  static/img/partitions-data-tiers/create-new-partition-flex.png
  static/img/partitions-data-tiers/edit-partition-pane-flex.png
  static/img/partitions-data-tiers/partitions-page-flex.png
  static/img/partitions-data-tiers/view-edit-partition-pane-flex.png
Labels: cla-signed

#4122 updated the action
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-v2.md
Labels: cla-signed

#4126 DOCS-193 - Index Access behavior section
  .github/workflows/pr.yml
  docs/cloud-soar/cloud-soar-integration-framework.md
  docs/contributing/code-of-conduct.md
  docs/contributing/remove-doc.md
  docs/integrations/amazon-aws/redshift-ulm.md
  docs/integrations/global-intelligence/nginx.md
  docs/integrations/web-servers/nginx-plus.md
  docs/manage/field-extractions/fer-templates/apache-access-logs.md
  docs/manage/users-roles/roles/create-manage-roles.md
  docs/manage/users-roles/roles/rbac-for-indexes.md
  docs/reuse/apps/create-monitors.md
  docs/send-data/kubernetes/troubleshoot-collection.md
  docs/send-data/opentelemetry-collector/auto-discovery.md
Labels: doc:new, cla-signed

#4127 DOCS-204 - Corrections to the F5 BIG-IP article
  docs/integrations/security-threat-detection/f5-big-ip-ltm.md
Labels: doc:update, cla-signed

#4129 Create 2024-05-23-content.md
  blog-cse/2024-05-23-content.md
Labels: cla-signed

#3603 Updates the New visualization info
  blog-service/2024-02-02-search.md
  docs/search/get-started-with-search/search-basics/chart-search-results.md
  static/img/search/get-started-search/search-basics/log-query-charts-properties-new.png
Labels: cla-signed

#4124 New Visualizations - Release notes
  blog-service/2024-05-24-search.md
Labels: cla-signed, hot🔥

#4118 Updated RDS Doc for MSSQL dashboards
  docs/integrations/amazon-aws/rds.md
  static/img/integrations/amazon-aws/Amazon-RDS-MSSQL-Logs-Error-Logs-Infrastructure-Overview.png
  static/img/integrations/amazon-aws/Amazon-RDS-MSSQL-Logs-Error-Logs-Logon Analysis.png
Labels: cla-signed

#4121 DOCS-194 - Hide "/docs/reuse" directory from site map
  docusaurus.config.js
Labels: doc:site tech, cla-signed

#4088 Scan estimates in SLO info added
  docs/manage/partitions/flex/estimate-scan-data.md
  static/img/partitions-data-tiers/flex-pricing/scan-estimates-slo.png
Labels: cla-signed

#4134 Fixing TriggerType alert variable description
  docs/alerts/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#4114 Query updated
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/scheduled-searches/faq.md
  docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
  docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
  docs/search/search-query-language/math-expressions/round.md
  i18n/ja/alerts/alerts/scheduled-searches/faqs/email-alert-data-usage-exceeded.md
Labels: cla-signed

#4125 Include Partition in Default Scope - release notes
  blog-service/2024-05-28-manage.md
  docs/manage/partitions/flex/create-edit-partitions-flex.md
  docs/manage/partitions/flex/flex-pricing-faq.md
  docs/search/get-started-with-search/search-basics/about-search-basics.md
Labels: cla-signed, hot🔥

#4135 Fix Otel Collector install command
  docs/send-data/opentelemetry-collector/quickstart.md
Labels: cla-signed

#4133 SUMO-238261 - Mitigating preview query charges for Flex Pricing
  docs/manage/partitions/flex/flex-pricing-faq.md
Labels: cla-signed, do-not-merge

#4138 Update create-edit-partitions-flex.md
  docs/manage/partitions/flex/create-edit-partitions-flex.md
Labels: cla-signed

#4139 updated the abuseipdb integration
  docs/platform-services/automation-service/app-central/integrations/abuseipdb.md
Labels: cla-signed

#4146 DOCS-222 - Regex fix for Zscaler Private Acess article
  docs/integrations/security-threat-detection/zscaler-private-access.md
Labels: doc:minor edit, cla-signed

#4147 Fix link for RBAC for Indexes
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
  docs/manage/users-roles/roles/rbac-for-indexes.md
Labels: doc:minor edit, cla-signed

#4143 DOCS-216 - Add new UI hidden instructions for beta opt-in (Kanso)
  docs/manage/manage-subscription/beta-opt-in.md
Labels: doc:update, cla-signed

#4151 CSIEM Release Notes 2024-05-30
  blog-cse/2024-05-30-application-update.md
  blog-cse/2024-05-30-content.md
Labels: cla-signed

#4148 Update source-log-encoding.md
  docs/send-data/reference-information/source-log-encoding.md
Labels: cla-signed

#4152 Change in the Filed name as per AWS cloudformation template
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
Labels: cla-signed

#4153 servicenow-v2 added change log
  docs/platform-services/automation-service/app-central/integrations/servicenow-v2.md
Labels: cla-signed

#4150 DOCS-224 - Update tour article
  docs/get-started/sumo-logic-ui.md
  static/img/get-started/ui/TUI_Left_Nav.png
  static/img/get-started/ui/WTS_Tab-options-details.png
  static/img/get-started/ui/WTS_UI_Add-dashboard-to-Favorites.png
  static/img/get-started/ui/WTS_UI_Administration_menu-options.png
  static/img/get-started/ui/WTS_UI_Home_landing-page.png
  static/img/get-started/ui/WTS_UI_Tab-delete.png
  static/img/get-started/ui/WTS_UI_Tab-rename.png
  static/img/get-started/ui/WTS_UI_Tabs.png
  static/img/get-started/ui/WTS_UI_View_list-of-Favorites.png
  static/img/get-started/ui/manage-data.png
  static/img/get-started/ui/tab-options.png
Labels: doc:update, cla-signed

#4154 Docusaurus 3.4 upgrade
  docs/platform-services/automation-service/app-central/integrations/imap.md
  package.json
  yarn.lock
Labels: cla-signed
