Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-09, with the labels that each got.

#4490 Update suppressed-lists.md
  docs/cse/match-lists-suppressed-lists/suppressed-lists.md
Labels: cla-signed

#4485 Audit logs info added to 1Password doc
  docs/integrations/1password.md
Labels: cla-signed

#4246 Manage data - New Search Filter - Screenshots updated
  blog-service/2024-09-02-manage.md
  docs/cse/schema/parser-editor.md
  docs/manage/data-forwarding/amazon-s3-bucket.md
  docs/manage/data-forwarding/view-list-data-forwarding.md
  docs/manage/field-extractions/index.md
  docs/manage/fields.md
  docs/manage/partitions/data-tiers/create-edit-partition.md
  docs/manage/partitions/data-tiers/view-partition-details.md
  docs/manage/partitions/decommission-partition.md
  docs/manage/partitions/edit-data-forwarding-destinations-partition.md
  docs/manage/partitions/flex/create-edit-partition-flex.md
  docs/manage/partitions/run-search-against-partition.md
  docs/manage/scheduled-views/view-list-scheduled-views.md
  static/img/cse/add-button.png
  static/img/cse/more-options-for-parser.png
  static/img/cse/parser-templates.png
  static/img/cse/three-dot.png
  static/img/data-forwarding/data-forwarding-status-icons.png
  static/img/data-forwarding/data_forwarding.png
  static/img/field-extraction-rules/fer-page.png
  static/img/fields/create-field-from-dropped-table.png
  static/img/fields/delete-icon.png
  static/img/fields/disable-field.png
  static/img/fields/dropped-fields-table.png
  static/img/fields/manage-fields-page.png
  static/img/partitions-data-tiers/filter-and-search-a-partition.png
  static/img/partitions-data-tiers/partitions-page-flex.png
  static/img/partitions-data-tiers/partitions-page-search-icon.png
  static/img/partitions-data-tiers/partitions-page.png
  static/img/scheduled-views/scheduled-view-page.png
Labels: cla-signed

#4484 Syntax update
  docs/search/search-query-language/search-operators/geo-lookup-map.md
Labels: cla-signed

#4469 Added the new max limit for Fields
  docs/manage/fields.md
  docs/reuse/fer-limitations.md
Labels: cla-signed

#4486 Sophos app docs
  blog-service/2024-09-02-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/sophos.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4497 SUMO-247117 Add the kor endpoint
  docs/integrations/amazon-aws/aws-privatelink.md
Labels: cla-signed

#4495 Update dashboards.md
  docs/observability/reliability-management-slo/dashboards.md
Labels: cla-signed

#4478 Updating docs to awso v2.10.0
  blog-service/2024-09-04-awso.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
Labels: cla-signed

#4499 Update preconfigure-machine-collect-remote-windows-events.md
  docs/send-data/installed-collectors/sources/preconfigure-machine-collect-remote-windows-events.md
Labels: cla-signed

#4504 DOCS-428 - Move Active Directory row
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/product-list/product-list-m-z.md
Labels: doc:update, cla-signed

#4503 DOCS-427 - Remove bad links in Cloud SOAR overview
  docs/cloud-soar/overview.md
Labels: doc:update, cla-signed

#4505 doc: Update important changes to metrics collection
  docs/send-data/kubernetes/v4/how-to-upgrade.md
  docs/send-data/kubernetes/v4/important-changes.md
Labels: doc:update, cla-signed

#4506 Weekly 404 fixes
  cid-redirects.json
Labels: cla-signed

#4303 DOCS-319 - Alerts/Monitors tag update
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/settings.md
  static/img/alerts/alert-response-tags.png
  static/img/alerts/monitors-alerts-list-tags.png
Labels: cla-signed, do-not-merge

#4508 DOCS-432 - Clarify Cloud SIEM and Cloud SOAR account licensing
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
Labels: doc:minor edit, cla-signed

#4509 Update python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: cla-signed

#4512 Update best-practices.md
  docs/send-data/kubernetes/best-practices.md
Labels: cla-signed

#4390 Docs updated with Seoul region
  docs/api/access-keys.md
  docs/api/account-management.md
  docs/api/app-management.md
  docs/api/archive-ingestion.md
  docs/api/collector-management/index.md
  docs/api/connections-management.md
  docs/api/content-management.md
  docs/api/content-permissions.md
  docs/api/dashboard.md
  docs/api/dynamic-parsing.md
  docs/api/field-extraction-rules.md
  docs/api/field-management.md
  docs/api/folder-management.md
  docs/api/getting-started.md
  docs/api/health-events.md
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/api/log-search-estimated-usage.md
  docs/api/log-searches.md
  docs/api/logs-data-forwarding.md
  docs/api/lookup-tables.md
  docs/api/metrics-query.md
  docs/api/metrics-searches-v2.md
  docs/api/metrics-searches.md
  docs/api/metrics-transformation-rules.md
  docs/api/monitors-management.md
  docs/api/muting-schedules.md
  docs/api/organizations-management.md
  docs/api/partition-management.md
  docs/api/password-policy.md
  docs/api/policies-management.md
  docs/api/role-management.md
  docs/api/saml-configuration.md
  docs/api/scheduled-views.md
  docs/api/service-allowlist.md
  docs/api/service-map.md
  docs/api/slo-management.md
  docs/api/span-analytics.md
  docs/api/token-management.md
  docs/api/tracing.md
  docs/api/user-management.md
  docs/get-started/faq.md
  docs/integrations/amazon-aws/aws-privatelink.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
  docs/reuse/aws-region-by-sumo-deployment.md
  docs/reuse/cse-api-table.md
  docs/reuse/csoar-api-table.md
  docs/security/cloud-infrastructure-security/cloud-infrastructure-security-for-aws.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  docs/send-data/hosted-collectors/amazon-aws/grant-access-aws-product.md
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
Labels: cla-signed, do-not-merge

#4511 DOCS-430 - Metrics API
  docs/api/metrics.md
Labels: doc:minor edit, cla-signed

#4510 Update mimecast-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source.md
  static/files/c2c/mimecast/example.json
  static/files/c2c/mimecast/example.tf
Labels: cla-signed

#4514 updated docs for mssql
  docs/platform-services/automation-service/app-central/integrations/mssql.md
Labels: cla-signed

#4502 Microsoft Azure AD Inventory Apps doc
  blog-service/2024-09-09-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/microsoft-azure-ad-inventory.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4515 DOCS-56 - Troubleshoot a playbook
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/monitors/playbook-completed-with-errors-icon.png
  static/img/platform-services/automation-service/arrow-on-playbook.png
  static/img/platform-services/automation-service/automations-in-cloud-siem.png
  static/img/platform-services/automation-service/cloud-soar-playbooks-graph-view.png
  static/img/platform-services/automation-service/failed-action-in-graph-view.png
  static/img/platform-services/automation-service/failed-actions-in-filtered-results.png
  static/img/platform-services/automation-service/playbook-in-alert-1.png
  static/img/platform-services/automation-service/playbook-in-alert.png
  static/img/platform-services/automation-service/playbook-in-cloud-siem.png
  static/img/platform-services/automation-service/playbook-payload.png
  static/img/platform-services/automation-service/playbooks-in-cloud-soar.png
  static/img/platform-services/automation-service/reason-for-failed-action.png
Labels: doc:new, cla-signed, do-not-merge

#4516 App central freshservice
  docs/platform-services/automation-service/app-central/integrations/freshservice.md
  static/img/platform-services/automation-service/app-central/integrations/freshservice/freshservice-5.png
  static/img/platform-services/automation-service/app-central/integrations/freshservice/freshservice-6.png
  static/img/platform-services/automation-service/app-central/integrations/freshservice/freshservice-7.png
  static/img/platform-services/automation-service/app-central/integrations/freshservice/freshservice-9.png
Labels: doc:update, cla-signed

#4518 Update automation-service-playbooks.md - Minor formatting
  docs/platform-services/automation-service/automation-service-playbooks.md
Labels: cla-signed

#4487 Suggestion Update faq.md
  docs/manage/partitions/flex/faq.md
Labels: cla-signed

#4496 Credit usage information screenshot updated
  docs/manage/fields.md
  docs/manage/partitions/manage-indexes-variable-retention.md
  docs/manage/scheduled-views/add-scheduled-view.md
  static/img/field-extraction-rules/fer-page.png
  static/img/fields/create-field-from-dropped-table.png
  static/img/fields/dropped-fields-table.png
  static/img/fields/fields-capacity.png
  static/img/fields/manage-fields-page.png
  static/img/partitions-data-tiers/filter-and-search-a-partition.png
  static/img/partitions-data-tiers/partitions-page-flex.png
  static/img/partitions-data-tiers/partitions-page.png
  static/img/scheduled-views/scheduled-view-page.png
Labels: cla-signed

#4526 Documentation Azure Load Balancer
  docs/integrations/microsoft-azure/azure-load-balancer.md
  static/img/send-data/azureloadbalancer-logs.png
  static/img/send-data/azureloadbalancer-metrics.png
Labels: cla-signed

#4523 Update sdo-manual-configuration.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
Labels: cla-signed

#4529 Image updated
  docs/manage/fields.md
Labels: cla-signed, hot🔥

#4524 Zendesk Source Docs
  blog-service/2024-09-13-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zendesk-source.md
  sidebars.ts
  static/files/c2c/zendesk/example.json
  static/files/c2c/zendesk/example.tf
  static/img/send-data/zendesk-icon.png
Labels: cla-signed

#4519 CONN-3352 Release atlassian-source.md
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/atlassian-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
Labels: cla-signed

#4498 DOCS-443 - Clean up API articles
  docs/api/access-keys.md
  docs/api/account-management.md
  docs/api/app-management.md
  docs/api/archive-ingestion.md
  docs/api/cloud-siem-enterprise.md
  docs/api/cloud-soar.md
  docs/api/collector-management/index.md
  docs/api/connections-management.md
  docs/api/content-management.md
  docs/api/content-permissions.md
  docs/api/dashboard.md
  docs/api/dynamic-parsing.md
  docs/api/field-extraction-rules.md
  docs/api/field-management.md
  docs/api/folder-management.md
  docs/api/getting-started.md
  docs/api/health-events.md
  docs/api/index.md
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/api/log-search-estimated-usage.md
  docs/api/log-searches.md
  docs/api/logs-data-forwarding.md
  docs/api/lookup-tables.md
  docs/api/metrics-query.md
  docs/api/metrics-searches-v2.md
  docs/api/metrics-searches.md
  docs/api/metrics-transformation-rules.md
  docs/api/monitors-management.md
  docs/api/muting-schedules.md
  docs/api/organizations-management.md
  docs/api/partition-management.md
  docs/api/password-policy.md
  docs/api/policies-management.md
  docs/api/role-management.md
  docs/api/saml-configuration.md
  docs/api/scheduled-views.md
  docs/api/search-job.md
  docs/api/service-allowlist.md
  docs/api/service-map.md
  docs/api/slo-management.md
  docs/api/span-analytics.md
  docs/api/token-management.md
  docs/api/tracing.md
  docs/api/user-management.md
  docs/reuse/api-roles.md
  sidebars.ts
Labels: doc:update, cla-signed

#4525 Micro Lesson added to the Flex app doc
  docs/integrations/sumo-apps/flex.md
Labels: cla-signed

#4530 Correct KinesisLog JSON contentType
  docs/send-data/use-json-configure-sources/json-parameters-hosted-sources.md
Labels: cla-signed

#4289 Estimate Infrequent tier data docs update
  docs/manage/partitions/data-tiers/searching-data-tiers.md
  static/img/partitions-data-tiers/CrossTier-Query-Start-Estimated-Scan.png
  static/img/partitions-data-tiers/no-scan-data.png
  static/img/partitions-data-tiers/scan-details.png
Labels: cla-signed

#4531 Fix spelling in organization article
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
Labels: doc:minor edit, cla-signed

#4532 added the content.
  docs/platform-services/automation-service/app-central/integrations/atlassian-opsgenie.md
Labels: cla-signed

#4521 modified date
  docs/platform-services/automation-service/app-central/integrations/freshservice.md
Labels: cla-signed

#4517 Added metrics collection and metrics-based dashboards info to MongoDB
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
Labels: doc:update, cla-signed

#4533 DOCS-449 - Add new Kanso video
  docs/get-started/sumo-logic-ui-new.md
Labels: doc:minor edit, cla-signed

#4534 Update python.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: cla-signed

#4535 Moved 1Password to SaaS apps
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/integrations/index.md
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/1password.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: cla-signed

#4537 Update python version
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
Labels: doc:minor edit, cla-signed

#4538 Update configure-data-collection.md
  docs/apm/real-user-monitoring/configure-data-collection.md
Labels: cla-signed

#4539 DOCS-207 - Pre-Kanso GA cleanup
  blog-service/2024-02-23-ui.md
  docs/cloud-soar/overview.md
  docs/cse/introduction-to-cloud-siem.md
  docs/send-data/collection/index.md
Labels: doc:minor edit, cla-signed

#4527 Overlapping data scans info update
  docs/manage/partitions/flex/create-edit-partition-flex.md
Labels: cla-signed

#4542 CONN-3640 Add JSON file clarification
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/snowflake-sql-api.md
Labels: cla-signed

#4544 Fix astrisk errors
  blog-service/2016/12-31.md
  blog-service/2017/12-31.md
  blog-service/2020/12-31.md
  blog-service/2021/12-31.md
Labels: doc:minor edit, cla-signed

#4543 DOCS-451 - Minor change to match lists article
  docs/cse/match-lists-suppressed-lists/create-match-list.md
Labels: doc:minor edit, cla-signed

#4372 DOCS-355 - UI Elements - Style Guide - Kanso
  docs/reuse/ui-elements.md
  static/img/content-sharing/icon-favorites-new.png
  static/img/content-sharing/icon-library-new.png
  static/img/content-sharing/icon-personal-new.png
  static/img/content-sharing/icon-recent.png
  static/img/content-sharing/left-nav.png
Labels: cla-signed

#4547 Update set-max-web-session-timeout.md
  docs/manage/security/set-max-web-session-timeout.md
Labels: cla-signed

#4548 added the content for abuseipdb
  docs/platform-services/automation-service/app-central/integrations/abuseipdb.md
  static/img/platform-services/automation-service/app-central/integrations/abuseipdf/abuseipdf-1.png
  static/img/platform-services/automation-service/app-central/integrations/abuseipdf/abuseipdf-2.png
  static/img/platform-services/automation-service/app-central/integrations/abuseipdf/abuseipdf-3.png
Labels: cla-signed

#4546 DOCS-445 - Entity group inventory example
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  static/img/cse/create-entity-group-inventory.png
  static/img/cse/create-entity-group-values.png
  static/img/cse/entity-group-inventory-example-1.png
  static/img/cse/entity-group-inventory-example-2.png
  static/img/cse/entity-group-inventory-example-3.png
Labels: doc:new, cla-signed

#4551 Cloud SIEM content release notes for September 19, 2024
  blog-cse/2024-09-19-content.md
Labels: cla-signed

#4555 DOCS-207 - Remove Kanso comments for metrics, observability, and dashboards
  docs/dashboards/create-dashboard-new.md
  docs/dashboards/explore-view.md
  docs/dashboards/share-dashboard-outside-org.md
  docs/metrics/introduction/index.md
  docs/metrics/logs-to-metrics.md
  docs/metrics/manage-metric-volume/data-limits-for-metrics.md
  docs/metrics/manage-metric-volume/disabled-metrics-sources.md
  docs/metrics/metric-rules-editor.md
  docs/metrics/metrics-dpm.md
  docs/metrics/metrics-queries/metrics-explorer.md
  docs/metrics/metrics-transformation-rules.md
  docs/observability/application-components.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/observability/kubernetes/monitoring.md
  docs/observability/kubernetes/troubleshoot-with-explore.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/observability/reliability-management-slo/dashboards.md
  docs/observability/reliability-management-slo/index.md
  docs/observability/root-cause-explorer.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
  docs/observability/sdo/set-up-sdo/sdo-setup-with-terraform-script.md
Labels: doc:update, cla-signed

#4556 DOCS-207 - Remove Kanso comments for Platform Services, APM, API, and release notes
  blog-service/2024-07-05-collection.md
  docs/apm/real-user-monitoring/configure-data-collection.md
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/real-user-monitoring/index.md
  docs/apm/traces/get-started-transaction-tracing/http-traces-source.md
  docs/apm/traces/quickstart.md
  docs/apm/traces/search-query-language-support-for-traces.md
  docs/apm/traces/services-list-map.md
  docs/apm/traces/spans.md
  docs/apm/traces/tracing-dashboards.md
  docs/apm/traces/view-and-investigate-traces.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-log-analytics.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications.md
  docs/platform-services/automation-service/automation-service-app-central.md
  docs/platform-services/automation-service/automation-service-audit-logging.md
  docs/platform-services/automation-service/automation-service-bridge.md
  docs/platform-services/automation-service/automation-service-integrations.md
  docs/platform-services/automation-service/automation-service-playbooks.md
Labels: doc:update, cla-signed

#4558 DOCS-207 - Remove Kanso comments final cleanup
  docs/reuse/apps/create-aws-s3-source.md
  docs/reuse/apps/opentelemetry/collector-installation.md
  docs/reuse/aws-cost-explorer.md
  docs/reuse/dark-light-theme.md
  docs/reuse/restart-c2c-source.md
  i18n/ja/alerts/alerts/monitors/alert-response.md
Labels: doc:update, cla-signed

#4559 DOCS-15 - Add redirect for "sumo-logic-ui-new"
  cid-redirects.json
Labels: doc:update, cla-signed

#4562 Fix Classic UI links for Setup Wizard and Root Cause Explorer
  docs/observability/root-cause-explorer.md
  docs/send-data/setup-wizard.md
Labels: doc:minor edit, cla-signed

#4565 Add Ayah-Saleh to cla file
  .clabot
Labels: doc:minor edit, cla-signed

#4557 Created 301 Redirects and OTEL apps index page
  blog-service/2016/12-31.md
  cid-redirects.json
  docs/integrations/containers-orchestration/opentelemetry/index.md
  docs/search/get-started-with-search/build-search/best-practices-search.md
  sidebars.ts
Labels: cla-signed

#3860 Schedule reports docs update
  blog-service/2024-09-23-dashboards.md
  docs/dashboards/scheduled-report.md
  static/img/dashboards-new/scheduled_reports/create_scheduled_report.png
  static/img/dashboards-new/scheduled_reports/delete_scheduled_report.png
  static/img/dashboards-new/scheduled_reports/delete_scheduled_report_1.png
  static/img/dashboards-new/scheduled_reports/delete_scheduled_report_2.png
  static/img/dashboards-new/scheduled_reports/duplicate_scheduled_report.png
  static/img/dashboards-new/scheduled_reports/scheduled_report.png
  static/img/dashboards-new/scheduled_reports/scheduled_report_1.png
  static/img/dashboards-new/scheduled_reports/subscribe_scheduled_report.png
  static/img/dashboards-new/scheduled_reports/update_scheduled_report.png
  static/img/dashboards-new/scheduled_reports/update_scheduled_report_1.png
Labels: cla-signed, do-not-merge

#4568 CSOAR anchor fixes
  docs/cloud-soar/overview.md
  docusaurus.config.js
Labels: cla-signed

#4570 RSS image fix
  blog-service/2024-09-23-dashboards.md
Labels: cla-signed, hot🔥

#4569 Contributing index - Fixes for grammar and clarity
  docs/contributing/index.md
Labels: cla-signed

#4576 Fix broken md in json source doc
  docs/send-data/use-json-configure-sources/json-parameters-installed-sources.md
Labels: cla-signed

#4574 Fix table value
  docs/search/search-query-language/search-operators/join.md
Labels: doc:minor edit, cla-signed

#4561 Update search-job.md
  docs/api/search-job.md
Labels: cla-signed, do-not-merge

#4541 Datatier modifier FAQ added
  docs/manage/partitions/data-tiers/faq.md
  docs/manage/partitions/flex/faq.md
Labels: cla-signed

#4578 Guides menu UI updates
  docusaurus.config.js
Labels: cla-signed

#4580 Update about-automation-service.md -Update Doc
  docs/platform-services/automation-service/about-automation-service.md
  docs/reuse/actions-limit-query.md
  docs/reuse/actions-limit.md
Labels: cla-signed

#4582 Replace **+ New** button content
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/real-user-monitoring/index.md
  docs/apm/traces/quickstart.md
  docs/apm/traces/search-query-language-support-for-traces.md
  docs/apm/traces/services-list-map.md
  docs/apm/traces/spans.md
  docs/apm/traces/tracing-dashboards.md
  docs/apm/traces/view-and-investigate-traces.md
  docs/cse/records-signals-entities-insights/search-cse-records-in-sumo.md
  docs/dashboards/create-dashboard-new.md
  docs/dashboards/explore-view.md
  docs/get-started/sumo-logic-ui-classic.md
  docs/integrations/amazon-aws/elastic-container-service-container-insights-cloudwatch.md
  docs/metrics/introduction/index.md
  docs/metrics/metrics-queries/metrics-explorer.md
  docs/observability/application-components.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/observability/kubernetes/monitoring.md
  docs/observability/kubernetes/troubleshoot-with-explore.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/observability/root-cause-explorer.md
  docs/platform-services/automation-service/automation-service-audit-logging.md
  docs/search/get-started-with-search/search-basics/about-search-basics.md
  docs/search/get-started-with-search/search-page/search-modes.md
  docs/search/live-tail/about-live-tail.md
  docs/security/additional-security-features/audit-and-compliance.md
  docs/security/additional-security-features/threat-detection-and-investigation.md
  static/img/alerts/monitors-alerts-list-tags.png
Labels: cla-signed

#4585 Legacy 301 fixes
  cid-redirects.json
Labels: cla-signed

#4588 DOCS-461 - Fix instructions to access Organizations in the new UI
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
Labels: doc:update, cla-signed

#4592 DOCS-229 - Clarify Org Mgmt API endpoints
  docs/api/organizations-management.md
Labels: cla-signed

#4590 DOCS-462 - Archive Release Notes 2015-2020
  blog-collector/2015/12-31.md
  blog-collector/2016/12-31.md
  blog-collector/2017/12-31.md
  blog-collector/2018/12-31.md
  blog-collector/2019/12-31.md
  blog-collector/2020/12-31.md
  blog-collector/2021/12-31.md
  blog-cse/2022/12-31.md
  blog-cse/2023/12-31.md
  blog-developer/2018/12-31.md
  blog-developer/2019/12-31.md
  blog-developer/2020/12-31.md
  blog-developer/2021/12-31.md
  blog-developer/2022/12-31.md
  blog-developer/2023/12-31.md
  blog-service/2016/12-31.md
  blog-service/2017/12-31.md
  blog-service/2018/12-31.md
  blog-service/2019/12-31.md
  blog-service/2020/12-31.md
  blog-service/2021/12-31.md
  blog-service/2022/12-31.md
  blog-service/2023/12-31.md
  docs/release-notes/index.md
Labels: cla-signed

#4591 DOCS-319 - Alerts/Monitors tags
  blog-service/2022/12-31.md
  docs/alerts/monitors/overview.md
  docs/alerts/monitors/settings.md
  docs/manage/users-roles/roles/role-capabilities.md
  static/img/alerts/alert-response-tags.png
  static/img/alerts/alerts-list-tags.png
  static/img/alerts/monitors-alerts-list-tags.png
  static/img/alerts/monitors-tags.png
Labels: cla-signed

#4513 Update deletion-requests.md
  docs/manage/deletion-requests.md
Labels: cla-signed

#4597 Apps Setup Guides - September Release
  blog-service/2024-09-30-apps.md
  docs/integrations/partner-ecosystem-apps.md
Labels: cla-signed, hot🔥

#4598 Revert "Apps Setup Guides - September Release"
  blog-service/2024-09-30-apps.md
  docs/integrations/partner-ecosystem-apps.md
Labels: cla-signed

#4593 Create New Monitor cleanup
  blog-service/2022/12-31.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/alert-variables.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/monitors/settings.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/get-started/ai-machine-learning.md
  docs/reuse/alerts-timeslice.md
  docs/search/search-query-language/search-operators/timeslice.md
  i18n/ja/alerts/alerts/monitors/index.md
  static/img/monitors/create-monitor.png
  static/img/monitors/edit-recovery-settings1.png
  static/img/monitors/home-metrics.png
  static/img/monitors/logs-missing-data.png
  static/img/monitors/logs-monitors.png
  static/img/monitors/metrics-explorer-thresholds.png
  static/img/monitors/metrics-explorer-view.png
  static/img/monitors/metrics-monitor-query-row.png
  static/img/monitors/metrics-query.png
  static/img/monitors/metrics-trigger-types.png
  static/img/monitors/missing.png
  static/img/monitors/monitor-detection-methods-for-logs.png
  static/img/monitors/monitor-detection-methods-for-metrics.png
  static/img/monitors/monitor-detector-types-for-anamoly.png
  static/img/monitors/monitor-detector-types-for-anomaly.png
  static/img/monitors/monitor-metrics-outlier-triggers.png
  static/img/monitors/monitor-outlier-logs.png
  static/img/monitors/new-monitor-advanced-settings.png
  static/img/monitors/new-monitor-dialog.png
  static/img/monitors/new-monitor-set-trigger-conditions.png
  static/img/monitors/new-monitor-window.png
  static/img/monitors/trigger-alerts-field.png
Labels: cla-signed
