Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-03, with the labels that each got.

#3760 chore(python): update deps
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
Labels: cla-signed

#3763 Add rshav-sumo-dev to clabot
  .clabot
Labels: cla-signed

#3659 Flex Pricing (publish March 5)
  docs/api/search-job.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/custom-tags-configuration.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/traceid-spanid-injection-into-logs-configuration.md
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/automation/cloud-siem-automation-examples.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/integrations/sumo-apps/flex.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
  docs/manage/partitions-data-tiers/data-tiers-faqs.md
  docs/manage/partitions-data-tiers/data-tiers.md
  docs/manage/partitions-data-tiers/manage-indexes-variable-retention.md
  docs/platform-services/automation-service/app-central/integrations/aws-security-hub.md
  docs/platform-services/automation-service/app-central/integrations/darktrace.md
  docs/platform-services/automation-service/app-central/integrations/mimecast.md
  docs/platform-services/automation-service/app-central/integrations/rsa-netwitness.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/platform-services/threat-intelligence-indicators.md
  docs/reuse/flex-pricing.md
  docs/search/get-started-with-search/search-page/search-modes.md
  docs/send-data/installed-collectors/collector-installation-reference/add-collector-linux-machine-image.md
  static/files/flex-tier/index.html
  static/files/flex-tier/page1.html
  static/files/flex-tier/page2.html
  static/img/integrations/sumo-apps/flex-tier.png
  static/img/partitions-data-tiers/DeleteNOW.png
  static/img/partitions-data-tiers/edit_retention_period_save.png
  static/img/partitions-data-tiers/reduce-retention-period.png
  static/img/platform-services/automation-service/automations-playbook-run-test.png
  static/img/platform-services/automation-service/automations-playbook-test-playbook.png
  static/img/platform-services/automation-service/automations-playbook-test-results-filtered.png
  static/img/platform-services/automation-service/automations-playbook-test-results.png
  static/img/subscriptions/flex-usage-categories.png
Labels: cla-signed, do-not-merge

#3762 App central integration criminal ip
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/criminal-ip.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  static/img/platform-services/automation-service/app-central/logos/criminal-ip.png
Labels: cla-signed

#3755 Update the "Cloud Infrastructure for AWS" article
  docs/integrations/amazon-aws/cloud-infrastructure-security-for-aws.md
  static/img/integrations/amazon-aws/cis-for-aws-param-1.png
  static/img/integrations/amazon-aws/cis-for-aws-param-7.png
  static/img/integrations/amazon-aws/cis-for-aws-param-7a.png
Labels: doc:update, cla-signed

#3695 K8s Helm install permissions requirements
  docs/send-data/kubernetes/install-helm-chart.md
Labels: cla-signed

#3765 Update S3 bucket instructions
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
  static/img/send-data/bucket-name-and-path-expression.png
Labels: doc:minor edit, cla-signed

#3661 Update naming from Live to new term Auto Refresh
  blog-service/2016/12-31.md
  blog-service/2017/12-31.md
  docs/manage/manage-subscription/cloud-flex-accounts.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
  docs/manage/security/audit-indexes/search-audit-index.md
  docs/search/search-cheat-sheets/log-operators.md
  docs/search/search-query-language/group-aggregate-operators/first-last.md
  docs/search/search-query-language/group-aggregate-operators/index.md
  docs/search/search-query-language/group-aggregate-operators/most-recent-least-recent.md
  docs/search/search-query-language/search-operators/cat.md
  docs/search/search-query-language/search-operators/fillmissing.md
  docs/search/search-query-language/search-operators/index.md
  docs/search/search-query-language/search-operators/querytimerange.md
  docs/search/subqueries.md
Labels: cla-signed

#3657 New enhancements to the Accounts page
  blog-service/2024-03-04-manage.md
  docs/manage/manage-subscription/cloud-flex-credits-accounts.md
  static/img/account/account-usage-fields.png
Labels: cla-signed

#3766 API formatting
  blog-developer/2020/12-31.md
  blog-developer/2022/12-31.md
  cid-redirects.json
  docs/alerts/webhook-connections/aws-lambda.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/api/account-management.md
  docs/api/archive-ingestion.md
  docs/api/collector-management/collector-api-methods-examples.md
  docs/api/collector-management/index.md
  docs/api/collector-management/source-api.md
  docs/api/collector-management/upgrade-downgrade-collectors.md
  docs/api/content-management.md
  docs/api/content-permissions.md
  docs/api/dashboard.md
  docs/api/data-forwarding.md
  docs/api/field-extraction-rules.md
  docs/api/field-management.md
  docs/api/folder-management.md
  docs/api/getting-started.md
  docs/api/index.md
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/api/log-search-estimated-usage.md
  docs/api/log-searches.md
  docs/api/logs-data-forwarding.md
  docs/api/metrics-query.md
  docs/api/metrics.md
  docs/api/monitors-management.md
  docs/api/muting-schedules.md
  docs/api/organizations-management.md
  docs/api/partition-management.md
  docs/api/policies-management.md
  docs/api/role-management.md
  docs/api/search-job.md
  docs/api/service-map.md
  docs/api/slo-management.md
  docs/api/span-analytics.md
  docs/api/token-management.md
  docs/api/troubleshooting.md
  docs/api/user-management.md
  docs/get-started/quickstart.md
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/cloudfront.md
  docs/integrations/amazon-aws/elastic-load-balancer-app.md
  docs/integrations/amazon-aws/elastic-load-balancing-classic.md
  docs/integrations/amazon-aws/global-intelligence-cloudtrail-devops.md
  docs/integrations/amazon-aws/network-firewall.md
  docs/integrations/amazon-aws/s3-audit.md
  docs/integrations/amazon-aws/waf.md
  docs/integrations/saas-cloud/acquia.md
  docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection.md
  docs/integrations/sumo-apps/enterprise-audit.md
  docs/manage/users-roles/users/delete-user.md
  docs/observability/kubernetes/quickstart.md
  docs/observability/sdo/set-up-sdo/sdo-manual-configuration.md
  docs/observability/sdo/set-up-sdo/sdo-setup-with-terraform-script.md
  docs/send-data/opentelemetry-collector/quickstart.md
  sidebars.ts
  static/img/api/search_job_api_process_flow.png
Labels: cla-signed

#3767 chore(ruby): update instrumentation dependencies
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby-on-rails.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/ruby.md
Labels: cla-signed

#3770 Update .clabot
  .clabot
Labels: cla-signed

#3771 chore: update js instrumentation deps
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/javascript/traceid-spanid-injection-into-logs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
Labels: cla-signed

#3769 Kanso - add microlesson vid
  docs/get-started/sumo-logic-ui-new.md
Labels: cla-signed

#3768 Updating changing the account owner when the account owner has left their organization
  docs/manage/manage-subscription/manage-org-settings.md
  docs/manage/users-roles/users/offboard-user.md
Labels: cla-signed

#3777 Update additionalRemoteWrite path
  docs/send-data/kubernetes/v4/how-to-upgrade.md
Labels: cla-signed

#3774 Revert "Updating changing the account owner when the account owner has left their organization"
  docs/manage/manage-subscription/manage-org-settings.md
  docs/manage/users-roles/users/offboard-user.md
Labels: cla-signed

#3780 Updating changing the account owner when the account owner has left t…
  docs/manage/manage-subscription/manage-org-settings.md
  docs/manage/users-roles/users/offboard-user.md
Labels: cla-signed

#3776 chore: golang update instrumentation deps
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/index.md
Labels: cla-signed

#3783 Update .clabot
  .clabot
Labels: cla-signed

#3784 App central integrations
  docs/platform-services/automation-service/app-central/integrations/alienvault-usm-anywhere.md
  docs/platform-services/automation-service/app-central/integrations/arbor.md
  docs/platform-services/automation-service/app-central/integrations/arcsight-esm.md
  docs/platform-services/automation-service/app-central/integrations/chronicle.md
  docs/platform-services/automation-service/app-central/integrations/coralogix-send-logs.md
  docs/platform-services/automation-service/app-central/integrations/cortex-xdr.md
  docs/platform-services/automation-service/app-central/integrations/crowdstrike-falcon-intelligence.md
  docs/platform-services/automation-service/app-central/integrations/crowdstrike-falcon.md
  docs/platform-services/automation-service/app-central/integrations/cylanceprotect.md
  docs/platform-services/automation-service/app-central/integrations/darkowl.md
  docs/platform-services/automation-service/app-central/integrations/darktrace.md
  docs/platform-services/automation-service/app-central/integrations/devo.md
  docs/platform-services/automation-service/app-central/integrations/elastic-security.md
  docs/platform-services/automation-service/app-central/integrations/fortianalyzer.md
  docs/platform-services/automation-service/app-central/integrations/imap.md
  docs/platform-services/automation-service/app-central/integrations/incident-tools.md
  docs/platform-services/automation-service/app-central/integrations/knowbe4-phisher.md
  docs/platform-services/automation-service/app-central/integrations/logrhythm.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-365-defender.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-ews-daemon.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-ews.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-teams.md
  docs/platform-services/automation-service/app-central/integrations/misp.md
  docs/platform-services/automation-service/app-central/integrations/netskope.md
  docs/platform-services/automation-service/app-central/integrations/protectonce.md
  docs/platform-services/automation-service/app-central/integrations/recorded-future.md
  docs/platform-services/automation-service/app-central/integrations/sentinelone.md
  docs/platform-services/automation-service/app-central/integrations/sophos-central-v3.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cse.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic.md
  docs/platform-services/automation-service/app-central/integrations/virustotal.md
  docs/platform-services/automation-service/app-central/integrations/vmware-carbon-black-cloud-endpoint-standard-v2.md
  docs/platform-services/automation-service/app-central/integrations/vmware-carbon-black-cloud-platform.md
  docs/platform-services/automation-service/app-central/integrations/withsecure-elements.md
Labels: cla-signed

#3787 Update "Proofpoint Tap Source" article
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
Labels: doc:update, cla-signed

#3788 Cloud SOAR actions limit
  docs/cloud-soar/automation.md
  static/img/cloud-soar/appcentral.png
Labels: doc:new, cla-signed

#3789 Update the Insight Trainer article
  docs/cse/rules/insight-trainer.md
Labels: doc:minor edit, cla-signed

#3785 Child credits usage section added
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
  static/img/subscriptions/access-org.png
  static/img/subscriptions/baselines_1.png
  static/img/subscriptions/child-credits-usage.png
  static/img/subscriptions/edit-org-3.png
Labels: cla-signed

#3790 Scheduled View edit re: log ingest volume
  docs/manage/scheduled-views/index.md
Labels: cla-signed

#3797 Link Cloud SIEM rules syntax to field expressions
  docs/cse/rules/cse-rules-syntax.md
  docs/search/search-query-language/field-expressions.md
  docs/search/search-query-language/index.md
Labels: doc:minor edit, cla-signed

#3795 App central integration onelogin
  docs/platform-services/automation-service/app-central/integrations/onelogin.md
  static/img/platform-services/automation-service/app-central/logos/onelogin.png
Labels: cla-signed

#3778 Version 19.484-1 Release notes
  blog-collector/2024-03-07.md
Labels: cla-signed

#3798 App Central Malware Nebula integration updated
  docs/platform-services/automation-service/app-central/integrations/malwarebytes-nebula.md
Labels: cla-signed

#3701 Add Delivery 2 "Report" section
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/main-menu.md
Labels: doc:new, cla-signed

#3786 SUMO-237234 - Tanzu application
  cid-redirects.json
  docs/integrations/containers-orchestration/index.md
  docs/integrations/containers-orchestration/vmware-tanzu-application-service.md
  sidebars.ts
  static/img/integrations/containers-orchestration/SumoLogicVerbose.png
  static/img/integrations/containers-orchestration/SumoNozzlePCFSettings.png
  static/img/integrations/containers-orchestration/SumoTile.png
  static/img/integrations/containers-orchestration/SumologicSettings.png
  static/img/integrations/containers-orchestration/Troubleshooting.png
  static/img/integrations/containers-orchestration/TroubleshootingApp.png
  static/img/integrations/containers-orchestration/TroubleshootingLogs.png
  static/img/integrations/containers-orchestration/selectnozzle.png
  static/img/integrations/containers-orchestration/selectplay.png
  static/img/integrations/containers-orchestration/vmware-tanzu.png
Labels: cla-signed

#3802 Swap out Cloud SOAR icon
  docs/cloud-soar/index.md
  src/helper/features.js
  static/img/icons/security/soar-2-color-icon.png
Labels: cla-signed

#3800 CONN-2959 Beta Config Based C2C
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed

#3804 CONN-2959 Add a link to available parser paths
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed

#3803 Updating default payload for PagerDuty v2
  docs/alerts/webhook-connections/pagerduty.md
Labels: cla-signed

#3718 AWS Amazon API Gateway doc
  docs/integrations/amazon-aws/api-gateway.md
  docs/integrations/amazon-aws/rds.md
  docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source.md
  static/img/integrations/amazon-aws/Access_Logging_HTTP_API.png
  static/img/integrations/amazon-aws/Access_Logging_REST_API.png
  static/img/integrations/amazon-aws/Access_Logging_WebSocket_API.png
  static/img/integrations/amazon-aws/HTTP_API_Enhanced_Metrics.png
  static/img/integrations/amazon-aws/REST_API_Enhanced_Metrics.png
  static/img/integrations/amazon-aws/REST_API_Enhanced_Metrics_Method_Overides.png
Labels: cla-signed

#3801 Apply Swagger CSS and HTML to Collector/Search Job API
  docs/api/collector-management/collector-api-methods-examples.md
  docs/api/collector-management/source-api.md
  docs/api/collector-management/upgrade-downgrade-collectors.md
  docs/api/search-job.md
  src/css/api-override.css
  src/css/sumo.scss
Labels: cla-signed

#3806 Update Cloud SIEM Actions article
  docs/cse/administration/create-cse-actions.md
  docs/cse/automation/automations-in-cloud-siem.md
Labels: doc:minor edit, cla-signed

#3808 Revert "CONN-2959 Add a link to available parser paths"
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed, hot🔥

#3809 Fix for CONN-2959
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: doc:minor edit, cla-signed

#3807 Added new integration AWS Private Certificate Authority to App Central
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/aws-private-certificate-authority.md
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#3810 Update Threat Intelligence roles info
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#3811 Update Insight Trainer article again
  docs/cse/rules/insight-trainer.md
Labels: doc:minor edit, cla-signed

#3799 PR template edits
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#3812 Fix warning admonition
  docs/contributing/style-guide.md
  src/theme/Admonition/index.js
Labels: cla-signed

#3814 feat(opentelemetry-collector): add troubleshooting for Windows FIPS
  docs/send-data/opentelemetry-collector/install-collector/windows.md
Labels: cla-signed

#3819 Update data-volume.md
  docs/integrations/sumo-apps/data-volume.md
Labels: cla-signed

#3816 CONN-2919 Config C2C Minor Updates
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed

#3820 Fix links in "Amazon VPC Flow Logs" article
  docs/integrations/amazon-aws/vpc-flow-logs.md
Labels: doc:minor edit, cla-signed

#3823 Add paultobiasumo to the clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#3824 CONN-2936 Add TAXII 1 C2C Source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  static/files/c2c/taxii-1/example.json
  static/files/c2c/taxii-1/example.tf
Labels: cla-signed

#3822 Update mitre-coverage.md
  docs/cse/administration/mitre-coverage.md
Labels: cla-signed

#3825 Add TAXII 1 Client Source to the threat intelligence indicators beta article
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#3772 Metadata information added (Kaltura)
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/kaltura-source.md
Labels: cla-signed

#3829 Cloud SOAR Release Notes
  blog-csoar/2024-03-12-application-update.md
  blog-csoar/2024-03-12-content.md
  static/files/updating-app-central-integrations.pdf
Labels: cla-signed

#3826 Update community-ecosystem-apps.md
  docs/integrations/community-ecosystem-apps.md
Labels: cla-signed

#3397 AI-driven alerting (aka "smart alerts") - GA
  blog-service/2024-03-12-alerts.md
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/platform-services/automation-service/about-automation-service.md
  sidebars.ts
  static/img/monitors/Suggested-Monitors.png
  static/img/monitors/automated-playbooks-in-alert-screen.png
  static/img/monitors/logs-monitors.png
  static/img/monitors/monitor-detection-methods-for-logs.png
  static/img/monitors/monitor-detection-methods-for-metrics.png
  static/img/monitors/monitor-detection-methods.png
  static/img/monitors/monitor-detector-types-for-anamoly.png
  static/img/monitors/monitor-playbooks-ui.png
  static/img/monitors/new-monitor-details.png
  static/img/monitors/new-monitor-dialog.png
  static/img/monitors/new-monitor-playbook.png
  static/img/monitors/new-monitor-set-trigger-conditions.png
  static/img/monitors/setup-logs.png
  static/img/monitors/usecase3.png
  static/img/monitors/usecase4.png
Labels: doc:new, cla-signed

#3815 Update lambda.md
  docs/integrations/amazon-aws/lambda.md
Labels: cla-signed

#3830 Add Classic Metrics deprecation note
  docs/metrics/index.md
  docs/metrics/metric-charts/add-metrics-visualization-to-dashboard.md
  docs/metrics/metric-charts/create-metrics-visualization.md
  docs/metrics/metric-charts/index.md
  docs/metrics/metric-charts/interacting-metric-charts.md
  docs/metrics/metric-charts/line-area-metric-charts.md
  docs/metrics/metric-charts/log-overlay-analyze-metrics-visualizations.md
  docs/metrics/metric-charts/metrics-outliers.md
  docs/metrics/metric-charts/quantization-interval-chart.md
  docs/metrics/metric-charts/single-value-metric-charts.md
  docs/metrics/metrics-queries/metrics-explorer.md
  docs/metrics/metrics-queries/metrics-queries-classic.md
  docs/reuse/classic-metrics-deprecation.md
Labels: doc:minor edit, cla-signed

#3835 Add audit logging for MITRE coverage
  docs/cse/administration/cse-audit-logging.md
  docs/cse/administration/mitre-coverage.md
Labels: doc:new, cla-signed

#3833 Minor update to training article
  docs/get-started/training-certification-faq.md
Labels: doc:minor edit, cla-signed

#3837 App Central Integration - Datto RMM
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/datto-rmm.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  static/img/platform-services/automation-service/app-central/logos/datto.png
Labels: cla-signed

#3836 Metadata fields path updated
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/code42-incydr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-cyber-resilience-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/kaltura-source.md
Labels: cla-signed, hot🔥

#3839 Add Time Parsing Note to Config C2C
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed

#3759 Abnormal security C2C doc update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/abnormal-security-source.md
  static/files/c2c/abnormal-security/example.json
  static/files/c2c/abnormal-security/example.tf
Labels: cla-signed

#3842 Update index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/root-cause-explorer.md
Labels: cla-signed

#3844 correct SUMOLOGIC_URL referent
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
Labels: cla-signed

#3840 Update left nav for the automation bridge
  docs/cloud-soar/cloud-soar-bridge.md
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: doc:minor edit, cla-signed

#3845 Update additional-configurations-reference.md
  docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
Labels: cla-signed

#3846 Uplate CIP to new term
  docs/contributing/word-list.md
  docs/get-started/sign-up.md
Labels: doc:minor edit, cla-signed

#3847 Change Sumo Logic CIP integration name
  docs/cse/automation/cloud-siem-automation-examples.md
  static/img/cse/automation-examples-edit-sumo-logic-resource.png
  static/img/cse/automation-examples-search-sumo-logic-node.png
  static/img/cse/automation-examples-sumo-logic-cip-resource-edit-button.png
Labels: doc:update, cla-signed

#3832 Update links to the Cloud SOAR comparison article
  docs/cloud-soar/compared-to-automation-service.md
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/platform-services/automation-service/about-automation-service.md
Labels: doc:update, cla-signed

#3848 Flex doc review comments updates
  docs/manage/partitions/data-tiers/data-tiers-faqs.md
  docs/manage/partitions/data-tiers/index.md
  docs/manage/partitions/index.md
Labels: cla-signed

#3841 Collector 19.484-2 Release Notes
  blog-collector/2024-03-18.md
Labels: cla-signed

#3850 Forward data example text
  docs/manage/data-forwarding/amazon-s3-bucket.md
Labels: doc:minor edit, cla-signed

#3851 Fixed link formatting
  docs/dashboards/restricted-operators-dashboards.md
Labels: cla-signed

#3857 APP-2946 - Update Threat Intel beta to STIX 2.x
  docs/platform-services/threat-intelligence-indicators.md
  static/img/platform-services/threat-intelligence-add-indicators.png
Labels: doc:minor edit, cla-signed

#3858 Flex Pricing release notes
  blog-service/2024-03-20-flex.md
Labels: cla-signed

#3859 Add 'do not merge' label to PR Checks workflow
  .github/workflows/pr.yml
Labels: cla-signed

#3828 Log Search Audit Index Fields Enhancement (Release notes)
  blog-service/2024-03-20-search.md
Labels: cla-signed

#3863 App Central Integration - Zscaler
  docs/platform-services/automation-service/app-central/integrations/zscaler.md
Labels: cla-signed

#3865 App Central Integration - CyberArk PAM
  docs/platform-services/automation-service/app-central/integrations/cyberark-pam.md
Labels: cla-signed

#3867 Revert "Add 'do not merge' label to PR Checks workflow"
  .github/workflows/pr.yml
Labels: cla-signed

#3866 Flex pricing release notes revision
  blog-service/2024-03-20-flex.md
Labels: cla-signed

#3864 Collecting metrics doc update
  docs/send-data/kubernetes/collecting-metrics.md
Labels: cla-signed

#3869 App Central Integration - Zendesk
  docs/platform-services/automation-service/app-central/integrations/zendesk.md
Labels: cla-signed

#3870 March 21, 2024 - Content Release
  blog-csoar/2024-03-21-content.md
Labels: cla-signed

#3871 CSOAR-1746 - Actions limit query
  docs/cloud-soar/automation.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/reuse/actions-limit-query.md
Labels: doc:update, cla-signed

#3872 Create 2024-03-21-content.md
  blog-cse/2024-03-21-content.md
Labels: doc:new, cla-signed

#3400 cloudquery-source doc added
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/cloudquery/example.json
  static/files/c2c/cloudquery/example.tf
  static/img/send-data/cloudquery-logo.png
Labels: cla-signed

#3873 Update troubleshooting.md
  docs/send-data/opentelemetry-collector/troubleshooting.md
Labels: cla-signed

#3874 App Central Integration - Slack
  docs/platform-services/automation-service/app-central/integrations/slack.md
Labels: cla-signed

#3875 Atlassian Oppsgenie integration.
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/atlassian-oppsgenie.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  static/img/platform-services/automation-service/app-central/logos/atlassian.png
Labels: cla-signed

#3877 INVS-2047 - Add APIs info to MITRE article
  docs/cse/administration/mitre-coverage.md
Labels: doc:update, cla-signed

#3876 CSOAR-1329 - Add note for certified integrations
  docs/cloud-soar/automation.md
Labels: doc:minor edit, cla-signed

#3878 Refresh HUD image
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
  static/img/cse/hud.png
Labels: doc:minor edit, cla-signed

#3879 Update .clabot
  .clabot
Labels: cla-signed

#3880 Create 2024-03-22-application-update.md
  blog-cse/2024-03-22-application-update.md
Labels: cla-signed

#3853 DOCS-58 - Anomaly detection design updates
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  static/img/monitors/anomaly-detection-input.png
  static/img/monitors/monitor-anomaly-logs.png
  static/img/monitors/monitor-detection-methods-for-logs.png
  static/img/monitors/monitor-detection-methods-for-metrics.png
  static/img/monitors/monitor-detector-types-for-anamoly.png
  static/img/monitors/new-monitor-anomaly-detection-method.png
  static/img/monitors/new-monitor-window.png
  static/img/monitors/outlier-detection-input.png
Labels: doc:update, cla-signed

#3881 Update the glossary
  docs/contributing/glossary.md
Labels: doc:minor edit, cla-signed

#3885 updated integrations on App Central
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/atlassian-opsgenie.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/app-central/integrations/joe-sandbox.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-ews-daemon.md
  docs/platform-services/automation-service/app-central/integrations/smtp-v3.md
Labels: cla-signed

#3884 rm Dashboards /v1 doc
  cid-redirects.json
  docs/api/dashboard-data.md
  docs/api/dashboard.md
  docs/api/index.md
  sidebars.ts
Labels: cla-signed

#3887 Add kaliserichmond to clabot
  .clabot
Labels: cla-signed

#3886 AWS UI changed selection for subscription
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
Labels: cla-signed

#3888 Revert "AWS UI changed selection for subscription"
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
Labels: cla-signed

#3855 Estimate scan data doc added
  cid-redirects.json
  docs/manage/partitions/flex/estimate-and-actual-scan-data.md
  docs/manage/partitions/flex/estimate-scan-data.md
  docs/manage/partitions/flex/index.md
  sidebars.ts
  static/img/partitions-data-tiers/flex-pricing/estimated-scanned-data.png
  static/img/partitions-data-tiers/flex-pricing/monitors_1.png
  static/img/partitions-data-tiers/flex-pricing/monitors_2.png
  static/img/partitions-data-tiers/flex-pricing/no-scan-data.png
  static/img/partitions-data-tiers/flex-pricing/scan-details.png
  static/img/partitions-data-tiers/flex-pricing/scan-schedules-search.png
Labels: cla-signed

#3889 AWS CloudTrail and Data Firehose fixes
  docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
  static/img/send-data/cloudtrail_events.png
Labels: cla-signed

#3891 new release note for cloud soar
  blog-csoar/2024-03-26-application-update.md
Labels: cla-signed

#3883 Add no-index tag to /reuse files
  docs/contributing/style-guide.md
  docs/reuse/actions-limit-query.md
  docs/reuse/actions-limit.md
  docs/reuse/alert-variables.md
  docs/reuse/api-endpoints.md
  docs/reuse/api-errors.md
  docs/reuse/api-intro.md
  docs/reuse/api-rate-limit.md
  docs/reuse/apm-traces-layer-order.md
  docs/reuse/apps/app-install-sumo-apps.md
  docs/reuse/apps/app-install-v2.md
  docs/reuse/apps/app-install.md
  docs/reuse/apps/create-aws-s3-source.md
  docs/reuse/apps/jfrog/artifactory-cached.md
  docs/reuse/apps/jfrog/artifactory-download.md
  docs/reuse/apps/jfrog/artifactory-noncached.md
  docs/reuse/apps/jfrog/artifactory-overview.md
  docs/reuse/apps/jfrog/artifactory-request-access.md
  docs/reuse/apps/jfrog/artifactory-traffic.md
  docs/reuse/apps/logs-collection-prereqisites.md
  docs/reuse/apps/opentelemetry/ansible-with-env.md
  docs/reuse/apps/opentelemetry/ansible-without-env.md
  docs/reuse/apps/opentelemetry/chef-with-env.md
  docs/reuse/apps/opentelemetry/chef-without-env.md
  docs/reuse/apps/opentelemetry/config-app-install.md
  docs/reuse/apps/opentelemetry/process-metric-collection.md
  docs/reuse/apps/opentelemetry/puppet-with-env.md
  docs/reuse/apps/opentelemetry/puppet-without-env.md
  docs/reuse/apps/opentelemetry/send-logs-intro.md
  docs/reuse/apps/opentelemetry/send-logs-outro.md
  docs/reuse/apps/opentelemetry/set-up-collector.md
  docs/reuse/apps/view-dashboards.md
  docs/reuse/aws-cost-explorer.md
  docs/reuse/aws-region-by-sumo-deployment.md
  docs/reuse/budget-assignment.md
  docs/reuse/classic-metrics-deprecation.md
  docs/reuse/collection-should-begin-note.md
  docs/reuse/cse-api-table.md
  docs/reuse/cse-launch-csoar-automation.md
  docs/reuse/cse-rule-description-links.md
  docs/reuse/csoar-api-table.md
  docs/reuse/doc-prerequisites.md
  docs/reuse/fer-limitations.md
  docs/reuse/filter-dashboards.md
  docs/reuse/flex-pricing.md
  docs/reuse/metadata-data-enrichment.md
  docs/reuse/restart-c2c-source.md
  docs/reuse/saml.md
  docs/reuse/ui-elements.md
Labels: cla-signed

#3894 Fix Case example
  docs/cse/schema/parsing-language-reference-guide.md
Labels: doc:minor edit, cla-signed

#3895 Add ccressent to CLA
  .clabot
Labels: doc:minor edit, cla-signed

#3893 Fix pod description
  docs/observability/kubernetes/about.md
Labels: doc:minor edit, cla-signed

#3890 Estimate Scan Data - Flex Release note
  blog-service/2024-03-27-search.md
  docs/manage/partitions/data-tiers/searching-data-tiers.md
  docs/manage/partitions/flex/estimate-scan-data.md
  static/img/partitions-data-tiers/flex-pricing/meter-icon.png
Labels: cla-signed

#3899 CONN-2682: Updated the CloudQuery source file
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
  static/files/c2c/cloudquery/accountExample.json
  static/files/c2c/cloudquery/accountExample.tf
  static/files/c2c/cloudquery/orgExample.json
  static/files/c2c/cloudquery/orgExample.tf
Labels: cla-signed

#3901 Add CID entries for "Estimate Scan Data" article
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#3903 Remove text from redundant signal suppression example
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
Labels: doc:minor edit, cla-signed

#3905 Revert "Add no-index tag to /reuse files"
  docs/contributing/style-guide.md
  docs/reuse/actions-limit-query.md
  docs/reuse/actions-limit.md
  docs/reuse/alert-variables.md
  docs/reuse/api-endpoints.md
  docs/reuse/api-errors.md
  docs/reuse/api-intro.md
  docs/reuse/api-rate-limit.md
  docs/reuse/apm-traces-layer-order.md
  docs/reuse/apps/app-install-sumo-apps.md
  docs/reuse/apps/app-install-v2.md
  docs/reuse/apps/app-install.md
  docs/reuse/apps/create-aws-s3-source.md
  docs/reuse/apps/jfrog/artifactory-cached.md
  docs/reuse/apps/jfrog/artifactory-download.md
  docs/reuse/apps/jfrog/artifactory-noncached.md
  docs/reuse/apps/jfrog/artifactory-overview.md
  docs/reuse/apps/jfrog/artifactory-request-access.md
  docs/reuse/apps/jfrog/artifactory-traffic.md
  docs/reuse/apps/logs-collection-prereqisites.md
  docs/reuse/apps/opentelemetry/ansible-with-env.md
  docs/reuse/apps/opentelemetry/ansible-without-env.md
  docs/reuse/apps/opentelemetry/chef-with-env.md
  docs/reuse/apps/opentelemetry/chef-without-env.md
  docs/reuse/apps/opentelemetry/config-app-install.md
  docs/reuse/apps/opentelemetry/process-metric-collection.md
  docs/reuse/apps/opentelemetry/puppet-with-env.md
  docs/reuse/apps/opentelemetry/puppet-without-env.md
  docs/reuse/apps/opentelemetry/send-logs-intro.md
  docs/reuse/apps/opentelemetry/send-logs-outro.md
  docs/reuse/apps/opentelemetry/set-up-collector.md
  docs/reuse/apps/view-dashboards.md
  docs/reuse/aws-cost-explorer.md
  docs/reuse/aws-region-by-sumo-deployment.md
  docs/reuse/budget-assignment.md
  docs/reuse/classic-metrics-deprecation.md
  docs/reuse/collection-should-begin-note.md
  docs/reuse/cse-api-table.md
  docs/reuse/cse-launch-csoar-automation.md
  docs/reuse/cse-rule-description-links.md
  docs/reuse/csoar-api-table.md
  docs/reuse/doc-prerequisites.md
  docs/reuse/fer-limitations.md
  docs/reuse/filter-dashboards.md
  docs/reuse/flex-pricing.md
  docs/reuse/metadata-data-enrichment.md
  docs/reuse/restart-c2c-source.md
  docs/reuse/saml.md
  docs/reuse/ui-elements.md
Labels: cla-signed

#3862 Azure Event Hubs Source for Logs doc updated
  docs/send-data/collect-from-other-data-sources/azure-monitoring/ms-azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  sidebars.ts
  static/img/send-data/azure-event-hub-name.png
Labels: cla-signed

#3623 Added info about the vertical lines to time series panels
  docs/dashboards/panels/index.md
  docs/dashboards/set-custom-time-ranges.md
  static/img/dashboards-new/panels/crosshair_1.png
  static/img/dashboards-new/panels/crosshair_2.png
  static/img/dashboards-new/set-custom-time-ranges/update-dashboard-time-range.png
Labels: cla-signed

#3852 Create 2024-03-20-dashboards.md
  blog-service/2024-03-28-dashboards.md
Labels: cla-signed

#3904 Update metrics screen images
  docs/metrics/logs-to-metrics.md
  docs/metrics/metric-rules-editor.md
  docs/metrics/metrics-transformation-rules.md
  static/img/metrics/add-a-rule.png
  static/img/metrics/add-logs-to-metrics-rules.png
  static/img/metrics/add-metric-rule-empty.png
  static/img/metrics/add-metric-rule-with-expression.png
  static/img/metrics/disabled-ltm.png
  static/img/metrics/dpm.png
  static/img/metrics/log-to-metrics-add.png
  static/img/metrics/mets-dims.png
  static/img/metrics/named-rule.png
  static/img/metrics/preview-parse-expression.png
  static/img/metrics/variable-extraction-selection.png
  static/img/metrics/variable-extracton.png
Labels: doc:update, cla-signed

#3907 Fix text in CIS for AWS article
  docs/integrations/amazon-aws/cloud-infrastructure-security-for-aws.md
Labels: doc:minor edit, cla-signed

#3909 Remove deprecated labels from CrowdStrike Falcon article
  docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection.md
Labels: doc:minor edit, cla-signed

#3912 Update cloud-infrastructure-security-for-aws.md
  docs/integrations/amazon-aws/cloud-infrastructure-security-for-aws.md
Labels: cla-signed

#3911 Remove cat search operator from Threat Intel beta
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:update, cla-signed

#3913 Update dashboard.md
  docs/api/dashboard.md
Labels: cla-signed

#3915 Create 2024-03-28-content.md
  blog-cse/2024-03-28-content.md
Labels: cla-signed

#3914 Define detected relationship
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
Labels: doc:minor edit, cla-signed

#3898 Update scheduled-report.md
  docs/dashboards/scheduled-report.md
Labels: cla-signed

#3906 Update enable-sni-collector-transparent-proxy.md
  docs/send-data/installed-collectors/collector-installation-reference/enable-sni-collector-transparent-proxy.md
Labels: cla-signed

#3791 Metadata field added (Cato Networks)
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
Labels: cla-signed

#3917 Add filter node
  docs/cloud-soar/automation.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/cloud-soar/add-filter-node.png
  static/img/cloud-soar/add-node-button.png
  static/img/cloud-soar/add-node-dialog.png
  static/img/cloud-soar/configure-filter-node.png
  static/img/platform-services/automation-service/add-node-button.png
  static/img/platform-services/automation-service/automations-add-filter-node-conditions.png
  static/img/platform-services/automation-service/automations-add-filter-node.png
Labels: doc:new, cla-signed

#3861 Index aliasing
  blog-service/2024-03-29-search.md
  docs/manage/partitions/run-search-against-partition.md
Labels: cla-signed, do-not-merge

#3910 Update alert-grouping.md
  docs/alerts/monitors/alert-grouping.md
Labels: cla-signed

#3920 Remove reference to deprecated admonition style
  docs/api/collector-management/index.md
Labels: cla-signed

#3897 Update windows.md for validating FIPS
  docs/send-data/opentelemetry-collector/install-collector/windows.md
Labels: cla-signed

#3921 Update how to create a monitor from Metrics Explorer
  docs/alerts/monitors/create-monitor.md
Labels: doc:minor edit, cla-signed

#3922 Fix "Search Job APIs" article
  docs/api/search-job.md
Labels: doc:minor edit, cla-signed

#3924 Add user to clabot
  .clabot
Labels: cla-signed

#3925 Update kubernetes.md
  docs/integrations/containers-orchestration/kubernetes.md
Labels: cla-signed

#3927 Add new CLA user
  .clabot
Labels: cla-signed

#3923 update Asana source docs for upcoming Asana release
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/asana-source.md
  static/img/send-data/asana-service-account-create.png
  static/img/send-data/asana-token-copy.png
  static/img/send-data/pat.png
Labels: cla-signed

#3928 DOCS-95 - Fix broken link
  docs/cloud-soar/incidents-triage.md
Labels: doc:minor edit, cla-signed

#3930 DOCS-29 - Favorite fields
  docs/cse/records-signals-entities-insights/view-records-signal.md
  static/img/cse/attached-records.png
  static/img/cse/disable-favorite-field.png
  static/img/cse/enable-favorite-field.png
  static/img/cse/example-record-favorite-fields.png
  static/img/cse/example-record.png
  static/img/cse/favorite-field.png
Labels: doc:new, cla-signed
