Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-04, with the labels that each got.

#3931 Update view records article
  docs/cse/records-signals-entities-insights/view-records-signal.md
Labels: doc:minor edit, cla-signed

#3916 Update apps-integrations.md
  docs/get-started/apps-integrations.md
Labels: cla-signed

#3932 Update index.md
  docs/manage/partitions/data-tiers/index.md
Labels: cla-signed

#3902 Migration from V1 to V2 budgets
  docs/api/ingest-budget-v1.md
  docs/api/ingest-budget-v2.md
  docs/manage/ingestion-volume/ingest-budgets/index.md
Labels: cla-signed

#3937 resolve-alert-deletion-faq-arp
  docs/alerts/monitors/alert-response-faq.md
Labels: cla-signed

#3935 Update scheduled-report.md
  docs/dashboards/scheduled-report.md
Labels: cla-signed

#3938 Update STIX/TAXII articles
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
Labels: doc:minor edit, cla-signed

#3940 Update search filter limitations
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
Labels: doc:minor edit, cla-signed

#3942 Update insight-generation-process.md
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
Labels: cla-signed

#3944 Update notes for Fed deployment
  docs/reuse/fed-deployment-note.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/abnormal-security-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/airtable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/asana-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-cloud-to-cloud-source-migration.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/box-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-amp-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-vulnerability-management-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/code42-incydr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-host-inventory.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-filevantage.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-spotlight-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/docusign-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-cyber-resilience-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/druva-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/duo-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-bigquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jfrog-xray.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/knowbe4-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-azure-ad-inventory-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-exchange-trace-logs.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-azure-ad-reporting-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-identity-protection-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/miro-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/okta-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/palo-alto-cortex-xdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-on-demand-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/proofpoint-tap-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/qualys-vmdr-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sentinelone-mgmt-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/slack-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sophos-central-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/trellix-mvisio-epo-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/webex-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zero-networks-segment-source.md
Labels: doc:minor edit, cla-signed

#3945 Deleted Credits Dashboard from Data Volume app
  docs/integrations/sumo-apps/data-volume.md
Labels: doc:update, cla-signed

#3950 feat: document example of setting HTTP_PROXY for windows
  docs/send-data/opentelemetry-collector/install-collector/windows.md
Labels: cla-signed

#3951 Add one action to VirusTotal
  docs/platform-services/automation-service/app-central/integrations/virustotal.md
Labels: cla-signed

#3953 Cid number added for ms-azure-event-hubs-source
  cid-redirects.json
Labels: cla-signed, hot🔥

#3952 [New integration] Druva
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/druva.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  static/img/platform-services/automation-service/app-central/logos/druva.png
Labels: cla-signed

#3954 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#3949 Azure Event Hubs Release notes
  blog-service/2024-04-05-collection.md
Labels: cla-signed

#3959 added the change log
  docs/platform-services/automation-service/app-central/integrations/servicenow-v2.md
Labels: cla-signed

#3958 Adding a NOTE for log level based routing to data tiers
  docs/search/get-started-with-search/search-page/log-level.md
Labels: cla-signed

#3957 Update Support links
  docs/alerts/monitors/monitor-faq.md
  docs/alerts/scheduled-searches/faq.md
  docs/api/getting-started.md
  docs/api/index.md
  docs/contributing/index.md
  docs/get-started/quickstart.md
  docs/get-started/sumo-logic-ui.md
  docs/integrations/app-development/jfrog-artifactory.md
  docs/integrations/index.md
  docs/manage/manage-subscription/close-cancel-sumo-account.md
  docs/manage/manage-subscription/manage-org-settings.md
  docs/manage/users-roles/users/offboard-user.md
  docs/search/index.md
  docs/search/search-query-language/index.md
  docs/send-data/collector-faq.md
  docs/send-data/use-json-configure-sources/troubleshooting-json-configure-sources.md
  docusaurus.config.js
  i18n/ja/alerts/alerts/monitors/monitor-faq.md
  i18n/ja/alerts/alerts/scheduled-searches/faqs/alerts-from-static-ip-address.md
  i18n/ja/alerts/alerts/scheduled-searches/faqs/failed-scheduled-search.md
  i18n/ja/alerts/alerts/scheduled-searches/faqs/suspended-scheduled-search.md
  i18n/ja/docusaurus-theme-classic/footer.json
Labels: cla-signed

#3955 Create 2024-04-04-content.md
  blog-cse/2024-04-05-content.md
Labels: cla-signed

#3956 Real-Time Sched Search deprecation notice
  docs/alerts/scheduled-searches/deprecation.md
Labels: cla-signed, do-not-merge

#3946 CONN-3085 Update netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: cla-signed

#3960 Updating Oracle Documentation
  docs/send-data/collect-from-other-data-sources/collect-logs-oracle-cloud-infrastructure.md
  static/img/send-data/oci-application.png
  static/img/send-data/oci-logging.png
  static/img/send-data/oci-resource-log.png
  static/img/send-data/oci-service-connector.png
  static/img/send-data/oci-sumo.png
Labels: cla-signed, do-not-merge

#3961 Re-named Sumo Logic Integrations on App Central
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem-internal.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-log-analytics-internal.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-log-analytics.md
  static/img/platform-services/automation-service/app-central/logos/cse-tools.png
  static/img/platform-services/automation-service/app-central/logos/sumo-logic-cse.png
Labels: cla-signed

#3962 Update Cisco Umbrella limitations
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
Labels: doc:minor edit, cla-signed

#3939 CSOAR-1861: Add csoar cloud execution egress topic
  docs/cloud-soar/architecture.md
Labels: cla-signed

#3965 CONN-2714 update how to gather service user token
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sentinelone-mgmt-api-source.md
Labels: cla-signed

#3963 Update Fastly variables
  docs/integrations/saas-cloud/fastly.md
Labels: doc:minor edit, cla-signed

#3967 20240409-new release note for cloud soar
  blog-csoar/2024-04-09-application-update.md
Labels: cla-signed

#3969 Cisco Talos integration removed from App Central
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/cisco-talos.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem.md
  static/img/platform-services/automation-service/app-central/logos/cisco-talos.png
Labels: cla-signed

#3966 Conn 3077 need to add all pre requisite steps of creating roles in help doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
Labels: cla-signed

#3970 Update rds.md
  docs/integrations/amazon-aws/rds.md
Labels: cla-signed

#3934 Feature: Set muting schedule for alert group
  blog-service/2024-04-10-alerts-monitors.md
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/muting-schedules.md
  static/img/alerts/mute-sched-alert-groups1.png
  static/img/alerts/mute-sched-alert-groups2.png
Labels: cla-signed

#3974 Update index.md
  docs/send-data/hosted-collectors/index.md
Labels: cla-signed

#3976 Add text to filter node section
  docs/cloud-soar/automation.md
Labels: doc:update, cla-signed

#3929 DOCS-31 - Update standard match lists
  docs/cse/match-lists-suppressed-lists/standard-match-lists.md
Labels: doc:update, cla-signed

#3975 Add RSAC banner
  docusaurus.config.js
Labels: cla-signed

#3973 Update Metrics DPM beta article
  docs/metrics/metrics-dpm.md
  static/img/metrics/metrics-dpm.png
Labels: doc:update, cla-signed

#3978 Cloud SIEM Release Notes for April 11, 2024
  blog-cse/2024-04-11-application-update.md
  static/img/release-notes/cse/csiem-light-dark-theme.jpg
  static/img/release-notes/cse/mitre-attack-explorer-custom-colors.jpg
  static/img/release-notes/cse/theme-setting.png
Labels: cla-signed

#3971 Update salesforce.md
  docs/integrations/saas-cloud/salesforce.md
Labels: cla-signed

#3972 Cross tier query screenshots updated
  static/img/partitions-data-tiers/CrossTier-Query-Complete-SearchDetails.png
  static/img/partitions-data-tiers/CrossTier-Query-Complete.png
  static/img/partitions-data-tiers/CrossTier-Query-Start-Estimated-Scan-2.png
  static/img/partitions-data-tiers/CrossTier-Query-Start-Estimated-Scan.png
Labels: cla-signed

#3977 Cloud SIEM light theme
  docs/cloud-soar/overview.md
  docs/cse/introduction-to-cloud-siem.md
  docs/get-started/account-settings-preferences.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/reuse/dark-light-theme.md
  static/img/get-started/change-email.png
  static/img/get-started/change-password.png
  static/img/get-started/change-password2.png
  static/img/get-started/preference-settings.png
Labels: doc:new, cla-signed

#3980 Corrections to 'Sumo Logic Credits Accounts' article
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
Labels: doc:minor edit, cla-signed

#3981 Log Analytics Platform (LAP) Connection with Full CSOAR
  docs/alerts/webhook-connections/cloud-soar.md
  docs/cloud-soar/automation.md
  sidebars.ts
  static/img/cloud-soar/CSOAR-connection1.png
  static/img/cloud-soar/api_documentation.png
  static/img/cloud-soar/iso_parser.png
Labels: cla-signed

#3984 Update otel collector install script urls
  docs/send-data/opentelemetry-collector/install-collector/linux.md
  docs/send-data/opentelemetry-collector/install-collector/macos.md
  docs/send-data/opentelemetry-collector/install-collector/windows.md
  docs/send-data/opentelemetry-collector/quickstart.md
Labels: cla-signed

#3985 Correction for the Cloud SOAR webhooks article
  docs/cloud-soar/automation.md
Labels: doc:minor edit, cla-signed

#3983 Renamed integrations updates
  docs/cse/automation/cloud-siem-automation-examples.md
  static/img/cse/automation-examples-add-insight-enrichmeent-node.png
  static/img/cse/automation-examples-add-insight-enrichment-node.png
  static/img/cse/automation-examples-advanced-add-insight-enrichment-node.png
Labels: doc:update, cla-signed

#3988 [App Central] Basic Tools Integration updated
  docs/platform-services/automation-service/app-central/integrations/basic-tools.md
Labels: cla-signed

#3989 Update compute-engine.md
  docs/integrations/google/compute-engine.md
Labels: cla-signed

#3992 App Central Integration - AWS EKS
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/aws-eks.md
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#3993 April 18, 2024 - Content Release
  blog-csoar/2024-04-18-content.md
Labels: cla-signed

#3995 Revert "April 18, 2024 - Content Release"
  blog-csoar/2024-04-18-content.md
Labels: cla-signed

#3996 Revert "App Central Integration - AWS EKS"
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/aws-eks.md
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#3997 Resubmit Cloud SOAR release note for April 18, 2024
  blog-csoar/2024-04-18-content.md
Labels: doc:new, cla-signed

#3998 Resubmit AWS EKS article
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/aws-eks.md
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: doc:new, cla-signed

#3947 Fixes to Contribution Guide, Get Started
  cid-redirects.json
  docs/contributing/create-doc.md
  docs/contributing/create-edit-doc.md
  docs/contributing/edit-doc.md
  docs/contributing/index.md
  docs/contributing/style-guide.md
  docs/get-started/account-settings-preferences.md
  docs/manage/security/about-2-step-verification.md
  docs/manage/security/access-keys.md
  docs/reuse/contributing/fork-repo.md
  docs/reuse/contributing/preview.md
  docs/reuse/contributing/submit.md
  docs/reuse/contributing/tools.md
  sidebars.ts
  static/img/get-started/change-email.png
  static/img/get-started/change-password.png
  static/img/security/access-key-preferences-page-2.png
  static/img/security/access-key-preferences-page.png
  static/img/security/access-key-three-dot.png
  static/img/security/create-access-key-2.png
  static/img/security/create-access-key.png
Labels: cla-signed

#3999 Merge queue fix
  .github/workflows/pr.yml
Labels: cla-signed

#4004 chore: fix example links, update otelcol version for other environments
  docs/apm/traces/get-started-transaction-tracing/set-up-traces-collection-for-other-environments.md
Labels: cla-signed

#4005 aws waf integration.
  docs/integrations/product-list.md
  docs/platform-services/automation-service/app-central/integrations/aws-waf.md
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#3987 SUMO-239173: v1-v2 Migration 9 Apps doc
  docs/integrations/google/cloud-load-balancing.md
  docs/integrations/google/cloud-sql.md
  docs/integrations/google/cloud-storage.md
  docs/integrations/google/cloud-vpc.md
  docs/integrations/google/compute-engine.md
  docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
  docs/integrations/microsoft-azure/office-365.md
  docs/integrations/saas-cloud/microsoft-graph-azure-ad-reporting.md
  docs/integrations/saas-cloud/microsoft-graph-security-v1.md
  docs/integrations/saas-cloud/microsoft-graph-security-v2.md
Labels: cla-signed

#3994 SUMO-238071: V1-V2 app migration for 4 apps
  docs/integrations/microsoft-azure/active-directory-azure.md
  docs/integrations/microsoft-azure/audit.md
  docs/integrations/microsoft-azure/network-watcher.md
  docs/integrations/microsoft-azure/sql.md
Labels: cla-signed

#3986 SUMO-239067: doc for v1-v2 10 apps
  docs/integrations/amazon-aws/cloudfront.md
  docs/integrations/amazon-aws/inspector-classic.md
  docs/integrations/amazon-aws/inspector.md
  docs/integrations/google/app-engine.md
  docs/integrations/google/bigquery.md
  docs/integrations/google/cloud-audit.md
  docs/integrations/google/cloud-firewall.md
  docs/integrations/google/cloud-functions.md
  docs/integrations/google/cloud-iam.md
  docs/integrations/saas-cloud/fastly.md
Labels: cla-signed, hot🔥

#4010 Added user for clabot
  .clabot
Labels: cla-signed, hot🔥

#3936 Filter partitions
  blog-service/2024-04-23-filter-partitions.md
  docs/manage/partitions/run-search-against-partition.md
  static/img/partitions-data-tiers/filter-and-search-a-partition.png
  static/img/partitions-data-tiers/partitions-page-flex.png
  static/img/partitions-data-tiers/partitions-page-search-icon.png
  static/img/partitions-data-tiers/partitions-page.png
Labels: cla-signed

#4001 Ingest budget doc updates
  cid-redirects.json
  docs/get-started/quickstart.md
  docs/manage/ingestion-volume/ingest-budgets/daily-volume/assign-collector-ingest-budget.md
  docs/manage/ingestion-volume/ingest-budgets/daily-volume/index.md
  docs/manage/ingestion-volume/ingest-budgets/daily-volume/quickstart.md
  docs/manage/ingestion-volume/ingest-budgets/index.md
  docs/manage/ingestion-volume/ingest-budgets/minute-volume.md
  sidebars.ts
Labels: cla-signed

#3941 Prep work for CloudQuery preview - CIS for AWS
  docs/integrations/amazon-aws/cloud-infrastructure-security-for-aws.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  static/img/integrations/amazon-aws/cis-for-aws-cloud-query-config.png
  static/img/integrations/amazon-aws/cis-for-aws-cloud-siem-insights.png
  static/img/integrations/amazon-aws/cis-for-aws-infrastructure-overview.png
  static/img/integrations/amazon-aws/cis-for-aws-install-1.png
  static/img/integrations/amazon-aws/cis-for-aws-install-step-1.png
  static/img/integrations/amazon-aws/cis-for-aws-install-step-2.png
  static/img/integrations/amazon-aws/cis-for-aws-install-step-3.png
  static/img/integrations/amazon-aws/cis-for-aws-permissions-cft.png
  static/img/integrations/amazon-aws/cis-for-aws-security-control-failures-aws-security-hub.png
  static/img/integrations/amazon-aws/cis-for-aws-security-control-failures-investigation.png
  static/img/integrations/amazon-aws/cis-for-aws-security-control-failures-overview.png
  static/img/integrations/amazon-aws/cis-for-aws-start-using-sumo.png
Labels: doc:new, cla-signed

#4016 App Central Integration - Okta
  docs/platform-services/automation-service/app-central/integrations/okta.md
Labels: cla-signed

#4018 Update .clabot
  .clabot
Labels: cla-signed

#4017 Fix for create-edit-doc URL
  docs/contributing/index.md
Labels: cla-signed

#4025 CONN-3135: Updated slack documenation with limitations
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/slack-source.md
Labels: cla-signed

#4026 Update remote-management.md
  docs/send-data/opentelemetry-collector/remote-management.md
Labels: cla-signed

#4027 DOCS-140 - Clean up Cloud SOAR (Kanso prep)
  blog-csoar/2024-02-06-application-update.md
  cid-redirects.json
  docs/cloud-soar/audit-event-index.md
  docs/cloud-soar/automation.md
  docs/cloud-soar/cloud-soar-integration-framework.md
  docs/cloud-soar/compared-to-automation-service.md
  docs/cloud-soar/global-functions-menu.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/index.md
  docs/cloud-soar/legacy/legacy-cloud-soar-apis.md
  docs/cloud-soar/legacy/legacy-cloud-soar-main-menu.md
  docs/cloud-soar/legacy/legacy-cloud-soar-mssp.md
  docs/cloud-soar/legacy/legacy-global-functions-menu.md
  docs/cloud-soar/main-menu.md
  docs/cloud-soar/overview.md
  docs/manage/users-roles/roles/role-capabilities.md
  sidebars.ts
  static/img/cloud-soar/cloud-soar-groups.png
  static/img/cloud-soar/image140.png
  static/img/cloud-soar/image142.png
  static/img/cloud-soar/image145.png
  static/img/cloud-soar/image26.png
  static/img/cloud-soar/image999.png
Labels: doc:update, cla-signed

#4024 Update apache-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-opentelemetry.md
Labels: cla-signed

#4031 chore: update examples for traffic shaping
  docs/apm/traces/advanced-configuration/filter-shape-tracing-data.md
Labels: cla-signed

#4029 SUMO-239629: Updated aws api gateway app
  docs/integrations/amazon-aws/api-gateway.md
Labels: cla-signed

#4030 Clarify Syslog source errors
  docs/send-data/installed-collectors/sources/syslog-source.md
Labels: cla-signed

#4033 Remove "noindex" tag from reuse files
  docs/reuse/fed-deployment-note.md
Labels: doc:minor edit, cla-signed, hot🔥

#4035 Redirects for Ingest Budget
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#4009 DOCS-132 - Add new UI menus for Cloud SIEM and Cloud SOAR (Kanso)
  docs/cloud-soar/overview.md
  docs/cse/introduction-to-cloud-siem.md
  static/img/cloud-soar/cloud-soar-administration-menu.png
  static/img/cloud-soar/cloud-soar-automation-sidebar-menu.png
  static/img/cloud-soar/cloud-soar-configuration-menu.png
  static/img/cloud-soar/cloud-soar-sidebar-menu.png
  static/img/cse/cloud-siem-configuration-menu-icon-new.png
  static/img/cse/cloud-siem-configuration-menu-new.png
  static/img/cse/cloud-siem-sidebar-menu.png
  static/img/get-started/administration-icon.png
  static/img/get-started/app-catalog-icon.png
  static/img/get-started/configuration-icon.png
  static/img/get-started/go-to-icon.png
  static/img/get-started/go-to-menu.png
  static/img/get-started/help-icon.png
  static/img/get-started/profile-icon-new.png
  static/img/get-started/sumo-logic-top-menu-bar-new.png
Labels: doc:new, cla-signed

#4020 Real-Time Scheduled Search deprecation (May 15)
  blog-service/2024-04-30-scheduled-search-alerts.md
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/deprecation.md
Labels: cla-signed

#4034 Clean up Cloud SIEM rules articles
  docs/cse/rules/write-aggregation-rule.md
  docs/cse/rules/write-chain-rule.md
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-match-rule.md
  docs/cse/rules/write-outlier-rule.md
  docs/cse/rules/write-threshold-rule.md
  static/img/cse/aggregation-rule.png
  static/img/cse/chain.png
  static/img/cse/empty-first-seen-rule.png
  static/img/cse/empty-outlier-rule.png
  static/img/cse/match.png
  static/img/cse/threshold.png
Labels: doc:new, cla-signed
