Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-10, with the labels that each got.

#4595 Azure Cache for Redis v2 app documentation
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
  static/img/send-data/azureredis-cache-logs.png
  static/img/send-data/azureredis-cache-metrics.png
Labels: cla-signed

#4599 Add partner integrations to product list
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/product-list/product-list-m-z.md
  static/img/integrations/misc/doppel-logo.png
  static/img/integrations/misc/netflow-logic-logo.png
  static/img/integrations/misc/phylum-logo.svg
Labels: doc:update, cla-signed

#4579 SUMO-242752 | Changes in IIS otel app to add metric collection and dashboards
  docs/integrations/web-servers/opentelemetry/iis-10-opentelemetry.md
Labels: cla-signed, do-not-merge

#4587 Updated version - App Central/Slack doc
  docs/platform-services/automation-service/app-central/integrations/slack.md
  static/img/platform-services/automation-service/app-central/integrations/slack/slack-16.png
Labels: cla-signed

#4601 Fix links to help-opensource.sumologic.com
  docs/manage/security/rotating-credentials-playbooks.md
Labels: doc:minor edit, cla-signed

#4603 Move LastPass from beta to GA
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/lastpass-source.md
  sidebars.ts
Labels: cla-signed, hot🔥

#4604 DOCS-407 - Fix ZeroFox link
  docs/integrations/product-list/product-list-m-z.md
Labels: doc:minor edit, cla-signed

#4605 Alerts/Monitors tags
  docs/alerts/monitors/settings.md
Labels: cla-signed

#4608 Add ishaanahuja29 to the .clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#4609 DOCS-455 - Cartesian product checkbox
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/reuse/cartesian-product.md
  static/img/platform-services/automation-service/automations-add-filter-node-conditions.png
Labels: doc:update, cla-signed

#4606 PLG-33 Sumo Logic Sample Data source doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-logic-sample-data-source.md
  sidebars.ts
  static/files/c2c/sumo-logic-sample-data/example.json
  static/files/c2c/sumo-logic-sample-data/example.tf
  static/img/send-data/sumo-logic-sample-data.png
Labels: cla-signed

#4607 PLG-33 Sumo Logic Sample Data (Astronomy) app doc
  cid-redirects.json
  docs/integrations/sumo-apps/sample-data-astronomy.md
  sidebars.ts
  static/img/integrations/sumo-apps/Sumo-Logic-Sample-Data-Astronomy-Application-Health-Dashboard.png
  static/img/integrations/sumo-apps/Sumo-Logic-Sample-Data-Astronomy-Business-KPIs-Dashboard.png
  static/img/integrations/sumo-apps/Sumo-Logic-Sample-Data-Astronomy-Icon.png
Labels: cla-signed

#4571 Doc changes - Azure WebApps
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/sql.md
  docs/integrations/microsoft-azure/web-apps.md
  static/img/send-data/azure-webapps-logs.png
  static/img/send-data/azure-webapps-metrics.png
Labels: cla-signed

#4611 Legacy 301 and 404 fixes
  cid-redirects.json
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/manage/partitions/data-tiers/faq.md
Labels: cla-signed

#4586 Azure Metrics Source doc
  cid-redirects.json
  docs/send-data/hosted-collectors/microsoft-source/azure-metrics-source.md
  static/files/c2c/azure-metrics/example.json
  static/img/send-data/azure-metrics-source/add-client-secret.png
  static/img/send-data/azure-metrics-source/app-registration.png
  static/img/send-data/azure-metrics-source/basics.png
  static/img/send-data/azure-metrics-source/client-secrets.png
  static/img/send-data/azure-metrics-source/create.png
  static/img/send-data/azure-metrics-source/new-client-secret.png
  static/img/send-data/azure-metrics-source/overview.png
  static/img/send-data/azure-metrics-source/register.png
  static/img/send-data/azure-metrics-source/subscriptions.png
Labels: cla-signed, do-not-merge

#4596 Update apps-integrations.md
  docs/get-started/apps-integrations.md
Labels: cla-signed

#4279 DOCS-100 - Forward raw data
  blog-service/2024-10-03-manage.md
  docs/manage/data-forwarding/amazon-s3-bucket.md
  docs/manage/data-forwarding/index.md
  docs/manage/data-forwarding/installed-collectors.md
  docs/manage/data-forwarding/view-list-data-forwarding.md
  docs/manage/partitions/data-tiers/infrequent-tier-data-forwarding.md
  docs/manage/partitions/decommission-partition.md
  docs/manage/partitions/flex/view-partition-details-flex.md
  static/img/data-forwarding/create-S3-destination.png
  static/img/data-forwarding/enable-option.png
  static/img/data-forwarding/forward-raw-data.png
  static/img/data-forwarding/specifiy-destination.png
  static/img/data-forwarding/specify-destination.png
  static/img/partitions-data-tiers/view-edit-partition-pane-flex.png
  static/img/partitions-data-tiers/view-edit-partition-pane.png
Labels: doc:new, cla-signed, do-not-merge

#4615 Remote mgmt/source templates fixes
  docs/integrations/containers-orchestration/docker-community-edition.md
  docs/integrations/containers-orchestration/docker-ulm.md
  docs/integrations/containers-orchestration/opentelemetry/docker-opentelemetry.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/index.md
  sidebars.ts
  static/img/integrations/containers-orchestration/docker-icon.png
  static/img/integrations/web-servers/apache.png
Labels: cla-signed

#4616 Windows events query fix
  docs/search/get-started-with-search/suggested-searches/windows-events.md
Labels: cla-signed

#4617 Optimizing monitor scan costs on Flex Licensing
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/monitor-faq.md
Labels: cla-signed

#4613 Update GitHub Actions to run on Node20
  .github/workflows/build_and_deploy.yml
  .github/workflows/pr.yml
Labels: doc:site tech, cla-signed

#4600 Changelog update for compatibility declaration in ST changelog
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/changelog.md
Labels: cla-signed

#4618 Release note title updated
  blog-service/2024-10-03-manage.md
Labels: cla-signed

#4621 Content-Release-2024-10-04
  blog-cse/2024-10-04-content.md
Labels: cla-signed

#4360 OTEL Remote Management / Source Templates beta fixes (pre-GA)
  docs/send-data/opentelemetry-collector/remote-management/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/index.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4620 Conn 3334 add offset pagination
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed

#4624 Update .clabot
  .clabot
Labels: cla-signed

#4623 chore: golang update instrumentation deps
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/go/index.md
Labels: cla-signed

#4625 Update 2024-10-04-content.md
  blog-cse/2024-10-04-content.md
Labels: cla-signed

#4627 Monitor and alert cleanup
  blog-service/2022/12-31.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/settings.md
  docs/integrations/databases/redis.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  i18n/ja/alerts/alerts/monitors/index.md
  static/img/alerts/alert-list-page-bell-border.png
  static/img/alerts/monitors/Add-monitors-page.png
  static/img/alerts/monitors/disable-monitor.png
  static/img/alerts/monitors/edit-monitor.png
  static/img/alerts/monitors/filter-monitors.png
  static/img/alerts/monitors/import-monitor.png
  static/img/alerts/monitors/monitor-actions.png
  static/img/alerts/monitors/monitor-details.png
  static/img/alerts/monitors/monitors-page.png
  static/img/alerts/monitors/monitors-shortcut.png
  static/img/alerts/monitors/more-actions.png
  static/img/alerts/monitors/mute-monitor.png
  static/img/alerts/monitors/new-folder.png
  static/img/alerts/monitors/new-monitor.png
  static/img/alerts/monitors/search-alert-list.png
  static/img/alerts/monitors/search-monitors-input.png
  static/img/alerts/monitors/search-monitors.png
Labels: cla-signed

#4628 Update .clabot
  .clabot
Labels: cla-signed

#4626 Update docker-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/docker-opentelemetry.md
Labels: cla-signed

#4630 CONN-3495 Add a best practice recommendation
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/armis-api-source.md
Labels: cla-signed

#4631 Role Management API v2 (beta)
  docs/api/index.md
  docs/api/role-management-v2.md
  sidebars.ts
Labels: cla-signed

#4639 Update .clabot
  .clabot
Labels: cla-signed

#4637 Update kubernetes.md - Fixed minor typo
  docs/integrations/microsoft-azure/kubernetes.md
Labels: cla-signed

#4636 Legacy 301s and 404 fixes
  cid-redirects.json
Labels: cla-signed

#4435 "Free Trial" and "Support" nav buttons
  docusaurus.config.js
  src/css/sumo.scss
Labels: doc:site tech, cla-signed

#4640 Improvements to New UI doc and banner
  docs/get-started/sumo-logic-ui.md
  docusaurus.config.js
Labels: cla-signed

#4634 Automox C2C Source Docs
  blog-service/2024-10-14-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/automox-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/automox/example.json
  static/files/c2c/automox/example.tf
  static/img/send-data/automox-logo.png
Labels: cla-signed

#3393 DOCS-24 - RBAC for Indexes - GA
  blog-service/2023/12-31.md
  blog-service/2024-10-14-manage.md
  cid-redirects.json
  docs/manage/security/audit-indexes/audit-index-access.md
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
  docs/manage/users-roles/roles/create-manage-roles.md
  docs/manage/users-roles/roles/rbac-for-indexes.md
  static/img/users-roles/create-new-role-index-based.png
  static/img/users-roles/create-new-role.png
Labels: doc:update, cla-signed, do-not-merge

#4645 DOCS-217 - Remove "RBAC for Indexes" beta article
  cid-redirects.json
  docs/manage/users-roles/roles/rbac-for-indexes.md
Labels: doc:update, cla-signed

#4642 Nav button CSS fixes
  src/css/sumo.scss
Labels: cla-signed

#4638 App central slack arg
  docs/platform-services/automation-service/app-central/integrations/slack.md
  static/img/platform-services/automation-service/app-central/integrations/slack/slack-14.png
  static/img/platform-services/automation-service/app-central/integrations/slack/slack-15.png
Labels: cla-signed

#4646 fixed timeout error
  docs/platform-services/automation-service/app-central/integrations/cortex-xdr.md
Labels: cla-signed

#4633 Kandji C2C source doc
  blog-service/2024-10-15-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/kandji-source.md
  sidebars.ts
  static/files/c2c/kandji/example.json
  static/files/c2c/kandji/example.tf
  static/img/send-data/kandji-logo.png
Labels: cla-signed

#4652 Update .clabot
  .clabot
Labels: cla-signed

#4649 docs: update Jenkins links
  docs/observability/sdo/jenkins-plugin-build-deploy-events.md
  docs/send-data/collect-from-other-data-sources/sumo-logic-open-source-projects.md
Labels: cla-signed

#4654 changed date
  docs/platform-services/automation-service/app-central/integrations/crowdstrike-falcon.md
Labels: cla-signed

#4655 Update ms-office-audit-source.md
  docs/send-data/hosted-collectors/microsoft-source/ms-office-audit-source.md
Labels: cla-signed

#4648 MS_Sentinel
  docs/platform-services/automation-service/app-central/integrations/microsoft-sentinel.md
Labels: cla-signed

#4658 added beta version of malwarebytes oneview integration
  docs/integrations/product-list/product-list-m-z.md
  docs/platform-services/automation-service/app-central/integrations/malwarebytes-oneview.md
  static/img/platform-services/automation-service/app-central/logos/malwarebytes-oneview.png
Labels: cla-signed

#4650 DOCS-91 - Playbook payloads
  cid-redirects.json
  docs/alerts/monitors/automation-payload-variables.md
  docs/alerts/monitors/index.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  sidebars.ts
  static/img/platform-services/automation-service/alert-payload.png
  static/img/platform-services/automation-service/arrow-on-playbook-new.png
  static/img/platform-services/automation-service/automation-on-entity-in-cloud-siem.png
  static/img/platform-services/automation-service/entity-payload.png
  static/img/platform-services/automation-service/entity-playbook.png
  static/img/platform-services/automation-service/insight-automation.png
  static/img/platform-services/automation-service/insight-payload.png
  static/img/platform-services/automation-service/insight-playbook.png
  static/img/platform-services/automation-service/playbook-in-alert-1-new.png
  static/img/platform-services/automation-service/playbook-in-alert-new.png
Labels: cla-signed

#4659 DOCS-498 - Add Ubuntu version
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: doc:minor edit, cla-signed

#4661 DOCS-494 - Update invite section
  docs/manage/users-roles/users/multi-account-access.md
Labels: doc:update, cla-signed

#4660 DOCS-484 - Add Cloud SOAR incident filtering criteria
  docs/cloud-soar/incidents-triage.md
Labels: doc:update, cla-signed

#4663 Remove copilot video
  docs/search/copilot.md
Labels: cla-signed

#4657 IP restrictions Note added
  docs/send-data/collect-from-other-data-sources/azure-monitoring/ms-azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
Labels: cla-signed

#4653 Update troubleshooting.md
  docs/send-data/opentelemetry-collector/troubleshooting.md
Labels: cla-signed

#4644 Update atlassian-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/atlassian-source.md
Labels: cla-signed

#4664 Legacy 301 fixes
  cid-redirects.json
Labels: cla-signed

#4666 Add missing rules to Cloud SIEM October 4 2024 release notes
  blog-cse/2024-10-04-content.md
Labels: doc:update, cla-signed

#4667 Update automation-service-bridge.md
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: cla-signed

#4669 Initial Bedrock Document
  cid-redirects.json
  docs/integrations/amazon-aws/amazon-bedrock.md
  docs/integrations/product-list/product-list-a-l.md
  sidebars.ts
  static/img/integrations/amazon-aws/Amazon-Bedrock-CloudTrail-Audit-Overview.png
  static/img/integrations/amazon-aws/Amazon-Bedrock-Model-Invocation-Log-Analysis.png
  static/img/integrations/amazon-aws/Amazon-Bedrock-Overview.png
  static/img/integrations/amazon-aws/Amazon-Bedrock-Runtime-Performance-Monitoring.png
  static/img/integrations/amazon-aws/Amazon-Bedrock-Settings.png
  static/img/integrations/amazon-aws/amazon-bedrock-logo.png
  static/img/integrations/amazon-aws/img.png
Labels: cla-signed

#4668 Added the permission for VMWare Vsphere Automation, JAMF available in CSOAR-993
  docs/platform-services/automation-service/app-central/integrations/jamf.md
  docs/platform-services/automation-service/app-central/integrations/vmware-vsphere.md
Labels: cla-signed

#4643 DOCS-493 - Migrate Audit Logging from V1 to V2 docs
  docs/api/role-management-v2.md
  static/img/users-roles/JSON-diff-V1-V2.png
Labels: cla-signed, do-not-merge

#4594 DOCS-467 - Copilot Preview 2
  docs/search/copilot.md
  static/img/search/copilot/chart-types.png
  static/img/search/copilot/code-editor.png
  static/img/search/copilot/copilot-geo-chart.png
  static/img/search/copilot/copilot-tab-new.png
  static/img/search/copilot/explore.png
  static/img/search/copilot/feedback-error.png
  static/img/search/copilot/feedback-thumbs.png
  static/img/search/copilot/history.png
  static/img/search/copilot/manual-entry.png
  static/img/search/copilot/new-conversation.png
  static/img/search/copilot/open-in-log-search.png
  static/img/search/copilot/refine.png
  static/img/search/copilot/resume-convo-history1.png
  static/img/search/copilot/resume-convo-history2.png
  static/img/search/copilot/search-button.png
  static/img/search/copilot/show-hide-query.gif
  static/img/search/copilot/show-hide-query.png
  static/img/search/copilot/source-category.png
  static/img/search/copilot/suggestions.png
  static/img/search/copilot/time-period.png
Labels: cla-signed, do-not-merge

#4670 Copilot edits
  docs/search/copilot.md
Labels: cla-signed

#4671 Added legal/security language
  docs/search/copilot.md
Labels: cla-signed

#4602 AWS opensearch docs
  blog-service/2023/12-31.md
  cid-redirects.json
  docs/integrations/amazon-aws/amazon-opensearch-service.md
  docs/integrations/amazon-aws/amazon-opensearch.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/product-list/product-list-a-l.md
  sidebars.ts
Labels: cla-signed

#4672 Enabled Bedrock page link
  docs/integrations/amazon-aws/amazon-bedrock.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/product-list/product-list-a-l.md
  sidebars.ts
Labels: cla-signed

#4647 Atlassian app doc
  blog-service/2024-10-17-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/atlassian.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
  static/img/integrations/saas-cloud/atlassian-jira-confluence-and-bitbucket.png
  static/img/integrations/saas-cloud/atlassian-overview.png
  static/img/integrations/saas-cloud/atlassian-user-activity.png
Labels: cla-signed

#4209 DOCS-107 - CIS for AWS CloudQuery - onboarding improvements
  blog-service/2024-05-13-apps.md
  blog-service/2024-10-21-apps.md
  cid-redirects.json
  docs/security/cloud-infrastructure-security/cloud-infrastructure-security-for-aws.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-azure-plugin-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-gcp-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/cloudquery-azure-plugin/example.json
  static/files/c2c/cloudquery-gcp/example.json
  static/files/c2c/cloudquery-gcp/example.tf
  static/files/c2c/cloudquery/accountExample.json
  static/files/c2c/cloudquery/accountExample.tf
  static/files/c2c/cloudquery/orgExample.json
  static/files/c2c/cloudquery/orgExample.tf
  static/img/integrations/amazon-aws/cis-for-aws-cloudtrail-multi-regions.png
  static/img/integrations/amazon-aws/cis-for-aws-guardduty-multi-regions.png
  static/img/integrations/amazon-aws/cis-for-aws-infrastructure-overview.png
  static/img/integrations/amazon-aws/cis-for-aws-install-0.png
  static/img/integrations/amazon-aws/cis-for-aws-install-0a.png
  static/img/integrations/amazon-aws/cis-for-aws-install-0b.png
  static/img/integrations/amazon-aws/cis-for-aws-install-1.png
  static/img/integrations/amazon-aws/cis-for-aws-install-step-1.png
  static/img/integrations/amazon-aws/cis-for-aws-install-step-2.png
  static/img/integrations/amazon-aws/cis-for-aws-install-step-3.png
  static/img/integrations/amazon-aws/cis-for-aws-installed.png
  static/img/integrations/amazon-aws/cis-for-aws-network-firewall-multi-regions.png
  static/img/integrations/amazon-aws/cis-for-aws-param-1.png
  static/img/integrations/amazon-aws/cis-for-aws-param-2.png
  static/img/integrations/amazon-aws/cis-for-aws-param-3.png
  static/img/integrations/amazon-aws/cis-for-aws-param-4.png
  static/img/integrations/amazon-aws/cis-for-aws-param-5.png
  static/img/integrations/amazon-aws/cis-for-aws-param-6.png
  static/img/integrations/amazon-aws/cis-for-aws-param-7.png
  static/img/integrations/amazon-aws/cis-for-aws-param-7a.png
  static/img/integrations/amazon-aws/cis-for-aws-permissions-cft.png
  static/img/integrations/amazon-aws/cis-for-aws-permissions.png
  static/img/integrations/amazon-aws/cis-for-aws-quick-create-stack.png
  static/img/integrations/amazon-aws/cis-for-aws-security-control-failures-investigation.png
  static/img/integrations/amazon-aws/cis-for-aws-security-control-failures-overview.png
  static/img/integrations/amazon-aws/cis-for-aws-security-hub-multi-regions.png
  static/img/integrations/amazon-aws/cis-for-aws-waf-multi-regions-1.png
  static/img/integrations/amazon-aws/cis-for-aws-waf-multi-regions-2.png
  static/img/integrations/amazon-aws/cis-for-aws-waf-multi-regions-3.png
  static/img/integrations/amazon-aws/cis-for-aws-waf-multi-regions.png
Labels: doc:update, cla-signed, do-not-merge

#4675 Update cloud-soar.md
  docs/alerts/webhook-connections/cloud-soar.md
Labels: cla-signed

#4673 Update search-job.md
  docs/api/search-job.md
Labels: cla-signed

#4632 FER template description updated
  docs/manage/field-extractions/fer-templates/akamai-cloud-monitor.md
  docs/manage/field-extractions/fer-templates/apache-access-logs.md
  docs/manage/field-extractions/fer-templates/apache-tomcat-access-log-fer.md
  docs/manage/field-extractions/fer-templates/apache-tomcat-access-logs.md
  docs/manage/field-extractions/fer-templates/aws-cloudtrail-logs.md
  docs/manage/field-extractions/fer-templates/aws-elastic-load-balancing-logs.md
  docs/manage/field-extractions/fer-templates/aws-s3-usage-logs.md
  docs/manage/field-extractions/fer-templates/microsoft-iis-logs.md
  docs/manage/field-extractions/fer-templates/nginx-logs.md
  docs/manage/field-extractions/fer-templates/palo-alto-networks.md
  docs/manage/field-extractions/fer-templates/varnish-logs.md
Labels: cla-signed

#4629 Outlier-to-Anomaly log monitor setting
  blog-service/2024-10-22-monitors.md
  docs/alerts/monitors/settings.md
  static/img/alerts/monitors/convert-to-anomaly.png
  static/img/alerts/monitors/scan-estimates-anomaly.png
Labels: cla-signed

#4619 Digital Guardian Source doc
  blog-service/2024-10-21-collection.md
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/digital-guardian-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/digital-guardian/example.json
  static/files/c2c/digital-guardian/example.tf
  static/img/send-data/digital-guardian-logo.svg
Labels: cla-signed, do-not-merge

#4577 DOCS-453 - Metrics Anomaly option
  blog-service/2024-10-22-alerts.md
  docs/alerts/monitors/create-monitor.md
  static/img/alerts/monitors/create-monitor.png
  static/img/alerts/monitors/monitor-detection-methods.png
  static/img/alerts/monitors/new-monitor-window.png
  static/img/alerts/query-metrics-explorer-view.png
  static/img/alerts/threshold-metrics-explorer-view.png
  static/img/alerts/thresholdonly-metrics-explorer-view.png
Labels: cla-signed, do-not-merge

#4679 Add Digital Guardian source to product list
  docs/integrations/product-list/product-list-a-l.md
Labels: doc:minor edit, cla-signed

#4682 Fix broken screenshots in "Create a New Monitor" article
  docs/alerts/monitors/create-monitor.md
Labels: doc:minor edit, cla-signed

#4676 Added the new action List Incident Entities V2
  docs/platform-services/automation-service/app-central/integrations/microsoft-sentinel.md
Labels: cla-signed

#4681 Update vmware-vrealize-log-insight.md
  docs/send-data/collect-from-other-data-sources/vmware-vrealize-log-insight.md
Labels: cla-signed

#4665 Azure Flexible DB for MySQL Document
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  static/img/send-data/azure-database-for-mysql-error-logs.png
  static/img/send-data/azureflexible-mysqlserver-logs.png
  static/img/send-data/azureflexible-mysqlserver-metrics.png
Labels: doc:update, cla-signed

#4641 Usage management - Advanced tab information added
  blog-service/2024-10-25-manage.md
  docs/api/index.md
  docs/api/scan-budget.md
  docs/manage/manage-subscription/index.md
  docs/manage/manage-subscription/sumo-logic-flex-accounts.md
  docs/manage/manage-subscription/usage-management.md
  sidebars.ts
  static/img/manage/account/create-scan-budget.png
  static/img/manage/account/usage-management-advanced.png
  static/img/manage/account/usage-management.png
  static/img/manage/account/view-scan-budget.png
Labels: cla-signed

#4482 OpenTelemetry Remote Management V2
  docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
  static/img/send-data/incompatible-collectors.png
  static/img/send-data/learn-more-button-warning.png
  static/img/send-data/link-collectors.png
  static/img/send-data/local-file-apache.png
Labels: cla-signed

#4684 Azure web app server farm doc changes
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  static/img/integrations/microsoft-azure/Azure-App-Service-Plan-Configure-Diagnostic-Metrics.png
Labels: cla-signed

#4688 SUMO-248960 | We got to know that when collecting metrics via mongos …
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
Labels: cla-signed

#4696 Scan Budgets Release notes_Pull back
  blog-service/2024-10-25-manage.md
Labels: cla-signed, hot🔥

#4691 Update the API intro reuse file
  docs/reuse/api-intro.md
Labels: doc:minor edit, cla-signed

#4689 Zendesk App doc
  blog-service/2024-10-30-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/zendesk.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4690 LastPass app docs
  blog-service/2024-10-28-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/lastpass.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#4698 Change release note dates for LastPass and Zendesk
  blog-service/2024-10-25-apps-2.md
  blog-service/2024-10-25-apps.md
Labels: doc:minor edit, cla-signed

#4697 DOCS-206 - Deprecate Root Cause Explorer
  docs/observability/root-cause-explorer-deprecation.md
  docs/observability/root-cause-explorer.md
Labels: doc:new, cla-signed, do-not-merge

#4692 Update minute-volume.md
  docs/manage/ingestion-volume/ingest-budgets/minute-volume.md
Labels: cla-signed

#4704 Added the Priority new field in "ConnectWise Manage"
  docs/platform-services/automation-service/app-central/integrations/connectwise-manage.md
Labels: cla-signed

#4695 CrowdStrike Spotlight app docs
  blog-service/2024-10-29-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/crowdstrike-spotlight.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: cla-signed

#4703 Update aws-cloudtrail.md
  docs/integrations/cloud-security-monitoring-analytics/aws-cloudtrail.md
Labels: cla-signed

#4711 updated the docs for google chat
  docs/platform-services/automation-service/app-central/integrations/google-chat.md
  static/img/platform-services/automation-service/app-central/integrations/google-drive/google-drive-10.png
Labels: cla-signed

#4712 Scan Budgets release notes
  blog-service/2024-10-29-manage.md
Labels: cla-signed, hot🔥

#4708 updated the DOC of microsoft-sentinel &bconnectwise-manage
  docs/platform-services/automation-service/app-central/integrations/connectwise-manage.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-sentinel.md
Labels: cla-signed

#4706 DOCS-508 - Update Insight creation threshold language
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
  docs/cse/introduction-to-cloud-siem.md
  docs/cse/records-signals-entities-insights/set-insight-generation-window-threshold.md
Labels: doc:minor edit, cla-signed

#4705 DOCS-514 - Parse operators note
  docs/cse/schema/parsing-language-reference-guide.md
Labels: doc:minor edit, cla-signed

#4710 Update minute-volume.md
  docs/manage/ingestion-volume/ingest-budgets/minute-volume.md
Labels: cla-signed

#4709 Update google-bigquery-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-bigquery-source.md
Labels: cla-signed

#4717 Change release note to preview
  blog-service/2024-10-22-alerts.md
Labels: cla-signed

#4716 Release note update - Scan Budget
  blog-service/2024-10-29-manage.md
  docs/manage/manage-subscription/usage-management.md
Labels: cla-signed, hot🔥

#4699 DOCS-509 - Add workaround for OCSP
  docs/integrations/cloud-security-monitoring-analytics/palo-alto-firewall-10.md
Labels: doc:minor edit, cla-signed

#4700 DOCS-510 - Update Kubernetes script example
  docs/send-data/kubernetes/collecting-logs.md
Labels: doc:update, cla-signed

#4718 Cloud SIEM release notes for October 31 2024
  blog-cse/2024-10-31-content.md
Labels: cla-signed

#4719 Change RBAC for Indexes rollout date
  blog-service/2024-10-14-manage.md
Labels: cla-signed
