Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-11, with the labels that each got.

#4701 DOCS-513 - Root Cause Explorer deprecation release note
  blog-service/2024-11-01-observability.md
Labels: doc:new, cla-signed, do-not-merge

#4720 Legacy/301 fixes
  cid-redirects.json
Labels: cla-signed

#4721 Copilot doc edits per legal/compliance
  docs/search/copilot.md
Labels: cla-signed

#4723 DOCS-526 - Update to signal suppression doc
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
Labels: doc:minor edit, cla-signed

#4724 Update workday-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
Labels: cla-signed

#4727 DOCS-527 - Cloud SIEM Network sensor end-of-life statement
  docs/cse/sensors/network-sensor-end-of-life.md
Labels: doc:new, cla-signed, hot🔥

#4729 Metrics anomalies GA release note
  blog-service/2024-11-05-alerts.md
Labels: cla-signed, hot🔥

#4707 App Guides - October Release
  blog-service/2024-10-30-apps.md
Labels: cla-signed, do-not-merge

#4714 Azure CosmosDB for NoSQL
  docs/integrations/microsoft-azure/azure-cosmos-db.md
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Plans-CosmosDB.png
  static/img/integrations/microsoft-azure/Microsoft-Cloud-Defender-Plans-CosmosDB_resource_types.png
  static/img/integrations/microsoft-azure/azurecosmosdb-metrics.png
  static/img/integrations/microsoft-azure/cosmosdb-diagnostic-logs.png
Labels: cla-signed

#4722 Update infrequent-data-tier.md
  docs/integrations/sumo-apps/infrequent-data-tier.md
Labels: cla-signed

#4732 User added to .cla
  .clabot
Labels: cla-signed, hot🔥

#4736 DOCS-534 - Quantize caveats
  docs/alerts/monitors/create-monitor.md
  static/img/alerts/monitors/metrics-query-with-quantize.png
Labels: doc:update, cla-signed

#4737 Legacy 301 redirects
  cid-redirects.json
Labels: cla-signed

#4734 Granular Data Tracking - Removed Beta and added to the related docs
  docs/manage/ingestion-volume/data-volume-index/granular-data-tracking.md
  docs/manage/ingestion-volume/data-volume-index/index.md
Labels: cla-signed

#4686 Doc for masking for windows source template
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/mask-rules-windows.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/mask-rules.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/index.md
Labels: cla-signed, do-not-merge

#4687 updating changelog for all ST for log/metric section feature, masking…
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/changelog.md
Labels: cla-signed, do-not-merge

#4735 DOCS-525 - Access key permissions text
  docs/api/getting-started.md
  docs/manage/security/access-keys.md
Labels: doc:update, cla-signed

#4731 Removing and rearranging monitors in kafka classic app
  docs/integrations/containers-orchestration/kafka.md
Labels: cla-signed

#4741 Content Release Notes 2024-11-07
  blog-cse/2024-11-07-content.md
Labels: cla-signed

#4662 DOCS-27 - Update docs for Network Sensor end-of-life
  blog-cse/2024-11-08-application-update.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/corelight-zeek.md
  docs/cse/sensors/index.md
  docs/cse/sensors/ingest-zeek-logs.md
  docs/cse/sensors/log-sensor-troubleshooting.md
  docs/cse/sensors/network-sensor-deployment-guide.md
  docs/cse/sensors/network-sensor-end-of-life.md
  docs/cse/sensors/network-sensor-troubleshooting.md
  docs/cse/sensors/sensor-download-locations.md
  docs/reuse/cloud-siem-network-sensor-eol.md
  sidebars.ts
  static/img/cse/create-mapping.png
  static/img/cse/ingest-mappings.png
Labels: doc:update, cla-signed, do-not-merge

#4738 Kandji app docs
  blog-service/2024-11-08-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/kandji.md
  sidebars.ts
Labels: cla-signed

#4744 DOCS-540 - Update screenshot in Cloud SIEM search article
  docs/cse/records-signals-entities-insights/search-cse-records-in-sumo.md
  static/img/cse/security-partitions.png
Labels: doc:minor edit, cla-signed

#4743 Change rollout date for RBAC for Indexes to Dec 16 2024
  blog-service/2024-10-14-manage.md
Labels: doc:minor edit, cla-signed

#4501 Added new integration - Sumo Logic Automation Tools
  docs/integrations/product-list/product-list-m-z.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-automation-tools.md
Labels: cla-signed

#4726 modified doc of netskope v2
  docs/platform-services/automation-service/app-central/integrations/netskope-v2.md
  static/img/platform-services/automation-service/app-central/integrations/netskope-v2/netskope-v2-10.png
  static/img/platform-services/automation-service/app-central/integrations/netskope-v2/netskope-v2-7.png
  static/img/platform-services/automation-service/app-central/integrations/netskope-v2/netskope-v2-8.png
Labels: cla-signed

#4733 scanned_partition_count field computation change - Release notes
  blog-service/2024-11-12-search.md
Labels: cla-signed

#4749 Scan budget docs update
  docs/manage/manage-subscription/usage-management.md
Labels: cla-signed

#4751 Updated the DOC of Microsoft EWS
  docs/platform-services/automation-service/app-central/integrations/microsoft-ews.md
Labels: cla-signed

#4754 Updated the DOC of azure-ad
  docs/platform-services/automation-service/app-central/integrations/azure-ad.md
Labels: cla-signed

#4750 added resource photo
  docs/platform-services/automation-service/app-central/integrations/netskope-v2.md
  static/img/platform-services/automation-service/app-central/integrations/netskope-v2/netskope-v2-11.png
Labels: cla-signed

#4753 PLG-157 rename
  cid-redirects.json
  docs/integrations/sumo-apps/kickstart-data-astronomy.md
  sidebars.ts
  static/img/integrations/sumo-apps/Sumo-Logic-Kickstart-Data-Application-Health-Dashboard.png
  static/img/integrations/sumo-apps/Sumo-Logic-Kickstart-Data-Business-KPIs-Dashboard.png
  static/img/integrations/sumo-apps/Sumo-Logic-Kickstart-Data-Icon.png
Labels: cla-signed

#4685 Added new field for the ASN operator doc
  docs/search/search-query-language/search-operators/asn-lookup.md
Labels: cla-signed

#4612 Kickstart data onboarding
  blog-service/2024-11-13-manage.md
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
Labels: cla-signed, do-not-merge

#4755 Azure Database for PostgreSQL doc and old doc location tag fix
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
  docs/integrations/microsoft-azure/azure-cosmos-db.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/microsoft-azure/azure-database-for-postgresql.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/sql.md
  docs/integrations/microsoft-azure/web-apps.md
  static/img/send-data/azureflexible-postgresqlserver-logs.png
  static/img/send-data/azureflexible-postgresqlserver-metrics.png
Labels: cla-signed

#4759 Added user to the chat bot
  .clabot
Labels: cla-signed

#4762 Remove caution admonition uses
  docs/cse/sensors/ingest-zeek-logs.md
  docs/cse/sensors/log-sensor-troubleshooting.md
  docs/cse/sensors/network-sensor-deployment-guide.md
  docs/cse/sensors/network-sensor-troubleshooting.md
  docs/cse/sensors/sensor-download-locations.md
Labels: cla-signed

#4757 DOCS-546 - Cloud SOAR release note for a new beta version of the Automation Bridge
  blog-csoar/2024-11-15-application-update.md
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: doc:new, cla-signed

#4766 404 fixes
  cid-redirects.json
  docs/integrations/sumo-apps/kickstart-data.md
Labels: cla-signed

#4765 DOCS-30 - Remove signal forwarding deprecation article
  blog-cse/2023/12-31.md
  docs/cse/records-signals-entities-insights/signal-index-migration-faq.md
Labels: doc:update, cla-signed

#4747 DOCS-386 - Add Cloud SOAR courses to doc
  docs/cloud-soar/index.md
  docs/cloud-soar/introduction.md
  sidebars.ts
  static/img/cloud-soar/add-investigator-example.png
  static/img/cloud-soar/add-playbook-example.png
  static/img/cloud-soar/app-central-integrations-tab.png
  static/img/cloud-soar/cloud-soar-automation-menu.png
  static/img/cloud-soar/cloud-soar-example-ui.png
  static/img/cloud-soar/column-configuration-icon.png
  static/img/cloud-soar/dashboards-page.png
  static/img/cloud-soar/entities-page.png
  static/img/cloud-soar/entities-tab-example.png
  static/img/cloud-soar/example-edit-resource.png
  static/img/cloud-soar/example-integration-resource.png
  static/img/cloud-soar/example-playbook.png
  static/img/cloud-soar/example-report-dialog.png
  static/img/cloud-soar/grab-event.png
  static/img/cloud-soar/incident-example.png
  static/img/cloud-soar/incident-response-cycle.png
  static/img/cloud-soar/incident-response-process.png
  static/img/cloud-soar/incidents-page.png
  static/img/cloud-soar/playbook-node-examples.png
  static/img/cloud-soar/playbook-nodes-example.png
  static/img/cloud-soar/run-playbook-example.png
  static/img/cloud-soar/secops-page.png
  static/img/cloud-soar/sidebar-example.png
  static/img/cloud-soar/war-room-example-2.png
  static/img/cloud-soar/war-room-example.png
Labels: doc:new, cla-signed

#4772 Fix typo in Cloud SOAR intro
  docs/cloud-soar/introduction.md
Labels: doc:minor edit, cla-signed

#4752 Updates in Mongodb atlas, Tracing and fedramp docs
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/traces/tracing-dashboards.md
  docs/integrations/databases/mongodb-atlas.md
  docs/manage/manage-subscription/fedramp-capabilities.md
  static/img/integrations/databases/mongodbatlas/changecluster.png
  static/img/integrations/databases/mongodbatlas/createapikey.png
  static/img/integrations/databases/mongodbatlas/invitetoproject.png
  static/img/integrations/databases/mongodbatlas/updatemetricslogs.png
Labels: cla-signed

#4771 CONN-1726 Creating smartsheet documentation
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/smartsheet-source.md
  sidebars.ts
  static/files/c2c/smartsheet/example.json
  static/files/c2c/smartsheet/example.tf
  static/img/send-data/smartsheet.png
Labels: doc:new, cla-signed

#4777 GitHub issue #3681
  docs/observability/reliability-management-slo/index.md
Labels: doc:minor edit, cla-signed

#4768 November 20, 2024 - Content Release
  blog-csoar/2024-11-20-content.md
Labels: cla-signed, do-not-merge

#4781 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#4779 Kickstart Data nomenclature fix
  docs/get-started/sign-up.md
Labels: cla-signed

#4776 Trend Micro C2C docs
  blog-service/2024-11-22-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/trend-micro-source.md
  sidebars.ts
  static/files/c2c/trend-micro/example.json
  static/files/c2c/trend-micro/example.tf
  static/img/send-data/trend-micro-logo.png
Labels: cla-signed, do-not-merge

#4786 GitHub issue #1984
  docs/search/lookup-tables/create-lookup-table.md
  docs/search/search-query-language/search-operators/lookup.md
  docs/search/search-query-language/search-operators/lookupcontains.md
  static/img/search/lookup-tables/search-for-lookups.png
Labels: doc:update

#4787 GitHub issue #3294
  docs/alerts/monitors/create-monitor.md
Labels: doc:update

#4774 Update asn-lookup.md
  docs/search/search-query-language/search-operators/asn-lookup.md
Labels: cla-signed

#4782 Updated docs for cloudTrail dashboard
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/network-load-balancer.md
  static/img/integrations/amazon-aws/AWS-Application-Load-Balancer-CloudTrail-Audit.png
  static/img/integrations/amazon-aws/AWS-Classic-Load-Balancer-CloudTrail-Audit.png
  static/img/integrations/amazon-aws/AWS-Network-Load-Balancer-CloudTrail-Audit.png
Labels: cla-signed

#4764 Updated RDS doc for oracle dashboards
  docs/integrations/amazon-aws/rds.md
  static/img/integrations/amazon-aws/Amazon-RDS-CloudTrail-Audit-Events.png
  static/img/integrations/amazon-aws/Amazon-RDS-Oracle-Logs-Alert-Logs-Analysis.png
  static/img/integrations/amazon-aws/Amazon-RDS-Oracle-Logs-Audit-Logs-Analysis.png
  static/img/integrations/amazon-aws/Amazon-RDS-Oracle-Logs-Listener-Troubleshooting.png
Labels: cla-signed

#4785 DET-559 - Update Cloud SIEM audit logging
  docs/cse/administration/cse-audit-logging.md
Labels: doc:minor edit, do-not-merge

#4792 Docusaurus v3.6.3
  package.json
  yarn.lock
Labels: doc:site tech

#4797 GitHub issue #1206
  docs/alerts/monitors/settings.md
Labels: doc:new

#4775 Add userGroupDetails field to Microsoft Azure AD Inventory Source
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-azure-ad-inventory-source.md
  static/files/c2c/microsoft-azure-ad-inventory/example.json
  static/files/c2c/microsoft-azure-ad-inventory/example.tf
Labels: cla-signed, do-not-merge

#4796 Collector 19.516-1 Release Notes
  blog-collector/2024-11-26.md
Labels: cla-signed

#4807 Update flex.md
  docs/integrations/sumo-apps/flex.md
Labels: cla-signed

#4780 Mandiant Threat Intel C2C Source
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mandiant-threat-intel-source.md
  sidebars.ts
  static/files/c2c/mandiant-threat-intel/example.json
  static/files/c2c/mandiant-threat-intel/example.tf
  static/img/send-data/mandiant-threat-intel-logo.png
Labels: cla-signed

#4808 Update the AWS ECS app for more clarity
  docs/integrations/amazon-aws/elastic-container-service-container-insights-cloudwatch.md
  docs/integrations/amazon-aws/elastic-container-service.md
Labels: cla-signed

#4812 Update copilot.md
  docs/search/copilot.md
Labels: cla-signed

#4811 Update search-job.md
  docs/api/search-job.md
Labels: cla-signed

#4813 Update Copilot media
  docs/search/copilot.md
  static/img/search/copilot/feedback-error.png
  static/img/search/copilot/feedback-thumbs.png
Labels: cla-signed

#4563 DOCS-409 - Query Assist (preview 1)
  blog-service/2024-11-28-search.md
  docs/search/query-assist.md
  static/img/search/get-started-search/query-assist-preview1.gif
Labels: cla-signed, do-not-merge

#4814 Legacy 301 fixes
  cid-redirects.json
Labels: cla-signed

#4816 Getting Started updates
  docs/get-started/sign-up.md
  docs/get-started/sumo-logic-ui-classic.md
  docs/get-started/sumo-logic-ui.md
  static/img/get-started/overview-classic-ui.png
  static/img/get-started/overview-new-ui.png
Labels: cla-signed

#4815 Added cid-redirect links for the search operator docs
  cid-redirects.json
Labels: cla-signed

#4805 Doc changes Azure ASE
  docs/integrations/microsoft-azure/azure-app-service-environment.md
  static/img/send-data/Azure-App-Service-Plan-Configure-Diagnostic-Logs.png
Labels: cla-signed

#4817 Fix staging deployment by escaping Markdown in domain regex
  docs/platform-services/automation-service/app-central/integrations/imap.md
Labels: cla-signed

#4823 Added user to the chat bot
  .clabot
Labels: cla-signed

#4822 SUMO-250995: Adding Monitors information to Apache Tomcat OTEL App
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
Labels: cla-signed

#4809 Nov release - apps
  blog-service/2024-10-02-apps.md
  blog-service/2024-10-30-apps.md
  blog-service/2024-11-28-apps.md
Labels: cla-signed, do-not-merge
