Repository SumoLogic/sumologic-documentation, pull requests merged in 2024-06, with the labels that each got.

#4155 DOCS-211 - Reorganize Cloud Infrastructure Security
  blog-service/2023/12-31.md
  blog-service/2024-01-19-aws-for-cis.md
  blog-service/2024-05-13-apps.md
  cid-redirects.json
  docs/cloud-infrastructure-security/index.md
  docs/cloud-soar/index.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/cloud-security-monitoring-analytics/index.md
  docs/integrations/product-list.md
  docs/integrations/security-threat-detection/index.md
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/reuse/cis-note.md
  docs/security/additional-security-features/application-security.md
  docs/security/additional-security-features/audit-and-compliance.md
  docs/security/additional-security-features/data-lake.md
  docs/security/additional-security-features/index.md
  docs/security/additional-security-features/introduction-to-additional-security-features.md
  docs/security/additional-security-features/threat-detection-and-investigation.md
  docs/security/cloud-infrastructure-security/cloud-infrastructure-security-for-aws.md
  docs/security/cloud-infrastructure-security/index.md
  docs/security/cloud-infrastructure-security/introduction-to-cloud-infrastructure-security.md
  docs/security/index.md
  sidebars.ts
  static/img/security/cis-dashboards.png
  static/img/security/cis-for-aws-monitors.png
  static/img/security/cis-for-aws-saved-searches.png
Labels: doc:new, cla-signed

#4156 DOCS-211 - Redirects for Cloud Infrastructure Security reorganization
  cid-redirects.json
Labels: doc:update, cla-signed

#4145 V1 to V2 apps migration (release_1)
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/microsoft-azure/web-apps.md
Labels: cla-signed

#4158 Update create-custom-threat-intel-source.md
  docs/cse/administration/create-custom-threat-intel-source.md
Labels: cla-signed

#4142 DOCS-172 - Add new UI hidden instructions for Organization articles (Kanso)
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
  docs/manage/manage-subscription/manage-org-settings.md
Labels: doc:update, cla-signed

#4159 Update integrate-cse-with-taxii-feed.md
  docs/cse/integrations/integrate-cse-with-taxii-feed.md
Labels: cla-signed

#4162 CONN-3262: Updated Salesforce doc by adding troubleshooting step
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/salesforce-source.md
Labels: cla-signed

#4149 ST docs -Apache
  cid-redirects.json
  docs/reuse/apps/opentelemetry/collector-installation.md
  docs/reuse/apps/opentelemetry/data-configuration.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache.md
Labels: cla-signed, do-not-merge, hot🔥

#4163 Update overview.md
  docs/cloud-soar/overview.md
  docs/integrations/product-list.md
  docs/manage/security/audit-indexes/index.md
Labels: cla-signed

#4132 Fixes to style guide, design (sumo.scss), README.md
  LICENSE
  README.md
  docs/contributing/style-guide.md
  docusaurus.config.js
  src/components/NavLink/styles.css
  src/css/sitesearch360.scss
  src/css/sumo.scss
  src/theme/NavbarItem/styles.css
Labels: cla-signed

#4164 chore(instr): update dotnet instrumentation
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/net/index.md
Labels: cla-signed

#4160 Add second Copilot video and more cleanup
  docs/search/copilot.md
Labels: cla-signed, do-not-merge

#4166 new release note for cloud soar and automation service
  blog-csoar/2024-06-05-application-update.md
Labels: cla-signed

#4167 Update metric-quantization.md
  docs/metrics/introduction/metric-quantization.md
Labels: cla-signed

#4170 Add smosca-sumologic to cla
  .clabot
Labels: doc:minor edit, cla-signed

#4171 Fix clabot
  .clabot
Labels: doc:minor edit

#4169 June 5, 2024 - Content Release
  blog-csoar/2024-06-05-content.md
Labels: cla-signed

#4168 App central integration incident tools
  docs/platform-services/automation-service/app-central/integrations/incident-tools.md
Labels: cla-signed

#4172 Update flow-diagrams.md
  docs/search/search-query-language/transaction-analytics/flow-diagrams.md
Labels: cla-signed

#4174 Update screenshot
  docs/send-data/hosted-collectors/webhook-sources/zoom.md
  static/img/send-data/zoom-sign-in.png
Labels: doc:minor edit, cla-signed

#4180 Adding cid redirect links for metric and log filter pages for OTRM since those are r…
  cid-redirects.json
Labels: cla-signed

#4173 Fix links in Microsoft Graph Security API Source article
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
Labels: doc:minor edit, cla-signed

#4179 bulk integrations update
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-v2.md
  docs/platform-services/automation-service/app-central/integrations/greynoise.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-ews-daemon.md
  docs/platform-services/automation-service/app-central/integrations/palo-alto-networks-ngfw.md
  docs/platform-services/automation-service/app-central/integrations/palo-alto-networks-panorama-v2.md
Labels: cla-signed

#4176 Add note to Manage > Security
  docs/manage/security/index.md
Labels: cla-signed

#4178 Reorder Guide categories to align with Sumo mission-critical priorities/initiatives
  docusaurus.config.js
Labels: cla-signed

#4177 Removed "tags:" frontmatter metadata
  blog-cse/2024-01-12-content.md
  blog-cse/2024-01-30-content.md
  blog-cse/2024-02-02-content.md
  blog-cse/2024-02-13-content.md
  blog-cse/2024-02-19-application-update.md
  blog-cse/2024-02-19-content.md
  blog-cse/2024-02-23-content.md
  blog-cse/2024-03-11-content.md
  blog-cse/2024-03-21-content.md
  blog-cse/2024-03-22-application-update.md
  blog-cse/2024-03-28-content.md
  blog-cse/2024-04-05-content.md
  blog-cse/2024-04-11-application-update.md
  blog-cse/2024-05-02-content.md
  blog-cse/2024-05-15-application-update.md
  blog-cse/2024-05-15-content.md
  blog-cse/2024-05-23-content.md
  blog-cse/2024-05-30-application-update.md
  blog-cse/2024-05-30-content.md
  blog-csoar/2024-01-03-application-update.md
  blog-csoar/2024-01-30-application-update.md
  blog-csoar/2024-02-19-application-update.md
  blog-csoar/2024-03-12-application-update.md
  blog-csoar/2024-03-26-application-update.md
  blog-csoar/2024-04-09-application-update.md
  blog-csoar/2024-04-23-application-update.md
  blog-csoar/2024-06-05-application-update.md
  docs/alerts/index.md
  docs/alerts/monitors/index.md
  docs/apm/index.md
  docs/apm/real-user-monitoring/index.md
  docs/apm/traces/index.md
  docs/cloud-soar/index.md
  docs/cse/automation/index.md
  docs/cse/index.md
  docs/dashboards/dashboards-migration/index.md
  docs/dashboards/index.md
  docs/get-started/index.md
  docs/get-started/quickstart.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/index.md
  docs/manage/security/index.md
  docs/metrics/index.md
  docs/metrics/logs-to-metrics.md
  docs/observability/aws/index.md
  docs/observability/index.md
  docs/observability/reliability-management-slo/index.md
  docs/platform-services/index.md
  docs/search/index.md
  docs/send-data/hosted-collectors/index.md
  docs/send-data/index.md
  docs/send-data/installed-collectors/index.md
  docs/send-data/kubernetes/index.md
  docs/send-data/reference-information/time-reference.md
  static/robots.txt
Labels: cla-signed

#4140 Flex Pricing files cleanup
  blog-service/2024-03-20-flex.md
  cid-redirects.json
  docs/get-started/sumo-logic-ui.md
  docs/manage/partitions/data-tiers/create-edit-partition.md
  docs/manage/partitions/data-tiers/faq.md
  docs/manage/partitions/data-tiers/index.md
  docs/manage/partitions/flex/create-edit-partition-flex.md
  docs/manage/partitions/flex/faq.md
  docs/manage/partitions/flex/index.md
  sidebars.ts
Labels: cla-signed

#4183 Update deprecation.md
  docs/alerts/scheduled-searches/deprecation.md
Labels: cla-signed

#4141 DOCS-215 - Add "Disallow weak passwords" option
  blog-service/2024-06-06-manage.md
  docs/manage/security/set-password-policy.md
  static/img/security/Set_Passwod_Policy.png
Labels: doc:new, cla-signed, do-not-merge

#4184 DOCS-260 - Fix step in the Azure Event Hubs Source article
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
Labels: doc:minor edit, cla-signed

#4144 Dashboard scan estimates
  docs/manage/partitions/flex/estimate-scan-data.md
  static/img/partitions-data-tiers/flex-pricing/scan-estimates-dashboard-creation.png
  static/img/partitions-data-tiers/flex-pricing/scan-estimates-dashboards.png
Labels: cla-signed

#4181 Update Install apps docs page
  cid-redirects.json
  docs/get-started/apps-integrations.md
  docs/get-started/onboarding-checklists.md
  docs/integrations/product-list.md
  docs/integrations/sumo-apps/audit.md
  docs/integrations/sumo-apps/enterprise-audit.md
  docs/integrations/sumo-apps/enterprise-search-audit.md
  docs/integrations/sumo-apps/index.md
  docs/integrations/sumo-apps/infrequent-data-tier.md
  docs/integrations/sumo-apps/log-analysis-quickstart.md
  docs/manage/manage-subscription/cloud-flex-legacy-accounts.md
  sidebars.ts
Labels: cla-signed

#4186 CONN-3248: removed siem-forward code
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
Labels: cla-signed

#4189 CONN-3282: remove SIEM forward from doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-fdr-source.md
  static/files/c2c/crowdstrike-fdr/example.json
  static/files/c2c/crowdstrike-fdr/example.tf
Labels: cla-signed

#4187 DOCS-264 - Create redirect for data tiers faq
  cid-redirects.json
  docs/send-data/collect-from-other-data-sources/azure-monitoring/ms-azure-event-hubs-source.md
Labels: doc:minor edit, cla-signed

#4165 Jamf C2C doc (Beta)
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
  static/files/c2c/jamf/example.json
  static/files/c2c/jamf/example.tf
  static/img/send-data/jamf.png
Labels: cla-signed, do-not-merge

#4194 DOCS-266 - Change release note date
  blog-service/2024-06-10-manage.md
Labels: doc:minor edit, cla-signed

#4198 DOCS-266 - Redirect for release note
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#4192 Add Nate Ledet to cla
  .clabot
Labels: doc:minor edit, cla-signed

#4191 Fixed error in c2c/slack-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/slack-source.md
Labels: cla-signed

#4188 DOCS-265 - Fix for F5 BIG-IP
  docs/integrations/security-threat-detection/f5-big-ip-ltm.md
Labels: doc:update, cla-signed

#4201 Update .clabot
  .clabot
Labels: cla-signed

#3979 SUMO-236061: Azure Append Blob Collection
  blog-service/2018/12-31.md
  blog-service/2019/12-31.md
  blog-service/2023/12-31.md
  blog-service/2024-02-09-apps.md
  blog-service/2024-06-12-collection.md
  cid-redirects.json
  docs/integrations/microsoft-azure/arm-integration-faq.md
  docs/integrations/microsoft-azure/network-watcher.md
  docs/integrations/product-list.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/append-blob/collect-logs.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/append-blob/index.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/block-blob/collect-logs.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/block-blob/index.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/index.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/troubleshoot-log-collection.md
  docs/send-data/collect-from-other-data-sources/index.md
  sidebars.ts
  static/img/send-data/Azure-Sumo-pipeline-Sumologic.png
  static/img/send-data/AzureBlob_CreatEventSubscription_dialog.png
  static/img/send-data/BlockBlobReader.png
  static/img/send-data/appendblob/AppendBlobReader.png
  static/img/send-data/appendblob/appendblob-arm.png
  static/img/send-data/appendblob/appendblob-notification.png
  static/img/send-data/appendblob/appendblob-resources.png
  static/img/send-data/appendblob/appendblob-reuse-sa.png
  static/img/send-data/appendblob/appendblob-rg.png
  static/img/send-data/appendblob/azureappendblob-outbound.png
Labels: cla-signed, do-not-merge

#4203 App centeral http tools
  docs/platform-services/automation-service/app-central/integrations/http-tools.md
  static/img/platform-services/automation-service/app-central/integrations/http-tools/http-tools-4.png
Labels: cla-signed

#4200 Update Access Key link in prisma-cloud integration with SumoLogic.md
  docs/platform-services/automation-service/app-central/integrations/prisma-cloud.md
Labels: cla-signed

#4205 Update restricted-operators-dashboards.md
  docs/dashboards/restricted-operators-dashboards.md
Labels: cla-signed

#4206 DOCS-272 - Update "Modify a Chart" article
  docs/dashboards/panels/modify-chart.md
  static/img/dashboards-new/panels/modify-chart/data-label-font-size.png
Labels: doc:new, cla-signed

#4202 Update eks-control-plane.md
  docs/integrations/amazon-aws/eks-control-plane.md
Labels: cla-signed

#4195 upgrade the app reuse file update
  docs/reuse/apps/app-update.md
Labels: cla-signed

#4208 Formatting/regex fixes in ZPA and ZIA apps
  docs/integrations/security-threat-detection/zscaler-internet-access.md
  docs/integrations/security-threat-detection/zscaler-private-access.md
Labels: cla-signed

#4211 Update create-custom-threat-intel-source.md
  docs/cse/administration/create-custom-threat-intel-source.md
Labels: cla-signed

#4213 Update .clabot
  .clabot
Labels: cla-signed

#4210 Update screenshot for Metrics DPM beta
  docs/metrics/metrics-dpm.md
  static/img/metrics/metrics-dpm.png
Labels: doc:update, cla-signed

#4196 New Environment Variables Added to Lambda Function
  blog-service/2024-06-17-collection.md
  docs/send-data/collect-from-other-data-sources/collect-aws-lambda-logs-extension.md
  static/img/send-data/AddLambdaEnvironmentVariableStep3.png
  static/img/send-data/AddLambdaRolestep2.png
  static/img/send-data/KMSKeycreationstep1.png
Labels: doc:update, cla-signed, hot🔥

#4214 Update deprecation.md
  docs/alerts/scheduled-searches/deprecation.md
Labels: cla-signed

#3642 New 404
  src/helper/google-analytics.js
  src/helper/google-tag-manager.js
Labels: doc:site tech, cla-signed, do-not-merge

#4223 Moved Copilot edits from #3793
  docs/search/copilot.md
Labels: cla-signed

#4224 Copilot edit - adds /img/search/copilot/copilot-periods.gif
  static/img/search/copilot/copilot-periods.gif
Labels: cla-signed

#4220 Jamf release notes
  blog-service/2024-06-20-collections.md
  docs/integrations/product-list.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
  sidebars.ts
  static/files/c2c/jamf/example.json
  static/files/c2c/jamf/example.tf
Labels: cla-signed

#4185 Update haproxy.md
  docs/integrations/web-servers/haproxy.md
Labels: cla-signed

#4225 404 fixes
  cid-redirects.json
Labels: cla-signed

#4218 DOCS-282 - Add Cloud SIEM example for Copilot
  docs/search/copilot.md
  static/img/search/copilot/copilot-cloud-siem-1.png
  static/img/search/copilot/copilot-cloud-siem-2.png
  static/img/search/copilot/copilot-cloud-siem-3.png
  static/img/search/copilot/copilot-cloud-siem-4.png
Labels: doc:new, cla-signed

#4232 Update .clabot
  .clabot
Labels: cla-signed

#4231 Update set-up-saml.md
  docs/manage/security/saml/set-up-saml.md
Labels: cla-signed

#4233 App Central Integrations:
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-v2.md
  docs/platform-services/automation-service/app-central/integrations/virustotal.md
Labels: cla-signed

#4234 Update cloudquery-azure-plugin-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-azure-plugin-source.md
Labels: cla-signed

#4236 Azure collection updates and release notes
  blog-service/2024-06-21-apps.md
  blog-service/2024-06-21-collection.md
  docs/integrations/partner-ecosystem-apps.md
  docs/integrations/product-list.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/block-blob/collect-logs.md
  static/img/integrations/misc/endace-logo.png
  static/img/send-data/Azure_Blob_Storage_Custom_Deployment.png
Labels: cla-signed

#4216 Ingest Budgets v2 release notes
  blog-service/2024-06-24-manage.md
Labels: cla-signed

#4222 [DOCS-163] Windows AD Directory doc: Add code example snippets showing attributes
  docs/send-data/installed-collectors/sources/collect-forwarded-events-windows-event-collector.md
  docs/send-data/installed-collectors/sources/local-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/local-windows-performance-monitor-log-source.md
  docs/send-data/installed-collectors/sources/remote-file-source/index.md
  docs/send-data/installed-collectors/sources/remote-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/script-source/index.md
  docs/send-data/installed-collectors/sources/windows-active-directory-inventory-source.md
Labels: cla-signed

#4241 SUMO-240788 Update Privatelink beta page with ot collector information
  docs/integrations/amazon-aws/aws-privatelink.md
Labels: cla-signed

#4238 Improve site performance and accessibility
  README.md
  docusaurus.config.js
  package.json
  src/pages/index.tsx
  src/theme/Footer/index.tsx
  static/img/hero-secondary-background.png
  static/img/hero-secondary-background.webp
  static/img/hero-secondary-graphic.png
  static/img/hero-secondary-graphic.webp
  static/robots.txt
  yarn.lock
Labels: cla-signed

#4242 GitHub Actions and React footer improvements
  .github/workflows/build_and_deploy.yml
  .github/workflows/pr.yml
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source.md
  docs/send-data/reference-information/time-reference.md
  src/theme/Footer/index.tsx
Labels: cla-signed

#4247 Update existing-collectors-and-sources.md
  docs/send-data/use-json-configure-sources/local-configuration-file-management/existing-collectors-and-sources.md
Labels: cla-signed

#4227 Symantec Endpoint Security C2C doc
  cid-redirects.json
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/symantec-endpoint-security-source.md
  static/files/c2c/symantec-endpoint-security/example.json
  static/files/c2c/symantec-endpoint-security/example.tf
Labels: cla-signed

#4245 Update base64decode.md
  docs/search/search-query-language/search-operators/base64decode.md
Labels: cla-signed

#4252 App central IBM X force exchange
  docs/platform-services/automation-service/app-central/integrations/ibm-x-force-exchange.md
Labels: cla-signed

#4248 Update windows.md
  docs/send-data/installed-collectors/windows.md
Labels: cla-signed

#4244 Deprecate 5 old app docs
  blog-service/2017/12-31.md
  blog-service/2018/12-31.md
  cid-redirects.json
  docs/integrations/amazon-aws/aurora-mysql-ulm.md
  docs/integrations/amazon-aws/aurora-postgresql-ulm.md
  docs/integrations/amazon-aws/elastic-load-balancer-app.md
  docs/integrations/amazon-aws/elastic-load-balancing-classic.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/containers-orchestration/kubernetes-control-plane.md
  docs/integrations/product-list.md
  sidebars.ts
Labels: cla-signed

#4251 App central url scan.io
  docs/platform-services/automation-service/app-central/integrations/urlscan.io.md
Labels: cla-signed

#4253 Update index.md
  docs/manage/ingestion-volume/ingest-budgets/daily-volume/index.md
Labels: cla-signed

#4243 Syslog ST doc and masking doc
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/index.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/mask-rules.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog.md
Labels: cla-signed

#4255 Jamf C2C doc revert to beta
  blog-service/2024-06-20-collections.md
  docs/integrations/product-list.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
  sidebars.ts
Labels: cla-signed, hot🔥

#4254 App centeral gmail
  docs/platform-services/automation-service/app-central/integrations/gmail.md
Labels: cla-signed

#4239 App central incident tool integration
  docs/platform-services/automation-service/app-central/integrations/incident-tools.md
Labels: cla-signed

#4230 CONN-3331 Update Source Page Title
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/config-based-source.md
Labels: cla-signed

#4240 describe new yaml field show_modal to skip textual input
  docs/cloud-soar/cloud-soar-integration-framework.md
Labels: cla-signed

#3793 DOCS-20 - AI/ML Hub Page
  docs/get-started/ai-machine-learning.md
  docs/search/copilot.md
  sidebars.ts
  static/img/get-started/ai-diagram.png
Labels: cla-signed, do-not-merge

#4128 K8s feature: How to send logs to multiple locations using Sumo Logic Helm Chart Collection
  docs/send-data/kubernetes/collecting-logs.md
Labels: cla-signed, do-not-merge

#4258 Added user to .clabot
  .clabot
Labels: cla-signed

#4235 DOCS-291 - Update new UI hidden instructions for Kanso Beta 2.0
  docs/alerts/monitors/alert-grouping.md
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/muting-schedules.md
  docs/alerts/monitors/settings.md
  docs/alerts/webhook-connections/servicenow/index.md
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/real-user-monitoring/index.md
  docs/apm/traces/quickstart.md
  docs/apm/traces/services-list-map.md
  docs/apm/traces/spans.md
  docs/apm/traces/tracing-dashboards.md
  docs/apm/traces/view-and-investigate-traces.md
  docs/cloud-soar/overview.md
  docs/cse/introduction-to-cloud-siem.md
  docs/dashboards/explore-view.md
  docs/get-started/quickstart.md
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/containers-orchestration/rabbitmq.md
  docs/integrations/databases/cassandra.md
  docs/integrations/databases/elasticsearch.md
  docs/integrations/databases/oracle.md
  docs/integrations/index.md
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/squid-proxy.md
  docs/integrations/web-servers/varnish.md
  docs/manage/health-events.md
  docs/metrics/introduction/index.md
  docs/metrics/metrics-queries/metrics-explorer.md
  docs/observability/application-components.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/other-configurations-tools/add-new-aws-service.md
  docs/observability/kubernetes/monitoring.md
  docs/observability/kubernetes/troubleshoot-with-explore.md
  docs/observability/reliability-management-slo/create-slo.md
  docs/observability/reliability-management-slo/dashboards.md
  docs/observability/reliability-management-slo/index.md
  i18n/ja/alerts/alerts/monitors/alert-response.md
Labels: doc:update, cla-signed, do-not-merge

#4221 DOCS-283 - Update tour new UI article for Kanso Beta 2.0
  docs/get-started/sumo-logic-ui-new.md
  static/img/get-started/acct-pref.png
  static/img/get-started/admin-config.png
  static/img/get-started/admin.png
  static/img/get-started/config.png
  static/img/get-started/dashboard-searches.png
  static/img/get-started/favs.png
  static/img/get-started/hamburger.gif
  static/img/get-started/library-content-admin.gif
  static/img/get-started/library-search.png
  static/img/get-started/library.png
  static/img/get-started/recent.png
  static/img/get-started/return-to-classic.png
Labels: doc:update, cla-signed, do-not-merge

#3058 DOCS-26 - Metrics DPM - GA
  blog-service/2024-06-28-metrics.md
  docs/metrics/index.md
  docs/metrics/metrics-dpm.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#4259 Broken/legacy link fixes
  cid-redirects.json
Labels: cla-signed
