Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-07, with the labels that each got.

#5446 Update Azure SQL with Azure metrics source compatibility
  docs/integrations/microsoft-azure/sql.md
Labels: doc:update, cla-signed, do-not-merge

#5536 Update June Release note (apps)
  blog-service/2025-06-30-apps.md
Labels: doc:minor edit, cla-signed

#5539 DOCS-970 - Fix typo in threatip article
  docs/search/search-query-language/search-operators/threatip.md
  docs/security/threat-intelligence/find-threats.md
Labels: doc:minor edit, cla-signed

#5540 DOCS-973 - Add section for testing actions
  docs/platform-services/automation-service/app-central/integrations/cyberint.md
  docs/platform-services/automation-service/automation-service-integrations.md
  static/img/platform-services/automation-service/example-action-for-test-action.png
  static/img/platform-services/automation-service/example-test-action.png
  static/img/platform-services/automation-service/test-action-required-fields.png
  static/img/platform-services/automation-service/test-action-results.png
Labels: doc:new, cla-signed

#5531 Update docusaurus.config.js
  docusaurus.config.js
Labels: cla-signed

#5541 DOCS-954 - Edit output of an action
  docs/platform-services/automation-service/automation-service-integrations.md
  docs/platform-services/automation-service/integration-framework/integration-framework-output.md
  static/img/platform-services/automation-service/action-output-edit-action.png
  static/img/platform-services/automation-service/action-output-edit-button.png
  static/img/platform-services/automation-service/action-output-edited-results.png
  static/img/platform-services/automation-service/action-output-edited.png
  static/img/platform-services/automation-service/action-output-example-action.png
  static/img/platform-services/automation-service/action-output-json-details.png
  static/img/platform-services/automation-service/action-output-test-action-json-details.png
  static/img/platform-services/automation-service/action-output-test-action-results.png
  static/img/platform-services/automation-service/action-output-test-action.png
Labels: cla-signed

#5542 DOCS-975 - Reorg the Cloud SOAR overview
  docs/cloud-soar/automation.md
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/index.md
  docs/cloud-soar/introduction.md
  docs/cloud-soar/legacy/legacy-cloud-soar-mssp.md
  docs/cloud-soar/menus.md
  docs/cloud-soar/overview.md
  docs/cloud-soar/settings.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/platform-services/automation-service/automation-service-audit-logging.md
  docs/platform-services/automation-service/automation-service-integrations.md
  sidebars.ts
Labels: doc:update, cla-signed

#5550 Update universal-connector-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/universal-connector-source.md
Labels: cla-signed

#5547 Version 19.525-44 (Installed Collector) - Release notes
  blog-collector/2025-07-4-installed.md
Labels: cla-signed

#5548 Update create-edit-partition-flex.md
  docs/manage/partitions/flex/create-edit-partition-flex.md
Labels: cla-signed

#5553 Update namespaces
  docs/integrations/microsoft-azure/azure-cosmos-db-for-postgresql.md
  docs/integrations/microsoft-azure/azure-database-for-postgresql.md
  docs/integrations/microsoft-azure/kubernetes.md
  docs/integrations/microsoft-azure/sql.md
  docs/integrations/microsoft-azure/web-apps.md
Labels: cla-signed

#5545 CSOAR-3521: Updated doc for SIEM Internal integration
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem-internal.md
Labels: cla-signed

#5544 CSOAR-3536: Cloudflare integration issue
  docs/platform-services/automation-service/app-central/integrations/cloudflare.md
Labels: cla-signed

#5555 DOCS-981 - Notification about TAXII 2
  docs/security/threat-intelligence/notice-about-taxii2.md
Labels: doc:new, cla-signed, hot🔥

#5561 DOCS-981 - Update TAXII 2 notice to latest version
  docs/security/threat-intelligence/notice-about-taxii2.md
Labels: doc:update, cla-signed, hot🔥

#5562 DOCS-981 - Change title
  docs/security/threat-intelligence/notice-about-taxii2.md
Labels: doc:update, cla-signed, hot🔥

#5565 Black Hat USA 2025 banner
  docusaurus.config.js
Labels: cla-signed

#5564 DOCS-825 - Out-of-the-box playbooks
  docs/platform-services/automation-service/app-central/index.md
  docs/platform-services/automation-service/automation-service-app-central.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/platform-services/automation-service/playbooks-in-app-central.md
  docs/reuse/automation-service/sample-playbooks.md
  sidebars.ts
Labels: doc:new, cla-signed

#5573 DOCS-986 - Remove "Event Analytics" beta article
  cid-redirects.json
  docs/search/get-started-with-search/search-page/event-analytics.md
Labels: doc:update, cla-signed

#5569 SUMO-255318 : added troubleshooting details for Azure Virtual Network app
  docs/integrations/microsoft-azure/azure-virtual-network.md
Labels: cla-signed

#5552 Source template feature for Timestamp parsing
  docs/reuse/apps/opentelemetry/logs-advance-option-otel.md
  docs/reuse/apps/opentelemetry/timestamp-parsing.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/elasticsearch/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mysql/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/otrm-time-reference.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/postgresql/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/index.md
  docs/send-data/reference-information/time-reference.md
  sidebars.ts
  static/img/send-data/source-template-edit.png
  static/img/send-data/st-timestamp-parsing.png
Labels: cla-signed

#5570 SUMO-264517: Otel App: Upgrade Tier 2 Apps to Tier 1 - Oracle
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
Labels: cla-signed

#5576 Information about the TLS version added/updated
  docs/send-data/hosted-collectors/amazon-aws/index.md
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
Labels: cla-signed

#5581 DOCS-998 - Remove beta label from "App Management APIs" article
  docs/api/app-management.md
Labels: doc:minor edit, cla-signed

#5584 DOCS-62 - Fix sidebar chevron direction (UX)
  src/css/sumo.scss
Labels: cla-signed

#5577 Google Cloud Security Command Center (Apps)
  blog-service/2025-07-14-apps.md
  cid-redirects.json
  docs/integrations/google/cloud-security-command-center.md
  docs/integrations/google/index.md
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zimperium-mtd-source.md
  sidebars.ts
  static/img/integrations/google/google-cloud-security-command-center.png
Labels: doc:new, cla-signed, do-not-merge

#5588 DOCS-1000 - Default Starting Page preference
  blog-service/2025-07-14-get-started.md
  docs/get-started/account-settings-preferences.md
  static/img/get-started/my-preferences.png
Labels: doc:new, cla-signed

#5589 DOCS-998 - Remove beta label from App Management API article
  docs/api/app-management.md
Labels: doc:minor edit, cla-signed

#5549 DOCS-978 - Docs site domain move redirect banner
  docusaurus.config.js
Labels: cla-signed, do-not-merge

#5587 Microsoft Defender for Endpoint app doc
  blog-service/2025-07-16-apps.md
  cid-redirects.json
  docs/integrations/microsoft-azure/index.md
  docs/integrations/microsoft-azure/microsoft-defender-for-endpoint.md
  docs/integrations/product-list/product-list-a-l.md
Labels: cla-signed, do-not-merge

#5594 Traces are not available on FED and as of today we cannot enable on demand for customers.
  docs/manage/manage-subscription/fedramp-capabilities.md
Labels: cla-signed

#5598 Remove duplicate H1 in google-workspace-apps-audit-source
  docs/send-data/hosted-collectors/google-source/google-workspace-apps-audit-source.md
Labels: cla-signed

#5597 Add 301 legacy and 404 fixes
  cid-redirects.json
Labels: cla-signed

#5599 DOCS-235- Remove text from release note
  blog-cse/2025-06-02-application.md
Labels: doc:minor edit, cla-signed

#5600 Remove section from "Create a Match List" article
  docs/cse/match-lists-suppressed-lists/create-match-list.md
Labels: doc:update, cla-signed

#5593 Updated sentry app
  docs/integrations/webhooks/sentry.md
  static/img/integrations/webhooks/Sentry-Permission.png
  static/img/integrations/webhooks/Sentry-Webhooks.png
Labels: cla-signed

#5603 Updated app with monitor
  docs/integrations/amazon-aws/amazon-bedrock.md
  docs/integrations/amazon-aws/amazon-ec2-auto-scaling.md
  docs/integrations/amazon-aws/amazon-elastic-block-store.md
  docs/integrations/amazon-aws/amazon-opensearch.md
  docs/integrations/saas-cloud/confluent-cloud.md
  docs/integrations/webhooks/sentry.md
Labels: cla-signed

#5609 CSOAR-3597: Inconsistent "http_url" Encoding Between Manual and Insight Execution of playbook
  docs/platform-services/automation-service/app-central/integrations/virustotal-v3.md
Labels: cla-signed

#5613 Update Keyboard Shortcuts doc
  docs/get-started/keyboard-shortcuts.md
Labels: cla-signed

#5616 Update microsoft-graph-security-api-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/microsoft-graph-security-api-source.md
Labels: cla-signed

#5619 Update Azure docs with monitors
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
  docs/integrations/microsoft-azure/azure-container-instances.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/microsoft-azure/azure-database-for-postgresql.md
  docs/integrations/microsoft-azure/azure-event-grid.md
  docs/integrations/microsoft-azure/azure-key-vault.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/azure-virtual-network.md
  docs/integrations/microsoft-azure/kubernetes.md
Labels: doc:update, doc:minor edit, cla-signed, do-not-merge

#5614 Update parsedate.md
  docs/search/search-query-language/parse-operators/parsedate.md
Labels: cla-signed

#5622 Minor update on indentation
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
Labels: doc:minor edit, cla-signed

#5625 Update Configuration part for AWS security apps
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-guardduty.md
  docs/integrations/amazon-aws/guardduty.md
  docs/integrations/amazon-aws/inspector.md
  docs/integrations/amazon-aws/security-hub.md
Labels: doc:update, cla-signed, do-not-merge

#5633 TLAB-2169 - Add aj-sumo to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#5639 DOCS-1030 - Update roles assignment in Entra ID provisioning article
  docs/manage/security/scim/provision-with-microsoft-entra-id.md
  static/img/security/provision-azure-attribute-mappings.png
  static/img/security/provision-azure-role-attribute.png
  static/img/security/roles-advanced-options.png
Labels: doc:update, cla-signed

#5637 DOCS-1033 - Remove beta label from "Restart a Collector" article
  docs/send-data/collection/restart-collectors.md
  sidebars.ts
Labels: doc:minor edit, cla-signed

#5642 Add 301 redirects
  cid-redirects.json
Labels: cla-signed

#5643 CSOAR-3443 Updated the new logo for Censys
  docs/platform-services/automation-service/app-central/integrations/censys-v2.md
  docs/platform-services/automation-service/app-central/integrations/censys.md
Labels: cla-signed

#5645 OneLogin (C2C)
  blog-service/2025-07-31-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/onelogin-source.md
  sidebars.ts
  static/files/c2c/onelogin/example.json
  static/files/c2c/onelogin/example.tf
Labels: doc:new, cla-signed, do-not-merge
