Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-09, with the labels that each got.

#5742 URL syntax updated
  docs/search/search-query-language/search-operators/geoip.md
Labels: cla-signed

#5741 Collector Version 19.525-59 - RN
  blog-collector/2025-07-04-installed.md
  blog-collector/2025-09-02-download-ic.md
  blog-collector/2025-09-02-installed.md
Labels: cla-signed

#5406 Update query-assist.md
  docs/search/query-assist.md
Labels: cla-signed

#5721 SUMO-267358 | Apoorv | Update. Azure Machine Learning Doc for new app
  docs/integrations/microsoft-azure/azure-machine-learning.md
  static/img/send-data/azure-machinelearning-logs.png
Labels: cla-signed

#5723 DOCS-1089 - Add Cloud SOAR August 2025 release notes
  blog-csoar/2025-09-04-applicaton-update.md
Labels: doc:new, cla-signed, do-not-merge

#5678 DOCS-1064 - Add note about entity name character length
  docs/cse/records-signals-entities-insights/view-manage-entities.md
Labels: doc:update, cla-signed, do-not-merge

#5747 docs: Update the nodejs and otel lambda versions
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
Labels: cla-signed

#5720 Manage Organizations for MSSPs - CSIEM
  cid-redirects.json
  docs/manage/manage-subscription/create-and-manage-orgs/index.md
  docs/manage/manage-subscription/create-and-manage-orgs/manage-orgs-for-mssps-csiem-rules.md
  docs/manage/manage-subscription/create-and-manage-orgs/manage-orgs-for-mssps.md
  sidebars.ts
  static/img/manage/subscriptions/mssp-orgs-sync-selected-items-2-csiem.png
  static/img/manage/subscriptions/mssp-orgs-sync-selected-items-2.png
  static/img/manage/subscriptions/mssp-orgs-sync-selected-items-csiem.png
  static/img/manage/subscriptions/mssp-orgs-sync-selected-items.png
Labels: cla-signed, do-not-merge

#5756 Test - Linking using relative path on GitHub README.md
  README.md
  blog-csoar/2024/12-31.md
Labels: cla-signed

#5757 Test 2 - relative link README.md
  README.md
Labels: cla-signed

#5759 Update README.md
  README.md
Labels: cla-signed

#5762 GAing Search Across Child Orgs (MSSPs)
  docs/search/search-across-child-orgs.md
  sidebars.ts
Labels: cla-signed, hot🔥

#5710 Create a Dashboard for Child Orgs (MSSPs)
  blog-service/2025-09-08-search.md
  docs/dashboards/create-dashboard-new.md
  docs/dashboards/dashboard-child-orgs.md
  docs/dashboards/index.md
  docs/search/search-across-child-orgs.md
  sidebars.ts
  static/img/dashboards/create-dashboard/select-org-for-dashboard.png
  static/img/dashboards/create-dashboard/set-as-default.png
Labels: cla-signed, do-not-merge

#5778 Mobot/Copilot multi-turn convos beta doc
  cid-redirects.json
  docs/search/mobot-multiturn-beta.md
  static/img/search/copilot/drill-causes.png
  static/img/search/copilot/initial-question.png
  static/img/search/copilot/narrow-scope-filter.png
  static/img/search/copilot/narrow-scope.png
  static/img/search/copilot/trend-over-time.png
Labels: cla-signed

#5717 DOCS-946 - Test nodes in playbooks
  blog-csoar/2025-09-10-application-update.md
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/platform-services/automation-service/playbook-test-node-condition.png
  static/img/platform-services/automation-service/playbook-test-node-info-button.png
  static/img/platform-services/automation-service/playbook-test-node-info-icon.png
  static/img/platform-services/automation-service/playbook-test-node-json-details-icon.png
  static/img/platform-services/automation-service/playbook-test-node-json-details.png
  static/img/platform-services/automation-service/playbook-test-node-table-details-icon.png
  static/img/platform-services/automation-service/playbook-test-node-task.png
  static/img/platform-services/automation-service/playbook-test-node-toggle.png
  static/img/platform-services/automation-service/playbook-test-node-user-choice.png
  static/img/platform-services/automation-service/playbook-test-node-variables.png
Labels: doc:new, cla-signed, do-not-merge

#5783 Revert "Add Kubernetes Collection Helm incompatibility warning"
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/troubleshoot-collection.md
Labels: cla-signed

#5781 Replace Activity Logs section with /reuse/ file
  docs/integrations/microsoft-azure/azure-api-management.md
  docs/integrations/microsoft-azure/azure-app-service-environment.md
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
  docs/integrations/microsoft-azure/azure-container-instances.md
  docs/integrations/microsoft-azure/azure-cosmos-db-for-postgresql.md
  docs/integrations/microsoft-azure/azure-cosmos-db.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/microsoft-azure/azure-database-for-postgresql.md
  docs/integrations/microsoft-azure/azure-event-grid.md
  docs/integrations/microsoft-azure/azure-event-hubs.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-key-vault.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-machine-learning.md
  docs/integrations/microsoft-azure/azure-service-bus.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/azure-virtual-machine.md
  docs/integrations/microsoft-azure/azure-virtual-network.md
  docs/integrations/microsoft-azure/sql.md
  docs/integrations/microsoft-azure/web-apps.md
  docs/reuse/apps/azure-activity-logs.md
Labels: cla-signed

#5784 CSOAR-3876: Added new daemon action
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-cloud.md
Labels: cla-signed

#5794 Trellix mVision ePO (apps)
  blog-service/2025-09-15-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/trellix-mvision-epo.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5797 Updated the Deletion request FAQ
  docs/manage/deletion-requests.md
Labels: cla-signed, do-not-merge

#5801 Update OneLogin app doc
  docs/integrations/saml/onelogin.md
  sidebars.ts
Labels: cla-signed

#5795 CSOAR-2639-new1: Updated the field in MS EWS Graph integration
  docs/platform-services/automation-service/app-central/integrations/microsoft-ews-graph.md
Labels: cla-signed

#5791 DOCS-1118 - Remove Mobot example queries temporarily
  docs/search/mobot-multiturn-beta.md
Labels: cla-signed

#5808 DOCS-1127 - Update Sumo Logic Notifications integration article
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications.md
Labels: doc:new, cla-signed

#5803 CSOAR-3800: Splunk integration failing on JLR
  docs/platform-services/automation-service/app-central/integrations/splunk.md
Labels: cla-signed

#5714 Apps docs formatting
  docs/integrations/saas-cloud/vectra.md
  docs/integrations/webhooks/extrahop-revealx-360.md
Labels: cla-signed

#5814 Updating the doc with compatible jenkins version to use the sumologic…
  docs/integrations/app-development/jenkins.md
Labels: cla-signed

#5817 Release note for Azure Metrics Source
  blog-service/2025-09-19-collection.md
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/product-list/product-list-m-z.md
Labels: cla-signed

#5820 Add note to Cloud SIEM Sept 19, 2025 release notes article
  blog-cse/2025-09-19-content.md
Labels: doc:minor edit, cla-signed

#5815 Update snowflake-sql-api.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/snowflake-sql-api.md
  static/files/c2c/snowflake-sql-api/example.json
  static/files/c2c/snowflake-sql-api/example.tf
Labels: cla-signed

#5809 DOCS-1010 - Update threat intel enrichment section
  docs/security/threat-intelligence/threat-indicators-in-cloud-siem.md
Labels: doc:update, cla-signed

#5827 Pausing SV - Customer communication
  docs/manage/scheduled-views/pausing-inactive-scheduled-views.md
  static/img/scheduled-views/AutoPause-Details.png
  static/img/scheduled-views/Enable-AutoPause.png
  static/img/scheduled-views/Restart-SV.png
  static/img/scheduled-views/Scheduled-Filter.png
Labels: cla-signed
