Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-04, with the labels that each got.

#5204 Removing apache from common instruction and introducing it as an exam…
  docs/reuse/apps/opentelemetry/collector-installation.md
Labels: cla-signed

#5103 Updated AWSO v2.12 in docs
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/automatic-installation-script.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/observability/aws/deploy-use-aws-observability/migration-strategy-using-terraform.md
  docs/observability/aws/deploy-use-aws-observability/resources.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/faq.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
  static/img/observability/Default-Scope.png
  static/img/observability/mappings.png
Labels: cla-signed

#5224 March release note (apps)
  blog-service/2025-03-31-apps.md
Labels: doc:new, cla-signed, do-not-merge

#5222 DOCS-789 - Update "Introduction to Logs for Security"
  docs/security/additional-security-features/introduction-to-additional-security-features.md
Labels: doc:update, cla-signed

#5228 Fixed the March release note for apps
  blog-service/2025-03-31-apps.md
Labels: doc:minor edit, cla-signed, do-not-merge

#5230 Publish "special communication" for new threat intel source
  docs/security/threat-intelligence/threat-intelligence-vendor-switch.md
  static/img/security/threat-intel-field-mappings.png
Labels: doc:new, cla-signed, hot🔥

#5193 Added a screenshot and call out
  docs/send-data/opentelemetry-collector/remote-management/index.md
  static/img/send-data/remote-mgmt-local.png
Labels: cla-signed

#5210 CSOAR-2860 : Create an AWS WAF Update IP Set Action
  docs/platform-services/automation-service/app-central/integrations/aws-waf.md
Labels: cla-signed

#5229 Removed Mumbai deployment references part2
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  docs/send-data/hosted-collectors/amazon-aws/grant-access-aws-product.md
Labels: cla-signed

#5214 Azure doc updates
  docs/integrations/microsoft-azure/azure-analysis-services.md
  docs/integrations/microsoft-azure/azure-api-management.md
  docs/integrations/microsoft-azure/azure-app-configuration.md
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-automation.md
  docs/integrations/microsoft-azure/azure-backup.md
  docs/integrations/microsoft-azure/azure-batch.md
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
  docs/integrations/microsoft-azure/azure-cognitive-search.md
  docs/integrations/microsoft-azure/azure-container-instances.md
  docs/integrations/microsoft-azure/azure-cosmos-db-for-postgresql.md
  docs/integrations/microsoft-azure/azure-data-explorer.md
  docs/integrations/microsoft-azure/azure-data-factory.md
  docs/integrations/microsoft-azure/azure-database-for-mariadb.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/microsoft-azure/azure-database-for-postgresql.md
  docs/integrations/microsoft-azure/azure-event-grid.md
  docs/integrations/microsoft-azure/azure-event-hubs.md
  docs/integrations/microsoft-azure/azure-front-door.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-hdinsight.md
  docs/integrations/microsoft-azure/azure-iot-hub.md
  docs/integrations/microsoft-azure/azure-key-vault.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-logic-app.md
  docs/integrations/microsoft-azure/azure-machine-learning.md
  docs/integrations/microsoft-azure/azure-network-interface.md
  docs/integrations/microsoft-azure/azure-public-ipAddress.md
  docs/integrations/microsoft-azure/azure-relay.md
  docs/integrations/microsoft-azure/azure-service-bus.md
  docs/integrations/microsoft-azure/azure-sql-elastic-pool.md
  docs/integrations/microsoft-azure/azure-storage.md
  docs/integrations/microsoft-azure/azure-stream-analytics.md
  docs/integrations/microsoft-azure/azure-virtual-network.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/append-blob/collect-logs.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/block-blob/collect-logs.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/ms-azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/microsoft-source/azure-metrics-source.md
  static/img/send-data/azure_functionapp.png
  static/img/send-data/azure_upgrade_status.png
  static/img/send-data/azure_upgrade_sync.png
  static/img/send-data/filtersprocessingrules.png
Labels: cla-signed, hot🔥

#5203 DOCS-553 - Cross-reference Kickstart Data source/app/main pages
  docs/integrations/sumo-apps/kickstart-data.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-logic-kickstart-data-source.md
  static/files/c2c/sumo-logic-kickstart-data/example.json
  static/files/c2c/sumo-logic-kickstart-data/example.tf
Labels: cla-signed

#5234 Revert "Update package dependencies" #5223
  cid-redirects.json
  package.json
  yarn.lock
Labels: cla-signed

#5227 Update joins.md
  docs/metrics/introduction/joins.md
Labels: cla-signed

#5233 DOCS-613 - Proposed edits to AI-Driven Investigations
  docs/observability/ai-driven-investigations.md
  static/img/observability/service-intelligence-history-dialog.png
  static/img/observability/service-intelligence-history.png
  static/img/observability/service-intelligence-refresh-button.png
  static/img/observability/service-intelligence-refresh.png
  static/img/observability/summary-button.png
Labels: cla-signed

#5225 Add info about the max raw message (Field Browser)
  docs/search/get-started-with-search/search-page/field-browser/index.md
Labels: cla-signed

#5239 Cisco Vulnerability Management (apps)
  blog-service/2025-04-03-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/cisco-vulnerability-management.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5243 Add FAQ
  docs/manage/partitions/flex/faq.md
Labels: doc:new, cla-signed

#5236 Legacy 301 fixes
  cid-redirects.json
Labels: cla-signed

#5244 Create 2025-04-03-content.md
  blog-cse/2025-04-03-content.md
Labels: cla-signed

#5241 Update histogram-quantile.md
  docs/metrics/metrics-operators/histogram-quantile.md
Labels: cla-signed

#5237 Collecting Device Apps details added
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/kandji-source.md
  static/files/c2c/kandji/example.json
  static/files/c2c/kandji/example.tf
Labels: cla-signed

#5240 Inline suggestions - Search Editor
  docs/search/query-assist.md
  static/img/search/get-started-search/query-assist-preview1.gif
Labels: cla-signed, do-not-merge

#5245 Add configuration link to integrations article
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: doc:minor edit, cla-signed

#5238 Update filter.md
  docs/metrics/metrics-operators/filter.md
Labels: cla-signed

#5246 CONN-4388: Added limitation for Sysdig Secure state
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sysdig-secure-source.md
Labels: cla-signed

#5231 SUMO-254673 non-FER apps
  docs/integrations/app-development/bitbucket.md
  docs/integrations/app-development/github.md
  docs/integrations/app-development/gitlab.md
  docs/integrations/app-development/jira-cloud.md
  docs/integrations/saas-cloud/opsgenie.md
  docs/integrations/saas-cloud/pagerduty-v2.md
  docs/integrations/saas-cloud/pagerduty-v3.md
  docs/reuse/apps/app-collection-option-1.md
  docs/reuse/apps/app-collection-option-2.md
  docs/reuse/apps/app-collection-option-3.md
  docs/reuse/apps/app-install-v2.md
  docs/reuse/apps/app-update.md
Labels: cla-signed

#5247 Update outlier.md
  docs/search/search-query-language/search-operators/outlier.md
Labels: cla-signed

#5185 DOCS-37 - New threat intel source
  blog-cse/2025-04-08-application.md
  blog-service/2025-04-08-security.md
  cid-redirects.json
  docs/cse/rules/cse-rules-syntax.md
  docs/integrations/amazon-aws/waf.md
  docs/integrations/security-threat-detection/threat-intel-quick-analysis.md
  docs/observability/aws/integrations/aws-dynamodb.md
  docs/search/search-query-language/search-operators/threatip.md
  docs/search/search-query-language/search-operators/threatlookup.md
  docs/search/search-query-language/search-operators/tolowercase-touppercase.md
  docs/search/subqueries.md
  docs/security/additional-security-features/threat-detection-and-investigation.md
  docs/security/threat-intelligence/about-threat-intelligence.md
  docs/security/threat-intelligence/find-threats.md
  docs/security/threat-intelligence/index.md
  docs/security/threat-intelligence/threat-indicators-in-cloud-siem.md
  docs/security/threat-intelligence/threat-intelligence-indicators.md
  docs/security/threat-intelligence/threat-intelligence-mapping.md
  docs/security/threat-intelligence/threat-intelligence-vendor-switch.md
  sidebars.ts
  static/img/security/global-feed-threat-intelligence-tab-example.png
  static/img/security/threat-intelligence-tab-example.png
  static/img/security/threat-intelligence-tab.png
Labels: doc:new, cla-signed

#5257 DOCS-805 - Automation Bridge version
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: doc:update, cla-signed

#5252 Deprecate India data center
  blog-developer/2025-04-09-api.md
  docs/api/access-keys.md
  docs/api/account-management.md
  docs/api/app-management.md
  docs/api/archive-ingestion.md
  docs/api/collector-management/index.md
  docs/api/connections-management.md
  docs/api/content-management.md
  docs/api/content-permissions.md
  docs/api/dashboard.md
  docs/api/dynamic-parsing.md
  docs/api/field-extraction-rules.md
  docs/api/field-management.md
  docs/api/folder-management.md
  docs/api/getting-started.md
  docs/api/health-events.md
  docs/api/ingest-budget-v2.md
  docs/api/log-search-estimated-usage.md
  docs/api/log-searches.md
  docs/api/logs-data-forwarding.md
  docs/api/lookup-tables.md
  docs/api/metrics-query.md
  docs/api/metrics-searches-v2.md
  docs/api/metrics-searches.md
  docs/api/metrics-transformation-rules.md
  docs/api/monitors-management.md
  docs/api/muting-schedules.md
  docs/api/organizations-management.md
  docs/api/partition-management.md
  docs/api/password-policy.md
  docs/api/policies-management.md
  docs/api/role-management-v2.md
  docs/api/role-management.md
  docs/api/saml-configuration.md
  docs/api/scan-budget.md
  docs/api/scheduled-views.md
  docs/api/service-allowlist.md
  docs/api/service-map.md
  docs/api/slo-management.md
  docs/api/span-analytics.md
  docs/api/threat-intel-ingest.md
  docs/api/token-management.md
  docs/api/tracing.md
  docs/api/user-management.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/java.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/nodejs.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/aws-lambda/python.md
  docs/get-started/faq.md
  docs/integrations/amazon-aws/aws-privatelink.md
  docs/manage/security/audit-indexes/documentation-audit-log-definitions.md
  docs/reuse/aws-region-by-sumo-deployment.md
  docs/reuse/cse-api-table.md
  docs/reuse/csoar-api-table.md
  docs/reuse/static-ips-automation-service.md
  docs/send-data/hosted-collectors/amazon-aws/amazon-security-lake-source.md
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-collection-source.md
  docs/send-data/installed-collectors/collector-installation-reference/download-collector-from-static-url.md
Labels: cla-signed, do-not-merge

#5216 Update macro.md
  docs/search/search-query-language/search-operators/macro.md
Labels: cla-signed, do-not-merge

#5259 Proposed changes to PR #5258 - Active Directory v2
  docs/platform-services/automation-service/app-central/integrations/active-directory-v2.md
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-add-roles-and-features.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-add-roles.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-example-path.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-root-domain-name.png
Labels: cla-signed

#5263 DOCS-814 - Remove threatlookup article
  cid-redirects.json
  docs/search/search-query-language/search-operators/threatlookup.md
Labels: doc:update, cla-signed

#5253 DOCS-724 - Kickstart Data GA
  blog-service/2025-03-31-apps.md
  blog-service/2025-04-09-manage.md
  docs/get-started/quickstart.md
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/sumo-apps/index.md
  docs/integrations/sumo-apps/kickstart-data.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-logic-kickstart-data-source.md
  sidebars.ts
  static/img/send-data/sumo-logic-kickstart-data.png
Labels: cla-signed, do-not-merge

#5258 CSOAR-2927 - Active Directory V2 setup
  docs/platform-services/automation-service/app-central/integrations/active-directory-v2.md
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-add-roles-and-features.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-add-roles.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-dn-output-example.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-domain-controller-options.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-edit-resource.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-example-path.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-full-form.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-login-dn.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-promote-server.png
  static/img/platform-services/automation-service/app-central/integrations/active-directory-v2/active-directory-v2-root-domain-name.png
Labels: doc:new, cla-signed

#5265 Update sql-server.md
  docs/integrations/microsoft-azure/sql-server.md
Labels: cla-signed

#5269 DOS-818 - Remove CrowdStrike deprecation mentions
  blog-service/2025-04-08-security.md
  docs/security/threat-intelligence/about-threat-intelligence.md
  docs/security/threat-intelligence/threat-intelligence-vendor-switch.md
Labels: doc:update, cla-signed, hot🔥

#5270 Fix typo in CyberArk article
  docs/integrations/saas-cloud/cyberark-audit.md
Labels: doc:minor edit, cla-signed

#5260 Update azure key vault description
  docs/integrations/microsoft-azure/azure-key-vault.md
Labels: cla-signed

#5272 301 redirects and 404 fixes
  cid-redirects.json
Labels: cla-signed

#5267 Update deletion-requests.md
  docs/manage/deletion-requests.md
Labels: cla-signed, do-not-merge

#5277 Release note content update
  blog-service/2025-03-31-apps.md
Labels: cla-signed, hot🔥

#5276 Annotate comments for threatlookup operator
  docs/integrations/amazon-aws/waf.md
  docs/observability/aws/integrations/aws-dynamodb.md
  docs/search/search-query-language/search-operators/threatip.md
  docs/search/search-query-language/search-operators/tolowercase-touppercase.md
  docs/search/subqueries.md
  docs/security/additional-security-features/threat-detection-and-investigation.md
  docs/security/threat-intelligence/find-threats.md
Labels: doc:minor edit, cla-signed

#5249 DOCS-694 - Additional resources - Proof of concept
  docs/cse/administration/mitre-coverage.md
  docs/cse/rules/about-cse-rules.md
  docs/get-started/ai-machine-learning.md
  docs/integrations/amazon-aws/cloudtrail.md
  docs/integrations/databases/postgresql.md
  docs/integrations/web-servers/opentelemetry/haproxy-opentelemetry.md
  docs/observability/aws/about.md
  docs/observability/kubernetes/about.md
  docs/search/copilot.md
  docs/security/additional-security-features/audit-and-compliance.md
  docs/security/additional-security-features/cloud-infrastructure-security/introduction-to-cloud-infrastructure-security.md
  docs/security/additional-security-features/introduction-to-additional-security-features.md
  docs/send-data/collect-from-other-data-sources/collect-prometheus-metrics.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/universal-connector-source.md
  docs/send-data/opentelemetry-collector/index.md
Labels: doc:update, cla-signed

#5281 Create 2025-04-14-content.md
  blog-cse/2025-04-14-content.md
Labels: cla-signed

#5275 Updated Documention for threatdown oneview
  docs/platform-services/automation-service/app-central/integrations/threatdown-oneview.md
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-8.png
  static/img/platform-services/automation-service/app-central/integrations/threatdown-oneview/threatdown-oneview5.png
  static/img/platform-services/automation-service/app-central/integrations/threatdown-oneview/threatdown-oneview6.png
  static/img/platform-services/automation-service/app-central/integrations/threatdown-oneview/threatdown-oneview7.png
Labels: cla-signed

#5266 Updated Amazon-EBS app
  docs/integrations/amazon-aws/amazon-elastic-block-store.md
  static/img/integrations/amazon-aws/Amazon-EBS-Overview.png
  static/img/integrations/amazon-aws/Amazon-EBS-Performance.png
  static/img/integrations/amazon-aws/Amazon-EBS-Throughput-and-IOPS.png
Labels: cla-signed

#5274 Update netskope-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/netskope-source.md
Labels: cla-signed, do-not-merge

#5278 CSOAR-3203 : Revise the AWS WAF integration documentation in accordance with the latest documentation updates.
  docs/platform-services/automation-service/app-central/integrations/aws-waf.md
  static/img/platform-services/automation-service/app-central/integrations/aws-waf/aws-waf-1.png
Labels: cla-signed

#5273 Update deletion-requests.md
  docs/manage/deletion-requests.md
Labels: cla-signed

#5287 Postgresql opentelemtry app enhanced with newly contributed metrics
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
Labels: cla-signed

#5283 GCP VPC app doc update
  docs/integrations/google/cloud-vpc.md
  static/img/integrations/google/Google-Cloud-VPC-Security-and-Direction.png
Labels: cla-signed

#5271 SUMO-257738: Google Cloud Storage | Docs
  docs/integrations/google/cloud-storage.md
  static/img/integrations/google/Google-Cloud-Storage-Access-and-Security.png
  static/img/integrations/google/Google-Cloud-Storage-Error-and-Access-Denied-Analysis.png
  static/img/integrations/google/Google-Cloud-Storage-Object-Activity.png
  static/img/integrations/google/Google-Cloud-Storage-Operational-Overview.png
  static/img/integrations/google/Google-Cloud-Storage-Operations-and-Error-Analysis copy.png
  static/img/integrations/google/Google-Cloud-Storage-Operations-and-Error-Analysis.png
  static/img/integrations/google/Google-Cloud-Storage-Storage-Optimization-and-Authorization copy.png
  static/img/integrations/google/Google-Cloud-Storage-Storage-Optimization-and-Authorization.png
  static/img/integrations/google/Google-Cloud-Storage-Usage-and-Activity-Overview copy.png
  static/img/integrations/google/Google-Cloud-Storage-Usage-and-Activity-Overview.png
  static/img/integrations/google/google-cloud-storage-buckets.png
  static/img/integrations/google/google-cloud-storage-overview.png
  static/img/integrations/google/google-cloud-storage-users.png
Labels: cla-signed, do-not-merge

#5289 Update Log Search config options
  docs/search/get-started-with-search/build-search/dynamic-parsing.md
  docs/search/get-started-with-search/build-search/use-receipt-time.md
  static/img/search/get-started-search/build-search/dynamic-parsing/auto-parse-mode-option.png
  static/img/search/get-started-search/build-search/dynamic-parsing/field-browser-search-field.png
  static/img/search/get-started-search/build-search/receipt-time-option.png
  static/img/search/get-started-search/build-search/use-receipt-time/messages-with-receipt-time.png
  static/img/search/get-started-search/build-search/use-receipt-time/use-receipt-time.png
Labels: cla-signed

#5286 Update Censys logo
  docs/integrations/product-list/product-list-a-l.md
  docs/platform-services/automation-service/app-central/integrations/censys-v2.md
  static/img/platform-services/automation-service/app-central/logos/censys.png
Labels: doc:minor edit, cla-signed

#5242 Sumo Collection app
  blog-service/2025-04-21-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/sumo-collection.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5293 Correct the naming convention for Auto Scaling
  docs/integrations/amazon-aws/amazon-ec2-auto-scaling.md
  docs/observability/sdo/about-sdo.md
Labels: cla-signed

#5288 SUMO-255292 | Apoorv | Add. Azure VM App Doc and Images
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-key-vault.md
  docs/integrations/microsoft-azure/azure-virtual-machine.md
  docs/integrations/product-list/product-list-a-l.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-virtual-machine-namespaces.png
  static/img/integrations/microsoft-azure/azure-vm-icon.png
Labels: cla-signed

#5294 Azure Kubernetes Service - Create documentation
  docs/integrations/microsoft-azure/kubernetes.md
  static/img/integrations/microsoft-azure/azure-kubernetes-service-namespaces.png
  static/img/integrations/microsoft-azure/diagnostic-setting-azure-kuberetes-service.png
Labels: cla-signed

#5261 Changelog entry for new source template release to include FAQ in the…
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/elasticsearch/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mysql/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/postgresql/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/changelog.md
Labels: cla-signed

#5290 Intelliparse Log Search mode (beta)
  docs/search/get-started-with-search/build-search/intelliparse.md
  static/img/search/get-started-search/build-search/log-search-parsing-modes.png
Labels: cla-signed

#5302 CSOAR-3312: Updated the content CrowdStrike Falcon
  docs/platform-services/automation-service/app-central/integrations/crowdstrike-falcon.md
Labels: cla-signed

#5304 Update atlassian-jira-v2.md
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-v2.md
Labels: cla-signed

#5305 Update atlassian-jira-cloud.md
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-cloud.md
Labels: cla-signed

#5307 Remove note from "Role Based Index Access" release note
  blog-service/2024/12-31.md
Labels: doc:minor edit, cla-signed

#5297 Update azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
Labels: cla-signed, do-not-merge

#5311 Update remove-doc.md
  docs/contributing/remove-doc.md
Labels: cla-signed

#5312 DOCS-845 - Update hasThreatMatch
  docs/cse/rules/cse-rules-syntax.md
Labels: doc:update, cla-signed

#5313 Update network-sensor-end-of-life.md
  docs/cse/sensors/network-sensor-end-of-life.md
Labels: doc:minor edit, cla-signed

#5298 Steps to remove Kickstart Data
  docs/get-started/quickstart.md
  docs/integrations/sumo-apps/kickstart-data.md
  docs/reuse/kickstart.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-logic-kickstart-data-source.md
  static/img/send-data/kickstart-data-retention-partion-confirmation.png
Labels: cla-signed

#5250 Clarify Sumo Collection source intro
  docs/integrations/saas-cloud/sumo-collection.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-collection-source.md
Labels: cla-signed

#4457 Otel collector configuration page update
  docs/send-data/opentelemetry-collector/install-collector/ansible.md
  docs/send-data/opentelemetry-collector/install-collector/chef.md
  docs/send-data/opentelemetry-collector/install-collector/linux.md
  docs/send-data/opentelemetry-collector/install-collector/macos.md
  docs/send-data/opentelemetry-collector/install-collector/puppet.md
  docs/send-data/opentelemetry-collector/install-collector/windows.md
  static/img/send-data/opentelemetry-collector/ansible.png
  static/img/send-data/opentelemetry-collector/chef.png
  static/img/send-data/opentelemetry-collector/linux-terminal.png
  static/img/send-data/opentelemetry-collector/macOs.png
  static/img/send-data/opentelemetry-collector/puppet.png
  static/img/send-data/opentelemetry-collector/windows.png
Labels: cla-signed

#5295 Update confluent-cloud-metrics-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/confluent-cloud-metrics-source.md
Labels: cla-signed, do-not-merge

#5196 DOCS-752 - Copilot unstructured logs beta
  docs/search/copilot-unstructured-logs-beta.md
  docs/search/get-started-with-search/build-search/intelliparse-beta.md
Labels: cla-signed

#5320 Remove location Tag
  docs/integrations/microsoft-azure/azure-container-instances.md
  docs/integrations/microsoft-azure/kubernetes.md
Labels: cla-signed

#5316 Create 2025-04-24-content.md
  blog-cse/2025-04-25-content.md
Labels: cla-signed

#5315 CSOAR-3290: Removed Exana integration doc
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/platform-services/automation-service/app-central/integrations/exana-open-dns.md
  docs/platform-services/automation-service/app-central/integrations/index.md
Labels: cla-signed

#5319 CSOAR-3278: Changed required field
  docs/platform-services/automation-service/app-central/integrations/microsoft-onedrive.md
Labels: cla-signed

#5321 DOCS-830 - Add links to third-party docs
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-cloud.md
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-v2.md
  docs/platform-services/automation-service/app-central/integrations/cisco-meraki.md
  docs/platform-services/automation-service/app-central/integrations/cortex-xdr.md
  docs/platform-services/automation-service/app-central/integrations/cuckoo.md
  docs/platform-services/automation-service/app-central/integrations/cyberark-aam.md
  docs/platform-services/automation-service/app-central/integrations/cyberark-pam.md
  docs/platform-services/automation-service/app-central/integrations/hatching-triage.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-onedrive.md
  docs/platform-services/automation-service/app-central/integrations/microsoft-sharepoint.md
  docs/platform-services/automation-service/app-central/integrations/pagerduty.md
  docs/platform-services/automation-service/configure-authentication-for-integrations.md
  static/img/platform-services/automation-service/app-central/integrations/cyberark-pam/cyberark-pam-4.png
Labels: doc:update, cla-signed

#5308 DOCS-829 - Add Kubernetes attributes processor
  docs/send-data/kubernetes/v4/important-changes.md
Labels: doc:update, cla-signed, do-not-merge

#5299 DOCS-824 - Improve threat intelligence documentation
  docs/cse/administration/create-custom-threat-intel-source.md
  docs/cse/integrations/configuring-threatq-source-in-cse.md
  docs/cse/integrations/integrate-cse-with-taxii-feed.md
  docs/cse/rules/about-cse-rules.md
  docs/security/threat-intelligence/about-threat-intelligence.md
  docs/security/threat-intelligence/find-threats.md
  docs/security/threat-intelligence/index.md
  docs/security/threat-intelligence/threat-indicators-in-cloud-siem.md
  docs/security/threat-intelligence/threat-intelligence-indicators.md
  docs/security/threat-intelligence/upload-formats.md
  sidebars.ts
Labels: doc:update, cla-signed

#5323 DOCS-829: Minor edit to the Kubernetes Attributes processor
  docs/send-data/kubernetes/v4/important-changes.md
Labels: cla-signed

#5322 DOCS-819 - Add note about multiple conditions
  docs/platform-services/automation-service/automation-service-playbooks.md
Labels: doc:minor edit, cla-signed

#5310 Update set-up-webhook-connections.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
Labels: cla-signed

#5327 Update threat intel screenshots
  static/img/security/global-feed-threat-intelligence-tab-example.png
  static/img/security/threat-intelligence-tab-example.png
  static/img/security/threat-intelligence-tab.png
Labels: doc:minor edit, cla-signed

#5080 DOCS-676 - App permissions update
  blog-service/2025-04-28-manage.md
  docs/manage/content-sharing/index.md
  static/img/content-sharing/PermissionsShare.png
  static/img/content-sharing/ShareSearchPrime.png
  static/img/content-sharing/analyst.png
  static/img/content-sharing/grant-app-access-to-org.png
  static/img/content-sharing/unsaved-search.png
Labels: doc:update, cla-signed, do-not-merge

#5329 Legacy 301 fixes
  cid-redirects.json
Labels: cla-signed

#5256 Update Timestamp Autocorrection and Historical Data Ingestion Documen…
  docs/send-data/collector-faq.md
  docs/send-data/reference-information/time-reference.md
Labels: doc:update, cla-signed, do-not-merge

#5284 Best practices for enhanced search performance
  docs/manage/ingestion-volume/log-ingestion.md
  docs/search/optimize-search-performance.md
Labels: cla-signed, do-not-merge

#4277 Update scheduled-report.md
  docs/dashboards/scheduled-report.md
Labels: cla-signed

#5331 April Release Note (apps)
  blog-service/2025-04-30-apps.md
Labels: doc:new, cla-signed, do-not-merge
