Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-03, with the labels that each got.

#5124 Legacy 301s
  cid-redirects.json
Labels: cla-signed

#5130 Remove Cloud SIEM ingestions articles from the product list
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/product-list/product-list-m-z.md
Labels: doc:update, cla-signed

#5067 DOCS-683 - New in Copilot - Dynamic Titles, Alert Troubleshooting, Pinned Suggestions
  blog-service/2025-03-03-copilot-search.md
  cid-redirects.json
  docs/alerts/monitors/alert-response.md
  docs/search/copilot.md
  static/img/alerts/open-in-copilot.png
Labels: cla-signed, do-not-merge

#5126 Automox (apps)
  blog-service/2025-02-27-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/automox.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5132 Remove mentions to real credentials
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-audit-source.md
  static/files/c2c/cyberark-audit/example.json
  static/files/c2c/cyberark-audit/example.tf
Labels: cla-signed

#5135 DOCS-123 - Remove threat intel beta article
  cid-redirects.json
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:update, cla-signed, hot🔥

#5134 Add Deklin to cla file
  .clabot
Labels: doc:minor edit, cla-signed

#5138 DOCS-25 - Fix minor threat intel doc issues
  blog-cse/2025-03-03-application.md
  blog-service/2025-03-03-security.md
  docs/api/index.md
  docs/api/threat-intel-ingest.md
  docs/cse/administration/create-custom-threat-intel-source.md
  docs/cse/get-started-with-cloud-siem/onboarding-checklist-cse.md
  docs/cse/rules/about-cse-rules.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/platform-services/index.md
  docs/search/search-query-language/search-operators/index.md
  docs/search/search-query-language/search-operators/threatlookup.md
  docs/search/subqueries.md
  docs/security/threat-intelligence/threat-intelligence-indicators.md
  docs/security/threat-intelligence/upload-formats.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/intel-471-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mandiant-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zerofox-intel-source.md
  docusaurus.config.js
  sidebars.ts
Labels: doc:update, cla-signed

#5139 Fix release note link
  blog-cse/2025-03-03-application.md
Labels: doc:minor edit, cla-signed

#5137 Update universal-connector-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/universal-connector-source.md
Labels: cla-signed

#5140 CSOAR-2985 : Google Drive Integration Not working as intended
  docs/platform-services/automation-service/app-central/integrations/google-drive.md
Labels: cla-signed

#5141 DOCS-736 - Legacy Cloud SIEM threat intel
  docs/cse/administration/create-custom-threat-intel-source.md
  docs/cse/administration/index.md
  docs/cse/rules/cse-rules-syntax.md
  docs/security/threat-intelligence/threat-indicators-in-cloud-siem.md
  docs/security/threat-intelligence/upload-formats.md
Labels: doc:update, cla-signed, hot🔥

#5061 DOCS-679 - Kanso opt-out GA
  blog-service/2025-03-05-ui.md
  docs/get-started/sumo-logic-ui-classic.md
  docs/get-started/sumo-logic-ui.md
  static/img/get-started/switch-new-ui.png
Labels: cla-signed

#5142 CONN-4275 Update Smartsheet info
  static/files/c2c/smartsheet/example.tf
Labels: cla-signed

#5120 Update media to reflect Kanso Home tiles
  static/img/get-started/library-content-admin.gif
  static/img/get-started/overview-new-ui.png
Labels: cla-signed, do-not-merge

#5143 DOCS-737 - Update enrichment info
  docs/cse/administration/create-cse-actions.md
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/integrations/enrichments-and-indicators.md
  docs/cse/integrations/index.md
  docs/cse/rules/cse-rules-syntax.md
  docs/security/threat-intelligence/threat-indicators-in-cloud-siem.md
  docs/security/threat-intelligence/upload-formats.md
Labels: doc:update, cla-signed, hot🔥

#5136 Update linux.md
  docs/send-data/opentelemetry-collector/install-collector/linux.md
Labels: cla-signed

#5102 Update local-file-source.md
  docs/send-data/installed-collectors/sources/local-file-source.md
Labels: cla-signed

#5110 Update palo-alto-networks.md
  docs/manage/field-extractions/fer-templates/palo-alto-networks.md
Labels: cla-signed

#5146 Update cisco-amp.md
  docs/integrations/saas-cloud/cisco-amp.md
Labels: cla-signed

#5088 Doc updates - Redis and RabbitMQ - metrics collection capability
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/index.md
Labels: cla-signed

#5147 Updated the Data Collected section
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sysdig-secure-source.md
Labels: doc:minor edit, cla-signed, do-not-merge

#5145 Update pct-sampling.md
  docs/search/search-query-language/group-aggregate-operators/pct-percentile.md
  docs/search/search-query-language/group-aggregate-operators/pct-sampling.md
Labels: cla-signed

#5153 Sumo Collection Source (C2C)
  blog-service/2025-03-07-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-collection-source.md
  sidebars.ts
  static/files/c2c/sumo-collection/example.json
  static/files/c2c/sumo-collection/example.tf
  static/img/sumo-logic-logo.png
Labels: doc:new, cla-signed, do-not-merge

#5150 Netskope WebTx (Apps)
  blog-service/2025-03-07-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/netskope-webtx.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5155 Add justrelax19 to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#5151 DOCS-734 - Update SSO for child organizations
  docs/manage/manage-subscription/create-and-manage-orgs/manage-org-settings.md
  static/img/manage/subscriptions/mssp-sso-enabled.png
Labels: doc:update, cla-signed

#5156 DOCS-637 - Add release note
  blog-service/2025-03-07-manage.md
  docs/manage/manage-subscription/create-and-manage-orgs/manage-orgs-for-mssps.md
Labels: doc:new, cla-signed

#5148 CSOAR-2213: Added doc for new integration
  blog-csoar/2024/12-31.md
  docs/integrations/product-list/product-list-m-z.md
  docs/platform-services/automation-service/app-central/integrations/malwarebytes-oneview.md
  docs/platform-services/automation-service/app-central/integrations/threatdown-oneview.md
  static/img/platform-services/automation-service/app-central/integrations/threatdown-oneview/threatdown-oneview1.png
  static/img/platform-services/automation-service/app-central/integrations/threatdown-oneview/threatdown-oneview2.png
  static/img/platform-services/automation-service/app-central/integrations/threatdown-oneview/threatdown-oneview3.png
  static/img/platform-services/automation-service/app-central/integrations/threatdown-oneview/threatdown-oneview4.png
  static/img/platform-services/automation-service/app-central/logos/malwarebytes-oneview.png
  static/img/platform-services/automation-service/app-central/logos/threatdown-oneview.png
Labels: cla-signed

#5152 DOCS-741 - Rules status article
  cid-redirects.json
  docs/cse/rules/before-writing-custom-rule.md
  docs/cse/rules/index.md
  docs/cse/rules/rules-status.md
  sidebars.ts
  static/img/cse/example-monitor-for-rule-status-change.png
  static/img/cse/filter-on-rule-status-1.png
  static/img/cse/filter-on-rule-status-2.png
  static/img/cse/rule-degraded-info-button.png
  static/img/cse/rule-failed-info-button.png
  static/img/cse/rule-status-information-button.png
  static/img/cse/rule-status-on-detail-page.png
  static/img/cse/rule-status-on-list-page.png
  static/img/cse/rule-warning-info-button.png
Labels: doc:new, cla-signed

#5108 DOCS-523 - Strict signal custom insights
  blog-cse/2025-03-10-application.md
  docs/cse/records-signals-entities-insights/configure-custom-insight.md
  static/img/cse/custom-insight.png
  static/img/cse/strict-signal-configuration-checkbox.png
  static/img/cse/ways-to-define-custom-insight.png
Labels: doc:update, cla-signed, do-not-merge

#5118 updated setup collection section
  docs/integrations/microsoft-azure/azure-container-instances.md
Labels: cla-signed

#5160 DOCS-707 - Update the Cloud SIEM SentinelOne article
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/sentinelone.md
Labels: doc:update, cla-signed

#5165 DOCS-746 - Updates to threat intelligence upload formats
  docs/cse/schema/username-and-hostname-normalization.md
  docs/security/threat-intelligence/threat-indicators-in-cloud-siem.md
  docs/security/threat-intelligence/upload-formats.md
Labels: doc:update, cla-signed

#5168 Adding IP Whitelist for Automation Service and Cloud SOAR
  docs/cloud-soar/overview.md
  docs/platform-services/automation-service/about-automation-service.md
  docs/reuse/static-ips-automation-service.md
Labels: cla-signed

#5164 CONN-4297: Update universal-connector-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/universal-connector-source.md
Labels: cla-signed

#5170 Legacy 301 and 404 fixes
  cid-redirects.json
Labels: cla-signed

#5173 Create 2025-03-13-content.md
  blog-cse/2025-03-13-content.md
Labels: cla-signed

#5158 GCP load balancing and BigQuery app updates - metrics collection and dashboards
  docs/integrations/google/bigquery.md
  docs/integrations/google/cloud-load-balancing.md
  static/img/integrations/google/Google-BigQuery-Management.png
  static/img/integrations/google/Google-BigQuery-Query-and-Job-Performance.png
  static/img/integrations/google/Google-BigQuery-Slots-and-Reservation.png
  static/img/integrations/google/Google-BigQuery-Storage-and-Ingestion.png
  static/img/integrations/google/Google-Bigquery-Overview.png
  static/img/integrations/google/Google-Bigquery-Queries.png
  static/img/integrations/google/Google-Bigquery-Users.png
  static/img/integrations/google/Google-Bigquery-mgmt.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Global-External-Bytes-Count.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Global-External-Latency.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Global-External-Overview.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Global-External-Request-Analysis.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Global-External-Requests.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Global-External-Status-Analysis.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Internal-Bytes-Count.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Internal-Latency.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Internal-Overview.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Internal-Request-Analysis.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Internal-Requests.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Internal-Status-Analysis.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Regional-External-Bytes-Count.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Regional-External-Latency.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Regional-External-Overview.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Regional-External-Request-Analysis.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Regional-External-Requests.png
  static/img/integrations/google/Google-Cloud-Application-Load-Balancer-Regional-External-Status-Analysis.png
  static/img/integrations/google/google-cloud-load-balancing-overview.png
  static/img/integrations/google/google-cloud-load-balancing-request-analysis.png
  static/img/integrations/google/google-cloud-load-balancing-status-analysis.png
Labels: cla-signed

#5171 Update Sysdig source doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sysdig-secure-source.md
  static/files/c2c/sysdig-secure/example.json
  static/files/c2c/sysdig-secure/example.tf
Labels: cla-signed

#5172 Update Account Preferences
  docs/get-started/account-settings-preferences.md
  static/img/get-started/change-email.png
  static/img/get-started/preference-settings.png
  static/img/get-started/reset-password.png
Labels: cla-signed

#5178 Update .clabot
  .clabot
Labels: cla-signed

#5131 Alert/monitor docs updates
  docs/alerts/monitors/alert-response.md
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/settings.md
  docs/alerts/monitors/use-playbooks-with-monitors.md
  docs/get-started/account-settings-preferences.md
  docs/integrations/databases/redis.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/manage/partitions/data-tiers/infrequent-tier-monitors.md
  docs/manage/users-roles/roles/role-capabilities.md
  i18n/ja/alerts/alerts/monitors/alert-response.md
  static/img/alerts/alert-list-page-bell-border.png
  static/img/alerts/alert-preferences.png
  static/img/alerts/monitors/analyzing-alert-content.png
  static/img/alerts/monitors/dimensional-explanation.png
  static/img/alerts/monitors/dimensional-explanations.png
  static/img/alerts/monitors/disable-monitor.png
  static/img/alerts/monitors/edit-monitor.png
  static/img/alerts/monitors/filter-monitors.png
  static/img/alerts/monitors/log-fluctuations.png
  static/img/alerts/monitors/monitor-based-slo.png
  static/img/alerts/monitors/monitor-details.png
  static/img/alerts/monitors/monitor-history.png
  static/img/alerts/monitors/monitor-playbooks-ui.png
  static/img/alerts/monitors/monitors-page.png
  static/img/alerts/monitors/more-actions.png
  static/img/alerts/monitors/mute-monitor.png
  static/img/alerts/monitors/open-drilldown-button.png
  static/img/alerts/monitors/quick-menu-monitors.png
  static/img/alerts/monitors/search-alert-list.png
  static/img/alerts/monitors/search-monitors.png
  static/img/alerts/monitors/thresholds-icon.png
  static/img/alerts/monitors/trigger-conditions.png
  static/img/alerts/monitors/view-in-explorer-icon.png
  static/img/alerts/monitors/view-in-explorer-page.png
  static/img/alerts/mute-sched1.png
  static/img/alerts/mute-sched2.png
Labels: doc:update, cla-signed

#5117 Update base64encode.md
  docs/search/search-query-language/search-operators/base64encode.md
Labels: cla-signed, do-not-merge

#5154 SUMO-257020 Updating the doc related to cardinality of metrics monitor
  docs/alerts/monitors/monitor-faq.md
Labels: doc:update, cla-signed

#5167 Updated the app installation section in AWS ALB app doc
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/network-load-balancer.md
Labels: doc:minor edit, cla-signed, do-not-merge

#5184 CSIEM Content 2025-03-18
  blog-cse/2025-03-18-content.md
Labels: cla-signed

#5180 Rename C2C Health Events
  docs/reuse/restart-c2c-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/source-info.md
Labels: cla-signed, do-not-merge

#5187 Update search-job.md
  docs/api/search-job.md
Labels: cla-signed

#5183 Update links in Collector Management APIs doc
  docs/api/collector-management/index.md
Labels: doc:update, cla-signed, do-not-merge

#5189 Confluent Cloud Metrics Source (C2C Collection)
  blog-service/2025-03-19-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/confluent-cloud-metrics-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/confluent-cloud-metrics/example.json
  static/files/c2c/confluent-cloud-metrics/example.tf
  static/img/send-data/confluent-cloud-metrics.png
Labels: doc:new, cla-signed, do-not-merge

#4893 Added new Integration Jira V3
  docs/platform-services/automation-service/app-central/integrations/atlassian-jira-cloud.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  static/img/platform-services/automation-service/app-central/integrations/atlassian-jira-v2/atlassian-jira-v2-8.png
Labels: cla-signed

#5191 Azure Security - Advisor (apps)
  blog-service/2025-03-20-apps.md
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-security-advisor.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/product-list/product-list-a-l.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-security-advisor.png
  static/img/integrations/microsoft-azure/create-action-group.png
  static/img/integrations/microsoft-azure/create-advisor-alert.png
Labels: doc:new, cla-signed, do-not-merge

#5192 Updated Remote and Local File Source docs
  docs/send-data/installed-collectors/sources/local-file-source.md
  docs/send-data/installed-collectors/sources/remote-file-source/index.md
  static/img/send-data/advanced-options-local-file-source.png
  static/img/send-data/advanced-options-remote-file-source.png
Labels: doc:minor edit, cla-signed, do-not-merge

#5186 Update search-job.md
  docs/api/search-job.md
Labels: cla-signed

#5157 Update windows.md
  docs/send-data/installed-collectors/windows.md
Labels: cla-signed

#5144 Enable/Disable a source template
  docs/send-data/opentelemetry-collector/remote-management/source-templates/manage-source-templates.md
  static/img/send-data/enable-confirm-st.png
  static/img/send-data/enable-st.png
  static/img/send-data/st-landing-page.png
Labels: cla-signed

#5200 Update ECS Legacy app docs
  docs/integrations/amazon-aws/elastic-container-service.md
Labels: cla-signed

#5202 Update threat intel source step
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/intel-471-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mandiant-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-2-client-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zerofox-intel-source.md
Labels: doc:minor edit, cla-signed

#5056 DOCS-684 - Add new tab preference
  blog-service/2025-03-25-manage.md
  docs/get-started/account-settings-preferences.md
  static/img/get-started/my-preferences.png
  static/img/get-started/my-profile.png
  static/img/get-started/open-in-new-tab-button-on-folder.png
  static/img/get-started/open-in-new-tab-button.png
Labels: doc:new, cla-signed, do-not-merge

#5206 Update lambda.md
  docs/integrations/amazon-aws/lambda.md
Labels: cla-signed

#5208 Update fillmissing.md
  docs/metrics/metrics-operators/fillmissing.md
Labels: cla-signed

#5197 Add borders to images in the "Collect Metrics from Azure Monitor" article
  docs/send-data/collect-from-other-data-sources/azure-monitoring/collect-metrics-azure-monitor.md
  static/img/send-data/Azure-metrics.png
Labels: doc:minor edit, cla-signed

#5211 Fix typo in ServiceNow V2 article
  docs/platform-services/automation-service/app-central/integrations/servicenow-v2.md
Labels: doc:minor edit, cla-signed

#5212 Update cisco-vulnerability-management-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-vulnerability-management-source.md
Labels: cla-signed

#5213 PLG-623: updated docs for kickstart data
  docs/integrations/sumo-apps/kickstart-data.md
  static/img/integrations/sumo-apps/Sumo-Logic-Kickstart-Data-Security-Dashboard.png
Labels: cla-signed

#5179 Export audit events
  docs/search/get-started-with-search/search-basics/export-search-results.md
Labels: cla-signed, do-not-merge

#5199 Added docs for ec2 auto-scaling
  docs/integrations/amazon-aws/amazon-ec2-auto-scaling.md
  static/img/integrations/01.-Amazon-EC2-Auto-Scaling-Overview.png
  static/img/integrations/02.-Amazon-EC2-Auto-Scaling-CloudTrail-Audit.png
  static/img/integrations/03.-Amazon-EC2-Auto-Scaling-Instances.png
  static/img/integrations/04.-Amazon-EC2-Auto-Scaling-Capacity.png
  static/img/integrations/05.-Amazon-EC2-Auto-Scaling-Warm-Pool.png
Labels: cla-signed, do-not-merge

#5188 Add Azure Key Vaults Doc changes with Dashboards and alerts
  docs/integrations/microsoft-azure/azure-key-vault.md
  static/img/integrations/microsoft-azure/azure-key-vaults-namespaces.png
Labels: cla-signed

#5207 Update log-level.md
  docs/search/get-started-with-search/search-page/log-level.md
Labels: cla-signed

#5220 RSA Conference 2025 banner
  docusaurus.config.js
Labels: cla-signed

#5223 Update package dependencies
  cid-redirects.json
  package.json
  yarn.lock
Labels: cla-signed, dependencies
