Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-06, with the labels that each got.

#5427 CSOAR-3362: Updated the content of Hatching Triage Integration
  docs/platform-services/automation-service/app-central/integrations/hatching-triage.md
Labels: cla-signed

#5194 DOCS-235 - Historical baselines in Cloud SIEM
  blog-cse/2025-06-02-application.md
  docs/cse/rules/rules-status.md
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-outlier-rule.md
  static/img/cse/empty-first-seen-rule.png
  static/img/cse/empty-outlier-rule.png
  static/img/cse/first-seen-rule.png
  static/img/cse/first-seen-signal-example.png
  static/img/cse/outlier-rule.png
Labels: doc:new, cla-signed, do-not-merge

#5429 Fix date on release note
  blog-cse/2025-06-02-application.md
Labels: cla-signed

#5424 Clarify screenshot image guidance in Style Guide
  docs/contributing/style-guide.md
Labels: cla-signed

#5379 Collector Release Notes refactor
  blog-collector/2023/12-31.md
  blog-collector/2025-01-08-otel.md
  blog-collector/2025-02-18-installed.md
  blog-collector/2025-05-14-installed.md
  blog-service/2023/12-31.md
  docs/release-notes/index.md
Labels: cla-signed

#5438 Fix typo in Cloud SIEM entity criticality article
  docs/cse/records-signals-entities-insights/entity-criticality.md
Labels: doc:minor edit, cla-signed

#5442 Add redirect for Root Cause Explorer
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#5445 DOCS-913 - Add micro lesson videos to the access keys article
  docs/manage/security/access-keys.md
Labels: doc:update, cla-signed

#5444 DET-1326 - Update the custom rule article
  docs/cse/rules/before-writing-custom-rule.md
  static/img/cse/example-in-editor.png
Labels: doc:update, cla-signed

#5449 Added new dashboards for RDS proxy in Amazon RDS app
  docs/integrations/amazon-aws/rds.md
  static/img/integrations/amazon-aws/Amazon-RDS-Proxy-Audit.png
  static/img/integrations/amazon-aws/Amazon-RDS-Proxy-Client-Connection-Endpoint-Performance.png
  static/img/integrations/amazon-aws/Amazon-RDS-Proxy-Log-Analysis.png
  static/img/integrations/amazon-aws/Amazon-RDS-Proxy-Overview.png
  static/img/integrations/amazon-aws/Amazon-RDS-Proxy-Query-Endpoint-Performance.png
  static/img/integrations/amazon-aws/Amazon-RDS-Proxy-Target-Performance.png
  static/img/integrations/amazon-aws/Amazon-RDS-Proxy-Target-Role-Performance.png
Labels: cla-signed

#5450 DOCS-915 - Update insight response metric description
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
  static/img/cse/hud.png
Labels: doc:update, cla-signed

#5433 Updating Azure service bus app doc wrt Beta metric source
  docs/integrations/microsoft-azure/azure-service-bus.md
Labels: cla-signed

#5448 Add env var syntax deprecation note to 12 OpenTelemetry app docs
  docs/integrations/app-development/opentelemetry/jmx-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/activemq-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/rabbitmq-opentelemetry.md
  docs/integrations/containers-orchestration/opentelemetry/vmware-opentelemetry.md
  docs/integrations/databases/opentelemetry/cassandra-opentelemetry.md
  docs/integrations/databases/opentelemetry/elasticsearch-opentelemetry.md
  docs/integrations/databases/opentelemetry/mongodb-opentelemetry.md
  docs/integrations/databases/opentelemetry/mysql-opentelemetry.md
  docs/integrations/databases/opentelemetry/oracle-opentelemetry.md
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/integrations/databases/opentelemetry/redis-opentelemetry.md
  docs/integrations/web-servers/opentelemetry/apache-tomcat-opentelemetry.md
  docs/reuse/apps/opentelemetry/env-var-optional.md
  docs/reuse/apps/opentelemetry/env-var-required.md
Labels: cla-signed

#5453 Legacy 301 and 404 fixes
  cid-redirects.json
Labels: cla-signed

#5345 DOCS-868 - Free tier plan deprecation
  docs/get-started/sign-up.md
  docs/integrations/amazon-aws/threat-intel.md
  docs/manage/manage-subscription/close-cancel-sumo-account.md
  docs/manage/manage-subscription/manage-billing-information.md
  docs/manage/manage-subscription/upgrade-account/index.md
  docs/manage/manage-subscription/upgrade-account/upgrade-credits-account.md
  docs/manage/manage-subscription/upgrade-account/upgrade-sumo-logic-flex-account.md
  docs/manage/manage-subscription/usage-management.md
  docs/search/lookup-tables/create-lookup-table.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  static/img/manage/subscriptions/essentials-landing-page.jpg
  static/img/manage/subscriptions/essentials-landing-page.png
  static/img/manage/subscriptions/upgrade-free-to-essentials-credits.png
Labels: cla-signed

#5458 Update slack-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/slack-source.md
Labels: cla-signed

#5435 CSOAR-3418: Trend Micro Vision ONE Integration problem
  docs/platform-services/automation-service/app-central/integrations/trend-micro-vision-one.md
Labels: cla-signed

#5280 DOCS-236 - Add insight summary section
  docs/cse/get-started-with-cloud-siem/insight-summary.md
  static/img/cse/insight-summary-pane.png
Labels: doc:new, cla-signed, do-not-merge

#5462 DOCS-918 - Update search filter limitations
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
Labels: doc:minor edit, cla-signed

#5465 Update Azure Key Vault with Azure metrics source compatibility
  docs/integrations/microsoft-azure/azure-key-vault.md
Labels: doc:update, cla-signed, do-not-merge

#5423 DOCS-895 - Remove XHR metrics from RUM docs
  docs/apm/real-user-monitoring/dashboards.md
  docs/apm/real-user-monitoring/metrics.md
Labels: cla-signed, do-not-merge

#5467 DOCS-930 - Add Contrast Security to product list
  docs/integrations/product-list/product-list-a-l.md
  static/img/integrations/misc/contrast-security-logo.png
Labels: doc:minor edit, cla-signed

#5468 Create 2025-06-12-content.md
  blog-cse/2025-06-12-content.md
Labels: cla-signed

#5474 Docusaurus Faster update
  package.json
  yarn.lock
Labels: doc:site tech, cla-signed

#5470 Added a note to the Snowflake Logs Source doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/snowflake-logs-source.md
Labels: doc:update, cla-signed, do-not-merge

#5471 Release note for AWS CloudTrail update
  blog-service/2025-06-16-apps.md
Labels: doc:new, cla-signed

#5436 Azure Security products - Help docs
  docs/integrations/microsoft-azure/microsoft-defender-for-cloud-apps.md
  docs/integrations/microsoft-azure/microsoft-defender-for-endpoint.md
  docs/integrations/microsoft-azure/microsoft-defender-for-identity.md
  docs/integrations/microsoft-azure/microsoft-defender-for-office-365.md
  docs/integrations/microsoft-azure/microsoft-entra-id-protection.md
  docs/integrations/microsoft-azure/microsoft-purview-data-loss-prevention.md
  sidebars.ts
  static/img/integrations/microsoft-azure/microsoft-defender-for-identity.png
  static/img/integrations/microsoft-azure/microsoft-defender-office-365.png
  static/img/integrations/microsoft-azure/microsoft-entra-id-protection.png
  static/img/integrations/microsoft-azure/microsoft-purview-data-loss-prevention.png
Labels: doc:new, cla-signed, do-not-merge

#5477 Palo Alto Networks 11 App doc
  blog-service/2025-06-17-apps.md
  cid-redirects.json
  docs/integrations/cloud-security-monitoring-analytics/index.md
  docs/integrations/cloud-security-monitoring-analytics/palo-alto-networks-11.md
  docs/integrations/product-list/product-list-m-z.md
  sidebars.ts
Labels: cla-signed

#5479 pfSense fix
  docs/integrations/product-list/product-list-m-z.md
  static/img/integrations/misc/pfsense-logo.png
Labels: cla-signed

#5482 Update security-hub.md
  docs/integrations/amazon-aws/security-hub.md
Labels: cla-signed

#5466 Update Azure Event Grid with Azure metrics source compatibility
  docs/integrations/microsoft-azure/azure-event-grid.md
Labels: doc:update, cla-signed

#5492 DOCS-944 - Remove deprecation language from Cloud SIEM actions and enrichment server documentation
  docs/cse/administration/create-cse-actions.md
  docs/cse/automation/automations-in-cloud-siem.md
  docs/cse/integrations/insight-enrichment-server.md
Labels: doc:update, cla-signed

#5500 Add 404 and Legacy 301 fixes
  cid-redirects.json
Labels: cla-signed

#5501 Algolia - Remove SearchBar.js
  src/theme/SearchBar.js
Labels: cla-signed

#5487 Update deploy with terraform doc
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: doc:minor edit, cla-signed, do-not-merge

#5496 Akamai CPC (apps)
  blog-service/2025-06-20-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/akamai-cpc.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5488 Update Azure App Service Environment with _index partitions, automatic field creation
  docs/integrations/microsoft-azure/azure-app-service-environment.md
Labels: doc:update, cla-signed, do-not-merge

#5504 Snowflake logs (apps)
  blog-service/2025-06-20-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/snowflake-logs.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5506 Update apps release note for 2025-06-20
  blog-service/2025-06-20-apps.md
  docs/integrations/saas-cloud/index.md
Labels: cla-signed

#5508 DOCS-940 - Improve Cloud SOAR widgets documentation
  docs/cloud-soar/incidents-triage.md
  static/img/cloud-soar/bulk-actions.png
  static/img/cloud-soar/example-pie-chart-widget.png
  static/img/cloud-soar/example-widget-for-frozen-incidents.png
  static/img/cloud-soar/example-widget-for-open-incidents.png
  static/img/cloud-soar/incident-query-cheatsheet.png
  static/img/cloud-soar/open-and-frozen-incidents.png
Labels: doc:update, cla-signed

#5516 DOCS-934 - Update .clabot
  .clabot
Labels: cla-signed

#5515 DOCS-949 - Fix incorrect KnowBe4 C2C source link on integrations doc
  docs/integrations/saas-cloud/knowbe4.md
Labels: cla-signed

#5520 Add Algolia/DocSearch insights parameter to docusaurus.config.js
  docusaurus.config.js
Labels: cla-signed

#5519 Update collect-with-cloudformation-template.md
  docs/send-data/collect-from-other-data-sources/amazon-cloudwatch-logs/collect-with-cloudformation-template.md
Labels: cla-signed

#5528 CSIEM Content 2025-06-26
  blog-cse/2025-06-26-content.md
Labels: cla-signed

#5526 Update AWS Security Hub doc
  docs/integrations/amazon-aws/index.md
  docs/integrations/amazon-aws/security-hub.md
  docs/integrations/product-list/product-list-a-l.md
Labels: doc:minor edit, cla-signed, do-not-merge

#5522 Remove the ARK reference from the Cloud SOAR docs
  docs/cloud-soar/introduction.md
  docs/cloud-soar/legacy/legacy-cloud-soar-architecture.md
  docs/cloud-soar/legacy/legacy-global-functions-menu.md
  docs/cloud-soar/overview.md
Labels: cla-signed

#5527 Timezone - Scheduled Views
  blog-service/2025-06-30-manage.md
  docs/manage/scheduled-views/add-scheduled-view.md
  docs/manage/scheduled-views/view-list-scheduled-views.md
  static/img/scheduled-views/add-view.png
  static/img/scheduled-views/sched-view-details.png
Labels: cla-signed, do-not-merge

#5505 CSOAR-3196-new: Issue with Global Confidence Score display
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-automation-tools.md
Labels: cla-signed

#5532 Updated doc for azure virtual network
  docs/integrations/microsoft-azure/azure-virtual-network.md
Labels: cla-signed
