Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-05, with the labels that each got.

#5041 DOCS-325 - Service accounts
  blog-service/2025-05-01-manage.md
  cid-redirects.json
  docs/api/index.md
  docs/api/service-accounts.md
  docs/manage/security/access-keys.md
  docs/manage/security/service-accounts.md
  sidebars.ts
  static/img/security/add-service-account.png
  static/img/security/edit-access-keys-on-service-account.png
  static/img/security/modify-options-for-service-accounts.png
  static/img/security/service-account-details.png
  static/img/security/service-accounts-page.png
Labels: doc:new, cla-signed

#4157 V1 to v2 apps migration (Release_2) + Threat Intel
  docs/integrations/microsoft-azure/teams.md
  docs/integrations/saas-cloud/gmail-tracelogs.md
  docs/integrations/saas-cloud/microsoft-exchange-trace-logs.md
  docs/integrations/security-threat-detection/threat-intel-quick-analysis.md
Labels: cla-signed

#5009 SUMO-254678: Doc update Database apps migration V1 to V2
  docs/integrations/amazon-aws/dynamodb.md
  docs/integrations/databases/cassandra.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/elasticsearch.md
  docs/integrations/databases/mariadb.md
  docs/integrations/databases/memcached.md
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/oracle.md
  docs/integrations/databases/postgresql.md
  docs/integrations/databases/redis.md
  docs/integrations/microsoft-azure/sql-server.md
  docs/observability/application-components.md
Labels: cla-signed

#5335 DOCS-860 - Update service accounts
  docs/api/service-accounts.md
  docs/manage/security/service-accounts.md
  static/img/security/edit-access-keys-on-service-account.png
  static/img/security/service-account-details.png
Labels: doc:update, cla-signed

#5337 Add stephenthedev to cla
  .clabot
Labels: doc:minor edit, cla-signed

#5336 doc: Updated api resource reference for metricsQueries
  docs/api/metrics-query.md
Labels: cla-signed

#5338 Update docusaurus.config.js
  docusaurus.config.js
Labels: cla-signed

#5254 V2 migration apps with fers
  docs/integrations/containers-orchestration/activemq.md
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/containers-orchestration/rabbitmq.md
Labels: cla-signed, do-not-merge

#5340 CSOAR-3291: Updated circl cve integration
  docs/platform-services/automation-service/app-central/integrations/circl-cve-search.md
Labels: cla-signed

#5292 Update cloudtrail.md
  docs/integrations/amazon-aws/cloudtrail.md
Labels: cla-signed

#5339 Update aws-waf.md
  docs/integrations/cloud-security-monitoring-analytics/aws-waf.md
Labels: cla-signed

#5324 Remove beta tag - Role Management API (V2)
  docs/api/getting-started.md
  docs/api/index.md
  docs/api/role-management-v2.md
  src/css/sumo.scss
Labels: cla-signed

#5215 DOCS-780 - Real-time sched search deprecation
  blog-service/2021/12-31.md
  blog-service/2024/12-31.md
  blog-service/2025-05-05-alerts.md
  cid-redirects.json
  docs/alerts/difference-from-scheduled-searches.md
  docs/alerts/scheduled-searches/create-email-alert.md
  docs/alerts/scheduled-searches/create-real-time-alert.md
  docs/alerts/scheduled-searches/deprecation.md
  docs/alerts/scheduled-searches/faq.md
  docs/alerts/scheduled-searches/index.md
  docs/alerts/scheduled-searches/schedule-search.md
  docs/alerts/webhook-connections/schedule-searches-webhook-connections.md
  docs/contributing/glossary.md
  docs/contributing/word-list.md
  docs/dashboards/share-dashboard-outside-org.md
  docs/get-started/account-settings-preferences.md
  docs/manage/manage-subscription/cloud-flex-legacy-accounts.md
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
  docs/manage/manage-subscription/sumo-logic-flex-accounts.md
  docs/manage/partitions/data-tiers/searching-data-tiers.md
  docs/search/behavior-insights/logexplain.md
  docs/search/search-cheat-sheets/log-operators.md
  docs/search/search-query-language/search-operators/join.md
  docs/search/search-query-language/search-operators/queryendtime.md
  docs/search/search-query-language/search-operators/querystarttime.md
  docs/search/search-query-language/search-operators/querytimerange.md
  docs/search/search-query-language/transaction-analytics/transactionize-operator.md
  docs/search/subqueries.md
  docs/send-data/reference-information/time-reference.md
  i18n/ja/alerts/alerts/scheduled-searches/create-real-time-alert.md
  i18n/ja/alerts/alerts/scheduled-searches/faqs/real-time-alert-with-greater-than-results.md
  i18n/ja/alerts/alerts/scheduled-searches/index.md
  i18n/ja/alerts/alerts/scheduled-searches/receive-email-alerts.md
  i18n/ja/alerts/alerts/scheduled-searches/schedule-search.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#5343 Update Root Cause Explorer article
  docs/observability/root-cause-explorer-deprecation.md
Labels: doc:minor edit, cla-signed

#5341 added cid number
  cid-redirects.json
Labels: cla-signed

#5318 SUMO-260501 - Copilot billing/search behavior
  docs/search/copilot.md
Labels: cla-signed, do-not-merge

#5349 404 fixes
  cid-redirects.json
Labels: cla-signed

#5326 CSOAR-3221 : API Error NoRegisteredProviderFound on MS Sentinel Integration
  docs/platform-services/automation-service/app-central/integrations/microsoft-sentinel.md
  static/img/platform-services/automation-service/app-central/integrations/microsoft-sentinel/ms-sentinel.png
Labels: cla-signed

#5353 User added to the .clabot file
  .clabot
Labels: cla-signed

#5354 Update Azure docs for Azure metrics source compatibility (Apps - Part 1)
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/kubernetes.md
Labels: doc:update, cla-signed, do-not-merge

#5357 Update SCIM User permissions
  docs/api/scim-user.md
Labels: doc:minor edit, cla-signed

#5351 SUMO-261315: Documentation | V1V2 Migration (Varnish, StrimziKafka, SquidProxy, IIS7/8)
  docs/integrations/containers-orchestration/strimzi-kafka.md
  docs/integrations/microsoft-azure/iis-7.md
  docs/integrations/web-servers/squid-proxy.md
  docs/integrations/web-servers/varnish.md
Labels: cla-signed

#5358 Create 2025-05-09-content.md
  blog-cse/2025-05-09-content.md
Labels: cla-signed

#5360 Sysdig Secure (apps)
  blog-service/2025-05-12-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/sysdig-secure.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5334 View variables in dashboard
  docs/dashboards/panels/modify-chart.md
Labels: cla-signed, do-not-merge

#5362 Add legacy 301s and update robots.txt
  cid-redirects.json
  static/robots.txt
Labels: doc:site tech, cla-signed

#5366 Add note to May 9, 2025 Cloud SIEM release notes
  blog-cse/2025-05-09-content.md
Labels: doc:minor edit, cla-signed, hot🔥

#5370 Remove note from May 9, 2025 Cloud SIEM release notes
  blog-cse/2025-05-09-content.md
Labels: doc:minor edit, cla-signed

#5369 Sysdig secure (apps)
  docs/integrations/saas-cloud/sysdig-secure.md
Labels: cla-signed

#5368 Bitwarden
  blog-service/2025-05-13-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/bitwarden.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5364 SUMO-259572 | Apoorv | Add. function app doc updates
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-virtual-machine.md
Labels: cla-signed

#5372 Updated Azure docs for Azure metrics source compatibility (part 2)
  docs/integrations/microsoft-azure/azure-container-instances.md
  docs/integrations/microsoft-azure/kubernetes.md
Labels: doc:update, cla-signed, do-not-merge

#5371 Collector Version 19.525-42 - Release note
  blog-collector/2025-02-18.md
  blog-collector/2025-05-14.md
Labels: cla-signed, do-not-merge

#5373 updated Error Log filepath
  docs/integrations/microsoft-azure/azure-container-instances.md
Labels: cla-signed

#5363 Updated AWS lambda app
  docs/integrations/amazon-aws/lambda.md
  static/img/integrations/amazon-aws/AWS-Lambda-Error-Analysis.png
  static/img/integrations/amazon-aws/AWS-Lambda-Overview.png
  static/img/integrations/amazon-aws/AWS-Lambda-Performance-Trends.png
  static/img/integrations/amazon-aws/AWS-Lambda-Request-Analysis.png
  static/img/integrations/amazon-aws/AWS-Lambda-Resource-Usage.png
  static/img/integrations/amazon-aws/AWS-Lambda-Threat-Intel.png
  static/img/integrations/amazon-aws/AWS-Lambda-Usage-Analysis.png
Labels: cla-signed

#5374 SUMO-259572 | Add. monitors and new dashboard to Azure Web Apps
  docs/integrations/microsoft-azure/web-apps.md
Labels: cla-signed

#5377 Legacy 301 and 404 fixes
  cid-redirects.json
  docs/manage/security/about-2-step-verification.md
  docs/manage/security/audit-indexes/audit-event-index.md
  docs/manage/security/index.md
  sidebars.ts
Labels: cla-signed

#5291 DOCS-811 Kickstart / Getting Started onboarding refactor
  blog-service/2025-02-25-apps.md
  blog-service/2025-05-15-get-started.md
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  docs/integrations/sumo-apps/kickstart-data.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-logic-kickstart-data-source.md
  static/img/get-started/kickstart-welcome-landing.png
Labels: cla-signed, do-not-merge

#5380 Kickstart Data removal guidance
  docs/integrations/sumo-apps/kickstart-data.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sumo-logic-kickstart-data-source.md
Labels: cla-signed, hot🔥

#5352 Akamai CPC doc creation
  blog-service/2025-05-16-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/akamai-cpc-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/akamai-cpc/example.json
  static/files/c2c/akamai-cpc/example.tf
Labels: cla-signed, do-not-merge

#5376 DOCS-873 - Remove duplicate information from Cloud SIEM ingestion articles
  cid-redirects.json
  docs/cse/ingestion/cse-ingestion-best-practices.md
  docs/cse/ingestion/index.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/auth0.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-application-load-balancer.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-cloudtrail.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-guardduty.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-network-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/aws-vpc-flow.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/carbon-black.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/check-point-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/cisco-asa.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/cisco-meraki.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/corelight-zeek.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/fortigate-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/g-suite-alert-center.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/google-workspace-apps-audit.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/index.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/kemp-loadmaster.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/linux-os-syslog.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-audit-office.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-azure-activity-log.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/microsoft-windows.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/nginx-access-logs.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/okta.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/onelogin.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/osquery.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/palo-alto-firewall.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/sentinelone.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/signal-sciences-waf.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/symantec-proxy-secure-gateway-blue-coat-proxy.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/symantec-proxy-secure-gateway.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/zscaler-nss.md
  docs/cse/ingestion/ingestion-sources-for-cloud-siem/zscaler-private-access.md
  docs/integrations/amazon-aws/guardduty.md
  docs/integrations/amazon-aws/vpc-flow-logs.md
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saml/auth0.md
  docs/send-data/hosted-collectors/amazon-aws/aws-s3-source.md
  docs/send-data/hosted-collectors/google-source/google-workspace-apps-audit-source.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/index.md
  docs/send-data/hosted-collectors/microsoft-source/ms-office-audit-source.md
  docs/send-data/installed-collectors/sources/syslog-source.md
  sidebars.ts
Labels: doc:update, cla-signed

#5330 Add information about the Searchable time
  docs/search/get-started-with-search/search-page/field-browser/index.md
Labels: cla-signed, do-not-merge

#5384 Small fixes to Cloud SIEM
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
  docs/security/threat-intelligence/threat-indicators-in-cloud-siem.md
Labels: doc:minor edit, cla-signed

#5382 Added the Neustar Doc to the Static folder
  docs/search/search-query-language/search-operators/geoip.md
  static/files/IP-Geo-Point-Data-Glossary.pdf
Labels: cla-signed

#5385 Update Azure Cache for Redis with Azure metrics source compatibility (Part 3)
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
Labels: doc:update, cla-signed, do-not-merge

#5388 Snowflake Logs (C2C)
  blog-service/2025-05-21-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/snowflake-logs-source.md
  sidebars.ts
  static/files/c2c/snowflake-logs/example.json
  static/files/c2c/snowflake-logs/example.tf
Labels: doc:new, cla-signed, do-not-merge

#5389 Update Azure App Service Plan with Azure metrics source compatibility
  docs/integrations/microsoft-azure/azure-app-service-plan.md
Labels: doc:update, cla-signed, do-not-merge

#5386 Update Azure database for mysql with Azure metrics source compatibility
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
Labels: doc:update, cla-signed

#5390 CSOAR-2039: Added new google Integration
  docs/platform-services/automation-service/app-central/integrations/google-workspace-idp.md
  docs/platform-services/automation-service/app-central/integrations/index.md
  static/img/platform-services/automation-service/app-central/integrations/google-drive/google-drive-9.png
  static/img/platform-services/automation-service/app-central/integrations/google-workspace-idp/google-workspace-idp1.png
  static/img/platform-services/automation-service/app-central/integrations/misc/google-workspace-idp-configuration.png
Labels: cla-signed

#5392 Azure apps use index and not source category as installation paramete…
  docs/integrations/microsoft-azure/azure-app-service-plan.md
  docs/integrations/microsoft-azure/azure-application-gateway.md
  docs/integrations/microsoft-azure/azure-cache-for-redis.md
  docs/integrations/microsoft-azure/azure-container-instances.md
  docs/integrations/microsoft-azure/azure-database-for-mysql.md
  docs/integrations/microsoft-azure/azure-functions.md
  docs/integrations/microsoft-azure/azure-load-balancer.md
  docs/integrations/microsoft-azure/azure-virtual-machine.md
  docs/integrations/microsoft-azure/kubernetes.md
  docs/integrations/microsoft-azure/web-apps.md
  docs/reuse/apps/app-install-index-option.md
  docs/reuse/apps/view-dashboards-index.md
Labels: cla-signed

#5393 SUMO-261517: Azure API Management app doc update wrt Beta metric source and monitors
  docs/integrations/microsoft-azure/azure-api-management.md
Labels: cla-signed

#5395 DOCS-890 - Cloud SIEM logical OR operator
  docs/cse/rules/cse-rules-syntax.md
Labels: doc:update, cla-signed

#5396 DOCS-887 - Add troubleshooting item for Kubernetes
  docs/send-data/kubernetes/troubleshoot-collection.md
Labels: doc:new, cla-signed

#5397 DOCS-894 - Update TAXII article
  docs/cse/integrations/integrate-cse-with-taxii-feed.md
Labels: doc:update, cla-signed

#5398 Update trellix-mvisio-epo-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/trellix-mvisio-epo-source.md
Labels: cla-signed

#5381 Query syntax fix
  docs/integrations/amazon-aws/cost-explorer.md
  docs/integrations/security-threat-detection/crowdstrike-falcon-endpoint-protection.md
  docs/manage/field-extractions/fer-templates/akamai-cloud-monitor.md
  docs/manage/field-extractions/fer-templates/apache-access-logs.md
  docs/manage/field-extractions/fer-templates/apache-tomcat-access-log-fer.md
  docs/manage/field-extractions/fer-templates/apache-tomcat-access-logs.md
  docs/manage/field-extractions/fer-templates/cisco-fwsm-fer.md
  docs/manage/field-extractions/fer-templates/nginx-logs.md
  docs/manage/field-extractions/fer-templates/varnish-logs.md
  docs/manage/field-extractions/safend-field-extraction.md
Labels: cla-signed, do-not-merge

#5401 Screenshot update required in the doc for bitbucket app after a fix m…
  static/img/integrations/app-development/Bitbucket_PullRequests.png
Labels: cla-signed

#5399 Create 2025-05-22-content.md
  blog-cse/2025-05-23-content.md
Labels: cla-signed

#5394 CSOAR-3239 : The Hive integration fails with error message about start-date and also certificate warning
  docs/platform-services/automation-service/app-central/integrations/thehive.md
  static/img/platform-services/automation-service/app-central/integrations/misc/thehive-configuration.png
Labels: cla-signed

#5391 Kaltura (apps)
  blog-service/2025-05-21-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/kaltura.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5403 Fixing syntax for _any operator
  docs/apm/traces/search-query-language-support-for-traces.md
Labels: cla-signed

#5405 Update log-operators.md
  docs/search/search-cheat-sheets/log-operators.md
Labels: cla-signed

#5404 Update cloud-iam.md
  docs/integrations/google/cloud-iam.md
Labels: cla-signed

#5411 Fix duplicate release notes RSS links
  docs/release-notes/index.md
Labels: cla-signed

#5414 Fix typo in Cloud SIEM article
  docs/cse/get-started-with-cloud-siem/intro-for-administrators.md
Labels: doc:minor edit, cla-signed

#5285 DOCS-463 - Access keys rotation
  blog-service/2025-05-29-manage.md
  docs/manage/security/access-keys.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
  static/img/security/access-key-expiration-policy.png
  static/img/security/my-access-keys1.png
Labels: doc:new, cla-signed

#5415 Clarify available threat intelligence sources
  docs/security/threat-intelligence/upload-formats.md
Labels: doc:update, cla-signed

#5417 Add Flex Tier micro lesson
  docs/manage/partitions/flex/create-edit-partition-flex.md
  docs/manage/partitions/flex/index.md
Labels: cla-signed

#5421 Create 2025-05-30-content.md
  blog-cse/2025-05-30-content.md
Labels: cla-signed
