Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-02, with the labels that each got.

#4929 DOCS-624 - Data setup onboarding changes
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  static/img/get-started/data-collection.png
  static/img/get-started/install-otel.png
Labels: cla-signed, do-not-merge

#4995 Dashboard information info added
  docs/dashboards/about.md
  static/img/dashboards/dashboard_info/dashboard_info.png
  static/img/dashboards/dashboard_info/dashboard_info_panel.png
Labels: cla-signed

#5029 Remove STIX from UI for threat intel beta
  docs/platform-services/threat-intelligence-indicators.md
  static/img/platform-services/threat-intelligence-add-indicators.png
Labels: doc:minor edit, cla-signed

#4549 fix the cmd for docker image
  docs/platform-services/automation-service/automation-service-integration-framework.md
  static/img/cloud-soar/integration-framework-custom-docker-image.png
  static/img/cloud-soar/integration-framework-docker-editor-2.png
  static/img/cloud-soar/integration-framework-docker-editor-3.png
  static/img/cloud-soar/integration-framework-docker-editor.png
  static/img/cloud-soar/integration-framework-test-docker-image-1.png
  static/img/cloud-soar/integration-framework-test-docker-image-2.png
  static/img/cloud-soar/integration-framework-test-docker-image-3.png
  static/img/cloud-soar/integration-framework-test-docker-image-4.png
  static/img/cloud-soar/integration-framework-test-docker-image.png
Labels: do-not-merge

#5026 Delete Elastic Load Balancing app
  cid-redirects.json
  docs/integrations/amazon-aws/elastic-load-balancing.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/product-list/product-list-a-l.md
  sidebars.ts
Labels: cla-signed

#5032 Update f5-big-ip-ltm.md
  docs/integrations/security-threat-detection/f5-big-ip-ltm.md
Labels: doc:update, cla-signed

#5030 Removed the redirect to Cloud to Cloud integration page
  docs/reuse/apps/app-collection-option-1.md
  docs/reuse/apps/app-collection-option-2.md
Labels: cla-signed

#5011 DOCS-568 - Add playbooks autosave section
  docs/platform-services/automation-service/automation-service-playbooks.md
  static/img/platform-services/automation-service/autosave-playbook-1.png
  static/img/platform-services/automation-service/autosave-playbook-2.png
  static/img/platform-services/automation-service/playbook-preferences-screen.png
  static/img/platform-services/automation-service/playbook-preferences.png
  static/img/platform-services/automation-service/playbook-publish-button.png
Labels: doc:update, cla-signed

#5039 CSOAR-2947: Updated the Doc for Aws EC2 & Any.Run
  docs/platform-services/automation-service/app-central/integrations/any.run.md
  docs/platform-services/automation-service/app-central/integrations/aws-ec2.md
Labels: cla-signed

#5040 DOCS-669 - Update "Logs for Security" section
  docs/security/additional-security-features/index.md
  docs/security/additional-security-features/introduction-to-additional-security-features.md
  docs/security/index.md
Labels: doc:update, cla-signed

#5034 code42-incydr-(Apps)
  blog-service/2025-02-04-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/code42-incydr.md
  docs/integrations/saas-cloud/index.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#4996 FAQs added with respect to Time phased budgets
  docs/manage/manage-subscription/usage-management.md
Labels: cla-signed

#5020 CSOAR-2914: CSOAR Release Notes 31-Jan-2025
  blog-csoar/2025-02-06-application-update.md
  blog-csoar/2025-02-06-content.md
Labels: cla-signed

#5008 DOCS-612 - Update suppressed lists
  docs/cse/match-lists-suppressed-lists/suppressed-lists.md
  static/img/cse/add-list-item.png
  static/img/cse/suppressed-list.png
  static/img/cse/suppressed-lists.png
  static/img/cse/suppression-slider.png
Labels: doc:update, cla-signed

#5045 Fix screenshot in tour article
  static/img/get-started/overview-new-ui.png
Labels: doc:minor edit, cla-signed

#5028 DOCS-610 - Update custom insights and network blocks
  docs/cse/administration/create-use-network-blocks.md
  docs/cse/administration/index.md
  docs/cse/get-started-with-cloud-siem/intro-for-analysts.md
  docs/cse/records-signals-entities-insights/configure-custom-insight.md
  docs/cse/records-signals-entities-insights/tags-insights-signals-entities-rules.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
  docs/get-started/training-certification-faq.md
  static/img/cse/create-network-block.png
  static/img/cse/network-block-page.png
Labels: doc:update, cla-signed

#5043 Added microlesson to the doc
  docs/send-data/opentelemetry-collector/remote-management/index.md
Labels: cla-signed

#5048 Update cse-ingestion-best-practices.md
  docs/cse/ingestion/cse-ingestion-best-practices.md
Labels: cla-signed

#5049 DOCS-680 - Update role filtering guidance on "role stacking"
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
  docs/manage/users-roles/roles/create-manage-roles.md
  docs/manage/users-roles/users/create-edit-users.md
  docs/reuse/role-stacking-tip.md
  static/img/users-roles/emulate-log-search-as-user.png
  static/img/users-roles/select-emulate-log-search.png
Labels: doc:update, cla-signed

#5042 new app+C2C flow (9 apps)
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/google/bigquery.md
  docs/integrations/saas-cloud/crowdstrike-falcon-filevantage.md
  docs/integrations/saas-cloud/kandji.md
  docs/integrations/saas-cloud/palo-alto-cortex-xdr.md
  docs/integrations/saas-cloud/symantec-web-security-service.md
  docs/integrations/saas-cloud/trend-micro-vision-one.md
  docs/integrations/saas-cloud/webex.md
  docs/integrations/security-threat-detection/carbon-black-cloud.md
  static/img/integrations/google/Google-Bigquery-Overview.png
  static/img/integrations/google/Google-Bigquery-Queries.png
  static/img/integrations/google/Google-Bigquery-Users.png
  static/img/integrations/google/Google-Bigquery-mgmt.png
Labels: doc:update, cla-signed, do-not-merge

#5052 DOCS-677 - Update the "Enterprise Audit - Cloud SIEM" article
  blog-cse/2023/12-31.md
  docs/cse/rules/insight-trainer.md
  docs/cse/troubleshoot/troubleshoot-mappers.md
  docs/cse/troubleshoot/troubleshoot-parsers.md
  docs/integrations/sumo-apps/cse.md
  static/img/integrations/sumo-apps/cloud-siem-failed-records-analysis-dashboard.png
  static/img/integrations/sumo-apps/cloud-siem-insight-explorer-dashboard.png
  static/img/integrations/sumo-apps/cloud-siem-insight-report-dashboard.png
  static/img/integrations/sumo-apps/cloud-siem-overview-dashboard.png
  static/img/integrations/sumo-apps/cloud-siem-record-parsing-and-analysis-dashboard.png
  static/img/integrations/sumo-apps/cloud-siem-rule-overview-dashboard.png
  static/img/integrations/sumo-apps/cloud-siem-security-operations-overview-dashboard.png
  static/img/integrations/sumo-apps/cloud-siem-signal-analysis-suppression.png
  static/img/integrations/sumo-apps/cloud-siem-soc-kpis.png
  static/img/integrations/sumo-apps/cloud-siem-soc-kris-dashboard.png
  static/img/integrations/sumo-apps/rules-and-mapping-changes.png
Labels: doc:update, cla-signed

#5055 Add hash to upload formats for threat intel beta
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:update, cla-signed

#5058 Homepage onboarding buttons - change links from absolute to relative
  src/pages/index.tsx
Labels: cla-signed

#5064 Add akesle to clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#4945 ST with secrets - mysql, elasticsearch, postgresql. Customer facing doc for setting secrets as env variable
  cid-redirects.json
  docs/integrations/databases/opentelemetry/postgresql-opentelemetry.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/elasticsearch/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/elasticsearch/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mysql/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mysql/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/postgresql/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/postgresql/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/st-with-secrets.md
  sidebars.ts
  static/img/send-data/opentelemetry-collector/ACL_windows_registry.png
  static/img/send-data/opentelemetry-collector/set_env_varibale_windows.png
Labels: cla-signed, do-not-merge

#5063 Update log-level.md
  docs/search/get-started-with-search/search-page/log-level.md
Labels: cla-signed, do-not-merge

#5062 CONN-4131: update lastpass doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/lastpass-source.md
  static/files/c2c/lastpass/example.json
  static/files/c2c/lastpass/example.tf
Labels: cla-signed

#5023 DOCS-639 - Playbooks text area enhancement
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/reuse/cartesian-product.md
  static/img/platform-services/automation-service/array-icon-combine.png
  static/img/platform-services/automation-service/array-icon-loop.png
  static/img/platform-services/automation-service/playbook-array-looped-example.png
  static/img/platform-services/automation-service/playbook-cartesian-product-disabled.png
  static/img/platform-services/automation-service/playbook-get-value-from-previous-action-2.png
  static/img/platform-services/automation-service/playbook-get-value-from-previous-action.png
  static/img/platform-services/automation-service/playbook-insert-placeholder-icon.png
  static/img/platform-services/automation-service/playbook-split-by.png
  static/img/platform-services/automation-service/playbook-variables-in-text-boxes.png
  static/img/platform-services/automation-service/playbooks-cartesian-product-checkbox.png
  static/img/platform-services/automation-service/playbooks-output-arrays-icons.png
Labels: doc:new, cla-signed, do-not-merge

#5070 Update example.tf
  static/files/c2c/snowflake-sql-api/example.tf
Labels: cla-signed

#5066 Legacy 404 and 301 fixes
  cid-redirects.json
Labels: cla-signed

#5071 Update hasThreatMatch in beta article for threat intel
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:update, cla-signed

#4986 Add note to update CRDs before upgrading to helm chart version 4.12.0
  docs/send-data/kubernetes/troubleshoot-collection.md
  docs/send-data/kubernetes/v4/how-to-upgrade.md
  docs/send-data/kubernetes/v4/important-changes.md
Labels: cla-signed

#5074 Minor reorganization of the steps to install otel CRDs
  docs/send-data/kubernetes/v4/how-to-upgrade.md
  docs/send-data/kubernetes/v4/important-changes.md
Labels: cla-signed

#5072 Copilot UI updates
  docs/search/copilot.md
  static/img/search/copilot/chart-types.png
  static/img/search/copilot/classic-ui-tab.png
  static/img/search/copilot/cloud-siem-1.png
  static/img/search/copilot/cloud-siem-2.png
  static/img/search/copilot/cloud-siem-3.png
  static/img/search/copilot/cloud-siem-4.png
  static/img/search/copilot/copilot-cloud-siem-1.png
  static/img/search/copilot/copilot-geo-chart.png
  static/img/search/copilot/copilot-tab.png
  static/img/search/copilot/geo-chart.png
  static/img/search/copilot/left-nav.png
  static/img/search/copilot/open-in-log-search1.png
  static/img/search/copilot/open-in-log-search2.png
  static/img/search/copilot/periods-query-syntax.gif
  static/img/search/copilot/resume-convo-history2.png
  static/img/search/copilot/source-category.png
Labels: cla-signed, hot🔥

#5031 Restructure Manage folder
  blog-service/2021/12-31.md
  blog-service/2022/12-31.md
  blog-service/2024/12-31.md
  blog-service/2025-01-30-manage.md
  cid-redirects.json
  docs/api/account-management.md
  docs/api/organizations-management.md
  docs/contributing/glossary.md
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/cse/get-started-with-cloud-siem/onboarding-checklist-cse.md
  docs/get-started/sign-up.md
  docs/integrations/amazon-aws/cloudfront.md
  docs/integrations/amazon-aws/cloudtrail.md
  docs/integrations/amazon-aws/s3-audit.md
  docs/integrations/saml/onelogin.md
  docs/manage/manage-subscription/cloud-flex-legacy-accounts.md
  docs/manage/manage-subscription/create-and-manage-orgs/create-manage-orgs-flex.md
  docs/manage/manage-subscription/create-and-manage-orgs/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-and-manage-orgs/create-manage-orgs.md
  docs/manage/manage-subscription/create-and-manage-orgs/index.md
  docs/manage/manage-subscription/create-and-manage-orgs/manage-org-settings.md
  docs/manage/manage-subscription/index.md
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
  docs/manage/manage-subscription/upgrade-account/index.md
  docs/manage/manage-subscription/upgrade-account/upgrade-cloud-flex-legacy-account.md
  docs/manage/manage-subscription/upgrade-account/upgrade-sumo-logic-credits-account.md
  docs/manage/security/saml/integrate-google-iam-service.md
  docs/manage/security/saml/integrate-onelogin.md
  docs/manage/security/saml/integrate-sumo-with-azure-ad.md
  docs/manage/security/saml/integrate-with-bitium.md
  docs/manage/security/saml/set-up-saml.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/manage/users-roles/users/delete-user.md
  docs/manage/users-roles/users/multi-account-access.md
  docs/manage/users-roles/users/reset-user-password.md
  docs/manage/users-roles/users/unlock-user-account.md
  sidebars.ts
Labels: cla-signed

#5076 AWSO - Added common troubleshooting error for
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#5079 Create 2025-02-14-content.md
  blog-cse/2025-02-14-content.md
Labels: cla-signed

#5075 Kickstart Data 7-day limit
  docs/get-started/quickstart.md
Labels: cla-signed

#5077 Change date on release note for RBAC for Indexes
  blog-service/2024/12-31.md
Labels: doc:minor edit, cla-signed

#5078 DOCS-688 - Update cert file location
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
  docs/send-data/hosted-collectors/cloud-syslog-source/rsyslog.md
  docs/send-data/hosted-collectors/cloud-syslog-source/syslog-ng.md
Labels: doc:minor edit, cla-signed

#5082 Add meta tag for Bing site verification
  docusaurus.config.js
Labels: doc:site tech, cla-signed

#5068 Updated billing pages info
  blog-service/2021/12-31.md
  blog-service/2022/12-31.md
  cid-redirects.json
  docs/get-started/sign-up.md
  docs/manage/manage-subscription/manage-billing-information.md
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
  docs/manage/manage-subscription/upgrade-account/index.md
  docs/manage/manage-subscription/upgrade-account/upgrade-credits-account.md
  docs/manage/manage-subscription/upgrade-account/upgrade-sumo-logic-flex-account.md
  sidebars.ts
  static/img/manage/subscriptions/change-payment-method.png
  static/img/manage/subscriptions/update-payment-details.png
  static/img/manage/subscriptions/upgrade-free-to-essentials-credits.png
Labels: cla-signed, do-not-merge

#5036 DOCS-674 - Static log monitor frequency evaluation
  cid-redirects.json
  docs/alerts/monitors/create-monitor.md
  docs/alerts/monitors/overview.md
  static/img/alerts/monitors/config-resolution-window-logs.png
  static/img/alerts/monitors/config-resolution-window-metrics.png
  static/img/alerts/monitors/logs-static-missing.png
  static/img/alerts/monitors/logs-trigger-type.png
  static/img/alerts/monitors/setup-logs.png
  static/img/alerts/monitors/show-estimated-scan.png
Labels: cla-signed, do-not-merge

#5037 Sysdig Secure Source (c2c Collector)
  blog-service/2025-02-18-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/sysdig-secure-source.md
  sidebars.ts
  static/files/c2c/sysdig-secure/example.json
  static/files/c2c/sysdig-secure/example.tf
Labels: doc:new, cla-signed, do-not-merge

#5060 Collector v19.525-1 release notes
  blog-collector/2024/2025-02-18.md
Labels: cla-signed, do-not-merge

#5053 Update index.md
  docs/send-data/hosted-collectors/http-source/logs-metrics/index.md
Labels: cla-signed

#5054 Trust Login (Apps)
  blog-service/2025-02-14-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/trust-login.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5083 Dragos app document
  blog-service/2025-02-18-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/dragos.md
  docs/integrations/saas-cloud/index.md
  docs/reuse/apps/collection-configuration.md
  sidebars.ts
Labels: do-not-merge

#5085 Update .clabot
  .clabot
Labels: cla-signed

#5086 DOCS-695 - Update search URL article
  docs/search/get-started-with-search/build-search/use-url-to-run-search.md
Labels: doc:update, cla-signed

#5089 Legacy 301s and 404s
  cid-redirects.json
Labels: cla-signed

#5050 Otel Collector tags information added
  docs/send-data/opentelemetry-collector/remote-management/source-templates/manage-source-templates.md
  static/img/send-data/add-delete-update-tags.png
  static/img/send-data/collector-tags-edit.png
  static/img/send-data/confirm-the-tags.png
  static/img/send-data/mapped-source-templates.png
  static/img/send-data/opentelemetry-collection.png
  static/img/send-data/update-tags-click-here.png
Labels: cla-signed

#5090 DOCS-700 - Update multi-account access article
  docs/manage/manage-subscription/create-and-manage-orgs/manage-org-settings.md
  docs/manage/users-roles/users/multi-account-access.md
  static/img/users-roles/multi-account-access-dropdown.png
Labels: doc:update, cla-signed

#5093 DOCS-702 - Update inventory data search information
  docs/cse/administration/inventory-sources-and-data.md
  docs/cse/records-signals-entities-insights/search-cse-records-in-sumo.md
Labels: doc:update, cla-signed

#5095 Update audit.md
  docs/integrations/microsoft-azure/audit.md
Labels: cla-signed

#5094 Update active-directory-azure.md
  docs/integrations/microsoft-azure/active-directory-azure.md
  static/img/integrations/microsoft-azure/diagnostic-setting.png
Labels: cla-signed

#5096 Create 2025-02-20-content.md
  blog-cse/2025-02-20-content.md
Labels: cla-signed

#5097 Add note about Index Access feature
  docs/manage/users-roles/roles/create-manage-roles.md
Labels: doc:minor edit, cla-signed

#5081 DOCS-611 - Add SSO content for organizations
  blog-service/2025-02-21-manage.md
  docs/api/organizations-management.md
  docs/manage/manage-subscription/create-and-manage-orgs/manage-org-settings.md
  docs/manage/security/set-max-web-session-timeout.md
  static/img/manage/subscriptions/enable-sso-button.png
  static/img/manage/subscriptions/mssp-login-with-parent-org.png
  static/img/manage/subscriptions/mssp-sso-enabled.png
  static/img/manage/subscriptions/no-subdomain-defined.png
  static/img/manage/subscriptions/subdomain-and-sso-enabled.png
Labels: doc:new, cla-signed, do-not-merge

#5069 Added new action related to Identity Protection
  docs/platform-services/automation-service/app-central/integrations/crowdstrike-falcon.md
Labels: cla-signed

#5100 Allow Berry widget to expand wider
  src/pages/index.tsx
Labels: cla-signed

#5092 Add the missing ST docs cards in the index page
  docs/send-data/opentelemetry-collector/remote-management/source-templates/elasticsearch/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/postgresql/index.md
Labels: cla-signed

#5105 DOCS-639 - Release note for dynamic array handling
  blog-csoar/2025-02-24-application-update.md
Labels: doc:new, cla-signed

#5106 Revert "Update mimecast-source.md (#4510)"
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/mimecast-source.md
  static/files/c2c/mimecast/example.json
  static/files/c2c/mimecast/example.tf
Labels: cla-signed

#5099 CONN-4195: rename app "microsoft defender for cloud" to "azure security defender for cloud"
  blog-service/2024/12-31.md
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-security-defender-for-cloud.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/product-list/product-list-m-z.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#5109 Onboarding - Option to explore App Catalog
  blog-service/2025-02-25-apps.md
  docs/get-started/sign-up.md
  static/img/get-started/data-onboarding.png
Labels: cla-signed, do-not-merge

#5107 CONN-4169 Add docs for new Bitwarden integration
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/bitwarden.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/bitwarden/example.json
  static/files/c2c/bitwarden/example.tf
  static/img/integrations/security-threat-detection/bitwarden.png
Labels: cla-signed

#5111 Fixed the data format across docs
  docs/search/search-cheat-sheets/log-operators.md
  docs/search/search-query-language/search-operators/now.md
Labels: cla-signed

#5017 added docs changes for Apache, Apache Tomcat, Haproxy, IIS-10, Nginx, Nginx Ingress, Nginx Plus and Nginx Plus Ingress
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx-plus-ingress.md
  docs/integrations/web-servers/nginx-plus.md
  docs/integrations/web-servers/nginx.md
Labels: cla-signed

#5115 Add CIDs for Cloud SIEM rules articles
  cid-redirects.json
Labels: doc:minor edit, cla-signed

#5101 Azure Container Instances document
  blog-service/2025-02-27-apps.md
  cid-redirects.json
  docs/integrations/microsoft-azure/azure-container-instances.md
  docs/integrations/microsoft-azure/index.md
  sidebars.ts
  static/img/integrations/microsoft-azure/azure-container-instance-namespaces.png
  static/img/integrations/microsoft-azure/azure-container-instances.png
Labels: cla-signed

#5114 Load balancer app docs update
  docs/integrations/amazon-aws/application-load-balancer.md
  docs/integrations/amazon-aws/classic-load-balancer.md
  docs/integrations/amazon-aws/network-load-balancer.md
  docs/reuse/apps/create-aws-s3-source.md
Labels: cla-signed

#5035 DOCS-637 - Content management for MSSPs - Beta
  cid-redirects.json
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/manage/manage-subscription/create-and-manage-orgs/index.md
  docs/manage/manage-subscription/create-and-manage-orgs/manage-org-settings.md
  docs/manage/manage-subscription/create-and-manage-orgs/manage-orgs-for-mssps.md
  sidebars.ts
  static/img/manage/subscriptions/mssp-orgs-selected-organizations.png
  static/img/manage/subscriptions/mssp-orgs-sync-associated-rules.png
  static/img/manage/subscriptions/mssp-orgs-sync-selected-items-2.png
  static/img/manage/subscriptions/mssp-orgs-sync-selected-items.png
  static/img/manage/subscriptions/mssp-view-history-query-results.png
  static/img/manage/subscriptions/mssp-view-history-query.png
  static/img/manage/subscriptions/search-button.png
Labels: doc:new, cla-signed

#5121 DOCS-SUMO-248716 - Update search filter limitations
  docs/manage/users-roles/roles/construct-search-filter-for-role.md
Labels: doc:minor edit, cla-signed

#5113 Updated the search query with correct syntax
  docs/cse/troubleshoot/troubleshoot-parsers.md
  docs/integrations/saas-cloud/citrix-cloud.md
  docs/manage/field-extractions/fer-templates/cisco-fwsm-fer.md
  docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
  docs/manage/partitions/data-tiers/create-edit-partition.md
  docs/manage/partitions/flex/create-edit-partition-flex.md
  docs/search/get-started-with-search/build-search/keyword-search-expressions.md
  docs/search/optimize-search-partitions.md
  docs/search/optimize-search-performance.md
  docs/search/search-cheat-sheets/log-operators.md
  docs/search/search-query-language/search-operators/lookup.md
  docs/send-data/collect-from-other-data-sources/docker-collection-methods.md
  docs/send-data/collection/search-collector-or-source.md
Labels: cla-signed

#5128 February Release Note (apps)
  blog-service/2025-02-28-apps.md
Labels: doc:new, cla-signed, do-not-merge

#5104 CONN-4232: Added docs code for Cyberark Audit C2C source
  blog-service/2025-02-27-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-audit-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/cyberark-audit/example.json
  static/files/c2c/cyberark-audit/example.tf
Labels: cla-signed, do-not-merge

#5129 DOCS-611 - Add "Limitations" section for SSO
  docs/manage/manage-subscription/create-and-manage-orgs/manage-org-settings.md
Labels: doc:update, cla-signed
