Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-08, with the labels that each got.

#5631 DOCS-1021 - DigiCert and ACM certificate migration for Cloud Syslog Source
  blog-service/2025-08-01-collection.md
  docs/integrations/saas-cloud/acquia.md
  docs/send-data/collect-from-other-data-sources/collect-logs-sentinelone.md
  docs/send-data/hosted-collectors/cloud-syslog-source/index.md
  docs/send-data/hosted-collectors/cloud-syslog-source/rsyslog.md
  docs/send-data/hosted-collectors/cloud-syslog-source/syslog-ng.md
Labels: doc:update, cla-signed, do-not-merge

#5635 DOCS-1032 - Fix feature comparison table icons
  cid-redirects.json
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/cloud-soar/compared-to-automation-service.md
  docs/get-started/sumo-logic-ui-classic.md
  docs/manage/manage-subscription/cloud-flex-legacy-accounts.md
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/manage/manage-subscription/sumo-logic-credits-accounts.md
  docs/manage/manage-subscription/sumo-logic-flex-accounts.md
  docs/manage/partitions/data-tiers/index.md
  docs/manage/partitions/flex/index.md
  docs/reuse/alert-variables.md
  docs/security/index.md
  docs/send-data/collect-from-other-data-sources/docker-collection-methods.md
  docs/send-data/collect-from-other-data-sources/kubernetes-fluentd-plugin.md
  i18n/ja/alerts/alerts/alert-variables.md
  static/img/reuse/check.png
  static/img/reuse/x.png
Labels: cla-signed

#5611 DOCS-1006 - SEO improvements (lengthen metadata descriptions, fix H1s)
  docs/alerts/index.md
  docs/alerts/webhook-connections/set-up-webhook-connections.md
  docs/api/index.md
  docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/traceid-spanid-injection-into-logs-configuration.md
  docs/cse/records-signals-entities-insights/index.md
  docs/cse/troubleshoot/troubleshoot-parsers.md
  docs/dashboards/filter-template-variables.md
  docs/dashboards/panels/column-charts.md
  docs/get-started/system-requirements.md
  docs/get-started/training-certification-faq.md
  docs/integrations/google/cloud-interconnect.md
  docs/integrations/index.md
  docs/integrations/microsoft-azure/index.md
  docs/integrations/webhooks/firefly.md
  docs/manage/data-forwarding/index.md
  docs/manage/fields.md
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/manage/security/audit-indexes/index.md
  docs/manage/security/enable-support-account.md
  docs/manage/security/saml/set-up-saml.md
  docs/search/get-started-with-search/build-search/search-syntax.md
  docs/search/get-started-with-search/search-basics/export-search-results.md
  docs/search/index.md
  docs/search/lookup-tables/create-lookup-table.md
  docs/search/lookup-tables/index.md
  docs/search/search-cheat-sheets/index.md
  docs/search/search-query-language/field-expressions.md
  docs/search/search-query-language/group-aggregate-operators/count-count-distinct-and-count-frequent.md
  docs/search/search-query-language/group-aggregate-operators/index.md
  docs/search/search-query-language/group-aggregate-operators/sum.md
  docs/search/search-query-language/index.md
  docs/search/search-query-language/parse-operators/index.md
  docs/search/search-query-language/parse-operators/parse-json-formatted-logs.md
  docs/search/search-query-language/search-operators/where.md
  docs/security/threat-intelligence/find-threats.md
  docs/send-data/choose-collector-source.md
  docs/send-data/index.md
  docs/send-data/installed-collectors/index.md
  docs/send-data/installed-collectors/linux.md
  docs/send-data/installed-collectors/sources/local-windows-event-log-source.md
  docs/send-data/installed-collectors/sources/syslog-source.md
  docs/send-data/installed-collectors/windows.md
  docs/send-data/opentelemetry-collector/install-collector/windows.md
  docs/send-data/use-json-configure-sources/index.md
  docusaurus.config.js
  src/pages/index.tsx
Labels: cla-signed

#5652 Update aws-kinesis-firehose-logs-source.md
  docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-logs-source.md
Labels: cla-signed

#5644 AWS Security Hub - OCSF app doc
  blog-service/2025-08-04-apps.md
  cid-redirects.json
  docs/integrations/cloud-security-monitoring-analytics/aws-security-hub-ocsf.md
  docs/integrations/cloud-security-monitoring-analytics/index.md
  docs/integrations/product-list/product-list-a-l.md
  sidebars.ts
Labels: cla-signed

#5659 Add more global metadata tags to improve SEO
  docusaurus.config.js
  src/pages/index.tsx
Labels: cla-signed

#5660 Sentry: Trimmed log samples to make them more suitable for search engine caching
  docs/integrations/webhooks/sentry.md
Labels: cla-signed

#5670 Update GitHub Copilot Source Doc
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/github-copilot-source.md
  static/img/send-data/github_copilot.png
Labels: cla-signed

#5669 added Troubleshooting section for Azure VM
  docs/integrations/microsoft-azure/azure-virtual-machine.md
  docs/integrations/microsoft-azure/azure-virtual-network.md
Labels: cla-signed

#5664 AWS IAM Users (c2c)
  blog-service/2025-08-07-collection.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/aws-iam-users-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/aws-iam-users/example.json
  static/files/c2c/aws-iam-users/example.tf
  static/img/send-data/aws-iam-users.png
Labels: doc:new, cla-signed, do-not-merge

#5673 Update aws-iam-users-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/aws-iam-users-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/onelogin-source.md
Labels: cla-signed

#5662 CONN-5025: Add param for time value format
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/universal-connector-source.md
Labels: cla-signed

#5676 Add naveenrama to the cla file
  .clabot
Labels: doc:minor edit, cla-signed

#5682 DOCS-1068 - Resource Cloud SIEM entity type
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/cse/get-started-with-cloud-siem/insight-generation-process.md
  docs/cse/records-signals-entities-insights/view-manage-entities.md
Labels: cla-signed

#5683 Add blog links
  docs/cloud-soar/incidents-triage.md
  docs/cloud-soar/introduction.md
  docs/cse/administration/mitre-coverage.md
  docs/cse/automation/about-automation-service-and-cloud-siem.md
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
  docs/cse/get-started-with-cloud-siem/cse-heads-up-display.md
  docs/cse/get-started-with-cloud-siem/intro-for-administrators.md
  docs/cse/get-started-with-cloud-siem/intro-for-analysts.md
  docs/cse/records-signals-entities-insights/create-an-entity-group.md
  docs/cse/rules/insight-trainer.md
  docs/cse/rules/rule-tuning-expressions.md
  docs/cse/rules/write-first-seen-rule.md
  docs/cse/rules/write-outlier-rule.md
  docs/cse/schema/username-and-hostname-normalization.md
  docs/platform-services/automation-service/integration-framework/about-integration-framework.md
  docs/security/additional-security-features/audit-and-compliance.md
  docs/security/additional-security-features/introduction-to-additional-security-features.md
  docs/security/index.md
  docs/security/threat-intelligence/about-threat-intelligence.md
Labels: doc:update, cla-signed

#5677 DOCS-1062 - Update "Disabled Metrics Sources" article
  docs/cse/rules/write-first-seen-rule.md
  docs/metrics/manage-metric-volume/disabled-metrics-sources.md
Labels: doc:update, cla-signed

#5675 Deprecating GIS for K8s - Update index.md
  cid-redirects.json
  docs/integrations/global-intelligence/index.md
  docs/integrations/global-intelligence/kubernetes-devops.md
  docs/integrations/product-list/product-list-a-l.md
  docs/observability/kubernetes/apps.md
  sidebars.ts
Labels: cla-signed

#5679 CSOAR-3716: One drive integration credential requirement
  docs/platform-services/automation-service/app-central/integrations/microsoft-onedrive.md
Labels: cla-signed

#5684 CSOAR-3657: Updated doc for hatching triage
  docs/platform-services/automation-service/app-central/integrations/hatching-triage.md
Labels: cla-signed

#5694 Issue 5690 - JFrog Artifactory traffic log property
  docs/integrations/app-development/jfrog-artifactory.md
Labels: doc:minor edit, cla-signed

#5697 DOCS-1016 - Suggested edits
  docs/api/about-apis/intro-to-apis.md
  static/img/api/add-access-key-dialog.png
  static/img/api/collector-sources.png
  static/img/api/imported-api.png
  static/img/api/postman-ui.png
  static/img/api/user-record.png
Labels: cla-signed

#5692 Update download-collector-from-static-url.md
  docs/send-data/installed-collectors/collector-installation-reference/download-collector-from-static-url.md
Labels: cla-signed

#5701 Vectra app doc
  blog-service/2025-08-20-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/vectra.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#5705 Create 2025-08-19-content.md
  blog-cse/2025-08-20-content.md
Labels: cla-signed

#5699 Extrahop RevealX 360 app doc
  blog-service/2025-08-20-apps-extrahop.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/webhooks/extrahop-revealx-360.md
  sidebars.ts
  static/img/send-data/extrahop-revealx-360-icon.png
Labels: cla-signed, do-not-merge

#5627 DOCS-1015 - Add Automation Service course as a new article
  docs/platform-services/automation-service/automation-service-playbooks.md
  docs/platform-services/automation-service/index.md
  docs/platform-services/automation-service/intro-to-automation-service.md
  sidebars.ts
  static/img/cse/automations-new-playbook-button.png
  static/img/cse/automations-new-playbook-dialog.png
  static/img/platform-services/automation-service/intro-add-automated-playbook.png
  static/img/platform-services/automation-service/intro-add-entity-enrichment-node.png
  static/img/platform-services/automation-service/intro-add-new-node.png
  static/img/platform-services/automation-service/intro-add-node.png
  static/img/platform-services/automation-service/intro-alert-node.png
  static/img/platform-services/automation-service/intro-alerts-playbook.png
  static/img/platform-services/automation-service/intro-app-central.png
  static/img/platform-services/automation-service/intro-completed-playbook.png
  static/img/platform-services/automation-service/intro-condition.png
  static/img/platform-services/automation-service/intro-edit-button.png
  static/img/platform-services/automation-service/intro-edit-node-alert.png
  static/img/platform-services/automation-service/intro-explore-ui-installed-integrations.png
  static/img/platform-services/automation-service/intro-explore-ui-integrations.png
  static/img/platform-services/automation-service/intro-find-high-severity-insights.png
  static/img/platform-services/automation-service/intro-get-virus-total-node.png
  static/img/platform-services/automation-service/intro-integrations.png
  static/img/platform-services/automation-service/intro-new-automation.png
  static/img/platform-services/automation-service/intro-notification-box.png
  static/img/platform-services/automation-service/intro-notification-email.png
  static/img/platform-services/automation-service/intro-params.png
  static/img/platform-services/automation-service/intro-playbook-results.png
  static/img/platform-services/automation-service/intro-playbook-view-of-results.png
  static/img/platform-services/automation-service/intro-reboot-instances-node.png
  static/img/platform-services/automation-service/intro-resolve-alert-node.png
  static/img/platform-services/automation-service/intro-results-of-automation.png
  static/img/platform-services/automation-service/intro-select-automation.png
  static/img/platform-services/automation-service/intro-start-node.png
  static/img/platform-services/automation-service/intro-test-playbook-email-2.png
  static/img/platform-services/automation-service/intro-test-playbook-email.png
  static/img/platform-services/automation-service/intro-test-playbook-results.png
  static/img/platform-services/automation-service/intro-test-playbook.png
Labels: doc:new, cla-signed

#5628 Partition and SV limitation enhanced (hyphen)
  docs/manage/partitions/data-tiers/create-edit-partition.md
  docs/manage/partitions/flex/create-edit-partition-flex.md
  docs/manage/partitions/index.md
  docs/manage/scheduled-views/add-scheduled-view.md
Labels: cla-signed

#5711 Update aws-iam-users-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/aws-iam-users-source.md
Labels: cla-signed

#5636 CSOAR-3364: Added IAM related change logs in AWS integrations
  docs/platform-services/automation-service/app-central/integrations/aws-athena.md
  docs/platform-services/automation-service/app-central/integrations/aws-cloudfront.md
  docs/platform-services/automation-service/app-central/integrations/aws-ec2.md
  docs/platform-services/automation-service/app-central/integrations/aws-inspector.md
  docs/platform-services/automation-service/app-central/integrations/aws-private-certificate-authority.md
Labels: cla-signed

#5716 Add fguimond to CLA
  .clabot
Labels: cla-signed

#5715 Add Kubernetes Collection Helm incompatibility warning
  docs/send-data/kubernetes/install-helm-chart.md
  docs/send-data/kubernetes/troubleshoot-collection.md
Labels: cla-signed

#5718 Update log-tracing-data-volume-index.md
  docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
Labels: cla-signed

#5722 DOCS-1092 - Remove forbidden characters from CID file
  cid-redirects.json
Labels: doc:update, cla-signed

#5702 Adding changelog entry for windows ST 8.0.0 release and adding a note…
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/changelog.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/index.md
Labels: cla-signed

#5712 SUMO-268804: Otel Collector monitoring App - Documentation
  blog-service/2025-08-26-apps.md
  cid-redirects.json
  docs/integrations/hosts-operating-systems/opentelemetry/index.md
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/sumo-apps/index.md
  docs/integrations/sumo-apps/opentelemetry-collector-insights.md
  sidebars.ts
Labels: cla-signed

#5724 Create 2025-08-27-content.md
  blog-cse/2025-08-27-content.md
Labels: cla-signed

#5727 CSOAR-3802: Updated doc to add details of auotmation bridge.
  docs/platform-services/automation-service/app-central/integrations/aws-athena.md
  docs/platform-services/automation-service/app-central/integrations/aws-cloudfront.md
  docs/platform-services/automation-service/app-central/integrations/aws-ec2.md
  docs/platform-services/automation-service/app-central/integrations/aws-inspector.md
  docs/platform-services/automation-service/app-central/integrations/aws-private-certificate-authority.md
Labels: cla-signed

#5729 DOCS-1069 - Triage automation
  docs/cloud-soar/incidents-triage.md
  static/img/cloud-soar/triage-add-action.png
  static/img/cloud-soar/triage-automation-rule.png
  static/img/cloud-soar/triage-custom-playbook-type.png
Labels: doc:new, cla-signed

#5726 CSOAR-3689: AWS Security Hub Integration: Reformat user message.
  docs/platform-services/automation-service/app-central/integrations/aws-security-hub.md
Labels: cla-signed

#5728 CSOAR-3801: Update AWS integration doc related to bridge information.
  docs/platform-services/automation-service/app-central/integrations/aws-cloudtrail.md
  docs/platform-services/automation-service/app-central/integrations/aws-route53.md
  docs/platform-services/automation-service/app-central/integrations/aws-s3.md
  docs/platform-services/automation-service/app-central/integrations/aws-simple-notification-service.md
  docs/platform-services/automation-service/app-central/integrations/aws-sqs.md
  docs/reuse/automation-service/aws/iam-role.md
  static/img/platform-services/automation-service/app-central/integrations/aws/aws-cloudtrail-configuration.png
  static/img/platform-services/automation-service/app-central/integrations/aws/aws-route53-configuration.png
  static/img/platform-services/automation-service/app-central/integrations/aws/aws-s3-configuration.png
  static/img/platform-services/automation-service/app-central/integrations/aws/aws-simple-notification-service-configuration.png
  static/img/platform-services/automation-service/app-central/integrations/aws/aws-sqs-configuration.png
Labels: cla-signed

#5731 CSOAR-3714: Updated Zscaler doc
  docs/platform-services/automation-service/app-central/integrations/zscaler.md
Labels: cla-signed

#5734 Zimperium (apps)
  blog-service/2025-08-29-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/zimperium.md
  sidebars.ts
  static/img/integrations/zimperium/add-data-export-config.png
  static/img/integrations/zimperium/zimperium-logo.png
Labels: doc:new, cla-signed, do-not-merge

#5735 August Release Note (apps)
  blog-service/2025-08-31-apps.md
Labels: doc:new, cla-signed

#5737 Copilot-to-Mobot rebranding
  blog-service/2024/12-31.md
  blog-service/2025-03-03-copilot-search.md
  blog-service/2025-08-31-apps.md
  cid-redirects.json
  docs/alerts/monitors/alert-response.md
  docs/get-started/ai-machine-learning.md
  docs/search/copilot-multiturn-beta.md
  docs/search/copilot-unstructured-logs-beta.md
  docs/search/copilot.md
  docs/search/get-started-with-search/build-search/intelliparse-beta.md
  docs/search/index.md
  docs/search/mobot-multiturn-beta.md
  docs/search/mobot-unstructured-logs-beta.md
  docs/search/mobot.md
  docs/search/query-assist.md
  sidebars.ts
  static/img/search/mobot/chart-types.png
  static/img/search/mobot/classic-ui-tab.png
  static/img/search/mobot/cloud-siem-1.png
  static/img/search/mobot/cloud-siem-2.png
  static/img/search/mobot/cloud-siem-3.png
  static/img/search/mobot/cloud-siem-4.png
  static/img/search/mobot/code-editor.png
  static/img/search/mobot/drill-causes.png
  static/img/search/mobot/feedback-error.png
  static/img/search/mobot/feedback-thumbs.png
  static/img/search/mobot/geo-chart.png
  static/img/search/mobot/history.png
  static/img/search/mobot/initial-question.png
  static/img/search/mobot/json.png
  static/img/search/mobot/left-nav.png
  static/img/search/mobot/manual-entry.png
  static/img/search/mobot/narrow-scope-filter.png
  static/img/search/mobot/narrow-scope.png
  static/img/search/mobot/new-conversation.png
  static/img/search/mobot/open-in-log-search1.png
  static/img/search/mobot/open-in-log-search2.png
  static/img/search/mobot/periods-query-syntax.gif
  static/img/search/mobot/play.png
  static/img/search/mobot/resume-convo-history1.png
  static/img/search/mobot/resume-convo-history2.png
  static/img/search/mobot/search-button.png
  static/img/search/mobot/show-hide-query.png
  static/img/search/mobot/source-category.png
  static/img/search/mobot/suggestions.png
  static/img/search/mobot/time-period.png
  static/img/search/mobot/trend-over-time.png
Labels: cla-signed
