Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-01, with the labels that each got.

#4910 On-prem SOAR end-of-life release note
  blog-csoar/2024-12-31-application-update.md
Labels: doc:new, cla-signed

#4918 Add darshan-sumo to cla file
  .clabot
Labels: doc:minor edit, cla-signed

#4920 Make the same statement between TAXII 1 and 2
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/stix-taxii-1-client-source.md
Labels: cla-signed

#4914 Migrating from ARM based Azure Monitor Logs Collection doc updated
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/azure-event-hubs-source-migration.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/ms-azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
Labels: cla-signed

#4916 2024 Archive Collector Release notes
  blog-collector/2024-01-25.md
  blog-collector/2024-03-07.md
  blog-collector/2024-03-18.md
  blog-collector/2024-07-03.md
  blog-collector/2024-08-23.md
  blog-collector/2024-10-31.md
  blog-collector/2024-11-26.md
  blog-collector/2024/12-31.md
Labels: cla-signed

#4921 Archive 2024 Cloud SIEM and Cloud SOAR release notes
  blog-cse/2022/12-31.md
  blog-cse/2023/12-31.md
  blog-cse/2024-01-12-content.md
  blog-cse/2024-01-30-content.md
  blog-cse/2024-02-02-content.md
  blog-cse/2024-02-13-content.md
  blog-cse/2024-02-19-application-update.md
  blog-cse/2024-02-19-content.md
  blog-cse/2024-02-23-content.md
  blog-cse/2024-03-11-content.md
  blog-cse/2024-03-21-content.md
  blog-cse/2024-03-22-application-update.md
  blog-cse/2024-03-28-content.md
  blog-cse/2024-04-05-content.md
  blog-cse/2024-04-11-application-update.md
  blog-cse/2024-05-02-content.md
  blog-cse/2024-05-15-application-update.md
  blog-cse/2024-05-15-content.md
  blog-cse/2024-05-23-content.md
  blog-cse/2024-05-30-application-update.md
  blog-cse/2024-05-30-content.md
  blog-cse/2024-07-03-content.md
  blog-cse/2024-07-16-content.md
  blog-cse/2024-08-05-content.md
  blog-cse/2024-08-16-content.md
  blog-cse/2024-08-23-content.md
  blog-cse/2024-08-27-content.md
  blog-cse/2024-09-19-content.md
  blog-cse/2024-10-04-content.md
  blog-cse/2024-10-31-content.md
  blog-cse/2024-11-07-content.md
  blog-cse/2024-11-08-application-update.md
  blog-cse/2024-11-22-content.md
  blog-cse/2024-12-06-content.md
  blog-cse/2024-12-20-content.md
  blog-cse/2024/12-31.md
  blog-csoar/2023/12-31.md
  blog-csoar/2024-01-03-application-update.md
  blog-csoar/2024-01-08-content.md
  blog-csoar/2024-01-25-content.md
  blog-csoar/2024-01-30-application-update.md
  blog-csoar/2024-02-06-application-update.md
  blog-csoar/2024-02-19-application-update.md
  blog-csoar/2024-02-27-content.md
  blog-csoar/2024-03-12-application-update.md
  blog-csoar/2024-03-12-content.md
  blog-csoar/2024-03-21-content.md
  blog-csoar/2024-03-26-application-update.md
  blog-csoar/2024-04-09-application-update.md
  blog-csoar/2024-04-18-content.md
  blog-csoar/2024-04-23-application-update.md
  blog-csoar/2024-06-05-application-update.md
  blog-csoar/2024-06-05-content.md
  blog-csoar/2024-07-17-application-update.md
  blog-csoar/2024-11-15-application-update.md
  blog-csoar/2024-11-20-content.md
  blog-csoar/2024-12-31-application-update.md
  blog-csoar/2024/12-31.md
Labels: doc:update, cla-signed

#4923 CSOAR Release Note 03/01/2025
  blog-csoar/2025-01-03-application-update.md
  blog-csoar/2025-01-03-content.md
  docs/platform-services/automation-service/app-central/integrations/google-chat.md
Labels: cla-signed

#4922 Azure AD
  docs/platform-services/automation-service/app-central/integrations/azure-ad.md
Labels: cla-signed

#4927 Upgrade Docusaurus 3.7.0 and React 19.0.0
  package.json
  yarn.lock
Labels: doc:site tech, cla-signed

#4926 DOCS-621 - Add caveats about suppressed lists
  docs/cse/match-lists-suppressed-lists/suppressed-lists.md
Labels: doc:update, cla-signed

#4925 Add ZeroFox to threat intel beta article
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#4931 Add mahendrak-sumo to clabot file
  .clabot
Labels: doc:minor edit, cla-signed

#4913 CONN-4000: Trend micro vision one app doc
  blog-service/2025-01-06-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/trend-micro-vision-one.md
  sidebars.ts
  static/img/send-data/trend-micro-vision-one.png
Labels: cla-signed

#4928 Docusaurus Faster installation
  LICENSE
  docs/api/getting-started.md
  docs/api/organizations-management.md
  docs/integrations/amazon-aws/aws-privatelink.md
  docs/integrations/amazon-aws/global-intelligence-cloudtrail-secops.md
  docs/integrations/amazon-aws/lambda.md
  docs/integrations/app-development/jfrog-artifactory.md
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/containers-orchestration/docker-ulm.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/postgresql.md
  docs/integrations/google/workspace/collect-logs-legacy.md
  docs/integrations/google/workspace/index.md
  docs/integrations/security-threat-detection/threat-intel-quick-analysis.md
  docs/integrations/web-servers/apache.md
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/automatic-installation-script.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cybereason-source.md
  docs/send-data/opentelemetry-collector/quickstart.md
  docusaurus.config.js
  package.json
  yarn.lock
Labels: doc:site tech, cla-signed

#4656 CrowdStrike Threat Intel C2C Source
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/platform-services/threat-intelligence-indicators.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-threat-intel-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  sidebars.ts
  static/files/c2c/crowdstrike-threat-intel/example.json
  static/files/c2c/crowdstrike-threat-intel/example.tf
Labels: cla-signed, do-not-merge

#4899 Update Field Browser index page
  docs/search/get-started-with-search/search-page/field-browser/index.md
  static/img/search/get-started-search/search-page/FB-Field-Browser-Display-Fields.png
Labels: cla-signed

#4935 Update how-to-upgrade.md
  docs/send-data/kubernetes/v4/how-to-upgrade.md
Labels: cla-signed

#4855 Sumo Trial/account sign-up updates
  docs/get-started/sign-up.md
  static/img/get-started/aws_marketplace_cancel.png
  static/img/get-started/aws_marketplace_create_contract.png
  static/img/get-started/aws_marketplace_new.png
  static/img/get-started/aws_marketplace_setup_new.png
  static/img/get-started/aws_marketplace_view_purchase_options.png
Labels: cla-signed

#4937 Fix ZeroFox logo
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zerofox-intel-source.md
Labels: doc:minor edit, cla-signed

#4936 Revert "Docusaurus Faster installation"
  LICENSE
  docs/api/getting-started.md
  docs/api/organizations-management.md
  docs/integrations/amazon-aws/aws-privatelink.md
  docs/integrations/amazon-aws/global-intelligence-cloudtrail-secops.md
  docs/integrations/amazon-aws/lambda.md
  docs/integrations/app-development/jfrog-artifactory.md
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/containers-orchestration/docker-ulm.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/postgresql.md
  docs/integrations/google/workspace/collect-logs-legacy.md
  docs/integrations/google/workspace/index.md
  docs/integrations/security-threat-detection/threat-intel-quick-analysis.md
  docs/integrations/web-servers/apache.md
  docs/manage/field-extractions/create-field-extraction-rule.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/automatic-installation-script.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cybereason-source.md
  docs/send-data/opentelemetry-collector/quickstart.md
  docusaurus.config.js
  package.json
  yarn.lock
Labels: cla-signed

#4930 Add the New Action "Add Match List Items" action in Sumo Logic Cloud SIEM
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem.md
Labels: doc:update, cla-signed

#4940 Fix restrict wording
  cid-redirects.json
  docs/manage/partitions/data-tiers/faq.md
  docs/manage/partitions/flex/faq.md
Labels: doc:minor edit, cla-signed

#4938 301 and 404 fixes
  cid-redirects.json
  docs/search/index.md
Labels: cla-signed

#4939 Fix ZeroFox logo again
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zerofox-intel-source.md
  static/img/integrations/security-threat-detection/zerofox-logo.png
Labels: doc:minor edit, cla-signed

#4875 OTEL Remote Management GA
  blog-service/2025-01-08-otel-remote-management.md
  cid-redirects.json
  docs/reuse/apps/opentelemetry/collector-installation.md
  docs/reuse/apps/opentelemetry/data-configuration.md
  docs/reuse/apps/opentelemetry/logs-advance-option-otel.md
  docs/send-data/opentelemetry-collector/remote-management/index.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/include-and-exclude-rules.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/index.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/mask-rules-windows.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/mask-rules.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/metrics-include-and-exclude-rules.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/overview.md
  docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/apache/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/docker/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/kafka/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/linux/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/localfile/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/mac/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/manage-source-templates.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/nginx/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/rabbitmq/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/redis/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/syslog/index.md
  docs/send-data/opentelemetry-collector/remote-management/source-templates/windows/index.md
  sidebars.ts
  static/img/send-data/link-collectors.png
  static/img/send-data/linux-install.png
  static/img/send-data/linux-terminal-installation.png
  static/img/send-data/preview-collectors1.png
  static/img/send-data/preview-collectors2.png
  static/img/send-data/source-template.png
Labels: cla-signed

#4944 [CSOAR-2808] Docs update for HTTP Tools
  docs/platform-services/automation-service/app-central/integrations/http-tools.md
Labels: cla-signed

#4917 DOCS-617: Created doc for Jamf App
  blog-service/2025-01-10-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/jamf.md
  sidebars.ts
Labels: cla-signed

#4943 SUMO-252275: Adding monitor's information to OTEL Apps Set4
  docs/integrations/app-development/opentelemetry/jfrog-artifactory-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jira-opentelemetry.md
  docs/integrations/app-development/opentelemetry/jmx-opentelemetry.md
  docs/integrations/app-development/opentelemetry/puppet-opentelemetry.md
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/linux-opentelemetry.md
Labels: cla-signed

#4951 New doc for Symantec Endpoint Security Service
  blog-service/2025-01-10-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/symantec-endpoint-security-service.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#4949 CONN-4021: Moved CIS AWS Foundations Benchmark to V2 app
  docs/integrations/amazon-aws/cis-aws-foundations-benchmark.md
Labels: cla-signed

#4950 Update sort.md
  docs/search/search-query-language/search-operators/sort.md
Labels: cla-signed

#4952 Update .clabot
  .clabot
Labels: cla-signed

#4955 OTRM link fixes and index page improvements
  docs/send-data/opentelemetry-collector/remote-management/index.md
  docs/send-data/opentelemetry-collector/remote-management/processing-rules/index.md
Labels: cla-signed

#4954 Update doc for Jamf and Symantec Endpoint Security App
  docs/integrations/saas-cloud/jamf.md
  docs/integrations/saas-cloud/symantec-endpoint-security-service.md
Labels: cla-signed

#4947 Fixed timedelta related error in all actions
  docs/platform-services/automation-service/app-central/integrations/darktrace.md
Labels: cla-signed

#4958 Update azure-event-hubs-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/azure-event-hubs-source.md
Labels: cla-signed

#4959 Update ms-azure-event-hubs-source.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/ms-azure-event-hubs-source.md
Labels: cla-signed

#4953 Update dynamic-parsing.md
  docs/search/get-started-with-search/build-search/dynamic-parsing.md
Labels: cla-signed

#4956 Updated the doc with new warning and usageDetails field
  docs/api/search-job.md
Labels: cla-signed

#4961 Minor updates to content sharing article
  docs/manage/content-sharing/index.md
  docs/reuse/ui-elements.md
Labels: doc:minor edit, cla-signed

#4960 Update Ubuntu version in Automation Bridge
  docs/platform-services/automation-service/automation-service-bridge.md
Labels: doc:minor edit, cla-signed

#4963 CSIEM Content Notes 2025-01-14
  blog-cse/2025/01-14.md
Labels: cla-signed

#4767 macro Operator docs
  cid-redirects.json
  docs/search/search-query-language/search-operators/macro.md
  sidebars.ts
  static/img/search/searchquerylanguage/search-operators/macro-logs-page.png
  static/img/search/searchquerylanguage/search-operators/macro-search-page.png
  static/img/search/searchquerylanguage/search-operators/view-macro-logs-details.png
  static/img/search/searchquerylanguage/search-operators/view-macro-logs-page.png
Labels: cla-signed, do-not-merge

#4964 Clean up Cloud SIEM release notes format
  blog-cse/2024/12-31.md
  blog-cse/2025-01-14-content.md
  blog-csoar/2024/12-31.md
Labels: cla-signed

#4965 Update cisco-umbrella.md
  docs/integrations/saas-cloud/cisco-umbrella.md
Labels: cla-signed

#4967 301 Legacy link fixes
  cid-redirects.json
Labels: cla-signed

#4589 DOCS-232 - Personal access keys
  blog-service/2023/12-31.md
  blog-service/2025-01-16-manage.md
  docs/cse/integrations/insight-enrichment-server.md
  docs/cse/integrations/security-incident-response-integration.md
  docs/get-started/account-settings-preferences.md
  docs/get-started/index.md
  docs/get-started/sumo-logic-ui-classic.md
  docs/get-started/sumo-logic-ui.md
  docs/integrations/amazon-aws/global-intelligence-guardduty.md
  docs/integrations/amazon-aws/guardduty-benchmark.md
  docs/integrations/app-development/jfrog-xray.md
  docs/integrations/containers-orchestration/activemq.md
  docs/integrations/containers-orchestration/docker-community-edition.md
  docs/integrations/containers-orchestration/kafka.md
  docs/integrations/containers-orchestration/kubernetes.md
  docs/integrations/containers-orchestration/rabbitmq.md
  docs/integrations/databases/cassandra.md
  docs/integrations/databases/couchbase.md
  docs/integrations/databases/elasticsearch.md
  docs/integrations/databases/mariadb.md
  docs/integrations/databases/memcached.md
  docs/integrations/databases/mongodb.md
  docs/integrations/databases/mysql.md
  docs/integrations/databases/opentelemetry/couchbase-opentelemetry.md
  docs/integrations/databases/oracle.md
  docs/integrations/databases/postgresql.md
  docs/integrations/databases/redis.md
  docs/integrations/hosts-operating-systems/host-process-metrics.md
  docs/integrations/microsoft-azure/sql-server.md
  docs/integrations/web-servers/apache-tomcat.md
  docs/integrations/web-servers/apache.md
  docs/integrations/web-servers/haproxy.md
  docs/integrations/web-servers/iis-10.md
  docs/integrations/web-servers/nginx-ingress.md
  docs/integrations/web-servers/nginx-plus-ingress.md
  docs/integrations/web-servers/nginx-plus.md
  docs/integrations/web-servers/nginx.md
  docs/integrations/web-servers/squid-proxy.md
  docs/integrations/web-servers/varnish.md
  docs/manage/security/access-keys.md
  docs/manage/users-roles/roles/role-capabilities.md
  docs/observability/application-components.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/automatic-installation-script.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-cloud-siem.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-log-analytics.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications-by-gmail.md
  docs/platform-services/automation-service/app-central/integrations/sumo-logic-notifications.md
  docs/send-data/installed-collectors/collector-installation-reference/sumoconf-for-legacy-collectors.md
  static/img/get-started/acct-pref.png
  static/img/security/access-key-preferences-page.png
  static/img/security/access-key-scopes.png
  static/img/security/access-keys-deactivation.png
  static/img/security/create-access-key.png
  static/img/security/custom-scopes-detail.png
  static/img/security/custom-scopes-example.png
  static/img/security/generated-access-key.png
  static/img/security/my-access-keys1.png
  static/img/security/personal-access-keys-menu-option.png
Labels: doc:update, cla-signed, do-not-merge

#4882 DOCS-522 - Cloud SIEM troubleshooting articles
  cid-redirects.json
  docs/cse/schema/index.md
  docs/cse/schema/parser-editor.md
  docs/cse/schema/parser-troubleshooting-tips.md
  docs/cse/troubleshoot/index.md
  docs/cse/troubleshoot/troubleshoot-mappers.md
  docs/cse/troubleshoot/troubleshoot-parsers.md
  sidebars.ts
  static/img/cse/troubleshoot-parser-example.png
Labels: doc:new, cla-signed

#4968 Update automation-service-playbooks.md
  docs/platform-services/automation-service/automation-service-playbooks.md
Labels: cla-signed

#4962 Sumo Orgs Flex docs
  cid-redirects.json
  docs/manage/manage-subscription/create-manage-orgs-flex.md
  docs/manage/manage-subscription/index.md
  sidebars.ts
  static/img/manage/subscriptions/account-overview-new-flex.png
  static/img/manage/subscriptions/baselines_2-flex.png
  static/img/manage/subscriptions/child-credit-usage-flex.png
  static/img/manage/subscriptions/child-org-flex.png
  static/img/manage/subscriptions/credits-calculator-flex.png
  static/img/manage/subscriptions/view-credits-calculator-flex.png
Labels: cla-signed

#4969 SUMO-252682: Adding monitors info for otel apps - set 5
  docs/integrations/cloud-security-monitoring-analytics/opentelemetry/windows-opentelemetry.md
  docs/integrations/pci-compliance/opentelemetry/linux-opentelemetry.md
  docs/integrations/pci-compliance/opentelemetry/windows-json-opentelemetry.md
Labels: cla-signed

#4974 Update Data Volume Index doc
  docs/manage/ingestion-volume/data-volume-index/index.md
  static/img/manage/account/enable-data-volume.png
Labels: cla-signed

#4970 Macro doc update
  docs/search/search-query-language/search-operators/macro.md
Labels: cla-signed

#4971 Update tenable-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/tenable-source.md
Labels: cla-signed

#4978 Update pattern_type to stix
  docs/manage/partitions/index.md
  docs/platform-services/automation-service/app-central/integrations/dynatrace.md
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#4979 Update Cloud SIEM scheduled searches article
  docs/alerts/scheduled-searches/generate-cse-signals.md
  static/img/alerts/confirm-create.png
  static/img/alerts/create-insight.png
  static/img/alerts/full-details.png
  static/img/alerts/new-related-insight.png
  static/img/alerts/ss-signal.png
Labels: doc:update, cla-signed

#4948 CONN-4040: Updated Dragos C2C doc with new endpoint
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/index.md
  static/files/c2c/dragos/example.json
  static/files/c2c/dragos/example.tf
Labels: cla-signed, do-not-merge

#4942 Updated the Code42 doc (C2C)
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/code42-incydr-source.md
  static/files/c2c/code42-incydr/example.json
  static/files/c2c/code42-incydr/example.tf
Labels: doc:update, cla-signed, do-not-merge

#4975 Update Usage management doc
  blog-service/2025-01-23-manage.md
  docs/manage/manage-subscription/usage-management.md
  static/img/manage/account/create-scan-budget.png
  static/img/manage/account/exceed-scan-budget-warning.png
  static/img/manage/account/usage-management-advanced.png
  static/img/manage/account/view-scan-budget.png
Labels: cla-signed

#4985 CyberArk EPM Source doc update
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
  static/files/c2c/cyberark/example.json
  static/files/c2c/cyberark/example.tf
Labels: cla-signed

#4973 DOCS-610 - Update match lists
  docs/cse/match-lists-suppressed-lists/create-match-list.md
  docs/cse/match-lists-suppressed-lists/custom-match-list-columns.md
  static/img/cse/create-column.png
  static/img/cse/example-match-list.png
  static/img/cse/match-lists.png
  static/img/cse/new-match-list.png
  static/img/cse/target-column-selector.png
Labels: doc:update, cla-signed

#4988 DOCS-610 - Fix match lists docs
  docs/cse/match-lists-suppressed-lists/create-match-list.md
  docs/cse/match-lists-suppressed-lists/custom-match-list-columns.md
  docs/cse/rules/about-cse-rules.md
  static/img/cse/example-match-lists.png
Labels: doc:minor edit, cla-signed

#4989 DOCS-647 - Add target fields to threat intel article
  docs/cse/administration/create-custom-threat-intel-source.md
Labels: doc:update, cla-signed

#4990 DOCS-649 - Add note about India region
  docs/api/getting-started.md
  docs/reuse/aws-region-by-sumo-deployment.md
Labels: doc:update, cla-signed

#4991 DOCS-650 - Make screenshot bigger
  docs/manage/manage-subscription/usage-management.md
Labels: doc:minor edit, cla-signed

#4886 Updated AWSO v2.11 in docs
  docs/observability/aws/deploy-use-aws-observability/before-you-deploy.md
  docs/observability/aws/deploy-use-aws-observability/changelog.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/deploy-multiple-accounts-regions.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
  docs/observability/aws/other-configurations-tools/add-fields-to-existing-host-metrics-sources.md
Labels: cla-signed

#4982 Azure Virtual Network App
  docs/integrations/microsoft-azure/azure-virtual-network.md
  docs/integrations/microsoft-azure/network-watcher.md
  static/img/integrations/microsoft-azure/azure-virtual-network/networkflowlogs-template-deployment.png
  static/img/integrations/microsoft-azure/azure-virtual-network/virtualnetworkflowlogs.png
Labels: cla-signed

#4992 Information about collecting traces
  docs/send-data/kubernetes/troubleshoot-collection.md
Labels: cla-signed

#4987 DOCS-610 - Rule tuning expression updates
  docs/cse/get-started-with-cloud-siem/intro-for-analysts.md
  docs/cse/rules/about-cse-rules.md
  docs/cse/rules/rule-tuning-expressions.md
  static/img/cse/annotated-expression.png
  static/img/cse/enable-on-details.png
  static/img/cse/enable-on-list.png
Labels: doc:update, cla-signed

#4999 Temporarily disable threatlookup operator
  docs/platform-services/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed, hot🔥

#4998 DOCS-653 - Add rate to quantize articles
  docs/metrics/introduction/metric-quantization.md
  docs/metrics/metrics-operators/quantize.md
Labels: doc:update, cla-signed

#4997 Upgrade katex, swc, swc/core dependencies
  package.json
  yarn.lock
Labels: doc:site tech, cla-signed, dependencies

#5000 SUMO-0 Remove duplicate entries for kor deployment
  docs/integrations/amazon-aws/aws-privatelink.md
Labels: cla-signed

#4977 CSOAR- 2821: Added mentioning related fix
  docs/platform-services/automation-service/app-central/integrations/slack.md
Labels: cla-signed

#4994 VMware Workspace ONE (apps)
  blog-service/2025-01-28-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-m-z.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/vmware-workspace-one.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5003 CSIEM Content Release Notes 2025-01-28
  blog-cse/2025-01-14-content.md
  blog-cse/2025-01-28-content.md
Labels: cla-signed

#5004 Minor fix to search jobs API article
  docs/api/search-job.md
Labels: cla-signed

#5007 Update troubleshoot-collection.md
  docs/send-data/kubernetes/troubleshoot-collection.md
Labels: cla-signed

#5002 Update F5 BIG-IP Local Traffic Manager
  docs/integrations/security-threat-detection/f5-big-ip-ltm.md
Labels: doc:update, cla-signed, do-not-merge

#5006 DOCS-659 - Reorganize Cloud Infrastructure Security under "Logs for Security"
  blog-service/2023/12-31.md
  blog-service/2024/12-31.md
  cid-redirects.json
  docs/integrations/amazon-aws/index.md
  docs/integrations/product-list/product-list-a-l.md
  docs/manage/manage-subscription/fedramp-capabilities.md
  docs/reuse/cis-note.md
  docs/security/additional-security-features/cloud-infrastructure-security/cloud-infrastructure-security-for-aws.md
  docs/security/additional-security-features/cloud-infrastructure-security/index.md
  docs/security/additional-security-features/cloud-infrastructure-security/introduction-to-cloud-infrastructure-security.md
  docs/security/additional-security-features/index.md
  docs/security/additional-security-features/introduction-to-additional-security-features.md
  docs/security/index.md
  sidebars.ts
Labels: doc:update, cla-signed, do-not-merge

#5013 Fix multi-insights section
  docs/cse/get-started-with-cloud-siem/about-cse-insight-ui.md
Labels: doc:update, cla-signed

#5014 Update troubleshoot-collection.md
  docs/send-data/kubernetes/troubleshoot-collection.md
Labels: cla-signed

#5015 Add micro lesson to Copilot
  docs/search/copilot.md
Labels: cla-signed

#5016 Legacy 301 and 404 fixes
  cid-redirects.json
  docs/search/search-cheat-sheets/log-operators.md
Labels: cla-signed

#5001 Release note landing page and Guides dropdown updated
  docs/release-notes/index.md
  docusaurus.config.js
  static/img/icons/new-releases.png
Labels: cla-signed

#5022 Add Apoorvkudesia-sumologic to clabot
  .clabot
Labels: doc:minor edit, cla-signed

#5012 Update Cloudflare app
  docs/integrations/saas-cloud/cloudflare.md
Labels: doc:update, cla-signed, do-not-merge

#4993 Update flex sumo orgs doc
  blog-service/2025-01-30-manage.md
  docs/manage/manage-subscription/create-manage-orgs-flex.md
  docs/manage/manage-subscription/create-manage-orgs-service-providers.md
  docs/manage/manage-subscription/create-manage-orgs.md
  static/img/manage/subscriptions/account-overview-new-flex.png
  static/img/manage/subscriptions/child-credit-usage-flex.png
  static/img/manage/subscriptions/child-org-flex.png
Labels: cla-signed

#4984 OTRM Troubleshooting doc
  docs/send-data/opentelemetry-collector/remote-management/index.md
  docs/send-data/opentelemetry-collector/remote-management/troubleshooting.md
  sidebars.ts
Labels: cla-signed, do-not-merge

#5024 Update troubleshooting.md
  docs/send-data/opentelemetry-collector/remote-management/troubleshooting.md
Labels: cla-signed

#5021 January 2025 Release Note (Apps)
  blog-service/2025-01-31-apps.md
Labels: doc:new, cla-signed, do-not-merge

#5025 JumpCloud Directory Insights (Apps)
  blog-service/2025-02-01-apps.md
  cid-redirects.json
  docs/integrations/product-list/product-list-a-l.md
  docs/integrations/saas-cloud/index.md
  docs/integrations/saas-cloud/jumpcloud-directory-insights.md
  sidebars.ts
Labels: doc:new, cla-signed, do-not-merge

#5027 CSIEM Content 2025-01-31
  blog-cse/2025-01-31-content.md
Labels: cla-signed
