Repository SumoLogic/sumologic-documentation, pull requests merged in 2025-10, with the labels that each got.

#5851 DOCS-1156 - Add Cloud SOAR release notes for September 2025
  blog-csoar/2025-02-06-application-update.md
  blog-csoar/2025-02-24-application-update.md
  blog-csoar/2025-04-21-content.md
  blog-csoar/2025-06-03-application-update.md
  blog-csoar/2025-09-04-applicaton-update.md
  blog-csoar/2025-10-01-application-update.md
Labels: doc:new, cla-signed

#5818 DOCS-1063 - Remove article "Update on Missing IOC Fields in TAXII 2.0-Based Threat Intelligence Feeds"
  cid-redirects.json
  docs/security/threat-intelligence/notice-about-taxii2.md
Labels: doc:update, cla-signed

#5862 DOCS-1166 - Remove 'noindex' tag from "Azure Metrics Source" article
  docs/send-data/hosted-collectors/microsoft-source/azure-metrics-source.md
Labels: doc:minor edit, cla-signed

#5863 Create 2025-09-30-content.md
  blog-cse/2025-10-01-content.md
Labels: cla-signed

#5870 Create 2025-10-01-saml.md
  blog-service/2025-10-01-manage.md
Labels: cla-signed

#5869 Update C2C Duo source with current docs
  docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/duo-source.md
  static/files/c2c/duo/example.json
  static/files/c2c/duo/example.tf
Labels: cla-signed

#5812 Docs update for Otel CDN
  blog-collector/2025-10-03-otel.md
  docs/integrations/hosts-operating-systems/opentelemetry/linux-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/macos-opentelemetry.md
  docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
  docs/send-data/opentelemetry-collector/install-collector/linux.md
  docs/send-data/opentelemetry-collector/install-collector/macos.md
  docs/send-data/opentelemetry-collector/install-collector/windows.md
  static/img/send-data/opentelemetry-collector/linux-install-command.png
  static/img/send-data/opentelemetry-collector/linux-install-ui.png
  static/img/send-data/opentelemetry-collector/macos-install-command.png
  static/img/send-data/opentelemetry-collector/macos-install-ui.png
  static/img/send-data/opentelemetry-collector/windows-install-command.png
  static/img/send-data/opentelemetry-collector/windows-install-ui.png
Labels: doc:update, cla-signed, do-not-merge

#5872 Update dashboard-child-orgs.md
  docs/dashboards/dashboard-child-orgs.md
Labels: cla-signed

#5868 update Pantheon workflows
  .github/workflows/deploy-to-pantheon.yml
  .github/workflows/job_build-site.yml
  .github/workflows/job_pantheon.yml
  .github/workflows/job_slack-notification.yml
  .github/workflows/job_trigger-jenkins-pipeline.yml
  .github/workflows/workflow_deploy-to-pantheon-prod.yml
  .github/workflows/workflow_deploy-to-pantheon-staging.yml
Labels: cla-signed

#5864 Unify deployment codes and AWS region mapping
  docs/api/about-apis/getting-started.md
  docs/api/aws-region-by-deployment.md
  docs/get-started/faq.md
  docs/reuse/aws-region-by-sumo-deployment.md
Labels: cla-signed, do-not-merge

#5624 Update index.md
  docs/search/get-started-with-search/search-page/field-browser/index.md
Labels: cla-signed

#5841 Changes for full vnet integration of data collected through block blo…
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/block-blob/collect-logs.md
  docs/send-data/collect-from-other-data-sources/azure-blob-storage/block-blob/full-vnet-integration.md
  docs/send-data/collect-from-other-data-sources/azure-monitoring/arm-integration-faq.md
  sidebars.ts
  static/img/send-data/AzureBlob_EventSubscriptionsPage.png
  static/img/send-data/AzureBlob_SelectEventHub-EventGrid.png
  static/img/send-data/blockblob/block-blob-NSG-rules.png
  static/img/send-data/blockblob/block-blob-arm-template-sa-networking.png
  static/img/send-data/blockblob/block-blob-event-hub-namespace-add-identity.png
  static/img/send-data/blockblob/block-blob-event-hub-networking.png
  static/img/send-data/blockblob/block-blob-event-hub-subscription-identity.png
  static/img/send-data/blockblob/block-blob-function-networking-config.png
  static/img/send-data/blockblob/block-blob-sa-flow-logs-networking.png
  static/img/send-data/blockblob/block-blob-service-endpoint-enabling-vnet.png
  static/img/send-data/blockblob/block-blob-system-assigned-identity-topic.png
  static/img/send-data/blockblob/block-blob-task-consumer-with-vnet-integration-inbound.png
  static/img/send-data/blockblob/block-blob-task-consumer-with-vnet-integration-outbound.png
  static/img/send-data/blockblob/block-blob-validation.png
  static/img/send-data/blockblob/block-blob-vnet-creation.png
  static/img/send-data/blockblob/block-blob-vnet-in-task-consumer.png
  static/img/send-data/blockblob/block-setting-env-variable-function.png
Labels: cla-signed

#5866 DOCS-1098 - Docs templates - standardize app/source intros with Sumo Logic naming
  docs/contributing/style-guide.md
  docs/contributing/templates/app-template-v2.md
  docs/contributing/templates/c2c-source.md
Labels: cla-signed

#5867 DOCS-1169 - Clarify using threat intelligence indicators in log search
  docs/security/threat-intelligence/find-threats.md
  docs/security/threat-intelligence/threat-intelligence-indicators.md
Labels: doc:minor edit, cla-signed

#5880 Revert "DOCS-1159 - Mobot limitation - handling query outputs"
  cid-redirects.json
  docs/search/mobot-multiturn-beta.md
Labels: cla-signed

#5879 DOCS-1176 - Add CID redirect for deprecated standalone API AWS Region endpoints
  cid-redirects.json
Labels: cla-signed

#5770 DOCS-1110 - Training/Cert FAQ GA (est. Oct 6)
  cid-redirects.json
  docs/get-started/account-settings-preferences.md
  docs/get-started/apps-integrations.md
  docs/get-started/keyboard-shortcuts.md
  docs/get-started/library.md
  docs/get-started/onboarding-checklists.md
  docs/get-started/quickstart.md
  docs/get-started/sign-up.md
  docs/get-started/system-requirements.md
  docs/get-started/training-certification-faq-new.md
  docs/get-started/training-certification-faq.md
  sidebars.ts
  src/css/sumo.scss
  static/img/get-started/certifications.png
  static/img/get-started/credentials.gif
  static/img/get-started/error.png
  static/img/get-started/lab-credentials.png
  static/img/get-started/learning-hub.png
  static/img/get-started/sumo-academy-dark-mode.png
  static/img/get-started/sumo-academy-light-mode.png
Labels: cla-signed, do-not-merge

#5875 Minor edit on the Sept release note for apps
  blog-service/2025-09-30-apps.md
Labels: cla-signed

#5687 Deprecating GIS for cloudtrail devops
  blog-service/2021/12-31.md
  cid-redirects.json
  docs/integrations/account-plans.md
  docs/integrations/amazon-aws/global-intelligence-cloudtrail-devops.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/global-intelligence/index.md
  docs/integrations/product-list/product-list-a-l.md
  docs/observability/aws/about.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/view-dashboards.md
  docs/observability/aws/integrations/global-intelligence-cloudtrail-devops.md
  docs/observability/aws/integrations/index.md
  docs/observability/diagnose-issues.md
  sidebars.ts
Labels: cla-signed

#5771 AWSO 2.13.0 doc
  docs/observability/aws/deploy-use-aws-observability/deploy-with-aws-cloudformation/index.md
  docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
Labels: cla-signed

#5691 Ingestion Throttling Limits (Scan Budgets update)
  blog-service/2024/12-31.md
  blog-service/2025-01-23-manage.md
  blog-service/2025-10-08-manage.md
  cid-redirects.json
  docs/api/scan-budget.md
  docs/manage/manage-subscription/index.md
  docs/manage/manage-subscription/organization-usage-limits.md
  docs/manage/manage-subscription/scan-budgets.md
  docs/manage/manage-subscription/sumo-logic-flex-accounts.md
  sidebars.ts
  static/img/get-started/enable-ingestion-throttling-notifications.png
  static/img/manage/account/organization-usage-limits.png
  static/img/manage/account/scan-budget-advanced.png
  static/img/manage/account/usage-management-advanced.png
  static/img/manage/account/usage-management.png
Labels: cla-signed, do-not-merge

#5887 Reinstated doc for GIS Cloudtrail DevOps app
  cid-redirects.json
  docs/integrations/account-plans.md
  docs/integrations/amazon-aws/global-intelligence-cloudtrail-devops.md
  docs/integrations/amazon-aws/index.md
  docs/integrations/global-intelligence/index.md
  docs/integrations/product-list/product-list-a-l.md
  package.json
  sidebars.ts
  yarn.lock
Labels: cla-signed

#5890 Test fix for hub page links
  docs/get-started/index.md
Labels: doc:minor edit, cla-signed
